### ISSUE TITLE
[Updating version] Lost all albums and photos after update

### ISSUE THREAD

**Issue by vuongquoc** [LycheeOrg/Lychee#1002]
I'm using godaddy shared host and everytime i update, i use manual update instruction.

-----

Update manually
This update will be the one you have to use if you are following the Release channel.

1. Download the newest Version
2. Replace all existing files, excluding uploads/ and dist/user.css
3. Go into the Diagnostic page and click on the Apply migration button.

-----

I've done as instructed but after uploading all the files and refresh my site to update, it go straight to installing pages that i need to verify my database...
after that, i have a blank new site (no albums, no photos)...

Did i do wrong somewhere or i missed something?

**Comment by ildyria** [comment]
Are you using sqlite or mysql ?
What does your diagnostic page says?

**Comment by vuongquoc** [comment]
It seem i'm using SQlite.
-----
System Information
    --------------
    Lychee Version (release):        4.3.0
    DB Version:                      4.3.0
    
    composer install:                --no-dev
    APP_ENV:                         production
    APP_DEBUG:                       false
    
    System:                          Linux
    PHP Version:                     7.4
    Max uploaded file size:          128M
    Max post size:                   128M
    SQLite Version:                  3.26.0
    
    Imagick:                         1
    Imagick Active:                  1
    Imagick Version:                 1802
    GD Version:                      2.2.5
-----
This is the info that currently in my dianostic.

But when i update, after uploaded all the files, and refresh diagnostic page, it transfered me to the installing pages that tell me check and update database info if changed.
I did not change anything so i just process and boom! everything is blank!

I'm uploading my pictures again but if there are any new update, may it happens again! 

I thought it would updates and migrates all albums and pictures... but no... even it still saved in the uploads folder but do not recognized.

**Comment by ildyria** [comment]
```
SQLite Version:                  3.26.0
```

Okay, I see what is happening. First of all, sorry that you lost your database. We don't have many user on the sqlite database solution, so nobody complained about this issue over the last 2 years.

The solution to avoid this problem in the future is actually pretty simple. For the next time **do not overwrite** `database/database.sqlite` as this is the content of the database.

**TODO:** Add this line info the documentation.

**Comment by ildyria** [comment]
File to update: https://github.com/LycheeOrg/LycheeOrg.github.io/blob/master/docs/md/update.md

**Comment by d7415** [comment]
> We don't have many user on the sqlite database solution

I'm actually curious whether we have more on sqlite or without shell access. Either way, very few on that combination!

**Comment by vuongquoc** [comment]
Thank you for your kind support!
Hope this one helps others too!
Lychee is the best suitable for me.
