### ISSUE TITLE
Sharing two albums with other user in the system shares only one album

### ISSUE THREAD

**Issue by elvisef** [LycheeOrg/Lychee#1004]
Firstly, A user was created earlier (some time ago, month, two or more).
So today I've just set two albums as shared with password for this specific user.

The effect is that only one of these (two sahred) albums is visible for this specific user.
I've fetched and pulled git updates (git fetch -a and git pull - being on master branch) but the problem still exists, because I've tested it again, by re-sharing image resources (images).

PS. I don't know if this should look this way, but the user sees album in a parent album - wouldn't be better to show only the last level albums forr additional users ?

**Comment by ildyria** [comment]
> PS. I don't know if this should look this way, but the user sees album in a parent album - wouldn't be better to show only the last level albums for additional users ?

I assume you mean the following structure:
```
+
|
+-+ A
  |
  +- B
```
and if you share A to a user, you expect B to be shared too?
No, at the moment we do not do the propagation. We have a "deny by default" policy as it is easier ​to
manage a *allowed* list rather than an *allowed & deny thoses* list.


However, it could be thought on album creation to inherit the properties of the parent...

**Comment by kamil4** [comment]
Could you provide more details? How about screenshots of the sharing and visibility settings for those two albums?

**Comment by elvisef** [comment]
> > PS. I don't know if this should look this way, but the user sees album in a parent album - wouldn't be better to show only the last level albums for additional users ?
> 
> I assume you mean the following structure:
> 
> ```
> +
> |
> +-+ A
>   |
>   +- B
> ```
> 
> and if you share A to a user, you expect B to be shared too?
> No, at the moment we do not do the propagation. We have a "deny by default" policy as it is easier ​to
> manage a _allowed_ list rather than an _allowed & deny thoses_ list.
> 
> However, it could be thought on album creation to inherit the properties of the parent...

For now (looking at Your "graphical" sample) I shared B for a user, and the user doesn't see B, because A is not shared with him. I think that's a problem, because B is a child of A. So if the user does not see B, he/she will not see anything what is a child of A. But If I will share a whole A to a user, the user will see B. 

A user should be able to make visible any gallery he/she needs : )
So, If I had for instance A as a parent, B as a child of A and..... so on... till Z, so Z will be a child of Y, I will need to share all of parent albums in order to make user see the last level gallery ?

I think as a user I should be able to select specific album to be shared regardless of the parent levels.
But if this is not the way it should work, You can close the issue : )
