### ISSUE TITLE
[Enhancement] Allow Cross-Origin loading

### ISSUE THREAD

**Issue by jcyrio** [LycheeOrg/Lychee#1006]
I am trying to embed an image gallery in a cross-origin iframe. I installed and tested 8 different open-source image galleries on the same server, and Lychee is the only one that I'm not able to get to load inside the cross-origin iframe. Lychee is my favorite of all the other galleries, so that's why I'd like to get it to work.

I'm getting an "Uncaught DOMException: Blocked a frame with origin "https://<URL>" from accessing a cross-origin frame at Function.get (https://<URL>/gallery/public/dist/main.js?161878522:181:16752)".

Since all of the other image galleries are working for me Cross-Origin on the same 2 hosts, I'm assuming my apache settings are correct. Do you know if there's anything I could do (maybe to the Lychee code) to get Lychee to work like this?

**Comment by ildyria** [comment]
Yes, have a look here:
https://github.com/LycheeOrg/Lychee/blob/master/config/secure-headers.php

**Comment by jcyrio** [comment]
Thank you for responding. I had actually tried to modify that file, using many different combinations, but was unsuccessful.

Could you please help me figure out which directives have to be modified in that file?

These are the ones I'm using now, and it's still not working:
```
'x-frame-options' => 'allow-from https://this-is-the-url-that-is-hosting-the-iframe.com/mygallery/',

'x-permitted-cross-domain-policies' => 'all',

'x-xss-protection' => '0',

'referrer-policy' => 'unsafe-url',
```

**Comment by ildyria** [comment]
Just to make sure, can you try:
```
php artisan config:clear
```

But I do agree with you, this should already work. :thinking:

**Comment by d7415** [comment]
Apparently allow-from doesn't work any more (from [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options), linked in the file). It's possible commenting it out might work, but I think the general message they're sending about cross origin frames is "don't".

**Comment by ildyria** [comment]
> **ALLOW-FROM uri** 
> This is an obsolete directive that no longer works in modern browsers. Don't use it. In supporting legacy browsers, a page can be displayed in a frame only on the specified origin uri. Note that in the legacy Firefox implementation this still suffered from the same problem as SAMEORIGIN did — it doesn't check the frame ancestors to see if they are in the same origin. The Content-Security-Policy HTTP header has a frame-ancestors directive which you can use instead.

I guess it is time to update the config file then. :confused:

**Comment by d7415** [comment]
> I guess it is time to update the config file then

Already done.

**Comment by jcyrio** [comment]
> Just to make sure, can you try:
> 
> ```
> php artisan config:clear
> ```
> 
> But I do agree with you, this should already work. 🤔

I ran this command successfully, but am getting the same "Uncaught DOMException: Permission denied to access property "document" on cross-origin object" errors.

What about the possibility of adding some JS/Ajax code, like in the example here: https://reload.dk/blog/lab/how-get-around-same-origin-problem-iframes
That page links to the following as an example for embedding a Vimeo player: https://codepen.io/rasben/pen/XNoXjp

**Comment by jcyrio** [comment]
Also, just to describe the purpose of such an endeavor:
I'm hosting a site on Shopify, on which I would like to have an image gallery. All of their image gallery apps/plugins would cost around $6-$10 per month, for something that can easily be done for free with open-source galleries on a regular webserver.

I'm able to embed an iframe inside the Shopify site, and load an external image gallery inside the iframe. It actually looks good, and I'm happy with the solution. Even though I've gotten many image galleries to load successfully cross-origin like this, I'd really like to get Lychee to work like this because I think it's the prettiest by far.

**Comment by d7415** [comment]
> Apparently allow-from doesn't work any more (from [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options), linked in the file). It's possible commenting it out might work, but I think the general message they're sending about cross origin frames is "don't".

Did you try this?

**Comment by jcyrio** [comment]
> > Apparently allow-from doesn't work any more (from [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options), linked in the file). It's possible commenting it out might work, but I think the general message they're sending about cross origin frames is "don't".
> 
> Did you try this?

I just tried commenting this line out. It still doesn't work.

**Comment by ildyria** [comment]
CSP problems. Out of scope.
