### ISSUE TITLE
Wrong context menu shown for restricted users

### ISSUE THREAD

**Issue by clix10** [LycheeOrg/Lychee#1007]
### Detailed description of the problem [REQUIRED]
For users with restricted account, wrong context menues are shown, when they click on the top rigth plus. When they go into one of the albums and back to the root of the gallery, even more wrong contex menu is show if they click on the plus in the corner.
I believe, both of them are wrong, even the small one has options that are not applicable to the restricted user. If user clicks on the options, the error, as shown below appears. He is not allowed to do any of the things, but menu shows them.

### Steps to reproduce the issue
1. log in as a user with restricted account, without upload rights
2. click on the plus on the top right corner
3. context menu is shown:
![lesar-acc_takoj_po_prijavi](https://user-images.githubusercontent.com/21221821/118358410-e9ec0d00-b57e-11eb-8c57-dad829a77b40.jpg)
4. click away from the content menu, so the menu closes
5. click on album, and the album opens
6. click on the arrow on the top left corner, to go back to the root of the gallery
7. click again on the plus on the top right corner
8. the next context menu is shown:
![lesar-acc_ko-gremo-v-en-album-in-potem-ven](https://user-images.githubusercontent.com/21221821/118358483-43ecd280-b57f-11eb-891b-902deb3b064b.jpg)
9. if the user clicks on the "New Album" and than create album, he is greeted with the error:
![error](https://user-images.githubusercontent.com/21221821/118358578-bc539380-b57f-11eb-8cde-e6c1b0d7afec.jpg)
10. Gallery doesn't allow user to do things, but they are still shown on the menu

### Output of the diagnostics  [REQUIRED]
    Diagnostics
    -----------
    Warning: Dropbox import not working. dropbox_key is empty.
    Warning: You may experience problems when uploading a photo of large size. Take a look in the FAQ for details.

    System Information
    ------------------
    Lychee Version (git):            No git data found.
    DB Version:                      4.3.0
    
    composer install:                --no-dev
    APP_ENV:                         production
    APP_DEBUG:                       false
    
    System:                          Linux
    PHP Version:                     7.4
    Max uploaded file size:          20M
    Max post size:                   100M
    MySQL Version:                   10.5.10-MariaDB-1:10.5.10+maria~focal
    
    Imagick:                         1
    Imagick Active:                  1
    Imagick Version:                 1691
    GD Version:                      2.3.0

    Config Information
    ------------------
    version:                         040300
    check_for_updates:               0
    sorting_Photos_col:              takestamp
    sorting_Photos_order:            ASC
    sorting_Albums_col:              max_takestamp
    sorting_Albums_order:            DESC
    imagick:                         1
    skip_duplicates:                 0
    small_max_width:                 0
    small_max_height:                360
    medium_max_width:                1920
    medium_max_height:               1080
    lang:                            en
    layout:                          1
    image_overlay_type:              none
    default_license:                 none
    compression_quality:             90
    full_photo:                      1
    delete_imported:                 0
    Mod_Frame:                       1
    Mod_Frame_refresh:               30
    thumb_2x:                        0
    small_2x:                        0
    medium_2x:                       0
    landing_page_enable:             0
    landing_owner:                   
    landing_title:                   
    landing_subtitle:                
    landing_facebook:                https://www.facebook.com/
    landing_flickr:                  https://www.flickr.com/
    landing_twitter:                 https://www.twitter.com/
    landing_instagram:               https://instagram.com/
    landing_youtube:                 https://www.youtube.com/
    landing_background:              dist/cat.jpg
    site_title:                      
    site_copyright_enable:           0
    site_copyright_begin:            2007
    site_copyright_end:              2021
    additional_footer_text:          
    display_social_in_gallery:       0
    public_search:                   0
    SL_enable:                       0
    SL_for_admin:                    0
    public_recent:                   0
    recent_age:                      1
    public_starred:                  0
    downloadable:                    1
    photos_wraparound:               1
    map_display:                     0
    zip64:                           1
    map_display_public:              0
    map_provider:                    Wikimedia
    force_32bit_ids:                 0
    map_include_subalbums:           0
    update_check_every_days:         3
    has_exiftool:                    1
    share_button_visible:            0
    import_via_symlink:              1
    has_ffmpeg:                      1
    location_decoding:               0
    location_decoding_timeout:       30
    location_show:                   0
    location_show_public:            0
    rss_enable:                      0
    rss_recent_days:                 7
    rss_max_items:                   100
    prefer_available_xmp_metadata:   0
    editor_enabled:                  0
    lossless_optimization:           0
    swipe_tolerance_x:               45
    swipe_tolerance_y:               200
    local_takestamp_video_formats:   .avi|.mov
    log_max_num_line:                1000
    unlock_password_photos_with_url_param: 0
    nsfw_visible:                    0
    nsfw_blur:                       0
    nsfw_warning:                    0
    nsfw_warning_admin:              0
    map_display_direction:           1
    album_subtitle_type:             oldstyle
    upload_processing_limit:         4
    public_photos_hidden:            1

### Browser and system

Tested on windows 10, with Chrome and Edge.
Gallery is running from the official docker image on Ubuntu server.

**Comment by ildyria** [comment]
> if the user clicks on the "New Album" and than create album, he is greeted with the error:

Yes, because server-side we check if they are actually allowed to do the action. :wink: 
And as they are not, the server just, return `"false"` (but I do agree the API should be improved on that regard).

**Comment by ildyria** [comment]
@kamil4 what is the status of that one?
Did the change you made on the front fix it?

**Comment by kamil4** [comment]
It's partially fixed. Specifically, the second problem (from step number 8) is fixed. I wasn't aware of the first problem (step number 3). Let's keep this one open for now...

**Comment by kamil4** [comment]
Closing; the remaining part was fixed in https://github.com/LycheeOrg/Lychee-front/pull/283
