### ISSUE TITLE
php_max_size limit is to small

### ISSUE THREAD

**Issue by ghost** [LycheeOrg/Lychee#1010]
I am having problems with uploading jpeg photos > 2Mb.
To solve the problem I have, as suggested in your documentation, adjusted the following files:
php.ini (no result), .user.ini (no result), the .conf file of nginx (no result).
Every time I try to upload a file I get the message: The php_max_size limit is too small.
I installed Lychee from Github (not with Docker) , with php7.4, Nginx and sqlite.
What else can I do? Is there a work around?

**Comment by nagmat84** [comment]
Which `php.ini` file did you adjust? Please note that there are three variants of this file for a typical installation (one for PHP for running from the CLi, one for the PHP Apache plugin and one for (F)CGI/FPM). Are you sure you edited the right one?

If PHP is running in it's own process (i.e. as CGI or FPM), did you restart that process?

**Comment by ghost** [comment]
I have adjusted `/etc/php/7.4/cli/php.ini` and `/etc/php/7.4/fpm/php.ini`  in post_max_size = 200M. 
However I have adjusted the .conf of NGINX. Added 
 `fastcgi_param PHP VALUE "post_max_size=100M";`
And restart NGINX (`service nginx restart` )and even my whole computer.
Same result.

**Comment by nagmat84** [comment]
What is the output of `phpinfo();` if delivered through your webserver? Unfortunately, I have never used ngnix myself (only Apache) so I cannot help much with administration.

Please also note, that there are two different options to be configured: `post_max_size` and `upload_max_filesize`. Both must be set large enough. Also note that other parameters might need tweaking, too, for example the memory limit which might be used by PHP in order to be able to keep large files in memory. See the PHP docs of those two parameters for further background information.

**Comment by ildyria** [comment]
> What is the output of `phpinfo();`

Note that if you log as admin, you can do https://yoursite.org/phpinfo to see it.

**Comment by PeterB513** [comment]
[PHP 7.4.3 - phpinfo().pdf](https://github.com/LycheeOrg/Lychee/files/6492606/PHP.7.4.3.-.phpinfo.pdf)

**Comment by nagmat84** [comment]
As I pointed out three posts ealier, the setting for `upload_max_filesize` is still 20MB. You must fix both settings: `post_max_size` **and** `upload_max_filesize`

**Comment by ghost** [comment]
[Diagnostics.pdf](https://github.com/LycheeOrg/Lychee/files/6493436/Diagnostics.pdf)
Adjusted according to your suggestion. See attached Diagnostics. Unfortunate the result is the same.

**Comment by nagmat84** [comment]
I believe you forgot to re-post the attachment which shows your new values. Also re-post the new output of `phpinfo` after you re-configured the values. It is not necessary to post the whole output of phpinfo as a PDF, all attributes which have "max", "memory", "size" and/or "upload" in their name should be enough.

**Comment by d7415** [comment]
Also, what is your nginx `client_max_body_size`?

**Comment by ghost** [comment]
I think I found something. I tried to upload photos directly (option Upload Photo) with a cable from my Ipad. Obviously  this has a limit in filesize. So I put some photos on a usb stick and selected the Import from Server option. Selected the path of the usb and voila this worked. Also with a big file size.

**Comment by netuseradministrator** [comment]
> I think I found something. I tried to upload photos directly (option Upload Photo) with a cable from my Ipad. Obviously this has a limit in filesize. So I put some photos on a usb stick and selected the Import from Server option. Selected the path of the usb and voila this worked. Also with a big file size.

hey,i wanna make it clear.What is the difference between ipad uploading and pc browser uploading.Why i can upload correctly on pc,but failed on uploading same picture on my ipad

**Comment by netuseradministrator** [comment]
> I think I found something. I tried to upload photos directly (option Upload Photo) with a cable from my Ipad. Obviously this has a limit in filesize. So I put some photos on a usb stick and selected the Import from Server option. Selected the path of the usb and voila this worked. Also with a big file size.

hey,i wanna figure it out.What is the difference between ipad uploading and pc browser uploading.Why i can upload correctly on pc,but failed on uploading same picture on my ipad.

**Comment by nagmat84** [comment]
For Lychee it makes no difference whether you upload the image via a browser from a PC or from an iPad. In both cases it is just uploading via a browser. If you experience any difference, then this must have a client-side reason.

**Comment by netuseradministrator** [comment]
> For Lychee it makes no difference whether you upload the image via a browser from a PC or from an iPad. In both cases it is just uploading via a browser. If you experience any difference, then this must have a client-side reason.

but i still cant understand why i am able to upload same picture on my computer browser ,but i can upload it on my ipad Safari

**Comment by nagmat84** [comment]
What is the error message do you get? And does it only affects some pictures or all pictures?

**Comment by netuseradministrator** [comment]
> What is the error message do you get?

"post_max_size too small" in chinese

**Comment by netuseradministrator** [comment]
![image](https://user-images.githubusercontent.com/96680088/164900451-75ce4a56-eed2-40e5-8976-59508f885e0f.png)
![image](https://user-images.githubusercontent.com/96680088/164900961-4cffd56e-e489-4225-86ad-45f003f88ea7.png)

**Comment by netuseradministrator** [comment]
it's weired

**Comment by nagmat84** [comment]
Well this error message is rather obvious. Your server-side PHP settings for `post_max_size` are too small, resp. the picture is too large. If you want to upload that picture adjust `post_max_size` to a higher value. See https://lycheeorg.github.io/docs/faq.html#i-cant-upload-large-photos in the docs.

But this should give identical results on the PC and iPad as the problem is with the particular photo.

**Comment by netuseradministrator** [comment]
sorry,i forget the nginx option (client_max_body_size )

**Comment by nagmat84** [comment]
Which still should not make a difference between a PC and an iPad. But I am glad that you figured it out.

**Comment by netuseradministrator** [comment]
LOL,now i figure it out why.Because i send same picture from ipad to my PC in Wechat,Wechat compressed image quality，so i can post same picture on PC browser,it's my mistake.
