### ISSUE TITLE
[Enhancement] Notifying user of new uploads

### ISSUE THREAD

**Issue by pokemonbattledroid** [LycheeOrg/Lychee#1011]
I looked around but couldn't find anything regarding this.  Is there a way to implement a feature where if a shared album gets new photos/videos, it automatically emails the user to say there is new content?

**Comment by ildyria** [comment]
Sure there is for sure a way to implement it. The question is more "_Is there someone to do it?_" :confused: We are kinda short staffed here but we do accept contributions [read more here](https://lycheeorg.github.io/docs/contributions.html).

Note this also would require users to add their mails address etc. (while right now we only store their username & password). So adding such a functionality would also be a significant refactoring also in the User section to add the mail management.

**Comment by d7415** [comment]
If adding email notifications it might make sense to at least consider push notifications at the same time. Even if it's just generic webhook support which many of them support.

Other thoughts to consider:
- Should pictures imported from the CLI be included
- Should there be a notification for every photo? Or grouped together somehow? Or a cooldown between notifications?

**Comment by pokemonbattledroid** [comment]
I wish I could contribute, but instead I'm just a user and it seems like I posted a question without any regard for the complexity around personal information, security, etc.  Sorry!!

I like the ideas though and notifications!

**Comment by ildyria** [comment]
>  it seems like I posted a question without any regard for the complexity around personal information, security

Indeed the mail address is personal data and would also require us to add a GDPR warning.
This link actually highlight the unexpected added complexity of such request :sweat_smile: :
https://www.litmus.com/blog/5-things-you-must-know-about-email-consent-under-gdpr/
