### ISSUE TITLE
Current state of Lychee-Laravel

### ISSUE THREAD

**Issue by guzzisti** [LycheeOrg/Lychee#102]
Not an issue but more of a question:
What is the current state of Lychee-Laravel?

Lychee-Laravel is often referred to when talking about issues/requests to the the Lychee V3 implementation. The official Lychee website (https://lycheeorg.github.io) still links to Lychee V3 as the current version.
So i'm curios what is the current state of Lychee V4? Is it production ready? Is there a timeline to get it production ready? Are you heading for feature equality to Lychee V3 before releasing it (from what i read so far: i guess not :) )?

I found issue https://github.com/LycheeOrg/Lychee/issues/18 that provides some information about why a new backend implementation seems useful.

**Comment by ildyria** [comment]
Lychee-Laravel aims to be Lychee v4. It's current status is Alpha/Beta.
Yes it is somewhat production ready in the sense that I'm using it with about 4000 pictures on my personal server.

As for the timeline, there is not really any. We need to fix a few more things: https://github.com/LycheeOrg/Lychee-Laravel/milestone/1
before actually releasing it. @SerenaButler is doing a great job as pointing current bugs. :smile: 

I would really like to see it go live on April 1st but there is no real pressure for when it will be ready.

> Are you heading for feature equality to Lychee V3 before releasing it?

No. Lychee v4 should cover what Lychee v3 has and add other features such as sub albums, multi users, landing page...

**Comment by psjbeisler** [comment]
great to hear it can be used already in that compacity, my only question now is what is the state of Postgresql. I know it was an issue before Larvel, but can it be recommended for use now?

**Comment by ildyria** [comment]
@psjbeisler Lychee-Laravel should be perfectly fine with Postgresql.

maybe worth reading: https://stackoverflow.com/questions/30480385/laravel-5-with-postgres-sql

**Comment by psjbeisler** [comment]
just curious too, but what is the plan for v3 + v4 going forward, will they be kept as separate repos or is the expectation that Lychee-Laravel maybe gets merged or at least deprecates Lychee v3 all together? 
Sorry is i missed this somewhere else, but being that this is a pinned issue for such a topic...

**Comment by ildyria** [comment]
Naah, it is nice that you actually reuse this issue, it helps to centralize the questions on the status. :smiley: 

And no, the answers to your questions are not anywhere yet. :+1: 

To be honest we don't really know yet how we are going to handle the change from v3 to v4. It is still in discussion in the team: do we want to merge the repo? do we just rename each repo? do we provide a script to migrate? Do we rename lychee-v3 into lychee-legacy and just do basic support on it (a bit like a LTS)? There are still a lot of answered questions.

There are also some concerns such as the fact the installation process is slightly more complex: you do not need to drag and drop Lychee release for it to work, you need to make your host point at public, you need to do migration yourself (`php artisan migrate`) etc... Having a single install script (sh? php?) would be nice.

However one thing is for sure. We will not add more feature to the v3. We may do some rare backports but all the new stuff are going to this repo. :)

**Comment by jprokop1** [comment]
After some time playing with Lychee-Laravel I have some suggestions for improvement:
- option to set up repository for data to separates volume/disk; idea behind is to run system/database (which is not so big) on SSD disk, but pictures/videos on big/cheap HDDs
although it is possible to do with symlinks, user defined setting in .env (default public/upload) would be cleaner (something similar #149)
- option to change album name is on two places - "Rename" in Album's directory and set Title in "About"; my suggestion is instead "Rename" to place a link to album's root in album's directory
![image](https://user-images.githubusercontent.com/46556236/56098258-ea78cc00-5efe-11e9-89f6-bceef4080616.png)

- searching possibility not only on album's root, but in each album
- after longer inactivity is no automatic logout, but only an error message (API not found) - in this case would be better redirect to login mask

**Comment by kamil4** [comment]
@jprokop1 Here's my take on your suggestions:

- Separate database and pictures/videos. In a way, I thought we already do? The pictures/videos are in `public/uploads/` but the location of the database is not specified by Lychee (on my system it ends up in `/var/lib/mysql/`, I believe). With respect to `public/uploads/`, have you tried editing `Lychee-Laravel/config/defines.php`? I think that may do what you want...

- Rename in two places. It's actually in three places, because you can also right-click on a thumb of an album and invoke Rename from the context menu that pops up :smile:. But is that a problem? I do agree with your other suggestion to add a link to album's root (it's actually called "albums view" in internal Lychee nomenclature) to that pop-down menu though.

- Searching. I have no opinion on your suggestion, but your mention did trigger a lingering question that I have: do people actually want to use the Search feature at all and do they find it useful? I'm asking because I fixed several glaring bugs in it over the weekend (such as the wrong photo layout, or it not working at all with v4 for the last few days) and since I haven't seen much complaining about such problems, I wonder if people care about this feature and thus, is fixing it the best use of our time?

- Inactivity timeout. We are already tracking this issue under #100 (you will see that there's a bit of a disagreement about it). I have an experimental patch that does what you suggest, but it's fragile (it stops working when `APP_DEBUG` is set to `false` in `.env`). It looks like we need support on the server side to make it work reliably but nobody stepped up with a patch so far...

**Comment by jprokop1** [comment]
@kamil4: thank you for the quick reply
- config/defines.php is exactly what I want! I overlooked it.
- with multiple renaming I have no problem, the link is important, thanks for realisation
- the possibility of searching in photo documentation by tag to find relevant images is crucial to me. 
There is no need to search by multiple criteria, but rather the ability to enter searches in albums and sub-albums - make the search in the mask available.
But if there is a direct link to albums view, it is sufficient for me
There are other suggestions - eg. watermark for public images, but you're right, it's only relevant if more people are interested.

**Comment by scratcher28** [comment]
@ildyria, @kamil4, why have you decided to hardcode all url/dir paths? It seems very strange to me. Can't get it... :/

**Comment by d7415** [comment]
> @ildyria, @kamil4, why have you decided to hardcode all url/dir paths? It seems very strange to me. Can't get it... :/

Did you read the post above yours...?

**Comment by scratcher28** [comment]
Instead of getting url/dir paths from config/defines.php (as it used to be), you now switched to hardcoded paths and getting them by calling Storage::path('small/'...), etc, which is ugly, imho, for 2 reasons:
1) I can't now easily rename those paths in one place (defines.php) and need to modify a lot of source code files, that makes harder to upgrade Lychee later;
2) Earlier I COULD have different locations/storages for (small/thumb/medium/big/import), and now only one (e.g. uploads/*).

**Comment by d7415** [comment]
Ok, my bad.

I think this was to allow the use of S3 and other storage backends.

What are you actually trying to achieve?

**Comment by scratcher28** [comment]
1) hardcoding paths is a bad idea;
2) keep ability to separate them to different storages/disks, for example: small/thumb/medium (SSD) and import/big (HDD).

**Comment by d7415** [comment]
>     1. hardcoding paths is a bad idea;

We're only hardcoding one level of the path.

>     2. keep ability to separate them to different storages/disks, for example: small/thumb/medium (SSD) and import/big (HDD).

Have you considered symlinks? Or, if you're feeling fancy, a bind mount?

**Comment by psjbeisler** [comment]
since we're on the second beta at this point, has there been any more thought to the v3 > v4 transition?

**Comment by jeyca** [comment]
I lost track about the different lychee forks and versions and I am confused which is the actual project. Is it lychee-laravel oder https://github.com/LycheeOrg/Lychee ? Are both still developed? Why is the Link on https://lychee.electerious.com still pointed to the very old repository and how is everything connected or not connected?!

**Comment by ildyria** [comment]
> I lost track about the different lychee forks and versions and I am confused which is the actual project. Is it lychee-laravel oder https://github.com/LycheeOrg/Lychee ? Are both still developed? 

https://github.com/LycheeOrg/Lychee-Laravel = v4
https://github.com/LycheeOrg/Lychee = v3.2....

v3 has been "on break" for quite a while. **It is not actively developped anymore.**
I consider v4 to actually be release ready, we just need to write the FAQ, documentation how to efficiently migrate from v3 to v4.

As for the activity of LycheeOrg:

- @d7415 and @tmp-hallenser seems to also be pretty busy
- @roblandry is in charge of the docker but this works rather well, he is currently adding support for other arch.
- @kamil4 did not give any news for quite a while.
- I am currently writting my PhD Thesis so it is pretty busy time for me.

That being said, @d7415, @tmp-hallenser and I are still monitoring the issues, helping on gitter and answering questions.

> Why is the Link on https://lychee.electerious.com still pointed to the very old repository and how is everything connected or not connected?!

We do not have control on that page. We contacted the electerious but he basically told us that for history purpose he would not change that link.

The current link (and up to date) is : https://lycheeorg.github.io/

**Comment by ildyria** [comment]
We also need to figure out how we are going to apply the update.

- Do we rename that repository "Lychee", and "Lychee" into "Lychee classic"/"Lychee v3" ?
- Do we change the master branch of Lychee into v3 and push this as the new master branch of Lychee...

The way to handle that is actually pretty difficult to solve.

**Comment by jeyca** [comment]
thanks for the infos, I would really recommend to choose better names like v4 or v3, most people wont be interested if its on laravel or something else. And if someone is interested she will find out by herself.

But is there also a working release of lychee-laravel? Or should I use lychee-classic in production?

**Comment by ildyria** [comment]
> But is there also a working release of lychee-laravel? 

You can use the beta ones: https://github.com/LycheeOrg/Lychee-Laravel/releases/tag/v4.0.0-beta.2

> Or should I use lychee-classic in production?

I have been using Lychee-Laravel in prod for more than a year without any troubles.

That's my current Diagnostic:
```
    System Information
    ------------------
    Lychee-front Version:      3.2.16
    Lychee Version (git):      bae5f2b (master) - Up to date (2 hours ago).
    DB Version:                040000
    System:                    Linux
    PHP Version:               7.3
    MySQL Version:             10.3.22-MariaDB-1
    
    Lychee total space:        90.52 GB
    Upload folder space:       90.36 GB
    System total space:        489.18 GB
    System free space:         359.35 GB (73%)
    
    Imagick:                   1
    Imagick Active:            1
    Imagick Version:           1690
    GD Version:                2.2.5
```

> Or should I better use current lychee-laravel, its best working just not very good documented?

Lychee-Laravel brings a lot compared to the v3, e.g. sub albums. 

The install step are actually pretty on documented (if you use apache):
https://github.com/LycheeOrg/Lychee-Laravel/wiki/Install
https://github.com/LycheeOrg/Lychee-Laravel/wiki/Install-Steps-on-Debian-Testing

**Comment by mayailkour** [comment]
I love your teamwork on Lychee! 😍
Is it possible to support the development via GitHub Sponsors?

**Comment by ildyria** [comment]
> I love your teamwork on Lychee! 
> Is it possible to support the development via GitHub Sponsors?

The problem with GitHub Sponsors for the organization, is that it requires us to set up a Bank account etc and I see how it can be more efficient for you.

We don't have costs (aside from our time) as we are using the github.io infrastructure to host the web pages. At the moment, the only way to support us is to buy coffees to individual developers members. More details here: https://lycheeorg.github.io/support :confused:

**Comment by d7415** [comment]
Lychee-Laravel has now been released as Lychee v4, so I'm going to close this and unpin it.
