### ISSUE TITLE
Error 500 after a fresh installation

### ISSUE THREAD

**Issue by ericxuo** [LycheeOrg/Lychee#1021]
Hi,

I've just installed Lychee.
I get a "500 Server Error" when I connect to my lychee config.
In my .env, I get :  
APP_DEBUG=true
APP_URL=http://localhost
DB_CONNECTION=mariadb
DB_HOST=localhost
DB_PORT=3306
DB_DATABASE=lychee
DB_USERNAME=lychee_admin
DB_PASSWORD='Lychee_admin_password'
DB_LOG_SQL=false

as I've set APP_DEBUG to true; I can see that it seems to come from line 14 of  Lychee_4.3.0/app/Http/Middleware/Checks/ExistsDB.php

![Lychee](https://user-images.githubusercontent.com/9089499/120345230-94438e80-c2fa-11eb-8313-7e73505d8cba.png)

I can connect to the lychee mariadb database with phpmyadmin as I've created the database using the following commands : 
CREATE DATABASE lychee CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE USER 'lychee_adminr'@'localhost' IDENTIFIED BY 'Lychee_admin_password';
GRANT ALL PRIVILEGES ON lychee.* TO 'lychee_admin'@'localhost';
FLUSH PRIVILEGES;
EXIT;
It does not contain any table.

Could you help me to solve this issue ?

Regards.

Xuo.

**Comment by nagmat84** [comment]
Did you run `./artisan config:cache` followed by `./artisan migrate`? Laravel must first create the tables before Lychee will work.

**Comment by ildyria** [comment]
can you do `./artisan lychee:diagnostics` ?

**Comment by ericxuo** [comment]
Hi,

Results of ./artisan config:cache followed by ./artisan migrate : 

![Lychee_artisan](https://user-images.githubusercontent.com/9089499/120355763-d9b88980-c303-11eb-8386-529b8e26d0ba.jpeg)

Results of ./artisan lychee:diagnostics : 

![Lychee_artisan_diagnostics](https://user-images.githubusercontent.com/9089499/120355809-ea68ff80-c303-11eb-827b-0a08128fa35b.jpeg)

The database is not configured. This is true, I didn't do it because I don't know what to do. I thought Lychee will do it when connecting the first time.

Regards.

Xuo.

**Comment by ildyria** [comment]
nah, there is something weird happening there.

**Comment by ildyria** [comment]
can you give us the output of your phpinfo() ?

**Comment by nagmat84** [comment]
I believe the solution could be easy. Even if you use MariaDB as a server instead of MySQL, the PHP PDO client is named mysql nonetheless. Your `.env` file is

    DB_CONNECTION=mariadb    // <-- ERROR. This must be mysql
    DB_HOST=localhost
    DB_PORT=3306
    DB_DATABASE=lychee
    DB_USERNAME=lychee_admin
    DB_PASSWORD='Lychee_admin_password'
    DB_LOG_SQL=false

The only supported values for `DB_CONNECTION` are documented in the sample `.env` file.

**Comment by ericxuo** [comment]
Hi,

My mistake. 
@nagmat84 : you are right. Replacing mariadb by mysql solved the issue. I didn't read carrefully the comments in the .env file.

Thank you for your help to all of you.

Regards.

Xuo.

**Comment by ericxuo** [comment]
Issue solved, see previous comment.
