### ISSUE TITLE
Unable to sync using lychee:sync command

### ISSUE THREAD

**Issue by aaronnewsome** [LycheeOrg/Lychee#1024]
### Detailed description of the problem [REQUIRED]
I've spent more than a few hours trying to track down what exactly is going on but I'm unable to sync from the server command line. In the FAQ it says to simply run "php artisan lychee:sync /dir/to/files". When I do that, I get this error:

In Geodecoder.php line 35:
  Class 'Http\Adapter\Guzzle6\Client' not found

I've searched around for anything named Guzzle6\Client. Didn't find anything. Not sure I'd know what to do with it if I did find the Guzzle6\Client file.

### Steps to reproduce the issue
1. Start the Docker image for Lychee 4.3.0.
2. Login to via the web UI.
3. Enable maps feature.
4. Use the command line interface to sync a directory as described above.

### Output of the diagnostics  [REQUIRED]
Diagnostics
-----------
Warning: Dropbox import not working. dropbox_key is empty.
Warning: You may experience problems when uploading a photo of large size. Take a look in the FAQ for details.
Warning: You may experience problems when uploading a photos of large size. Take a look in the FAQ for details.
Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.

System Information
------------------
Lychee Version (git):            No git data found.
DB Version:                      4.3.0

composer install:                --no-dev
APP_ENV:                         production
APP_DEBUG:                       false

System:                          Linux
PHP Version:                     7.4
Max uploaded file size:          2M
Max post size:                   8M
PostgreSQL Version:              PostgreSQL 9.5.25 on x86_64-pc-linux-gnu (Debian 9.5.25-1.pgdg90+1), compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit

Imagick:                         1
Imagick Active:                  1
Imagick Version:                 1691
GD Version:                      2.3.0

Config Information
------------------
version:                         040300
check_for_updates:               0
sorting_Photos_col:              takestamp
sorting_Photos_order:            ASC
sorting_Albums_col:              max_takestamp
sorting_Albums_order:            ASC
imagick:                         1
skip_duplicates:                 0
small_max_width:                 0
small_max_height:                360
medium_max_width:                1920
medium_max_height:               1080
lang:                            en
layout:                          1
image_overlay_type:              desc
default_license:                 none
compression_quality:             90
full_photo:                      1
delete_imported:                 0
Mod_Frame:                       1
Mod_Frame_refresh:               30
thumb_2x:                        1
small_2x:                        1
medium_2x:                       1
landing_page_enable:             0
**owner name removed**
site_copyright_enable:           1
site_copyright_begin:            2000
site_copyright_end:              2021
additional_footer_text:          
display_social_in_gallery:       0
public_search:                   1
SL_enable:                       0
SL_for_admin:                    0
public_recent:                   0
recent_age:                      1
public_starred:                  0
downloadable:                    0
photos_wraparound:               1
map_display:                     1
zip64:                           1
map_display_public:              0
map_provider:                    Wikimedia
force_32bit_ids:                 0
map_include_subalbums:           0
update_check_every_days:         3
has_exiftool:                    1
share_button_visible:            0
import_via_symlink:              0
has_ffmpeg:                      1
location_decoding:               1
location_decoding_timeout:       30
location_show:                   0
location_show_public:            0
rss_enable:                      0
rss_recent_days:                 7
rss_max_items:                   100
prefer_available_xmp_metadata:   0
editor_enabled:                  1
lossless_optimization:           0
swipe_tolerance_x:               150
swipe_tolerance_y:               250
local_takestamp_video_formats:   .avi
log_max_num_line:                1000
unlock_password_photos_with_url_param: 0
nsfw_visible:                    0
nsfw_blur:                       0
nsfw_warning:                    0
nsfw_warning_admin:              0
map_display_direction:           1
album_subtitle_type:             oldstyle
upload_processing_limit:         4
public_photos_hidden:            1

**Comment by nagmat84** [comment]
Did you upgrade from an older version of Lychee recently? If yes, it might be that some of the optimized and cached PHP files still link to the wrong dependencies. Please run the following commands

    php artisan optimize:clear
    composer install

The first command clears the cache of the (perhaps outdated) cached files  Don't worry, the will be re-created the next time they are needed. The second command ensures that you have the correct dependencies installed.

Then try again what you wanted to do.

**Comment by d7415** [comment]
This is #998. Fixed in master and the `:dev` image, but I don't think it's in a release yet.
