### ISSUE TITLE
Usage Related issues

### ISSUE THREAD

**Issue by asarangaram** [LycheeOrg/Lychee#1025]
I tried Lychee today and I am not clear if there is any forum to help, hence writing here.  I installed on Ubuntu/RPi and it works perfectly, however, transition is not possible as there are three issues.
1. When uploading the server directories, repeatedly, I see the photos are duplicated. Does Lychee detects the duplicate? Seems like, it has copied only once into the upload/ folder, however, on photos, it shows repeatedly. Is there a way to remove duplicates in album views? (Even albums are duplicated)
2. The original create date (or Photo taken) is not shown anywhere. Is this preserved? Can we organise the photos based on the date the photo was taken?
3. All the images are copied into the upload folder with an encrypted name. I understand, when I download, it renames and gives correctly. However, If I want to access the photos from backdoor in the server, We need to reapply the name. Is it possible?  This is important because, if my server crashes, I don't have Lychee to access, and need to back up the data from the hard disk. 
Can someone comment on these issues? IT will help me to decide on migrating to Lychee for my photo management.

Anand

**Comment by ildyria** [comment]
Hi @asarangaram thank you for asking,

> 1. When uploading the server directories, repeatedly, I see the photos are duplicated. Does Lychee detects the duplicate? Seems like, it has copied only once into the upload/ folder, however, on photos, it shows repeatedly. Is there a way to remove duplicates in album views? (Even albums are duplicated)

We do detect duplicates and we have a setting for that. It may also be interesting to use instead _import via symlinks_, this will create links to your pictures instead of moving/copying them over.
@d7415 and @tmp-hallenser are a bit more familiar than me in this process.

> 2. The original create date (or Photo taken) is not shown anywhere. Is this preserved? Can we organise the photos based on the date the photo was taken?

Yes it is preserved as long as you have exiftool installed so that we are able to extract the data. Later you can order your pictures by taken date ASC or DESC. 

> 3. All the images are copied into the upload folder with an encrypted name. I understand, when I download, it renames and gives correctly. However, If I want to access the photos from backdoor in the server, We need to reapply the name. Is it possible? This is important because, if my server crashes, I don't have Lychee to access, and need to back up the data from the hard disk.

At the moment it is not possible to preserve a folder structure with respect to the names (as if you were exploring). However, if you backup your sql server, you will not use those information and it will not be hard to reconstruct the folder structure with a simple php script.

Also note that if you decide to use SQLite instead of MySQL, the database is just a single file: 
`database/database.sqlite`.

**Comment by ildyria** [comment]
https://lycheeorg.github.io/docs/faq.html

**Comment by asarangaram** [comment]
Hello Benoît Viguier,

Thank you for the quick response. I forgot to mention that I am trying the
3.x version from https://github.com/electerious/Lychee.
I believe you are answering for the 4.x version from
www.github.com/LycheeOrg/Lychee.
Unfortunately, I couldn't run 4.x yet on Raspberry Pi / Ubuntu, even though
I gave multiple attempts.
From your reply, it seems some of the issues I reported are already solved
in 4.x. I'll give one more attempt to move to 4.x next week.

The problem I am facing with 4.x is as below...
I have configured apache2 and confirmed that I could render a simple
index.php file under the folder Lychee/public.
When I move to the git clone, and follow the procedures, I see only a blank
page. I think I need to dig out what configuration mistake I am making.
I assume someone has already tested it on Raspberry Pi / Ubuntu.
I'll confirm the status by next week.

Thanks!
Anand

**Comment by ildyria** [comment]
I don't have a Raspberry Pi to test, but I am pretty sure it is possible to run Lychee v4 on such device as long as you have the correct version of php (7.4 or 8) and the required packages.

If you get a blank page, check also that you have the rewrite module enabled.
I use lychee in a VM as follows. Nonetheless, this should give you an idea of the configuration: https://lycheeorg.github.io/docs/distributions.html#apache-and-proxy-in-the-host

The FAQ should also help you if you have problems. Don't hesitate to ask questions. :)

PS: version 4 is a big step up from version 3.

**Comment by asarangaram** [comment]
Hello Benoît Viguier,

I could run the Release version 4.2.2, but not 4.3.0. or git top. I notice
that you have added support for php8 from 4.3.0 and something seems to have
broken (at least for my setup with php 7.4).
As I could run 4.2.2, I assume there are no web server related settings. Is
there any log that I can share with you to help tracing this issue?

On 4.2.2, there are some other issues related to photo upload, unrelated to
this issue. Investigating.

Anand

**Comment by asarangaram** [comment]
Here is some update with version 4.2.2:

When I try to upload a picture, it seems it uploads somewhere (as when I
try with an mp4 file, it shows the progress %), but at the end, it reports
the following error. I checked all the permissions issue with file system
(all folders has write permission to user 'www-data'
[image: Screenshot 2021-06-06 at 7.06.39 PM.png]
Not sufficient info even in the console except "500 | Server Error ". I
tested uploading with a standalone php script and it worked fine. Is there
any error log which will help to understand the problem?

I tried to use sqlite. The sqlite is indeed installed and I could use it
outside Lychee, but Lychee's installation reports Sqlite3 is missing. I
don't see any settings in .env other than setting DB_CONNECTION=sqlite (and
leaving all others blank, and  commenting out DB_DATABASE)

[image: image.png]
[image: image.png]
It accepted mysql settings.

PS:
I am not a web developer, so I need some support to debug issues,
if possible. I am trying this only to setup a photo sharing on my home LAN.
I am afraid I am violating any norm of this project by reporting all the
issues I am facing in the same Issue ID in git. In case you see any red
flag in the way I am communicating, please let me know. I can correct
myself.

Anand

**Comment by ildyria** [comment]
> I need some support to debug issues,
> 
>  In case you see any red
flag in the way I am communicating, please let me know. 

No worries. 

>  I tried to use sqlite. The sqlite is indeed installed and I could use it
outside Lychee, but Lychee's installation reports Sqlite3 is missing. I
don't see any settings in .env other than setting DB_CONNECTION=sqlite (and
leaving all others blank, and  commenting out DB_DATABASE)

That should be fine.

You probably have access to command line, so if you can do:
`php artisan lychee:diagnostics` and give us the output?

**Comment by asarangaram** [comment]
Thank you!

*// php artisan lychee:diagnostics*
This is what I was looking for.  Fixed 3 issues found using this
diagnostics and that gave a good progress.

1. The problem with sqlite was that I had sqlite, but not php sqlite plug
in.  My mistake!

2. In the file public/.htaccess, Lychee is  modifying the limits for php.
Seems like this didn't take effect.(maybe because I am using 7.4?).
<IfModule mod_php7.c>
        php_value max_execution_time 200
        php_value post_max_size 500M
        php_value upload_max_filesize 500M
        php_value max_file_uploads 100
</IfModule>

3. Permission related issues, just changing the ownership to www-data is
not sufficient, we still need to give write permission to others for
specific folders (chmod -R o+w). In the documentation, some places it is
mentioned to change the ownership and some other place, to change the
permissions. Both are required)

I updated these limits in php.ini, but that alone didn't solve the issue.
It seems like, Lychee captures Max uploaded file size and Max post size
during installation and preserves somewhere internally. I don't know the
way to refresh (one way I found was to edit advanced settings, but I was
not sure), hence I redid everything and now, all are good for photos.

Uploading single/Multiple photos -- OK
Duplicate when Uploading single/Multiple photos" -- NOT OK (duplicates are
uploaded)
Upload using "Import from Server" -- OK
Duplicate Detection when "Import from Server" -- OK (duplicates are skipped)
Symlink instead of copying when "Import from Server" -- OK

Supporting *Symlink and duplicate detection* during server import are the
game changers, it helps the users to organize in their own way.
These two features also solve all three issues I reported. I truly
appreciate the effort of this open source community, particularly, the
enhancement from 3.x to 4.x.

*I saw some issues in uploading mp4 files, but it is not my current
requirement. Once the photos are fully migrated to Lychee, I'll check this
and write back if I can't solve the issue myself.*

Thanks again for your prompt and pointed response.

Anand

**Comment by ildyria** [comment]
Hi Anand, thank you for coming back at us.

1. yay :smiley: 
2. Surprising, but nice that you found a work around
3. Could you tell us which folder also need to be changed ? that would be helpful for future users. :thinking: 
    > Lychee captures Max uploaded file size and Max post size
during installation and preserves somewhere internally. 

     Actually we don't. We just read the values from the ini.
4. > Duplicate when Uploading single/Multiple photos" -- NOT OK (duplicates are
uploaded)

    Possible bug. However in theory there are only duplicates in the database. In the file system, you have uniqueness.

> Supporting *Symlink and duplicate detection* during server import are the
game changers, it helps the users to organize in their own way.
These two features also solve all three issues I reported.

Happy to read that.

> I truly appreciate the effort of this open source community, particularly, the
enhancement from 3.x to 4.x.

Told you moving from v3 to v4 was worth it :wink: 

I think we can close this issue now. :+1:

**Comment by asarangaram** [comment]
Sorry for the late response. I could upload the entire Photos (of about
1,00,000) into Lychee..

On the status:

There was no more setup related issue.

I Initially tried the softlink approach, by importing from a directory in
the server. As the photos are too many, it timed out before even
finishing 20%. and every restart rescans and ignores duplicates. However,
This approach couldn't succeed. Later, I allowed the Lychee to manage the
photos, by importing portion by portion. It became a part time job to add
photos from every year for the last one and half months. As the photos are
removed from the original location, I could succeed in this method. Now, I
have started tagging in my free time. So far so good.. I am free from
Google Photos!

I hope the database works without crashing in the coming days.  As I am
using sqlite, I have some worries. (I do have a backup of the originals
anyways). Also because I am using a 1TB external drive connected over USB
to store the lichee folder! I won't be importing videos at least for now.

*//Could you tell us which folder also needs to be changed ? that would be
helpful for future users. *
Nothing, If we switch the ownership to www-data:www-data for the entire
Lychee directory, there is no need to change anything else.

I created a detailed procedure to set up Lychee on a Raspberry Pi here.
https://gitlab.com/asarangaram/step-by-step-guides/-/blob/main/Lychee_on_RPi.md
. It also covers steps we need to take care of before we download Lychee.
Hope this helps someone. I created it with the very latest release I found
on github today.

Thanks
Anand

திங்., 7 ஜூன், 2021, பிற்பகல் 12:27 அன்று, Benoît Viguier <
***@***.***> எழுதியது:
