### ISSUE TITLE
Moving photos between albums causes scolling to reset at top

### ISSUE THREAD

**Issue by vjuliano** [LycheeOrg/Lychee#1027]
### Detailed description of the problem [REQUIRED]
When I  MOVE a photo from one album to another, in most cases after a short delay (few seconds) the album is reloaded and I am back at the top.  There have been a few instances where the reload happens and I stay scrolled to where I was, which is how I suspect it is supposed to function.  I thought album size had an impact, but it does not seem to.  It happens the same if 1 photo is moved, or multiple.  Functionally it is ok, most of the time it seems the MOVE took effect, but it is annoying, especially in a large album because you loose your place.  It seems DELETE works correctly and does not cause me to end up on top.

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Go to any album large enough to have scrolling.
2. Right Click on any photo that requires scrolling to bring into view
3. Select MOVE from context menu
4. See annoying behavior

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

### Output of the diagnostics  [REQUIRED]
    Diagnostics
    -----------
    Warning: Dropbox import not working. dropbox_key is empty.
    Warning: Using 32 bit PHP, recommended upgrade to 64 bit

    System Information
    ------------------
    Lychee Version (release):        4.3.0
    DB Version:                      4.3.0
    
    composer install:                dev
    APP_ENV:                         test
    APP_DEBUG:                       false
    
    System:                          Linux
    PHP Version:                     7.4
    Max uploaded file size:          500M
    Max post size:                   500M
    MySQL Version:                   10.3.27-MariaDB-0+deb10u1
    
    Imagick:                         1
    Imagick Active:                  1
    Imagick Version:                 1690
    GD Version:                      2.2.5

    Config Information
    ------------------
    version:                         040300
    check_for_updates:               1
    sorting_Photos_col:              takestamp
    sorting_Photos_order:            ASC
    sorting_Albums_col:              max_takestamp
    sorting_Albums_order:            ASC
    imagick:                         1
    skip_duplicates:                 0
    small_max_width:                 0
    small_max_height:                360
    medium_max_width:                1920
    medium_max_height:               1080
    lang:                            en
    layout:                          1
    image_overlay_type:              desc
    default_license:                 none
    compression_quality:             90
    full_photo:                      1
    delete_imported:                 0
    Mod_Frame:                       1
    Mod_Frame_refresh:               30
    thumb_2x:                        1
    small_2x:                        1
    medium_2x:                       1
    landing_page_enable:             0
    landing_owner:                   Vincent Juliano
    landing_title:                   Photo Gallery
    landing_subtitle:                
    landing_facebook:                
    landing_flickr:                  
    landing_twitter:                 
    landing_instagram:               
    landing_youtube:                 
    landing_background:              dist/cat.jpg
    site_title:                      Vince Juliano's Photo Gallery
    site_copyright_enable:           1
    site_copyright_begin:            2021
    site_copyright_end:              2021
    additional_footer_text:          
    display_social_in_gallery:       0
    public_search:                   0
    SL_enable:                       0
    SL_for_admin:                    0
    public_recent:                   0
    recent_age:                      1
    public_starred:                  0
    downloadable:                    0
    photos_wraparound:               1
    map_display:                     1
    zip64:                           1
    map_display_public:              1
    map_provider:                    Wikimedia
    force_32bit_ids:                 0
    map_include_subalbums:           1
    update_check_every_days:         3
    has_exiftool:                    0
    share_button_visible:            0
    import_via_symlink:              0
    has_ffmpeg:                      1
    location_decoding:               1
    location_decoding_timeout:       30
    location_show:                   1
    location_show_public:            1
    rss_enable:                      0
    rss_recent_days:                 7
    rss_max_items:                   100
    prefer_available_xmp_metadata:   0
    editor_enabled:                  1
    lossless_optimization:           0
    swipe_tolerance_x:               150
    swipe_tolerance_y:               250
    local_takestamp_video_formats:   .avi|.mov
    log_max_num_line:                1000
    unlock_password_photos_with_url_param: 0
    nsfw_visible:                    0
    nsfw_blur:                       0
    nsfw_warning:                    0
    nsfw_warning_admin:              0
    map_display_direction:           1
    album_subtitle_type:             oldstyle
    upload_processing_limit:         4
    public_photos_hidden:            1

### Browser and system
Mac os 11 Big Sur   Intel
Firefox 89
Chrome 91.0.4472.77

**Comment by kamil4** [comment]
Confirmed. I'm guessing it's a race condition. Also, the code that saves the scrolling position is deliberately written to work only for albums with subalbums, which tells me that it was never really meant to handle the cases such as post-move album refreshes, but I agree that it should...
