### ISSUE TITLE
Claims Update Available when one is not

### ISSUE THREAD

**Issue by vjuliano** [LycheeOrg/Lychee#1032]
### Detailed description of the problem [REQUIRED]
Lychee is saying there is an update available, and there does not appear to be one.  It says 'Update Available' on the sign in form and in the left menu.  The sign in form says 'Lychee 4.3.0 - Update Available', even though I am running 4.3.0.  Clicking on the Update Available in the side menu brings up a page that says 'Nothing to migrate'.  The Diagnostics page confirms that I am running 4.3.0.
### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Go to Lychee side menu
2. Click on 'Update Available'
4. See error*

**Screenshots**
![Screen Shot 2021-06-07 at 3 18 38 AM](https://user-images.githubusercontent.com/58374187/121024515-24e5f880-c759-11eb-9fb7-059057821bda.png)
![Screen Shot 2021-06-07 at 6 21 22 AM](https://user-images.githubusercontent.com/58374187/121024532-29aaac80-c759-11eb-9cf7-2dd1c2619c24.png)

### Output of the diagnostics  [REQUIRED]
    Diagnostics
    -----------
    Warning: Dropbox import not working. dropbox_key is empty.
    Warning: Using 32 bit PHP, recommended upgrade to 64 bit

    System Information
    ------------------
    Lychee Version (release):        4.3.0
    DB Version:                      4.3.0
    
    composer install:                dev
    APP_ENV:                         test
    APP_DEBUG:                       false
    
    System:                          Linux
    PHP Version:                     7.4
    Max uploaded file size:          500M
    Max post size:                   500M
    MySQL Version:                   10.3.27-MariaDB-0+deb10u1
    
    Imagick:                         1
    Imagick Active:                  1
    Imagick Version:                 1690
    GD Version:                      2.2.5

    Config Information
    ------------------
    version:                         040300
    check_for_updates:               1
    sorting_Photos_col:              takestamp
    sorting_Photos_order:            ASC
    sorting_Albums_col:              max_takestamp
    sorting_Albums_order:            ASC
    imagick:                         1
    skip_duplicates:                 0
    small_max_width:                 0
    small_max_height:                360
    medium_max_width:                1920
    medium_max_height:               1080
    lang:                            en
    layout:                          1
    image_overlay_type:              desc
    default_license:                 none
    compression_quality:             90
    full_photo:                      1
    delete_imported:                 0
    Mod_Frame:                       1
    Mod_Frame_refresh:               30
    thumb_2x:                        1
    small_2x:                        1
    medium_2x:                       1
    landing_page_enable:             0
    landing_owner:                   Vincent Juliano
    landing_title:                   Photo Gallery
    landing_subtitle:                
    landing_facebook:                
    landing_flickr:                  
    landing_twitter:                 
    landing_instagram:               
    landing_youtube:                 
    landing_background:              dist/cat.jpg
    site_title:                      Vince Juliano's Photo Gallery
    site_copyright_enable:           1
    site_copyright_begin:            2021
    site_copyright_end:              2021
    additional_footer_text:          
    display_social_in_gallery:       0
    public_search:                   0
    SL_enable:                       0
    SL_for_admin:                    0
    public_recent:                   0
    recent_age:                      1
    public_starred:                  0
    downloadable:                    0
    photos_wraparound:               1
    map_display:                     1
    zip64:                           1
    map_display_public:              1
    map_provider:                    Wikimedia
    force_32bit_ids:                 0
    map_include_subalbums:           1
    update_check_every_days:         3
    has_exiftool:                    0
    share_button_visible:            0
    import_via_symlink:              0
    has_ffmpeg:                      1
    location_decoding:               1
    location_decoding_timeout:       30
    location_show:                   1
    location_show_public:            1
    rss_enable:                      0
    rss_recent_days:                 7
    rss_max_items:                   100
    prefer_available_xmp_metadata:   0
    editor_enabled:                  1
    lossless_optimization:           0
    swipe_tolerance_x:               150
    swipe_tolerance_y:               250
    local_takestamp_video_formats:   .avi|.mov
    log_max_num_line:                1000
    unlock_password_photos_with_url_param: 0
    nsfw_visible:                    0
    nsfw_blur:                       0
    nsfw_warning:                    0
    nsfw_warning_admin:              0
    map_display_direction:           1
    album_subtitle_type:             oldstyle
    upload_processing_limit:         4
    public_photos_hidden:            1

### Browser and system
Mac Os 11 Big Sur     Firefox 89, Chrome 91.0.4472.77
Windows 7 Firefox 89

**Comment by ildyria** [comment]
Update available means that there is a new update available because we bumped the version number in the repository which was caught by the website: https://lycheeorg.github.io/update.json

This value directly depends on: https://github.com/LycheeOrg/Lychee/blob/master/version.md
Which specifies the file version vs the database version.

But yes, there needs to be more info with regard to that detail. By the way, you can also disable the search for updates in your settings. :)

**Comment by d7415** [comment]
> But yes, there needs to be more info with regard to that detail.

Or make a release? 😉
