### ISSUE TITLE
Failing to upload files larger than 20MB,want to upload 2GB

### ISSUE THREAD

**Issue by Moonjer** [LycheeOrg/Lychee#1035]
### Detailed description of the problem [REQUIRED]
*A clear and concise description of what the bug is.*

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
4. See error*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

### Output of the diagnostics  [REQUIRED]
*(Settings => Diagnostics or https://example.com/Diagnostics or `php artisan lychee:diagnostics`)*

**Comment by d7415** [comment]
https://lycheeorg.github.io/docs/faq.html#i-cant-upload-large-photos

**Comment by Moonjer** [comment]
modify 
1.nginx- nginx.conf " client_max_body_size "and php's conf value
2.php-file in cli and file in fpm,modify php.ini
3.lychee-file in public ,modify .user.ini
