### ISSUE TITLE
[Question] Lychee usage of Database

### ISSUE THREAD

**Issue by wescrockett** [LycheeOrg/Lychee#1038]
Sorry if this is the wrong place, but I don't see a forum or other avenue for asking a general questions related to the project.

I have an Unraid server with a photos share. I would like to set up Lychee for a method of browsing these photos but I have a few questions prior to going down that path.

1. If I install Lychee and point it to my photos share, will Lychee have any affect on the organization, contents, or metadata of the existing directories and files?
2. Is the database solely for adding metadata about pictures and videos?
3. When uploading from within Lychee, where do the actual files end up residing?

Thank you very much. If there is a better place for these questions, please let me know where that is and close this issue.

-Wes

**Comment by ildyria** [comment]
> but I don't see a forum for asking a general questions related to the project.

We have gitter :) https://gitter.im/LycheeOrg/Lobby
It is also in the Read me, but I agree we could make it more visible. :)

**Comment by ildyria** [comment]
> If I install Lychee and point it to my photos share, will Lychee have any affect on the organization, contents, or metadata of the existing directories and files?

If you use Import via symlinks, no.

> Is the database solely for adding metadata about pictures and videos?

It is also used to link with what thumbs images and Album organization. But yes. However Lychee displays the pictures that are in the database, it does not actively parse a folder.

> When uploading from within Lychee, where do the actual files end up residing?

When you upload from Lychee, this is a different action than an import from folder or a console sync.
The picture will be placed in `public/uploads/big/` give you the following path `public/uploads/big/1234567890abcdef1234567890abcdef.ext`

While some complains "*You do not preserve the folder structure, etc*" This structure can be recovered by simply downloading the archive of the album from the Lychee interface.

Do check our FAQ : https://lycheeorg.github.io/docs/faq.html :)

**Comment by wescrockett** [comment]
Thank you!
