### ISSUE TITLE
Firefox issue : Can't open any album

### ISSUE THREAD

**Issue by Babyforce** [LycheeOrg/Lychee#1040]
### Detailed description of the problem [REQUIRED]
Sometimes, when using Firefox, Lychee won't let any user open an album (even the admin). When you place your cursor on one, the animation plays, but clicking has no effect at all. Trying to click after refreshing the page or going in private mode doesn't solve the issue. It works prefectly on any chromium based browser though. It also works perfectly on Firefox for Android.

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Connect to the web interface using the Mozilla Firefox Browser.
2. Place your cursor on any album.
3. Click on an album. Nothing may happen. Nothing in the logs. Just nothing at all happens.

### Output of the diagnostics  [REQUIRED]
Diagnostics
-----------
Warning: Dropbox import not working. dropbox_key is empty.
Warning: You may experience problems when uploading a photo of large size. Take a look in the FAQ for details.
Warning: You may experience problems when uploading a photos of large size. Take a look in the FAQ for details.
Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.

System Information
------------------
Lychee Version (release):        4.3.0
DB Version:                      4.3.0

composer install:                --no-dev
APP_ENV:                         production
APP_DEBUG:                       true

System:                          Linux
PHP Version:                     8
Max uploaded file size:          2M
Max post size:                   8M
MySQL Version:                   10.3.27-MariaDB-0+deb10u1

Imagick:                         1
Imagick Active:                  1
Imagick Version:                 1690
GD Version:                      2.2.5

Config Information
------------------
version:                         040300
check_for_updates:               0
sorting_Photos_col:              title
sorting_Photos_order:            ASC
sorting_Albums_col:              title
sorting_Albums_order:            ASC
imagick:                         1
skip_duplicates:                 1
small_max_width:                 0
small_max_height:                360
medium_max_width:                1920
medium_max_height:               1080
lang:                            en
layout:                          1
image_overlay_type:              desc
default_license:                 none
compression_quality:             90
full_photo:                      1
delete_imported:                 0
Mod_Frame:                       1
Mod_Frame_refresh:               30
thumb_2x:                        1
small_2x:                        1
medium_2x:                       1
landing_page_enable:             0
landing_owner:                   John Smith
landing_title:                   John Smith
landing_subtitle:
landing_facebook:
landing_flickr:
landing_twitter:
landing_instagram:
landing_youtube:
landing_background:              dist/cat.jpg
site_title:                      Gallery
site_copyright_enable:           0
site_copyright_begin:            2019
site_copyright_end:              2019
additional_footer_text:
display_social_in_gallery:       0
public_search:                   1
SL_enable:                       0
SL_for_admin:                    0
public_recent:                   0
recent_age:                      1
public_starred:                  0
downloadable:                    0
photos_wraparound:               1
map_display:                     0
zip64:                           1
map_display_public:              0
map_provider:                    Wikimedia
force_32bit_ids:                 0
map_include_subalbums:           0
update_check_every_days:         3
has_exiftool:                    0
share_button_visible:            0
import_via_symlink:              1
has_ffmpeg:                      1
location_decoding:               0
location_decoding_timeout:       30
location_show:                   0
location_show_public:            0
rss_enable:                      0
rss_recent_days:                 7
rss_max_items:                   100
prefer_available_xmp_metadata:   0
editor_enabled:                  1
lossless_optimization:           0
swipe_tolerance_x:               150
swipe_tolerance_y:               250
local_takestamp_video_formats:   .avi|.mov
log_max_num_line:                1000
unlock_password_photos_with_url_param: 0
nsfw_visible:                    1
nsfw_blur:                       0
nsfw_warning:                    0
nsfw_warning_admin:              0
map_display_direction:           1
album_subtitle_type:             oldstyle
upload_processing_limit:         4
public_photos_hidden:            1

### Browser and system
Firefox 86-90 (and probably lower versions too)
Arch Linux
Windows 10

**Comment by ildyria** [comment]
Very surprising.

**Comment by ildyria** [comment]
> Nothing in the logs.

I assume you mean Lychee's logs.

Can you press F12 in your browser and have a look at the console logs?

PS: nice that you are using php8. :)

**Comment by Babyforce** [comment]
> 
> 
> > Nothing in the logs.
> 
> I assume you mean Lychee's logs.
> 
> Can you press F12 in your browser and have a look at the console logs?
> 
> PS: nice that you are using php8. :)

Will send whenever I can. Might take a while.

And yes, when I saw Lychee could run on PHP 8, I immediatly started using this instead of PHP 7.4. I like using the latest technologies.

**Comment by ildyria** [comment]
> And yes, when I saw Lychee could run on PHP 8, I immediatly started using this instead of PHP 7.4. I like using the latest technologies.

We will kill php 7.4 support next December anyway. :)

**Comment by Babyforce** [comment]
Here's what happens in the browser when trying to open an album :
![b16151d8104121196bd12125d27ade833e2c56ae53d4e5066b2f1d3d65343a91](https://user-images.githubusercontent.com/1695422/123252713-e2f4da80-d4ec-11eb-9bb2-35b93b9faf01.png)

**Comment by kamil4** [comment]
FYI, I've been using Lychee with Firefox under Linux for years, without issue. So I strongly suspect a configuration issue on your end.

If the backtrace is to be believed, the trigger is this line:

https://github.com/LycheeOrg/Lychee/blob/0c0661d6f04d306e31cfb303c53ee60a24d5e01f/public/dist/main.js#L4732

I'm seeing the following potentially relevant info on stackoverlow: https://stackoverflow.com/questions/13348766/securityerror-the-operation-is-insecure-window-history-pushstate

Are you serving your gallery over http or https?

If it's not a server-side configuration issue, could it be a browser configuration? Have you tried creating a new profile (`firefox --new-instance --ProfileManager`) and browsing the gallery then, without loading any extensions, etc?

**Comment by Babyforce** [comment]
> 
> 
> FYI, I've been using Lychee with Firefox under Linux for years, without issue. So I strongly suspect a configuration issue on your end.
> 
> If the backtrace is to be believed, the trigger is this line:
> 
> https://github.com/LycheeOrg/Lychee/blob/0c0661d6f04d306e31cfb303c53ee60a24d5e01f/public/dist/main.js#L4732
> 
> I'm seeing the following potentially relevant info on stackoverlow: https://stackoverflow.com/questions/13348766/securityerror-the-operation-is-insecure-window-history-pushstate
> 
> Are you serving your gallery over http or https?
> 
> If it's not a server-side configuration issue, could it be a browser configuration? Have you tried creating a new profile (`firefox --new-instance --ProfileManager`) and browsing the gallery then, without loading any extensions, etc?

Thank you for your reply. It seem to be because of my browser, but specifically because I password protected the thing using htaccess credentials, and I was passing the user and password in the link as "user:password@domain.com". It seems Firefox specifically doesn't like that and has an error everytime I try to open an album. Using this same link in a Chromium-based browser doesn't trigger any error, so I would guess both browsers handle this differently, and Firefox would try to use the credentials in any link I click on the web interface, triggering an error (because it's insecure I suppose). I was convinced it was an issue with the web app itself, though this is pretty annoying. Thanks for the help and sorry for the false report.
