### ISSUE TITLE
Problems with uploading of pictures

### ISSUE THREAD

**Issue by ghost** [LycheeOrg/Lychee#1044]
### Detailed description of the problem
When I upload pictures via the website from my filemanager only a part of the images is uploaded. The other pictures return a 500 error. I also tried the other upload methods, but these resulted in a API error.
(My knowledge of databases and websites is quite low so probably it is an incorrect configuration on my part, but I don't know where to start to solve the problem.)

### Steps to reproduce the issue
Upload pictures via website and chose the desired pictures from the filemanager.
This result in a partial upload of the pictures.

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/76212814/123671269-5d4f9280-d83e-11eb-8862-b8d281d51c97.png)

### Output of the diagnostics

    Diagnostics
    -------
    Warning: Pictures that are rotated lose their metadata! Please install Imagick to avoid that.
    Error: PHP zip extension not activated

    System Information
    --------------
    Lychee Version (release):        4.3.0
    DB Version:                      4.3.0
    
    composer install:                --no-dev
    APP_ENV:                         production
    APP_DEBUG:                       true
    
    System:                          Linux
    PHP Version:                     7.4
    Max uploaded file size:          500M
    Max post size:                   500M
    MySQL Version:                   10.3.29-MariaDB-cll-lve
    
    Imagick:                         -
    Imagick Active:                  1
    Imagick Version:                 -
    GD Version:                      bundled (2.1.0 compatible)

    Config Information
    --------------
    version:                         040300
    check_for_updates:               0
    sorting_Photos_col:              title
    sorting_Photos_order:            ASC
    sorting_Albums_col:              max_takestamp
    sorting_Albums_order:            DESC
    imagick:                         1
    skip_duplicates:                 0
    small_max_width:                 0
    small_max_height:                360
    medium_max_width:                1920
    medium_max_height:               1080
    lang:                            nl
    layout:                          1
    image_overlay_type:              desc
    default_license:                 CC-BY-NC-SA-4.0
    compression_quality:             100
    full_photo:                      1
    delete_imported:                 0
    Mod_Frame:                       1
    Mod_Frame_refresh:               30
    thumb_2x:                        1
    small_2x:                        1
    medium_2x:                       1
    landing_page_enable:             0
    landing_owner:                   KSA Sint-Maarten Moorslede
    landing_title:                   Welkom
    landing_subtitle:                Hier vind je alle recente foto's
    landing_facebook:                https://www.facebook.com/KSAMoorslede
    landing_flickr:                  
    landing_twitter:                 
    landing_instagram:               https://instagram.com/ksamoorslede
    landing_youtube:                 
    landing_background:              dist/Groepsfoto_s_20 (1).jpg
    site_title:                      KSA Sint-Maarten Moorslede
    site_copyright_enable:           1
    site_copyright_begin:            2019
    site_copyright_end:              2021
    additional_footer_text:          
    display_social_in_gallery:       1
    public_search:                   0
    SL_enable:                       0
    SL_for_admin:                    0
    public_recent:                   0
    recent_age:                      1
    public_starred:                  0
    downloadable:                    0
    photos_wraparound:               1
    map_display:                     1
    zip64:                           1
    map_display_public:              1
    map_provider:                    OpenStreetMap.org
    force_32bit_ids:                 0
    map_include_subalbums:           1
    update_check_every_days:         3
    has_exiftool:                    0
    share_button_visible:            0
    import_via_symlink:              0
    has_ffmpeg:                      0
    location_decoding:               1
    location_decoding_timeout:       30
    location_show:                   1
    location_show_public:            1
    rss_enable:                      0
    rss_recent_days:                 7
    rss_max_items:                   100
    prefer_available_xmp_metadata:   0
    editor_enabled:                  1
    lossless_optimization:           0
    swipe_tolerance_x:               150
    swipe_tolerance_y:               250
    local_takestamp_video_formats:   .avi|.mov
    log_max_num_line:                1000
    unlock_password_photos_with_url_param: 0
    nsfw_visible:                    1
    nsfw_blur:                       0
    nsfw_warning:                    0
    nsfw_warning_admin:              0
    map_display_direction:           1
    album_subtitle_type:             oldstyle
    upload_processing_limit:         4
    public_photos_hidden:            1

### Browser and system
Firefox 89.0.2 
Windows

**Comment by kamil4** [comment]
Are you saying that if you upload the same pictures one at time, they upload fine, and it's only when you upload more than one at a time that things fail?

If so, try lowering the value of `upload_processing_limit` (Settings / More) to `1`. Lychee by default will process up to 4 pictures in parallel, which for a very memory-constrained server could be problematic.

**Comment by ghost** [comment]
If I upload pictures in bulk around 4 out of 20 picture succeed to upload sometimes more and sometimes less.
When I chose one image to upload it sometimes succeeds but more often not.

I tried with the adjusted settings, but did not yielded improvements. The same random behavior of random upload is seen.

**Comment by kamil4** [comment]
Sorry for the delay in responding.

I'm still trying to understand the exact failure scenario. What happens if you try to reupload pictures that failed? Will they eventually succeed if you try enough times (random failure behavior) or do particular pictures fail consistently?

If it's consistent with some pictures, could you make a sample available for us to try?

Do you see anything in the logs after a picture fails to upload (_Show Logs_ from the cogwheel menu).

**Comment by jcmcnch** [comment]
I recently ran into something similar running lychee on a VPS with only 1Gb RAM. Reducing the upload limit to 1 as suggested by @kamil4 worked for me - 4 concurrent uploads was apparently too much for the server to handle and I kept getting failed uploads in a kind of random manner.

**Comment by ghost** [comment]
When I start uploading some pictures succeed. Then I can try to have them again uploaded and then some will again succeed. The strange thing is that after it once succeeded to upload a picture it is possible to load them up and they will show up twice in my album, although a first time it was not possible to upload them. However I could try  to upload everything in this way it becomes harder at the end to have a picture uploaded. 

I see during upload the number increase to 100% and then the next step it goes from "processing" to "failled" and goes to the next one.

I have a shared webhost with also 1gb ram. Because I saw in my serverlog there is a memory problem (I think) I again tested with the 1 picture upload limit.
Log from webserver:
![afbeelding](https://user-images.githubusercontent.com/76212814/124089082-d96ef380-da53-11eb-9c94-37c2095f7995.png)

The pictures I use are compressed ones to save place. I tested with the original ones but they give the same result.
Original: https://ksa.stackstorage.com/s/jauz2OFVPEGQKOBn
Compressed: https://ksa.stackstorage.com/s/6CV5kBur7q0cR6fC

I'm not sure but is possible also related due to transfer from webhost, but this already some time ago. The earlier webhost had Lychee in the Softacolous manager and now there is no Softacalous more, however both are managed via Cpanel and in this way transferred.

Log from Lychee:

    2021-07-01 08:02:24 -- notice  -- App\Models\Extensions\ConfigsHas::hasImagick -- 19 -- hasImagick : false
    2021-07-01 08:02:23 -- notice  -- App\Models\Extensions\ConfigsHas::hasImagick -- 19 -- hasImagick : false
    2021-07-01 08:02:22 -- notice  -- /home/ksamoo/public_html/prentjes/app/Actions/Photo/Strategies/StrategyDuplicate.php -- 91 -- Nothing to generate, image is a duplicate
    2021-07-01 08:02:22 -- notice  -- App\Models\Extensions\ConfigsHas::hasImagick -- 19 -- hasImagick : false
    2021-07-01 08:02:22 -- notice  -- /home/ksamoo/public_html/prentjes/app/Actions/Photo/Strategies/StrategyDuplicate.php -- 31 -- Nothing to store, image is a duplicate
    2021-07-01 08:02:21 -- notice  -- App\Models\Extensions\ConfigsHas::hasImagick -- 19 -- hasImagick : false
    2021-07-01 08:02:21 -- notice  -- App\Models\Extensions\ConfigsHas::hasImagick -- 19 -- hasImagick : false
    2021-07-01 08:02:20 -- notice  -- App\Models\Extensions\ConfigsHas::hasImagick -- 19 -- hasImagick : false
    2021-07-01 08:02:20 -- notice  -- App\Models\Extensions\ConfigsHas::hasImagick -- 19 -- hasImagick : false
    2021-07-01 08:02:19 -- notice  -- App\Models\Extensions\ConfigsHas::hasImagick -- 19 -- hasImagick : false
    2021-07-01 08:02:19 -- notice  -- App\Models\Extensions\ConfigsHas::hasImagick -- 19 -- hasImagick : false
    2021-07-01 08:02:17 -- notice  -- App\Models\Extensions\ConfigsHas::hasImagick -- 19 -- hasImagick : false
    2021-07-01 08:02:17 -- notice  -- App\Models\Extensions\ConfigsHas::hasImagick -- 19 -- hasImagick : false
    2021-07-01 08:01:53 -- notice  -- App\ModelFunctions\SessionFunctions::log_as_admin -- 176 -- User (photomin) has logged in from 109.236.138.114

**Comment by d7415** [comment]
Looks like you have a low php `memory_limit`. See https://lycheeorg.github.io/docs/faq.html#i-cant-upload-large-photos

**Comment by ghost** [comment]
My php.ini had a limit of 32M. 
Thanks all for helping!! Sorry for opening an issue for a common mistake.
