### ISSUE TITLE
[Enhancement] Import images from network shares with a symbolic link

### ISSUE THREAD

**Issue by departet** [LycheeOrg/Lychee#1046]
Hey there,

couldnt find anything on this. Is it possible to view images that are available on a network share?
I dont want to duplicate the images, neither do i want to move them away from the network share.

The network share contains the images in a ordered structure.

**Comment by d7415** [comment]
If you mount the network share on the server then you should be able to do this as if it was a folder on the server, using the Import from Server functionality.

**Comment by departet** [comment]
Perfect, will try this!
