### ISSUE TITLE
Server error during search

### ISSUE THREAD

**Issue by endotronic** [LycheeOrg/Lychee#1054]
Very often (perhaps half the time?) my searches fail due to a 500 error in the XHR call.
<img width="374" alt="Screenshot 2021-07-09 234045" src="https://user-images.githubusercontent.com/1331112/125154560-5e6ea280-e10f-11eb-8432-339cf8101990.png">

I tried getting logs by running `php artisan lychee:logs` in the docker container (I am using the docker build), but there are no logs for this error.

Is there another place I can find logs? I've been all over the documentation (e.g. https://lycheeorg.github.io/docs/faq.html) and can't find anything else.

**Comment by endotronic** [comment]
Let me add that I am suspicious there may be a timeout somewhere, e.g. between Lychee and the db. I have quite a lot of images in there, so Lychee is already running quite slowly. If there is a timeout to increase, I'd love to know.

**Comment by ildyria** [comment]
> Let me add that I am suspicious there may be a timeout somewhere, e.g. between Lychee and the db. I have quite a lot of images in there, so Lychee is already running quite slowly. If there is a timeout to increase, I'd love to know.

You can try to increase the php maximum execution time. That would be a first guess. :|

I really need to add a Statistics pages to have an idea of how many pictures and albums are on a server. :)

**Comment by sunosv** [comment]
> > Let me add that I am suspicious there may be a timeout somewhere, e.g. between Lychee and the db. I have quite a lot of images in there, so Lychee is already running quite slowly. If there is a timeout to increase, I'd love to know.
> 
> You can try to increase the php maximum execution time. That would be a first guess. :|
> 
> I really need to add a Statistics pages to have an idea of how many pictures and albums are on a server. :)

May I ask when will update the Lychee version? I have been waiting  too long.

**Comment by endotronic** [comment]
Thanks for the quick reply! I'm not familiar with PHP development or Laravel. Can you tell me how I could do that, or at least let me know something about the serving stack so I can search the right terms?

**Comment by d7415** [comment]
These should point you in the right direction.

https://lycheeorg.github.io/docs/faq.html#i-cant-upload-large-photos
https://github.com/LycheeOrg/Lychee-Docker#advanced-configuration
https://github.com/LycheeOrg/Lychee-Docker/blob/master/default.conf#L81

**Comment by kamil4** [comment]
I'm wondering if entering a complete search string via copy-paste has a higher success rate for you than typing it in -- could you try? Lychee does find-as-you-type so if you type in just the first letter and then wait, it could result in a massive response that could be subject to either your execution time limit (as @ildyria pointed out above) or the memory limit...

**Comment by endotronic** [comment]
Thanks both of you, this is looking promising. I'll try soon and report back.

I had the same thought about copy/paste (though I was just thinking about many parallel requests and didn't have the clarity you have in thinking about the single letter case). I tried copy/paste and also simply loading a new browser tab with the search URL and the full request.

So it seems Apache is part of the serving stack? Should I expect to find logging there if processing was terminated due to timeout or memory usage?

**Comment by endotronic** [comment]
It seems my issue was memory related, since I now see that the default execution time is 3600 (seconds I presume), which I left configured that way. By increasing the memory limit, my issue is now resolved. Thanks!

For anyone else, the steps were at https://lycheeorg.github.io/docs/faq.html#i-cant-upload-large-photos as @d7415 linked.
