### ISSUE TITLE
[Enhancement] cli sync from from server with option to delete  

### ISSUE THREAD

**Issue by tomergam** [LycheeOrg/Lychee#1056]
I am using the command: `php artisan lychee:sync`
part of the cron job it will run every day, the android phone will push the photos to a directory in the server, 
but there is no option to "delete original" as in the GUI

maybe there is different API call, or it not exists for the CLI

**Comment by kamil4** [comment]
Indeed. It appears to be deliberately coded that way:
https://github.com/LycheeOrg/Lychee/blob/3e0a8c9bb7f6afd3bd380a8db82bc7e8192648b6/app/Console/Commands/Sync.php#L42
I guess the `lychee:sync` command was meant to be limited-utility (just to keep lychee in sync with an external directory) but I agree with you that it seems unnecessarily limiting...

**Comment by d7415** [comment]
Agreed. I see no reason not to expose that (or even some of the other options) to the command line.
