### ISSUE TITLE
I would like to propose to have "Search" on all views

### ISSUE THREAD

**Issue by SerenaButler** [LycheeOrg/Lychee#106]
It is now missing in Album and Image view.

**Comment by ildyria** [comment]
In Image view: **no**
In Album view: **could be interesting** This would allow to "filter" the result only to the current album (and sub-album).

**Comment by SerenaButler** [comment]
I think we should differ between search and filter. I like to have a "global" searchfield (on all sides) because I don't want the user to need to go back if he wants to do a new search ;-)
