### ISSUE TITLE
What is restricted account for?

### ISSUE THREAD

**Issue by ghost** [LycheeOrg/Lychee#1068]
Hi, 

Sorry, this is not a bug report, but I was not sure how to ask for that. I have noticed, that we can add ability to upload new files for a new user and there is "restricted account" option beside.

What does that mean? What are the limitations for restricted account? I couldn't find anything about that in documentation.

**Comment by d7415** [comment]
Technically it's in the documentation, but not very clearly. [This](https://github.com/LycheeOrg/Lychee/issues/748#issuecomment-704355002) is a pretty good explanation.
