### ISSUE TITLE
Error 22P02 on upload of some photos (Lychee fresh install; postgresql v13 DB)

### ISSUE THREAD

**Issue by zpetukhov** [LycheeOrg/Lychee#1070]
Here what I see in the logs table (below).
Obviously, the app tries to write a float number into an integer field and fails.
In this case, it tries to write 1438.3410138249 into "medium_width" column and fails.
Probably, this error is tied with postgresql database.
(I didn't change anything in settings, neither PG nor PHP or Lychee).

Additionally, after the errors (i tried to import a lot of images), I have 18 successfully imported images (their resolution is 1600x1200) and 18 records in "photos" table, but a lot of files in uploads/big, uploads/medium, uploads/small.

Something went wrong, error 22P02, SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type integer: "1438.3410138249" (SQL: insert into "photos" ("id", "checksum", "title", "url", "description", "tags", "width", "height", "type", "filesize", "iso", "aperture", "make", "model", "lens", "shutter", "focal", "taken_at", "taken_at_orig_tz", "latitude", "longitude", "altitude", "imgDirection", "location", "livePhotoContentID", "public", "star", "album_id", "owner_id", "thumb2x", "thumbUrl", "medium_width", "medium_height", "medium2x_width", "medium2x_height", "small_width", "small_height", "small2x_width", "small2x_height", "updated_at", "created_at") values (16277790297715, b08c3e8d4cc41ddcf2416ee4c6a921cc1f3737fb, IMG_20210720_195845, b08c3e8d4cc41ddcf2416ee4c6a921cc.jpg, , , 4624, 3472, image/jpeg, 2731113, 101, f/1.9, Xiaomi, Redmi Note 8 Pro, , 1/571 s, 5 mm, ?, ?, 36.237036111111, 32.297236111111, ?, ?, ?, ?, 0, 0, ?, 0, 1, b08c3e8d4cc41ddcf2416ee4c6a921cc.jpeg, 1438.3410138249, 1080, 2876.6820276498, 2160, 479.44700460829, 360, 958.89400921659, 720, 2021-08-01 00:50:35, 2021-08-01 00:50:35) returning "id")

In case some workaround is available to resolve the issue, I would like to try use it.
Thanks.

**Comment by d7415** [comment]
This was fixed in #1235.
