### ISSUE TITLE
A little question

### ISSUE THREAD

**Issue by elvisef** [LycheeOrg/Lychee#1074]
How to disable this bar ? I can't find any option.
It is still being displayed, even if sharing chosen galleries to other ppl.
It should not be displayed publicly (even if someone knows the password).

![2021-08-02_19-03-28](https://user-images.githubusercontent.com/25976749/127897825-76915ade-5bc4-4ee0-837c-383eea54bb57.png)

**Comment by ildyria** [comment]
go in .env :
```sh
APP_DEBUG=false

# enable or disable debug bar. By default it is disabled.
DEBUGBAR_ENABLED=false
```

**Comment by nagmat84** [comment]
This bar is only meant for debugging and development questions. It should not be shown if the `.env` file of your local installation has the following settings

    APP_ENV=production
    APP_DEBUG=false
    DEBUGBAR_ENABLED=false

Out of curiosity: Did you install the composer dependencies with development dependencies included? If you don't intend to develop, then the development dependencies are not necessary. If the development dependencies are not installed, then the bar should never be shown.
