### ISSUE TITLE
No images on album

### ISSUE THREAD

**Issue by Jorc0** [LycheeOrg/Lychee#1076]
For some reason, my pictures/GIFs arent showing on albums, images are set to public, also the album itself

**Steps to reproduce the behavior:**
1. Go to 'Main menu'
2. Click on 'Desired album'
3. No pics*
Also the image previews are shown on main page, but when i click on it, there are no images
Using fresh install of Lychee

![image](https://user-images.githubusercontent.com/48130077/128075642-07156cfd-68b9-400e-8bd7-3055506f52e9.png)

![image](https://user-images.githubusercontent.com/48130077/128074961-a57362fe-1a5c-47bf-998e-964dfbbeaa75.png)

### Output of the diagnostics  [REQUIRED]

<html>
<body>
<div class="content contentZoomIn leftMenu__open" style="user-select: none; transition: margin-left 0.5s ease 0s; margin: 0px 0px 0px 250px; padding: 50px 30px 33px 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; line-height: inherit; font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 12px; vertical-align: baseline; display: flex; flex-wrap: wrap; align-content: flex-start; width: calc(100% - 280px); max-width: calc(100vw - 10px); color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(29, 29, 29); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; min-height: calc(((100vh - 50px) - 33px) - 62px);"><pre class="logs_diagnostics_view" style="user-select: none; transition: color 0.3s ease 0s, opacity 0.3s ease-out 0s, transform 0.3s ease-out 0s, box-shadow 0.3s ease 0s, -webkit-transform 0.3s ease-out 0s, -webkit-box-shadow 0.3s ease 0s; margin: 0px auto; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: 14px; font-family: inherit; font-size: 12px; vertical-align: baseline; width: 1425.59px; color: rgb(204, 204, 204);"><pre id="content_diag_error" style="user-select: text; transition: color 0.3s ease 0s, opacity 0.3s ease-out 0s, transform 0.3s ease-out 0s, box-shadow 0.3s ease 0s, -webkit-transform 0.3s ease-out 0s, -webkit-box-shadow 0.3s ease 0s; margin: 0px; padding: 0px 30px 0px 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: monospace; font-size: 12px; vertical-align: baseline; width: fit-content;"><br class="Apple-interchange-newline">

    Diagnostics
    -------
    Warning: Dropbox import not working. dropbox_key is empty.
    Warning: Pictures that are rotated lose their metadata! Please install Imagick to avoid that.
    Warning: exec function has been disabled. You may experience some error 500, please report them to us.
</pre>
<pre id="content_diag_sys" style="user-select: text; transition: color 0.3s ease 0s, opacity 0.3s ease-out 0s, transform 0.3s ease-out 0s, box-shadow 0.3s ease 0s, -webkit-transform 0.3s ease-out 0s, -webkit-box-shadow 0.3s ease 0s; margin: 0px; padding: 0px 30px 0px 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: monospace; font-size: 12px; vertical-align: baseline; width: fit-content;">

    System Information
    --------------
    Lychee Version (release):        4.3.0
    DB Version:                      4.3.0
    
    composer install:                --no-dev
    APP_ENV:                         production
    APP_DEBUG:                       false
    
    System:                          Linux
    PHP Version:                     7.4
    Max uploaded file size:          500M
    Max post size:                   500M
    MySQL Version:                   10.3.30-MariaDB-cll-lve
    
    Imagick:                         -
    Imagick Active:                  1
    Imagick Version:                 -
    GD Version:                      2.2.5
</pre>
<a id="Get_Size_Lychee" class="basicModal__button button_left" style="user-select: none; transition: background-color 0.2s ease 0s; margin: 0px 0px 0px 24px; padding: 13px 0px 15px; border-width: 1px 0px 0px; border-top-style: solid; border-right-style: initial; border-bottom-style: initial; border-left-style: initial; border-top-color: rgba(0, 0, 0, 0.2); border-right-color: initial; border-bottom-color: initial; border-left-color: initial; border-image: initial; font-style: inherit; font-variant: inherit; font-weight: 700; font-stretch: inherit; line-height: inherit; font-family: inherit; font-size: 12px; vertical-align: baseline; display: inline-block; width: 400px; text-align: center; background: rgba(0, 0, 0, 0.02); color: rgb(34, 147, 236); box-shadow: rgba(255, 255, 255, 0.02) 0px 1px 0px inset, rgba(0, 0, 0, 0.2) 1px 0px 0px inset; cursor: default; border-radius: 5px;"><svg class="iconic"><use xlink:href="#reload"><svg id="reload" viewBox="0 0 8 8"><path d="M4 0c-2.201 0-4 1.799-4 4s1.799 4 4 4c1.104 0 2.092-.456 2.813-1.188l-.688-.688c-.54.548-1.289.875-2.125.875-1.659 0-3-1.341-3-3s1.341-3 3-3c.834 0 1.545.354 2.094.906l-1.094 1.094h3v-3l-1.188 1.188c-.731-.72-1.719-1.188-2.813-1.188z"></path></svg></use></svg>Request space usage</a><pre id="content_diag_conf" style="user-select: text; transition: color 0.3s ease 0s, opacity 0.3s ease-out 0s, transform 0.3s ease-out 0s, box-shadow 0.3s ease 0s, -webkit-transform 0.3s ease-out 0s, -webkit-box-shadow 0.3s ease 0s; margin: 0px; padding: 0px 30px 0px 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: monospace; font-size: 12px; vertical-align: baseline; width: fit-content;">

    Config Information
    --------------
    version:                         040300
    check_for_updates:               0
    sorting_Photos_col:              takestamp
    sorting_Photos_order:            ASC
    sorting_Albums_col:              max_takestamp
    sorting_Albums_order:            ASC
    imagick:                         1
    skip_duplicates:                 0
    small_max_width:                 0
    small_max_height:                360
    medium_max_width:                1920
    medium_max_height:               1080
    lang:                            es
    layout:                          2
    image_overlay_type:              desc
    default_license:                 CC-BY-NC-4.0
    compression_quality:             90
    full_photo:                      1
    delete_imported:                 0
    Mod_Frame:                       1
    Mod_Frame_refresh:               30
    thumb_2x:                        1
    small_2x:                        1
    medium_2x:                       1
    landing_page_enable:             0
    landing_owner:                   John Smith
    landing_title:                   John Smith
    landing_subtitle:                Cats, Dogs &amp; Humans Photography
    landing_facebook:                https://www.facebook.com/JohnSmith
    landing_flickr:                  https://www.flickr.com/JohnSmith
    landing_twitter:                 https://www.twitter.com/JohnSmith
    landing_instagram:               https://instagram.com/JohnSmith
    landing_youtube:                 https://www.youtube.com/JohnSmith
    landing_background:              dist/cat.jpg
    site_title:                      Lychee v4
    site_copyright_enable:           1
    site_copyright_begin:            2019
    site_copyright_end:              2019
    additional_footer_text:          
    display_social_in_gallery:       0
    public_search:                   0
    SL_enable:                       0
    SL_for_admin:                    0
    public_recent:                   0
    recent_age:                      1
    public_starred:                  0
    downloadable:                    0
    photos_wraparound:               1
    map_display:                     0
    zip64:                           1
    map_display_public:              0
    map_provider:                    Wikimedia
    force_32bit_ids:                 0
    map_include_subalbums:           0
    update_check_every_days:         3
    has_exiftool:                    0
    share_button_visible:            0
    import_via_symlink:              0
    has_ffmpeg:                      0
    location_decoding:               0
    location_decoding_timeout:       30
    location_show:                   1
    location_show_public:            0
    rss_enable:                      0
    rss_recent_days:                 7
    rss_max_items:                   100
    prefer_available_xmp_metadata:   0
    editor_enabled:                  1
    lossless_optimization:           0
    swipe_tolerance_x:               150
    swipe_tolerance_y:               250
    local_takestamp_video_formats:   .avi|.mov
    log_max_num_line:                1000
    unlock_password_photos_with_url_param: 0
    nsfw_visible:                    1
    nsfw_blur:                       0
    nsfw_warning:                    0
    nsfw_warning_admin:              0
    map_display_direction:           1
    album_subtitle_type:             oldstyle
    upload_processing_limit:         4
    public_photos_hidden:            1
</pre>
</pre></div><div class="sidebar" style="user-select: none; transition: transform 0.3s cubic-bezier(0.51, 0.92, 0.24, 1) 0s, -webkit-transform 0.3s cubic-bezier(0.51, 0.92, 0.24, 1) 0s; margin: 0px; padding: 0px; border-width: 0px 0px 0px 1px; border-top-style: initial; border-right-style: initial; border-bottom-style: initial; border-left-style: solid; border-top-color: initial; border-right-color: initial; border-bottom-color: initial; border-left-color: rgba(0, 0, 0, 0.2); border-image: initial; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; line-height: inherit; font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 12px; vertical-align: baseline; position: fixed; top: 49px; right: -360px; width: 350px; height: calc(100% - 49px); background-color: rgba(25, 25, 25, 0.98); transform: translateX(0px); z-index: 4; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="sidebar__header" style="user-select: none; transition: color 0.3s ease 0s, opacity 0.3s ease-out 0s, transform 0.3s ease-out 0s, box-shadow 0.3s ease 0s, -webkit-transform 0.3s ease-out 0s, -webkit-box-shadow 0.3s ease 0s; margin: 0px; padding: 0px; border-width: 1px 0px 0px; border-top-style: solid; border-right-style: initial; border-bottom-style: initial; border-left-style: initial; border-top-color: rgb(34, 147, 236); border-right-color: initial; border-bottom-color: initial; border-left-color: initial; border-image: initial; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-size: 12px; vertical-align: baseline; float: left; height: 49px; width: 350px; background: linear-gradient(rgba(255, 255, 255, 0.02), rgba(0, 0, 0, 0));"><h1 style="user-select: text; transition: color 0.3s ease 0s, opacity 0.3s ease-out 0s, transform 0.3s ease-out 0s, box-shadow 0.3s ease 0s, -webkit-transform 0.3s ease-out 0s, -webkit-box-shadow 0.3s ease 0s; margin: 15px 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 700; font-stretch: inherit; line-height: inherit; font-family: inherit; font-size: 16px; vertical-align: baseline; position: absolute; width: 350px; color: rgb(255, 255, 255); text-align: center;">About</h1></div><div class="sidebar__wrapper" style="user-select: none; transition: color 0.3s ease 0s, opacity 0.3s ease-out 0s, transform 0.3s ease-out 0s, box-shadow 0.3s ease 0s, -webkit-transform 0.3s ease-out 0s, -webkit-box-shadow 0.3s ease 0s; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-size: 12px; vertical-align: baseline; float: left; height: calc(100% - 49px); width: 350px; overflow: auto;"><div class="sidebar__divider" style="user-select: none; transition: color 0.3s ease 0s, opacity 0.3s ease-out 0s, transform 0.3s ease-out 0s, box-shadow 0.3s ease 0s, -webkit-transform 0.3s ease-out 0s, -webkit-box-shadow 0.3s ease 0s; margin: 0px; padding: 12px 0px 8px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-size: 12px; vertical-align: baseline; float: left; width: 350px; box-shadow: none;"><h1 style="user-select: text; transition: color 0.3s ease 0s, opacity 0.3s ease-out 0s, transform 0.3s ease-out 0s, box-shadow 0.3s ease 0s, -webkit-transform 0.3s ease-out 0s, -webkit-box-shadow 0.3s ease 0s; margin: 0px 0px 0px 20px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 700; font-stretch: inherit; line-height: inherit; font-family: inherit; font-size: 14px; vertical-align: baseline; color: rgba(255, 255, 255, 0.6);"></h1></div>
</div></div>
</body>
</html>

### Browser and system

OperaGX LVL3 (core: 77.0.4054.275)

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36 OPR/77.0.4054.275

**Comment by kamil4** [comment]
We've seen similar reports lately. In at least some instances, setting `force_32bit_ids` to `1` in the advanced config solves the problem (you should recreate the album and reupload the pictures though). Let us know if that helps!

**Comment by Jorc0** [comment]
> We've seen similar reports lately. In at least some instances, setting `force_32bit_ids` to `1` in the advanced config solves the problem (you should recreate the album and reupload the pictures though). Let us know if that helps!

FIXED TYVM
