### ISSUE TITLE
Thumbnails on map broken

### ISSUE THREAD

**Issue by firetora** [LycheeOrg/Lychee#1077]
### Detailed description of the problem [REQUIRED]
Thumbnails in the map view are broken. Was unable to find any online records of the same issue.

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Enable Maps
2. Go to 'Main Menu'
3. Click on desired album
4. Click on Map
5. Thumbnail Images broken - thumbnail image URL directs to [domain]/null
    Preview shows when broken thumbnail is clicked

**Screenshots**
![image](https://user-images.githubusercontent.com/18279587/128337134-55166f27-3dfe-46a2-bf4c-6c0c604fbd9e.png)

### Output of the diagnostics  [REQUIRED]
![image](https://user-images.githubusercontent.com/18279587/128336467-ddec955b-9a0a-4e1a-94af-7dbb5edaee0e.png)

### Browser and system
Linux Mint 20.2 Uma, base: Ubuntu 20.04 focal
Firefox 90.0.2 (64-bit)

**Comment by julianwachholz** [comment]
Thumbnails do work in the latest v4.3.4 version

**Comment by yuorfaec** [comment]
For me, it works on desktop but is broken on mobile. On mobile I tried on Android Firefox & Chrome as well as iPadOS Safari & Chrome. 4.3.4 on Ubuntu 20.04
<img src="https://user-images.githubusercontent.com/66703188/142553190-8fd3943d-a468-4a78-9b4c-98cef4e030a1.png" width="200">

**Comment by yuorfaec** [comment]
Not sure if a recent update finally knocked it out, but it's no longer a problem for me on Lychee 4.4.0

**Comment by LouisVallat** [comment]
Is it fixed for you too @firetora ?

**Comment by firetora** [comment]
Yeah, looks to be working fine with the latest docker image.
