### ISSUE TITLE
Can not reset admin password

### ISSUE THREAD

**Issue by AidPioneerJH** [LycheeOrg/Lychee#1078]
Hello - absolute newbie here,

I recently set up lychee on my web server and I am in love with it. Unfortunately I lost the password for the admin account. 

Following the instructions of the FAQ I used the macOS Terminal to connect to the web server and lychee and tried the suggested command

> php artisan lychee:reset_admin

However this did not work out - the response was 

> Could not open input file: artisan

Did I forgot to enter a command or do I need to do this action in another program / environment? 

I am fairly new to this thing and could need a little help.

**Comment by ildyria** [comment]
Which version of Lychee are you using?
Are you sure you are on the version 4?

**Comment by AidPioneerJH** [comment]
I am running v. 4.3.4

**Comment by ildyria** [comment]
Are you in the lychee folder (not the public folder) when you do the `php artisan` command? because honestly, there is absolutely no reason why this should not work.

**Comment by fqx** [comment]
@ildyria What is the default username and password after resetting?

**Comment by fqx** [comment]
> @ildyria What is the default username and password after resetting?

I see, I didn't run the reset command as www-data.
If it's correctly reset, Lychee will ask a new username and password.
