### ISSUE TITLE
Error during installation of V4.3.4

### ISSUE THREAD

**Issue by danieldotnet** [LycheeOrg/Lychee#1079]
### Detailed description of the problem [REQUIRED]
After entering the login data for the database --> click on Install the message "500 Server error" appears. See screenshot for more details.

![error](https://user-images.githubusercontent.com/18641962/128703320-8b608034-440f-4f05-b3f0-d3b100b3a5c5.PNG)

PHP Version 8.0.7

### Browser and system
Firefox Browser on Windows 10 64-Bit

If you need more details please let me know.
Thank you.

**Comment by ildyria** [comment]
Can you check that the function `exec` is indeed enabled for your php installation. I find this surprising that it crashes here.

**Comment by danieldotnet** [comment]
The exec function is active, but the error still occurs. I have again deleted the database, recreated, error still comes at the same place. In the database 10 tables were created.

**Comment by nagmat84** [comment]
Is this issue still relevant? Can it be closed?

**Comment by nagmat84** [comment]
As there has been no response from the original poster in a timely manner, I am going to close this issue.
