### ISSUE TITLE
Fresh install - Session::init 404 error

### ISSUE THREAD

**Issue by romleinster** [LycheeOrg/Lychee#1080]
### Detailed description of the problem [REQUIRED]
Possibly dupe of https://github.com/LycheeOrg/Lychee/issues/52 but not sure how to apply nginx settings in the fix to apache.
did an install and I'm getting an application error (Server error or API not found) when pulling up index.php
using apache, I have in httpd.conf:
```
258 <Directory /srv/http/Lychee/public>
259         DirectoryIndex index.php
260         AllowOverride All
261         Options Indexes FollowSymLinks
262         Require all granted
263 </Directory>
...
540 <VirtualHost *:80>
541         DocumentRoot "/srv/http/"

543         Alias /lychee "/srv/http/Lychee/public"
544 RewriteEngine on
...
...
547 </VirtualHost>
```
I have that same alias copied into a vhost listening on 443 for https (which I'm using when the error occurs). 
I've tried using both the .htaccess that ships in Lychee/public and the alternative file from the install doc.

my .env:
```
APP_NAME=Lychee
APP_ENV=production
APP_KEY=base64:<myKey>
APP_DEBUG=true
APP_URL=<myURL>

# enable or disable debug bar. By default it is disabled.
DEBUGBAR_ENABLED=true

LOG_CHANNEL=stack

##############################################################################
# IMPORTANT: To migrate from Lychee v3 you *MUST* use the same MySQL/MariaDB #
#            server as v3.                                                   #
##############################################################################

# Table prefix (e.g. lychee_) of a Lychee v3 instance for migration
#DB_OLD_LYCHEE_PREFIX=

# DB_CONNECTION can be sqlite, mysql or pgsql. For sqlite the other entries are
# not required, but an existing sqlite3 database may be specified if desired. In
# this case, please use an absolute path. DB_DATABASE may be omitted but should
# *not* be left blank.
DB_CONNECTION=mysql
DB_HOST=localhost
DB_PORT=<myPort>
DB_DATABASE=<myDB>
DB_USERNAME=<myUser>
DB_PASSWORD=<myPassword>
DB_LOG_SQL=false

TIMEZONE=UTC

# folders in which the files will be stored
# LYCHEE_DIST="/serverfiles/Lychee-Laravel/public/dist/"
# LYCHEE_UPLOADS="/serverfiles/Lychee-Laravel/public/uploads/"

# url to access those files
# LYCHEE_DIST_URL="dist/"
# LYCHEE_UPLOADS_URL="uploads/"

BROADCAST_DRIVER=log
CACHE_DRIVER=file
SESSION_DRIVER=file
SESSION_LIFETIME=120
QUEUE_DRIVER=sync

SECURITY_HEADER_HSTS_ENABLE=false

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=
MAIL_PORT=
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_ENCRYPTION=
MAIL_FROM_NAME=
MAIL_FROM_ADDRESS=

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

```
In Chrome I'm seeing:
```
description: "Server error or API not found."
params: {function: "Session::init"}
```

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
fresh install from release (clone repo)
create new database/user
composer install --no-dev
copy .env file
php artisan key:generate
php artisan migrate

### Browser and system
using arch 5.13.7 / apache 2.4.48-1 / mariadb 10.6.3-1 / php 8.0.9-1

**Comment by d7415** [comment]
>  php artisan key;generate

Just checking this was just a typo here, not in the shell?

**Comment by romleinster** [comment]
yeah that's just a typo, not pasted from shell, I'll  edit the post

**Comment by qiuaibo** [comment]
I have the same problem:
![1](https://user-images.githubusercontent.com/29228484/141062523-e6048640-a8d4-447c-bdca-57b68ea90897.png)
![2](https://user-images.githubusercontent.com/29228484/141062538-84188598-3a56-4da4-9073-711855c41f26.png)

**Comment by d7415** [comment]
As no-one else has dived in here, you've followed https://lycheeorg.github.io/docs/installation.html#apache ?

**Comment by ildyria** [comment]
No answer.
