### ISSUE TITLE
User Menu problem

### ISSUE THREAD

**Issue by homer276** [LycheeOrg/Lychee#1081]
Hi,
I just recently installed the version 4.3.4 on my server , installation went well . No complains. However only the menu Item "Users" does not work as expected. I always see the message "Server error or api not found"
Installation was done from the release branch. 
![Bildschirmfoto 2021-08-10 um 08 03 53](https://user-images.githubusercontent.com/48461825/128816693-837988ca-1562-4eb3-aa4c-709e7acf8f4a.png)
![Bildschirmfoto 2021-08-10 um 08 04 22](https://user-images.githubusercontent.com/48461825/128816694-ebdafb5c-478a-4592-b8e5-99ed8ea9fdde.png)
![Bildschirmfoto 2021-08-10 um 08 04 11](https://user-images.githubusercontent.com/48461825/128816695-22b3b02f-a9c0-45aa-adbc-4a127cf6803d.png)
![Bildschirmfoto 2021-08-10 um 08 03 01](https://user-images.githubusercontent.com/48461825/128816697-0d2354f6-9979-4820-89f3-49e3ebab23b4.png)

Any idea what is going on here ? I saw a post with the same problem but for another webserver

Tks
Henning

**Comment by Butzy79** [comment]
Hi,
I've the same issue having the same configuration.

**Comment by LouisVallat** [comment]
Hi,
I think we need a bit more information on this issue to reproduce it, such as:
- Which version did you setup (i.e. Docker?) and if you're using a reverse proxy/webserver, which one are you using (i.e. Nginx or Apache)?
- Can you also give us the output of the web browser console when facing this error please?
