### ISSUE TITLE
[Enhancement] Option to make new imports public, or to default all new imports to public

### ISSUE THREAD

**Issue by jgarcia-opsmx** [LycheeOrg/Lychee#1083]
*Explain in a few words which functionality or improvements you would like to see in Lychee.*

I'm importing a large number of photos in subfolders, but they are marked "private" by default. Unfortunately, for lack of a recursive privacy switch, I am going to have to enter a hundred folders manually to mark them public.

**Comment by kamil4** [comment]
Agreed.

In the meantime, if you are comfortable with accessing your database directly using SQL queries, you can do it that way; the column is called `public`.

**Comment by ildyria** [comment]
Duplicate: https://github.com/LycheeOrg/Lychee/issues/1363
