### ISSUE TITLE
[SOLVED] : Cannot log in after updating from 4.3.0 to 4.3.4.

### ISSUE THREAD

**Issue by ericxuo** [LycheeOrg/Lychee#1085]
Hi,

I've just updated Lychee from version 4.3.0 to 4.3.4 (Linux, Mageia8, PHP 8.0.9).
Everything looks correct : 
# more installed.log 
Lychee INSTALLED on 2021-08-14 16:04:53

but I can't connect anymore using the username+password that I've already defined in version 4.3.0.
When connecting to the sql database, here is what I get in the "users" section : 
![image](https://user-images.githubusercontent.com/9089499/129452841-ec4a3c8d-f84a-47be-8afe-7515baec114d.png)

I've copied the .env file from version 4.3.0 into the .env section of the update gui of 4.3.4, **including the APP_KEY variable**. 
Now, the 2 .env files differ only from the APP_KEY section.

Do you know how to either create a new user or to re-enable the previous one ?

Regards.

Xuo.

**Comment by ericxuo** [comment]
Hi,

The issue was coming from my password. For some unknown reason, if I copy/paste the password, it does not work. If I enter it manually, it does.

Regards.

Xuo.

**Comment by LouisVallat** [comment]
Hi!
If the issue is Solved, maybe it could be closed?
