### ISSUE TITLE
error with installer permissions step 

### ISSUE THREAD

**Issue by Ibrahim-Albrahim** [LycheeOrg/Lychee#1089]
hello,
![‪Lychee Installer - Google Chrome‬ 14_01_43 10_30_01 م (2)](https://user-images.githubusercontent.com/86062781/130367757-59643261-d8d9-4f02-9f69-9d026d66f276.png)

can you help what is the first directory that I need to edit it's permission ?

**Comment by d7415** [comment]
By the looks of it, the lychee root (i.e. `.`), the level above `public`, etc

**Comment by Ibrahim-Albrahim** [comment]
> By the looks of it, the lychee root (i.e. `.`), the level above `public`, etc

couldn't figure it out , thanks I get it now
