### ISSUE TITLE
Cannot install: Undefined array key "format" 

### ISSUE THREAD

**Issue by chrisfoster121** [LycheeOrg/Lychee#1091]
I am currently trying to install Lychee using Apache2 with PHP 8.0 and have installed the necessary PHP extensions. When I run composer install --no-dev I get the following output  for the optimized autoload files:

```
Generating optimized autoload files
>Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In ConfigurationValidator.php line 15:
                                
  Undefined array key "format"  
                                

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1
```

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Go to /var/www/html/Lychee/
2. Run composer install --no-dev
3. See error*

With `composer install --no-dev`
![image](https://user-images.githubusercontent.com/36481654/130556970-4ae79d9d-5fb1-4183-ad51-5bb7a7e90337.png)

With `composer update` 
![image](https://user-images.githubusercontent.com/36481654/130557101-1bde9c4a-b07e-4dda-ab30-9a9fcba267c6.png)

### Output of the diagnostics  
```
php artisan lychee:diagnostics

In ConfigurationValidator.php line 15:
                                
  Undefined array key "format"  
                                

```
### Browser and system
Cant get to browser as I cant get it installed. 

```
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```

**Comment by ildyria** [comment]
Yes, this is thanks to Spatie...

Please try this branch: https://github.com/LycheeOrg/Lychee/tree/upgrade-composer
I fixed it, but merging this branch will require to drop support for 7.4 which I would rather avoid before November. :angry:

**Comment by chrisfoster121** [comment]
Thank you for the swift response! That seems to have worked. I was able to get all the way up to the apache webserver configuration on the branch you suggested. At this step I was able to load `xx.xx.xx.xx/Lychee/public/info.php` from another device on the local network. It was a page saying to enable rewrite which I did with `a2enmod rewrite`. After this did not work I then replaced the lines in .htaccess to

```
Options +FollowSymLinks -Indexes
RewriteEngine On

RewriteCond %{HTTP:Authorization} .
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^ index.php [L]
```
This has resulted in an error 404 on the same page that was previously able to load.

`php artisan lychee:diagnostics` provides me with the following output:

```
In Connection.php line 678:
                                                          
  could not find driver (SQL: PRAGMA foreign_keys = ON;)  
                                                          

In Exception.php line 18:
                         
  could not find driver  
                         

In PDOConnection.php line 39:
                         
  could not find driver  
                         
```

Is this user error or no?

**Comment by d7415** [comment]
`could not find driver ` usually means the php extensions for the configured database are not available.

**Comment by chrisfoster121** [comment]
Forgive my ignorance but could this be a result of using MariaDB? I see in the `../config/database.php` file there are connections listed for sqlite, mysql, pgsql, sqlsrv but not for mariadb. Is this intended to work out of the box so to speak with mariadb?

**Comment by nagmat84** [comment]
Yes, it does work with MariaDB. The client-server protocols of MySQL and MariaDB are binary compatible. MariaDB is a drop-in replacement for MySQL and as far as I know nowadays most Linux distros ship with MariaDB instead of MySQL due to licensing issues. I also use MariaDB for my development test setup.

**Comment by d7415** [comment]
That might explain the "Could not find driver" though - use `mysql` for your `DB_CONNECTION`.

**Comment by nagmat84** [comment]
What is the status of this issue? We are on the verge of migrating to PHP 8.0 officially. Today, I upgraded both my development installation on Gentoo and my productive installation on Ubuntu to PHP 8.0 and could not reproduce the exception as reported by the TO. I guess that Spatie has fixed the bug upstream and that the current version of Spatie does not conflict with PHP 8.0 anymore?

So can this issue be closed?

**Comment by ildyria** [comment]
Can this issue be closed? IMHO Yes. 🙂

⁣Télécharger BlueMail pour Android ​

Le 20 nov. 2021 à 19:52, à 19:52, Matthias Nagel ***@***.***> a écrit:

**Comment by nagmat84** [comment]
This issue affects an older version of Spatie which had problems with PHP 8 back at the time when the issue were reported. Meanwhile, newer version of Spatie have been fixed upstream. So the issue can be closed.
