### ISSUE TITLE
[Enhancement] Install on a Shared host

### ISSUE THREAD

**Issue by reszel** [LycheeOrg/Lychee#1099]
*Explain in a few words which functionality or improvements you would like to see in Lychee.*
like I install Wordpress: Peace of cake!
No running Linux commands.
No editing files.
Just as easy as Wordpess install is! PLEASE!

**Comment by ildyria** [comment]
Hi,

Here is a tutorial to use Lychee without editing files and without running linux commands.

1. Download the latest release, currently: https://github.com/LycheeOrg/Lychee/releases/download/v4.3.4/Lychee.zip
2. Extract where need to be on your webserver.
3. Access with your browser & profit.

Does not work? I guess it is time for you to learn to use basic Linux commands.
It says dependencies are missing? I guess you are out of luck if you don't want to run Linux commands.
