### ISSUE TITLE
Character limitation of table column `logs.function` causes server error 500 for deployments with long installation path

### ISSUE THREAD

**Issue by pacocalvari** [LycheeOrg/Lychee#1102]
### Detailed description of the problem [REQUIRED]
When I try to upload an image to an album, that already is in any other album from any other user I get "upload failed" message and browser console shows an error 500

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Upload a (new) image to an album
2. log in with another account to another album (optional) 
3. upload the same image
4. get error message
5. ghostbuster will find the orphan(s) afterwards in big-folder! 

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

### Output of the diagnostics  [REQUIRED]
Diagnostics
    -------
    Warning: Dropbox import not working. dropbox_key is empty.
    Warning: You may experience problems when uploading a photos of large size. Take a look in the FAQ for details.
    Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.
    Info: Latest version of PHP is 8

    System Information
    --------------
    Lychee Version (release):        4.3.4
    DB Version:                      4.3.4
    
    composer install:                --no-dev
    APP_ENV:                         production
    APP_DEBUG:                       true
    
    System:                          Linux
    PHP Version:                     7.4
    Max uploaded file size:          64M
    Max post size:                   64M
    MySQL Version:                   10.6.4-MariaDB-1:10.6.4+maria~bionic
    
    Imagick:                         1
    Imagick Active:                  1
    Imagick Version:                 1687
    GD Version:                      bundled (2.1.0 compatible)

    Config Information
    --------------
    version:                         040304
    check_for_updates:               0
    sorting_Photos_col:              taken_at
    sorting_Photos_order:            DESC
    sorting_Albums_col:              max_taken_at
    sorting_Albums_order:            ASC
    imagick:                         1
    skip_duplicates:                 0
    small_max_width:                 0
    small_max_height:                360
    medium_max_width:                1920
    medium_max_height:               1080
    lang:                            de
    layout:                          1
    image_overlay_type:              desc
    default_license:                 none
    compression_quality:             90
    full_photo:                      1
    delete_imported:                 0
    Mod_Frame:                       1
    Mod_Frame_refresh:               30
    thumb_2x:                        1
    small_2x:                        1
    medium_2x:                       1
    landing_page_enable:             0
    landing_owner:                   John Smith
    landing_title:                   John Smith
    landing_subtitle:                Cats, Dogs & Humans Photography
    landing_facebook:                https://www.facebook.com/JohnSmith
    landing_flickr:                  https://www.flickr.com/JohnSmith
    landing_twitter:                 https://www.twitter.com/JohnSmith
    landing_instagram:               https://instagram.com/JohnSmith
    landing_youtube:                 https://www.youtube.com/JohnSmith
    landing_background:              dist/cat.jpg
    site_title:                      Fotos - KL
    site_copyright_enable:           0
    site_copyright_begin:            2019
    site_copyright_end:              2019
    additional_footer_text:          
    display_social_in_gallery:       0
    public_search:                   0
    SL_enable:                       0
    SL_for_admin:                    0
    public_recent:                   0
    recent_age:                      1
    public_starred:                  0
    downloadable:                    0
    photos_wraparound:               1
    map_display:                     0
    zip64:                           1
    map_display_public:              0
    map_provider:                    Wikimedia
    force_32bit_ids:                 0
    map_include_subalbums:           0
    update_check_every_days:         3
    has_exiftool:                    1
    share_button_visible:            0
    import_via_symlink:              0
    has_ffmpeg:                      1
    location_decoding:               0
    location_decoding_timeout:       30
    location_show:                   1
    location_show_public:            0
    rss_enable:                      0
    rss_recent_days:                 7
    rss_max_items:                   100
    prefer_available_xmp_metadata:   0
    editor_enabled:                  1
    lossless_optimization:           0
    swipe_tolerance_x:               150
    swipe_tolerance_y:               250
    local_takestamp_video_formats:   .avi|.mov
    log_max_num_line:                1000
    unlock_password_photos_with_url_param: 0
    nsfw_visible:                    1
    nsfw_blur:                       0
    nsfw_warning:                    0
    nsfw_warning_admin:              0
    map_display_direction:           1
    album_subtitle_type:             oldstyle
    upload_processing_limit:         4
    public_photos_hidden:            1

### Browser and system
Firefox/Android
Chrome/Android
Firefox/Win10

**Comment by pacocalvari** [comment]
skip-duplicates true/false doesn't seem to make any difference

**Comment by nagmat84** [comment]
Even if the option `skip_duplicates` was set, you should not receive an error 500 but a proper and user-friendly warning that the photo has been skipped, because it is a duplicate.

An error 500 means that there is a more catastrophic failure which has not been foreseen by the application logic.

But everything else (e.g. uploading of images for the first time, creating albums, etc.) does work?

**Comment by pacocalvari** [comment]
Yes, everything else works fine. (Except for video-thumbnails, but thats not a problem at the moment)
I really like the sofftware a lot! 
batch-uploading also works fine.

When the error occurs, the browser console shows this as a response from the XMLHTTPrequest:

SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'function' at row 1 (SQL: insert into `logs` (`type`, `function`, `line`, `text`, `updated_at`, `created_at`) values (notice, /var/www/vhosts/xyz/httpdocs/Lychee/app/Actions/Photo/Strategies/StrategyDuplicate.php, 31, Nothing to store, image is a duplicate, 2021-09-18 10:40:10, 2021-09-18 10:40:10)) (500 Internal Server Error) 
[...]

**Comment by nagmat84** [comment]
Thanks, that's an obvious bug. The upload function correctly identifies the photo as a duplicate and tries to log that event to the log. Unfortunately, the logging fails and cause the 500 error. The cause of the problem is that the path of your installation is longer than can be stored in the column of the log table.

We need to fix that. We may increase the character limit of the table column. On top,  we should ensure that the string is trucated before written to the log in order to avoid such failures and make logging more robust. In this particular case, we could also modify the logging such that only the relative path is logged.

**Comment by pacocalvari** [comment]
ok. I am happy it was an obvious one :)
I just changed the "functions"-field in logs-table from varchar(100) to varchar(200) and now uploads work as expected. I also get the user friendly notices of skipped files.
Thanks a lot and keep up the good work :)
