### ISSUE TITLE
[Bug] Lens name not displayed correcly

### ISSUE THREAD

**Issue by LouisVallat** [LycheeOrg/Lychee#1107]
### Detailed description of the problem [REQUIRED]
The lens EXIF data seems to be read but displayed uncorrectly, in HEX format.

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Go to "upload a new picture"
2. Upload picture with Lens metadata
3. Check Lens metadata in Lychee

**Screenshots**
These are the different views for the same EXIF data, from a Nkon D7100, shot in RAW.
In DarkTable : 
![image](https://user-images.githubusercontent.com/33779779/134823878-9a714fe7-de03-4f76-96e4-f149ee21f9bd.png)

In Lychee : 
![image](https://user-images.githubusercontent.com/33779779/134823948-05574356-7d0f-480b-876e-3ce4f5f0631d.png)

In EXIF reader online : 
![image](https://user-images.githubusercontent.com/33779779/134823976-7cbb66b4-d9ba-44ea-b7a7-68e5b414fbfa.png)

### Output of the diagnostics  [REQUIRED]
```txt



    Diagnostics
    -------
    Warning: Dropbox import not working. dropbox_key is empty.
    Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.
    Info: Latest version of PHP is 8




    System Information
    --------------
    Lychee Version (release):        4.3.4
    DB Version:                      4.3.4
    
    composer install:                --no-dev
    APP_ENV:                         production
    APP_DEBUG:                       false
    
    System:                          Linux
    PHP Version:                     7.4
    Max uploaded file size:          500M
    Max post size:                   5G
    MySQL Version:                   8.0.26
    
    Imagick:                         1
    Imagick Active:                  1
    Imagick Version:                 1803
    GD Version:                      bundled (2.1.0 compatible)




    Config Information
    --------------
    version:                         040304
    check_for_updates:               0
    sorting_Photos_col:              taken_at
    sorting_Photos_order:            DESC
    sorting_Albums_col:              id
    sorting_Albums_order:            DESC
    imagick:                         1
    skip_duplicates:                 0
    small_max_width:                 0
    small_max_height:                360
    medium_max_width:                1920
    medium_max_height:               1080
    lang:                            en
    layout:                          1
    image_overlay_type:              exif
    default_license:                 reserved
    compression_quality:             90
    full_photo:                      1
    delete_imported:                 1
    Mod_Frame:                       1
    Mod_Frame_refresh:               30
    thumb_2x:                        1
    small_2x:                        1
    medium_2x:                       1
    landing_page_enable:             0
    landing_owner:                   Louis Vallat
    landing_title:                   Louis Vallat
    landing_subtitle:                Landscapes, technology and trains.
    landing_facebook:                
    landing_flickr:                  
    landing_twitter:                 https://www.twitter.com/VallatLouis
    landing_instagram:               
    landing_youtube:                 
    landing_background:              dist/cat.jpg
    site_title:                      Lychee - Louis Vallat
    site_copyright_enable:           1
    site_copyright_begin:            2019
    site_copyright_end:              2021
    additional_footer_text:          
    display_social_in_gallery:       1
    public_search:                   1
    SL_enable:                       0
    SL_for_admin:                    0
    public_recent:                   0
    recent_age:                      1
    public_starred:                  0
    downloadable:                    0
    photos_wraparound:               1
    map_display:                     0
    zip64:                           1
    map_display_public:              0
    map_provider:                    Wikimedia
    force_32bit_ids:                 0
    map_include_subalbums:           0
    update_check_every_days:         3
    has_exiftool:                    1
    share_button_visible:            0
    import_via_symlink:              0
    has_ffmpeg:                      1
    location_decoding:               0
    location_decoding_timeout:       30
    location_show:                   1
    location_show_public:            0
    rss_enable:                      0
    rss_recent_days:                 7
    rss_max_items:                   100
    prefer_available_xmp_metadata:   0
    editor_enabled:                  1
    lossless_optimization:           0
    swipe_tolerance_x:               150
    swipe_tolerance_y:               250
    local_takestamp_video_formats:   .avi|.mov
    log_max_num_line:                1000
    unlock_password_photos_with_url_param: 0
    nsfw_visible:                    0
    nsfw_blur:                       0
    nsfw_warning:                    0
    nsfw_warning_admin:              0
    map_display_direction:           1
    album_subtitle_type:             oldstyle
    upload_processing_limit:         4
    public_photos_hidden:            1
```

### Browser and system
Docker version, Firefox Nightly 94, Lychee 4.3.4

**Comment by ildyria** [comment]
Most likely related to https://github.com/LycheeOrg/php-exif

>     has_exiftool:                    1

So you have exiftool (yay).

Can you check the output in **command line** for this specific image ? 

`exiftool <your image>`

Note that the hex is most likely some UUID for this lens as it correspond in UTF-8 to `-j,< ` .

**Comment by LouisVallat** [comment]
> Most likely related to https://github.com/LycheeOrg/php-exif
> 
> > ```
> > has_exiftool:                    1
> > ```
> 
> So you have exiftool (yay).
> 
> Can you check the output in **command line** for this specific image ?
> 
> `exiftool <your image>`
> 
> Note that the hex is most likely some UUID for this lens as it correspond in UTF-8 to `�-j,< �` .

Hey, thank you for taking the time to check on my issue.

After executing bash as root in the live docker container, I can confirm that exiftool works fine with this image : 
![image](https://user-images.githubusercontent.com/33779779/134824462-f086e34b-c99c-4286-802b-dcbdcba17a1a.png)
![image](https://user-images.githubusercontent.com/33779779/134824483-3b020ff1-7e39-4c63-a7ca-9c1fede17320.png)

and this is the part from this output that is interesting:
![image](https://user-images.githubusercontent.com/33779779/134824491-a3a61044-64f6-47fe-bc02-ad9ddd6c8419.png)

As you can see, exiftool seems to be working pretty fine :man_shrugging:

**Comment by ildyria** [comment]
Weird O.o

**Comment by ildyria** [comment]
By curiosity, can you set your `has_exiftool` to `0` in the advanced settings and reupload the said picture? :thinking: 
This should force the use of php_exiftool instead of the command line one.

**Comment by LouisVallat** [comment]
Hello back!

I think I understand why I have this issue... And it's maybe not your fault at all :sweat_smile: 
I just remembered that I'm running the LinuxServer version of Lychee, and not the official one. After spawning a fresh docker container from your official image (`lycheeorg/lychee:latest`), the lens tag seems to just be ignored, although `has_exiftool` is still set to 1. So in a way it's not your fault as it's a bug related to an image that you devs don't build, and it's kind of my fault for running a not-official image.
I've been using Lychee for a long time, and when I've set it up for my needs, there was no "official docker image" as far as I can remember, that's why I went with the linuxserver image instead.

I can close this issue as it's not related specifically to you, but still interesting that the official image just ignores (as it had always used to be on my non-official instance) the lens EXIF metadata.
See for yourself, on the official docker image : 
![image](https://user-images.githubusercontent.com/33779779/134825045-16eeaa80-5753-45f1-aabe-6386a4ffcc79.png)

**Comment by ildyria** [comment]
Well happy to read that this is resolved. :)

Still a weird bug.

**Comment by ildyria** [comment]
linuxserver images are usually pretty good, so very surprising. @alex-phillips knows probably more than me on the subject. :)

**Comment by LouisVallat** [comment]
Thanks! Yeah I've never had issue with this one (until today :cry:). I've noticed that they're often not 100% compatible with the official ones (had issues with a jellyfin instance)..
I'm glad this issue made me realize I didn't use your official image, I'll migrate soon, now that I know!
Thanks again for the time you spent on such a silly issue, I apologize!

You guys rock, and lychee is an amazing tool that I always recommend! :heart:
