### ISSUE TITLE
Lychee:Sync returns "Killed" after a few minutes of uploading. 

### ISSUE THREAD

**Issue by Normanras** [LycheeOrg/Lychee#1109]
### Detailed description of the problem [REQUIRED]
I have uploaded some photos (less than 100) into an album on my NAS, which is where my Lychee instance lives in a docker container. The goal is to eventually set up a cronjob so I can slowly back up all my photos. Currently, some photos are divided into `/year/month/day/picture.jpg` while two others (for testing) are just placed into a single directory. 

These are all located in the container path of `/pictures/import/`, which is also `/srv/disk-path/Lychee/imports`. In the latter example, other directories alongside import include: big, medium, small, raw, and thumb. 

When I `docker exec -ti /bin/bash` into my lychee container and run `php /app/lychee/artisan lychee:sync /pictures/import`, the files begin importing, but something begins to hang it up and then the terminal just returns `Killed`. 

Here are the last few entries in `php /app/lychee/artisan lychee: logs`

`2021-09-27 14:37:58 -- notice  -- App\Image\ImagickHandler::scale -- 113 -- Saving thumb to /app/lychee/public/uploads/small/ea715fec1e2fdd7bc9409b5379dccc34@2x.JPG
2021-09-27 14:38:02 -- notice  -- App\Actions\Photo\Extensions\ImageEditing::createThumb -- 165 -- Photo URL is 2a31d9548778eb6b9c7db1bcc3e75845.JPG
2021-09-27 14:38:05 -- notice  -- App\Image\ImagickHandler::crop -- 161 -- Saving thumb to /app/lychee/public/uploads/thumb/2a31d9548778eb6b9c7db1bcc3e75845.jpeg`

It just stops without explanation. See Diagnostics below. 

Things I've accounted for:

- File size, thought I've looked through and nothing is above 16mb. That being said, I adjusted my .ini file according to the documentation to the following: 
`max_execution_time = 200
post_max_size = 100M
upload_max_size = 100M
upload_max_filesize = 100M
memory_limit = 256M`

- Every time it fails, the last entry of the logs has to do with ImagickHandler. But I'm not sure how to dig deeper into _why_ that handler would cause the import to be killed. It is also failing on the same thumbnail, but I'm not sure how to download and actually see the thumbnail for issues. 
- My file structure is based on either Apple Photos (drag and drop from Photos into a Finder window and directory), or from the iOS PhotoSync app, uploading via SMB into the import directory. 
- I've also tried just importing a single directory within the import directory with this command: `php /app/lychee/artisan lychee:sync /pictures/import/2021`

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Place images in import directory
2. Access command line within the Lychee Docker container
3. Run `php /app/lychee/artisan lychee:sync /pictures/import/` 
4. Watch the terminal attempt to import or skip duplicates and then fail at a certain point. 

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

### Output of the diagnostics  [REQUIRED]
*(Settings => Diagnostics or https://example.com/Diagnostics or `php artisan lychee:diagnostics`)*

`Diagnostics
-----------
Warning: Dropbox import not working. dropbox_key is empty.
Warning: You may experience problems when uploading a large number of photos. Take a look at the FAQ for details.
Info: Latest version of PHP is 8

System Information
------------------
Lychee Version (release):        4.3.4
DB Version:                      4.3.4

composer install:                --no-dev
APP_ENV:                         production
APP_DEBUG:                       false

System:                          Linux
PHP Version:                     7.4
Max uploaded file size:          100M
Max post size:                   100M
MySQL Version:                   10.5.12-MariaDB-log

Imagick:                         1
Imagick Active:                  1
Imagick Version:                 1803
GD Version:                      bundled (2.1.0 compatible)

Config Information
------------------
version:                         040304
check_for_updates:               0
sorting_Photos_col:              taken_at
sorting_Photos_order:            ASC
sorting_Albums_col:              max_taken_at
sorting_Albums_order:            ASC
imagick:                         1
skip_duplicates:                 1
small_max_width:                 0
small_max_height:                360
medium_max_width:                1920
medium_max_height:               1080
lang:                            en
layout:                          0
image_overlay_type:              desc
default_license:                 reserved
compression_quality:             90
full_photo:                      1
delete_imported:                 1
Mod_Frame:                       1
Mod_Frame_refresh:               30
thumb_2x:                        1
small_2x:                        1
medium_2x:                       1
landing_page_enable:             0
landing_owner:                   redacted
landing_title:                   redacted
landing_subtitle:                redacted
landing_facebook:                
landing_flickr:                  
landing_twitter:                 
landing_instagram:               
landing_youtube:                 
landing_background:              
site_title:                      Lychee v4
site_copyright_enable:           1
site_copyright_begin:            2019
site_copyright_end:              2019
additional_footer_text:          
display_social_in_gallery:       0
public_search:                   0
SL_enable:                       0
SL_for_admin:                    0
public_recent:                   0
recent_age:                      1
public_starred:                  0
downloadable:                    0
photos_wraparound:               1
map_display:                     1
zip64:                           1
map_display_public:              1
map_provider:                    Wikimedia
force_32bit_ids:                 0
map_include_subalbums:           0
update_check_every_days:         3
has_exiftool:                    1
share_button_visible:            0
import_via_symlink:              0
has_ffmpeg:                      1
location_decoding:               1
location_decoding_timeout:       30
location_show:                   1
location_show_public:            0
rss_enable:                      0
rss_recent_days:                 7
rss_max_items:                   100
prefer_available_xmp_metadata:   0
editor_enabled:                  1
lossless_optimization:           0
swipe_tolerance_x:               150
swipe_tolerance_y:               250
local_takestamp_video_formats:   .avi|.mov
log_max_num_line:                1000
unlock_password_photos_with_url_param: 0
nsfw_visible:                    1
nsfw_blur:                       0
nsfw_warning:                    0
nsfw_warning_admin:              0
map_display_direction:           1
album_subtitle_type:             oldstyle
upload_processing_limit:         4
public_photos_hidden:            1`

### Browser and system

Odroid HC-4
OMV, Docker
Linux, armv8, 4gb ram

**Comment by d7415** [comment]
`Killed` is usually a memory issue. You may need to increase the memory limit in php further, or you may need to check the available memory on the NAS or, possibly, the memory allocated to the container.

**Comment by d7415** [comment]
>     * That being said, I adjusted my .ini file according to the documentation to the following:
>       `max_execution_time = 200 post_max_size = 100M upload_max_size = 100M upload_max_filesize = 100M memory_limit = 256M`

Did you change these in the ini for the php cli? Because that will have different settings to php-fpm used to serve Lychee.

**Comment by Normanras** [comment]
I updated the php-local.ini file in my config directory. I don't see another ini file in that or my db directory, unless I'm missing something or was supposed to add a file?

**Comment by Normanras** [comment]
> `Killed` is usually a memory issue. You may need to increase the memory limit in php further, or you may need to check the available memory on the NAS or, possibly, the memory allocated to the container.

Missed this and just replied to your other one. Actually, let me check this and then I'll close this out. I just got a notification about low memory recently, so I think you may be right.

**Comment by d7415** [comment]
> I updated the php-local.ini file in my config directory. I don't see another ini file in that or my db directory, unless I'm missing something or was supposed to add a file?

I suspect the other message will solve this, but if you're using the Docker image it won't be using the NAS's php installation/configuration. You need to configure within the container.

**Comment by Normanras** [comment]
ok @d7415 you are correct, sir - that solved it. Killed indeed was related to memory. Turns out my /var/log/ files were at 98%. I've moved them and cleared them and now all files are uploading to my lychee instance without issue. Sorry for making this a customer service sesh but thanks so much for you help!

**Comment by Normanras** [comment]
Hi @d7415, sorry for revisiting this, but the problem persists. I can confirm I have enough memory and availbility on my server. I decided to try a few different import commands and changes while processing imports and watching `top`.

What happens every time in top is php shows up ~20% usage, then 30%, then 50%, then 80%, and then it disappears. My `artisan` command shows that the process has been killed. 

I have tried running `nice -n 10 php /app/lychee/artisan lychee:sync /pictures/import`, but that didn't make a difference. Originally, in my `.ini` file, `memory_limit=256M` so I dropped that to 64M and finally to -1, but again, no change. 

I'm currently reading through some old StackOverflow conversations about Docker and Artisan not playing well together and Docker not limiting the process' usage. I'll continue reading and please feel free to leave this as closed. Just wanted to make you aware as I uncover more and if anyone else is having a similar issue.

**Comment by Normanras** [comment]
@d7415 Martin, I'm back. Idk if this is still a memory issue, or something else. But I've upgraded my system to remove the SD card completely - the OS is running off a 1TB SSD. 4gb ram. Debian 11. 

I do the same steps as above, and start uploading inside of docker exec while watching `top`. This time, `php` gets up to 50% and while lychee is processing a folder, it seems to start moving slowly and gets hung up on a certain file. Then all of a sudden the terminal shows the killed command and php disappears from top. But it doesn't eat up the same memory and CPU as before. 

I've located the file/picture and there is nothing strange about it. All within normal ranges. What else can I explore to figure this out? I searched through issues, but not sure what issues relate to this. The other ones seem to relate to large file size. Any thoughts?

**Comment by kamil4** [comment]
Did you run it multiple times? If so, does it get hung up on the same file every time?

How many images are you trying to import at any one time? Is it still around 100, like you said in your first post?

From your description, it does sound like it's running out of memory...

**Comment by Normanras** [comment]
Yes, it is the same folder, around 100. And yeah, it seems like it is the same photo, but I can't figure out why that photo is any different from the rest. It seems fairly normal. 

My memory (4 gb) shows it has 2.7 gb available and when looking at my monitoring charts, I don't see a spike when trying to run the import command. Argh, I don't understand why it would fail! Top isn't showing a crazy spike and my memory doesn't show as full. 

I've even tried running it with `nice` and other priority management and limiters, but still it fails. Very strange. 

I'll try other folders and see if anything gets through.

**Comment by d7415** [comment]
Quickly...
- I wouldn't expect `nice` to help
- I'm not sure whether PHP applies its memory limits to child processes. That could explain it.
- There could also be limits imposed by Docker, but I wouldn't expect any by default.

**Comment by kamil4** [comment]
> Yes, it is the same folder, around 100. And yeah, it seems like it is the same photo, but I can't figure out why that photo is any different from the rest. It seems fairly normal.

So can you try temporarily moving that one offending photo out of the folder and checking if the import succeeds then? Does importing that photo separately (from a folder containing nothing but that one file) work?

**Comment by Normanras** [comment]
Hi guys, I was finally able to sit down and dig into this. I figured it out and reproduced it 3 times - let me know if I missed something in the documentation. 

The offending photos are all panoramas. Basically, in `docker exec` I see the full filename for all the duplicates, it then shows a new line for each new photo imported, and then it says `killed` when trying to import a panoramic photo. 

The photos were taken in 2016 using an iPhone (I think that would have been the 8 or 10), using the native panorama feature. 

See attached picture. Importing directly from a folder containing _only_ one or a few of the offending pictures ends in the same `killed` result. 

The three photos that caused the fail are of the following sizes: 7.9Mb, 10.7Mb, and 19.6Mb. Other non-panoramic photos are of larger sizes, so it isn't restricted to only size. My non-dev hunch is that since the proportions are different, lychee doesn't know what to do with it and kills the sync. 
![Screen Shot 2021-10-29 at 12 12 29 PM](https://user-images.githubusercontent.com/44226464/139468186-271677b8-bc07-4f9b-8b22-c8d178163877.png)

**Comment by kamil4** [comment]
Could you put the offending photos online so that we can download them and give them a try?

**Comment by Normanras** [comment]
This is the only one I can upload. The other two are above the Github 10MB limit at 10.7mb and 19.6mb. I don't want to compress anything and potentially change the photo. I could throw all three in a zip if you need the other photos. 

![2016-02-14_09-42-01_6EB80F48-A33C-48BA-A17C-E852AA2F7E20](https://user-images.githubusercontent.com/44226464/139883956-e758486d-ac03-45f9-8a7f-6c056a0ea081.JPG)

**Comment by kamil4** [comment]
I tried to upload your image to Lychee using the web GUI. It worked for me out-of-the-box when using Imagick, but it failed when I had Imagick disabled; it was running out of memory then. My `memory_limit` was set to `128M`; increasing it to `512M` fixed it (I have not tried `256M`).

Based on your diagnostics output, you are using Imagick so should not be affected by this though. Although, depending on the amount of memory on your server, Imagick may be exhausting system resources and be getting killed by the kernel. You may want to check you system log for any such output after a failed upload/import attempt (that may require admin-level access). Another possibility is that your Imagick installation has a low maximum image width limit. Typically the limit is set to 16KP so your image should not be affected, but do check the config file `policy.xml` on your server; in my case it's in `/etc/ImageMagick-7/` but I imagine that may vary depending on the version of Imagick.
