### ISSUE TITLE
Set Size of Grid

### ISSUE THREAD

**Issue by FlyingEagle** [LycheeOrg/Lychee#1111]
I want to change the size of the thumbnails in the grid of an album, I can not found an option, so I request one ;-)

Addendum: And if I think about it properly, it would actually be more pleasant (adjustable) if all thumbnails were the same size, whether portrait or landscape.

**Comment by kamil4** [comment]
> I want to change the size of the thumbnails in the grid of an album, I can not found an option, so I request one ;-)

Which photo layout are you using? The default "justified" one? If so, there is an undocumented feature you can use via custom CSS:

```
.justified-layout > .photo {
    --lychee-default-height: 480px;
}
```

The above will make them _much_ larger than default. Tweak as you see fit.

> Addendum: And if I think about it properly, it would actually be more pleasant (adjustable) if all thumbnails were the same size, whether portrait or landscape.

I'm not sure what you are asking for here. That they are all of uniform height between rows? That's what "unjustified" photo layout does. The only way to make all thumbnails exactly the same size is to make them square, and we do support that as well via the "square" photo layout.

**Comment by ildyria** [comment]
This is already possible with the user.css.
