### ISSUE TITLE
Docker: Migrating from MariaDB to Postgres

### ISSUE THREAD

**Issue by FlyingEagle** [LycheeOrg/Lychee#1112]
How to migrate from mariadb to postgres with lychee?

what do I have to write in docker-compose for env-variable DB_CONNECTION?

when using 'postgres' or 'pgsql' I got an error like "unknown database engine" in Connection.php ...

I use this image: ghcr.io/linuxserver/lychee:latest

with mariadb it works!

`
In Connection.php line 678:
  could not find driver (SQL: select * from information_schema.tables where t  
  able_schema = public and table_name = migrations and table_type = 'BASE TAB  
  LE')    
In Exception.php line 18:
  could not find driver  
In PDOConnection.php line 39:
  could not find driver  
`

**Comment by d7415** [comment]
The .env directives are described here: https://github.com/LycheeOrg/Lychee/blob/master/.env.example#L20-L23
