### ISSUE TITLE
List, add or delete albums using the API via cURL result in a "false"

### ISSUE THREAD

**Issue by Babyforce** [LycheeOrg/Lychee#1114]
### Detailed description of the problem [REQUIRED]
I'm trying to list, create and delete albums using the API and cURL, but it doesn't seem to be working. According to the official API documentation at https://lycheeorg.github.io/docs/api.html, I have to first login using a POST request and an API Key that I created : `curl -X POST -F 'username=Username' -F 'password=Password' -H 'Authorization: xxxxxxxxxxxxxxxx' https://gallery.domain.com/api/Session::login` and doing this sends "true", so I suppose it means the machine that sent the command is logged-in (as my gallery administrator). I can then list the available albums using the command `curl -X POST -H 'Authorization: xxxxxxxxxxxxxxxx' https://gallery.domain.com/api/Albums::get`, which works but it doesn't display the private albums, like it should. Trying to list a private album sends this result : "Warning: Album private!", and whenever I want to create a new album from a POST request, the api just sends a "false" and that's it. No album gets created. According to the documentation above, the command to create an album should just require "title" as a minimum requirement, and "parent_id" can be left blank. The command I tried using are :

- `curl -X POST -d "title=Test Album" -H 'Authorization: xxxxxxxxxxxxxxxx' https://gallery.domain.com/api/Album::add`
- `curl -X POST -F 'title=Test Album' -F 'parent_id=' -H 'Authorization: xxxxxxxxxxxxxxxx' https://gallery.domain.com/api/Album::add`
- `curl -X POST -F 'title=Test Album' -H 'Authorization: xxxxxxxxxxxxxxxx' https://gallery.domain.com/api/Album::add`
- `curl -X POST -d "title=Test Album" -H 'Authorization: xxxxxxxxxxxxxxxx' https://gallery.domain.com/api/Album::add`
- `curl -X POST -d "title=Test Album&parent_id=" -H 'Authorization: xxxxxxxxxxxxxxxx' https://gallery.domain.com/api/Album::add`

All of them send a "false" like I am not logged-in at all. I tried adding my credentials to the commands above with no success either. I do not know if I am doing anything wrong or if there is an issue somewhere. I am not an expert with using APIs, so maybe the issue comes from me, but I have no idea what I would be doing wrong. I have searched and tried for hours with little to no success. All these commands are executed from the server the gallery is running from.

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Log-in to the API using the command from the documentation above
2. Try to list a private album or create/delete one

### Output of the diagnostics  [REQUIRED]
System Information
------------------
Lychee Version (release):        4.3.4
DB Version:                      4.3.4

composer install:                --no-dev
APP_ENV:                         production
APP_DEBUG:                       true

System:                          Linux
PHP Version:                     8
Max uploaded file size:          2M
Max post size:                   8M
MySQL Version:                   10.5.11-MariaDB-1

Imagick:                         1
Imagick Active:                  1
Imagick Version:                 1691
GD Version:                      2.3.0

### Browser and system
Debian 11 x64 (server)

**Comment by ildyria** [comment]
Hi Sorry that you have spent so much time on this problem.

The `Authorization: xxxxxxxxxxxxxxxx` is to **bypass the XCRF protection**. Once you are authenticated (with `api/Session::login` which you are doing correctly), you should get a Laravel session cookie (`lychee_session`). You will need to provide that one to the server for subsequent queries.

If I look at the post request I send to my server I see:
`set-cookie: lychee_session=eyJpdiI6IkRlUzZ6eHppUVpQbjFoRUdJSWQ1eUE9PSIsInZhbHVlIjoiaGx3ckl...JekNNYlVsbjNOdVM2dGNLaDZjamFLdXJMYTdKR1A1WFdMZkpUmE4YzI0MjY4OThmOWExYzNkMjhhZTBkMjVkNzgyYjBhOTdkOTI2Yjc4NDYzOTQ3NWRmYjJhOGZiMGRmIn0%3D; expires=Tue, 05-Oct-2021 16:29:22 GMT; Max-Age=7200; path=/; secure; httponly; samesite=lax`

**Comment by Babyforce** [comment]
Thank you for your reply. I was indeed thinking about a cookie but wasn't sure about it since it was mentioned nowhere in the documentation. Getting the cookie with the -c option worked and I could successfully create an album using this method. I also discovered that "parent_id" must be actually set to "0" to be considered "null". If I do not add this option, I get a huge wall of error. Thanks again! I really feel stupid about this one.

**Comment by ildyria** [comment]
> I really feel stupid about this one.

Don't sweat it. We all make mistakes. :)

**Comment by LouisVallat** [comment]
I'd like to work on this issue :smile:, seems like something important, after I experimented for a while with the API.

**Comment by nagmat84** [comment]
What issue do you refer to exactly? I don't see an issue here.

**Comment by LouisVallat** [comment]
Adding this mention in the documentation.
This issue is still open and has a `documentation` tag so I assumed you'd like someone to add a mention in the documentation for that cookie, as I don't find it mentioned anywhere.

**Comment by nagmat84** [comment]
Ah, OK. Yes, I agree the API documentation could be improved a lot. Actually, a lot is missing there.

**Comment by LouisVallat** [comment]
As the fixing PR has been merged, I believe that this issue can be closed.

**Comment by Babyforce** [comment]
> As the fixing PR has been merged, I believe that this issue can be closed.

Absolutely. I'm closing this now. Thank you for updating the documentation.
