### ISSUE TITLE
'Copy To...' command creates duplicate in destination folder, removes photo from source folder.

### ISSUE THREAD

**Issue by ghost** [LycheeOrg/Lychee#1116]
### Detailed description of the problem [REQUIRED]
When right-clicking a photo and selecting "Copy to..." a copy is created in the destination folder and the original photo moved to the same destination folder.

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Right click an image in any folder.
2. Click 'Copy to...'
3. Select destination folder
5. See error*

### Output of the diagnostics  [REQUIRED]
    Diagnostics
    -----------
    Warning: Dropbox import not working. dropbox_key is empty.
    Warning: You may experience problems when uploading a photo of large size. Take a look in the FAQ for details.
    Error: A user is missing! Please create a user with id: "2"
    Info: Latest version of PHP is 8

    System Information
    ------------------
    Lychee Version (release):        4.3.4
    DB Version:                      4.3.4
    
    composer install:                --no-dev
    APP_ENV:                         production
    APP_DEBUG:                       false
    
    System:                          Linux
    PHP Version:                     7.4
    Max uploaded file size:          20M
    Max post size:                   200M
    MySQL Version:                   10.5.12-MariaDB-log
    
    Imagick:                         1
    Imagick Active:                  1
    Imagick Version:                 1803
    GD Version:                      bundled (2.1.0 compatible)

    Config Information
    ------------------
    version:                         040304
    check_for_updates:               0
    sorting_Photos_col:              taken_at
    sorting_Photos_order:            ASC
    sorting_Albums_col:              max_taken_at
    sorting_Albums_order:            ASC
    imagick:                         1
    skip_duplicates:                 0
    small_max_width:                 0
    small_max_height:                360
    medium_max_width:                1920
    medium_max_height:               1080
    lang:                            en
    layout:                          1
    image_overlay_type:              desc
    default_license:                 none
    compression_quality:             90
    full_photo:                      1
    delete_imported:                 0
    Mod_Frame:                       1
    Mod_Frame_refresh:               30
    thumb_2x:                        1
    small_2x:                        1
    medium_2x:                       1
    landing_page_enable:             0
    landing_owner:                   Dunwell Tech, Inc.
    landing_title:                   Dunwell Photo Server
    landing_subtitle:                
    landing_facebook:                
    landing_flickr:                  
    landing_twitter:                 
    landing_instagram:               
    landing_youtube:                 
    landing_background:              dist/background1.jpg
    site_title:                      Photo Server
    site_copyright_enable:           0
    site_copyright_begin:            2019
    site_copyright_end:              2021
    additional_footer_text:          
    display_social_in_gallery:       0
    public_search:                   1
    SL_enable:                       0
    SL_for_admin:                    0
    public_recent:                   0
    recent_age:                      1
    public_starred:                  0
    downloadable:                    1
    photos_wraparound:               1
    map_display:                     0
    zip64:                           1
    map_display_public:              0
    map_provider:                    Wikimedia
    force_32bit_ids:                 0
    map_include_subalbums:           0
    update_check_every_days:         3
    has_exiftool:                    1
    share_button_visible:            0
    import_via_symlink:              0
    has_ffmpeg:                      1
    location_decoding:               0
    location_decoding_timeout:       30
    location_show:                   0
    location_show_public:            0
    rss_enable:                      0
    rss_recent_days:                 7
    rss_max_items:                   100
    prefer_available_xmp_metadata:   0
    editor_enabled:                  1
    lossless_optimization:           0
    swipe_tolerance_x:               150
    swipe_tolerance_y:               250
    local_takestamp_video_formats:   .avi|.mov
    log_max_num_line:                1000
    unlock_password_photos_with_url_param: 0
    nsfw_visible:                    1
    nsfw_blur:                       0
    nsfw_warning:                    0
    nsfw_warning_admin:              0
    map_display_direction:           1
    album_subtitle_type:             oldstyle
    upload_processing_limit:         4
    public_photos_hidden:            0

### Browser and system
Chrome  - Version 94.0.4606.71 (Official Build) (64-bit)
Windows 10 Pro - Version 19041.1237

**Comment by kamil4** [comment]
Thank you for your report! This bug is actually already fixed (https://github.com/LycheeOrg/Lychee-front/pull/270) but the fix was merged after the 4.3.4 version was released and we haven't released the next version yet.
