### ISSUE TITLE
importing images from command line using symlink

### ISSUE THREAD

**Issue by Atreb92** [LycheeOrg/Lychee#1118]
When trying to import images through the command line, as described in the, [docs](https://lycheeorg.github.io/docs/faq.html#can-i-set-up-lychee-to-watch-a-folder-for-new-images-and-automatically-add-them-to-albums) it is unclear if it is possible to add the new images using symlinks or deleting originals.

Is it possible to have the same level of functionality when using the command line as the web interface?

**Comment by nagmat84** [comment]
This issue has already been address in #1056 and fixed by #1086.

**Comment by Atreb92** [comment]
Ok, then I might be using this improperly because I am getting the following error when attempting to add those options.

![lychee_error](https://user-images.githubusercontent.com/36992456/136832543-ad10eca5-52c6-47c9-a32d-ad1c07a1c0c4.PNG)

**Comment by d7415** [comment]
What version of Lychee are you using?

**Comment by Atreb92** [comment]
Currently using the latest available docker from linuxserver and it is running Lychee 4.3.4

**Comment by d7415** [comment]
Yup, that fix is not in 4.3.4.

**Comment by Atreb92** [comment]
Isn't 4.3.4 the latest available version? Is there any workaround I can apply?

**Comment by kamil4** [comment]
4.3.4 is the latest release; the fix was committed after that release came out so is not included in any public release yet.

However, you should be able to apply the fix to your 4.3.4 tree. Simply replace the file `Lychee/app/Console/Commands/Sync.php` with the contents of https://raw.githubusercontent.com/LycheeOrg/Lychee/master/app/Console/Commands/Sync.php.

**Comment by Atreb92** [comment]
Thank you for the advice, I will give it a try and see if it works.

**Comment by d7415** [comment]
You could also see whether they provide a Docker image that tracks master. We do.
