### ISSUE TITLE
No video upload when ffmpeg is missing

### ISSUE THREAD

**Issue by gueba** [LycheeOrg/Lychee#1119]
### Detailed description of the problem [REQUIRED]

I installed Version 4.3.4 on hosted webspace without ssh and ffmpeg. Lychee does not find ffmpeg and sets "has_ffmpeg" to 0, which is expected. When uploading a *.mp4 video it shows the progress and ends with the message:
```
Failed
Server returned an unknown response. Please take a look at the console of your browser for further details.
```
the video is not uploaded, firefox console shows '500 Internal Server Error'

Setting manually 'has_ffmpeg' to '1' lets me upload the video as usual. (no thumbs created of course).
Tested with PHP7.4 and PHP8.

On a parallel installation of version 4.3.0 the video upload with the "correct" setting of 'has_ffmeg' to '0' works, which is the correct way, I guess.

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Make sure that ffmpeg is not available
2. Check if 'has_ffmep' is correctly set from '2' to '0'
3. Upload video
4. See error "Failed"
5. Manually set 'has_ffmpeg' to '1'
6. Try upload again --> success

### Output of the diagnostics  [REQUIRED]
`    Diagnostics
    -------
    Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.

    System Information
    --------------
    Lychee Version (release):        4.3.4
    DB Version:                      4.3.4
    
    composer install:                --no-dev
    APP_ENV:                         production
    APP_DEBUG:                       false
    
    System:                          Linux
    PHP Version:                     8
    Max uploaded file size:          200M
    Max post size:                   200M
    MySQL Version:                   10.5.11-MariaDB-1:10.5.11+maria~focal-log
    
    Imagick:                         1
    Imagick Active:                  1
    Imagick Version:                 1690
    GD Version:                      2.2.5

    Config Information
    --------------
    version:                         040304
    check_for_updates:               0
    sorting_Photos_col:              title
    sorting_Photos_order:            ASC
    sorting_Albums_col:              title
    sorting_Albums_order:            ASC
    imagick:                         1
    skip_duplicates:                 0
    small_max_width:                 0
    small_max_height:                360
    medium_max_width:                1920
    medium_max_height:               1080
    lang:                            en
    layout:                          0
    image_overlay_type:              desc
    default_license:                 none
    compression_quality:             90
    full_photo:                      1
    delete_imported:                 0
    Mod_Frame:                       1
    Mod_Frame_refresh:               30
    thumb_2x:                        1
    small_2x:                        1
    medium_2x:                       1
    landing_page_enable:             0
    landing_owner:                   John Smith
    landing_title:                   John Smith
    landing_subtitle:                Cats, Dogs & Humans Photography
    landing_facebook:                https://www.facebook.com/JohnSmith
    landing_flickr:                  https://www.flickr.com/JohnSmith
    landing_twitter:                 https://www.twitter.com/JohnSmith
    landing_instagram:               https://instagram.com/JohnSmith
    landing_youtube:                 https://www.youtube.com/JohnSmith
    landing_background:              dist/cat.jpg
    site_title:                      Fotos
    site_copyright_enable:           1
    site_copyright_begin:            2019
    site_copyright_end:              2019
    additional_footer_text:          
    display_social_in_gallery:       0
    public_search:                   0
    SL_enable:                       0
    SL_for_admin:                    0
    public_recent:                   0
    recent_age:                      1
    public_starred:                  0
    downloadable:                    0
    photos_wraparound:               1
    map_display:                     0
    zip64:                           1
    map_display_public:              0
    map_provider:                    Wikimedia
    force_32bit_ids:                 0
    map_include_subalbums:           0
    update_check_every_days:         3
    has_exiftool:                    1
    share_button_visible:            0
    import_via_symlink:              0
    has_ffmpeg:                      0
    location_decoding:               0
    location_decoding_timeout:       30
    location_show:                   1
    location_show_public:            0
    rss_enable:                      0
    rss_recent_days:                 7
    rss_max_items:                   100
    prefer_available_xmp_metadata:   0
    editor_enabled:                  1
    lossless_optimization:           0
    swipe_tolerance_x:               150
    swipe_tolerance_y:               250
    local_takestamp_video_formats:   .avi|.mov
    log_max_num_line:                1000
    unlock_password_photos_with_url_param: 0
    nsfw_visible:                    1
    nsfw_blur:                       0
    nsfw_warning:                    0
    nsfw_warning_admin:              0
    map_display_direction:           1
    album_subtitle_type:             oldstyle
    upload_processing_limit:         4
    public_photos_hidden:            1`

### Browser and system
Firefox 93.0 on Xubuntu 20.04

**Comment by kamil4** [comment]
Confirmed. Working on a fix.

**Comment by kamil4** [comment]
The fix will be included in the next version. Thank you for your report!
