### ISSUE TITLE
ffmpeg not found by Lychee

### ISSUE THREAD

**Issue by corrilan** [LycheeOrg/Lychee#1125]
### Detailed description of the problem [REQUIRED]
The Diagnostics screen is showing "has_ffmpeg: 0" even though ffmpeg is installed via apt-get and php-ffmpeg is install from "https://github.com/PHP-FFMpeg/PHP-FFMpeg" using "composer require php-ffmpeg/php-ffmpeg".
I restarted Apache after the installations.
I am therefore not getting any thumbnails for uploaded videos.
Perhaps I have misinterpreted what ffmpeg components I need to install, or how to install them?

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Go to Diagnostic page of Lychee.
2. See "has_ffmpeg: 0" when I would expect a 1.

### Output of the diagnostics  [REQUIRED]
Diagnostics
    -------
    Warning: Dropbox import not working. dropbox_key is empty.
    Warning: Pictures that are rotated lose their metadata! Please install Imagick to avoid that.
    Info: Latest version of PHP is 8

    System Information
    --------------
    Lychee Version (release):        4.3.4
    DB Version:                      4.3.4
    
    composer install:                --no-dev
    APP_ENV:                         production
    APP_DEBUG:                       false
    
    System:                          Linux
    PHP Version:                     7.4
    Max uploaded file size:          500M
    Max post size:                   500M
    MySQL Version:                   8.0.26-0ubuntu0.20.04.3
    
    Imagick:                         -
    Imagick Active:                  1
    Imagick Version:                 -
    GD Version:                      2.2.5

    Config Information
    --------------
    version:                         040304
    check_for_updates:               0
    sorting_Photos_col:              taken_at
    sorting_Photos_order:            DESC
    sorting_Albums_col:              id
    sorting_Albums_order:            DESC
    imagick:                         1
    skip_duplicates:                 0
    small_max_width:                 0
    small_max_height:                360
    medium_max_width:                1920
    medium_max_height:               1080
    lang:                            en
    layout:                          1
    image_overlay_type:              none
    default_license:                 reserved
    compression_quality:             90
    full_photo:                      1
    delete_imported:                 1
    Mod_Frame:                       1
    Mod_Frame_refresh:               10
    thumb_2x:                        1
    small_2x:                        1
    medium_2x:                       1
    landing_page_enable:             0
    landing_owner:                   Jason
    landing_title:                   Jason
    landing_subtitle:                Cats, Dogs & Humans Photography
    landing_facebook:                https://www.facebook.com/JohnSmith
    landing_flickr:                  https://www.flickr.com/JohnSmith
    landing_twitter:                 https://www.twitter.com/JohnSmith
    landing_instagram:               https://instagram.com/JohnSmith
    landing_youtube:                 https://www.youtube.com/JohnSmith
    landing_background:              dist/cat.jpg
    site_title:                      Photos
    site_copyright_enable:           1
    site_copyright_begin:            2019
    site_copyright_end:              2021
    additional_footer_text:          
    display_social_in_gallery:       0
    public_search:                   0
    SL_enable:                       0
    SL_for_admin:                    0
    public_recent:                   0
    recent_age:                      1
    public_starred:                  0
    downloadable:                    0
    photos_wraparound:               1
    map_display:                     0
    zip64:                           1
    map_display_public:              0
    map_provider:                    Wikimedia
    force_32bit_ids:                 0
    map_include_subalbums:           0
    update_check_every_days:         3
    has_exiftool:                    0
    share_button_visible:            0
    import_via_symlink:              0
    has_ffmpeg:                      0
    location_decoding:               0
    location_decoding_timeout:       30
    location_show:                   1
    location_show_public:            0
    rss_enable:                      0
    rss_recent_days:                 7
    rss_max_items:                   100
    prefer_available_xmp_metadata:   0
    editor_enabled:                  1
    lossless_optimization:           0
    swipe_tolerance_x:               150
    swipe_tolerance_y:               250
    local_takestamp_video_formats:   .avi|.mov
    log_max_num_line:                1000
    unlock_password_photos_with_url_param: 0
    nsfw_visible:                    1
    nsfw_blur:                       0
    nsfw_warning:                    0
    nsfw_warning_admin:              0
    map_display_direction:           1
    album_subtitle_type:             oldstyle
    upload_processing_limit:         4
    public_photos_hidden:            1

### Browser and system
Server: Ubuntu 20.04.3 LTS (Focal Fossa)
Browser on remote client: Google Chrome and Mozilla Firefox on Ubuntu 12.04

**Comment by kamil4** [comment]
You may need to manually reset `has_ffmpeg` to `1` in the advanced config (https://lycheeorg.github.io/docs/settings.html#full-settings) and try uploading a video file again. There's also an extensive FAQ entry on solving issues with missing video thumbnails: https://lycheeorg.github.io/docs/faq.html#why-dont-my-videos-have-thumbnails

I hope this helps but if you need more help, don't hesitate to ask!

**Comment by corrilan** [comment]
Thanks kamil4, manually setting has_ffmpeg did the trick.
