### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by mir07** [LycheeOrg/Lychee#1129]
If a person have a direct link to an album the person can access the album even if the album is marked as not public.

Affected version of Lychee: 4.3.4

**Comment by ildyria** [comment]
I just tested on my installation, I do not observe this behavior.

**Comment by mir07** [comment]
I have just tried with a newly created album and cannot replicate. The problem occured when an album was deleted and then recreated with the same name. I uploaded new images to the album and forgot to make it available only if people had a direct link but I send the link to the album to another person which then were able to see the contents of the album even though it was not public. I will pay more attention to the circomstances if it occurs again.
