### ISSUE TITLE
Add feature to delete entire contents of album without deleting the album itself

### ISSUE THREAD

**Issue by mir07** [LycheeOrg/Lychee#1130]
In latest release (4.3.4) when you mark all images in an album and press delete you can only choose between cancel or delete all images as well as the album. I can see many usecases where a user would like to delete the entire contents of an album but do this without deleting the album.

**Comment by ildyria** [comment]
Yeah I am aware of that one.
The best way to actually delete in those case is not to use the trash on the top right which will delete the album, but to use the right click.

**Comment by mir07** [comment]
The action and text gives mening if you have selected one or more albums but due to the fact that an album can contain albums as well as images at the same time you potentially end of it a very complex situtation. And easy fix would be to restrict albums to either only contain images or albums because then the recursive nature is only in play when an album is chosen. BTW. I was not aware of the context sentive menu which provide a means for my usecase so thanks for that ;-)

**Comment by ildyria** [comment]
When you do a selection, you will be restricted to select either only images or only albums. You cannot select both and do an operation. :)
