### ISSUE TITLE
Unable to get email notification working

### ISSUE THREAD

**Issue by corrilan** [LycheeOrg/Lychee#1134]
### Detailed description of the problem [REQUIRED]
I have followed instructions in the readme to configure email notification but have been unable to locate the "Send new photos notification emails" in the settings.

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Go to 'Settings'
2. Search for "Send new photos notification emails" or similar
3. Option does not appear to exist.

### Output of the diagnostics  [REQUIRED]
*(Settings => Diagnostics or https://example.com/Diagnostics or `php artisan lychee:diagnostics`)*

    Diagnostics
    -------
    Warning: Dropbox import not working. dropbox_key is empty.
    Warning: Pictures that are rotated lose their metadata! Please install Imagick to avoid that.
    Info: Latest version of PHP is 8

    System Information
    --------------
    Lychee Version (release):        4.3.4
    DB Version:                      4.3.4
    
    composer install:                --no-dev
    APP_ENV:                         production
    APP_DEBUG:                       false
    
    System:                          Linux
    PHP Version:                     7.4
    Max uploaded file size:          500M
    Max post size:                   500M
    MySQL Version:                   8.0.27-0ubuntu0.20.04.1
    
    Imagick:                         -
    Imagick Active:                  1
    Imagick Version:                 -
    GD Version:                      2.2.5

    Config Information
    --------------
    version:                         040304
    check_for_updates:               0
    sorting_Photos_col:              taken_at
    sorting_Photos_order:            DESC
    sorting_Albums_col:              id
    sorting_Albums_order:            DESC
    imagick:                         1
    skip_duplicates:                 0
    small_max_width:                 0
    small_max_height:                360
    medium_max_width:                1920
    medium_max_height:               1080
    lang:                            en
    layout:                          1
    image_overlay_type:              none
    default_license:                 reserved
    compression_quality:             90
    full_photo:                      1
    delete_imported:                 1
    Mod_Frame:                       1
    Mod_Frame_refresh:               10
    thumb_2x:                        1
    small_2x:                        1
    medium_2x:                       1
    landing_page_enable:             0
    landing_owner:                   Jason and Lynsey Bassett
    landing_title:                   Jason and Lynsey Bassett
    landing_subtitle:                Cats, Dogs &amp; Humans Photography
    landing_facebook:                https://www.facebook.com/JohnSmith
    landing_flickr:                  https://www.flickr.com/JohnSmith
    landing_twitter:                 https://www.twitter.com/JohnSmith
    landing_instagram:               https://instagram.com/JohnSmith
    landing_youtube:                 https://www.youtube.com/JohnSmith
    landing_background:              dist/cat.jpg
    site_title:                      Enframed Photos
    site_copyright_enable:           1
    site_copyright_begin:            2019
    site_copyright_end:              2021
    additional_footer_text:          
    display_social_in_gallery:       0
    public_search:                   0
    SL_enable:                       0
    SL_for_admin:                    0
    public_recent:                   0
    recent_age:                      1
    public_starred:                  0
    downloadable:                    0
    photos_wraparound:               1
    map_display:                     0
    zip64:                           1
    map_display_public:              0
    map_provider:                    Wikimedia
    force_32bit_ids:                 0
    map_include_subalbums:           0
    update_check_every_days:         3
    has_exiftool:                    0
    share_button_visible:            0
    import_via_symlink:              0
    has_ffmpeg:                      1
    location_decoding:               0
    location_decoding_timeout:       30
    location_show:                   1
    location_show_public:            0
    rss_enable:                      0
    rss_recent_days:                 7
    rss_max_items:                   100
    prefer_available_xmp_metadata:   0
    editor_enabled:                  1
    lossless_optimization:           0
    swipe_tolerance_x:               150
    swipe_tolerance_y:               250
    local_takestamp_video_formats:   .avi|.mov
    log_max_num_line:                1000
    unlock_password_photos_with_url_param: 0
    nsfw_visible:                    1
    nsfw_blur:                       0
    nsfw_warning:                    0
    nsfw_warning_admin:              0
    map_display_direction:           1
    album_subtitle_type:             oldstyle
    upload_processing_limit:         4
    public_photos_hidden:            1

### Browser and system
Client: Mozilla Firefox on Ubuntu 20.04
Server: Ubuntu 20.04

**Comment by ildyria** [comment]
Hi,

Mail notification was added https://github.com/LycheeOrg/Lychee/pull/1049 on July 19.
The version you are using **release** [4.3.4](https://github.com/LycheeOrg/Lychee/releases/tag/v4.3.4) was published on July 9. 

Thus no bug. Update to master branch version. (Sorry.)

**Comment by ryanfiller** [comment]
Hi, I am on v 4.7.0 (running the docker image `lscr.io/linuxserver/lychee:latest`). I cannot seem to get emails working either, I can open a new ticket if you would rather than me comment on this one.

<details>
<summary>Diagnostics</summary>
```
-----------
Warning: Dropbox import not working. dropbox_key is empty.
Warning: You may experience problems when uploading a photo of large size. Take a look in the FAQ for details.
Info: Latest version of PHP is 8.2
Error: /app/www/.git (and subdirectories) are not executable, check the permissions
Foreign key: albums.parent_id               → albums.id            : RESTRICT
Foreign key: albums.id                      → base_albums.id       : RESTRICT
Foreign key: albums.cover_id                → photos.id            : CASCADE
Foreign key: base_albums.owner_id           → users.id             : RESTRICT
Foreign key: photos.album_id                → albums.id            : RESTRICT
Foreign key: photos.owner_id                → users.id             : RESTRICT
Foreign key: size_variants.photo_id         → photos.id            : RESTRICT
Foreign key: sym_links.size_variant_id      → size_variants.id     : RESTRICT
Foreign key: tag_albums.id                  → base_albums.id       : RESTRICT
Foreign key: user_base_album.base_album_id  → base_albums.id       : CASCADE
Foreign key: user_base_album.user_id        → users.id             : CASCADE

System Information
------------------
Lychee Version (git):                    ?? (60c6f34) -- Could not compare.
DB Version:                              4.7.0

composer install:                        --no-dev
APP_ENV:                                 production
APP_DEBUG:                               false

System:                                  Linux
PHP Version:                             8.1.14
PHP User agent:                          Lychee/4 (https://lycheeorg.github.io/)
Timezone:                                America/Chicago
Max uploaded file size:                  20M
Max post size:                           200M
Max execution time:                      200
MySQL Version:                           10.6.12-MariaDB-log

exec() Available:                        yes
Imagick Available:                       1
Imagick Enabled:                         1
Imagick Version:                         1808
GD Version:                              bundled (2.1.0 compatible)
Number of foreign key:                   11 found.

Config Information
------------------
version:                                 040700
check_for_updates:                       0
sorting_photos_col:                      taken_at
sorting_photos_order:                    DESC
sorting_albums_col:                      max_taken_at
sorting_albums_order:                    ASC
imagick:                                 1
skip_duplicates:                         0
small_max_width:                         0
small_max_height:                        360
medium_max_width:                        1920
medium_max_height:                       1080
lang:                                    en
layout:                                  1
image_overlay_type:                      desc
default_license:                         none
compression_quality:                     90
grants_full_photo_access:                1
delete_imported:                         0
mod_frame_enabled:                       1
mod_frame_refresh:                       30
thumb_2x:                                1
small_2x:                                1
medium_2x:                               1
landing_page_enable:                     0
site_owner:                              Gabby & Ryan
landing_title:                           John Smith
landing_subtitle:                        Cats, Dogs & Humans Photography
sm_facebook_url:                         
sm_flickr_url:                           
sm_twitter_url:                          
sm_instagram_url:                        
sm_youtube_url:                          
landing_background:                      dist/cat.webp
site_title:                              G & R
footer_show_copyright:                   0
site_copyright_begin:                    2019
site_copyright_end:                      2019
footer_additional_text:                  
footer_show_social_media:                0
public_search:                           1
SL_enable:                               0
SL_for_admin:                            0
public_recent:                           1
recent_age:                              1
public_starred:                          0
grants_download:                         0
photos_wraparound:                       1
map_display:                             0
zip64:                                   1
map_display_public:                      0
map_provider:                            Wikimedia
force_32bit_ids:                         0
map_include_subalbums:                   0
update_check_every_days:                 3
has_exiftool:                            1
share_button_visible:                    0
import_via_symlink:                      0
has_ffmpeg:                              1
location_decoding:                       0
location_decoding_timeout:               30
location_show:                           0
location_show_public:                    0
rss_enable:                              0
rss_recent_days:                         7
rss_max_items:                           100
prefer_available_xmp_metadata:           0
editor_enabled:                          1
lossless_optimization:                   0
swipe_tolerance_x:                       150
swipe_tolerance_y:                       250
local_takestamp_video_formats:           .avi|.mov
log_max_num_line:                        1000
unlock_password_photos_with_url_param:   0
nsfw_visible:                            1
nsfw_blur:                               0
nsfw_warning:                            0
nsfw_warning_admin:                      0
nsfw_banner_override:                    
map_display_direction:                   1
album_subtitle_type:                     oldstyle
upload_processing_limit:                 4
public_photos_hidden:                    1
new_photos_notification:                 1
legacy_id_redirection:                   1
zip_deflate_level:                       6
SA_enabled:                              1
default_album_protection:                1
album_decoration:                        layers
album_decoration_orientation:            row
allow_username_change:                   1
```
</details>

**Comment by d7415** [comment]
> I can open a new ticket if you would rather than me comment on this one.

Yes please. This ticket is unrelated.
