### ISSUE TITLE
Video Uploads

### ISSUE THREAD

**Issue by Mapantz** [LycheeOrg/Lychee#1136]
I apologize if I have posted in the wrong place..

I have searched, but could find no insights.

I cannot seem to upload videos using my Lychee installation. 
I have .mp4 in the video formats

"Server returned an unknown response. Please take a look at the console of your browser for further details."

Here's what the console says: https://ibb.co/jRtNNmj

My settings below:

max_execution_time = 200
post_max_size = 200M
upload_max_size = 200M
upload_max_filesize = 200M
max_file_uploads = 200
max_input_time = 60
max_input_vars = 1000
memory_limit = 100M
session.gc_maxlifetime = 1440
upload_max_filesize = 100M

Regards.

**Comment by d7415** [comment]
Please open a new issue and follow the template.
