### ISSUE TITLE
Chrome hangs often while browsing; other browsers are excellent

### ISSUE THREAD

**Issue by hess8** [LycheeOrg/Lychee#1138]
### Detailed description of the problem 
Chrome hangs many seconds ("Page Unresponsive", while scrolling through albums, while doing **any** of the following:
- page-up  (I can start paging down, but as soon as I hit page-up the page is unresponsive)
- mouse wheel scrolling on thumbnails or on right scroll bar 
- dragging the right scroll bar frequently

**Steps to reproduce the behavior:**
1.  Immediately when I hit page-up
2. Or: eventually while mouse wheel scrolling on thumbnails
3. Or: eventually while mouse wheel scrolling on right scroll bar 
4. Or: eventually while dragging up and down on right scroll bar 

This happens on brand new installs. Every session I test browsing photos with Chrome hangs in less that a minute.  On the other hand, Microsoft Edge and Firefox have excellent performance.  

While it hangs, I can sometimes scroll to see more thumbnails, but I can't open any photo or select it.

### Output of the diagnostics 
<html>
<body>
<div class="content contentZoomIn leftMenu__open" style="user-select: none; transition: margin-left 0.5s ease 0s; margin: 0px 0px 0px 250px; padding: 50px 30px 33px 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; line-height: inherit; font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 12px; vertical-align: baseline; display: flex; flex-wrap: wrap; align-content: flex-start; width: calc(100% - 280px); max-width: calc(100vw - 10px); color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(29, 29, 29); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; min-height: calc(((100vh - 50px) - 33px) - 36px);"><pre class="logs_diagnostics_view" style="user-select: none; transition: color 0.3s ease 0s, opacity 0.3s ease-out 0s, transform 0.3s ease-out 0s, box-shadow 0.3s ease 0s, -webkit-transform 0.3s ease-out 0s, -webkit-box-shadow 0.3s ease 0s; margin: 0px auto; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: 14px; font-family: inherit; font-size: 12px; vertical-align: baseline; width: 927.891px; color: rgb(204, 204, 204);"><pre id="content_diag_error" style="user-select: text; transition: color 0.3s ease 0s, opacity 0.3s ease-out 0s, transform 0.3s ease-out 0s, box-shadow 0.3s ease 0s, -webkit-transform 0.3s ease-out 0s, -webkit-box-shadow 0.3s ease 0s; margin: 0px; padding: 0px 30px 0px 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: monospace; font-size: 12px; vertical-align: baseline; width: fit-content;"><br class="Apple-interchange-newline">

    Diagnostics
    -------
    Warning: Dropbox import not working. dropbox_key is empty.
    Info: Latest version of PHP is 8
</pre>
<pre id="content_diag_sys" style="user-select: text; transition: color 0.3s ease 0s, opacity 0.3s ease-out 0s, transform 0.3s ease-out 0s, box-shadow 0.3s ease 0s, -webkit-transform 0.3s ease-out 0s, -webkit-box-shadow 0.3s ease 0s; margin: 0px; padding: 0px 30px 0px 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: monospace; font-size: 12px; vertical-align: baseline; width: fit-content;">

    System Information
    --------------
    Lychee Version (git):            master (815f896) - Data not in Cache
    DB Version:                      4.3.5
    
    composer install:                --no-dev
    APP_ENV:                         production
    APP_DEBUG:                       true
    
    System:                          Linux
    PHP Version:                     7.4
    Max uploaded file size:          1024M
    Max post size:                   1024M
    SQLite Version:                  3.36.0
    
    Imagick:                         1
    Imagick Active:                  1
    Imagick Version:                 1691
    GD Version:                      2.3.0
<pre class="" style="user-select: text; transition: color 0.3s ease 0s, opacity 0.3s ease-out 0s, transform 0.3s ease-out 0s, box-shadow 0.3s ease 0s, -webkit-transform 0.3s ease-out 0s, -webkit-box-shadow 0.3s ease 0s; margin: 0px; padding: 0px 30px 0px 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: monospace; font-size: 12px; vertical-align: baseline; width: fit-content;">    
    Lychee total space:              5.06 GB
    Upload folder space:             4.98 GB
    System total space:              2.15 TB
    System free space:               1.98 TB (92%)
</pre></pre>
<pre id="content_diag_conf" style="user-select: text; transition: color 0.3s ease 0s, opacity 0.3s ease-out 0s, transform 0.3s ease-out 0s, box-shadow 0.3s ease 0s, -webkit-transform 0.3s ease-out 0s, -webkit-box-shadow 0.3s ease 0s; margin: 0px; padding: 0px 30px 0px 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: monospace; font-size: 12px; vertical-align: baseline; width: fit-content;">

    Config Information
    --------------
    version:                         040305
    check_for_updates:               0
    sorting_Photos_col:              taken_at
    sorting_Photos_order:            ASC
    sorting_Albums_col:              max_taken_at
    sorting_Albums_order:            ASC
    imagick:                         1
    skip_duplicates:                 0
    small_max_width:                 0
    small_max_height:                360
    medium_max_width:                1920
    medium_max_height:               1080
    lang:                            en
    layout:                          1
    image_overlay_type:              desc
    default_license:                 none
    compression_quality:             90
    full_photo:                      1
    delete_imported:                 0
    Mod_Frame:                       1
    Mod_Frame_refresh:               30
    thumb_2x:                        1
    small_2x:                        1
    medium_2x:                       1
    landing_page_enable:             0
    landing_owner:                   John Smith
    landing_title:                   John Smith
    landing_subtitle:                Cats, Dogs &amp; Humans Photography
    landing_facebook:                https://www.facebook.com/JohnSmith
    landing_flickr:                  https://www.flickr.com/JohnSmith
    landing_twitter:                 https://www.twitter.com/JohnSmith
    landing_instagram:               https://instagram.com/JohnSmith
    landing_youtube:                 https://www.youtube.com/JohnSmith
    landing_background:              dist/cat.jpg
    site_title:                      Lychee v4
    site_copyright_enable:           0
    site_copyright_begin:            1930
    site_copyright_end:              1931
    additional_footer_text:          
    display_social_in_gallery:       0
    public_search:                   0
    SL_enable:                       0
    SL_for_admin:                    0
    public_recent:                   0
    recent_age:                      1
    public_starred:                  0
    downloadable:                    0
    photos_wraparound:               1
    map_display:                     1
    zip64:                           1
    map_display_public:              0
    map_provider:                    Wikimedia
    force_32bit_ids:                 0
    map_include_subalbums:           1
    update_check_every_days:         3
    has_exiftool:                    0
    share_button_visible:            0
    import_via_symlink:              0
    has_ffmpeg:                      0
    location_decoding:               1
    location_decoding_timeout:       30
    location_show:                   1
    location_show_public:            0
    rss_enable:                      0
    rss_recent_days:                 7
    rss_max_items:                   100
    prefer_available_xmp_metadata:   0
    editor_enabled:                  1
    lossless_optimization:           0
    swipe_tolerance_x:               150
    swipe_tolerance_y:               250
    local_takestamp_video_formats:   .avi|.mov
    log_max_num_line:                1000
    unlock_password_photos_with_url_param: 0
    nsfw_visible:                    1
    nsfw_blur:                       0
    nsfw_warning:                    0
    nsfw_warning_admin:              0
    map_display_direction:           1
    album_subtitle_type:             oldstyle
    upload_processing_limit:         4
    public_photos_hidden:            1
    new_photos_notification:         0
</pre>
</pre></div><div class="sidebar" style="user-select: none; transition: transform 0.3s cubic-bezier(0.51, 0.92, 0.24, 1) 0s, -webkit-transform 0.3s cubic-bezier(0.51, 0.92, 0.24, 1) 0s; margin: 0px; padding: 0px; border-width: 0px 0px 0px 1px; border-top-style: initial; border-right-style: initial; border-bottom-style: initial; border-left-style: solid; border-top-color: initial; border-right-color: initial; border-bottom-color: initial; border-left-color: rgba(0, 0, 0, 0.2); border-image: initial; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; line-height: inherit; font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 12px; vertical-align: baseline; position: fixed; top: 49px; right: -360px; width: 350px; height: calc(100% - 49px); background-color: rgba(25, 25, 25, 0.98); transform: translateX(0px); z-index: 4; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="sidebar__header" style="user-select: none; transition: color 0.3s ease 0s, opacity 0.3s ease-out 0s, transform 0.3s ease-out 0s, box-shadow 0.3s ease 0s, -webkit-transform 0.3s ease-out 0s, -webkit-box-shadow 0.3s ease 0s; margin: 0px; padding: 0px; border-width: 1px 0px 0px; border-top-style: solid; border-right-style: initial; border-bottom-style: initial; border-left-style: initial; border-top-color: rgb(34, 147, 236); border-right-color: initial; border-bottom-color: initial; border-left-color: initial; border-image: initial; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-size: 12px; vertical-align: baseline; float: left; height: 49px; width: 350px; background: linear-gradient(rgba(255, 255, 255, 0.02), rgba(0, 0, 0, 0));"><h1 style="user-select: text; transition: color 0.3s ease 0s, opacity 0.3s ease-out 0s, transform 0.3s ease-out 0s, box-shadow 0.3s ease 0s, -webkit-transform 0.3s ease-out 0s, -webkit-box-shadow 0.3s ease 0s; margin: 15px 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 700; font-stretch: inherit; line-height: inherit; font-family: inherit; font-size: 16px; vertical-align: baseline; position: absolute; width: 350px; color: rgb(255, 255, 255); text-align: center;">About</h1></div><div class="sidebar__wrapper" style="user-select: none; transition: color 0.3s ease 0s, opacity 0.3s ease-out 0s, transform 0.3s ease-out 0s, box-shadow 0.3s ease 0s, -webkit-transform 0.3s ease-out 0s, -webkit-box-shadow 0.3s ease 0s; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-size: 12px; vertical-align: baseline; float: left; height: calc(100% - 49px); width: 350px; overflow: auto;"><div class="sidebar__divider" style="user-select: none; transition: color 0.3s ease 0s, opacity 0.3s ease-out 0s, transform 0.3s ease-out 0s, box-shadow 0.3s ease 0s, -webkit-transform 0.3s ease-out 0s, -webkit-box-shadow 0.3s ease 0s; margin: 0px; padding: 12px 0px 8px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-size: 12px; vertical-align: baseline; float: left; width: 350px; box-shadow: none;"><h1 style="user-select: text; transition: color 0.3s ease 0s, opacity 0.3s ease-out 0s, transform 0.3s ease-out 0s, box-shadow 0.3s ease 0s, -webkit-transform 0.3s ease-out 0s, -webkit-box-shadow 0.3s ease 0s; margin: 0px 0px 0px 20px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 700; font-stretch: inherit; line-height: inherit; font-family: inherit; font-size: 14px; vertical-align: baseline; color: rgba(255, 255, 255, 0.6);">Basics</h1></div>

</div></div>
</body>
</html>

### Browser and system
Chrome latest version, Windows 10

**Comment by LouisVallat** [comment]
Hi, do you have any plugins on Chrome that you don't have in FF or MS Edge? Is the issue still there when trying on Chrome in Private Navigation?

**Comment by hess8** [comment]
Hi.  I turned off all plugins and restarted Chrome.  It still hangs. 

I tried incognito mode in Chrome and it still hangs.

**Comment by ildyria** [comment]
@hess8 can you drop in gitter : https://gitter.im/LycheeOrg/Lobby and give us a link to your gallery there because to me this seems very specific to your installation.

**Comment by hess8** [comment]
I posted the gallery link for testing.

**Comment by hess8** [comment]
Thanks, a bunch of people tested my server and it works great in chrome for them.  I guess it's just my chrome install.  Thanks.
