### ISSUE TITLE
REST-ify API

### ISSUE THREAD

**Issue by hermzz** [LycheeOrg/Lychee#114]
The current API abuses POST methods which shouldn't really be used for read-only requests. The following endpoints should be GET requests:

```
/api/Albums::get
/api/Album::get
/api/Album::getPublic
/api/Frame::getSettings
/api/Photo::get
/api/Photo::getRandom
/api/Sharing::List
/api/Sharing::ListUser
/api/Settings::getAll
/api/User::List
/api/Logs
/api/Diagnostics
```

As an aside, the current URL format is a bit awkward and unorthodox, updating it to something a bit more readable could be helpful (ie: `/api/Album::get` to `/api/album/{id}`).

**Comment by ildyria** [comment]
I know, but this makes it hard to manage the compatibility between Lychee v3 and Lychee v4 for the front-end. :/

However I can see why and why not 
```
/api/Albums::get
/api/Album::get
```
should be GET and POST. E.g. as an admin, if you move a picture, you may not want the browser to cache the GET request on `/api/album/{id}` :neutral_face:

**Comment by hermzz** [comment]
Yeah I wouldn't bother tackling this until v3 is no more.

The idea with a proper REST API is that it's the combination of method _and_ path that describes what the the URL does. So for example you can have multiple actions based on the same URL: `GET /api/album/{id}` retrieves an album, `POST /api/album/{id}` edits the album, `DELETE /api/album/{id}` deletes the album, and `PUT /api/album/{id}` could be used to add photos to an album. That last one doesn't make much sense based on how albums work, but you get the idea.

I've never encountered issues with browsers caching API GET requests, but if it happens it's easily solvable by including any number of cache (`Cache-Control`, `Expires`, or even `Etag`) headers.
