### ISSUE TITLE
[Enhancement] Add the ability to modify the tags of a tag album after creation

### ISSUE THREAD

**Issue by nanawel** [LycheeOrg/Lychee#1140]
There seems to be no way in the GUI at the moment to modify the tags associated to a tag album once it's been created.
It's possible to rename it, but not to change the tags. The only solution is to create a new tag album but it's not ideal.

I guess there could be a "Tags" field on the "Rename" dialog.

**Comment by kamil4** [comment]
Actually, there _already is_ a way to modify the tags: using the sidebar ("info" dialog). There is an editable field `Tags to show` in there.

**Comment by nanawel** [comment]
Ah, so there must be an intermittent issue with the sidebar then, because most of the time it's empty for tag albums.

![image](https://user-images.githubusercontent.com/4866761/142144759-77f1443b-786a-4210-a11c-b412230aba8d.png)

I'm using **Lychee 4.3.4**.

**Comment by kamil4** [comment]
Incidentally, I was fixing some unrelated bugs in the front end last night and noticed the same behavior as well. It should be fixed when https://github.com/LycheeOrg/Lychee-front/pull/278 gets merged.
