### ISSUE TITLE
[Beginner Question] How to integrate Lychee photos or Albums elsewhere?

### ISSUE THREAD

**Issue by flow7** [LycheeOrg/Lychee#1160]
Hi, this might be either super easy or solved elsewhere already, though I couldn't find it yet.

Usecase:
- photos in a Lychee setup, split into various albums etc
- blog elsewhere, in this case a Grav CMS setup

Question: 
- Is there an easy way to integrate Lychee photos or even entire albums on a different page?
 - I don't want to just link to Lychee, but rather have the pics displayed on that other page.

Any suggestions?
THANKS

**Comment by ildyria** [comment]
We have some links about that in our [FAQ](https://lycheeorg.github.io/docs/faq.html) which I think is related to your question:
[Can I host Lychee with a subpath with Nginx? Like `https://example.dev/lychee/`](https://lycheeorg.github.io/docs/faq.html#can-i-host-lychee-with-a-subpath-with-nginx-like-httpsexampledevlychee)
[Can I host Lychee with a subpath with Apache? Like `https://example.dev/lychee/`](https://lycheeorg.github.io/docs/faq.html#can-i-host-lychee-with-a-subpath-with-apache-like-httpsexampledevlychee)

This should help.
