### ISSUE TITLE
DOCUMENTATION] How to configurate Lychee to use PHP 8.0 when others web application use PHP 7.4

### ISSUE THREAD

**Issue by JacquelinDV** [LycheeOrg/Lychee#1161]
Coukd you make a documentation to use APACHE 2 + PHP 8.0 when Exist some web application which use APACHE 2 + PHP 7.4? Or give a link where this is explained!

**Comment by ildyria** [comment]
Here are some pointers:
https://www.digitalocean.com/community/tutorials/how-to-run-multiple-php-versions-on-one-server-using-apache-and-php-fpm-on-ubuntu-18-04
Of course you will need to replace the phpX.X-fpm by the appropriate versions.

Assuming Debian, you can install php8 following those steps: https://computingforgeeks.com/how-to-install-php-on-debian-linux/
Or you can add the testing/sid to your apt and install php 8.1 from there as it is now available:
https://packages.debian.org/source/sid/php8.1

I would recommend the 8.1 way so you are all set for the next 2 years.

Also worth noting as you will need to run composer with the specific php version:
https://stackoverflow.com/a/52146990/3981163

**Comment by JacquelinDV** [comment]
Merci beaucoup

Le lun. 6 déc. 2021 à 20:45, Benoît Viguier ***@***.***> a
écrit :
