### ISSUE TITLE
installation requires Intl

### ISSUE THREAD

**Issue by yuorfaec** [LycheeOrg/Lychee#1163]
### Detailed description of the problem [REQUIRED]
Installation will not continue if Intl is not installed, but per @ildyria in https://github.com/LycheeOrg/LycheeOrg.github.io/pull/40#discussion_r765128105_, this is no longer true.

### Steps to reproduce the issue
1. Install apache2, mysql, PHP, PHP extensions
2. Clone from GitHub and install via composer, restart apache2
3. Navigate to domain
4. Click 'Next >'

**Screenshots**
https://gist.github.com/yuorfaec/4602f7eb9980ca71e47622cca159e4ba
![](https://gist.githubusercontent.com/yuorfaec/4602f7eb9980ca71e47622cca159e4ba/raw/0fa081d1cf389e45ee66399e3c68ae6b1e0fda4d/install.png)

### Output of the diagnostics  [REQUIRED]
None, installation not complete (500 Server error/Could not open input file: artisan)

### Browser and system
Server: Ubuntu  20.04, PHP 8.0.13, mysql 8.0.27, apache 2.4.41
Client: Windows 10 20H2 19042.1348, Firefox 94.0.2

**Comment by ildyria** [comment]
Weird, I thought I fixed that one.

**Comment by ildyria** [comment]
Crap forgot to remove it here: 
https://github.com/LycheeOrg/Lychee/pull/1145/files#diff-48fe38da3ea525d25449927b41456cd9c0bdd5d57616b8a0fe9abe8b52a3ea00L29
