### ISSUE TITLE
ParseError after upgrade

### ISSUE THREAD

**Issue by stanelie** [LycheeOrg/Lychee#1167]
### Detailed description of the problem [REQUIRED]
After clicking on the upgrade button, my Lychee no longer works, I get a "ParseError" error message

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Click on Upgrade

**Screenshots**
![2021-12-13 14_45_04-Whoops! There was an error](https://user-images.githubusercontent.com/2935029/145877792-6c1c12d8-224b-49e6-8312-e34429e1986c.png)

### Output of the diagnostics  [REQUIRED]
```
   ParseError

  syntax error, unexpected '|', expecting ';' or '{'

  at app/Metadata/GitHubFunctions.php:59
     55▕         * Return false if the file is not readable.
     56▕         *
     57▕         * @return false|string
     58▕         */
  ➜  59▕        public function get_current_branch(): string|false
     60▕        {
     61▕                // @codeCoverageIgnoreStart
     62▕                $head_file = base_path('.git/HEAD');
     63▕                $branch_ = file_get_contents($head_file);

      +1 vendor frames
  2   [internal]:0
      Composer\Autoload\ClassLoader::loadClass()

  3   [internal]:0
      spl_autoload_call()

```

### Browser and system
Ubuntu 21.04, Chrome latest

**Comment by ildyria** [comment]
I'm pretty sure that is because you are using php7.4. Please update to php8.0 (or better php8.1) and this will be fixed.

**Comment by stanelie** [comment]
I will verify this shortly.

Might i suggest a sanity verification upon pushing the "update" button to warn users of unmet minimum system requirements? I can't be the only one that uses a server that is not updated as quickly as the bleeding edge Lychee requirements, this is bound to happen again and waste the nice developer's time again. 🙂

Thanks!

**Comment by ildyria** [comment]
> Might i suggest a sanity verification upon pushing the "update" button to warn users of unmet minimum system requirements?

Good one ! :)

**Comment by stanelie** [comment]
Updating to PHP 8 fixed my issue.
Thanks.
