### ISSUE TITLE
Error: Wrong property for image_overlay_type in database

### ISSUE THREAD

**Issue by stanelie** [LycheeOrg/Lychee#1169]
### Detailed description of the problem [REQUIRED]
Error message in diagnostics, looks like it didn't like that I upgraded

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Clic on Diagnostics

**Screenshots
![2021-12-14 12_08_43-photo stanelie com - Diagnostics](https://user-images.githubusercontent.com/2935029/146046028-573a5fa0-71ac-4752-ae87-028f0eb745e8.png)
**

### Output of the diagnostics  [REQUIRED]
```
    Diagnostics
    -------
    Error: Wrong property for image_overlay_type in database, expected exif or desc or date or none, got takedate
    Warning: Dropbox import not working. dropbox_key is empty.
    Warning: You may experience problems when uploading a photo of large size. Take a look in the FAQ for details.
    Warning: You may experience problems when uploading a photo of large size. Take a look in the FAQ for details.
    Warning: You may experience problems when uploading a photo of large size or handling many/large albums. Take a look in the FAQ for details.
    Info: Latest version of PHP is 8.1
```

### Browser and system
Ubuntu 21.04, latest Chrome

**Comment by stanelie** [comment]
Just changed the value "takedate" to "date" in directly in the database, it fixed the error message.
Maybe an upgrade script missed the name change of this field's value?

**Comment by nagmat84** [comment]
Seems so. In particular, `takedate` was renamed into `taken_at` in order to be consistent with `created_at` and `updated_at` and to stress that it is not only a date but also includes a time. So while `takedate` is deprecated and should have been converted into `taken_at` by a migration, the attribute `date` is completely wrong. It had never existed nor does it exist.

**Comment by stanelie** [comment]
Hum...
I tried `taken_at` and diagnostics now complains about it too.

In the database, configs, image_overlay_type , the `type_range` value is `exif|desc|date|none` , hinting at these being the only values allowed. `date` does not throw an error message

**Comment by nagmat84** [comment]
I already have suspected so from your previous comment. Yes, I already have noticed that `type_range` for your installation includes `date`. But why?! That shouldn't be there. Note, this is a rhetorical question. I don't expect you to know the answer to it.

It seems we have a bug here and will investigate that on the weekend.

**Comment by kamil4** [comment]
`date` is a supported value: see https://github.com/LycheeOrg/Lychee/blob/master/database/migrations/2021_03_03_175555_config_remove_image_overlay.php. It does look though like that migration is incomplete; it updates the range without converting the old value if needed.
