### ISSUE TITLE
Dropped PHP 7.4 support

### ISSUE THREAD

**Issue by KarelWintersky** [LycheeOrg/Lychee#1170]
### Detailed description of the problem [REQUIRED]
```
root@blacktower:/var/www/gallery# composer install --no-dev
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]? y
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 2
    - spatie/laravel-feed is locked to version 4.0.5 and an update of this package was not requested.
    - spatie/laravel-feed 4.0.5 requires php ^8.0 -> your php version (7.4.25) does not satisfy that requirement.
  Problem 3
    - symfony/css-selector is locked to version v6.0.0 and an update of this package was not requested.
    - symfony/css-selector v6.0.0 requires php >=8.0.2 -> your php version (7.4.25) does not satisfy that requirement.
  Problem 4
    - symfony/event-dispatcher-contracts is locked to version v3.0.0 and an update of this package was not requested.
    - symfony/event-dispatcher-contracts v3.0.0 requires php >=8.0.2 -> your php version (7.4.25) does not satisfy that requirement.
  Problem 5
    - symfony/string is locked to version v6.0.0 and an update of this package was not requested.
    - symfony/string v6.0.0 requires php >=8.0.2 -> your php version (7.4.25) does not satisfy that requirement.
  Problem 6
    - symfony/translation is locked to version v6.0.0 and an update of this package was not requested.
    - symfony/translation v6.0.0 requires php >=8.0.2 -> your php version (7.4.25) does not satisfy that requirement.
  Problem 7
    - symfony/translation-contracts is locked to version v3.0.0 and an update of this package was not requested.
    - symfony/translation-contracts v3.0.0 requires php >=8.0.2 -> your php version (7.4.25) does not satisfy that requirement.
  Problem 8
    - symfony/var-exporter is locked to version v6.0.0 and an update of this package was not requested.
    - symfony/var-exporter v6.0.0 requires php >=8.0.2 -> your php version (7.4.25) does not satisfy that requirement.
  Problem 9
    - symfony/translation v6.0.0 requires php >=8.0.2 -> your php version (7.4.25) does not satisfy that requirement.
    - nesbot/carbon 2.55.2 requires symfony/translation ^3.4 || ^4.0 || ^5.0 || ^6.0 -> satisfiable by symfony/translation[v6.0.0].
    - nesbot/carbon is locked to version 2.55.2 and an update of this package was not requested.
```
### How to reproduce?

```
git clone ...
composer install --no-dev
```

### Browser and system

Debian 11, PHP 7.4

**Comment by ildyria** [comment]
Yes. I think we are pretty explicit in that regard:
https://github.com/LycheeOrg/Lychee/releases/tag/v4.4.0 : **Version 4.4.0 - Full support of PHP 8.0 and 8.1 - dropped 7.4**

Documentation requirements:
https://lycheeorg.github.io/docs/#server-requirements

![2021-12-14_1920x1080_22:00:22](https://user-images.githubusercontent.com/627094/146078705-3983bad8-5b7e-4e06-b945-53e519ac455d.png)

I personally consider PHP 7.4 EoL. If you wish to continue using bleeding edge Lychee, please upgrade to PHP 8.0 or 8.1

**Comment by ildyria** [comment]
And I will repost it again here:

> We are aware this may not be a popular decision.
> 
> Please accept the rationale of such change:
> - [Php supported version](https://www.php.net/supported-versions.php): we want to **stay in the green zone**, anything orange is ignored.
> - PHP 8.0 brings lots of improvements: stronger typing, JIT... read more [here](https://stitcher.io/blog/new-in-php-8)
> - [Spatie](https://github.com/spatie) requires in all their updated packages to be in version 8.0 (basically some of our dependencies).

**Comment by KarelWintersky** [comment]
Stable debian 11 does not have PHP 8.0 in default repo. 

So, how I can downgrade Lychee to PHP 7.4 support?

**Comment by KarelWintersky** [comment]
Also, README have:
```
To run Lychee, everything you need is a web-server with PHP 7.4 or later and a MySQL-Database. Follow the instructions to install Lychee on your server. This version of Lychee is built on the Laravel framework. To install:
```

**Comment by LouisVallat** [comment]
> Stable debian 11 does not have PHP 8.0 in default repo. 

You can wait for the official debian release, or you can add a PPA such as https://github.com/oerdnj/deb.sury.org to get it faster (not an endorsement).

**Comment by LouisVallat** [comment]
> Also, README have:
> ```
> To run Lychee, everything you need is a web-server with PHP 7.4 or later and a MySQL-Database. Follow the instructions to install Lychee on your server. This version of Lychee is built on the Laravel framework. To install:
> ```
> 

Oops, thanks for noticing, it'll need to be fixed (even tho it says everywhere else that ≥ 8.0 is the only supported version).

**Comment by mhthies** [comment]
The official Debian release of php 8.x will only be available with the next Debian release, which will be released in mid 2023, following the regular 2 year release cycle. I hope, you are aware that you exclude everyone running their webserver on plain Debian without fishy third-party repositories from newer Lychee releases until then. I'm affected by this issue as well.

**Comment by nagmat84** [comment]
> I hope, you are aware that you exclude everyone running their webserver on plain Debian without fishy third-party repositories from newer Lychee releases until then. I'm affected by this issue as well.

Yes, we are aware of that fact. Also see the @ildyria‘s [post in this thread](https://github.com/LycheeOrg/Lychee/issues/1170#issuecomment-994007200): "we are aware that this may not a popular decision". This quote is also part of the official release notes. So there is no reason to insinuate we did this step thoughtlessly. There was also some discussions among us developers about this, but basically we had no other choice. I am not repeat the arguments here, please see the release notes for the rationale.

Of course, it is up to you  how you personally assess the "fishiness" of 3rd-party repositories, but take into consideration that
https://deb.sury.org/ (which provides a PPA for PHP 8 on stable Debian 11) is run by the official Debian maintainer of PHP himself.

**Comment by KarelWintersky** [comment]
Is benefits of PHP 8.0 REALLY using in your projects now?

**Comment by d7415** [comment]
> Is benefits of PHP 8.0 REALLY using in your projects now?

Please read the linked issue.

Aside: From some experimentation, most of the packages are available with php8.1 in Debian `testing`/`bookworm` now - it appears imagick is lagging behind, but hopefully that will be usable soon. Alternatively there's the PPA linked above and hopefully I'll be migrating the Docker version soon.

Feel free to keep an eye on the release notes - it's quite possible everything will be in place before there's a feature or fix that you need.

Useful feedback is welcome, but if we end up repeating ourselves again and again we may have to lock this issue.

**Comment by KarelWintersky** [comment]
> Please read the linked issue.

sorry, which linked issue? O.o

**Comment by ildyria** [comment]
@d7415 meant the issue: #1170.
Also the issue about enforcing php8 where some of the discussion happened: #1072  
We also discussed this on gitter: https://gitter.im/LycheeOrg/Lobby

> Is benefits of PHP 8.0 REALLY using in your projects now?

In one word, **yes**.

In short: we do use the stronger typing provided (**more type safety**, _that reason alone is enough for me to move forward._) and coalescing operator (simpler code).

And if it were just me, we would have already moved to php 8 already 6 months ago.

**Comment by KarelWintersky** [comment]
ok.
Also, link to issue #1170 from issue #1170 looks like excessive recursion. 

Also, two branches - with PHP 7.4 and PHP 8.0 support will be more... community-friendly solution. 

Throwing overboard those who use stable Debian builds seems to me to be a disregard for the message of the users of the Lychee. (sorry for google translate)

**Comment by kamil4** [comment]
As the already linked https://www.php.net/supported-versions.php indicates, PHP 7.4 is already out of active support and security support will end if November 2022. As one of you mentioned in an earlier comment, the next stable version of Debian with PHP 8 support won't be out until mid-2023. Even if we had delayed the transition of Lychee to PHP 8.0 until November 2022, what do you suggest we should do between then and mid-2023?

While I have wondered myself at times if the project is not unnecessarily aggressive regarding our minimum PHP version requirements, accommodating the release cycle of Debian stable really isn't a viable strategy.

Those who want stability can always stay with Lychee 4.3.6. One thing I would certainly agree with is that there should be a mechanism in place for updates to check that the server meets the requirements of the new version before the old version is overwritten...

**Comment by KarelWintersky** [comment]
> Those who want stability can always stay with Lychee 4.3.6.

I think a good solution would be to add a mention to the file that for PHP 7.4, you should select Lychee 4.3.6 (via git checkout XXX) or 'download release'.
