### ISSUE TITLE
Exported picture is missing EXIF info

### ISSUE THREAD

**Issue by stanelie** [LycheeOrg/Lychee#1171]
### Detailed description of the problem [REQUIRED]
When I export a picture from my Lychee install (original size), I get a download that is missing the original's exif info

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. clic on Download
2. choose original size
3. run exiftool on the download picture
4. See exif info missing, even if it is correctly displayed within Lychee

**Screenshots**
![2021-12-14 16_45_05-photo stanelie com - 2_picasa-5668378310821258642_1024x768](https://user-images.githubusercontent.com/2935029/146084388-fbd39fa4-0402-47ca-b062-9ee996cf42b7.png)

![2021-12-14 16_45_31-root@monitor_ _var_www_lychee_public_uploads_big](https://user-images.githubusercontent.com/2935029/146084401-bc84e02e-3e57-40db-b847-11a50204f32f.png)

### Output of the diagnostics  [REQUIRED]
```
    Diagnostics
    -------
    Warning: Dropbox import not working. dropbox_key is empty.
    Info: Latest version of PHP is 8.1



    System Information
    --------------
    Lychee Version (git):            master (31f8d34) - Up to date (3 hours ago).
    DB Version:                      4.4.0
    
    composer install:                dev
    APP_ENV:                         local
    APP_DEBUG:                       true
    
    System:                          Linux
    PHP Version:                     8
    PHP User agent:                  Lychee/4 (https://lycheeorg.github.io/)
    Max uploaded file size:          100M
    Max post size:                   100M
    Max execution time:              200
    MySQL Version:                   10.5.13-MariaDB-0ubuntu0.21.04.1
    
    Imagick:                         1
    Imagick Active:                  0
    Imagick Version:                 1691
    GD Version:                      2.3.0
```

### Browser and system
Ubuntu 21.04, latest Chrome

**Comment by ildyria** [comment]
BTW I see that `Imagick` is not active.

Can you check in the settings if you have the image optimizers enabled ?

**Comment by nagmat84** [comment]
Does this happen to all photos or only to photos that need rotation? Normally Lychee does not touch the original image file, so Exif data cannot be lost, except the image needs rotation. As I can see from your diagnostic, Imagick is disabled. Please enable Imagick and try again. If an image is rotated without Imagick, then Lychee falls back to GD Image which does not save Exif data.

**Comment by LouisVallat** [comment]
Just tried on my instance running latest docker version (4.3.6) and cannot reproduce the bug.

**Comment by stanelie** [comment]
I enabled Imagick on my instance. What do I need to do to re-process the photos with it?

**Comment by kamil4** [comment]
Unfortunately, since the "original" size images were overwritten, you will need to delete those photos and reupload them all...

**Comment by stanelie** [comment]
Ok, thanks. If I discover this is still an issue, I will reopen this ticket.
