### ISSUE TITLE
Unable to show sensitive albums on mobile

### ISSUE THREAD

**Issue by vjuliano** [LycheeOrg/Lychee#1174]
### Detailed description of the problem [REQUIRED]
It seems that it is currently impossible to unhide sensitive albums while viewing on mobile (atleast on Android).  On desktop one presses 'h' key to toggle visibility.  There is no readily available way to do this on mobile.
Or I am just not bright enough to figure out how to do this.

### Steps to reproduce the issue
Have a hidden album at root level.
View gallery on mobile (Android for me but I suspect same on IOS)
Attempt to view hidden album.

### Output of the diagnostics  [REQUIRED]

    Diagnostics
    -------
    Warning: Dropbox import not working. dropbox_key is empty.

    System Information
    --------------
    Lychee Version (git):            master (a7de020) - Data not in Cache
    DB Version:                      4.4.0
    
    composer install:                dev
    APP_ENV:                         production
    APP_DEBUG:                       true
    
    System:                          Linux
    PHP Version:                     8.1
    PHP User agent:                  Lychee/4 (https://lycheeorg.github.io/)
    Max uploaded file size:          500M
    Max post size:                   500M
    Max execution time:              200
    MySQL Version:                   10.5.13-MariaDB-0ubuntu0.21.10.1
    
    Imagick:                         1
    Imagick Active:                  1
    Imagick Version:                 1691
    GD Version:                      2.3.0

    Config Information
    --------------
    version:                         040400
    check_for_updates:               1
    sorting_Photos_col:              id
    sorting_Photos_order:            DESC
    sorting_Albums_col:              max_taken_at
    sorting_Albums_order:            DESC
    imagick:                         1
    skip_duplicates:                 1
    small_max_width:                 0
    small_max_height:                360
    medium_max_width:                1920
    medium_max_height:               1080
    lang:                            en
    layout:                          1
    image_overlay_type:              none
    default_license:                 CC-BY-NC-ND-4.0
    compression_quality:             90
    full_photo:                      1
    delete_imported:                 1
    Mod_Frame:                       1
    Mod_Frame_refresh:               30
    thumb_2x:                        1
    small_2x:                        1
    medium_2x:                       1
    landing_page_enable:             1
    landing_owner:                   Vincent Juliano
    landing_title:                   Life on 35mm
    landing_subtitle:                Click top right to continue.  Next page top left to login
    landing_facebook:                
    landing_flickr:                  
    landing_twitter:                 
    landing_instagram:               
    landing_youtube:                 
    landing_background:              /uploads/medium/3d4bf4e35e5ea06853d7983c88efb6a2.jpg
    site_title:                      Vince Juliano's Photo Gallery
    site_copyright_enable:           1
    site_copyright_begin:            2021
    site_copyright_end:              2021
    additional_footer_text:          "Alex's Photos" copyright Alex Panicacci 2021
    display_social_in_gallery:       0
    public_search:                   0
    SL_enable:                       0
    SL_for_admin:                    0
    public_recent:                   0
    recent_age:                      30
    public_starred:                  0
    downloadable:                    1
    photos_wraparound:               1
    map_display:                     1
    zip64:                           1
    map_display_public:              1
    map_provider:                    Wikimedia
    force_32bit_ids:                 0
    map_include_subalbums:           1
    update_check_every_days:         3
    has_exiftool:                    1
    share_button_visible:            0
    import_via_symlink:              0
    has_ffmpeg:                      1
    location_decoding:               1
    location_decoding_timeout:       30
    location_show:                   1
    location_show_public:            1
    rss_enable:                      0
    rss_recent_days:                 7
    rss_max_items:                   100
    prefer_available_xmp_metadata:   0
    editor_enabled:                  1
    lossless_optimization:           1
    swipe_tolerance_x:               150
    swipe_tolerance_y:               250
    local_takestamp_video_formats:   .avi|.mov
    log_max_num_line:                1000
    unlock_password_photos_with_url_param: 0
    nsfw_visible:                    0
    nsfw_blur:                       0
    nsfw_warning:                    0
    nsfw_warning_admin:              0
    map_display_direction:           1
    album_subtitle_type:             oldstyle
    upload_processing_limit:         4
    public_photos_hidden:            1
    new_photos_notification:         1

### Browser and system
Android 11.  Firefox and Opera

**Comment by LouisVallat** [comment]
Hi,
I believe there's no way right now to do this on mobile, indeed. Will have to check and confirm, but I didn't find it in the code.
What would you see as an action to show the sensitive albums on mobile, comparable to the "press the h key" thing on desktop?

**Comment by vjuliano** [comment]
Idk I was thinking it would have to be a button at the top right with the others to toggle visibility, but it is already crowded in that top bar on mobile.  This might be a separate ticket, but I also noticed the context menus dont seem to work on mobile either.  Long tapping uses normal browser  context menu, not lychee custom one.

**Comment by LouisVallat** [comment]
> This might be a separate ticket

Yup, could you please open another issue so it can be marked and sorted for easier treatment?
