### ISSUE TITLE
[Enhancement]Use progressive loading of thumbnails for large albums.

### ISSUE THREAD

**Issue by vjuliano** [LycheeOrg/Lychee#1175]
If I use the search functionality to search for a term that returns many results, "2021" in my example,  only the thumbnails for the images in view load.  As I scroll, it then proceeds to load the thumbs for the images that are entering view.  This works really nicely and does not bog down client or server.  

However if I have an album with a large number of member images, it tries to load all thumbs at once,  hanging client for a long period of time.  I can easily replicate this by making the 'Recent' smart album include all of 2021.  It becomes unusable.  

Can the progressive loading of thumbs as view is scrolled be used across the UI?

I can include more quantitative data such as load times, num of images etc if that is useful.

**Comment by kamil4** [comment]
I'm a little surprised by your report.

I mean, sure, Lychee can slow down to a crawl for very large albums. My rule-of-the-thumb is 1,000 images max per album -- more than that can really slow things down.

The part that surprises me, however, is that you don't see this problem with search results. Perhaps there is some small but critical difference that I'm not aware of, but in broad terms, displaying search results is internally implemented in the same way as displaying an album. So there really should be no difference here?!

In general:
* the server always returns all images to the front end in a single API call (i.e., when you open an album or perform a search, _all_ the images are returned at the same time in one large response; they are not returned in parts/as  need/or anything like that)
* the front end (and the web browser in general) lays out all the images in one go; in my experience this is the part that takes the most time when loading large albums
* the front end uses lazy loading for all thumbs (so the image files are loaded only for the currently visible photo thumbs) so I think we are already doing what you are postulating?

If your observations are different from I wrote above, then by all means, go ahead and share your quantitative data. Thank you!

**Comment by nagmat84** [comment]
Although the third bullet point above makes it clear, I would just like to restate the first bullet point a bit more precisely:

> In general:
> * the server always returns **the URLs of all images** to the front end in a single API call […]

**Comment by vjuliano** [comment]
It turns out I was just mistaken how regular albums load.  It seems they do the same thing.  But what I have noticed is search results with a large result set seem to behave better than an album with similar results.  I am having issues getting numbers, but if I do a search for '2021' which should return pretty much every pic from 2021 based on file name, it takes a bit to load, but works well over all.  Now if I make my Recent smart album contain everything from last 300 days, it locks up browser and is unusable.  Is there a cap on the max result set size?

**Comment by kamil4** [comment]
There is no cap in Lychee, although there are various memory limits in PHP, and there may be limits and timeouts both on the web server side and in the web browser.

For getting timings, we recommend using your browser's debug console (typically F12 for desktop browsers), specifically the networking tab.

**Comment by haivala** [comment]
Just out of curiosity has anyone tried to use `loading="lazy"` in image tag?

https://developer.mozilla.org/en-US/docs/Web/Performance/Lazy_loading#images_and_iframes

**Comment by kamil4** [comment]
Lychee uses [lazysizes](https://github.com/aFarkas/lazysizes) which provides this functionality and predates "native" lazy support in the browsers.
