### ISSUE TITLE
Sensitive albums appear in search results

### ISSUE THREAD

**Issue by vjuliano** [LycheeOrg/Lychee#1176]
### Detailed description of the problem [REQUIRED]
Albums which are marked sensitive appear in search results.  Including when sensitive album visibility is not toggled on.  If the album is a sub album of another sensitive album, if you navigate to it from search results, UI back button in top left will bring you to parent sub album rather than back to search results.

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Make an album and mark it sensitive 
2. Add a few images.  Not sure this is necessary.
3. Go back to top level gallery
4. Search for sensitive album name

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

### Output of the diagnostics  [REQUIRED]

    Diagnostics
    -------
    Warning: Dropbox import not working. dropbox_key is empty.

    System Information
    --------------
    Lychee Version (git):            master (a7de020) - Data not in Cache
    DB Version:                      4.4.0
    
    composer install:                dev
    APP_ENV:                         production
    APP_DEBUG:                       true
    
    System:                          Linux
    PHP Version:                     8.1
    PHP User agent:                  Lychee/4 (https://lycheeorg.github.io/)
    Max uploaded file size:          500M
    Max post size:                   500M
    Max execution time:              200
    MySQL Version:                   10.5.13-MariaDB-0ubuntu0.21.10.1
    
    Imagick:                         1
    Imagick Active:                  1
    Imagick Version:                 1691
    GD Version:                      2.3.0

    Config Information
    --------------
    version:                         040400
    check_for_updates:               1
    sorting_Photos_col:              id
    sorting_Photos_order:            DESC
    sorting_Albums_col:              max_taken_at
    sorting_Albums_order:            DESC
    imagick:                         1
    skip_duplicates:                 1
    small_max_width:                 0
    small_max_height:                360
    medium_max_width:                1920
    medium_max_height:               1080
    lang:                            en
    layout:                          1
    image_overlay_type:              none
    default_license:                 CC-BY-NC-ND-4.0
    compression_quality:             90
    full_photo:                      1
    delete_imported:                 1
    Mod_Frame:                       1
    Mod_Frame_refresh:               30
    thumb_2x:                        1
    small_2x:                        1
    medium_2x:                       1
    landing_page_enable:             1
    landing_owner:                   Vincent Juliano
    landing_title:                   Life on 35mm
    landing_subtitle:                Click top right to continue.  Next page top left to login
    landing_facebook:                
    landing_flickr:                  
    landing_twitter:                 
    landing_instagram:               
    landing_youtube:                 
    landing_background:              /uploads/medium/3d4bf4e35e5ea06853d7983c88efb6a2.jpg
    site_title:                      Vince Juliano's Photo Gallery
    site_copyright_enable:           1
    site_copyright_begin:            2021
    site_copyright_end:              2021
    additional_footer_text:          "Alex's Photos" copyright Alex Panicacci 2021
    display_social_in_gallery:       0
    public_search:                   0
    SL_enable:                       0
    SL_for_admin:                    0
    public_recent:                   0
    recent_age:                      30
    public_starred:                  0
    downloadable:                    1
    photos_wraparound:               1
    map_display:                     1
    zip64:                           1
    map_display_public:              1
    map_provider:                    Wikimedia
    force_32bit_ids:                 0
    map_include_subalbums:           1
    update_check_every_days:         3
    has_exiftool:                    1
    share_button_visible:            0
    import_via_symlink:              0
    has_ffmpeg:                      1
    location_decoding:               1
    location_decoding_timeout:       30
    location_show:                   1
    location_show_public:            1
    rss_enable:                      0
    rss_recent_days:                 7
    rss_max_items:                   100
    prefer_available_xmp_metadata:   0
    editor_enabled:                  1
    lossless_optimization:           1
    swipe_tolerance_x:               150
    swipe_tolerance_y:               250
    local_takestamp_video_formats:   .avi|.mov
    log_max_num_line:                1000
    unlock_password_photos_with_url_param: 0
    nsfw_visible:                    0
    nsfw_blur:                       0
    nsfw_warning:                    0
    nsfw_warning_admin:              0
    map_display_direction:           1
    album_subtitle_type:             oldstyle
    upload_processing_limit:         4
    public_photos_hidden:            1
    new_photos_notification:         1
### Browser and system
![Screen Shot 2021-12-24 at 3 55 56 AM](https://user-images.githubusercontent.com/58374187/147350732-7395b8ac-9027-46c6-88f9-e6f81667669a.png)

**Comment by vjuliano** [comment]
Not sure if this is related to #1155

**Comment by nagmat84** [comment]
No, it is not related to issue #1155, see #1179 for an explanation.
Also, this issue is a duplicate of #1179. Under the hood search results and the recent album use the same code. More precisely, the recent album is nothing more than a special search.
