### ISSUE TITLE
Error 500 / sharing:add

### ISSUE THREAD

**Issue by PierreFLC** [LycheeOrg/Lychee#1183]
### Detailed description of the problem [REQUIRED]
*A clear and concise description of what the bug is.*

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. In the Parameteres menu, click on "share"
2. Click on >> to select an album and on >> to select a user
3. Click on "share" at the bootom of the page
4. See error*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*
![Capture d’écran 2021-12-31 à 17 23 00](https://user-images.githubusercontent.com/96919763/147832290-941c9efc-6f73-4b6b-8cb4-b327c8f1144f.png)
### Output of the diagnostics  [REQUIRED]
*(Settings => Diagnostics or https://example.com/Diagnostics or `php artisan lychee:diagnostics`)*
[2112311725-Diagnostics.txt](https://github.com/LycheeOrg/Lychee/files/7796643/2112311725-Diagnostics.txt)

### Browser and system
Firefox Version 95.0 (64 bits) on MacOS X Mojave

**Comment by nagmat84** [comment]
Please provide more information about the failing request, in particular the content of the request and the answer. You get this information when you click on the row with the failing request in your screenshot.

**Comment by PierreFLC** [comment]
![Capture d’écran 2021-12-31 à 17 37 01](https://user-images.githubusercontent.com/96919763/147832630-77d85bab-c825-4edf-9ed9-5104ab0c620b.png)

![Capture d’écran 2021-12-31 à 17 37 14](https://user-images.githubusercontent.com/96919763/147832641-270543b9-c2a5-40c6-b7c4-15981acd3e3d.png)

**Comment by nagmat84** [comment]
The request looks good, nothing wrong there. Do you see anything in your logs?

**Comment by PierreFLC** [comment]
Please help me to find the logs which could be interesting...

**Comment by nagmat84** [comment]
Via the web front-end: On the main page click onto the cog icon (left upper corner), then select "Show Logs".
Via the CLI: Run `./artisan lychee:logs`.

**Comment by PierreFLC** [comment]
![Capture d’écran 2021-12-31 à 17 58 06](https://user-images.githubusercontent.com/96919763/147833237-b92e4cee-babf-4fe3-9086-a62372281a65.png)

**Comment by nagmat84** [comment]
Honestly, I have no idea what is going on there and what causes the strange message `82 - lychee_photos does not exist!` and friends. Maybe some of the other maintainers has an idea.

**Comment by PierreFLC** [comment]
Thank you Matthias for your attention. I hope however that the problem will be fixed. Until then, happy new year!
