### ISSUE TITLE
No image displayed in a public album although the thumbnail is correct

### ISSUE THREAD

**Issue by PierreFLC** [LycheeOrg/Lychee#1184]
### Detailed description of the problem [REQUIRED]
*A clear and concise description of what the bug is.*
![Capture d’écran 2021-12-31 à 17 34 07](https://user-images.githubusercontent.com/96919763/147832729-0e1989ac-6f37-4b6a-91e8-8603564381bb.png)

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Click on album "Les oiseaux..."
2. It should contain one photo tagged as "public"
3. Nothing is displayed

### Output of the diagnostics  [REQUIRED]
*(Settings => Diagnostics or https://example.com/Diagnostics or `php artisan lychee:diagnostics`)*
[2112311725-Diagnostics.txt](https://github.com/LycheeOrg/Lychee/files/7796675/2112311725-Diagnostics.txt)

### Browser and system
Firefox Version 95.0 (64 bits) on MacOS X Mojave

**Comment by nagmat84** [comment]
Does the problem also occur on Lychee 4.5.0? There has been a major refactoring between 4.4.0 and 4.5.0, in particular how the thumbnails and image listings of an album are determined. So there are chances that the problem has been solved.

**Comment by ildyria** [comment]
No reply. I assume the problem is no longer applicable as hard to reproduce.
