### ISSUE TITLE
Notifications missing from Mobile webpage menu

### ISSUE THREAD

**Issue by T-burger** [LycheeOrg/Lychee#1185]
### Detailed description of the problem [REQUIRED]
On the mobile webpage the menu from the top left is missing the entry for notification where users can add their email to receive notifications. Is this intentional?

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Log in on a mobile browser (Tested chrome on Android and Safari on iOS)
2. Click on gear in top left corner
3. Notifications is missing from the list (it is present in desktop version)

**Screenshots**
![Screenshot_20220103-213745](https://user-images.githubusercontent.com/72326039/147921936-d06d7b87-3c43-4be1-8d29-754cc1c9ac42.png)
![ima_5c08026](https://user-images.githubusercontent.com/72326039/147922034-d37e2127-d394-4c68-8af4-c436a736618f.png)

### Output of the diagnostics  [REQUIRED]
System Information
------------------
Lychee Version (git):            No git data found.
DB Version:                      4.3.6

composer install:                --no-dev
APP_ENV:                         production
APP_DEBUG:                       false

System:                          Linux
PHP Version:                     7.4
Max uploaded file size:          2M
Max post size:                   8M
MySQL Version:                   10.6.5-MariaDB-1:10.6.5+maria~focal

Imagick:                         1
Imagick Active:                  1
Imagick Version:                 1691
GD Version:                      2.3.0

### Browser and system
Running the latest docker image from  LycheeOrg /Lychee-Docker, which is on Lychee 4.3.6

Tested mobile and desktop behavior on:
Chrome on Android, Windows and Linux
Firefox on Windows and Linux 
Safari on iOS

**Comment by kamil4** [comment]
Thanks for the report! No, this is not intentional; it's just an oversight.

This bug will be fixed when a large code refactoring in #1055 (and specifically the corresponding front-end changes in https://github.com/LycheeOrg/Lychee-front/pull/271) is merged. Note that the next Lychee release to include the fix will probably be 5.0.

**Comment by kamil4** [comment]
The fix for this bug has just been merged to master; closing.
