### ISSUE TITLE
Missing v4.4.0 tag on Docker Hub

### ISSUE THREAD

**Issue by pichouk** [LycheeOrg/Lychee#1186]
### Detailed description of the problem [REQUIRED]
I can see on Github releases that the version `4.4.0` is available since beginning of December, but the appropriate Docker Hub tags doesn't seems to exists [here](https://hub.docker.com/r/lycheeorg/lychee)

### Steps to reproduce the issue

1. Go to https://hub.docker.com/r/lycheeorg/lychee/tags
2. Search for 4.4.0

**Comment by d7415** [comment]
Wrong place, but yes. It's been delayed due to php8 complications. I'm considering dropping armv6 support to get it published more quickly, but I haven't decided on that yet.
