### ISSUE TITLE
[Enhancement] Multiline descriptions with markdown support for images and albums

### ISSUE THREAD

**Issue by Madoka03** [LycheeOrg/Lychee#1189]
I would be very happy if Lychee would allow multiple lines in descriptions. In the best case additionally the support of Markdown in the description would be perfect.

**Comment by kamil4** [comment]
It looks like our descriptions are already unlimited in length so that's one hurdle out of the way at least...

Do I understand it correctly that what you're missing when you say "multiline" is support for newlines inside a description?

**Comment by Madoka03** [comment]
Yes that you enter the description in a textarea and line breaks are also visible in the view (right in the sidebar).

**Comment by haivala** [comment]
It would be nice to have this kind of description optionally between the header and album pictures so that the user would see more info about the pics than just name of the album. same goes with picture descriptions.
 
What do you think?

**Comment by ildyria** [comment]
> It would be nice to have this kind of description optionally between the header and album pictures so that the user would see more info about the pics than just name of the album. same goes with picture descriptions.
> 
> What do you think?

I already had that in mind with a Hero content once I finish rewritting the front-end (soon TM)

**Comment by kamil4** [comment]
@haivala The photo descriptions you can actually already optionally see in the overlay (if you are unfamiliar, use "o" to cycle through them). We definitely should have something similar for albums though, as you said.

**Comment by haivala** [comment]
> @haivala The photo descriptions you can actually already optionally see in the overlay (if you are unfamiliar, use "o" to cycle through them). We definitely should have something similar for albums though, as you said.

Problem is that it is not that obvious for first time user. I'm mainly thinking situation where I share album to someone who has never seen the album and lychee before. If album would have the introduction text I would not need to rewrite it into the sharing message for everyone who I share the album with.

**Comment by kamil4** [comment]
FYI, I'm working on this. I have multi-line descriptions working, but I still need to do something about displaying album descriptions...

**Comment by haivala** [comment]
Thank you!

**Comment by kamil4** [comment]
Draft implementation is ready! If you feel like experimenting... (it will require having the current bleeding-edge Lychee already running, and switching to experimental branches)

**Comment by Madoka03** [comment]
Thank you, the screenshots in the merge request looks very promising. I look forward to the update that brings this feature.
