### ISSUE TITLE
Where edit and replace default "site-title" and "copy-right" with personal info?

### ISSUE THREAD

**Issue by Cybertel777** [LycheeOrg/Lychee#1191]
I like your Lychee Gallery a lot. It might be the most advanced, beautiful and easy to use in the world. 
:)

It took some seconds to install it with the softaculous automatic script installer on my hosting server. But I spend nearly 1 hour trying to find the right css file? where I might be able to change the default "John Smith" owner with my personal information and could still not find it. :-(

**Please can you tell me how to achieve this?**

And why not add an option to the admin settings to make it easier?

Thanks in advance for your response

**Comment by d7415** [comment]
It is in the admin settings, under "More", "Mod Welcome", "landing_owner".  It could be exposed more clearly.

**Comment by Cybertel777** [comment]
So, it's already in the admin settings. That's amazing. Thanks a lot and again bravo for your application. :-)

**Comment by LouisVallat** [comment]
Closing due to being solved.
Although the settings page could maybe see a redesign to make it clearer (or add in docs if not already).
