### ISSUE TITLE
[Enhancement] Any plans on dealing with big albums / big imports?

### ISSUE THREAD

**Issue by kuzyn** [LycheeOrg/Lychee#1193]
Hi :)

Is there any plans on adding paging to big albums (or any other mechanism) so that all items aren't front loaded as they are now?
Alternatively, a functionality to break an album into multiple albums (i.e. using exif data) would be useful too.

Use case is importing a lot of photos (10k+) from a single folder and being unable to easily view them.

**Comment by ildyria** [comment]
> Use case is importing a lot of photos (10k+) from a single folder and being unable to easily view them.

Just don't...

**Comment by kuzyn** [comment]
Super constructive, thanks!

**Comment by ildyria** [comment]
@kuzyn to answer your question, yes, pagination is planned in the future... when I have time rewrite the front-end (which is significantly more urgent).

But your use-case of importing 10k+ pictures is not something that Lychee can handle sorry. My Lychee library has 40 k pictures total. What you can do however is split your imports into sub folders and hen import the root, that's something lychee can handle.

**Comment by kamil4** [comment]
Yeah, it's really the web browser itself that's struggling big time when the front end asks it to render 10,000+ pictures (the images themselves are loaded lazily; however, I believe that laying them out on the page is what's killing the performance). The Lychee server can mostly deal with such numbers (if you configure your PHP with enough memory). My rule-of-the-thumb is 1,000 photos per album -- that works pretty smoothly. More than that and the problems start...

**Comment by kuzyn** [comment]
That's good to know. Splitting collections into small dirs before uploading
is an acceptable stopgap (obviously the annoying thing is to reupload
thousands of items just to map the folder layout).

And it does look like the img containers are layed out before the img is
actually requested. Wonder if things would be different with a
"display:none".

**Comment by ildyria** [comment]
If you make your album layout at the folder level, Lychee will import the pictures following this structure.
