### ISSUE TITLE
Lychee behind nginx reverse proxy doesn't detect correct remote address

### ISSUE THREAD

**Issue by drtech981** [LycheeOrg/Lychee#1197]
I have Lychee on Docker hosted behind an NGINX reverse proxy, and while logging in, in the logs section, it shows login from '172.24.0.1', which is in fact the local address of the reverse proxy : 
`App\ModelFunctions\SessionFunctions::log_as_admin -- 179 -- User (admin) has logged in from 172.24.0.1`

Setting these headers doesn't help either : 

`proxy_set_header X-Forwarded-For $remote_addr;`

`proxy_set_header REMOTE_ADDR $remote_addr;`

**Comment by ildyria** [comment]
https://github.com/LycheeOrg/Lychee/blob/376f8c7c9c463816252319dcbdab2975d221ed8a/app/Http/Middleware/TrustProxies.php#L15-L24
See if you can add your proxy ip in this file if it helps.

**Comment by drtech981** [comment]
Thanks @ildyria it is now working !!

**Comment by drtech981** [comment]
@ildyria Would be great if a docker environment variable is introduced for Trusted_Proxies since presently each time the container is updated, a manual re-edit of [TrustProxies.php](https://github.com/LycheeOrg/Lychee/blob/376f8c7c9c463816252319dcbdab2975d221ed8a/app/Http/Middleware/TrustProxies.php#L15-L24) is needed.

**Comment by ildyria** [comment]
I think a different & better approach would be to add those as a setting in `.env` :)
