### ISSUE TITLE
Shared albums: policy

### ISSUE THREAD

**Issue by ildyria** [LycheeOrg/Lychee#12]
If an album is shared, do we want to automatically apply it to the children ?
Or is this something that we only do in the sharing panel (click on parent also move children) ?

**Comment by ma-tt** [comment]
Yes.

Let's say I create a folder called "photos of bob" and inside that album I have two sub albums called "bob at the beach" and "bob at home". Now, I share the parent album called "photos of bob" and view that link. Currently I get a blank page. Absolutely nothing.

Surely, the default behavior would be to see the content of the folder that was just shared. If people want more options, customization, or to be asked each time, that is all awesome and welcomed. Everyone loves options. But the current way it works is not at all desirable or intuitive.

**Comment by kamil4** [comment]
I agree with you that the current behavior is a poor _default_. At the very least, in the scenario you outlined we should be asking the user whether to apply the change to the subalbums as well...

**Comment by matthijskooijman** [comment]
I believe this issue is the same as #1411, but that one has more relevant discussion, so I would suggest closing this issue in favor of that one.
