### ISSUE TITLE
Unable to move most photos, Uncaught TypeError: _photo.json.album is undefined

### ISSUE THREAD

**Issue by vjuliano** [LycheeOrg/Lychee#1204]
### Detailed description of the problem [REQUIRED]
For most photos, I am unable to move them from one album to another.  Hitting the folder icon does nothing.  Looking at console, I see error  Uncaught TypeError: _photo.json.album is undefined.  This seems to be happening for photos that are 'Unsorted' as well.  It does not seem to be for 100% of photos, as I have been able to find a few that do work as expected.  Date uploaded does not seem to be relevant. 
 I am happy to provide any info from database.  I am unclear on how the relational modeling works since the recent db refactor.
I have cleared cache etc with no improvement.

Full error:
Uncaught TypeError: _photo.json.album is undefined
    addItems https://192.168.0.200/dist/main.js?1642560772:3034
    move https://192.168.0.200/dist/main.js?1642560772:3044
    success https://192.168.0.200/dist/main.js?1642560772:435
    c https://192.168.0.200/dist/main.js?1642560772:2
    fireWith https://192.168.0.200/dist/main.js?1642560772:2
    l https://192.168.0.200/dist/main.js?1642560772:2
    o https://192.168.0.200/dist/main.js?1642560772:2
    send https://192.168.0.200/dist/main.js?1642560772:2
    ajax https://192.168.0.200/dist/main.js?1642560772:2
    post https://192.168.0.200/dist/main.js?1642560772:463
    move https://192.168.0.200/dist/main.js?1642560772:3010
    bind https://192.168.0.200/dist/main.js?1642560772:3258
    dispatch https://192.168.0.200/dist/main.js?1642560772:2
    handle https://192.168.0.200/dist/main.js?1642560772:2
main.js:3034:5

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Go to almost any album
2. Click on almost any photo
3. Click on folder icon for 'move'
4. Nothing apparently will happen.  List of albums to move to does not load.  In console you will see error.

### Output of the diagnostics  [REQUIRED]
Diagnostics
    -------
    Warning: Dropbox import not working. dropbox_key is empty.

    System Information
    --------------
    Lychee Version (git):            master (49fd769) - Data not in Cache
    DB Version:                      4.5.0
    
    composer install:                dev
    APP_ENV:                         production
    APP_DEBUG:                       true
    
    System:                          Linux
    PHP Version:                     8.1
    PHP User agent:                  Lychee/4 (https://lycheeorg.github.io/)
    Max uploaded file size:          500M
    Max post size:                   500M
    Max execution time:              200
    MySQL Version:                   10.5.13-MariaDB-0ubuntu0.21.10.1
    
    Imagick:                         1
    Imagick Active:                  1
    Imagick Version:                 1691
    GD Version:                      2.3.0

    Config Information
    --------------
    version:                         040500
    check_for_updates:               1
    sorting_Photos_col:              created_at
    sorting_Photos_order:            DESC
    sorting_Albums_col:              max_taken_at
    sorting_Albums_order:            DESC
    imagick:                         1
    skip_duplicates:                 1
    small_max_width:                 0
    small_max_height:                360
    medium_max_width:                1920
    medium_max_height:               1080
    lang:                            en
    layout:                          1
    image_overlay_type:              none
    default_license:                 CC-BY-NC-ND-4.0
    compression_quality:             90
    full_photo:                      1
    delete_imported:                 1
    Mod_Frame:                       1
    Mod_Frame_refresh:               30
    thumb_2x:                        1
    small_2x:                        1
    medium_2x:                       1
    landing_page_enable:             1
    landing_owner:                   me
    landing_title:                   Life on 35mm
    landing_subtitle:                Click top right to continue.  Next page top left to login
    landing_facebook:                
    landing_flickr:                  
    landing_twitter:                 
    landing_instagram:               
    landing_youtube:                 
    landing_background:              /uploads/medium/3d4bf4e35e5ea06853d7983c88efb6a2.jpg
    site_title:                      Photo Gallery
    site_copyright_enable:           1
    site_copyright_begin:            2021
    site_copyright_end:              2022
    additional_footer_text:          "Alex's Photos" copyright 2022
    display_social_in_gallery:       0
    public_search:                   0
    SL_enable:                       0
    SL_for_admin:                    0
    public_recent:                   0
    recent_age:                      60
    public_starred:                  0
    downloadable:                    1
    photos_wraparound:               1
    map_display:                     1
    zip64:                           1
    map_display_public:              1
    map_provider:                    Wikimedia
    force_32bit_ids:                 0
    map_include_subalbums:           1
    update_check_every_days:         3
    has_exiftool:                    1
    share_button_visible:            0
    import_via_symlink:              0
    has_ffmpeg:                      1
    location_decoding:               1
    location_decoding_timeout:       30
    location_show:                   1
    location_show_public:            1
    rss_enable:                      0
    rss_recent_days:                 7
    rss_max_items:                   100
    prefer_available_xmp_metadata:   0
    editor_enabled:                  112.1
    lossless_optimization:           1
    swipe_tolerance_x:               150
    swipe_tolerance_y:               250
    local_takestamp_video_formats:   .avi|.mov
    log_max_num_line:                1000
    unlock_password_photos_with_url_param: 0
    nsfw_visible:                    0
    nsfw_blur:                       0
    nsfw_warning:                    0
    nsfw_warning_admin:              0
    map_display_direction:           1
    album_subtitle_type:             oldstyle
    upload_processing_limit:         4
    public_photos_hidden:            1
    new_photos_notification:         1
    legacy_id_redirection:           1

### Browser and system
Server: Unbuntu 21.10.  Client: Mac OS 12.1  Firefox 96.0.2

**Comment by kamil4** [comment]
Thanks for the report! I'm not sure how I missed it since I thought I did test moving extensively recently. Anyway, the fix is pending...

**Comment by kamil4** [comment]
BTW, as a workaround, until the fix is merged, you can use the `Move` available in the context menu in the album view when you right-click on a photo.

**Comment by nagmat84** [comment]
@kamil4 Did you understand how to reproduce the problem? Using the context menu is the only way I am aware of and that works for me. I did not know that there is apparently a second, currently broken way to move photos.

If I knew what the problem is, I might be able to implement a fix.

**Comment by kamil4** [comment]
Yeah, I normally use the context menu as well as it's more convenient for casual browsing. But you can also do it in photo view, using the `Move` (folder) icon from the header. And that's broken. Anyway, I already submitted the fix...
