### ISSUE TITLE
Another timezone issue

### ISSUE THREAD

**Issue by MikeTheTux** [LycheeOrg/Lychee#1206]
I'm running Lychee 4.4.0 using the official docker:

`PHP_TZ=Europe/Berlin`
```
root@lychee:/var/www/html/Lychee# cat /etc/timezone                                                                        
Europe/Berlin                                                                                                              
root@lychee:/var/www/html/Lychee# date                                                                                     
Sun Jan 30 11:25:56 CET 2022    
```                                                                                           

Lychee is configured to use MariaDB.
MariaDB 10.6 runs on the same server, but using UTC .
I read this as recommended setting here: [UTCBasedTimes.php](https://github.com/LycheeOrg/Lychee/blob/32c374db4505bb44bf5b357ee952034ad271515c/app/Models/Extensions/UTCBasedTimes.php)

`TZ=UTC`
```
root@mariadb:/# cat /etc/timezone                                                                                          
Etc/UTC                                                                                                                    
root@mariadb:/# date                                                                                                       
Sun Jan 30 10:29:35 UTC 2022
```

My browser is running on Win10, also in CET timezone.

I use to have photos from my mobile-phone and my digi-cam in the same album.

- The mobile cam adds the timezone info to the photo. 
- The digi-cam doesn't add timezone info to the photo.

Both photos are pre-processed via Adobe Lightroom.
Lightroom is doing a good job in adding missing timezone info. Therefore it is using the computer timezone, when the picture doesn't provide any info.
Left you can see the timing related info from the mobile (with TZ info). Right picture is from the digi-cam (witout TZ info) - both after the Lightroom pre-processing:
![grafik](https://user-images.githubusercontent.com/44850211/151698955-52afd6a8-2d07-4aba-97cb-06a887085242.png)
The main differences are highlighted.

When importing the pictures in Lychee:
- The mobile photo shows the correct timezone as `UCT+01:00` in the lychee meta data info (and database).
- For the digi-cam photo I would expect that Lychee takes over the timezone from one of the fields added by Lightroom or that it uses as fallback the timezone of the server when reading the orginal attribute without timezone info. Both should result to `UCT+01:00`. Nevertheless it shows up as `UTC` in the lychee meta data info (and database).

This creates and issue when sorting the pictures according to the `taken date`. An offset of 1 hour is added between the different cam types.

Is my setup right? Recommended timezone config of Lychee as well as MariaDB?
Is my expectation right? If no timezone info is present in the picture, Lychee server time zone should be used during the upload instead of UTC?

**Screenshots**
![grafik](https://user-images.githubusercontent.com/44850211/151699091-93a26893-95dc-4890-a86f-06269ae44423.png)
You can see the wrong order (`8:49` should come after `8:21`) caused by the wrong timezone info `UTC`.

### Output of the diagnostics  [REQUIRED]
```
    Diagnostics
    -------
    Warning: Dropbox import not working. dropbox_key is empty.




    System Information
    --------------
    Lychee Version (git):            No git data found.
    DB Version:                      4.4.0
    
    composer install:                --no-dev
    APP_ENV:                         production
    APP_DEBUG:                       false
    
    System:                          Linux
    PHP Version:                     8.1
    PHP User agent:                  Lychee/4 (https://lycheeorg.github.io/)
    Max uploaded file size:          100M
    Max post size:                   100M
    Max execution time:              3600
    MySQL Version:                   10.6.4-MariaDB-1:10.6.4+maria~focal
    
    Imagick:                         1
    Imagick Active:                  1
    Imagick Version:                 1691
    GD Version:                      2.3.0




    Config Information
    --------------
    version:                         040400
    check_for_updates:               0
    sorting_Photos_col:              taken_at
    sorting_Photos_order:            ASC
    sorting_Albums_col:              title
    sorting_Albums_order:            DESC
    imagick:                         1
    skip_duplicates:                 0
    small_max_width:                 0
    small_max_height:                360
    medium_max_width:                1920
    medium_max_height:               1080
    lang:                            en
    layout:                          1
    image_overlay_type:              date
    default_license:                 CC-BY-NC-ND-4.0
    compression_quality:             90
    full_photo:                      1
    delete_imported:                 0
    Mod_Frame:                       1
    Mod_Frame_refresh:               30
    thumb_2x:                        1
    small_2x:                        1
    medium_2x:                       1
    landing_page_enable:             1
    landing_owner:                   xxx
    landing_title:                   xxx
    landing_subtitle:                public albums
    landing_facebook:                xxx
    landing_flickr:                  
    landing_twitter:                 
    landing_instagram:               xxx
    landing_youtube:                 xxx
    landing_background:              dist/bg.jpg
    site_title:                      public albums
    site_copyright_enable:           1
    site_copyright_begin:            2009
    site_copyright_end:              2022
    additional_footer_text:          
    display_social_in_gallery:       1
    public_search:                   0
    SL_enable:                       0
    SL_for_admin:                    0
    public_recent:                   0
    recent_age:                      1
    public_starred:                  0
    downloadable:                    0
    photos_wraparound:               1
    map_display:                     0
    zip64:                           1
    map_display_public:              0
    map_provider:                    Wikimedia
    force_32bit_ids:                 0
    map_include_subalbums:           0
    update_check_every_days:         3
    has_exiftool:                    1
    share_button_visible:            0
    import_via_symlink:              0
    has_ffmpeg:                      1
    location_decoding:               0
    location_decoding_timeout:       30
    location_show:                   1
    location_show_public:            0
    rss_enable:                      0
    rss_recent_days:                 7
    rss_max_items:                   100
    prefer_available_xmp_metadata:   0
    editor_enabled:                  1
    lossless_optimization:           0
    swipe_tolerance_x:               150
    swipe_tolerance_y:               250
    local_takestamp_video_formats:   .avi|.mov
    log_max_num_line:                1000
    unlock_password_photos_with_url_param: 0
    nsfw_visible:                    1
    nsfw_blur:                       0
    nsfw_warning:                    0
    nsfw_warning_admin:              0
    map_display_direction:           1
    album_subtitle_type:             oldstyle
    upload_processing_limit:         4
    public_photos_hidden:            1
    new_photos_notification:         0
```

### Browser and system
Win10
Firefox Browser
Using CET timezone (UCT+01:00)

**Comment by MikeTheTux** [comment]
The usage of `Date Created` in [Extractor.php](https://github.com/LycheeOrg/Lychee/blob/master/app/Metadata/Extractor.php) explains, why the timezone info added by Lightroom is not conidered:

`$taken_at = $exif->getCreationDate();`

According to the meta data above, this is the only value where the timezone info is missing.

**Comment by nagmat84** [comment]
> Lychee is configured to use mariadb. MariaDB 10.6 runs on the same server, but using UTC . I read this as recommend setting here: [UTCBasedTimes.php](https://github.com/LycheeOrg/Lychee/blob/32c374db4505bb44bf5b357ee952034ad271515c/app/Models/Extensions/UTCBasedTimes.php)
> 
> ```
> root@mariadb:/# cat /etc/timezone                                                                                          
> Etc/UTC                                                                                                                    
> root@mariadb:/# date                                                                                                       
> Sun Jan 30 10:29:35 UTC 2022
> ```

That should be fine, but should not matter. It should also work exactly the same way, if your DB server would run in any other timezone.

The settings in `./config/database.php` are crucial. Can you confirm that the configuration key `connections.mysql.timezone` equals `+00:00`? The only important point is that the PHP code of Lychee and the DB abstraction layer have the same mutual understanding how times shall be interpreted.

> I use to have photos from my mobile-phone and my digi-cam in the same album.
> 
>     * The mobile cam adds the timezone info to the photo. It is shown as `UCT+01:00 ` in the lychee meta data info (and database).
> 
>     * The digi-cam doesn't add timezone info to the photo. I would expect that per default the timezone of the server is used in that case = CET / UTC+1. Nevertheless it shows up as `UTC` in the lychee meta data info (and database).

Could you provide the original example photos? I downloaded your example but it was a processed collage without any EXIF data. Having the original photos might help to reproduce and investigate the problem.

> This creates and issue when sorting the pictures according to the `taken date`. An offset of 1 hour is added between the different cam types.

Sorting should always use the calculated UTC time, i.e. photos should be sorting according to the instant they were taken on the universe timeline. "08:49:11 UTC+01:00" equals "07:49:11 UTC" which is earlier than "08:21:10 UTC". If you sort your photos according to descending time (latest photos first), then "2022-01-07 08:21:10 UTC"  should be positioned before "2022-01-07 08:49:11 UTC+01:00" , because the latter is actually older.

Can you confirm that this happens?

> Is my setup right? Recommended timezone config of Lychee as well as MariaDB? Is my expectation right? 

Yes.

> If no timezone info is present in the picture, Lychee server time zone should be used during the upload instead of UTC?

In most cases yes. If an explicit timezone indication is missing, then the EXIF extractor actually tries something more clever. For certain camera types and smartphone models (Apple) it falls back to UTC, because the EXIF extractor knows that these models always store UTC times. For any other model the EXIF extractor assumes the local time zone, if an explicit indication is missing.

**Comment by MikeTheTux** [comment]
> The settings in ./config/database.php are crucial. Can you confirm that the configuration key connections.mysql.timezone equals +00:00?

`cat database.php`
```
        'connections' => [
                'sqlite' => [
                        'driver' => 'sqlite',
                        'url' => env('DATABASE_URL'),
                        'database' => env('DB_DATABASE', database_path('database.sqlite')),
                        'prefix' => '',
                        'foreign_key_constraints' => env('DB_FOREIGN_KEYS', true),
                ],

                'mysql' => [
                        'driver' => 'mysql',
                        'url' => env('DATABASE_URL'),
                        'host' => env('DB_HOST', '127.0.0.1'),
                        'port' => env('DB_PORT', '3306'),
                        'database' => env('DB_DATABASE', 'forge'),
                        'username' => env('DB_USERNAME', 'forge'),
                        'password' => env('DB_PASSWORD', ''),
                        'unix_socket' => env('DB_SOCKET', ''),
                        'charset' => 'utf8mb4',
                        'collation' => 'utf8mb4_unicode_ci',
                        // The timezone of the DB connection should always be set in order
                        // to ensure that the PHP application and the DB server have a
                        // mutual understanding how SQL datetime strings without an
                        // explicit timezone indication such as `YYYY-MM-DD hh:mm:ss`
                        // shall be interpreted.
                        // The setting here must not be changed and must match the
                        // assumption in \App\Models\PatchedBaseModel.
                        'timezone' => '+00:00',
                        'prefix' => '',
                        'prefix_indexes' => true,
                        'strict' => true,
                        'engine' => 'InnoDB ROW_FORMAT=DYNAMIC',
                        'options' => extension_loaded('pdo_mysql') ? array_filter([
                                PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
                        ]) : [],
                ],
```

**Comment by MikeTheTux** [comment]
> Could you provide the original example photos? I downloaded your example but it was a processed collage without any EXIF data. Having the original photos might help to reproduce and investigate the problem.

In this [Dropbox](https://www.dropbox.com/sh/3dah4qc3p5zee53/AABltSDuhtN3K2bbPpayrTm2a?dl=0) you can find the pictures of my example (not the originals, but the result from my Lightroom workflow)

**Comment by nagmat84** [comment]
> In this [Dropbox](https://www.dropbox.com/sh/3dah4qc3p5zee53/AABltSDuhtN3K2bbPpayrTm2a?dl=0) you can find the pictures of my example (not the originals, but the result from my Lightroom workflow)

Thank you. I have downloaded them and I will try to reproduce the problem later this day.

**Comment by MikeTheTux** [comment]
> Sorting should always use the calculated UTC time, i.e. photos should be sorting according to the instant they were taken on the universe timeline. "08:49:11 UTC+01:00" equals "07:49:11 UTC" which is earlier than "08:21:10 UTC". If you sort your photos according to descending time (latest photos first), then "2022-01-07 08:21:10 UTC" should be positioned before "2022-01-07 08:49:11 UTC+01:00" , because the latter is actually older.

This is right. According to the current meta info in the DB, the sorting duing the view is done right. The problem is during the import - both should have been UTC+01:00.

**Comment by MikeTheTux** [comment]
> If you sort your photos according to descending time (latest photos first), then "2022-01-07 08:21:10 UTC" should be positioned before "2022-01-07 08:49:11 UTC+01:00" , because the latter is actually older.
> 
> Can you confirm that this happens?

Yes, if I switch to sorting order to descending time, the order changes. 8:21 before 8:49.
![grafik](https://user-images.githubusercontent.com/44850211/151700871-32da2aaf-a5a5-490b-88f1-58bad5224364.png)

**Comment by MikeTheTux** [comment]
another test on the Lychee server:

```
root@lychee:/var/www/html/Lychee# php -r 'echo date_default_timezone_get();'
Europe/Berlin
```

**Comment by nagmat84** [comment]
I tried the photos your provided and unfortunately cannot reproduce the problem. The only difference is that I don't use docker.

## `timezone issue - takenat0849CET withTZ.jpg`

### Exiftool output from CLI

    $> exiftool timezone\ issue\ -\ takenat0849CET\ withTZ.jpg 
    ExifTool Version Number         : 12.30
    Exif Version                    : 0231
    Make                            : samsung
    Camera Model Name               : SM-G970F
    Date/Time Original              : 2022:01:07 08:49:11
    Create Date                     : 2022:01:07 08:49:11
    Offset Time                     : +01:00
    Offset Time Original            : +01:00
    Time Created                    : 08:49:11+01:00
    Digital Creation Date           : 2022:01:07
    Digital Creation Time           : 08:49:11+01:00
    Date Created                    : 2022:01:07 08:49:11+01:00

### Step debugging

 1. **Extraction from file**
    
    ![01](https://user-images.githubusercontent.com/7428426/151707219-696e3d14-4c4a-4df7-ac02-916485559166.png)
    
    ![02](https://user-images.githubusercontent.com/7428426/151707225-5d69be6f-b4d9-4676-92bf-da5e8392244e.png)
    
    _Result:_ The datetime is correctly extracted as `2022-01-07 08:49:11` in timezone `+01:00`.
    
 2. **Conversion to SQL representation**
    
    ![03](https://user-images.githubusercontent.com/7428426/151707332-68084d92-d415-496a-aaff-4b427c742045.png)
    
    _Result_: The SQL strings passed to the DB layer are `2022-01-07 07:49:11.000000` (UTC) and original timezone `+01:00`.
    
### SQL result

    MariaDB [lychee]> select id,title,taken_at,taken_at_orig_tz from photos;
    +--------------------------+----------------------------------------+----------------------------+------------------+
    | id                       | title                                  | taken_at                   | taken_at_orig_tz |
    +--------------------------+----------------------------------------+----------------------------+------------------+
    | 72iE56aCdpCuuQ1y4a4RHEKQ | timezone issue - takenat0849CET withTZ | 2022-01-07 07:49:11.000000 | +01:00           |
    +--------------------------+----------------------------------------+----------------------------+------------------+

### Frontend

![07](https://user-images.githubusercontent.com/7428426/151707464-c039c650-cb23-4386-a81c-9e95129cc997.png)

_Result:_ Correctly shown as "07.01.2022, 08:49:11 UTC+01:00".

## `timezone issue - takenat0821CET withoutTZ.jpg`

### Exiftool output from CLI

    $> exiftool timezone\ issue\ -\ takenat0821CET\ withoutTZ.jpg 
    ExifTool Version Number         : 12.30
    Exif Version                    : 0231
    Make                            : SONY
    Camera Model Name               : DSC-RX100M3
    Date/Time Original              : 2022:01:07 08:21:10
    Create Date                     : 2022:01:07 08:21:10
    Offset Time                     : +01:00
    Time Created                    : 08:21:10+01:00
    Digital Creation Date           : 2022:01:07
    Digital Creation Time           : 08:21:10+01:00
    Date/Time Created               : 2022:01:07 08:21:10+01:00
    Digital Creation Date/Time      : 2022:01:07 08:21:10+01:00

### Step debugging

 1. **Extraction from file**
    
    ![04](https://user-images.githubusercontent.com/7428426/151707552-f18b9ce2-cab1-41d7-909d-dd9175e89e66.png)

    _Result:_ The datetime is correctly extracted as `2022-01-07 08:21:10` in timezone `Europe/Berlin`. Note, the difference to the first photo. As the photo did not contain an explicit timezone, the extractor used the timezone of the PHP process which is a _named_ timezone, hence it is `Europe/Berlin` and not just `+01:00`. This is expected behavior!
    
 2. **Conversion to SQL representation**
    
    ![05](https://user-images.githubusercontent.com/7428426/151707683-2d52322a-5da7-4c54-bf00-773932089cbb.png)
    
    _Result_: The SQL strings passed to the DB layer are `2022-01-07 07:21:10.000000` (UTC) and original timezone `Europe/Berlin`.
    
### SQL result


    MariaDB [lychee]> select id,title,taken_at,taken_at_orig_tz from photos;
    +--------------------------+-------------------------------------------+----------------------------+------------------+
    | id                       | title                                     | taken_at                   | taken_at_orig_tz |
    +--------------------------+-------------------------------------------+----------------------------+------------------+
    | CY1kWxwT6foGBpsZk08XIQxA | timezone issue - takenat0821CET withoutTZ | 2022-01-07 07:21:10.000000 | Europe/Berlin    |
    +--------------------------+-------------------------------------------+----------------------------+------------------+

Again note that in this case a _named_ timezone is stored for a photo without any timezone indication, because this is the timezone of the PHP process.

### Frontend

![06](https://user-images.githubusercontent.com/7428426/151707436-22a4a45f-ddde-432b-94fa-7f01e8285445.png)

_Result:_ Correctly shown as "07.01.2022, 08:21:10 UTC+01:00".

**Comment by nagmat84** [comment]
@MikeTheTux Can you confirm that your SQL database looks like that after import of both photos?

    MariaDB [lychee]> select id,title,taken_at,taken_at_orig_tz from photos;
    +--------------------------+-------------------------------------------+----------------------------+------------------+
    | id                       | title                                     | taken_at                   | taken_at_orig_tz |
    +--------------------------+-------------------------------------------+----------------------------+------------------+
    | 72iE56aCdpCuuQ1y4a4RHEKQ | timezone issue - takenat0849CET withTZ    | 2022-01-07 07:49:11.000000 | +01:00           |
    | CY1kWxwT6foGBpsZk08XIQxA | timezone issue - takenat0821CET withoutTZ | 2022-01-07 07:21:10.000000 | Europe/Berlin    |
    +--------------------------+-------------------------------------------+----------------------------+------------------+

**Comment by MikeTheTux** [comment]
no, it does not :-|

```
| id             | title                                     | taken_at            | taken_at_orig_tz      |
------------------------------------------------------------------------------------------------------------
| 16435479401016 | timezone issue - takenat0821CET withoutTZ | 2022-01-07 08:21:10 | UTC                   |
| 16435479401194 | timezone issue - takenat0849CET withTZ    | 2022-01-07 07:49:11 | +01:00                |
```

08:21@UTC is the problem

**Comment by MikeTheTux** [comment]
```
root@lychee:/var/www/html/Lychee/config# exiftool /uploads/timezone\ issue\ -\ takenat0821CET\ withoutTZ.jpg  | grep Date
File Modification Date/Time     : 2022:01:30 12:09:29+01:00
File Access Date/Time           : 2022:01:30 14:38:02+01:00
File Inode Change Date/Time     : 2022:01:30 14:37:38+01:00
Modify Date                     : 2022:01:30 12:09:27
Date/Time Original              : 2022:01:07 08:21:10
Create Date                     : 2022:01:07 08:21:10
Digital Creation Date           : 2022:01:07
Date Created                    : 2022:01:07 08:21:10
Metadata Date                   : 2022:01:30 12:09:27+01:00
Profile Date Time               : 1998:02:09 06:49:00
Modify Date                     : 2022:01:30 12:09:27+01:00
Date/Time Created               : 2022:01:07 08:21:10+01:00
Digital Creation Date/Time      : 2022:01:07 08:21:10+01:00

```

**Comment by nagmat84** [comment]
> no, it does not :-|
> 
> ```
> | id             | title                                     | taken_at            | taken_at_orig_tz      |
> ------------------------------------------------------------------------------------------------------------
> | 16435479401016 | timezone issue - takenat0821CET withoutTZ | 2022-01-07 08:21:10 | UTC                   |
> | 16435479401194 | timezone issue - takenat0849CET withTZ    | 2022-01-07 07:49:11 | +01:00                |
> ```
> 

OK, but this indicates that your PHP script uses UTC as its timezone at least if it is invoked by the web-server. Note that running `# php -r 'echo date_default_timezone_get();'` from the CLI might not tell you the truth, because PHP if invoked from the CLI might use a different configuration than the PHP process of the web-server. In `/etc/php` there are typically at least three different PHP configurations: for CLI, for the apache module and for PHP FPM.

I guess we should at the timezone information to the diagnostic output.

**Comment by MikeTheTux** [comment]
In which file I could add a `echo date_default_timezone_get();` in order to validate the TimeZone used by the PHP webserver instance?

**Comment by nagmat84** [comment]
I just pushed a fix which adds the timezone information to the diagnostic output. As you are using docker and thus you won't get the latest fixes soon, you could patch your Lychee installation manually. At https://github.com/LycheeOrg/Lychee/pull/1207/files you can see what needs to be changed.

Basically, throw the new file `app/Actions/Diagnostics/Checks/TimezoneCheck.php` into the right place and edit `app/Actions/Diagnostics/Info.php` accordingly (two lines need to added).

**Comment by MikeTheTux** [comment]
Arrrr ...

`Timezone:                        UTC`

The Lyche code is right, the PHP environment provided by the docker is wrong.
This issue should now be moved into the Lychee Docker project ...

**Comment by MikeTheTux** [comment]
I'm wondering why "Europe/Berlin" is pushed to `/etc/php/8.1/cli/php.ini` and not `/etc/php/8.1/fpm/php.ini`.
Changed `/etc/php/8.1/cli/php.ini`, but it didn't made a difference ...

**Comment by MikeTheTux** [comment]
I modified now `/var/www/html/Lychee/.env` and restarted the container. Now it's working.

```
Timezone:                        Europe/Berlin
```

I've no idea who is reading this file.
Shall I creat a ticket in the Docker project in order to fix the bug there?
I'm happy with my workaround.
Thanks allot for your help!

**Comment by nagmat84** [comment]
What is your server setup?

| Setup                            | PHP config file                |
|:---------------------------------|:-------------------------------|
| Apache with `mod_php`            | `/etc/php/8.1/apache2/php.ini` |
| Apache with PHP FPM              | `/etc/php/8.1/fpm/php.ini`     |
| Nginx with PHP FPM               | `/etc/php/8.1/fpm/php.ini`     |
| Apache with PHP CGI (deprecated) | `/etc/php/8.1/cgi/php.ini`     |
| Nginx with PHP CGI (deprecated)  | `/etc/php/8.1/cgi/php.ini`     |

Note, the config file `/etc/php/8.1/cli/php.ini` (cli = command line interface) is unimportant here. Also note, that you need to restart your web-server (for Apache with mod_php or the CGI cases) or restart the PHP FPM manager to make the changed configuration effective.

**Comment by nagmat84** [comment]
> Shall I create a ticket in the Docker project in order to fix the bug there?

Yes, please!

**Comment by MikeTheTux** [comment]
> What is your server setup?

The one from [Lychee-Docker](https://github.com/LycheeOrg/Lychee-Docker) ;-) . I guess it is _Nginx with PHP FPM_.

> Note, the config file /etc/php/8.1/cli/php.ini (cli = command line interface) is unimportant here.

This is also my understanding and made me suspicious when seeing this in [inject.sh](https://github.com/LycheeOrg/Lychee-Docker/blob/master/inject.sh):

```
if [ "$PHP_TZ" != '' ]; then
    sed -i "s|;*date.timezone =.*|date.timezone = ${PHP_TZ}|i" /etc/php/8.1/cli/php.ini
fi
```
That's the reason why `root@lychee:/var/www/html/Lychee# php -r 'echo date_default_timezone_get();'` reported the right TZ.

> Also note, that you need to restart your web-server (for Apache with mod_php or the CGI cases) or restart the PHP FPM manager to make the changed configuration effective.

In order to be sure I restarted the entire container

**Comment by MikeTheTux** [comment]
I have now 33k of photos in my database with wrong timestamp information :-(

@nagmat84 Is there a way (e.g. a `php artisan lychee:xxx` command) I can use to trigger Lychee to re-calculate the timestamps? The originals are no longer available but the right info is still in `./uploads/big/*`.

**Comment by ildyria** [comment]
@MikeTheTux how about that one:
https://github.com/LycheeOrg/Lychee/blob/master/app/Console/Commands/Takedate.php

EDIT: the script is likely broken as is as there is no longer an attribute takestamp: 
https://github.com/LycheeOrg/Lychee/blob/master/app/Console/Commands/Takedate.php#L71-L72

Please open an issue about that one. :)

**Comment by nagmat84** [comment]
Right, unfortunately the script is broken. The fix is already on its way have as part of 2nd half of the re-factoring, because my IDE spotted that bug some weeks ago.

However, in your particular case there is probably a much easier and faster solution. If the EXIF data of a photo contained an explicit time offset, then the column `taken_at_orig_tz` contains a _time offset_, e.g. `"+01:00"`. I am not aware of any camera model or smartphone that uses proper _named timezones_ today, e.g. something like `"Europe/Berlin"`.

Given that there is a simple heuristic how you can update all your photos at once using SQL. Simply run

    UPDATE photos SET taken_at_orig_tz = 'Europe/Berlin' WHERE taken_at_orig_tz = 'UTC';

The line above assumes that the former (wrong) timezone setting was UTC and your actual timezone is Europe/Berlin. Adopt as you need. The only way how the column might contain `"UTC"` (or any other named timezone) is that this ways your previous (wrong) default timezone which was picked by PHP as a fallback.

**Comment by MikeTheTux** [comment]
> Please open an issue about that one. :)

did it

**Comment by MikeTheTux** [comment]
> Given that there is a simple heuristic how you can update all your photos at once using SQL

I guess that could work. I'm going to check it later ...

**Comment by MikeTheTux** [comment]
> > Given that there is a simple heuristic how you can update all your photos at once using SQL
> 
> I guess that could work. I'm going to check it later ...

It seems that "my problem" is not that big as initially thought. The timezone info in the meta data seems to be quite new. This means that the majority of all old photos are all wrong in the same way and I do not have the problem that I mix pictures with the right and wrong timezone in the same album very often.

Nevertheless the shown timezone in the web-view is wrong. This is why I still would like to correct the timestamps.
As the database stores the time in `UTC`, I need to shift it by -1 hour, when changing `taken_at_orig_tz` to `Europe/Berlin` (=`+01:00`), right?

I plan to execute the following query:

```
UPDATE `photos` SET `taken_at_orig_tz`='Europe/Berlin', `taken_at`=DATE_SUB(`taken_at`, INTERVAL 1 HOUR) WHERE `taken_at_orig_tz`='UTC';
```

But what about CET summer time?
During summer time `Europe/Berlin` translates to `+02:00`.
I can see already now `+02:00` in the DB and Lychee-frontend on photos taken with my mobile including CET timezone info during summer.

How does Lychee handle summer time? Will `Europe/Berlin` in the DB translates to `+02:00` in the Lychee-frontend during summer time as well? In this case I need a different UPDATE query during summer time (`+02:00` instead of `+01:00`).

If this is not the case, we will again have a problem when uploading pictures with timezone info (`+02:00`->`+02:00`) and without timezone info (`Europe/Berlin` -> `+01:00`) when we are back to summer time.

As a next step I will need to run a similar query on all albums where I've not been in the CET timezone.

**Comment by nagmat84** [comment]
> I plan to execute the following query:
> 
> ```SQL
> UPDATE `photos` SET `taken_at_orig_tz` = 'Europe/Berlin', `taken_at` = DATE_SUB(`taken_at`, INTERVAL 1 HOUR) WHERE `taken_at_orig_tz`='UTC';
> ```
>
> I need to shift it by -1 hour, when changing `taken_at_orig_tz` to `Europe/Berlin` (=`+01:00`), right?

Not entirely, thank you for paying attention. `Europe/Berlin` is not equivalent to `+01:00`. The latter is a _timezone offset_, called a level 0 tz information in PHP and always means a time shift by exactly one hour. `Europe/Berlin` is a _named timezone_, called level 2 tz information in PHP and also takes daylight saving into account.

Lychee correctly deals with level 0, 1 and 2 tz information. (Level 1 are _timezone designations_ like CET or CEST). If you were going to update the column `taken_at_tz_orig` to `Europe/Berlin`, then you would also have to shift the time by 1 or 2 hours depending on daylight saving

> But what about CET summer time? During summer time `Europe/Berlin` translates to `+02:00`.

Exactly and that is why `"Europe/Berlin"` and `"+01:00"` or `"+02:00"` are _not_ equivalent. The former is a level 2 tz information, the latter two a level 0 tz information.

> How does Lychee handle summer time? Will `Europe/Berlin` in the DB translates to `+02:00` in the Lychee front-end during summer time as well?

Yes, it will. Lychee handles all types of tz information correctly.

Luckily, MySQL supports the `CONVERT_TZ` keyword, see https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_convert-tz.

So, the following query would probably the best one

```SQL
UPDATE `photos` SET
  `taken_at_orig_tz` = 'Europe/Berlin'
  `taken_at` = CONVERT_TZ(`taken_at`, 'UTC', 'Europe/Berlin');
WHERE
  `taken_at_orig_tz` = 'UTC';
```

**Attention 1:** I haven't tested the SQL query myself.

**Attention 2:** You need to install the MySQL timezone system table first. Otherwise MySQL does not know the timezones. See here: https://dev.mysql.com/doc/refman/8.0/en/time-zone-support.html#time-zone-installation

If you don't want or cannot to install the MySQL timezone system tables, it is probably easier to wait for a fix of #1208. I already have the fix, I only need to cherry-pick the commits from my 2nd half of the re-factoring.

**Comment by MikeTheTux** [comment]
Thanks allot. I came up with a similar solution in parallel to your post.
**You need to switch the parameters of `CONVERT_TZ()`, as the offset must be removed but not added.**

The following query does the right translation in the DB 👍 

```
UPDATE `photos` SET
  `taken_at_orig_tz` = 'Europe/Berlin',
  `taken_at` = CONVERT_TZ(`taken_at`, 'Europe/Berlin', 'UTC');
WHERE
  `taken_at_orig_tz` = 'UTC';
```

I can also confirm, that the Lychee PHP implementation is treating the data then in the right way 👍

**Comment by MikeTheTux** [comment]
Thanks again for your support!

**Comment by nagmat84** [comment]
The PR #1209 is also ready.
