### ISSUE TITLE
proxy_cookie_path +HttpOnly breaks laravel XHR with http 419

### ISSUE THREAD

**Issue by audioscavenger** [LycheeOrg/Lychee#1214]
### Detailed description of the problem
Upgraded nginx proxy, with cookie security as recommended all around the web, with `proxy_cookie_path / "__Host-sess=123; path=/; HttpOnly; Secure; SameSite";`
The keyword `HttpOnly` causes an http 419 related to laravel and XHR: `419 No Reason Phrase`
The response is a json message | "CSRF token mismatch."
This breaks the public page.

Not sure what that means but removing the keyword _HttpOnly_ indeed solves the problem.
I host a host of photography sites including piwigo photoprism photostructure and librephotos and none did complain after the nginx change.

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. in your nginx front/proxy edit ssl.conf
2. add cookie security: `proxy_cookie_path / "__Host-sess=123; path=/; HttpOnly; Secure; SameSite";`
3. access your lychee
4. error http 419

**Screenshots**
![image](https://user-images.githubusercontent.com/3853962/152415482-75a79a48-d044-4044-bc35-c7f993d443e4.png)

### Output of the diagnostics
```
    Diagnostics
    -----------
    Warning: Dropbox import not working. dropbox_key is empty.
    Warning: You may experience problems when uploading a photo of large size. Take a look in the FAQ for details.
    Info: Latest version of PHP is 8.1

    System Information
    ------------------
    You must be logged in to see this.

    Config Information
    ------------------
    You must be logged in to see this.
```

### Browser and system
* firefox latest
* Docker version 20.10.7, build 20.10.7-0ubuntu5~20.04.2
* compose + mariadb + lychee latest

**Comment by d7415** [comment]
Lychee accesses the cookie from its javascript, so will not (currently) work with that setting.

**Comment by nagmat84** [comment]
I am re-opening the issue, because I believe it should be fixed and as far as I see it, it is quite simple to fix. Chances are that it will "accidentally" happen as part of the second half of my big re-factoring. Basically, we only must change the way how the front-end sends its AJAX requests. Luckily, this code is nicely concentrated in `lychee.api`. So the fix should only require a couple of lines.
