### ISSUE TITLE
[Enhancement] Tags for Albums

### ISSUE THREAD

**Issue by MikeTheTux** [LycheeOrg/Lychee#1215]
I would like to request the possibilty in order to add Tags to `Albums`, similar to how it is already possible for `Photos`.
The database provides already a column `albums.showtags`. The GUI seems not to support it. What is it meant for?

**Comment by MikeTheTux** [comment]
Closing this one, as it is redundant to https://github.com/LycheeOrg/Lychee/issues/42

**Comment by nagmat84** [comment]
The column `tag_albums.showtags` defines the set of tags of a `TagAlbum` which must be matched by a photo to be included in this tag album.

The code can be found in [`\Relations\HasManyPhotosByTag::addEagerContraints()`](https://github.com/LycheeOrg/Lychee/blob/8c6b20028f3f3792a0160ecd64ebaffdb637ca5a/app/Relations/HasManyPhotosByTag.php#L40). You set these tags upon creation of a tag album.

**Comment by MikeTheTux** [comment]
got it, thanks!
