### ISSUE TITLE
checksum in photos table not matching the actual sha1sum

### ISSUE THREAD

**Issue by christianhorn** [LycheeOrg/Lychee#1223]
### Detailed description of the problem
I use scripts to modify description and other fields in the photos table of the database. This is broken on the current git tree: I have image files where the 'checksum' value does not match the sha1sum as reported by sha1sum utility, or the php8 sha1_file() function. The checksum seems to get mangled before ending um in the photos-table? The mangling seems to be consistent when importing and displaying the pictures. Just when computing the sha1 sum externally, the difference gets noticed.

I looked at plain php8 code on the system, sha1_file() output for the problematic files matches the real sha1 sum.

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. place https://fluxcoil.net/files/tmp/20210923_001522589_backpacks.jpg in a directory
2. Use 'import from server', point it at that directory
3. Observe checksum appearing in photos table: 5b0539a780e807202f5659d65848dac835801944 vs. real sha1: 8e8ed26b62f93513166039af0448b0a2d72a1981

### Output of the diagnostics
Diagnostics
-----------
Warning: Dropbox import not working. dropbox_key is empty.
Warning: You may experience problems when uploading a photo of large size. Take a look in the FAQ for details.
Warning: You may experience problems when uploading a photo of large size. Take a look in the FAQ for details.
Warning: Pictures that are rotated lose their metadata! Please install Imagick to avoid that.
Warning: Default timezone not properly set; you might experience strange results when importing photos without explicit EXIF timezone

System Information
------------------
Lychee Version (git):            master (e0c2c8c) - Data not in Cache
DB Version:                      4.5.0

composer install:                --no-dev
APP_ENV:                         production
APP_DEBUG:                       false

System:                          Linux
PHP Version:                     8.1
PHP User agent:                  Lychee/4 (https://lycheeorg.github.io/)
Timezone:                        UTC
Max uploaded file size:          2M
Max post size:                   8M
Max execution time:              0
SQLite Version:                  3.36.0

Imagick:                         -
Imagick Active:                  1
Imagick Version:                 -
GD Version:                      2.3.3

Config Information
------------------
version:                         040500
check_for_updates:               0
sorting_Photos_col:              description
sorting_Photos_order:            ASC
sorting_Albums_col:              max_taken_at
sorting_Albums_order:            ASC
imagick:                         1
skip_duplicates:                 0
small_max_width:                 0
small_max_height:                360
medium_max_width:                1920
medium_max_height:               1080
lang:                            en
layout:                          1
image_overlay_type:              desc
default_license:                 CC-BY-SA-4.0
compression_quality:             90
full_photo:                      1
delete_imported:                 0
Mod_Frame:                       1
Mod_Frame_refresh:               30
thumb_2x:                        1
small_2x:                        1
medium_2x:                       1
landing_page_enable:             1
landing_owner:                   Christian Horn
landing_title:                   Christian Horn
landing_subtitle:                Japan, OpenSource & technology
landing_facebook:                
landing_flickr:                  
landing_twitter:                 https://www.twitter.com/chorntwi
landing_instagram:               
landing_youtube:                 
landing_background:              dist/20121103_154205_matsuyama_dogo_onsen_topview_hq_darkened.jpg
site_title:                      Japan, OpenSource and culture
site_copyright_enable:           1
site_copyright_begin:            2008
site_copyright_end:              2021
additional_footer_text:          
display_social_in_gallery:       0
public_search:                   0
SL_enable:                       0
SL_for_admin:                    0
public_recent:                   0
recent_age:                      1
public_starred:                  0
downloadable:                    0
photos_wraparound:               1
map_display:                     1
zip64:                           1
map_display_public:              1
map_provider:                    Wikimedia
force_32bit_ids:                 0
map_include_subalbums:           1
update_check_every_days:         3
has_exiftool:                    0
share_button_visible:            0
import_via_symlink:              0
has_ffmpeg:                      0
location_decoding:               1
location_decoding_timeout:       30
location_show:                   1
location_show_public:            1
rss_enable:                      1
rss_recent_days:                 7
rss_max_items:                   100
prefer_available_xmp_metadata:   0
editor_enabled:                  1
lossless_optimization:           0
swipe_tolerance_x:               150
swipe_tolerance_y:               250
local_takestamp_video_formats:   .avi|.mov
log_max_num_line:                1000
unlock_password_photos_with_url_param: 0
nsfw_visible:                    1
nsfw_blur:                       0
nsfw_warning:                    0
nsfw_warning_admin:              0
map_display_direction:           1
album_subtitle_type:             oldstyle
upload_processing_limit:         4
public_photos_hidden:            1
new_photos_notification:         0
legacy_id_redirection:           1

### Browser and system
client: firefox-97.0-1.fc35.x86_64, Fedora35
Lychee instance: Fedora36 container, php8 (on Fedora35 hypervisor)

**Comment by nagmat84** [comment]
First a disclaimer. I tend to call this a non-bug. We do not give any guarantees about a particular way how the checksums are calculated. The checksums are not part of the "public" API of the backend and only used internally. In particular, the way how the checksums are calculated may be subject to change at any time without warning. So I would not say it is "broken".

However, I understand that these checksums are useful for you. Unfortunately, I am on a trip, so I cannot check the source code what exactly may cause the difference. But the source code is open source, so you can check for yourself. It should be in `AddStandAloneStrategy` (or something like that) if I remember correctly by heart.

Also note, that there was a short period of some weeks during which the checksum was not calculated before rotation of photos, but after rotation. We fixed that problem and introduced a new column `original_checksum`. Now, `original_checksum` is calculated from the original file upon import/upload _before_ the file is normalized. The column `checksum` is calculated from the media file _after_ it has been potentially rotated. Also, `checksum` is updated everytime the media file is rotated and should always match the file on disk, while `original_checksum` remains constant.

Besides auto-rotation of media files upon import/export I cannot think of anything special which should lead to a different SHA-1 checksum. But auto-rotation of images has always been there, this is nothing new and nothing which has changed recently.

But go and check the code for yourself.

**Comment by christianhorn** [comment]
Awesome, thanks a lot. I had not noticed original_checksum, when using that as criteria I can nicely update the entries.
Sorry for the noise, have a safe trip!
