### ISSUE TITLE
Is there any way to preserve original size of an image?

### ISSUE THREAD

**Issue by ghost** [LycheeOrg/Lychee#1224]
Hi, I wanted to store a few very big images in my Lychee instance. They uploaded without any issues, but when I downloaded them later I found, that they were resized, and now they are significantly smaller.

I understand, that size reduction is needed for the web interface display, but I wanted to use Lychee as a storage for stock images for my graphics work and keeping the original size is a must!

**Comment by ildyria** [comment]
Hi.

Please fill up the template provided when opening an issue.
**It is absolutely not clear what you mean by "I downloaded them later".**
I never had problems such as the one you are describing.

You can also disable the image optimizer in the Lychee advanced settings.

**Comment by ildyria** [comment]
Close because unclear **and did not follow provided template**:

Help us to help you.

PS: What you are describing is not en Enhancement, this is a Bug report.

**Comment by kamil4** [comment]
Yeah, we _do_ store the original image, and downloading it should be no problem. The only thing I can imagine is if the image had embedded Exif rotation data -- in that case we normally rotate the original at import size, which preserves the overall dimenstions, but could result in a different file size. As @ildyria said, we need more detail to understand what doesn't work in your case.
