### ISSUE TITLE
lychee:generate_thumbs how to use it ?

### ISSUE THREAD

**Issue by sunosv** [LycheeOrg/Lychee#1226]
Is this function disabled?

**Comment by nagmat84** [comment]
Could be a little bit more precise? The command is not disabled and the signature of the command is printed by Laravel Artisan on the CLI on request. (I think `./artisan lychee:generate_thumbs --help` should do it, may be `./artisan help lychee:generate_thumbs`, I always forget the order).

So what exactly is not working for you?

**Comment by ildyria** [comment]
Syntax is: 
`php artisan lychee:generate_thumbs --help`
The function is sufficiently documented.
