### ISSUE TITLE
Please provide a complete upgrade document 

### ISSUE THREAD

**Issue by cnkmmk** [LycheeOrg/Lychee#1227]
The existing upgrade document cannot be referred to, please re-issue a copy, thank you.

**Comment by ildyria** [comment]
https://lycheeorg.github.io/docs/upgrade.html
&
https://lycheeorg.github.io/docs/installation.html

**Comment by cnkmmk** [comment]
the v 4.3.0 upgrade 4.4.0, cannot use it.

**Comment by ildyria** [comment]
I don't understand.

**Comment by nagmat84** [comment]
I assume the author wants to tell us that the first link is only correct for upgrades from v3, but the author's version is v.4.3.0.

The correct link for updates from v4.x.y to v4.x.z is https://lycheeorg.github.io/docs/update.html.

**Comment by cnkmmk** [comment]
thx, @nagmat84.

I follow the method below, but can't upgrade. And there is an error with error code 500. 

```
[Update manually](https://lycheeorg.github.io/docs/update.html#update-manually)

This update will be the one you have to use if you are following the Release channel.

    1 — Download the [newest Version](https://github.com/LycheeOrg/Lychee/releases)
    2 — Replace all existing files, excluding uploads/ and dist/user.css (and database/database.sqlite if using SQLite as your database)
    3 — Go into the Diagnostic page and click on the Apply migration button.
```

**Comment by nagmat84** [comment]
If you encounter an error 500, this indicates a server-side error. Without additional information we cannot help. Please issue a proper bug report which **uses the template and includes every information requested by that template, in particular incl. all diagnostic output and the precise steps you have taken**.

Just stating that there is a 500 error is not helpful and will not lead to anything.
