### ISSUE TITLE
Album sorting issue

### ISSUE THREAD

**Issue by xi1976github** [LycheeOrg/Lychee#1232]
Lychee should sort albums like newest first, oldest last, 
![image](https://user-images.githubusercontent.com/23615871/155891277-88d7109a-b484-4cdf-9c43-43cb086272aa.png)

A new created Album with Fotos taken today is in the middle, this is not expected behaviour.

[diag.txt](https://github.com/LycheeOrg/Lychee/files/8149034/diag.txt)

**Comment by nagmat84** [comment]
What takedate does Lychee show in the left sidebar for the photos? Was Lychee able to extract the takedate?

**Comment by xi1976github** [comment]
The newest photo in the "old album" shows 31.12.2021, 22.11.22 UTC+01:00 (album creation date 02.01.2022, 18:38:59 UTC+01:00), 
the newest photo in the "new album" shows 14.01.2022, 09.41:07 UTC+01:00 (album creation date 27.02.2022, 16:57:34 UTC+01:00)

**Comment by ildyria** [comment]
@xi1976github could you check if that behaviour is still present ? There have been significant refactoring in the core.
