### ISSUE TITLE
Warning: Default timezone not properly set

### ISSUE THREAD

**Issue by StrangeRanger** [LycheeOrg/Lychee#1233]
### Detailed description of the problem [REQUIRED]

How do I go about fixing the following warning: "Warning: Default timezone not properly set; you might experience strange results when importing photos without explicit EXIF timezone". I had changed to the timezone field inside of `config/app.php` but was still presented with the warning when accessing the "Diagnostics" page.

**Comment by kamil4** [comment]
The best place to change it should be your `.env` file in the top-level Lychee directory.
