### ISSUE TITLE
After upgrade to Lychee 4.4, problem displaying photos

### ISSUE THREAD

**Issue by zylv1** [LycheeOrg/Lychee#1240]
Hi,
Sorry for my English !
### Detailed description of the problem [REQUIRED]
*A clear and concise description of what the bug is.*
After upgrade to Lychee 4.4, sub-albums and photos are no longer displayed. Only top level albums are visible.
 

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1.click on any photo album
2. No sub-albums are displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/100931045/156776427-ef03999e-32d4-4772-89dd-16e4c4ee663d.png)

### Output of the diagnostics  [REQUIRED]
*(Settings => Diagnostics or https://example.com/Diagnostics or `php artisan lychee:diagnostics`)*

    Diagnostics
    -------
    Warning: Dropbox import not working. dropbox_key is empty.
    Warning: You may experience problems when uploading a photo of large size. Take a look in the FAQ for details.
    Warning: You may experience problems when uploading a photo of large size. Take a look in the FAQ for details.
    Warning: You may experience problems when uploading a photo of large size or handling many/large albums. Take a look in the FAQ for details.
    Warning: Pictures that are rotated lose their metadata! Please install Imagick to avoid that.
    Info: Latest version of PHP is 8.1
    Error: PHP zip extension not activated

    System Information
    --------------
    Lychee Version (release):        4.4.0
    DB Version:                      4.4.0
    
    composer install:                --no-dev
    APP_ENV:                         production
    APP_DEBUG:                       false
    
    System:                          Linux
    PHP Version:                     8
    PHP User agent:                  Lychee/4 (https://lycheeorg.github.io/)
    Max uploaded file size:          2M
    Max post size:                   8M
    Max execution time:              30
    MySQL Version:                   10.5.15-MariaDB
    
    Imagick:                         -
    Imagick Active:                  1
    Imagick Version:                 -
    GD Version:                      2.2.5

    Config Information
    --------------
    version:                         040400
    check_for_updates:               0
    sorting_Photos_col:              taken_at
    sorting_Photos_order:            ASC
    sorting_Albums_col:              title
    sorting_Albums_order:            DESC
    imagick:                         1
    skip_duplicates:                 0
    small_max_width:                 0
    small_max_height:                360
    medium_max_width:                1920
    medium_max_height:               1080
    lang:                            fr
    layout:                          1
    image_overlay_type:              desc
    default_license:                 reserved
    compression_quality:             90
    full_photo:                      1
    delete_imported:                 0
    Mod_Frame:                       1
    Mod_Frame_refresh:               30
    thumb_2x:                        1
    small_2x:                        1
    medium_2x:                       1
    landing_page_enable:             0
    landing_owner:                   Sylvain PAULI
    landing_title:                   Zylv
    landing_subtitle:                Photo de Cat & Syl
    landing_facebook:                
    landing_flickr:                  
    landing_twitter:                 
    landing_instagram:               
    landing_youtube:                 
    landing_background:              dist/cat.jpg
    site_title:                      Photos de Cat & Syl
    site_copyright_enable:           1
    site_copyright_begin:            2021
    site_copyright_end:              2021
    additional_footer_text:          
    display_social_in_gallery:       0
    public_search:                   0
    SL_enable:                       0
    SL_for_admin:                    0
    public_recent:                   0
    recent_age:                      1
    public_starred:                  0
    downloadable:                    0
    photos_wraparound:               1
    map_display:                     1
    zip64:                           1
    map_display_public:              0
    map_provider:                    Wikimedia
    force_32bit_ids:                 0
    map_include_subalbums:           1
    update_check_every_days:         3
    has_exiftool:                    0
    share_button_visible:            0
    import_via_symlink:              0
    has_ffmpeg:                      0
    location_decoding:               0
    location_decoding_timeout:       30
    location_show:                   1
    location_show_public:            0
    rss_enable:                      0
    rss_recent_days:                 7
    rss_max_items:                   100
    prefer_available_xmp_metadata:   0
    editor_enabled:                  1
    lossless_optimization:           0
    swipe_tolerance_x:               150
    swipe_tolerance_y:               250
    local_takestamp_video_formats:   .avi|.mov
    log_max_num_line:                1000
    unlock_password_photos_with_url_param: 0
    nsfw_visible:                    0
    nsfw_blur:                       0
    nsfw_warning:                    0
    nsfw_warning_admin:              0
    map_display_direction:           1
    album_subtitle_type:             oldstyle
    upload_processing_limit:         4
    public_photos_hidden:            1
    new_photos_notification:         0
### Browser and system
Firefox 97.0 (64 bits) / Ubuntu 20.04.4 LTS
Chrome 98.0.4758.102 / Windows 10

Thanks for your help,
Sylvain,

**Comment by kamil4** [comment]
What version did you upgrade from?

Are newly created albums affected in the same way?

If yes, can you set `force_32bit_ids` to `1` and then create a new album and see if that fixes it?

**Comment by zylv1** [comment]
I upgrade from v4.3.0.
I'm able to create a new album but I can't upload photos anymore and i can't create sub-albums

I set force_32bit_ids to 1 and create a new album and it fixes the problem but only for the new album.

**Comment by kamil4** [comment]
We've seen similar bug reports. This seems to happen when your PHP is 64-bit but your MySQL/MariaDB is 32-bit.

Essentially, there are three solutions to this problem:
1) Upgrade your database engine to 64-bit.
2) Downgrade Lychee to the version that worked with your database (4.3.0 in your case, although you may want to try some of the incremental releases such as 4.3.6).
3) Upgrade Lychee to the current git master. There's been a large refactoring of the codebase that should comprehensively fix any such 32bit/64bit issues.

**Comment by zylv1** [comment]
I asked my web host. The database is already 64 bit.
For solutions 2 and 3, I don't know how to do it because I installed Lychee with Softaculous.

**Comment by nagmat84** [comment]
Do you have CLI access to your web host?

**Comment by zylv1** [comment]
Yes I have Command line Acces.

**Comment by nagmat84** [comment]
In this case you could use the CLI to either downgrade to the last working version of upgrade to a newer version manually. But I don't know what happens if you interfere with Softaculous.

**Comment by zylv1** [comment]
I have successfully upgrade to version 4.5 using CLI. And it fixes the problem ! 
Softaculous detected an inconsistency in the version number and and offered to  update the version number in the softaculous administration interface.

Thank you @kamil4  and @nagmat84  for your help.
