### ISSUE TITLE
Importing plain JPEG after export from Lightrom (raw=>jpeg) creates problem

### ISSUE THREAD

**Issue by krzych-s** [LycheeOrg/Lychee#1243]
Importing plain JPEG after export from Lightrom (raw=>jpeg) creates problem like this:

2022-03-17 12:00:54 -- error   -- App\Actions\Photo\Extensions\Save::recover -- 59 -- Something went wrong, error 22P02, SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type integer: "1619.9105812221"
CONTEXT:  unnamed portal parameter $32 = '...' (SQL: insert into "photos" ("id", "checksum", "title", "url", "description", "tags", "width", "height", "type", "filesize", "iso", "aperture", "make", "model", "lens", "shutter", "focal", "taken_at", "taken_at_orig_tz", "latitude", "longitude", "altitude", "imgDirection", "location", "livePhotoContentID", "public", "star", "album_id", "owner_id", "thumb2x", "thumbUrl", "medium_width", "medium_height", "medium2x_width", "medium2x_height", "small_width", "small_height", "small2x_width", "small2x_height", "updated_at", "created_at") values (16475184479003, 8e0abcdae19e89543d60d50724e1096d4c8eabb1, DSC03298, 8e0abcdae19e89543d60d50724e1096d.jpg, , , 9058, 6039, image/jpeg, 31204867, 100, f/8.0, SONY, ILCE-7RM4A, FE 24-70mm F4 ZA OSS, 1/500 s, 24 mm, 2022-03-11 15:55:29, +01:00, ?, ?, ?, ?, ?, ?, 0, 0, 16475138922476, 0, 1, 8e0abcdae19e89543d60d50724e1096d.jpeg, 1619.9105812221, 1080, 3239.8211624441, 2160, 539.97019374069, 360, 1079.9403874814, 720, 2022-03-17 12:00:54, 2022-03-17 12:00:54) returning "id")

Temporary solution of mine was to change types of the size fields to numeric instead of integer

![image](https://user-images.githubusercontent.com/41375014/158805888-f7b5e5b1-10c6-4c37-956c-031105b577a8.png)

Please fix asap.

**Comment by d7415** [comment]
This looks like #1234 which is fixed in master.

**Comment by krzych-s** [comment]
Thx, didn't notice that.
