### ISSUE TITLE
Out of range value for column 'album_id' 

### ISSUE THREAD

**Issue by kassirh** [LycheeOrg/Lychee#1244]
### Detailed description of the problem [REQUIRED]
I have installed v4.4.0. The downloaded, and extracted the zip file to install. I also tried to use the git repo directly, by checking out the relevant commit version for 4.4.0. I have tried multiple fresh installs.

Linux 4.18.0-348.12.2.lve.el8.x86_64
MySQL 8.0.28
PHP 8.1.3

<img width="705" alt="Screenshot 2022-03-21 at 08 39 40" src="https://user-images.githubusercontent.com/2500088/159228009-fe3602bc-9179-45f9-b438-13ad18460d96.png">

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Create album
2. Go into album and try to upload photo from web UI (+). I am not importing via a URL.
3. Fails to upload with "something went wrong, errorr 22003.

### Output of the diagnostics  [REQUIRED]
*(Settings => Diagnostics or https://example.com/Diagnostics or `php artisan lychee:diagnostics`)*

```
    2022-03-21 08:31:12 -- error   -- App\Actions\Photo\Extensions\Save::recover -- 59 -- Something went wrong, error 22003, 
SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'album_id' at row 1 (SQL: insert into `photos` (`id`, `checksum`, `title`, `url`, `description`, `tags`, `width`, `height`, `type`, `filesize`, `iso`, `aperture`, `make`, `model`, `lens`, `shutter`, `focal`, `taken_at`, `taken_at_orig_tz`, `latitude`, `longitude`, `altitude`, `imgDirection`, `location`, `livePhotoContentID`, `public`, `star`, `album_id`, `owner_id`, `thumb2x`, `thumbUrl`, `medium_width`, `medium_height`, `small_width`, `small_height`, `small2x_width`, `small2x_height`, `updated_at`, `created_at`) values (1647851472, 2731cd826ba979d9c3f51db32f343ca9eaee99d6, 1S3A0242, 2731cd826ba979d9c3f51db32f343ca9.jpg, , , 1000, 1500, image/jpeg, 683525, 5000, f/4.5, Canon, Canon EOS R6, RF24-105mm F4-7.1 IS STM, 1/80 s, 24 mm, 2022-03-19 21:04:32, UTC, ?, ?, ?, ?, ?, ?, 0, 0, 16478178281540, 0, 1, 2731cd826ba979d9c3f51db32f343ca9.jpeg, 720, 1080, 240, 360, 480, 720, 2022-03-21 08:31:12, 2022-03-21 08:31:12))
```
### Browser and system
Brave and Safari (latest). MacOS 12.3

I've tried everything, but can't get it to work.

**Comment by nagmat84** [comment]
If this is a new installation I strongly recommend you to use the current `master` which points to what currently is called 4.5.0.

The problems with IDs should be fixed. Moreover it will spare you a long migration and — in case you plan to share photos — will give you the future IDs right away.

**Comment by kassirh** [comment]
> If this is a new installation I strongly recommend you to use the current master which points to what currently is called 4.5.0.

Thanks for the quick answer. Let me try tonight, and come back to let you know if it resolved the issue, or not.

**Comment by kassirh** [comment]
Ok, I went to the latest release, and now have a different set of problems. Server error or API not found. I think it is time to call it a day. I am sorry. I absolutely love the app, but 2 hours in, and can't get it working.

Thanks for the answer.

**Comment by kassirh** [comment]
Ok, so finally, I swapped using a MySQL db, to Sqlite, and managed to make it work with version 4.5.
