### ISSUE TITLE
This can't no more be installed on website hosting provider?

### ISSUE THREAD

**Issue by Bazimek** [LycheeOrg/Lychee#1247]
Version 3 was just 100 files -> copy to the hosting provider and that was it.

This version got 7k files?! :O So I guess it is not possible to run it on hosting provider anymore? After an hour I copied every file on the hosting and it shows

The requested URL /domains/<MY DOMAIN>/install was not found on this server.

**Comment by nagmat84** [comment]
I can't understand what you are doing from your problem description.

I assume you have no CLI access to your web host, but only filesystem access. Then you should follow this installation guide: https://lycheeorg.github.io/docs/#from-release We provide a ZIP archive with all required files which must be put into your web space. I haven't counted the files, but 7,000 sounds as way too many. But even if there were so many it shouldn't take you 1h to copy them.

After you have copied the files, Lychee still needs to be configured (again see the installation guide). The second part of your post indicates that you might have skipped that part.

**Comment by nagmat84** [comment]
As there has been no response from the reporter in a timely manner and the problem report is unclear, I am going to close this issue.

**Comment by kamil4** [comment]
I will add a comment about the count of files though: indeed a distribution archive has on the order of 7,000 files, but the vast majority of them are the dependencies in the `vendor` folder.
