### ISSUE TITLE
[Enhancement] header text for the gallery.

### ISSUE THREAD

**Issue by lepidas** [LycheeOrg/Lychee#1249]
Is it tpossible to make it easy to add text to the header of the gallery?
At the moment what is the way to add some text to it? Thank you community

**Comment by nagmat84** [comment]
There is a pending PR #1195 which will introduce markdown support. It will also allow to add a description to each album which can be displayed below the title. I guess that is what you want.

At the moment the PR is blocked by another rather huge PR, but I hope that we will get everything merged within a couple of weeks.

**Comment by ildyria** [comment]
For the future front end, I do plan to create something like a HERO/header thingy (a bit _a la flickr_).

**Comment by lepidas** [comment]
I just want to add a return back to my website text with link

**Comment by ildyria** [comment]
Not implemented in the current version.

But can most likely be added as an Enhancement. :)

**Comment by nagmat84** [comment]
> I just want to add a return back to my website text with link

The markdown PR will also supports links via the markdown syntax `[description](url)`. However, for your use case you would have to add the return link as part of the description to every album individually. There is no option to set this on a global level.

**Comment by lepidas** [comment]
> > I just want to add a return back to my website text with link
> 
> The markdown PR will also supports links via the markdown syntax `[description](url)`. However, for your use case you would have to add the return link as part of the description to every album individually. There is no option to set this on a global level.

global level you mean the very central home page of my Lycee gallery? Wow it seems little bit strange

**Comment by kamil4** [comment]
> global level you mean the very central home page of my Lycee gallery? Wow it seems little bit strange

He means that there is no option to add such header in one place but have it displayed in _all_ albums and subalbums; it will have to be added individually to every album that you want.
