### ISSUE TITLE
About landing_background

### ISSUE THREAD

**Issue by Tiritibambix** [LycheeOrg/Lychee#1257]
Hello.

I wanted to change the default `dist/cat.jpg` landing background.

I tried creating and pointing to `uploads/background/mybg.jpg` but it's not working.

`/dist/` in nowhere to be found.

How shall I proceed ?

**Comment by nagmat84** [comment]
There is no default landing page with a cat photo for a vanilla installation. A fresh installation comes with absolutely no photos and an empty gallery. There should be no need to link anything somewhere.

How did you install Lychee? What does your setup look like?

**Comment by Tiritibambix** [comment]
I'm using [LycheeOrg/Lychee-Docker](https://github.com/LycheeOrg/Lychee-Docker/blob/master/docker-compose.yml).

I probably should post there ...

**Comment by ildyria** [comment]
@tiritibambix if you wish to change the cat for something else, you just need to edit the line in the Settings -> More menu.

**Comment by Tiritibambix** [comment]
Thank you for your answer.

As mentioned above, I tried creating and pointing to `uploads/background/mybg.jpg`.

Should it be the absolute path ? Something like `/srv/path/to/my/uploads/background/bg.jpg` ?

**Comment by ildyria** [comment]
Nah, a Url path.

**Comment by Tiritibambix** [comment]
> Nah, a Url path.

You mean like in `www.img.com/bg.jpg` ?
Didn't work

Edit: nevermind I figured it out

**Comment by hhenne1** [comment]
i still cant figure it out.. care to elaborate?

**Comment by Tiritibambix** [comment]
> i still cant figure it out.. care to elaborate?

Let's say you mounted `/path/to/lychee/uploads:/uploads`
Create a folder in `/path/to/lychee/uploads`, say `background`. Put your `background.jpg` image in it.

Head to `settings > more > landing_background` and input `uploads/background/background.jpg`
Save.

**Comment by hhenne1** [comment]
weird... i was sure i had tried that. seems so obvious and works well. thanks.
I was just under the impression that it would extend to more than just the landing page itself. my mistake

**Comment by clueless416** [comment]
> Let's say you mounted `/path/to/lychee/uploads:/uploads` 
>Create a folder in `/path/to/lychee/uploads`, say `background`. Put your `background.jpg` image in it.
> 
> Head to `settings > more > landing_background` and input `uploads/background/background.jpg` 
>Save.

Ok, I'm sure it's user error but, I've done exactly this and still cannot get it to work. 

I'm using an Unraid docker image with the "upload path" `/mnt/user/photos/Lychee/` which is abbreviated `/pictures` 
Under that directory I've created a folder `background` and saved both a `.webp` and `.jpg` version of the picture I want to use.
In `settings > more > landing_background` I've input `pictures/background/background.jpg`

**Comment by Tiritibambix** [comment]
> In `settings > more > landing_background` I've input `pictures/background/background.jpg`

`/mnt/user/photos/Lychee/background/background.jpg` on your machine should be `/pictures/background/background.jpg` in your container.

If you don't find a typo in there and got it working, try binding `/mnt/user/photos/Lychee/` to `/uploads` and not `/pictures` and in `settings > more > landing_background` input `uploads/background/background.jpg`

**Comment by Baltimorepc** [comment]
ive tried all these options and still cant get it to work any other ideas im on the newest version 5.5.1
