### ISSUE TITLE
Remove Google Fonts usage

### ISSUE THREAD

**Issue by qwerty287** [LycheeOrg/Lychee#1261]
This is actually more a background question than a bug report or feature request. I don't really know any CSS and web styling, however, there are some lines importing Google Fonts APIs. I think, you should replace them with local files - take a look at your website:
```
Your server, your data, your rules. Never depend on someone else. Lychee is a self-hosted solution, so you are in the full control of your photos.
```
Sure, I'm in the full control of my photos, but connections to Google Fonts are still very bad and `Never depend on someone else` also isn't correct.

The lines are:
https://github.com/LycheeOrg/Lychee/blob/cb2a2262bfff56dee1a8468fbddc1bd143ea0ea0/simple_error_template.html#L11-L12
https://github.com/LycheeOrg/Lychee/blob/cb2a2262bfff56dee1a8468fbddc1bd143ea0ea0/public/dist/landing.css#L1
https://github.com/LycheeOrg/Lychee/blob/cb2a2262bfff56dee1a8468fbddc1bd143ea0ea0/config/secure-headers.php#L362 (more a side effect of others)
https://github.com/LycheeOrg/Lychee/blob/cb2a2262bfff56dee1a8468fbddc1bd143ea0ea0/config/secure-headers.php#L417 (more a side effect of others)
https://github.com/LycheeOrg/Lychee/blob/cb2a2262bfff56dee1a8468fbddc1bd143ea0ea0/public/dist/page.css#L1
https://github.com/LycheeOrg/Lychee/blob/cb2a2262bfff56dee1a8468fbddc1bd143ea0ea0/public/installer/assets/css/style.css#L8
https://github.com/LycheeOrg/Lychee/blob/cb2a2262bfff56dee1a8468fbddc1bd143ea0ea0/resources/views/error/error.blade.php#L10-L11
https://github.com/LycheeOrg/Lychee/blob/cb2a2262bfff56dee1a8468fbddc1bd143ea0ea0/resources/views/error/update.blade.php#L10-L11
https://github.com/LycheeOrg/Lychee-front/blob/feba79086476c7c522052b9b8d4c81b397a888c3/styles/landing/landing.scss#L2
https://github.com/LycheeOrg/Lychee-front/blob/feba79086476c7c522052b9b8d4c81b397a888c3/styles/page/page.scss#L2

**Comment by ildyria** [comment]
No worries. I think we do all agree with you.
A few years back when I added the landing page, I used some html layout which included those fonts (mostly Roboto).
Adding them statically would also be fine for me. :)

**Comment by kamil4** [comment]
We actually discussed this recently here: https://github.com/LycheeOrg/Lychee/pull/1217#discussion_r836562219 :smiley:.

**Comment by qwerty287** [comment]
There is an issue with Laravel here, because they used Google Fonts in their Exception templates. There is a merged PR https://github.com/laravel/framework/pull/40926 for Laravel 9.x, which is not used by Lychee (means the only way fixing the problem on the Exception templates is to upgrade Laravel to any version higher than Laravel 9.0.2, the first version which includes the PR).

**Comment by nagmat84** [comment]
There is no need to use the exception templates provided by Laravel, they can  be replaced by custom templates and the branch `consistent_json_api` also does so. However, I only modified them to the necessary extent and did not take care of any font dependencies.
