### ISSUE TITLE
[Enhancement] different photos in background of hovered album

### ISSUE THREAD

**Issue by qwerty287** [LycheeOrg/Lychee#1265]
*Explain in a few words which functionality or improvements you would like to see in Lychee.*
If I hover over an album with the mouse, the are 2 more images behind the thumbnail. These photos are exactly the same as the thumbnail, independent from how many photos are in there.
My suggestions:
* no / 1 image(s): no animated background photos (only thumbnail)
* 2 images: view one background photos which is different from the thumbnail
* 3 or more: three background photos, but only different one

![Screenshot_20220411_110257](https://user-images.githubusercontent.com/80460567/162702806-5c65a482-6ca1-4d49-bf82-896cda407bea.png)

**Comment by ildyria** [comment]
This was the original implementation (v3 and early v4). We decided to move to single thumb image for the following reasons:
- **simpler code in the back end** (if you only have one level of album it is easy, once you start including sub albums, it becomes more complex).
- simpler code in the front end (loop no longer needed etc...)
- lower memory footprint (on server and on the page loading client side).

**Comment by kamil4** [comment]
All of what @ildyria wrote about is true but what directly prompted us to abandon the three separate photos was the implementation of custom photo cover selection. Customizing one is fine; customizing three would be kind-of crazy.

We thought that the old visual feedback when hovering over an album was still worth keeping, but if you have an idea for a different kind of feedback, I think it's worth considering. Maybe simply making the hovered-over image slightly larger? Or some different animation involving just one image?

**Comment by qwerty287** [comment]
A different animation with only one image would be the best, I think.

**Comment by kamil4** [comment]
Play around with it and when you have something that you think looks good, submit a PR :smiley:.

**Comment by ildyria** [comment]
I guess this one is pretty stale. :)
