### ISSUE TITLE
Unable to download albums.

### ISSUE THREAD

**Issue by tyz1989** [LycheeOrg/Lychee#1268]
In short - I am able to download individual images, but unable to download albums.

I have enabled the "downloadable" setting in the options ( 0 -> 1 ) and also enabled the downloadable option in the webui for each album.

Lychee is installed within a Jail on my Truenas Core system. Everything is working well and as intended except the above issue. My gut feeling is the Zipping of the files is failing for some reason? Maybe the zipping pkg has corrupted during the install? I am still very new to FreeBSD and appreciate any help I can get.

### Steps to reproduce the issue
**Steps to reproduce the behavior:**

1. Go to Lychee jail via local IP or Public IP
2. Click on Download album button, or right click and download album.
3. _See error*_ Nothing happens in mozilla firefox (By pressing F12 I was able to find "500
Internal Server Error"), microsift edge "ERR_INVALID_RESPONSE"

### Output of the diagnostics  [REQUIRED]

    Diagnostics
    -------
    Warning: Dropbox import not working. dropbox_key is empty.
    Info: Latest version of PHP is 8.1

    System Information
    --------------
    Lychee Version (git):            master (d8279c8) - Up to date (3 hours ago).
    DB Version:                      4.5.0
    
    composer install:                --no-dev
    APP_ENV:                         production
    APP_DEBUG:                       false
    
    System:                          FreeBSD
    PHP Version:                     8
    PHP User agent:                  Lychee/4 (https://lycheeorg.github.io/)
    Timezone:                        Australia/Melbourne
    Max uploaded file size:          16G
    Max post size:                   16G
    Max execution time:              3600
    MySQL Version:                   10.3.34-MariaDB
    
    Imagick:                         1
    Imagick Active:                  1
    Imagick Version:                 1692
    GD Version:                      2.3.1

    Config Information
    --------------
    version:                         040500
    check_for_updates:               1
    sorting_Photos_col:              created_at
    sorting_Photos_order:            DESC
    sorting_Albums_col:              max_taken_at
    sorting_Albums_order:            DESC
    imagick:                         1
    skip_duplicates:                 0
    small_max_width:                 0
    small_max_height:                360
    medium_max_width:                1920
    medium_max_height:               1080
    lang:                            en
    layout:                          1
    image_overlay_type:              desc
    default_license:                 none
    compression_quality:             90
    full_photo:                      1
    delete_imported:                 0
    Mod_Frame:                       1
    Mod_Frame_refresh:               30
    thumb_2x:                        1
    small_2x:                        1
    medium_2x:                       1
    landing_page_enable:             0
    landing_owner:                   
    landing_title:                   
    landing_subtitle:                
    landing_facebook:                
    landing_flickr:                  
    landing_twitter:                 
    landing_instagram:               
    landing_youtube:                 
    landing_background:              dist/cat.jpg
    site_title:                      Richardson Photo Album
    site_copyright_enable:           1
    site_copyright_begin:            2019
    site_copyright_end:              2099
    additional_footer_text:          
    display_social_in_gallery:       0
    public_search:                   0
    SL_enable:                       0
    SL_for_admin:                    0
    public_recent:                   0
    recent_age:                      1
    public_starred:                  0
    downloadable:                    1
    photos_wraparound:               1
    map_display:                     0
    zip64:                           1
    map_display_public:              0
    map_provider:                    Wikimedia
    force_32bit_ids:                 0
    map_include_subalbums:           0
    update_check_every_days:         3
    has_exiftool:                    0
    share_button_visible:            0
    import_via_symlink:              0
    has_ffmpeg:                      0
    location_decoding:               0
    location_decoding_timeout:       30
    location_show:                   1
    location_show_public:            0
    rss_enable:                      0
    rss_recent_days:                 7
    rss_max_items:                   100
    prefer_available_xmp_metadata:   0
    editor_enabled:                  1
    lossless_optimization:           0
    swipe_tolerance_x:               150
    swipe_tolerance_y:               250
    local_takestamp_video_formats:   .avi|.mov
    log_max_num_line:                1000
    unlock_password_photos_with_url_param: 0
    nsfw_visible:                    1
    nsfw_blur:                       0
    nsfw_warning:                    0
    nsfw_warning_admin:              0
    map_display_direction:           1
    album_subtitle_type:             oldstyle
    upload_processing_limit:         4
    public_photos_hidden:            1
    new_photos_notification:         0
    legacy_id_redirection:           1

### Browser and system

Mozilla Firefox + Microsoft Edge
Truenas Scale - Running in a jail compiled by a script. ( https://github.com/LycheeOrg/Lychee )

**Comment by nagmat84** [comment]
Is there anything in the logs? What happens if you don't download an album but a collection of multiple, individual photos? If you are right and the problem is with zipping, then this should fail, too.

**Comment by tyz1989** [comment]
There is nothing show in logs related to zipping/downloading. And I am unable to download multiple images at once.

I have recreated the jail and was able to download zip files initially, but they were empty... as i have given permissions to be downloaded yet.

Could it be a Truenas permissions issue within the jails? o.O

**Comment by nagmat84** [comment]
> Could it be a Truenas permissions issue within the jails? o.O

Maybe, I don't know. I have no TrueNAS and have no experience with jail.

Do you have CLI access and did you install Lychee via `git clone`? If yes you could test the following

```
git checkout consistent_json_api
git pull
composer install
./artisan migrate
./artisan cache:clear && ./artisan config:clear && ./artisan optimize:clear && ./artisan route:clear && ./artisan view:clear
```

The branch `consistent_json_api` greatly improves error handling and you should see a better error message in the logs.

Command 1 takes you to the branch. Command 2 pulls in the new updates. Commands 3 and 4 should typically be executed after command 2 automatically, but it is safe to run them manually again. Command 5 clears all caches to ensure that no old information interferes.

**Comment by tyz1989** [comment]
I'm not sure of the correct terminology so please bare with me. Truenas Jails run on FreeBSD, so I don't believe CLI commands will work for me. They how ever might be able to be rewritten to suit.

I am able to download empty albums in zip form, but if there are files in the album it wont work. Weird... I am thinking that maybe the php80-zip does not have permission to access the files.

**Comment by nagmat84** [comment]
> Truenas Jails run on FreeBSD, so I don't believe CLI commands will work for me.

Why not? How did you install Lychee in the first place?

**Comment by tyz1989** [comment]
I followed this guide to use their script: https://github.com/danb35/freenas-iocage-lychee

**Comment by nagmat84** [comment]
I had a quick look into their scripted installation. At it's core it executes

```
iocage ​exec​ ​"​${JAIL_NAME}​" ​ git clone https://github.com/LycheeOrg/Lychee /usr/local/www/Lychee
```

And the environment variable `${JAIL_NAME}` equals `lychee` unless you haven't changed it in the configuration file. I assume all the commands above should work if you put the prefix `iocage ​exec​ ​lychee` in front of them.

**Comment by tyz1989** [comment]
I just tried:

iocage ​exec​ ​Lychee git checkout consistent_json_api

and it came back with

Command: git checkout  consistent_json_api failed!

**Comment by nagmat84** [comment]
Unfortunately, I am not an expert for FreeBSD or jails. I only had a quick look at what jails are (basically a chroot environment with some extras) and from what I understood you can run commands within a jail via said command.

But I noticed that you typed `iocage exec Lychee` with a capital L, but the name of the jail is `lychee` with a small L. I assume that the name of a jail is case-sensitive. Is this only a copy and paste error in your comment?

**Comment by tyz1989** [comment]
I actually did change it to a capital L while setting up my jail. so it is different, but not an error.

Thanks for all your help. Ill come back to it tomorrow :)

**Comment by nagmat84** [comment]
My fault. Of course the initial `git clone` command from the scripted installer cloned Lychee into a subdirectory within the jail. The suggested command from above runs `git checkout` in the root directory of the jail which obviously cannot work, because the command must be run from that sub-directory in that jail. So you first need to change into that subdirectory. But that's out of my wheelhouse.

**Comment by tyz1989** [comment]
Ok well I was able to follow those instructions and I am now able to download albums, but they are empty zips still.

**Comment by nagmat84** [comment]
Anything in the logs? If you are on branch `consistent_json_api` you should see more/better error reports.

**Comment by tyz1989** [comment]
Progress!

After following you commands, the clockwork directory was owned by root and user www was not able to write in that directory... causes the webui of Lychee to not work at all. I have been able to adjust the permission to get it working!

How ever downloading albums as zips is still not working, but I do have an error log now!

2022-04-11 17:20:17 UTC -- error   -- App\Actions\Album\Archive::compressAlbum -- 196 -- Call to undefined function ZipStream\gzdeflate()

**Comment by tyz1989** [comment]
You legend! Thank you so much!

It is working now!

I had to add

pkg install php80-zlib

and restart with

service php-fpm restart

**Comment by nagmat84** [comment]
I am happy I could help. But after we merged the branch into master (hopefully within the next month) you need to remember to switch back to the `master` branch. Otherwise you will be stuck in the (dead) branch `consistent_json_api` and won't get any updates.

**Comment by tyz1989** [comment]
Great, thanks for the heads up.

Could I please get the commands to switch back to the master branch? I will revisit this post when it's time to switch back.

**Comment by nagmat84** [comment]
```
git checkout master
git pull
composer install --no-dev
./artisan migrate
./artisan cache:clear && ./artisan config:clear
```

Nearly the same five lines as earlier. But with `master` in the first line.

Also note the `--no-dev` in the third line. Actually, this should have been there in the first place and will avoid the installation of clockwork, so you won't encounter the permission problem again.
