### ISSUE TITLE
Empty Albums not working (empty zip)

### ISSUE THREAD

**Issue by skydivercactus** [LycheeOrg/Lychee#1276]
### Detailed description of the problem [REQUIRED]
*A clear and concise description of what the bug is.*

Download button for album empty albums zip. 

workaround: A work around is crtl+a and download selected. 

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Go to any albums
2. Click on download albums
3. Zip Downloads
4. Zip is empty.

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

### Output of the diagnostics  [REQUIRED]
```
Diagnostics
-----------
Error: Wrong property for image_overlay_type in database, expected exif or desc or date or none, got takedate
Warning: Dropbox import not working. dropbox_key is empty.
Warning: You may experience problems when uploading a photo of large size. Take a look in the FAQ for details.
Warning: You may experience problems when uploading a photo of large size. Take a look in the FAQ for details.
Info: Latest version of PHP is 8.1
Warning: Default timezone not properly set; you might experience strange results when importing photos without explicit EXIF timezone

System Information
------------------
Lychee Version (git):            master (0199212) - Data not in Cache
DB Version:                      4.5.0

composer install:                --no-dev
APP_ENV:                         local
APP_DEBUG:                       false

System:                          FreeBSD
PHP Version:                     8
PHP User agent:                  Lychee/4 (https://lycheeorg.github.io/)
Timezone:                        UTC
Max uploaded file size:          2M
Max post size:                   8M
Max execution time:              0
MySQL Version:                   10.2.31-MariaDB

Imagick:                         1
Imagick Active:                  1
Imagick Version:                 1692
GD Version:                      2.3.1

Config Information
------------------
version:                         040500
check_for_updates:               1
sorting_Photos_col:              taken_at
sorting_Photos_order:            DESC
sorting_Albums_col:              title
sorting_Albums_order:            ASC
imagick:                         1
skip_duplicates:                 0
small_max_width:                 0
small_max_height:                360
medium_max_width:                1920
medium_max_height:               1080
lang:                            en
layout:                          1
image_overlay_type:              takedate
default_license:                 none
compression_quality:             90
full_photo:                      1
delete_imported:                 0
Mod_Frame:                       1
Mod_Frame_refresh:               30
thumb_2x:                        1
small_2x:                        1
medium_2x:                       1
landing_page_enable:             0
landing_owner:
landing_title:
landing_subtitle:
landing_facebook:
landing_flickr:
landing_twitter:
landing_instagram:
landing_youtube:
landing_background:
site_title:                      Home Gallery
site_copyright_enable:           0
site_copyright_begin:            2019
site_copyright_end:              2019
additional_footer_text:
display_social_in_gallery:       0
public_search:                   0
SL_enable:                       0
SL_for_admin:                    0
public_recent:                   0
recent_age:                      1
public_starred:                  0
downloadable:                    0
photos_wraparound:               1
map_display:                     1
zip64:                           1
map_display_public:              1
map_provider:                    Wikimedia
force_32bit_ids:                 0
map_include_subalbums:           1
update_check_every_days:         3
has_exiftool:                    0
share_button_visible:            0
import_via_symlink:              0
has_ffmpeg:                      1
location_decoding:               1
location_decoding_timeout:       30
location_show:                   1
location_show_public:            0
rss_enable:                      0
rss_recent_days:                 7
rss_max_items:                   100
prefer_available_xmp_metadata:   0
editor_enabled:                  1
lossless_optimization:           0
swipe_tolerance_x:               150
swipe_tolerance_y:               250
local_takestamp_video_formats:   .avi|.mov
log_max_num_line:                1000
unlock_password_photos_with_url_param: 0
nsfw_visible:                    1
nsfw_blur:                       0
nsfw_warning:                    0
nsfw_warning_admin:              0
map_display_direction:           1
album_subtitle_type:             oldstyle
upload_processing_limit:         4
public_photos_hidden:            1
new_photos_notification:         0
legacy_id_redirection:           1
```

### Browser and system
Tired Latest Chrome and Firefox, same result.

**Comment by kamil4** [comment]
Weird. I'm assuming this is also happening when you are logged in and the album belongs to the current user? Are there any potentially interesting messages in the Logs? Do you have the `zlib` php module installed (use `php -m` to see the full list).

**Comment by skydivercactus** [comment]
> Weird. I'm assuming this is also happening when you are logged in and the album belongs to the current user? Are there any potentially interesting messages in the Logs? Do you have the `zlib` php module installed (use `php -m` to see the full list).

zlib is installed, below all the php moudle installed. 

edit: Yes, using same users. Have 3 users, only use one user to import photo and shared with other user. Nothing in logs just fail generation of thumbnails, and login logs. Not really worried about the thumbnails, as it seem just missing Imagick. I wouldn't think this would effect downloading original file again right? 

`[PHP Modules]
bcmath
Core
ctype
date
dom
exif
fileinfo
filter
gd
hash
iconv
imagick
intl
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
redis
Reflection
session
SimpleXML
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
Zend OPcache
zip
zlib
`

**Comment by d7415** [comment]
It may be worth double checking that your CLI PHP is the same as you're using with Lychee. The phpinfo page may help (append /phpinfo to your Lychee URL while logged in as admin) as it should list the modules there.

This is very similar to #1268 which also involved zips on FreeBSD. In that case the issue *was* zlib. That one was also complicated by being in a jail.

**Comment by skydivercactus** [comment]
Yeah, already had look at that issue, that issue like it doesn't download anything. While this is empty zip. 

Yeah that module is installed, could have look if I am missing something? 


edit: What do you mean by double checking CLI is same as PHP? I would assume if there is conflict especially with latest version the ui wouldn't even load. Individual photo downloads is ok, just wish to download my albums and move to different setup. 

![image](https://user-images.githubusercontent.com/49363576/163573841-95eb3157-f960-471b-ad16-7f551f8371c5.png)


![image](https://user-images.githubusercontent.com/49363576/163551691-68e8b4f1-40db-4fa9-9b35-59db5b78471a.png)

**Comment by kamil4** [comment]
What we see sometimes is that the version of PHP used by the http daemon (and thus, the one that Lychee server uses) is different than what's available at the commandline -- that's what @d7415 meant. But we don't see any indication of this being a problem in your case.

Anyway, I'm sorry to say that based on the info provided, I have no idea what the source of the problem you are experiencing is or how to fix it. It's puzzling why you would be getting empty archives without any error messages in the logs.

**Comment by skydivercactus** [comment]
> What we see sometimes is that the version of PHP used by the http daemon (and thus, the one that Lychee server uses) is different than what's available at the commandline -- that's what @d7415 meant. But we don't see any indication of this being a problem in your case.
> 
> Anyway, I'm sorry to say that based on the info provided, I have no idea what the source of the problem you are experiencing is or how to fix it. It's puzzling why you would be getting empty archives without any error messages in the logs.

Is there another location for log apart from web gui or is default log information just basic or debug mode? 

edit: A work around is crtl a and download selected.

**Comment by skydivercactus** [comment]
A work around is crtl a and download selected.

**Comment by kamil4** [comment]
Wait, so download selected (which also zips) works for you, but download of the whole album does not? That is beyond bizarre...

**Comment by skydivercactus** [comment]
> Wait, so download selected (which also zips) works for you, but download of the whole album does not? That is beyond bizarre...

Yeah, there is limit so for larger albums which results in 414 error, I need go updated php/ngix to increase url length.
