### ISSUE TITLE
Wrong live_photo_url  after upgrade from 4.4.0 to git master

### ISSUE THREAD

**Issue by z-jun** [LycheeOrg/Lychee#1280]
After upgarde from 4.4.0 release to git master branch my previously imported live photos did not display the video part due to change of live_photo_url json key returned  by /api/Photo::get.

4.4.0
"live_photo_url": "uploads/big/0eca72a047014b57f3cc7a96ca80d26a.mov"

git master
"live_photo_url": "uploads/0eca72a047014b57f3cc7a96ca80d26a.mov"

Photos initially imported from command line with symlinks.
Temporary fixed in database by adding 'big/' prefix to live_photo_short_path column in photos table;

**Comment by nagmat84** [comment]
Does the problem also exist for newly added live photos?

I am wondering whether this is a bug in the migration or the import/upload/download function.

**Comment by z-jun** [comment]
Both uploaded and synchronized/symlinked photos works on master without problem.

"live_photo_url" points to "uploads/raw/hash.mov" and symlink/file is in right place.

**Comment by nagmat84** [comment]
I tried to reproduce you problem but failed to create a live photo in the first place. Apparently, Google has changed the way how live photos work on their Pixel smartphones which is incompatible with the way how Lychee identifies live photos. (They are also called "top photos" nowadays and don't use ) So I am currently unable to create a live photo my own. Could you provide me with a sample live photo?

**Comment by nagmat84** [comment]
Issued this newly found problem here: https://github.com/LycheeOrg/Lychee/issues/1283

**Comment by nagmat84** [comment]
Also, I have problems to test the problem myself due to a lack of a usable live photo, I can reconstruct the problem and submitted a patch blindly. See https://github.com/LycheeOrg/Lychee/pull/1284.

> Both [freshly] uploaded and synchronized/symlinked photos works on master without problem. `"live_photo_url"` points to `"uploads/raw/hash.mov"` and symlink/file is in right place.

Are you sure that it points to `'raw/'`? The video part of a live photo should also be placed in `big/` next to the photo file.

**Comment by z-jun** [comment]
Yes, i have raw_formats options set to .tex|.heic to be able upload .heic files.

When video part is uploaded first, it lands in big/small etc directories with all variants and is presented as standart photo/video. Subsequent parent .heic  upload moves video part original to raw directory, nukes correctly all video thumbs and merges video and photo instance.

Btw - in the case, when video is uploaded first, upload dialog freezes upon successful upload of image part. Message changes over Processing to Finished, bud dialog remains open and Cancel button does nothing.

Sample live photo parts attached.

[Archiv.zip](https://github.com/LycheeOrg/Lychee/files/8512156/Archiv.zip)
