### ISSUE TITLE
No HTTPS link on landing page

### ISSUE THREAD

**Issue by gareththered** [LycheeOrg/Lychee#1287]
### Detailed description of the problem
When the landing page is enabled, the hyperlinks (my name and Gallery) point to the site URL, but with a http scheme instead of the https scheme.  The `APP_URL` entry in `.env` has the https scheme along with my internet facing FQDN for the host.

Lychee is installed using the official Docker image, with Traefik in front as a TLS terminating load-balancer.   Opening an image with _Open Original_  menu option displays the image in a new tab, using the correct https scheme.  That suggests to me that Lychee generally recognises the correct scheme, but not when creating the landing page.

This could be related to #1281?

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Go to Settings, and select More.  Set `landing_page_enable` to `1`
2. Sign out of the site and refresh the page.
3. Click on the owner's name or the GALLERY link and the browser tries to open the site with the `http` scheme.
4. Browser displays a 404 error (it's how Traefik handles unknown URLs, including known server name with the wrong scheme)

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

### Output of the diagnostics

    Diagnostics
    -------
    Warning: Dropbox import not working. dropbox_key is empty.
    
    System Information
    --------------
    Lychee Version (git):            No git data found.
    DB Version:                      4.4.0
    
    composer install:                --no-dev
    APP_ENV:                         production
    APP_DEBUG:                       true
    
    System:                          Linux
    PHP Version:                     8.1
    PHP User agent:                  Lychee/4 (https://lycheeorg.github.io/)
    Max uploaded file size:          100M
    Max post size:                   100M
    Max execution time:              3600
    MySQL Version:                   10.7.3-MariaDB-1:10.7.3+maria~focal
    
    Imagick:                         1
    Imagick Active:                  1
    Imagick Version:                 1691
    GD Version:                      2.3.0

    Config Information
    --------------
    version:                         040400
    check_for_updates:               0
    sorting_Photos_col:              taken_at
    sorting_Photos_order:            DESC
    sorting_Albums_col:              max_taken_at
    sorting_Albums_order:            DESC
    imagick:                         1
    skip_duplicates:                 0
    small_max_width:                 0
    small_max_height:                360
    medium_max_width:                1920
    medium_max_height:               1080
    lang:                            en
    layout:                          1
    image_overlay_type:              desc
    default_license:                 reserved
    compression_quality:             90
    full_photo:                      1
    delete_imported:                 0
    Mod_Frame:                       1
    Mod_Frame_refresh:               30
    thumb_2x:                        1
    small_2x:                        1
    medium_2x:                       1
    landing_page_enable:             1
    landing_owner:                   Gareth Williams
    landing_title:                   Gareth Williams
    landing_subtitle:                Dogs & Humans Photography
    landing_facebook:                https://www.facebook.com/JohnSmith
    landing_flickr:                  https://www.flickr.com/JohnSmith
    landing_twitter:                 https://www.twitter.com/JohnSmith
    landing_instagram:               https://instagram.com/JohnSmith
    landing_youtube:                 https://www.youtube.com/JohnSmith
    landing_background:              dist/cat.jpg
    site_title:                      Gareth's Photo Library
    site_copyright_enable:           1
    site_copyright_begin:            2019
    site_copyright_end:              2022
    additional_footer_text:          
    display_social_in_gallery:       0
    public_search:                   0
    SL_enable:                       0
    SL_for_admin:                    0
    public_recent:                   0
    recent_age:                      1
    public_starred:                  0
    downloadable:                    0
    photos_wraparound:               1
    map_display:                     1
    zip64:                           1
    map_display_public:              0
    map_provider:                    Wikimedia
    force_32bit_ids:                 0
    map_include_subalbums:           0
    update_check_every_days:         3
    has_exiftool:                    1
    share_button_visible:            0
    import_via_symlink:              0
    has_ffmpeg:                      1
    location_decoding:               0
    location_decoding_timeout:       30
    location_show:                   1
    location_show_public:            0
    rss_enable:                      0
    rss_recent_days:                 7
    rss_max_items:                   100
    prefer_available_xmp_metadata:   0
    editor_enabled:                  1
    lossless_optimization:           0
    swipe_tolerance_x:               150
    swipe_tolerance_y:               250
    local_takestamp_video_formats:   .avi|.mov
    log_max_num_line:                1000
    unlock_password_photos_with_url_param: 0
    nsfw_visible:                    1
    nsfw_blur:                       0
    nsfw_warning:                    0
    nsfw_warning_admin:              0
    map_display_direction:           1
    album_subtitle_type:             oldstyle
    upload_processing_limit:         4
    public_photos_hidden:            1
    new_photos_notification:         0

### Browser and system

Any browser, on any system.

**Comment by qwerty287** [comment]
This looks like a duplicate of https://github.com/LycheeOrg/Lychee-Docker/issues/89.

**Comment by Rackoolio** [comment]
Hi! 👋 To enable HTTPS in Lychee, you can add the following line to your `.env` file:

```env
APP_FORCE_HTTPS=true
```

This will force Lychee to use HTTPS. Make sure your server is properly configured to support HTTPS (e.g., with a valid SSL certificate).
