### ISSUE TITLE
[Question] Releases

### ISSUE THREAD

**Issue by haivala** [LycheeOrg/Lychee#1301]
Should there be release schedule like once in month or two?
I'm using releases to to upgrade my Lychee and it would be nice to have new functionalities..

**Comment by ildyria** [comment]
This would work on big project but would not work on Lychee. We have a very small team of dev, all of us have a work life and a social life on the side, which means that we don't spend all our time on Lychee.

A release schedule would not benefit anyone as there would be empty releases...

**Comment by haivala** [comment]
well that was just an suggestion about the time frame. releases as working timestamps would be nice enough.

**Comment by kamil4** [comment]
More to the point about a new release, the second part of a large refactoring just landed on `master` and I believe we should be in a good shape to have a new public release soon (once we are satisfied that wider testing of the new code by our users who track `master` does not run into any major problems).

**Comment by haivala** [comment]
Good to know! I thought the release tags were abandoned all together.

Should there be a mention about this release strategy and what is the recommended way in the readme? How about option to choose the update nags (for example in the login screen) from releases and the `master`? Now I'm wondering is the nag only show to admin?

Anyway, this issue can be closed.
