### ISSUE TITLE
Update stuck at check 

### ISSUE THREAD

**Issue by avalx** [LycheeOrg/Lychee#1304]
### Detailed description of the problem [REQUIRED]
I updated via git pull to latest version. After that I went to the web interface to finish the update, but the update is stuck at the second step (see attachment). Even if everything is 'green' the process does not continue. Any other way to finish the update, via command line perhaps?

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. git pull
2. Go to web http://server/Lychee/public/install
3. First screen shows Lychee-installer -> click on Next button
4. Second screen shows error: "Please fix the errors before going to the next step." But all the checks are 'green'
5. Clicking Re-check button does not help

**Screenshots**

![Clipboard01](https://user-images.githubusercontent.com/22810741/167099614-f7ff98c8-2556-43ec-8f42-8e72dd22e0fb.jpg)

![Clipboard02](https://user-images.githubusercontent.com/22810741/167099633-0ec2b787-3d18-4042-bea0-5da06751789a.jpg)

Error in logs table:

![Clipboard03](https://user-images.githubusercontent.com/22810741/167100988-c6b19669-93cb-4e59-ad18-f53f4fab4bd7.jpg)

### Output of the diagnostics  [REQUIRED]
*(Settings => Diagnostics or https://example.com/Diagnostics or `php artisan lychee:diagnostics`)*

Diagnostics
-----------
Warning: Dropbox import not working. dropbox_key is empty.
Info: Latest version of PHP is 8.1
Warning: Default timezone not properly set; you might experience strange results when importing photos without explicit EXIF timezone

System Information
------------------
Lychee Version (git):            master (50dacef) --  - Up to date (0 seconds ago).
DB Version:                      4.5.1

composer install:                --no-dev
APP_ENV:                         production
APP_DEBUG:                       false

System:                          Linux
PHP Version:                     8
PHP User agent:                  Lychee/4 (https://lycheeorg.github.io/)
Timezone:                        CET
Max uploaded file size:          512M
Max post size:                   512M
Max execution time:              0
MySQL Version:                   10.5.13-MariaDB

Imagick:                         1
Imagick Active:                  1
Imagick Version:                 1692
GD Version:                      2.3.2

Config Information
------------------
version:                         040501
check_for_updates:               0
sorting_photos_col:              taken_at
sorting_photos_order:            ASC
sorting_albums_col:              title
sorting_albums_order:            ASC
imagick:                         1
skip_duplicates:                 0
small_max_width:                 0
small_max_height:                360
medium_max_width:                1920
medium_max_height:               1080
lang:                            en
layout:                          2
image_overlay_type:              exif
default_license:                 CC0
compression_quality:             90
full_photo:                      1
delete_imported:                 0
Mod_Frame:                       1
Mod_Frame_refresh:               30
thumb_2x:                        1
small_2x:                        1
medium_2x:                       1
landing_page_enable:             0
landing_owner:                   My Name
landing_title:                   Aval
landing_subtitle:                Some photos
landing_facebook:                https://www.facebook.com/JohnSmith
landing_flickr:                  https://www.flickr.com/JohnSmith
landing_twitter:                 https://www.twitter.com/JohnSmith
landing_instagram:               https://instagram.com/JohnSmith
landing_youtube:                 https://www.youtube.com/JohnSmith
landing_background:              dist/cat.jpg
site_title:                      My Photo Album
site_copyright_enable:           1
site_copyright_begin:            2011
site_copyright_end:              2021
additional_footer_text:
display_social_in_gallery:       0
public_search:                   0
SL_enable:                       0
SL_for_admin:                    0
public_recent:                   0
recent_age:                      1
public_starred:                  0
downloadable:                    0
photos_wraparound:               1
map_display:                     0
zip64:                           1
map_display_public:              0
map_provider:                    OpenStreetMap.org
force_32bit_ids:                 0
map_include_subalbums:           0
update_check_every_days:         3
has_exiftool:                    1
share_button_visible:            0
import_via_symlink:              0
has_ffmpeg:                      0
location_decoding:               0
location_decoding_timeout:       30
location_show:                   1
location_show_public:            0
rss_enable:                      0
rss_recent_days:                 7
rss_max_items:                   100
prefer_available_xmp_metadata:   0
editor_enabled:                  1
lossless_optimization:           0
swipe_tolerance_x:               150
swipe_tolerance_y:               250
local_takestamp_video_formats:   .avi|.mov
log_max_num_line:                1000
unlock_password_photos_with_url_param: 0
nsfw_visible:                    0
nsfw_blur:                       0
nsfw_warning:                    0
nsfw_warning_admin:              0
map_display_direction:           1
album_subtitle_type:             oldstyle
upload_processing_limit:         4
public_photos_hidden:            1
new_photos_notification:         0
legacy_id_redirection:           1

### Browser and system
Server: Fedora 35/Apache
Client: Windows 10
Browser: any

**Comment by ildyria** [comment]
I had the same problem a few days ago.

Look at the `/var/www/html/Lychee` root, there might be a file `.NO_SECURE_KEY`. Can you please remove it ?
**do check that your encryption key is set in your `.env`**

I do not know why this happened, but in my case it solved the problem.

**Comment by avalx** [comment]
> I had the same problem a few days ago.
> 
> Look at the `/var/www/html/Lychee` root, there might be a file `.NO_SECURE_KEY`. Can you please remove it ? **do check that your encryption key is set in your `.env`**
> 
> I do not know why this happened, but in my case it solved the problem.

Thanks, that did the trick.

But I'm note sure what you mean by: **do check that your encryption key is set in your `.env`** - which parameter did you have in mind?

**Comment by ildyria** [comment]
`APP_KEY=base64:<LONG SECRET STRING>`

**Comment by avalx** [comment]
>

**Comment by avalx** [comment]
> `APP_KEY=base64:<LONG SECRET STRING>`

Ah OK, that is set.
