### ISSUE TITLE
"Attempt to read property "id" on null" error when importing new folder

### ISSUE THREAD

**Issue by dbrandesky** [LycheeOrg/Lychee#1310]
Hi all, I'm running Lychee in a Jail on a TrueNAS system (FreeBSD-based) using [this script for setup](https://github.com/danb35/freenas-iocage-lychee). Lychee is up and running and appears to be healthy. I added a mount to my iocage/jail containing Lychee in order to access some of my photos on the local storage pools. I ensured that the user running the jail/iocage is in a group with the same GID as the GID used for my photos on the host system, and I have confirmed that I can "cat" my photos from within the jail/iocage without issue, so I'm pretty sure file permissions are good.

Despite this, when I attempt to add the location to Lychee, it quickly returns the error shown in the title of this issue. This appears to be a Laravel issue which I have no idea how to address. I don't see any other errors returned so I don't really have anything else go to on.

FWIW, I'm importing the location using symlinks as I don't want to duplicate my entire photo library.

**Comment by dbrandesky** [comment]
Also, I just tested importing one of my subfolders without using symlinks, and it suceeded, so the problem appears to have something to do with symlinks.

**Comment by nagmat84** [comment]
Please use the template to report your error. Your report misses crucial information like which Lychee version your are using, etc.

**Comment by dbrandesky** [comment]
> Please use the template to report your error. Your report misses crucial information like which Lychee version your are using, etc.

I'm sorry, I've not seen a project that uses a template for issues. Where can I find the blank template?

**Comment by nagmat84** [comment]
If you submit a new issue via the button on the top right of Gihtub, you select "Bug report" in the next step and then you get an text input with some pre-filled text you need to edit. I wonder how you missed it as it is the only way to report a bug.
