### ISSUE TITLE
Lychee Web installer insists to fix errors without giving a specific error description

### ISSUE THREAD

**Issue by mm2** [LycheeOrg/Lychee#1313]
Hi,
I am getting this on TrueNAS core, in an iocage jail.  Not sure about which error I have to fix, and there are no other options in the screen.

![lychee](https://user-images.githubusercontent.com/199618/167270857-4ae5400a-ade5-478e-8e2c-bc37cef4a9e4.png)

I'm using this script https://github.com/danb35/freenas-iocage-lychee

**Comment by d7415** [comment]
Please use the supplied template.

**Comment by ildyria** [comment]
most likely related: https://github.com/LycheeOrg/Lychee/issues/1304
