### ISSUE TITLE
Settings error

### ISSUE THREAD

**Issue by sunosv** [LycheeOrg/Lychee#1329]
### Detailed description of the problem [REQUIRED]
*A clear and concise description of what the bug is.*

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1.click setting

**Screenshots**
*If applicable, add screenshots to help explain your problem.*
[![QQ截图20220514223542.png](https://sunos.top:1098/2022/05/14/9317c7c023e51.png)](https://sunos.top:1098/2022/05/14/9317c7c023e51.png)
### Output of the diagnostics  [REQUIRED]
Diagnostics
-----------
Warning: 'D:\phpEnv\www\Lychee\public\dist\user.css' does not exist or has insufficient read/write privileges.
Warning: Dropbox import not working. dropbox_key is empty.
Warning: zend.assertions is enabled although Lychee is not in debug mode. Outside of debugging, code generation for assertions is recommended to be disabled for efficiency reasons

System Information
------------------
Lychee Version (release):        4.5.1
DB Version:                      4.5.1

composer install:                --no-dev
APP_ENV:                         production
APP_DEBUG:                       false

System:                          WINNT
PHP Version:                     8.1
PHP User agent:                  Lychee/4 (https://lycheeorg.github.io/)
Timezone:                        Asia/Shanghai
Max uploaded file size:          200M
Max post size:                   256M
Max execution time:              0
MySQL Version:                   5.7.28

Imagick:                         1
Imagick Active:                  1
Imagick Version:                 1808
GD Version:                      bundled (2.1.0 compatible)

Config Information
------------------
version:                         040501
check_for_updates:               0
sorting_photos_col:              taken_at
sorting_photos_order:            ASC
sorting_albums_col:              max_taken_at
sorting_albums_order:            ASC
imagick:                         1
skip_duplicates:                 0
small_max_width:                 0
small_max_height:                360
medium_max_width:                1920
medium_max_height:               1080
lang:                            en
layout:                          1
image_overlay_type:              desc
default_license:                 none
compression_quality:             90
full_photo:                      1
delete_imported:                 0
Mod_Frame:                       1
Mod_Frame_refresh:               30
thumb_2x:                        1
small_2x:                        1
medium_2x:                       1
landing_page_enable:             0
landing_owner:                   John Smith
landing_title:                   John Smith
landing_subtitle:                Cats, Dogs & Humans Photography
landing_facebook:                https://www.facebook.com/JohnSmith
landing_flickr:                  https://www.flickr.com/JohnSmith
landing_twitter:                 https://www.twitter.com/JohnSmith
landing_instagram:               https://instagram.com/JohnSmith
landing_youtube:                 https://www.youtube.com/JohnSmith
landing_background:              dist/cat.jpg
site_title:                      Lychee v4
site_copyright_enable:           1
site_copyright_begin:            2019
site_copyright_end:              2019
additional_footer_text:
display_social_in_gallery:       0
public_search:                   0
SL_enable:                       0
SL_for_admin:                    0
public_recent:                   0
recent_age:                      1
public_starred:                  0
downloadable:                    0
photos_wraparound:               1
map_display:                     0
zip64:                           1
map_display_public:              0
map_provider:                    Wikimedia
force_32bit_ids:                 0
map_include_subalbums:           0
update_check_every_days:         3
has_exiftool:                    0
share_button_visible:            0
import_via_symlink:              0
has_ffmpeg:                      0
location_decoding:               0
location_decoding_timeout:       30
location_show:                   1
location_show_public:            0
rss_enable:                      0
rss_recent_days:                 7
rss_max_items:                   100
prefer_available_xmp_metadata:   0
editor_enabled:                  1
lossless_optimization:           0
swipe_tolerance_x:               150
swipe_tolerance_y:               250
local_takestamp_video_formats:   .avi|.mov
log_max_num_line:                1000
unlock_password_photos_with_url_param: 0
nsfw_visible:                    1
nsfw_blur:                       0
nsfw_warning:                    0
nsfw_warning_admin:              0
map_display_direction:           1
album_subtitle_type:             oldstyle
upload_processing_limit:         4
public_photos_hidden:            1
new_photos_notification:         0
legacy_id_redirection:           1

### Browser and system
windows10  Chrome

**Show logs**
2022-05-14 14:22:33 UTC -- error   -- App\Http\Middleware\FixStatusCode::handle -- 31 -- ; caused by
2022-05-14 14:22:32 UTC -- error   -- Illuminate\Routing\AbstractRouteCollection::handleMatchedRoute -- 43 -- 
2022-05-14 14:22:32 UTC -- error   -- App\Http\Middleware\FixStatusCode::handle -- 31 -- ; caused by
2022-05-14 14:22:32 UTC -- error   -- Illuminate\Routing\AbstractRouteCollection::handleMatchedRoute -- 43 -- 
2022-05-14 14:22:32 UTC -- error   -- App\Http\Middleware\FixStatusCode::handle -- 31 -- ; caused by
2022-05-14 14:22:13 UTC -- error   -- Illuminate\Routing\AbstractRouteCollection::handleMatchedRoute -- 43 -- 
2022-05-14 14:22:13 UTC -- error   -- App\Http\Middleware\FixStatusCode::handle -- 31 -- ; caused by
2022-05-14 14:21:40 UTC -- error   -- Illuminate\Routing\AbstractRouteCollection::handleMatchedRoute -- 43 -- 
2022-05-14 14:21:40 UTC -- error   -- App\Http\Middleware\FixStatusCode::handle -- 31 -- ; caused by
2022-05-14 14:21:30 UTC -- warning -- GenerateInstalledLog::up -- 18 -- Installation completed.
2022-05-14 14:21:24 UTC -- notice  -- up -- 37 -- lychee_albums does not exist!
2022-05-14 14:21:24 UTC -- notice  -- up -- 68 -- lychee_settings does not exist!

**Comment by kamil4** [comment]
So does the Settings screen not work for you at all? And is that a regression compared to an older Lychee version?

**Comment by sunosv** [comment]
> So does the Settings screen not work for you at all? And is that a regression compared to an older Lychee version?

Sorry, I didn't quite understand what you meant.

**Comment by ildyria** [comment]
1. What he means is whether you can modify the info.
2. Can you open your browser console and see if there are any messages in there?

**Comment by sunosv** [comment]
> 1. What he means is whether you can modify the info.
> 2. Can you open your browser console and see if there are any messages in there?

Yeah, I'm so stupid.I just solved this problem. This problem is related to user.css
