### ISSUE TITLE
[Enhancement] WhatsApp Share

### ISSUE THREAD

**Issue by lorvent** [LycheeOrg/Lychee#1333]
Hello,
Actually i want to raise 3 points here.

1. WhatsApp sharing... beside facebook, twitter sharing...it would be great (especially on phone), if we show option to share in whatsapp, i guess using `wa:` or using standard whatsapp share URL
2. when sharing using mobile phone default share option, it doesn't show any image, description as we get from other apps like amazon...is it possible to get something like that?
3. we have "Direct Link" option in share but clicking on `copy` button does nothing and select all the url address on mobile is bit tough.

hope you guys can guide how to achieve these or add them into Lychee in next update.

thanks.

**Comment by ildyria** [comment]
> when sharing using mobile phone default share option, it doesn't show any image, description as we get from other apps like amazon...is it possible to get something like that?

Not with the current implementation of the front end. It should be doable with Livewire though.

**Comment by nagmat84** [comment]
Or with the native Android App, I am still planning to work on.

**Comment by lorvent** [comment]
> Or with the native Android App, I am still planning to work on.

oh great thanks :)
