### ISSUE TITLE
Landing-Page Error: "Server Error or API not found"

### ISSUE THREAD

**Issue by Crome696** [LycheeOrg/Lychee#1334]
### Detailed description of the problem [REQUIRED]
Entering the Landing Page of a self hosted Lychee instance may abort due "Server Error or API not found" Error Message.

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Install Lychee 4.4.0 Release Build on a Windows 11 Computer toger with XAMMP 3.3.0 Build April 2021
2. Login on http://localhost/Lychee/public/ and create a new User
3. Use another Device (IPhone, IPad, different Windows Computer, Raspberry PI, SmartTV) in same network and enter http://<IP>/Lychee/public/
4. I see a black background on all network devices with a red animated line as header "Server Error or API not found" and thats it.

**Additional: Sometimes this also happens on the host computer (but very rare)**

**Screenshots**
Example from IPhone 11 Pro:
![grafik](https://user-images.githubusercontent.com/7686889/168738219-82ea269b-3861-436b-8c82-e3a3bbdc172c.png)

### Output of the diagnostics  [REQUIRED]

`

    Diagnostics
    -------
    Warning: Dropbox import not working. dropbox_key is empty.
    Warning: You may experience problems when uploading a photo of large size. Take a look in the FAQ for details.
    Warning: You may experience problems when uploading a photo of large size or handling many/large albums. Take a look in the FAQ for details.
    Warning: Pictures that are rotated lose their metadata! Please install Imagick to avoid that.

    System Information
    --------------
    Lychee Version (release):        4.4.0
    DB Version:                      4.4.0
    
    composer install:                --no-dev
    APP_ENV:                         production
    APP_DEBUG:                       true
    
    System:                          WINNT
    PHP Version:                     8.1
    PHP User agent:                  Lychee/4 (https://lycheeorg.github.io/)
    Max uploaded file size:          40M
    Max post size:                   40M
    Max execution time:              120
    SQLite Version:                  3.36.0
    
    Imagick:                         -
    Imagick Active:                  1
    Imagick Version:                 -
    GD Version:                      bundled (2.1.0 compatible)

    Config Information
    --------------
    version:                         040400
    check_for_updates:               0
    sorting_Photos_col:              taken_at
    sorting_Photos_order:            ASC
    sorting_Albums_col:              max_taken_at
    sorting_Albums_order:            ASC
    imagick:                         1
    skip_duplicates:                 0
    small_max_width:                 0
    small_max_height:                360
    medium_max_width:                1920
    medium_max_height:               1080
    lang:                            en
    layout:                          1
    image_overlay_type:              desc
    default_license:                 none
    compression_quality:             90
    full_photo:                      1
    delete_imported:                 0
    Mod_Frame:                       1
    Mod_Frame_refresh:               30
    thumb_2x:                        1
    small_2x:                        1
    medium_2x:                       1
    landing_page_enable:             0
    landing_owner:                   John Smith
    landing_title:                   John Smith
    landing_subtitle:                Cats, Dogs & Humans Photography
    landing_facebook:                https://www.facebook.com/JohnSmith
    landing_flickr:                  https://www.flickr.com/JohnSmith
    landing_twitter:                 https://www.twitter.com/JohnSmith
    landing_instagram:               https://instagram.com/JohnSmith
    landing_youtube:                 https://www.youtube.com/JohnSmith
    landing_background:              dist/cat.jpg
    site_title:                      Lychee v4
    site_copyright_enable:           1
    site_copyright_begin:            2019
    site_copyright_end:              2019
    additional_footer_text:          
    display_social_in_gallery:       0
    public_search:                   0
    SL_enable:                       0
    SL_for_admin:                    0
    public_recent:                   0
    recent_age:                      1
    public_starred:                  0
    downloadable:                    0
    photos_wraparound:               1
    map_display:                     0
    zip64:                           1
    map_display_public:              0
    map_provider:                    Wikimedia
    force_32bit_ids:                 0
    map_include_subalbums:           0
    update_check_every_days:         3
    has_exiftool:                    0
    share_button_visible:            0
    import_via_symlink:              0
    has_ffmpeg:                      0
    location_decoding:               0
    location_decoding_timeout:       30
    location_show:                   1
    location_show_public:            0
    rss_enable:                      0
    rss_recent_days:                 7
    rss_max_items:                   100
    prefer_available_xmp_metadata:   0
    editor_enabled:                  1
    lossless_optimization:           0
    swipe_tolerance_x:               150
    swipe_tolerance_y:               250
    local_takestamp_video_formats:   .avi|.mov
    log_max_num_line:                1000
    unlock_password_photos_with_url_param: 0
    nsfw_visible:                    1
    nsfw_blur:                       0
    nsfw_warning:                    0
    nsfw_warning_admin:              0
    map_display_direction:           1
    album_subtitle_type:             oldstyle
    upload_processing_limit:         4
    public_photos_hidden:            1
    new_photos_notification:         0

About
`

### Browser and system

- AMD Ryzen 5 Minis Forum PC  16GB RAM -  Windows 11 - Mozilla Firefox Build 100.0.1 64-Bit
- IPhone 11 Pro  - IOS 15.x - Safari Browser latest
- IPad Model 2020 - IOS 15.x - Safari Browser latest
- Acer Nitro 5 32GB RAM - Windows 11 Pro -  Mozilla Firefox Build 100.0.1 64-Bit

**Comment by nagmat84** [comment]
Considering the URL in your example `.../public/`, this sounds like a configuration error. Although the public files of the web application reside in the folder `public` the URL should not use a `public` as its final path component

Have you followed the installation guide closely? Does the web root of the configuration of your web server point to the `pubic` folder? Have you configured the URL in the `.env.` file?

**Comment by Crome696** [comment]
I´m fairly new to this topic. I´ve installed Apache, copied the package to the folder and checked how to install\enable extensions, database and so on. When i enter http://localhost/lychee/ i get following issue:
![grafik](https://user-images.githubusercontent.com/7686889/168742614-b637312f-1d26-46eb-8476-e288c7765abd.png)

`Have you configured the URL in the .env. file?` I have not changed any path there. Might there be the issue? I use this Gallery on my personal network and not thoguth about the endpoint setting yet.

**Comment by nagmat84** [comment]
Please follow this installation guide: https://lycheeorg.github.io/docs/#installation It is simply not sufficient to throw Lychee into the root folder of your web server. If the server runs in your local network and you have full control over the server, I recommend the installation via GIT from the master branch.

**Comment by ildyria** [comment]
> When i enter http://localhost/lychee/ i get following issue: ![grafik](https://user-images.githubusercontent.com/7686889/168742614-b637312f-1d26-46eb-8476-e288c7765abd.png)

Have you tried... clicking on `here` in the said page?  :)

**Comment by Crome696** [comment]
> > When i enter http://localhost/lychee/ i get following issue: ![grafik](https://user-images.githubusercontent.com/7686889/168742614-b637312f-1d26-46eb-8476-e288c7765abd.png)
> 
> Have you tried... clicking on `here` in the said page? :)

Hi, of course this were the first i have seen when i installed lychee. When clicking there it routes me to /public page.
On Localhost *everything* works but once i tried to connect from network it started to make trouble.

I gave up on finding the issue. I´m not experienced as much it seems to require to install it on a local system. I´ve installed the Docker-Version now and getting different issues that after i set up the lychee user i get access denied exceptions. Will try to find out how to solve it else may need to find a replacement.

**Comment by nagmat84** [comment]
It makes me sad to hear that you will have to look for an alternative eventually. Please forget about @ildyria comment as it was not helpful.

The problem is rather obvious. The directory structure of Lychee looks like this

```
(root)
   |-- app
   |-- public
   |-- vendor
   |-- ...
```

The problem occurs, because the entry point of your web-server points to the root folder of Lychee, but it must point to the `public` folder. That's also the reason why you have to type the additional `public` into all URLs which must not be there and causes the API not found error.

Have you tried to follow the installation guide linked in https://github.com/LycheeOrg/Lychee/issues/1334#issuecomment-1128464639?

If you still have problems, could you post the configuration of your web-server and your `.env` file? Then we should be able to tell you what you need to change.

**Comment by ildyria** [comment]
No answer was provided. Closing.
