### ISSUE TITLE
Install fails with MySQL Error No : 1064

### ISSUE THREAD

**Issue by spinone** [LycheeOrg/Lychee#1344]
Installing on my web host using softaculous results in an SQL syntax error as follows:
The following errors were found :
Could not make the query numbered : 22
MySQL Error No : 1064
MySQL Error : You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'json NOT NULL, `attestation_type` json NOT NULL, `trust_path` json NOT NULL,' at line 9
Several other gallery options install without error.
I like the look of Lychee - any idea what's going wrong?

**Comment by ildyria** [comment]
Please use the template provided. Help us help you.

**Comment by ildyria** [comment]
No info were provided over a month. Closing.
