### ISSUE TITLE
EXIF data on iOS uploaded photos is missing

### ISSUE THREAD

**Issue by TobiasDax** [LycheeOrg/Lychee#1355]
### Detailed description of the problem [REQUIRED]
*A clear and concise description of what the bug is.*
Wien i Upload photos Tommy Lychee instance  Form my iPhone or iPad Pro all the exif data is stripped And the Image ist Shopping up without Any informations.

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Installed the https://github.com/linuxserver/docker-lychee docker on my unraid Server 
2. Took some photos on my iPhone 
3. Uploaded the photos Form my iPhone through the Web Ui
4. Saw No exif data

**Screenshots**
An Image Top Test the Problem 
![1DC5E0A3-04AF-41AA-A93C-582FE0A234A8](https://user-images.githubusercontent.com/42605856/171498878-b73499c3-8c8a-4725-9bd3-96b1002cd7d7.jpeg)

### Output of the diagnostics  [REQUIRED]
*(Settings => Diagnostics or https://example.com/Diagnostics or `php artisan lychee:diagnostics`)*
´´´

System Information
    --------------
    Lychee Version (release):        4.4.0
    DB Version:                      4.4.0
    
    composer install:                --no-dev
    APP_ENV:                         production
    APP_DEBUG:                       false
    
    System:                          Linux
    PHP Version:                     8
    PHP User agent:                  Lychee/4 (https://lycheeorg.github.io/)
    Max uploaded file size:          2000M
    Max post size:                   2000M
    Max execution time:              200
    MySQL Version:                   10.5.16-MariaDB
    
    Imagick:                         1
    Imagick Active:                  1
    Imagick Version:                 1808
    GD Version:                      bundled (2.1.0 compatible)

Speicherplatz-Nutzung abrufen

    Config Information
    --------------
    version:                         040400
    check_for_updates:               0
    sorting_Photos_col:              taken_at
    sorting_Photos_order:            ASC
    sorting_Albums_col:              max_taken_at
    sorting_Albums_order:            ASC
    imagick:                         1
    skip_duplicates:                 1
    small_max_width:                 0
    small_max_height:                360
    medium_max_width:                1920
    medium_max_height:               1080
    lang:                            de
    layout:                          1
    image_overlay_type:              exif
    default_license:                 CC-BY-NC-ND-4.0
    compression_quality:             90
    full_photo:                      1
    delete_imported:                 0
    Mod_Frame:                       1
    Mod_Frame_refresh:               30
    thumb_2x:                        1
    small_2x:                        1
    medium_2x:                       1
    landing_page_enable:             0
    landing_owner:                   Jobi 2022
    landing_title:                   JOBI 2022
    landing_subtitle:                Unser Freudenfest
    landing_facebook:                
    landing_flickr:                  
    landing_twitter:                 
    landing_instagram:               
    landing_youtube:                 
    landing_background:              dist/cat.jpg
    site_title:                      Lychee v4
    site_copyright_enable:           1
    site_copyright_begin:            2019
    site_copyright_end:              2019
    additional_footer_text:          
    display_social_in_gallery:       0
    public_search:                   0
    SL_enable:                       0
    SL_for_admin:                    0
    public_recent:                   0
    recent_age:                      1
    public_starred:                  0
    downloadable:                    0
    photos_wraparound:               1
    map_display:                     1
    zip64:                           1
    map_display_public:              1
    map_provider:                    Wikimedia
    force_32bit_ids:                 0
    map_include_subalbums:           1
    update_check_every_days:         3
    has_exiftool:                    1
    share_button_visible:            0
    import_via_symlink:              0
    has_ffmpeg:                      1
    location_decoding:               1
    location_decoding_timeout:       30
    location_show:                   1
    location_show_public:            1
    rss_enable:                      0
    rss_recent_days:                 7
    rss_max_items:                   100
    prefer_available_xmp_metadata:   0
    editor_enabled:                  1
    lossless_optimization:           0
    swipe_tolerance_x:               150
    swipe_tolerance_y:               250
    local_takestamp_video_formats:   .avi|.mov
    log_max_num_line:                1000
    unlock_password_photos_with_url_param: 0
    nsfw_visible:                    0
    nsfw_blur:                       0
    nsfw_warning:                    0
    nsfw_warning_admin:              0
    map_display_direction:           1
    album_subtitle_type:             oldstyle
    upload_processing_limit:         4
    public_photos_hidden:            1
    new_photos_notification:         0
    ´´´

**Comment by kamil4** [comment]
Is this an original, straight out-of-camera photo? Just to confirm, the file size is 3188952, md5 sum is 9fe2e495c36aacc90bcc0af4a12ac5d2, sha1 sum is 483536fb6ce1436fd8539299b5b45dbc05f49aa2?

I'm asking because indeed it looks like Exiftool is unable to extract any useful metadata out of this file. Does your phone or the iPad display anything of interest for this file (like the aperture, shutter speed, or ISO)?

**Comment by nagmat84** [comment]
On Gitter you said that the problem is with an image in [HEIC-format](https://en.m.wikipedia.org/wiki/High_Efficiency_Image_File_Format). But you uploaded an ordinary JPEG here. Please upload the original image, not a JPEG extracted from the HEIC image.

**Comment by kamil4** [comment]
Do we even support HEIF/HEIC files in Lychee though? I don't see any indication of that...

**Comment by TobiasDax** [comment]
I have shot this image yesterday and uploaded it straight to GitHub (and Lychee) through the iOS file manager.

might be a problem with iOS and automatic conversion to jpeg? Because in my devices I have all the relevant infos and the phone is set to take pictures in heic.

I will do some googling 


Edit:
Oh, this seems to be some native iOS „feature“
Sorry to bother you with it, should have googled before. Just had never ran into that issue before.

https://stackoverflow.com/questions/16297730/image-upload-from-iphone-strips-exif-data

**Comment by d7415** [comment]
> Do we even support HEIF/HEIC files in Lychee though? I don't see any indication of that...

I *think* we support them as if they were RAW (i.e. we convert them but keep the original) but it's been a while.

**Comment by TobiasDax** [comment]
yeah i thought i read some thing in other issues about HEIC supprot, but manually uploading a heic file does not work for me either ;)

**Comment by kamil4** [comment]
According to https://caniuse.com/heif, no browser can display them at the moment. So, effectively, we need to treat them like RAW files. You can try adding the file extension to `raw_formats` (https://lycheeorg.github.io/docs/settings.html#raw_formats) and see if that helps. ImageMagick should then convert the original file to JPEG and use that for display purposes. I'm curious if any metadata can be extracted though. If it doesn't work, why don't you attach a sample image and we can see what it would take...

**Comment by TobiasDax** [comment]
adding the raw_formats of .heic workes great on pc.
(ios still converts on export)
but on my desktop it now imports the HEIC, converts to JPG and keeps ALL the exif information perfectly

**Comment by kamil4** [comment]
That's great to hear about the PC uploads. I wonder if there's something we need to do to indicate to the iOS browsers that we can accept `.heic` files...

**Comment by ZhangTianrong** [comment]
I have included `.heic` in the list of raw formats and then I try to import photos with symlink. However, all heic files leads to `Could move/copy/symlink source file to final destination` (I guess a "not" is missing in the error message).
