### ISSUE TITLE
[Enhancement] Public by default

### ISSUE THREAD

**Issue by Compizfox** [LycheeOrg/Lychee#1363]
Would it be possible to have pictures and albums be public by default? I use Lychee as a public photo album, and it's quite nuisance to manually set everything to public one-by-one.

**Comment by kamil4** [comment]
One enhancement along these lines that we've talked about in the past was (possibly optional) inheriting of visibility settings from the parent album when creating a new subalbum or recursively applying changes of visibility settings of an album to its subalbums. That wouldn't change anything when creating new top-level albums though.

**Comment by Compizfox** [comment]
That sounds reasonable in its own right.

But indeed, I still see the merit of having a default public setting for new top-level albums (as well as unsorted pictures!).

**Comment by ildyria** [comment]
This does not sound that hard to add to Lychee.
I would actually see it as a nice project for someone who wants to get a bit into the code without diving into the complex parts.
