### ISSUE TITLE
PHPExif\Exif::getLatitude(): Return value must be of type float|false, string returned

### ISSUE THREAD

**Issue by ryansechrest** [LycheeOrg/Lychee#1367]
### Detailed description of the problem [REQUIRED]
I'm trying to upload photos by importing them from a directory on the server.

Once the upload starts, there is an error for each picture that was attempted to be uploaded:

```
App\Metadata\Extractor::createFromFile -- 209 -- PHPExif\Exif::getLatitude(): Return value must be of type float|false, string returned; caused by
2022-06-12 04:33:47 UTC -- error   -- PHPExif\Exif::getLatitude -- 1020 -- PHPExif\Exif::getLatitude(): Return value must be of type float|false, string returned
```

All of this worked fine prior to upgrading Lychee to the latest version.

### Steps to reproduce the issue
1. Click the + in the top right corner
2. Select "Import from Server"
3. Select a directory with a photo
4. See error in dialog box

### Output of the diagnostics  [REQUIRED]
    Diagnostics
    -------
    Warning: Dropbox import not working. dropbox_key is empty.
    Warning: You may experience problems when uploading a photo of large size. Take a look in the FAQ for details.
    Warning: You may experience problems when uploading a photo of large size. Take a look in the FAQ for details.
    Warning: You may experience problems when uploading a photo of large size or handling many/large albums. Take a look in the FAQ for details.
    Info: Latest version of PHP is 8.1
    Warning: Default timezone not properly set; you might experience strange results when importing photos without explicit EXIF timezone

    System Information
    --------------
    Lychee Version (git):            master (8511ea7) --  - Up to date (42 minutes ago).
    DB Version:                      4.5.1
    
    composer install:                --no-dev
    APP_ENV:                         production
    APP_DEBUG:                       false
    
    System:                          Linux
    PHP Version:                     8
    PHP User agent:                  Lychee/4 (https://lycheeorg.github.io/)
    Timezone:                        UTC
    Max uploaded file size:          2M
    Max post size:                   15M
    Max execution time:              30
    MySQL Version:                   8.0.29-0ubuntu0.20.04.3
    
    Imagick:                         1
    Imagick Active:                  1
    Imagick Version:                 1690
    GD Version:                      bundled (2.1.0 compatible)

    Config Information
    --------------
    version:                         040501
    check_for_updates:               1
    sorting_photos_col:              taken_at
    sorting_photos_order:            ASC
    sorting_albums_col:              created_at
    sorting_albums_order:            DESC
    imagick:                         1
    skip_duplicates:                 0
    small_max_width:                 0
    small_max_height:                360
    medium_max_width:                1920
    medium_max_height:               1080
    lang:                            en
    layout:                          1
    image_overlay_type:              desc
    default_license:                 reserved
    compression_quality:             90
    full_photo:                      1
    delete_imported:                 0
    Mod_Frame:                       1
    Mod_Frame_refresh:               30
    thumb_2x:                        1
    small_2x:                        1
    medium_2x:                       1
    landing_page_enable:             0
    landing_owner:                   
    landing_title:                   
    landing_subtitle:                
    landing_facebook:                
    landing_flickr:                  
    landing_twitter:                 
    landing_instagram:               
    landing_youtube:                 
    landing_background:              dist/cat.jpg
    site_title:                      Photos
    site_copyright_enable:           0
    site_copyright_begin:            2020
    site_copyright_end:              2022
    additional_footer_text:          
    display_social_in_gallery:       0
    public_search:                   0
    SL_enable:                       0
    SL_for_admin:                    0
    public_recent:                   0
    recent_age:                      0
    public_starred:                  0
    downloadable:                    0
    photos_wraparound:               1
    map_display:                     1
    zip64:                           1
    map_display_public:              0
    map_provider:                    Wikimedia
    force_32bit_ids:                 0
    map_include_subalbums:           1
    update_check_every_days:         3
    has_exiftool:                    0
    share_button_visible:            0
    import_via_symlink:              0
    has_ffmpeg:                      0
    location_decoding:               1
    location_decoding_timeout:       30
    location_show:                   1
    location_show_public:            0
    rss_enable:                      0
    rss_recent_days:                 7
    rss_max_items:                   100
    prefer_available_xmp_metadata:   0
    editor_enabled:                  1
    lossless_optimization:           0
    swipe_tolerance_x:               150
    swipe_tolerance_y:               250
    local_takestamp_video_formats:   .avi|.mov
    log_max_num_line:                1000
    unlock_password_photos_with_url_param: 0
    nsfw_visible:                    0
    nsfw_blur:                       0
    nsfw_warning:                    0
    nsfw_warning_admin:              0
    map_display_direction:           1
    album_subtitle_type:             oldstyle
    upload_processing_limit:         4
    public_photos_hidden:            0
    new_photos_notification:         0
    legacy_id_redirection:           1

### Browser and system
Brave 1.39.x on macOS Monterey.

**Comment by kamil4** [comment]
Could you attach a sample photo that triggers the problem? I'm having difficulty reproducing it here...

Until we figure out what might be going on, you may be able to work it around by editing the file `Lychee/vendor/lychee-org/php-exif/lib/PHPExif/Exif.php`; in line 1014, remove `: float|false` (note that the colon needs to be removed as well). For reference, here's that line highlighted in the source repo: https://github.com/LycheeOrg/php-exif/blob/baf5c7759d56e7be37746f4d3da60c438a9bd151/lib/PHPExif/Exif.php#L1014

**Comment by ryansechrest** [comment]
@kamil4 Sure, photo attached. I'll confirm whether removing the return type resolves the issue.

![photo](https://user-images.githubusercontent.com/877536/173217306-3bca55dc-097f-49e2-83b1-62a7e1b66134.jpg)

**Comment by ryansechrest** [comment]
@kamil4 Removing the return type leads to this:

```
App\Metadata\Extractor::createFromFile -- 209 -- Cannot assign string to property App\Metadata\Extractor::$latitude of type ?float
2022-06-12 05:36:26 UTC -- error   -- PHPExif\Exif::getLatitude -- 1020 -- PHPExif\Exif::getLatitude(): Return value must be of type float|false, string returned
```

For testing, I then cast the return to a float:

```
/**
 * Returns latitude, if it exists
 * 
 * @return float|boolean
 */
public function getLatitude()
{
    if (!isset($this->data[self::LATITUDE])) {
        return false;
    }

    return (float) $this->data[self::LATITUDE];
}
```

And had to do the same for longitude.

The image now imported, but the location isn't right.

**Comment by qwerty287** [comment]
Can reproduce after disabling exiftool.
@ryansechrest if you can install `exiftool` on your server, you can set `has_exiftool` in the advanced settings to `1`, then it should work (but that's only a workaround).

This is a bug in the Imagick parser/mapper. The location data of the photo in raw format is `48/1, 94983333/10000000, 0/1`, and this doesn't match the regex in https://github.com/LycheeOrg/php-exif/blob/baf5c7759d56e7be37746f4d3da60c438a9bd151/lib/PHPExif/Mapper/ImageMagick.php#L231. But actually it should return `false` then...

**Comment by ryansechrest** [comment]
@qwerty287 Thank you, this worked out well.

For anyone else trying this on Ubuntu, you can just run `apt install exiftool`, which will install `libimage-exiftool-perl`.

I also had to whitelist `/bin/exiftool` in my virtual host file due to `open_basedir` restriction:

```
phpIniOverride  {
  php_admin_value open_basedir "/tmp:/bin/exiftool:$VH_ROOT"
}
```

**Comment by kamil4** [comment]
I've got a draft fix: https://github.com/LycheeOrg/php-exif/pull/44
