### ISSUE TITLE
[Enhancement] Direct link to MP4s no longer result in Discord Embeds

### ISSUE THREAD

**Issue by Rami-Pastrami** [LycheeOrg/Lychee#1378]
Not sure if a bug since this was previously working, but it does not seem to be working now.

In Discord, direct links to MP4s will be embedded into the chat itself so long as the format is h264 and that the file is under 100mb. However, I noticed that recently, posting the MP4 link from lychee into discord no longer embeds any content at all, it only appears as a link. I am unsure what the cause of change is currently but wanted to raise an issue here if anyone had any ideas.

I confirmed the MP4 links are direct and publicly available (no login necessary)

**Comment by kamil4** [comment]
I can't imagine how any Lychee updates could trigger such a change in behavior. If as you say you are using direct links, then Lychee should simply be out of the picture at this point. Could it be due to a change in the webserver configuration?

If you could post specific examples, we may be able to have a look...

**Comment by ildyria** [comment]
I don't think this is Lychee related. If you post the URL of the video xxx/big/xxx.mp4 it should not matter that it is from Lychee or anywhere else.

**Comment by nagmat84** [comment]
This rather sound like a change in Discord.

**Comment by Rami-Pastrami** [comment]
After dealing with the issue for quite a while, I think I actually just stumbled on the culprit!

My site goes through Cloudflare, and i had a firewall rule set to disallow bot crawling. Issue went away as soon as that rule was lifted.

as such, Lychee had nothing to do with this issue so I will close this issue. Hopefully this will help other people in the future
