### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by hiensarahly** [LycheeOrg/Lychee#1381]
How to remove the footer line “All images copyright by John Smith”?

Can Lychee made be to a light interface?

**Comment by ildyria** [comment]
1. Settings -> bottom -> More Settings -> change the configuration.
2. There was work in progress to be able to enable any theme: https://github.com/LycheeOrg/Lychee-front/pull/269  
  I also know that @SerenaButler  has a light seem that you may be interested in using if he shares his `user.css`. :)

**Comment by hiensarahly** [comment]
hi thank u! @ildyria 
may you pls share light theme? i’d really. appreciate it. @SerenaButler

**Comment by qwerty287** [comment]
See https://github.com/LycheeOrg/Lychee/issues/2086

**Comment by hiensarahly** [comment]
it works great, thx!
