### ISSUE TITLE
syncing an altered file results in a duplicated entry

### ISSUE THREAD

**Issue by verymilan** [LycheeOrg/Lychee#1383]
### Detailed description of the problem [REQUIRED]
When trying to sync an altered image with symlinks enabled, i end up in a duplicated entry in Lychee. The old one remains as preview and possibly lowres download (not checked, but:) – but when selected, it opens the new version of the image and the ghostbuster task removed only 4 entries.

````
Lychee (git)-[tags/v4.4.0] # sudo -u www-data php artisan lychee:ghostbuster 1 0


Also parsing database for pictures where the url does not point to an existing file.
This may modify the database.

This is not a drill! Let's delete those files!

removed file: thumb/bff2a6797a77cc9f09d4a9e653bbd5d4.jpeg
removed file: thumb/bff2a6797a77cc9f09d4a9e653bbd5d4@2x.jpeg
removed file: medium/bff2a6797a77cc9f09d4a9e653bbd5d4.jpg
removed file: big/bff2a6797a77cc9f09d4a9e653bbd5d4.jpg

4 pictures have been deleted.
````
 
### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Add photo to folder to be synced (in my case Nextcloud)
2. Start the sync with `--import_via_symlink=1 --skip_duplicates=1`
2.1 Lychee now shows the added image
3. ~~Add altered version~~ replace image with altered version of the same photo ~~to~~ in the directory to sync
4. Start the sync with `--import_via_symlink=1 --skip_duplicates=1`
4.1 The new image now shows as new image and when clicking on the old image inside Lychee

### Output of the diagnostics  [REQUIRED]
````
Diagnostics
    -------
    Warning: Dropbox import not working. dropbox_key is empty.



    System Information
    --------------
    Lychee Version (git):            No git data found.
    DB Version:                      4.4.0
    
    composer install:                --no-dev
    APP_ENV:                         production
    APP_DEBUG:                       false
    
    System:                          Linux
    PHP Version:                     8.1
    PHP User agent:                  Lychee/4 (https://lycheeorg.github.io/)
    Max uploaded file size:          100M
    Max post size:                   100M
    Max execution time:              3600
    PostgreSQL Version:              PostgreSQL 13.7 (Debian 13.7-0+deb11u1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
    
    Imagick:                         1
    Imagick Active:                  1
    Imagick Version:                 1691
    GD Version:                      2.3.0
    
    Lychee total space:              3.17 GB
    Upload folder space:             3.10 GB
    System total space:              316.20 GB
    System free space:               205.96 GB (65%)
 ````

### Browser and system
Vivaldi on macOS (because Firefox uploads got stuck)
Lychee v4.4.0

**Comment by kamil4** [comment]
An interesting experiment (thanks for sharing!) but, at the end of the day, not that surprising, considering that what you tried is currently not supported.

But yeah, I agree that it would be good to add support for it, and that it's a relatively low-hanging fruit (we don't need to add any new functionality; we "just" need to reuse the pieces that are already there).

**Comment by d7415** [comment]
The main problem I see is whether we know internally what's a symlink and not. We don't want to replace a file just because it has the same filename, so we use the hash. That leads the the apparently strange behaviour here. We'd need to know that it's definitely intended as a replacement, not an additional file.

**Comment by kamil4** [comment]
Yeah, in my comment I wasn't even thinking about the "sync" feature but about adding an explicit new GUI feature to "replace the image" (working like image upload) and/or "rescan metadata / regenerate intermediate sizes" (I believe we have this functionality already via the CLI, but only for photos that are _missing_ the relevant data).

**Comment by d7415** [comment]
Closing as superseded by #1384.
