### ISSUE TITLE
Unable to adjust sharing

### ISSUE THREAD

**Issue by DaGoldOne** [LycheeOrg/Lychee#1390]
When attempting to modify sharing settings an error appears 
'Error Internal Server Error - Internal Server Error 

### Steps to reproduce the issue
Open an album
Click the sharing icon in the top right hand side of the page 
Error appears at the top of the screen
or
*(Settings => Sharing) gives the same error

**Screenshots**
![image](https://user-images.githubusercontent.com/49998771/176987086-d2dbfea0-bcad-4244-9925-6fd2d91dbcb4.png)

### Logs: The following are in the logs
2022-07-01 04:27:42 UTC -- error -- App\Actions\Sharing\ListShare::App\Actions\Sharing{closure} -- 54 -- App\Actions\Sharing\ListShare::App\Actions\Sharing{closure}(): Argument [#1](https://github.com/issues?q=1+user%3ALycheeOrg) ($album) must be of type App\DTO\BreadCrumbData, stdClass given, called in /var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php on line 245

### Output of the diagnostics  [REQUIRED]
*(Settings => Diagnostics or https://example.com/Diagnostics or `php artisan lychee:diagnostics`)*

    Diagnostics
    -------
    Warning: Dropbox import not working. dropbox_key is empty.

    System Information
    --------------
    Lychee Version (git):            master (46ae70b) -- Up to date (0 seconds ago).
    DB Version:                      4.5.1
    
    composer install:                --no-dev
    APP_ENV:                         production
    APP_DEBUG:                       false
    
    System:                          Linux
    PHP Version:                     8.1.5
    PHP User agent:                  Lychee/4 (https://lycheeorg.github.io/)
    Timezone:                        America/New_York
    Max uploaded file size:          4096M
    Max post size:                   4096M
    Max execution time:              10800
    MySQL Version:                   10.8.3-MariaDB-1:10.8.3+maria~jammy
    
    Imagick Available:               1
    Imagick Enabled:                 1
    Imagick Version:                 1691
    GD Version:                      2.3.0

    Lychee total space:              148.68 MB
    Upload folder space:             8.00 B
    System total space:              29.36 GB
    System free space:               5.42 GB (18%)

    Config Information
    --------------
    version:                         040501
    check_for_updates:               0
    sorting_photos_col:              taken_at
    sorting_photos_order:            ASC
    sorting_albums_col:              max_taken_at
    sorting_albums_order:            ASC
    imagick:                         1
    skip_duplicates:                 0
    small_max_width:                 0
    small_max_height:                360
    medium_max_width:                1920
    medium_max_height:               1080
    lang:                            en
    layout:                          1
    image_overlay_type:              desc
    default_license:                 CC-BY-NC-SA-4.0
    compression_quality:             90
    full_photo:                      1
    delete_imported:                 0
    Mod_Frame:                       1
    Mod_Frame_refresh:               30
    thumb_2x:                        1
    small_2x:                        1
    medium_2x:                       1
    landing_page_enable:             0
    landing_owner:                  xxxxxxxxx
    landing_title:                   xxxxxx
    landing_subtitle:                Cats, Dogs & Humans Photography
    landing_facebook:                https://www.facebook.com/JohnSmith
    landing_flickr:                  https://www.flickr.com/JohnSmith
    landing_twitter:                 https://www.twitter.com/JohnSmith
    landing_instagram:               https://instagram.com/JohnSmith
    landing_youtube:                 https://www.youtube.com/JohnSmith
    landing_background:              dist/cat.jpg
    site_title:                      xxxxxxxxxxs Photo Sharing
    site_copyright_enable:           1
    site_copyright_begin:            2019
    site_copyright_end:              2022
    additional_footer_text:          xxxxxxxxx
    display_social_in_gallery:       0
    public_search:                   0
    SL_enable:                       0
    SL_for_admin:                    0
    public_recent:                   0
    recent_age:                      1
    public_starred:                  0
    downloadable:                    0
    photos_wraparound:               1
    map_display:                     0
    zip64:                           1
    map_display_public:              0
    map_provider:                    Wikimedia
    force_32bit_ids:                 0
    map_include_subalbums:           0
    update_check_every_days:         3
    has_exiftool:                    1
    share_button_visible:            0
    import_via_symlink:              0
    has_ffmpeg:                      1
    location_decoding:               0
    location_decoding_timeout:       30
    location_show:                   1
    location_show_public:            0
    rss_enable:                      0
    rss_recent_days:                 7
    rss_max_items:                   100
    prefer_available_xmp_metadata:   0
    editor_enabled:                  1
    lossless_optimization:           0
    swipe_tolerance_x:               150
    swipe_tolerance_y:               250
    local_takestamp_video_formats:   .avi|.mov
    log_max_num_line:                1000
    unlock_password_photos_with_url_param: 0
    nsfw_visible:                    1
    nsfw_blur:                       0
    nsfw_warning:                    0
    nsfw_warning_admin:              0
    map_display_direction:           1
    album_subtitle_type:             oldstyle
    upload_processing_limit:         4
    public_photos_hidden:            1
    new_photos_notification:         0
    legacy_id_redirection:           1

About
### Browser and system

Firefox ,installed Lychee via Docker-Compose using :Dev tag 
I also recently pulled an new image using docker compose

**Comment by d7415** [comment]
Thanks for the report @DaGoldOne! This should now be fixed in master.
