### ISSUE TITLE
[Documentation] Would it be possible to enhance https://lycheeorg.github.io/docs/installation.html and show copy/paste-able instructions?

### ISSUE THREAD

**Issue by rubyFeedback** [LycheeOrg/Lychee#1398]
Hey guys,

I visited: https://lycheeorg.github.io/docs/installation.html

The instructions are a bit long, though. I have PHP, mysql, postgresql, sqlite etc... all
installed already.

Would it be possible for you guys to also add a copy/paste-able instruction set? Something
that should work by default as much as possible; it can be assumed that PHP, mysql 
etc.. all works already, so the instructions only have to be for lychee.

You can reason that the information is already available on the website, but I would
really like a super-condensed variant that I can mostly just copy/paste when possible.
For instance, the website says PHP needs these add-ons:

    PHP >= 8.0 with these PHP extensions:
    bcmath
    ctype
    dom
    exif
    fileinfo
    filter
    gd
    imagick (optional — to generate better thumbnails)
    json
    libxml
    mbstring
    openssl
    pcre
    PDO
    Phar
    SimpleXML
    tokenizer
    xml
    xmlwriter

And so forth. But I'd just like the condensed information for lychee, ideally via a 
copy/pasteable instruction set, ideally from the commandline (I use linux).

Right now the instructions have a lot of explanations, which is fine, but I am
only interested in to get-it-to-work and only look back when errors happen,
if that makes sense.

**Comment by d7415** [comment]
Hi,

There are a few bits here.

> it can be assumed that PHP, mysql, etc.. all works already,

That stuff is largely skimmed over. If you're confident you have the right requirements, you can skip to "Installing Lychee", but we need to provide that information.

> But I'd just like the condensed information for lychee, 

So, sticking to the list of PHP modules, Lychee needs all of those. Some will probably be installed by default, others may not be. That will depend on many things we don't know.

> ... ideally via a copy/pasteable instruction set,

This would depend on your operating system/distribution for the required commands and for the package names. Unfortunately it's just not that simple. We would need to include separate instructions for each distro (Debian, Fedora, etc.) And that's without considering other operating systems.

The closest we have to a "quick start" is probably Docker, but even then if you start without reading first, you may bite yourself (e.g. starting in sqlite when you wanted mariadb/mysql/postgres).
