### ISSUE TITLE
[Enhancement] Change or add user admin

### ISSUE THREAD

**Issue by RoiArthurB** [LycheeOrg/Lychee#1399]
*Explain in a few words which functionality or improvements you would like to see in Lychee.*
Since v3, I share a Lychee instance with all my family. However, since I moved it to Lychee v4 everyone have a little account (which make it very nice for all of us btw).

Unfortunately, the primary account (and then, admin one) is the one linked to my parent's account (not IT). 

I'd like to know if there's a way to move admin privilege from this first account to my personal one (i.e. regular user on v4). I think it's possible to do by manipulating DB (changing the `username` and `password` in the `lychee.configs` by mine from the `lychee.users`), but I'm really not sure. 
I also think it would be a great enhancement for the entire application, regardless of my personal need :)

**Comment by ildyria** [comment]
> DB (changing the username and password in the lychee.configs by mine from the lychee.users),

Nah, not like that, this entry is no longer used.

The id of the user determine if it is admin or not. So for you the solution would be:
1. change the DB by moving their ID to another unused number (e.g. 5).
2. make sure their username is update to clear.
3. move all the pictures with owner = null or owner = 0 to owner = 5
4. move all the picture associated to your user id to  owner = 0
5. remove your user.
6. do an admin reset.

**Comment by RoiArthurB** [comment]
Couldn't it be an integrated feature? All this process seems very tricky 😅😅😅

**Comment by ildyria** [comment]
Access rights need a major overhaul. I would rather tackle it all at once (and I'm pretty sure @nagmat84 agrees).
That is why I gave you a "recipe" to temporarily fix your problem. :)

**Comment by nagmat84** [comment]
Right. I still envision a much better replacement of the whole authentication scheme by something which uses more of the Laravel framework than our home-brewed session management does at the moment. Probably, such a feature can be implemented much more easier then.

**Comment by ildyria** [comment]
Done thanks to @qwerty287

**Comment by RoiArthurB** [comment]
@ildyria I try to check @qwerty287 's work but can't see/found/understand what he did to manage it nor what steps to follow to achieve it.
Could you help me on this please 🙏

**Comment by ildyria** [comment]
You need to use the command line.
`php artisan lychee:create_user --help` should give you the necessary info.
