### ISSUE TITLE
Uninitialized string offset 0 Error on Photo Upload

### ISSUE THREAD

**Issue by romleinster** [LycheeOrg/Lychee#1406]
I'm trying to upload a .jpg file and after it fails I get these errors in the logs:
2022-07-15 19:57:16 UTC -- error   -- PHPExif\Mapper\ImageMagick::mapRawData -- 188 -- Uninitialized string offset 0
2022-07-15 19:57:16 UTC -- error   -- App\Metadata\Extractor::createFromFile -- 117 -- Uninitialized string offset 0; caused by

I've tried copying the file, renaming the files, and stripping metadata from the file using windows explorer but same error every time. This is the only file that gives this error, I've otherwise successfully uploaded several hundred files.

### Output of the diagnostics  [REQUIRED]
    Diagnostics
    -------
    Warning: Dropbox import not working. dropbox_key is empty.

    System Information
    --------------
    Lychee Version (git):            master (985f6f8) -- Up to date (1 days ago).
    DB Version:                      4.5.1
    
    composer install:                --no-dev
    APP_ENV:                         production
    APP_DEBUG:                       false
    
    System:                          Linux
    PHP Version:                     8.1.8
    PHP User agent:                  Lychee/4 (https://lycheeorg.github.io/)
    Timezone:                        America/New_York
    Max uploaded file size:          500M
    Max post size:                   500M
    Max execution time:              200
    MySQL Version:                   10.8.3-MariaDB-log
    
    exec() Available:                yes
    Imagick Available:               1
    Imagick Enabled:                 1
    Imagick Version:                 1808
    GD Version:                      2.3.3

    Config Information
    --------------
    version:                         040501
    check_for_updates:               0
    sorting_photos_col:              taken_at
    sorting_photos_order:            ASC
    sorting_albums_col:              max_taken_at
    sorting_albums_order:            ASC
    imagick:                         1
    skip_duplicates:                 0
    small_max_width:                 0
    small_max_height:                360
    medium_max_width:                1920
    medium_max_height:               1080
    lang:                            en
    layout:                          1
    image_overlay_type:              desc
    default_license:                 none
    compression_quality:             90
    full_photo:                      1
    delete_imported:                 0
    Mod_Frame:                       1
    Mod_Frame_refresh:               30
    thumb_2x:                        1
    small_2x:                        1
    medium_2x:                       1
    landing_page_enable:             1
    landing_owner:                   <me>
    landing_title:                   <me>
    landing_subtitle:                Photos
    landing_facebook:                
    landing_flickr:                  
    landing_twitter:                 
    landing_instagram:               
    landing_youtube:                 
    landing_background:              <my image>.jpg
    site_title:                      Lychee v4
    site_copyright_enable:           1
    site_copyright_begin:            2019
    site_copyright_end:              2022
    additional_footer_text:          
    display_social_in_gallery:       0
    public_search:                   0
    SL_enable:                       0
    SL_for_admin:                    0
    public_recent:                   0
    recent_age:                      1
    public_starred:                  0
    downloadable:                    0
    photos_wraparound:               1
    map_display:                     1
    zip64:                           1
    map_display_public:              0
    map_provider:                    Wikimedia
    force_32bit_ids:                 0
    map_include_subalbums:           0
    update_check_every_days:         3
    has_exiftool:                    0
    share_button_visible:            0
    import_via_symlink:              0
    has_ffmpeg:                      1
    location_decoding:               1
    location_decoding_timeout:       30
    location_show:                   1
    location_show_public:            0
    rss_enable:                      0
    rss_recent_days:                 7
    rss_max_items:                   100
    prefer_available_xmp_metadata:   0
    editor_enabled:                  1
    lossless_optimization:           0
    swipe_tolerance_x:               150
    swipe_tolerance_y:               250
    local_takestamp_video_formats:   .avi|.mov
    log_max_num_line:                1000
    unlock_password_photos_with_url_param: 0
    nsfw_visible:                    1
    nsfw_blur:                       0
    nsfw_warning:                    0
    nsfw_warning_admin:              0
    map_display_direction:           1
    album_subtitle_type:             oldstyle
    upload_processing_limit:         4
    public_photos_hidden:            1
    new_photos_notification:         0
    legacy_id_redirection:           1

Server is Arch 5.18.11, I've tried latest versions of Chrome and Firefox with same results.

**Comment by ildyria** [comment]
> This is the only file that gives this error,

Any way you can provide us that said breaking file ? :)

**Comment by romleinster** [comment]
https://drive.google.com/file/d/1I6OCdt1w0rhLnmm9u7B4LuGAEXI3pe0n/view?usp=sharing

**Comment by kamil4** [comment]
We've got three alternative metadata extractors and it fails with all three of them. That's... impressive :wink:.
