### ISSUE TITLE
Photo View link does not work

### ISSUE THREAD

**Issue by nikodemusk** [LycheeOrg/Lychee#1419]
### Detailed description of the problem [REQUIRED]
When I copy the link to Lychee Photo View, it just display the title of the photo, not the photo itself.

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Go to any photo in any public album
2. Click on Share button (the symbol), select Direct Links and copy the link to Lychee Photo View
3. Paste the link in a browser.
4. See error, i.e just the title of the photo is displayed. I also noticed that the info button and share button (even when album) not work. More: the Share button is visible even when "Share button is visible" is unchecked in the album share settings.

**Screenshots**
No screenshot, but see
https://photos.nikodemuskarlsson.se/view?p=QGY3AJYLenj4NMqO8tscV68X
(it should be a photo on the page too).

### Output of the diagnostics  [REQUIRED]
* https://photos.nikodemuskarlsson.se/Diagnostics

### Browser and system
 I run Safari v.15.5, Lychee v. 4.5.2 from Git Master 89fcba4 and PHP 8.1.8.

**Comment by kamil4** [comment]
Confirmed. That photo view is an unloved child of our project :wink: -- it's a standalone implementation largely independent from the rest of the front end, and there are technical reasons for it to be that way, but in practice it simply doesn't receive the day-to-day testing it needs so it tends to accumulate bugs as time goes by. Anyway, thanks for the report -- we'll fix it!

**Comment by nikodemusk** [comment]
Just a question: This fix is merged to Lychee frontend, will this in turn be merged to Lychee or do I need to do something else than keep my installation up to date?

**Comment by ildyria** [comment]
We still need to apply an update in Lychee. So at the next commit in the Lychee repo (not the front-end) it will be _deployed_.

**Comment by nikodemusk** [comment]
Great! Sorry for my wrong terminology, I learn new things every day.

**Comment by ildyria** [comment]
There is not terminology error, it is just that I wanted put the emphasis on when it will be propagated to the base repo. :)

**Comment by ghost** [comment]
Hi,
I just stumbled upon this bug and wanted to ask, if the fix is already implemented?

I use the latest docker image, Diagnosis shows version "4.5.3".

But the direct link feature still doesn't work (only the black bar on top with title is shown).

**Comment by kamil4** [comment]
The fix is implemented, but it looks like it missed making it into the 4.5.3 release.

You may want to try the 4.6.0 prerelease (available from our Releases page); that one surely should include the fix.
