### ISSUE TITLE
[Enhancement] Album name in link preview

### ISSUE THREAD

**Issue by shrx** [LycheeOrg/Lychee#1420]
Is it possible to add the album name to the preview that is generated when the album's link is shared, e.g. on discord?

For example, when I share an album named "Summer vacation 2022" with a link https://my.lychee.gallery/#16587703455451 it will generate a preview embed with title "My lychee photo gallery" instead of the album name, which is not very helpful.

**Comment by ildyria** [comment]
Not possible in the current state of Lychee. The reason being that we use the id part after the `#` to determine what is the album.
However this information is not available when doing a request to the server, a JS client needs to parse the URL and then query the server.
I am _working_ (but very slow progress) on a new front-end which would make this possible.
