### ISSUE TITLE
Session::init - API Usage Problems

### ISSUE THREAD

**Issue by Glokeru** [LycheeOrg/Lychee#1421]
Hello there,

i am trying to realize an automated sync of a directory structure into Lychee. Every folder should be imported as a new album. Since tools like lycheesync do not work with the new database structure i am trying to use the API for creating new albums and call the artisan sync command with the album_id.  Unfortunatly my script is failing already on Session::init. 

```
import requests
from requests.structures import CaseInsensitiveDict

url = "https://lychee.mydomain.de/api/Session::login"

headers = CaseInsensitiveDict()
headers["Accept"] = "application/json"
headers["Content-Type"] = "application/json"

data = """
{
 "username" : "REDACTED",
 "password" : "REDACTED"
}
"""
resp = requests.post(url, headers=headers, data=data)

print(resp.status_code)
print(resp.text)
```

Calling this code i get:

```
419
{
    "message": "Session expired",
    "exception": "SessionExpiredException"
}
```
Any idea what the Problem could be? 
Are there any other ways (which i did not find) to sync a directory structure?

Thanks in advance,

Andrei

**Comment by ildyria** [comment]
It's the XSRF protection (read more [here][1]). You have two way to solve this.
1. Query an endpoint not XSRF protected, get the cookie and continue with your next requests
2. Use the API key to bypass the XSRF protection (would recommend that way).
Do note that the API key behaviour will change once https://github.com/LycheeOrg/Lychee/pull/1368 is merged (which will also make it simpler for you).

[1]: https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html

**Comment by d7415** [comment]
> Are there any other ways (which i did not find) to sync a directory structure?

You can use the [built-in sync functionality](https://lycheeorg.github.io/docs/faq.html#can-i-set-up-lychee-to-watch-a-folder-for-new-images-and-automatically-add-them-to-albums).

**Comment by Glokeru** [comment]
> 2\. Use the API key to bypass the XSRF protection (would recommend that way).

Can you provide me more info about the api_key? Where do i set it / get it. It is not clearly documented.

**Comment by qwerty287** [comment]
`api_key` will be removed with #1368. I'd recommend you to wait for this, and then you can easily authenticate with an additional key.

**Comment by dbv-rl** [comment]
Though #1368 is merged, the documentation does not contain information about the `api_key` or the additonal key.
I'm using version 4.6.

**Comment by ildyria** [comment]
We should indeed add those in the release notes and in the docs.

**Comment by dbv-rl** [comment]
@ildyria Any update on on the documentation?

**Comment by pawelmalak** [comment]
If anyone is looking for an automated way of importing files from server in the background, here is my current solution working with Lychee v4.9.4.

First go to `Settings` and click on `API Token`:

![image](https://github.com/LycheeOrg/Lychee/assets/24780509/fb517b0a-127a-4276-8d60-c1d0bf3b03a2)

Generate the token and copy it.

---

### Shell script
```sh
#!/bin/bash
host="https://lychee.tld"
token="YOUR_TOKEN"

generate_req_body()
{
  cat <<EOF
{
  "albumID": null,
  "paths": ["/app/www/public/uploads/import/"],
  "delete_imported": false,
  "import_via_symlink": true,
  "skip_duplicates": true,
  "resync_metadata": false
}
EOF
}

curl \
  -X POST \
  -H "Content-Type: application/json" \
  -H "Accept: application/json" \
  -H "Authorization: $token" \
  -d "$(generate_req_body)" \
  -s "$host/api/Import::server" > /dev/null
```

- Set `host` and `token` variables to match your Lychee instance
- In `generate_req_body` you can configure your import options. I'm skipping duplicates and creating symbolic links.

**Comment by x1ntt** [comment]
> If anyone is looking for an automated way of importing files from server in the background, here is my current solution working with Lychee v4.9.4.如果有人正在寻找一种在后台从服务器导入文件的自动化方法，这是我目前使用 Lychee v4.9.4 的解决方案。
> 
> First go to `Settings` and click on `API Token`:
> 
> ![image](https://private-user-images.githubusercontent.com/24780509/261825845-fb517b0a-127a-4276-8d60-c1d0bf3b03a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNjc4MDQsIm5iZiI6MTcyNzE2NzUwNCwicGF0aCI6Ii8yNDc4MDUwOS8yNjE4MjU4NDUtZmI1MTdiMGEtMTI3YS00Mjc2LThkNjAtYzFkMGJmM2IwM2EyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDA4NDUwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjNjkxM2MwMWQ1MzFiNmFjOTZmZDM2OGEzYTljNDE4NDU5NTAyYmZjYjk3ZTBiZDAzNzIxNGU3NTZjMzJjNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SVIKXeheM8XjmTFGC0-PNpBA4nEgea3ZucorliuV-9Y)
> 
> Generate the token and copy it.
> 
> ### Shell script
> ```shell
> #!/bin/bash
> host="https://lychee.tld"
> token="YOUR_TOKEN"
> 
> generate_req_body()
> {
>   cat <<EOF
> {
>   "albumID": null,
>   "paths": ["/app/www/public/uploads/import/"],
>   "delete_imported": false,
>   "import_via_symlink": true,
>   "skip_duplicates": true,
>   "resync_metadata": false
> }
> EOF
> }
> 
> curl \
>   -X POST \
>   -H "Content-Type: application/json" \
>   -H "Accept: application/json" \
>   -H "Authorization: $token" \
>   -d "$(generate_req_body)" \
>   -s "$host/api/Import::server" > /dev/null
> ```
> 
> * Set `host` and `token` variables to match your Lychee instance设置 `host` 和 `token` 变量以匹配您的 Lychee 实例
> * In `generate_req_body` you can configure your import options. I'm skipping duplicates and creating symbolic links.在 `generate_req_body` 中，您可以配置导入选项。我跳过了重复项并创建了符号链接。

Thank you, this method is still effective in 5.5.1
