### ISSUE TITLE
Site slow and the new album image uploads stay stuck on "processing"

### ISSUE THREAD

**Issue by adim-att** [LycheeOrg/Lychee#1426]
### Output of the diagnostics  [REQUIRED]
Diagnostics
    -------
    Warning: Dropbox import not working. dropbox_key is empty.
    Warning: You may experience problems when uploading a photo of large size. Take a look in the FAQ for details.
    Warning: You may experience problems when uploading a photo of large size. Take a look in the FAQ for details.
    Warning: You may experience problems when uploading a photo of large size or handling many/large albums. Take a look in the FAQ for details.
    Warning: Pictures that are rotated lose their metadata! Please install Imagick to avoid that.
    Info: Latest version of PHP is 8.1

### Browser and system
Firefox, Ubuntu 20.04

**Comment by nagmat84** [comment]
Please fill out the provided template for issues and include the _complete_ output of the diagnostic. Without even knowing which version of Lychee you are using, we cannot help.

**Comment by adim-att** [comment]
It was on Version 4.4.0, the diagnosis section ended where I copied that, the rest looked like another section, perhaps you need to edit that as well to be intuitive to users. I uninstalled the script, I don't have time to do it again, I just commented here to help you troubleshoot it !

My php version was 8.1
Shared hosting
On a subdomain

Feel free to close this issue.
