### ISSUE TITLE
Failed Import with Lightroom Metadata

### ISSUE THREAD

**Issue by rheinon** [LycheeOrg/Lychee#1431]
Some photos where "All Metadata" is exported from Lightroom failed import in Lychee.

<img width="437" alt="image" src="https://user-images.githubusercontent.com/55107720/182042108-eb71c376-cc6a-47f4-ae10-4e39051f034b.png">

The link to the exif and metadata of the failed import is as follows:
[failed_lychee_import.zip](https://github.com/LycheeOrg/Lychee/files/9229773/failed_lychee_import.zip)

When metadata is set to "Copyright & Contact Info Only", the photo will import to Lychee without any problem.

<img width="437" alt="image" src="https://user-images.githubusercontent.com/55107720/182042140-7fcc19c7-14f1-4283-a249-3b85b8070e03.png">

The link to the exif and metadata the successfully imported is as follows:
[passed_lychee_import.zip](https://github.com/LycheeOrg/Lychee/files/9229774/passed_lychee_import.zip)

**Comment by kamil4** [comment]
Sorry, but would you mind following the bug reporting template? As is, we are missing some critical information here. In particular, which Lychee version is that? The current git master? What was the error message? Was there anything in the logs? And which metadata extractor was being used (what are the values of the config variables `has_exiftool` and `imagick`?).

Last but not least, a link to the actual failing image is critical for us to be able to reproduce the problem...
