### ISSUE TITLE
How to render Lychee in an iframe?

### ISSUE THREAD

**Issue by andreasm123** [LycheeOrg/Lychee#1451]
I'm trying to render Lychee in an iframe of another web application. Trying various settings in .htaccess, /etc/apache2/conf-available/security.conf, /etc/apache2/apache2.conf with e.g.

```
Header set X-Frame-Options: "ALLOW-FROM <ip-address>"
Header always unset X-Frame-Options
```
did not help. Using 'Header always unset X-Frame-Options' at least starts to render, but the Chrome Dev. Console shows errors like:

```
Uncaught DOMException: Blocked a frame with origin "http://<ip-address>" from accessing a cross-origin frame.
at Function.get (http://<ip-address>/dist/main.js?1659883422:841:16752)
```
Has anyone got Lychee running in an iframe? Or how can this be fixed?

Andreas

**Comment by ildyria** [comment]
I have not used it in an iframe, but you may want to try to edit this file:
https://github.com/LycheeOrg/Lychee/blob/master/config/secure-headers.php#L42

**Comment by andreasm123** [comment]
tried this but no luck. Setting 

```
'x-frame-options' => '' 
or 
'x-frame-options' => 'ALLOW-FROM http://<ip-address>' 
```
throws the same error. Using 

```
'x-frame-options' => 'SAMEORIGIN'
```
does not help in my case as i'm using 2 different servers.

**Comment by d7415** [comment]
I suspect you want https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors

Beyond `secure-headers.php`, this is not a Lychee issue, so I'm going to close it.

**Comment by andreasm123** [comment]
Hope this read by the developers (as this is already in status closed)
i tried almost every combination in secure-headers.php but still no luck besides errors in main.js and/or in best case a blank screen. If someone could provide a working example how to configure Lychee running in an iframe that would be great!

Andreas

**Comment by d7415** [comment]
Did you try `frame-ancestors`? Did you check your browser logs to see why it wasn't loading?

None of the core team use Lychee in an iframe, so we do not have a working example to share.

**Comment by andreasm123** [comment]
thanks for reaching out - yes i tried both the x-frame options / frame-ancestors as well as Apache and nginx. Best i can get is the browser not to complain about headers preventing loading content in a frame. What's left over is an error thrown in main.js:

```
Uncaught DOMException: Blocked a frame with origin "http://<snipped>" from accessing a cross-origin frame.
    at Function.get (http://<snipped>/dist/main.js?1659883422:841:16752)
    at Object.<anonymous> (http://<snipped>/dist/main.js?1659883422:841:61625)
    at t (http://<snipped>/dist/main.js?1659883422:841:330)
    at Object.<anonymous> (http://<snipped>/dist/main.js?1659883422:841:43853)
    at t (http://<snipped>/dist/main.js?1659883422:841:330)
    at Object.<anonymous> (http://<snipped>/dist/main.js?1659883422:841:49127)
    at t (http://<snipped>/dist/main.js?1659883422:841:330)
    at Object.<anonymous> (http://<snipped>/dist/main.js?1659883422:841:52188)
    at t (http://<snipped>/dist/main.js?1659883422:841:330)
    at Object.<anonymous> (http://<snipped>/dist/main.js?1659883422:841:25535)
```

For Reference here's the HTTP header right now delivered by Lychee (i disabled all security options as suggested earlier in /var/www/html/Lychee/config/secure-headers.php):

```
HTTP/1.1 204 No Content
Server: nginx/1.18.0 (Ubuntu)
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Cache-Control: no-cache, private
Date: Mon, 15 Aug 2022 21:11:15 GMT
Permissions-Policy: accelerometer=(self), ambient-light-sensor=(self), autoplay=(self), battery=(self), camera=(self), cross-origin-isolated=(self), display-capture=(self), document-domain=*, encrypted-media=(self), execution-while-not-rendered=*, execution-while-out-of-viewport=*, fullscreen=(self), geolocation=(self), gyroscope=(self), magnetometer=(self), microphone=(self), midi=(self), navigation-override=(self), payment=(self), picture-in-picture=*, publickey-credentials-get=(self), screen-wake-lock=(self), sync-xhr=*, usb=(self), web-share=(self), xr-spatial-tracking=(self)
Set-Cookie: XSRF-TOKEN=<snipped>; expires=Mon, 15-Aug-2022 23:11:15 GMT; Max-Age=7200; path=/; samesite=lax
Set-Cookie: lychee_session=<snipped>; expires=Mon, 15-Aug-2022 23:11:15 GMT; Max-Age=7200; path=/; httponly; samesite=lax

```

**Comment by d7415** [comment]
Ah, there we go. I don't think that can't be fixed with headers - you may need to adjust hostnames to match. https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy

**Comment by andreasm123** [comment]
Agree - this is not related to headers any more. Both hosts are in the same domain but the policy says when launching from a different host its treated as failure - so guess we're stuck. A typical iframe scenario is to have content from different hosts, Can't this same origin policy be removed in Lychee?

**Comment by d7415** [comment]
I forgot about these. https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
