### ISSUE TITLE
Error Installing new 4.5.3

### ISSUE THREAD

**Issue by vuongquoc** [LycheeOrg/Lychee#1461]
Dear,

I'm trying to install new 4.5.3 with mysql (instead of sqlite)

Start installing
Everything was smooth untill...
Click on Install of env pages 
and boom:

![image](https://user-images.githubusercontent.com/84169528/184791339-d8e59531-1fd9-4812-8a7a-24add4cb272f.png)

### Output of the diagnostics  [REQUIRED]
Diagnostics
-----------
Warning: /home/whcallo6t34w/public_html/bachda.xyz/Lychee/public/uploads/ has permissions 0777, but should have 2775
Warning: /home/whcallo6t34w/public_html/bachda.xyz/Lychee/public/uploads/small has permissions 0777, but should have 2775
Warning: /home/whcallo6t34w/public_html/bachda.xyz/Lychee/public/uploads/medium has permissions 0777, but should have 2775
Warning: /home/whcallo6t34w/public_html/bachda.xyz/Lychee/public/uploads/import has permissions 0777, but should have 2775
Warning: /home/whcallo6t34w/public_html/bachda.xyz/Lychee/public/uploads/thumb has permissions 0777, but should have 2775
Warning: 3 more directories with wrong permissions
Error: sorting_photos_col not set in database
Error: sorting_albums_col not set in database
Warning: Dropbox import not working. dropbox_key is empty.
Error: Database is behind file versions. Please apply the migration.
Warning: Default timezone not properly set; you might experience strange results when importing photos without explicit EXIF timezone

System Information
------------------
Lychee Version (release):        4.5.3
DB Version:                      4.0.8

composer install:                --no-dev
APP_ENV:                         production
APP_DEBUG:                       false

System:                          Linux
PHP Version:                     8.1.8
PHP User agent:                  Lychee/4 (https://lycheeorg.github.io/)
Timezone:                        UTC
Max uploaded file size:          1G
Max post size:                   128M
Max execution time:              0
MySQL Version:                   5.6.51-cll-lve

exec() Available:                yes
Imagick Available:               1
Imagick Enabled:                 1
Imagick Version:                 1808
GD Version:                      2.2.5

Config Information
------------------
version:                         040008
check_for_updates:               0
sorting_Photos_col:              takestamp
sorting_Photos_order:            ASC
sorting_Albums_col:              max_takestamp
sorting_Albums_order:            ASC
imagick:                         1
skip_duplicates:                 0
small_max_width:                 0
small_max_height:                360
medium_max_width:                1920
medium_max_height:               1080
lang:                            en
layout:                          1
image_overlay:                   1
image_overlay_type:              desc
default_license:                 none
compression_quality:             90
full_photo:                      1
delete_imported:                 0
Mod_Frame:                       1
Mod_Frame_refresh:               30
thumb_2x:                        1
small_2x:                        1
medium_2x:                       1
landing_page_enable:             0
landing_owner:                   John Smith
landing_title:                   John Smith
landing_subtitle:                Cats, Dogs & Humans Photography
landing_facebook:                https://www.facebook.com/JohnSmith
landing_flickr:                  https://www.flickr.com/JohnSmith
landing_twitter:                 https://www.twitter.com/JohnSmith
landing_instagram:               https://instagram.com/JohnSmith
landing_youtube:                 https://www.youtube.com/JohnSmith
landing_background:              dist/cat.jpg
site_title:                      Lychee v4
site_copyright_enable:           1
site_copyright_begin:            2019
site_copyright_end:              2019
additional_footer_text:
display_social_in_gallery:       0
public_search:                   0
SL_enable:                       0
SL_for_admin:                    0
public_recent:                   0
recent_age:                      1
public_starred:                  0
downloadable:                    0
photos_wraparound:               1
map_display:                     0
zip64:                           1
map_display_public:              0
map_provider:                    Wikimedia
force_32bit_ids:                 0
map_include_subalbums:           0
update_check_every_days:         3
has_exiftool:                    0
share_button_visible:            0
import_via_symlink:              0
has_ffmpeg:                      0
location_decoding:               0
location_decoding_timeout:       30
location_show:                   1
location_show_public:            0
rss_enable:                      0
rss_recent_days:                 7
rss_max_items:                   100
prefer_available_xmp_metadata:   0
editor_enabled:                  1
lossless_optimization:           0
swipe_tolerance_x:               150
swipe_tolerance_y:               250
local_takestamp_video_formats:   .avi|.mov
log_max_num_line:                1000
unlock_password_photos_with_url_param: 0

please have a look at your convenients

Thanks

Vuong Quoc

**Comment by d7415** [comment]
Hi,

It looks like our minimum supported version for MySQL is 5.7 due to the `json` field type.

**Comment by d7415** [comment]
Update: The [requirements](https://lycheeorg.github.io/docs/installation.html#server-requirements) already state 5.7.8.

**Comment by ildyria** [comment]
Should we add a check for MySQL version in the diagnostics ?

**Comment by d7415** [comment]
> Should we add a check for MySQL version in the diagnostics ?

A line or a check? DB Engine version would probably be useful. A check would be nice, but may be excessive.
