### ISSUE TITLE
Uploads fail with App\Image\StreamStatFilter::onCreate error

### ISSUE THREAD

**Issue by oleonard** [LycheeOrg/Lychee#1464]
### Detailed description of the problem [REQUIRED]
I have a new installation of Lychee on shared hosting. Everything appears to be working correctly, but when I try to upload an image it fails. I've tried with PNG, JPG, and GIF

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Log in as a user with permission to upload photos
2. Click the "+" link to trigger the upload form
3. Upload a valid image
4. Process fails with "Error"

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

### Output of the diagnostics  [REQUIRED]

Diagnostics
-----------
Warning: Dropbox import not working. dropbox_key is empty.
Warning: zend.assertions is enabled although Lychee is not in debug mode. Outside of debugging, code generation for assertions is recommended to be disabled for efficiency reasons
Info: Latest version of PHP is 8.1

System Information
------------------
Lychee Version (release):        4.5.3
DB Version:                      4.5.3

composer install:                --no-dev
APP_ENV:                         production
APP_DEBUG:                       false

System:                          Linux
PHP Version:                     8.0.2
PHP User agent:                  Lychee/4 (https://lycheeorg.github.io/)
Timezone:                        America/Los_Angeles
Max uploaded file size:          512M
Max post size:                   512M
Max execution time:              0
MySQL Version:                   8.0.28-0ubuntu0.20.04.3

exec() Available:                yes
Imagick Available:               1
Imagick Enabled:                 1
Imagick Version:                 1687
GD Version:                      bundled (2.1.0 compatible)

### Browser and system

macOS 12.5, Firefox Developer Edition v104 and Chrome 104

**Comment by nagmat84** [comment]
Could you please clear the log from noise, reproduce the error and post the then filled log here? The log should tell us what goes wrong. You'll find the log via the cog icon in the upper left and then "Show logs".

**Comment by oleonard** [comment]
2022-08-17 16:37:26 UTC -- error   -- App\Image\StreamStatFilter::onCreate -- 68 -- App\Image\StreamStatFilter::onCreate(): Return value must be of type bool, null returned

**Comment by nagmat84** [comment]
Is this the only log entry? Actually there should be a backtrace.

**Comment by nagmat84** [comment]
I had a look into the code

https://github.com/LycheeOrg/Lychee/blob/6e52fcc618793f49d9ff00f53f701d6ed9b00149/app/Image/StreamStatFilter.php#L61-L69

The failing line 68 does not make any sense. The error tells us that this method returns `null` although it should return a boolean. But this would indicate a bug in the PHP core engine. `php_user_filter::onCreate` is not a PHP "user land" method but implemented in C in the PHP engine itself.

You are running PHP 8.0.2. This is not the current version of the 8.0-branch. The most recent version is 8.0.23., Ubuntu provides 8.0.8. I also had a rough and quick look into the PHP issue tracker and merge history. Indeed, there have been some stream-related bug fixes regarding wrong `null` values although I did not spot a PR which seemed directly related to `onCreate`. But anyway, could you please try to update your PHP version? Chances are that the issue will vanish. Personally, I am running PHP 8.0.20 and I cannot reproduce the problem.

**Comment by oleonard** [comment]
Switching to PHP 8.1.0 solved my problem. Thank you very much for your help!

**Comment by kamil4** [comment]
Thumbs up for @nagmat84! It would've taken me forever to even look into PHP engine itself being the possible culprit.
