### ISSUE TITLE
Unable to delete tag album - foreign key violation

### ISSUE THREAD

**Issue by flaki** [LycheeOrg/Lychee#1472]
### Detailed description of the problem

Unable to remove a tag album, getting a 500 server error to the request. The log shows an error message to an *unrelated* table.

### Steps to reproduce the issue

Accidentally created a second tag table matching the same single tag as another one. I wanted to delete the second table from the UI, but was getting an error.

### Output of the diagnostics

This is the gist of the request that is sent upon the deletion:

```
curl 'https://my-lychee.example/api/Album::delete'
    -X POST
    -H 'Accept: application/json [...]'
    -H 'Content-Type: application/json'
    -H 'X-XSRF-TOKEN: [...]'
    -H 'Cookie: XSRF-TOKEN=[...]; lychee_session=[...]'
    --data-raw '{"albumIDs":["h13fg_..."]}'
```

The response is a 500 server error:

```json
{
    "message": "Server Error",
    "exception": "QueryException"
}
```

The diagnostics is the weirdest of all, and yes I double checked this error is generated in response to the above QueryException:

```
2022-08-20 14:12:32 UTC -- error   -- PDOStatement::execute -- 526 -- SQLSTATE[23503]: Foreign key violation: 7 ERROR:  update or delete on table "albums" violates foreign key constraint "photos_album_id_foreign" on table "photos"
DETAIL:  Key (id)=(bRiZ_...) is still referenced from table "photos".
2022-08-20 14:12:32 UTC -- error   -- App\Actions\Album\Delete::do -- 137 -- SQLSTATE[23503]: Foreign key violation: 7 ERROR:  update or delete on table "albums" violates foreign key constraint "photos_album_id_foreign" on table "photos"
DETAIL:  Key (id)=(bRiZ_...) is still referenced from table "photos".; caused by
2022-08-20 14:12:32 UTC -- error   -- Illuminate\Database\Connection::runQueryCallback -- 712 -- SQLSTATE[23503]: Foreign key violation: 7 ERROR:  update or delete on table "albums" violates foreign key constraint "photos_album_id_foreign" on table "photos"
DETAIL:  Key (id)=(bRiZ_...) is still referenced from table "photos". (SQL: delete from "albums"); caused by
2022-08-20 14:12:32 UTC -- error   -- App\Actions\Album\Delete::do -- 137 -- SQLSTATE[23503]: Foreign key violation: 7 ERROR:  update or delete on table "albums" violates foreign key constraint "photos_album_id_foreign" on table "photos"
DETAIL:  Key (id)=(bRiZ_...) is still referenced from table "photos". (SQL: delete from "albums"); caused by
```

The weird thing is, the foreign key violation is referencing *another*, completely unrelated album (id `bRiZ...`), which is a regular album with two photos in it which correctly reference the album (of course it complains about dropping it). The tag album that was *supposed to* get dropped was actually id `h13fg_...`, as can be seen in the request above. When manually finding these id-s in the `tag_album` and `base_albums` tables and deleting the rows, the album is correctly removed.

### Browser and system
Up-to-date Firefox on Linux, Lychee 4.5.3 running in an LXC container on a Debian install connected to an external Postgres database.

**Comment by nagmat84** [comment]
Could you provide us with a dump of your DB and a script shell script which runs the necessary cUrl commands to reproduce the issue? (I.e. login via cUrl, init the session via cUrl, etc. and finally call the failing request).

If you do, I would agree to run it in the PHP step debugger and have a look what goes wrong. But otherwise it will be difficult for us to reproduce the problem, in particular as this error is not using the frontend.

**Comment by flaki** [comment]
Hey, apologies for the misunderstanding, I am _absolutely_ using the frontend, the `curl` is just shared as a 'what gets sent from the frontend', after clicking okay in the delete dialog the red bar on the top of the screen will report that the deletion failed.

I shared all relevant details from the database, I'm afraid even if i could share the dump I already manually deleted the album as mentioned above.

**Comment by flaki** [comment]
Fwiw I just created a new tag album that i am also unable to delete, same error message, different completely unrelated album id in the log output:
![image](https://user-images.githubusercontent.com/2089432/185762056-f0eeab49-4629-466f-925b-f1fc787ee2d1.png)

From a cursory look at [`Actions/Album/Delete.php`](https://github.com/LycheeOrg/Lychee/blob/master/app/Actions/Album/Delete.php) which looks sufficiently complex to have a bug lurking somewhere this might be it. If noone can repro this i can have a look later if I can figure out what's going wrong, though I haven't touched PHP in a good ten years so can't promise anything :sweat_smile:

**Comment by nagmat84** [comment]
I can confirm the bug. I am on it.

BTW, just to let you know, in case you are interested to do any debugging on your own in the future: if you set `APP_DEBUG=true` in the `.env` file of your Lychee installation, you get a full clickable backtrace in the Javascript console of your browser.

![Screenshot_20220821_105159](https://user-images.githubusercontent.com/7428426/185783598-8a7bf0fb-d018-42c0-be70-355bbf7987ed.png)

I found that very helpful and hence implemented it as part of the new error reporting handler.

**Comment by nagmat84** [comment]
Just to let you know: I have pinpointed the bug. The root cause is terrifying. Luckily, we have foreign constraints which essentially prevents the query from succeeding. Otherwise this could have easily deleted your whole database. :astonished:

The short version is: We build a query for deletion and iterate over the album IDs to add conditions to the query like this:

```php
$deleteQuery = Album::query();
...
foreach ($albums as $album) {
	...
	$deleteQuery->whereDescendantOf($album, 'or', false, true);
}
// For MySQL deletion must be done in correct order otherwise the
// foreign key constraint to `parent_id` fails.
$deleteQuery->orderBy('_lft', 'desc')->delete();
```

However, if `$albums` is empty because we only want to delete tag albums and no regular albums, then the loop is not entered, but the query is executed nonetheless with _zero_ conditions, i.e. it would delete all albums if it was able to succeed. :scream:

The "logical" problem in the code is that the term "albums" is used in two different ways: on the one hand side it means any kind of album, i.e. tag albums and regular albums, on the other hand side it is used for regular albums only.

**Comment by flaki** [comment]
Yay! Thank you!

> The root cause is terrifying. Luckily, we have foreign constraints which essentially prevents the query from succeeding. Otherwise this could have easily deleted your whole database. :astonished: 

Yeah when I saw the completely unrelated album ID I knew something similar was up and only the constraints were saving the day (and the fact that the albums were not empty I guess?).
