### ISSUE TITLE
Installer not updated for v4.5.3 directories

### ISSUE THREAD

**Issue by d7415** [LycheeOrg/Lychee#1473]
### Detailed description of the problem [REQUIRED]
v4.5.3 [changed the directory structure of Lychee](https://github.com/LycheeOrg/Lychee/releases/tag/v4.5.3). The tests in the installer still test the old paths.

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Start a clean installation of Lychee
2. Run the installer
3. Go to the directory tests.

**Screenshots**
![2022-08-20-225813_751x711_scrot](https://user-images.githubusercontent.com/1611702/185767464-9876c44e-478f-48df-8491-1d7caafe9d62.png)

**Comment by kamil4** [comment]
So now we know: even the author of the web installer doesn't use it in testing :wink:.
