### ISSUE TITLE
PHP Debugger On Website

### ISSUE THREAD

**Issue by StrangeRanger** [LycheeOrg/Lychee#1476]
I just modified my CSP for my website, allowing previously blocked information. After doing this, I noticed my website displays what it calls a PHP Debugger Console. If I'm correct, it contains the Lavarel logo. It's in the bottom left corner. Is this supposed to be here? Can I disable it?

<img width="1792" alt="Screen Shot 2022-08-21 at 10 16 00 AM" src="https://user-images.githubusercontent.com/30395560/185803114-1570a217-c6d7-4905-a4dc-15f3a0167881.png">

**Comment by nagmat84** [comment]
You _should_ disable it for production environments. There are two related configuration settings in your `.env` file:

 - `APP_ENV` should be `production`
 - `APP_DEBUG` should be `false`

Also see [Lychee Documentation - Development Options](https://lycheeorg.github.io/docs/configuration.html#development-options).

If you are not planning to actively develop for Lychee, you should also run `composer install --no-dev` which removes all the debugging packages and would also have prevented the toolbar from appearing in the first place.

**Comment by StrangeRanger** [comment]
Weird... I always use `composer install --no-dev`, but after using it again, the little logo/debug system disappeared. Either way it looks like it worked. Thank you.
