### ISSUE TITLE
[Enhancement] Modify Copyright Message

### ISSUE THREAD

**Issue by StrangeRanger** [LycheeOrg/Lychee#1477]
Currently, Lychee give you the option to add a copyright notice to the website. Can we possibly get an option that lets us modify the wording of the copyright notice? Like instead of "All images on this website are subject to Copyright by Hunter T. © 2020-2022", I'm wanting to word is like "Images on this website may be subject to Copyright by Hunter T. © 2020-2022". I ask as some of the images on my website are created by me and would fall under copyright, but I also host some images I've not created nor own the copyright of.

**Comment by kamil4** [comment]
I think you should be able to achieve what you want by setting `site_copyright_enable` to `0` and providing your own copyright message in `additional_footer_text`.

**Comment by StrangeRanger** [comment]
I see. I'll use that then.
