### ISSUE TITLE
id undefined error on upload after update via git

### ISSUE THREAD

**Issue by romleinster** [LycheeOrg/Lychee#1483]
Before submitting my last bug report re: an un-uploadable file, I updated via git pull, composer install --no-dev, php artisan migrate (all ran successfully). Since then, when I submit a file to upload, the upload modal doesn't appear and the file sometimes uploads, sometimes does not. I get these errors in the client:

in Firefox:
```
Uncaught TypeError: id is undefined
    isSearchID https://my.domain/Lychee/public/dist/main.js?1661352025:1426
    isID https://my.domain/Lychee/public/dist/main.js?1661352025:1456
    getID https://my.domain/Lychee/public/dist/main.js?1661352025:1463
    reload https://my.domain/Lychee/public/dist/main.js?1661352025:2673
    finish https://my.domain/Lychee/public/dist/main.js?1661352025:11137
    onComplete https://my.domain/Lychee/public/dist/main.js?1661352025:11291
    process https://my.domain/Lychee/public/dist/main.js?1661352025:11317
    local https://my.domain/Lychee/public/dist/main.js?1661352025:11335
    n https://my.domain/Lychee/public/dist/main.js?1661352025:21
    show https://my.domain/Lychee/public/dist/main.js?1661352025:11020
    local https://my.domain/Lychee/public/dist/main.js?1661352025:11332
    <anonymous> https://my.domain/Lychee/public/dist/main.js?1661352025:5072
    dispatch https://my.domain/Lychee/public/dist/main.js?1661352025:2
    handle https://my.domain/Lychee/public/dist/main.js?1661352025:2
    add https://my.domain/Lychee/public/dist/main.js?1661352025:2
    Ee https://my.domain/Lychee/public/dist/main.js?1661352025:2
    each https://my.domain/Lychee/public/dist/main.js?1661352025:2
    each https://my.domain/Lychee/public/dist/main.js?1661352025:2
    Ee https://my.domain/Lychee/public/dist/main.js?1661352025:2
    on https://my.domain/Lychee/public/dist/main.js?1661352025:2
    <anonymous> https://my.domain/Lychee/public/dist/main.js?1661352025:5070
    e https://my.domain/Lychee/public/dist/main.js?1661352025:2
    t https://my.domain/Lychee/public/dist/main.js?1661352025:2
    setTimeout handler*Deferred/then/l/< https://my.domain/Lychee/public/dist/main.js?1661352025:2
    c https://my.domain/Lychee/public/dist/main.js?1661352025:2
    fireWith https://my.domain/Lychee/public/dist/main.js?1661352025:2
    fire https://my.domain/Lychee/public/dist/main.js?1661352025:2
    c https://my.domain/Lychee/public/dist/main.js?1661352025:2
    fireWith https://my.domain/Lychee/public/dist/main.js?1661352025:2
    ready https://my.domain/Lychee/public/dist/main.js?1661352025:2
    setTimeout handler* https://my.domain/Lychee/public/dist/main.js?1661352025:2
    <anonymous> https://my.domain/Lychee/public/dist/main.js?1661352025:2
    <anonymous> https://my.domain/Lychee/public/dist/main.js?1661352025:2
main.js:1426:2
```

in Chrome:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'startsWith')
    at album.isSearchID (main.js?1661352025:1426:58)
    at isID (main.js?1661352025:1456:40)
    at album.getID (main.js?1661352025:1463:6)
    at Object.local (main.js?1661352025:11067:23)
    at HTMLInputElement.<anonymous> (main.js?1661352025:5072:16)
    at HTMLDocument.dispatch (main.js?1661352025:2:43064)
    at v.handle (main.js?1661352025:2:41048)
album.isSearchID @ main.js?1661352025:1426
isID @ main.js?1661352025:1456
album.getID @ main.js?1661352025:1463
local @ main.js?1661352025:11067
(anonymous) @ main.js?1661352025:5072
dispatch @ main.js?1661352025:2
v.handle @ main.js?1661352025:2
```

I've run php artisan cache:clear and php artisan config:clear.
Any idea what I've mixed up and how to fix it?

    Diagnostics
    -------
    Warning: Dropbox import not working. dropbox_key is empty.

    System Information
    --------------
    Lychee Version (git):            master (04b1522) -- Up to date (19 minutes ago).
    DB Version:                      4.6.0
    
    composer install:                --no-dev
    APP_ENV:                         production
    APP_DEBUG:                       false
    
    System:                          Linux
    PHP Version:                     8.1.9
    PHP User agent:                  Lychee/4 (https://lycheeorg.github.io/)
    Timezone:                        America/New_York
    Max uploaded file size:          500M
    Max post size:                   500M
    Max execution time:              200
    MySQL Version:                   10.8.4-MariaDB-log
    
    exec() Available:                yes
    Imagick Available:               1
    Imagick Enabled:                 1
    Imagick Version:                 1808
    GD Version:                      2.3.3

    Config Information
    --------------
    version:                         040600
    check_for_updates:               0
    sorting_photos_col:              taken_at
    sorting_photos_order:            ASC
    sorting_albums_col:              max_taken_at
    sorting_albums_order:            ASC
    imagick:                         1
    skip_duplicates:                 0
    small_max_width:                 0
    small_max_height:                360
    medium_max_width:                1920
    medium_max_height:               1080
    lang:                            en
    layout:                          1
    image_overlay_type:              desc
    default_license:                 none
    compression_quality:             90
    full_photo:                      1
    delete_imported:                 0
    Mod_Frame:                       1
    Mod_Frame_refresh:               30
    thumb_2x:                        1
    small_2x:                        1
    medium_2x:                       1
    landing_page_enable:             1
    landing_owner:           
    landing_title:               
    landing_subtitle:          
    landing_facebook:                
    landing_flickr:                  
    landing_twitter:                 
    landing_instagram:               
    landing_youtube:                 
    landing_background:   
    site_title:                      
    site_copyright_enable:           1
    site_copyright_begin:            1985
    site_copyright_end:              2022
    additional_footer_text:          
    display_social_in_gallery:       0
    public_search:                   0
    SL_enable:                       0
    SL_for_admin:                    0
    public_recent:                   0
    recent_age:                      0
    public_starred:                  0
    downloadable:                    0
    photos_wraparound:               1
    map_display:                     1
    zip64:                           1
    map_display_public:              1
    map_provider:                    Wikimedia
    force_32bit_ids:                 0
    map_include_subalbums:           1
    update_check_every_days:         3
    has_exiftool:                    0
    share_button_visible:            0
    import_via_symlink:              0
    has_ffmpeg:                      1
    location_decoding:               1
    location_decoding_timeout:       30
    location_show:                   1
    location_show_public:            0
    rss_enable:                      0
    rss_recent_days:                 7
    rss_max_items:                   100
    prefer_available_xmp_metadata:   0
    editor_enabled:                  1
    lossless_optimization:           0
    swipe_tolerance_x:               150
    swipe_tolerance_y:               250
    local_takestamp_video_formats:   .avi|.mov
    log_max_num_line:                1000
    unlock_password_photos_with_url_param: 0
    nsfw_visible:                    1
    nsfw_blur:                       0
    nsfw_warning:                    0
    nsfw_warning_admin:              0
    map_display_direction:           1
    album_subtitle_type:             oldstyle
    upload_processing_limit:         4
    public_photos_hidden:            0
    new_photos_notification:         0
    legacy_id_redirection:           1
    zip_deflate_level:               6

**Comment by kamil4** [comment]
Do you mean that you see this behavior now with _any_ file you try to upload?

**Comment by nagmat84** [comment]
This sounds like a "bug" we had some time ago. Are you absolutely sure that the frontend version is correct for your backend?

Some users (maybe you, too?) don't serve the frontend, i.e. essentially the JS code, from `public/` but from some other location on the server and they had copied the content of `public/` to that other location back in time, but have forgotten about it in the meantime (no offense). If they update Lychee, the updated frontend code must be re-copied.

Could you please post your webserver config?

@LycheeOrg/reviewers I suspect that this is the third case of that issue in a row. I wonder whether we should add a version string to the frontend, too, which is shown as part of the diagnostics but which not served from the backend but which is statically part of the frontend. This way we could identify those potential mismatches more easily. However, I am unsure how we could do that in a clever way. Optimally, whenever we run `npm run compile` the GIT hash and/or version tag would be automatically added to a pre-defined position in the JS source code from where it is injected into the diagnostics.

**Comment by ildyria** [comment]
> @LycheeOrg/reviewers I suspect that this is the third case of that issue in a row. I wonder whether we should add a version string to the frontend, too, which is shown as part of the diagnostics but which not served from the backend but which is statically part of the frontend. This way we could identify those potential mismatches more easily. However, I am unsure how we could do that in a clever way. Optimally, whenever we run `npm run compile` the GIT hash and/or version tag would be automatically added to a pre-defined position in the JS source code from where it is injected into the diagnostics.

good idea.

**Comment by kamil4** [comment]
@nagmat84 https://github.com/LycheeOrg/Lychee-front/pull/316 added a test against `null` but from the diagnostics here it looks like `id` is undefined. So I can believe that the front end is up to date.

**Comment by romleinster** [comment]
I don't think I'm doing anything weird or fancy on the webserver end. I have:

```
<Directory /srv/http/Lychee/public>
Options Indexes FollowSymLinks
AllowOverride All
Require all granted
DirectoryIndex index.php
</Directory>

<Directory /srv/http/Lychee>
Require all denied
</Directory>
```

Everything is served out of the public directory and accessed directly via the URL. The only 'weird' thing I'm doing is using a symlink to my uploads directory, so that /srv/http/Lychee/public/uploads is a link to another directory elsewhere on the filesystem. I've also added that path (to the actual file location) in .env with LYCHEE_UPLOADS=

I've been testing with three files, each time I submit one for upload, I get the errors in the client console, that's consistent. Whether the modal appears and the upload completes successfully is inconsistent. One file will consistently upload, the others seem to only upload depending on whether or not I've refreshed the page or uploaded the other file first (or some other factor). And interestingly the uploaded photos are often brought in marked public.

**Comment by kamil4** [comment]
I can reproduce it locally by trying to upload any random picture to the top-level albums view. Uploading to an album works fine for me.

**Comment by romleinster** [comment]
@kamil4 

> I can reproduce it locally by trying to upload any random picture to the top-level albums view. Uploading to an album works fine for me.

Same behavior here, should have mentioned these were all top-level uploads I was trying.

**Comment by nagmat84** [comment]
WTF?!

Could you please explain your specific steps in every detail chronologically, i.e. like in [Rubber Duck Debugging](https://en.m.wikipedia.org/wiki/Rubber_duck_debugging)?

In particular, do you upload to the root album, to one of the smart albums or into a regular album? In the latter, is that album empty or not, etc.? How do you upload? Do you use the menu (from the upper left), do you use the keyboard shortcut or do you drag & drop the photo into the album?

Please explain _every_ step with no details left out.

**Comment by romleinster** [comment]
from the top level, main url  (/Lychee/public/gallery#) and I use the + button in the upper right, select upload photo, browse to the photo in the prompt and press Open. Then the errors appear in the console and the photo may or may not upload.

from a gallery url ( /Lychee/public/gallery#Njv2bkrK4fZZMs6vgsZyqN1v) doing the same steps results in the expected upload behavior with no errors in the console.

**Comment by kamil4** [comment]
Yeah, same here. I guess https://github.com/LycheeOrg/Lychee-front/pull/316 fixed "Import from Server" but as it turns out regular "Upload" is also affected. Oops...

**Comment by nagmat84** [comment]
That is embarrassing (for us).

**Comment by kamil4** [comment]
Yes, it's an embarrassing bug. Unfortunately, we don't have a good way to automate the testing of the front end, do we?

**Comment by kamil4** [comment]
Anyway, since it's a victim of my https://github.com/LycheeOrg/Lychee-front/pull/306, I'll take care of it...
