### ISSUE TITLE
Unable to upgrade!

### ISSUE THREAD

**Issue by gardiol** [LycheeOrg/Lychee#1496]
### Detailed description of the problem [REQUIRED]
I have downloaded and unpacked the new zip, checked permissions, .env file and so on.

After logging in to the GUI to complete the installation i get:
Updating user failed

ModelDBException
in[ /home/web/gardiol.org/subdomains/photos/Lychee/app/Exceptions/ModelDBException.php ](https://photos.gardiol.org/migrate)(line 50)

         *
         * @return ModelDBException
         */
        public static function create(string $modelName, string $operationName, \Throwable $previous = null): ModelDBException
        {
            return new ModelDBException(Str::ucfirst($operationName) . ' ' . $modelName . ' failed', $previous);
        }
    }

QueryException

SQLSTATE[HY000]: General error: 1364 Field 'id' doesn't have a default value (SQL: insert into `users` (`username`, `password`, `updated_at`, `created_at`) values ($2y$10$LAdeiZwZq8vDrMXsPAF3JeidUqQXHl5Ry5v.qIYyKGBZbih7agLAy, $2y$10$ruv1WvHL/2cTp8xDb7vYh.huY7LpNpFnSpWydu1tRo2AVgZyDajD6, 2022-08-31 07:44:30.529740, 2022-08-31 07:44:30.529740))

To try to fix i deleted the users in the "users" table, but the error is still here. I see that new users get added to the users table.

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
Login

**Screenshots**

### Output of the diagnostics  [REQUIRED]
Can't access at this time due to error

### Browser and system
Linux, firefox. server is installed on Linux + MySql.

**Comment by gardiol** [comment]
Just to clarify, i was upgrading from an "old" installation (4.0.6 IIRC). While i can go back, i would like to finish the upgrade process and go with the new shiny whistles.

**Comment by ildyria** [comment]
Which version are you trying to update to 4.6.0-RC3 or 4.5.3 ?

**Comment by gardiol** [comment]
4.6.0-RC3

**Comment by ildyria** [comment]
Can you give the diagnostic in version 4.0.6 ? i.e. previous migration.

**Comment by ildyria** [comment]
I am trying to get 4.0.6 running to try the migration.

**Comment by gardiol** [comment]
I had one user created in 4.0.6, if that helps

**Comment by ildyria** [comment]
Lychee 4.0.6 won't run on my 8.1 php :')

**Comment by gardiol** [comment]
yes i also had to switch from 7.4 to 8.0 for RC3 to run php... :)

**Comment by ildyria** [comment]
```
 insert into users (username, password, updated_at, created_at) values ($2y$10$LAdeiZwZq8vDrMXsPAF3JeidUqQXHl5Ry5v.qIYyKGBZbih7agLAy, $2y$10$ruv1WvHL/2cTp8xDb7vYh.huY7LpNpFnSpWydu1tRo2AVgZyDajD6, 2022-08-31 07:44:30.529740, 2022-08-31 07:44:30.529740))
 ```
 That is a Admin user migration (due to the username starting with `$2$10`.

**Comment by ildyria** [comment]
Can you do `./artisan migrate:status` on the 4.6.0-RC3 version ?

**Comment by gardiol** [comment]
~/subdomains/photos/Lychee $ ./artisan migrate:status
```
+------+-------------------------------------------------------------+-------+
| Ran? | Migration                                                   | Batch |
+------+-------------------------------------------------------------+-------+
| Yes  | 2014_10_12_000000_create_users_table                        | 1     |
| Yes  | 2018_08_03_110935_create_albums_table                       | 1     |
| Yes  | 2018_08_03_110936_create_photos_table                       | 1     |
| Yes  | 2018_08_03_110942_create_configs_table                      | 1     |
| Yes  | 2018_08_03_111324_create_logs_table                         | 1     |
| Yes  | 2018_08_10_134924_move_settings                             | 4     |
| Yes  | 2018_08_15_102039_move_albums                               | 1     |
| Yes  | 2018_08_15_103716_move_photos                               | 1     |
| Yes  | 2018_10_30_135411_sharing                                   | 1     |
| Yes  | 2019_02_21_114356_create_pages_table                        | 1     |
| Yes  | 2019_02_21_114408_create_page_contents_table                | 1     |
| Yes  | 2019_06_21_180451_create_sym_links_table                    | 1     |
| Yes  | 2019_09_28_171753_config_fix                                | 1     |
| Yes  | 2019_09_28_190822_photos_fix                                | 1     |
| Yes  | 2019_10_01_add_livephoto_cols                               | 1     |
| Yes  | 2019_10_02_1400_config_map_display_public                   | 1     |
| Yes  | 2019_10_03_214750_frame_refresh_in_sec                      | 1     |
| Yes  | 2019_10_06_1400_config_map_providers                        | 1     |
| Yes  | 2019_10_06_152017_add_force_32bit_ids                       | 1     |
| Yes  | 2019_10_07_0900_config_map_include_sub_albums               | 1     |
| Yes  | 2019_10_09_233402_config_map_mod                            | 1     |
| Yes  | 2019_10_11_093442_config_check_update_every                 | 1     |
| Yes  | 2019_12_02_2100_config_exiftool                             | 1     |
| Yes  | 2019_12_15_0700_add_share_button_visible_option             | 1     |
| Yes  | 2019_12_15_1000_config_check_update_every_cat_fix           | 1     |
| Yes  | 2019_12_25_0600_config_exiftool_ternary                     | 1     |
| Yes  | 2020_01_018_2300_config_import_via_symlink                  | 2     |
| Yes  | 2020_01_04_1200_config_has_ffmpeg                           | 1     |
| Yes  | 2020_01_26_1200_config_public_sorting                       | 2     |
| Yes  | 2020_01_28_133201_composer_update                           | 2     |
| Yes  | 2020_02_14_0600_location_decoding                           | 3     |
| Yes  | 2020_03_11_124417_increase_length_photo_type                | 3     |
| Yes  | 2020_03_17_200000_unhide_configs                            | 3     |
| Yes  | 2020_04_19_122905_bump_version                              | 4     |
| Yes  | 2020_04_22_155712_bump_version040002                        | 4     |
| Yes  | 2020_04_29_000250_bump_version040003                        | 4     |
| Yes  | 2020_05_12_114228_rss                                       | 4     |
| Yes  | 2020_05_12_161427_bump_version040005                        | 4     |
| Yes  | 2020_05_19_174233_config_prefer_available_xmp_metadata      | 4     |
| Yes  | 2020_05_26_135052_bump_version040006                        | 4     |
| Yes  | 2020_06_04_104605_config_editor_enabled                     | 5     |
| Yes  | 2020_07_11_104605_config_lossless_optimization              | 6     |
| Yes  | 2020_07_11_184605_update_licences                           | 6     |
| Yes  | 2020_07_26_085322_config_swipe_tolerance                    | 6     |
| Yes  | 2020_07_29_132731_config_local_takestamp                    | 6     |
| Yes  | 2020_08_21_123622_add_smart_tag_album_cols                  | 6     |
| Yes  | 2020_10_09_130043_bump_version040007                        | 6     |
| Yes  | 2020_10_15_104504_add_log_max_num_line                      | 6     |
| Yes  | 2020_10_15_161346_sort_image_per_album                      | 6     |
| Yes  | 2020_11_12_183345_config_password_url_param_for_smart_album | 6     |
| Yes  | 2020_11_19_231553_bump_version040008                        | 6     |
| No   | 2020_12_12_203153_migrate_admin_user                        |       |
| No   | 2020_12_12_203831_create_web_authn_tables                   |       |
| No   | 2020_12_18_162100_bump_version040009                        |       |
| No   | 2020_12_18_162155_add_nsfw_album                            |       |
| No   | 2020_12_18_163800_bump_version040010                        |       |
| No   | 2020_12_24_022307_bump_version040100                        |       |
| No   | 2020_12_26_153220_nested_set_for_albums                     |       |
| No   | 2021_01_09_163715_remove_max_min_takestamps                 |       |
| No   | 2021_01_12_122546_bump_version040200                        |       |
| No   | 2021_01_18_103729_add_album_cover                           |       |
| No   | 2021_01_20_113912_bump_version040201                        |       |
| No   | 2021_01_24_231904_fix-rotation                              |       |
| No   | 2021_01_27_085903_config_map_display_direction              |       |
| No   | 2021_01_30_111736_display_takedate                          |       |
| No   | 2021_02_12_222948_config_upload_processing_limit            |       |
| No   | 2021_02_13_132245_bump_version040202                        |       |
| No   | 2021_02_18_232639_config_public_photos_hidden               |       |
| No   | 2021_03_03_175555_config_remove_image_overlay               |       |
| No   | 2021_04_17_135924_bump_version040300                        |       |
| No   | 2021_05_02_174300_add_filesize_raw_col                      |       |
| No   | 2021_05_12_185726_bump_version040301                        |       |
| No   | 2021_05_13_140700_refactor_size_variants                    |       |
| No   | 2021_05_16_171615_bump_version040302                        |       |
| No   | 2021_05_25_160600_post_revert_fixes                         |       |
| No   | 2021_05_31_201000_convert_filesize_to_bigint                |       |
| No   | 2021_06_01_181900_refactor_timestamps_anew                  |       |
| No   | 2021_06_01_182000_bump_version040304                        |       |
| No   | 2021_06_06_151613_fix-takedate                              |       |
| No   | 2021_06_23_105939_create_notifications_table                |       |
| No   | 2021_06_30_121651_add_email_to_users_table                  |       |
| No   | 2021_06_30_122229_config_new_photos_notification            |       |
| No   | 2021_07_19_134617_bump_version040305                        |       |
| No   | 2021_10_27_133121_fix_confidentiality                       |       |
| No   | 2021_11_16_162058_bump_version040306                        |       |
| No   | 2021_12_03_201242_bump_version040400                        |       |
| No   | 2021_12_04_181200_refactor_models                           |       |
| No   | 2022_01_13_183131_bump_version040500                        |       |
| No   | 2022_01_16_181337_optimize_tables                           |       |
| No   | 2022_02_02_203008_filesize_size_variants                    |       |
| No   | 2022_02_22_194700_fix_sorting_config                        |       |
| No   | 2022_04_06_091900_drop_objectionable_indices                |       |
| No   | 2022_04_13_094611_add_track_short_path_to_album_table       |       |
| No   | 2022_04_16_170724_add_missing_indices                       |       |
| No   | 2022_04_16_174503_bump_version040501                        |       |
| No   | 2022_04_18_150400_add_index_for_delete                      |       |
| No   | 2022_04_18_174417_fix_live_photo_short_path                 |       |
| No   | 2022_07_13_174800_permission_test                           |       |
| No   | 2022_07_24_102214_bump_version040502                        |       |
| No   | 2022_08_03_184746_add_zip_options                           |       |
| No   | 2022_08_06_205701_bump_version040503                        |       |
| No   | 2022_08_06_210757_bump_version040600                        |       |
| Yes  | 2064_12_25_0000_generate_installed_log                      | 2     |
+------+-------------------------------------------------------------+-------+
```

**Comment by gardiol** [comment]
I added the SQL row you sent me and now i only get an
"User is not authenticated" error

**Comment by ildyria** [comment]
In `database/migrations/2020_12_12_203153_migrate_admin_user.php`
```php
	public function up(): void
	{
		$user = new User();
		$user->username = Configs::getValueAsString('username', '');
		$user->password = Configs::getValueAsString('password', '');
		$user->save();

		// User will have an ID which is NOT 0.
		// We want this user to have an ID of 0 as it is the ADMIN ID.
		$user->id = 0;
		$user->save();
	}
```
Can you replace that by:
```php
	public function up(): void
	{
		$user = new User();
		$user->id = 0;
		$user->username = Configs::getValueAsString('username', '');
		$user->password = Configs::getValueAsString('password', '');
		$user->save();

		// User will have an ID which is NOT 0.
		// We want this user to have an ID of 0 as it is the ADMIN ID.
		$user->id = 0;
		$user->save();
	}
```
and try to re run the migration ?

**Comment by ildyria** [comment]
> I added the SQL row you sent me and now i only get an "User is not authenticated" error

Errr that was not what I intended :')

**Comment by gardiol** [comment]
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY' (SQL: insert into `users` (`id`, `username`, `password`, `updated_at`, `created_at`) values (0, $2y$10$LAdeiZwZq8vDrMXsPAF3JeidUqQXHl5Ry5v.qIYyKGBZbih7agLAy, $2y$10$ruv1WvHL/2cTp8xDb7vYh.huY7LpNpFnSpWydu1tRo2AVgZyDajD6, 2022-08-31 08:18:54.282993, 2022-08-31 08:18:54.282993))

It looks like it tries to add the user with key 0 TWICE

**Comment by gardiol** [comment]
Maybe if you send me a SQL query to add an admin user with some standard password i can input on the GUI it will work

**Comment by ildyria** [comment]
`./artisan migrate:status` 

It should still show:
```
| No   | 2020_12_12_203153_migrate_admin_user                        |       |
```

Thus you can do:
```
DELETE FROM users WHERE id = 0;
```
And then re run the `./artisan migrate`, it should then be running. :)

**Comment by gardiol** [comment]
Nope. I have cleared all rows from the "users" table, then:

./artisan migrate
Migrating: 2020_12_12_203153_migrate_admin_user

In ModelDBException.php line 50:
                        
  Updating user failed  
                        

In Connection.php line 712:
                                                                                                                                                                    
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY' (SQL: insert into `users` (`id`, `username`, `password`, `updated_at  
  `, `created_at`) values (0, $2y$10$LAdeiZwZq8vDrMXsPAF3JeidUqQXHl5Ry5v.qIYyKGBZbih7agLAy, $2y$10$ruv1WvHL/2cTp8xDb7vYh.huY7LpNpFnSpWydu1tRo2AVgZyDajD6, 2022-08-  
  31 08:31:03.239265, 2022-08-31 08:31:03.239265))                                                                                                                  
                                                                                                                                                                    

In Connection.php line 501:
                                                                                               
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY'  


And i find an empty row with ID= 0  in the users table

**Comment by ildyria** [comment]
what the hell

**Comment by gardiol** [comment]
I stand corrected: runing artisan migrate from CLI the users table is not modified, and i still get that error

**Comment by gardiol** [comment]
I managed to get that row in the table (my manually inserting it with ID=10 then deleting the empty row with ID=0 that gets created, and manually chaning ID=10 to ID=0) but this did not fix anything as the migrate action will again try to do the same thing and fails

**Comment by ildyria** [comment]
Once you have done that you can just comment the code in the `up()` function by prefixing the `->save()` lines with `//`

**Comment by ildyria** [comment]
the rest should be working fine (hopefully)

**Comment by gardiol** [comment]
Yes it seems now fixed, i will update after the lengthy process is complete, but that step is passed now.
I am missing AUTOINCREMENT on the ID field of that table, but i cannot add it because:

ALTER TABLE `users` CHANGE `id` `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT;
#1833 - Cannot change column 'id': used in a foreign key constraint 'user_album_user_id_foreign' of table 'lychee.user_album'

I am not an Sql expert, do you know how i can fix this? I suspect THIS was the issue at the origin of it all

**Comment by gardiol** [comment]
Correct migration complete!

**Comment by ildyria** [comment]
Maybe you can try:
```
SET FOREIGN_KEY_CHECKS=0;
ALTER TABLE `users` CHANGE `id` `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT;
SET FOREIGN_KEY_CHECKS=1;
```

**Comment by gardiol** [comment]
Thanks i will try. Meanwhile, i was still able to add one user after the migration, so maybe it's not needed or i was wrong.
what is the default admin passsword? just empty?

**Comment by ildyria** [comment]
> Thanks i will try. Meanwhile, i was still able to add one user after the migration, so maybe it's not needed or i was wrong. what is the default admin passsword? just empty?

There is no default admin password, if you previous password and username does not work anymore, just do

`./artisan lychee:reset_Admin` 

You will be prompted with an dialog box on the website to create a new username and password for admin.

**Comment by gardiol** [comment]
It worked. 
thank you! Everything seems to be up and running. Amazing update process... from a very ancient build too!
Keep up the great work.
