### ISSUE TITLE
Is it possible to force a rebuild of all thumbnails?

### ISSUE THREAD

**Issue by gardiol** [LycheeOrg/Lychee#1497]
Is there an artisan command o a GUI command to regenerate thumbs and multiple sizes (small, medium..) for all images?

**Comment by kamil4** [comment]
Sorry; this question seems to have fallen through the cracks, as they say.

There is the `lychee:generate_thumbs` artisan command that can be used to generate the "small" and "medium" variants (as well as their "2x" versions); not sure if that's what you were looking for?

**Comment by gardiol** [comment]
Yes, that's what i was looking for! I deleted by mistake a bunch of small and needed to fix that.
The "thumb" folder is not needed anymore? Is there a way to regenerate that one too? Thank you

**Comment by ildyria** [comment]
`thumb` is used for the square thumbnails which are used as cover albums.

**Comment by gardiol** [comment]
And that cannot be regeneratyed right now? Or already are when needed?

**Comment by ildyria** [comment]
Humm it seems indeed that they are not in the list of _regeneratable_ 
https://github.com/LycheeOrg/Lychee/blob/16bd4c1b1775abab010d9fd544987965f3cd1b98/app/Console/Commands/GenerateThumbs.php#L25-L30

**Comment by ildyria** [comment]
This can easily be fixed though by adding:
```
'thumb' => SizeVariant::THUMB,
'thumb2x' => SizeVariant::THUMB2X,
```

**Comment by ildyria** [comment]
Though in order for those to be regenerated, the respective size-variant entry line should not be present in the database.

**Comment by gardiol** [comment]
Ok, thanks, for now this is closed for me. Think if it could be added in the future, maybe can be useful as well.
