### ISSUE TITLE
Question: Imported images deleted

### ISSUE THREAD

**Issue by kdorris-blm** [LycheeOrg/Lychee#1499]
This is a question and possible bug.

I'm reporting this for another user. This is in regards to an old version 4.3.4. I was unable to find a reported bug specifically addressing this issue. Yes, they should upgrade. However, that is not possible at the moment. In the logs it shows many lines of something like this: "[obfuscated date/time] -- notice  -- App\Models\Photo::predelete -- 184 -- [obfuscated folder name] is a duplicate!"

About the time this happened the user reported dozens of folders and the associated files had disappeared. I am unable to locate 35k images in the db or on the server. Your application was installed by someone else who no longer works here. So this issue has been given to me to solve. If you could give me an idea of what might have triggered this action, I'd be grateful. Please be kind. This is my first post to GH.

### Steps to reproduce the issue
unknown

**Screenshots**
none

### Output of the diagnostics  [REQUIRED]
Diagnostics
    -------
    Warning: Dropbox import not working. dropbox_key is empty.
    Warning: You may experience problems when uploading a photos of large size. Take a look in the FAQ for details.
    Error: PHP intl extension not activated

    System Information
    --------------
    Lychee Version (release):        4.3.4
    DB Version:                      4.3.4
    
    composer install:                --no-dev
    APP_ENV:                         production
    APP_DEBUG:                       false
    
    System:                          WINNT
    PHP Version:                     8
    Max uploaded file size:          209715200
    Max post size:                   0
    MySQL Version:                   8.0.28
    
    Imagick:                         1
    Imagick Active:                  1
    Imagick Version:                 1799
    GD Version:                      bundled (2.1.0 compatible)

    Config Information
    --------------
    version:                         040304
    check_for_updates:               0
    sorting_Photos_col:              id
    sorting_Photos_order:            DESC
    sorting_Albums_col:              title
    sorting_Albums_order:            ASC
    imagick:                         1
    skip_duplicates:                 0
    small_max_width:                 0
    small_max_height:                360
    medium_max_width:                1920
    medium_max_height:               1080
    lang:                            en
    layout:                          1
    image_overlay_type:              desc
    default_license:                 CC0
    compression_quality:             90
    full_photo:                      1
    delete_imported:                 0
    Mod_Frame:                       1
    Mod_Frame_refresh:               30
    thumb_2x:                        1
    small_2x:                        1
    medium_2x:                       1
    landing_page_enable:             0
    landing_owner:                   [obfuscated]
    landing_title:                   [obfuscated]
    landing_subtitle:                [obfuscated]
    landing_facebook:                https://www.facebook.com/JohnSmith
    landing_flickr:                  https://www.flickr.com/JohnSmith
    landing_twitter:                 https://www.twitter.com/JohnSmith
    landing_instagram:               https://instagram.com/JohnSmith
    landing_youtube:                 https://www.youtube.com/JohnSmith
    landing_background:              dist/cat.jpg
    site_title:                      Lychee v4
    site_copyright_enable:           1
    site_copyright_begin:            2019
    site_copyright_end:              2019
    additional_footer_text:          
    display_social_in_gallery:       0
    public_search:                   1
    SL_enable:                       0
    SL_for_admin:                    0
    public_recent:                   0
    recent_age:                      1
    public_starred:                  0
    downloadable:                    0
    photos_wraparound:               1
    map_display:                     1
    zip64:                           1
    map_display_public:              1
    map_provider:                    OpenStreetMap.org
    force_32bit_ids:                 0
    map_include_subalbums:           0
    update_check_every_days:         3
    has_exiftool:                    0
    share_button_visible:            0
    import_via_symlink:              0
    has_ffmpeg:                      0
    location_decoding:               0
    location_decoding_timeout:       30
    location_show:                   1
    location_show_public:            1
    rss_enable:                      0
    rss_recent_days:                 7
    rss_max_items:                   100
    prefer_available_xmp_metadata:   0
    editor_enabled:                  1
    lossless_optimization:           0
    swipe_tolerance_x:               150
    swipe_tolerance_y:               250
    local_takestamp_video_formats:   .avi|.mov
    log_max_num_line:                99999
    unlock_password_photos_with_url_param: 0
    nsfw_visible:                    1
    nsfw_blur:                       0
    nsfw_warning:                    0
    nsfw_warning_admin:              0
    map_display_direction:           1
    album_subtitle_type:             oldstyle
    upload_processing_limit:         4
    public_photos_hidden:            1

### Browser and system
unknown

**Comment by d7415** [comment]
Windows and old versions are never a good start.

But that log message is called when Lychee is *not* deleting a photo (on the filesystem), despite the user requesting it.

It sounds to me as if someone has manually deleted the photos. Someone more familiar may have more insight.

**Comment by kdorris-blm** [comment]
Thank you for the feedback.

**Comment by nagmat84** [comment]
As @d7415 said, the conditions are far from optimal. I do not even understand what the actual problem is.

The log message you are quoting was used to indicate that an image file is _not_ going to be deleted, because it is still used somewhere else. This log message is not an error, but as you can see from the logs only counts as a _notice_. This is pretty normal. Seeing this message several thousand times can still be normal, if someone duplicated several huge albums (hence all the photos inside them were duplicated, too) and then some of the albums are deleted again. Newer versions of Lychee are much less verbose in this regard.

Hence, so far no problem.

But you lost your photos anyway? Correct? Is the following summary of your problem accurate?

You deleted duplicated photos, but in addition to the duplicates the original photos were accidentally and falsely deleted, too, despite the fact that Lychee correctly identified them as duplicates.

**Comment by kdorris-blm** [comment]
Thanks. I don't know if the user deleted duplicates/originals or not. Yes, the original photos disappeared somehow despite the application correctly identifying them as duplicates at some point.

**Comment by nagmat84** [comment]
> Thanks. I don't know if the user deleted duplicates/originals or not.

That makes the issue rather more unclear than before. If I understand correctly, chances are that the user simply deleted the photos and there has been no bug involved at all.

For example, lets say a user simply selected a set of photos for deletion like this A, A', A'', B, B', C, D, D', D'', ... Let identical letters with a hyphen denote instances of the same photo. In this case you would see the log message from above 5 times, namely for A, A', B, D and D'. Nonetheless, the real image file would be deleted as soon as the last instance of each photo had beed deleted, i.e A'', B', C and D''.

Hence, I am not sure whether we really face a bug here or only a misfortune action triggered by a user who unintentionally deleted too many photos. (No offense.)

I guess the only chance you have is to restore a backup. I hope you have one.

**Comment by kdorris-blm** [comment]
I admit this isn't a clear-cut case and sub-optimal conditions. If it was clearer I probably could have figured this out on my own. I wanted to reach out to see if the dev community could help. I'm not familiar with the program and couldn't find any known issues. I understand that chances are if this were an inherent issue, it would have triggered a lot of comments. I get all of that. I'm just trying to put the pieces of the puzzle together to try to understand how the program works. Thank you all for your input.

**Comment by kamil4** [comment]
So are the photos in question missing from the `public/uploads/big/` folder (where Lychee stores the original files)? Are their records also missing from the `photos` table in the database? If the answer is "yes" to both, then they are indeed gone for good and a backup is your only option. Even if the answer is "yes" to only one, you are in trouble because either you are missing the photos themselves or you are missing the metadata from the db that could be used to, e.g., map the random names that Lychee stores the photos under to the meaningful photo titles/descriptions.

**Comment by kdorris-blm** [comment]
@kamil4 Thank you for the question. Yes to both: missing from server and missing from DB. The files were brought over from somewhere else for the import so yes, we have a backup, we have the original files stored elsewhere. We can easily restore them, but we want to troubleshoot or understand why they were deleted before we re-import 35,000+ images again or go through a db restoration.
