### ISSUE TITLE
[Enhancement] "captions"

### ISSUE THREAD

**Issue by mlapaglia** [LycheeOrg/Lychee#1517]
I am using lychee to share baby pictures with my family and friends. Could the ability to add a one line caption be possible? Maybe when clicking on the image showing it along the bottom of the image?

**Comment by kamil4** [comment]
I may be misunderstanding your question, but don't we have that already?

You can add descriptions to individual photos (via the info sidebar or the `d` keyboard shortcut) and then you can display them at the bottom by setting the "Photo overlay" in the settings to "Description" (this is also easily adjustable by the viewer by using the `o` keyboard shortcut or simply by repeatedly clicking on a photo).

**Comment by mlapaglia** [comment]
yep you're right, i'm blind, thanks!
