### ISSUE TITLE
reset password

### ISSUE THREAD

**Issue by centoyas** [LycheeOrg/Lychee#1518]
Hi,
i freshly installed Lychee ( via git clone https://github.com/electerious/Lychee.git ) but i already lost my password.
i type :
```
root@server:/var/www/html/Lychee# sudo -E -u www-data php artisan lychee:reset_admin
Could not open input file: artisan
```

here's the contents of files :

> root@server:/var/www/html/Lychee# ls -lrt
> total 204
> -rw-r--r-- 1 root root  4993  8 sept. 00:27 README.md
> -rw-r--r-- 1 root root  1074  8 sept. 00:27 LICENSE
> drwxr-xr-x 2 root root  4096  8 sept. 00:27 dist
> -rw-r--r-- 1 root root  3219  8 sept. 00:27 CODE_OF_CONDUCT.md
> drwxr-xr-x 4 root root  4096  8 sept. 00:27 plugins
> drwxr-xr-x 6 root root  4096  8 sept. 00:27 php
> -rw-r--r-- 1 root root 60906  8 sept. 00:27 index.html
> -rw-r--r-- 1 root root 33412  8 sept. 00:27 favicon.ico
> drwxr-xr-x 2 root root  4096  8 sept. 00:27 docs
> -rw-r--r-- 1 root root 58442  8 sept. 00:27 view.php
> drwxr-xrwx 6 root root  4096  8 sept. 00:27 uploads
> drwxr-xr-x 5 root root  4096  8 sept. 00:27 src
> -rw-r--r-- 1 root root   136  8 sept. 00:27 robots.txt
> drwxr-xrwx 2 root root  4096  8 sept. 01:27 data
> 

> root@server:/var/www/html/Lychee/php# ls -lrt
> total 28
> drwxr-xr-x 2 root root 4096  8 sept. 00:27 Modules
> -rwxr-xr-x 1 root root 2463  8 sept. 00:27 index.php
> drwxr-xr-x 2 root root 4096  8 sept. 00:27 helpers
> -rw-r--r-- 1 root root 1593  8 sept. 00:27 define.php
> drwxr-xr-x 2 root root 4096  8 sept. 00:27 database
> -rw-r--r-- 1 root root  482  8 sept. 00:27 autoload.php
> drwxr-xr-x 2 root root 4096  8 sept. 00:27 Access

and find nothing else in depth altrought
```

root@server:/var/www/html/Lychee# find ./ -iname artisan
root@server:/var/www/html/Lychee#

```

what i'm doing wrong pls?

**Comment by ildyria** [comment]
From the directory structure, this looks a lot like like https://github.com/LycheeOrg/Lychee-v3
Can you do a `cat version.md` ?
If my guess is right, you will be very interested in https://lycheeorg.github.io/docs/upgrade.html

**Comment by centoyas** [comment]
ok thank's you, i just did the manipulations and now i'm 
```
root@server:/var/www/html/Lychee# cat version.md
4.6.0
```

and i have it !! but error is now : 

> root@server:/var/www/html/Lychee# sudo -E -u www-data php artisan lychee:reset_admin
> PHP Warning:  require(/var/www/html/Lychee/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/Lychee/artisan on line 18
> PHP Fatal error:  require(): Failed opening required '/var/www/html/Lychee/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/Lychee/artisan on line 18


edit : i ' m currently running the 
`composer install --no-dev`
and 
`composer update`
and resolving my problem with composer.
thanks for helped me :)

**Comment by d7415** [comment]
> via git clone https://github.com/electerious/Lychee.git

Please check the repo URL against the one you used.
