### ISSUE TITLE
After Update from V4.4.0 Message 220 | Migration results "Nothing to Migrate"

### ISSUE THREAD

**Issue by wlan4you** [LycheeOrg/Lychee#1521]
After Update from V4.4.0 Message 220 | Migration results "Nothing to Migrate"

I Installed first on February or March new System on the Website.
Everything is running and i uploaded around 2500 Pictires in around 20 subfolders.
Now i see "New Update available".
Ok, i check the website and found new V4.6 Version.
I download the ZIP and extract them.
Upload via FTP without:
Replace all existing files, excluding public/uploads/, public/dist/user.css and .env (and database/database.sqlite if using SQLite as your database)

After upload, i go to my Lynchee Page and he ask me for user and passwort.
I give hom that and after that i become a white screen with this Text:

220 | Migration results "Nothing to Migrate."

And every time i com back to my page, he jumps automaticly to this page:  Webseite.info/migrate

What are my fault? ANd how can i solve that?

Thanks for helping me

### Browser and system
Firefox V104.0.2 Windos 10 H2

**Comment by ildyria** [comment]
Very weird behaviour.

**Comment by ildyria** [comment]
This is most likely resolved with the newer versions + migrations available + stronger code.
