### ISSUE TITLE
"SQLSTATE[42S02]: Base table or view not found: 1146 Table 'lychee.pages' doesn't exist" After update

### ISSUE THREAD

**Issue by romleinster** [LycheeOrg/Lychee#1523]
I just ran `git pull` `composer install --no-dev` and `php artisan migrate` all successfully on a running instance version 4.6. Now I'm  getting this error trying to load /Lychee/public/:
```

500
HttpException

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'lychee.pages' doesn't exist (SQL: select * from 'pages' where 'in_menu' = 1 and 'enabled' = 1 order by order asc)
```

After the 2022_08_27_103010_drop_page_support migration removes the pages table, am I missing some update to the code that removes references to that table?

Any ideas whats up and how to restore my instance to functioning?

My diagnostics as of before I ran the update:

```Diagnostics
-------
Warning: Dropbox import not working. dropbox_key is empty.




System Information
--------------
Lychee Version (git):            master (04b1522) -- Up to date (32 minutes ago).
DB Version:                      4.6.0

composer install:                --no-dev
APP_ENV:                         production
APP_DEBUG:                       false

System:                          Linux
PHP Version:                     8.1.9
PHP User agent:                  Lychee/4 (https://lycheeorg.github.io/)
Timezone:                        America/New_York
Max uploaded file size:          500M
Max post size:                   500M
Max execution time:              200
MySQL Version:                   10.8.4-MariaDB-log

exec() Available:                yes
Imagick Available:               1
Imagick Enabled:                 1
Imagick Version:                 1808
GD Version:                      2.3.3




Config Information
--------------
version:                         040600
check_for_updates:               0
sorting_photos_col:              taken_at
sorting_photos_order:            ASC
sorting_albums_col:              max_taken_at
sorting_albums_order:            ASC
imagick:                         1
skip_duplicates:                 0
small_max_width:                 0
small_max_height:                360
medium_max_width:                1920
medium_max_height:               1080
lang:                            en
layout:                          1
image_overlay_type:              desc
default_license:                 none
compression_quality:             90
full_photo:                      1
delete_imported:                 0
Mod_Frame:                       1
Mod_Frame_refresh:               30
thumb_2x:                        1
small_2x:                        1
medium_2x:                       1
landing_page_enable:             1
landing_owner:                   
landing_title:                    
landing_subtitle:                
landing_facebook:                
landing_flickr:                  
landing_twitter:                 
landing_instagram:               
landing_youtube:                 
landing_background:              
site_title:                 
site_copyright_enable:           1
site_copyright_begin:            
site_copyright_end:              2022
additional_footer_text:          
display_social_in_gallery:       0
public_search:                   0
SL_enable:                       0
SL_for_admin:                    0
public_recent:                   0
recent_age:                      0
public_starred:                  0
downloadable:                    0
photos_wraparound:               1
map_display:                     1
zip64:                           1
map_display_public:              1
map_provider:                    Wikimedia
force_32bit_ids:                 0
map_include_subalbums:           1
update_check_every_days:         3
has_exiftool:                    0
share_button_visible:            0
import_via_symlink:              0
has_ffmpeg:                      1
location_decoding:               1
location_decoding_timeout:       30
location_show:                   1
location_show_public:            0
rss_enable:                      0
rss_recent_days:                 7
rss_max_items:                   100
prefer_available_xmp_metadata:   0
editor_enabled:                  1
lossless_optimization:           0
swipe_tolerance_x:               150
swipe_tolerance_y:               250
local_takestamp_video_formats:   .avi|.mov
log_max_num_line:                1000
unlock_password_photos_with_url_param: 0
nsfw_visible:                    1
nsfw_blur:                       0
nsfw_warning:                    0
nsfw_warning_admin:              0
map_display_direction:           1
album_subtitle_type:             oldstyle
upload_processing_limit:         4
public_photos_hidden:            0
new_photos_notification:         0
legacy_id_redirection:           1
zip_deflate_level:               6```

**Comment by romleinster** [comment]
Not sure what I did wrong, but it looks like trying to load the page again in the morning has solved this issue.

The only problem I still notice after update is that the gallery link on the landing page (in the upper right corner) no longer links to the root of my app. I have my app served at https://my.domain.com/Lychee/public and instead of linking to https://my.domain.com/Lychee/public/gallery, it links to https://my.domain.com/gallery. Is this a setting I can change? My app URL is set properly in .env not sure where else to look

**Comment by ildyria** [comment]
> I have my app served at https://my.domain.com/Lychee/public and instead of linking to

That is definitively NOT something you should do. The reason being that if you miss configure your server, the `.env` file can be accessible by mistake. That file contains the secrets required to connect to SQL, encrypt the cookies etc.

I would strongly advise you to redirect https://lychee.my.domain.com/ to the `public` directory, thus hiding the Lychee root. This will also fix your https://my.domain.com/gallery problem as it will be converted to https://lychee.my.domain.com/gallery.

**Comment by romleinster** [comment]
Is there a way to configure that link though? I can't serve from a subdomain and I have an existing app served from the root url (my.domain). I can set up an alias and serve Lychee from my.domain/photos but that link on the landing page still points to the wrong place (my.domain/gallery).

**Comment by ildyria** [comment]
> I have my app served at [my.domain.com/Lychee/public](https://my.domain.com/Lychee/public) and instead of linking to [my.domain.com/Lychee/public/gallery](https://my.domain.com/Lychee/public/gallery), it links to [my.domain.com/gallery](https://my.domain.com/gallery). Is this a setting I can change? My app URL is set properly in .env not sure where else to look

@romleinster can you test against latest master and see if that behaviour is still present ?

**Comment by romleinster** [comment]
> > I have my app served at [my.domain.com/Lychee/public](https://my.domain.com/Lychee/public) and instead of linking to [my.domain.com/Lychee/public/gallery](https://my.domain.com/Lychee/public/gallery), it links to [my.domain.com/gallery](https://my.domain.com/gallery). Is this a setting I can change? My app URL is set properly in .env not sure where else to look
> 
> @romleinster can you test against latest master and see if that behaviour is still present ?

The link works again in latest version. Thanks!

**Comment by ildyria** [comment]
noice!
