### ISSUE TITLE
Last version 4.6.0  with PHP 8 and 8.1 ,  Create ALBUM comes with error:  2022-09-26 17:36:39 UTC -- error   -- PDOStatement::execute -- 501 -- SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'legacy_id' at row 1 

### ISSUE THREAD

**Issue by NiekPer** [LycheeOrg/Lychee#1532]
### Detailed description of the problem [REQUIRED]
*A clear and concise description of what the bug is.*

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
4. See error*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

### Output of the diagnostics  [REQUIRED]
*(Settings => Diagnostics or https://example.com/Diagnostics or `php artisan lychee:diagnostics`)*

**Comment by ildyria** [comment]
Please follow the template, as is this is pretty much useless and very unhelpful.

**Comment by nagmat84** [comment]
Please fill out the provided template, in particular the diagnostic. I assume the problem is the typical 32-bit problem.

**Comment by NiekPer** [comment]
Diagnostics
    -------
    Warning: Dropbox import not working. dropbox_key is empty.
    Warning: You may experience problems when uploading a photo of large size. Take a look in the FAQ for details.
    Warning: You may experience problems when uploading a photo of large size. Take a look in the FAQ for details.
    Warning: You may experience problems when uploading a photo of large size or handling many/large albums. Take a look in the FAQ for details.
    Warning: Pictures that are rotated lose their metadata! Please install Imagick to avoid that.
    Info: Latest version of PHP is 8.1



    System Information
    --------------
    Lychee Version (release):        4.6.0
    DB Version:                      4.6.0
    
    composer install:                --no-dev
    APP_ENV:                         production
    APP_DEBUG:                       false
    
    System:                          Linux
    PHP Version:                     8.0.13
    PHP User agent:                  Lychee/4 (https://lycheeorg.github.io/)
    Timezone:                        Europe/Amsterdam
    Max uploaded file size:          2M
    Max post size:                   8M
    Max execution time:              120
    MySQL Version:                   10.3.24-MariaDB-cll-lve
    
    exec() Available:                yes
    Imagick Available:               -
    Imagick Enabled:                 1
    Imagick Version:                 -
    GD Version:                      2.2.5



    Config Information
    --------------
    version:                         040600
    check_for_updates:               0
    sorting_photos_col:              title
    sorting_photos_order:            ASC
    sorting_albums_col:              created_at
    sorting_albums_order:            ASC
    imagick:                         1
    skip_duplicates:                 0
    small_max_width:                 0
    small_max_height:                360
    medium_max_width:                1920
    medium_max_height:               1080
    lang:                            nl
    layout:                          1
    image_overlay_type:              none
    default_license:                 none
    compression_quality:             90
    full_photo:                      1
    delete_imported:                 0
    Mod_Frame:                       1
    Mod_Frame_refresh:               30
    thumb_2x:                        1
    small_2x:                        1
    medium_2x:                       1
    landing_page_enable:             0
    landing_owner:                   HJdeDoper
    landing_title:                   HJdeDoper
    landing_subtitle:                Cats, Dogs & Humans Photography
    landing_facebook:                https://www.facebook.com/JohnSmith
    landing_flickr:                  https://www.flickr.com/JohnSmith
    landing_twitter:                 https://www.twitter.com/JohnSmith
    landing_instagram:               https://instagram.com/JohnSmith
    landing_youtube:                 https://www.youtube.com/JohnSmith
    landing_background:              dist/cat.jpg
    site_title:                      Foto-album
    site_copyright_enable:           0
    site_copyright_begin:            2022
    site_copyright_end:              2022
    additional_footer_text:          Foto-album
    display_social_in_gallery:       0
    public_search:                   0
    SL_enable:                       0
    SL_for_admin:                    0
    public_recent:                   0
    recent_age:                      1
    public_starred:                  0
    downloadable:                    0
    photos_wraparound:               1
    map_display:                     0
    zip64:                           1
    map_display_public:              0
    map_provider:                    Wikimedia
    force_32bit_ids:                 0
    map_include_subalbums:           0
    update_check_every_days:         3
    has_exiftool:                    0
    share_button_visible:            0
    import_via_symlink:              0
    has_ffmpeg:                      0
    location_decoding:               0
    location_decoding_timeout:       30
    location_show:                   0
    location_show_public:            0
    rss_enable:                      0
    rss_recent_days:                 7
    rss_max_items:                   100
    prefer_available_xmp_metadata:   0
    editor_enabled:                  1
    lossless_optimization:           0
    swipe_tolerance_x:               150
    swipe_tolerance_y:               250
    local_takestamp_video_formats:   .avi|.mov
    log_max_num_line:                1000
    unlock_password_photos_with_url_param: 0
    nsfw_visible:                    0
    nsfw_blur:                       0
    nsfw_warning:                    0
    nsfw_warning_admin:              0
    map_display_direction:           1
    album_subtitle_type:             oldstyle
    upload_processing_limit:         4
    public_photos_hidden:            1
    new_photos_notification:         0
    legacy_id_redirection:           1
    zip_deflate_level:               6

**Comment by nagmat84** [comment]
Please try to set `force_32bit_ids` to `1`  and retry. I assume that your PHP version is 64bit, but your MySQL version only 32bit.

**Comment by NiekPer** [comment]
Yes !!  it works,  thank you verry much for the quick response !  Super !
