### ISSUE TITLE
Upload of pictures is hanging after hundreds of successful uploads

### ISSUE THREAD

**Issue by bjornsmith** [LycheeOrg/Lychee#1549]
Hi!
I have a new fresh installation of latest release on a new Ubuntu 22.04 server. It has been working perfectly up to a certain point when the upload of photos hangs. The upload dialog complain about the file format, but I think that is not the case. I can take any of my jpg files which gives the same result. It appears to be volume/quantity related, but I'm not sure.

Thank you!

![Screenshot 2022-10-05 at 11 43 03](https://user-images.githubusercontent.com/6472220/194033502-c94463ae-9c8e-451e-9814-fba5a8939bd4.png)
![Screenshot 2022-10-05 at 11 43 57](https://user-images.githubusercontent.com/6472220/194033568-ac407191-18a6-4854-aabc-6f94e373d57b.png)
![Screenshot 2022-10-05 at 11 45 04](https://user-images.githubusercontent.com/6472220/194033661-17f970c7-f681-498e-8adb-7ee71e661d8b.png)

**Comment by kamil4** [comment]
Just to make sure that I understand: it now fails when you try to upload _any_ jpg file?

I'm wondering if you might be running out of space in `/tmp` or other similar location (`/var/tmp`, etc). Can you verify that with `df`? When uploading, the files are first put in a temporary location, and only later moved to `Lychee/public/uploads/`. So if you were running out of space in the temporary location, resulting in truncated files, that could explain the `File format not supported` message. Also see if you get any relevant error/warning messages in the logs of your web browser...

**Comment by bjornsmith** [comment]
root@photoarchive:/var/log/apache2# df
Filesystem     1K-blocks    Used Available Use% Mounted on
tmpfs             202316    1184    201132   1% /run
/dev/sda2       20529768 8654432  10810488  45% /
tmpfs            1011576       0   1011576   0% /dev/shm
tmpfs               5120       0      5120   0% /run/lock
tmpfs             202312       0    202312   0% /run/user/1000

And the apache logo are quiet when this occurs.

**Comment by bjornsmith** [comment]
Hi kamil4!

For your info, I succeeded to upload some more jpg files, but now it's stuck again in the same way as before. Is there some way of getting diagnostics logged?

**Comment by bjornsmith** [comment]
Believe it or not, but the problem was browser related. I've been using Safari on a fairly new Mac. Using Crome it works fine and the problem is gone!

**Comment by kamil4** [comment]
Weird... I mean, Safari does have a reputation of being a modern day Internet Explorer of web browsers, but still...

**Comment by qwerty287** [comment]
@bjornsmith If you can still reproduce it, it would be good to know if there's something in the JS console of Safari. Can you try to look this up?
