### ISSUE TITLE
[Enhancement] Option to skip 2775 permission checks in diagnostics

### ISSUE THREAD

**Issue by sigulete** [LycheeOrg/Lychee#1555]
My installation is using S3 storage and when I run diagnostics, the script can take literally hours to check the 2775 permissions in my gallery. The reason is because S3 storage badly under-perform with operations like listing.

Considering that this permission is not implemented in a S3 bucket anyways, I would like to skip this part of the script.

For now, I can't run diagnostics at all.

**Comment by ildyria** [comment]
I had a look, our permission check code is as follows:
```php
$disks = [
	SizeVariantNamingStrategy::getImageDisk(),
	Storage::disk(SymLink::DISK_NAME),
];

foreach ($disks as $disk) {
	if ($disk->getDriver()->getAdapter() instanceof LocalFlysystem) {
		$this->checkDirectoryPermissionsRecursively($disk->path(''), $errors);
	}
}
```

So I am not sure what is blocking. Can you tell us more about your S3 storage solution?

**Comment by nagmat84** [comment]
That is rather easy. PHP does not recognize that the files are located in a remote location, because the OS mounts the storage. Hence, from the perspective of Lychee (as for every other user land application) the location is local, because the network operations are handled on the kernel level.
