### ISSUE TITLE
Big albums not loading

### ISSUE THREAD

**Issue by saulius-s** [LycheeOrg/Lychee#1561]
Hi Team,

I got stuck with the issue where all huge albums not loading. They contain 2/3K various photos on every. Smaller albums working well. Lychee log does not showing any error but browser returns:

![Screenshot 2022-10-19 at 14 35 28](https://user-images.githubusercontent.com/32930113/196681155-18a15acc-72b1-4ee8-9360-e62fb23c1ef8.png)

While there was no issue earlier I did not catch from which version it stopped working.

![Screenshot 2022-10-19 at 14 53 51](https://user-images.githubusercontent.com/32930113/196683862-c8e2e8b0-4ec6-42d2-aa44-37a7be9ce2fc.png)

Same happens with all browsers.

Raspbian GNU/Linux 11 (bullseye) 32bit

**Comment by nagmat84** [comment]
Please update your MySQL version and PHP version to at least 8.1.13 (you have 8.1.11). This is a bug in the PHP MySQL adapter which can not handle replies larger than 1000 items. It is a memory corruption bug in C. That is nothing what we can do about.
