### ISSUE TITLE
Install.php

### ISSUE THREAD

**Issue by ghost** [LycheeOrg/Lychee#1565]
Why am I not able to install this script anymore as I use to be able to without all the extra headaches? I use to be able to upload the script to my paid hosting & just type in the address/install.php & put the information I setup for it threw my MySQL, and User. Now its so complicated I have stopped using it. I love the original script but this is a royal pain. Can I get the older version back or a working version that allows me to install as I am use to?

**Comment by nagmat84** [comment]
What exactly is your problem? We still have a web-based installer. Which step is causing you problems?

**Comment by kamil4** [comment]
What is the last version that worked for you? If you used v3 before, then we have it archived here: https://github.com/LycheeOrg/Lychee-v3. No guarantees that it still works, though (there've been many changes to PHP, for instance).

**Comment by ghost** [comment]
I found 3.1.6 & have it installed. I would like to use the latest version
of it but I don't understand how to upgrade it. I read it but get a headache
trying to understand all that.

Working Live version of 3.1.6,
https://images.awfordjr.net

https://images.awfordjr.net/uploads/big/b3eb057866fc6b1bb6a45d4854dd3565.png

Am I suppose to upload the entire content of this zip same as I did with older version? That is a lot of files! Surely you can see what I am asking? There is no way that I am suppose to upload all that! Perhaps just the "public" directory? I am so confused...

**Comment by AWFordJr** [comment]
https://images.awfordjr.net - Sorry I meant to include this

**Comment by AWFordJr** [comment]
When I upload the newest version I don't get the option to install like I do with the older 3.0 versions of it. I have a 3 version setup now at images.awfordjr.net I would like to use the latest versions but I get errors when trying to do so.

**Comment by ghost** [comment]
Let me try to better explain what I am asking for & what I am trying to do here. Most PHP scripts comes in a an archive like zip or whatever right? Well in the case of "Lychee 3.1.6" I download the archive, extract it some place, then upload it to the directory, sub domain, ..., whatever then install it. These newer versions do not work like that or do not seem to. I am old school I don't know nothing about git or whatever. I just want the normal simple extract, upload, and install like with Lychee 3.1.6 It's so much easier then all this other stuff you have going on here...

I know how to make a database, user, pass & input all that when asked by a script. I don't understand whatever this other method is that is needed. I have never had issues installing scripts in the past.

I have begged my host to include Lychee in their preinstallers but they never reply... In my option Lychee is the best Image Gallery out there & I have used quite a few. I sometimes wish videos were an option to upload also, but other then that its awesome. I miss the original creator they never made things so complicated!

**Comment by d7415** [comment]
> I found 3.1.6 & have it installed. I would like to use the latest version

Ok, that's *very* old.

> These newer versions do not work like that or do not seem to.

They do, or at least they should.
https://lycheeorg.github.io/docs/installation.html#from-release

Edit to add: [This](https://lycheeorg.github.io/docs/upgrade.html) page may also be of use, but I can't say for sure that it will work from 3.1.6.

**Comment by ghost** [comment]
I have seen those pages already it wasn't anything to do with my being lazy about it, I just do not understand those methods. I have a lot of problems with my memory past few years that make it impossible to learn new things. Its not a matter of laziness or not wanting to. Ive always loved learning new things in the past when it was not an issue for me mentally.

Is there not a way to get the files in a zip old school? Like I brought up about the current version I am running? I am sure I am missing out on some great new features, but if not I will just stick to the 3.1.6 I am not trying to make things complicated, but if you feel that I am just say so & I will stick with what I have.

Either way thank you very much for your time, help, and trying to support my insanity...

**Comment by d7415** [comment]
> Is there not a way to get the files in a zip old school?

That's what the page I linked was for. There's a zip [here](https://github.com/LycheeOrg/Lychee/releases/download/v4.6.1/Lychee.zip) that will extract Lychee v4.6.1 with the web installer.

**Comment by ghost** [comment]
I did I just got a blank page with no options. I even changed between different versions of PHP no luck so I gave up. I will just direct link images & videos from now on. Good luck with the script. It really is the best on the net & I have tried a good bit of all the popular ones even some of the paid ones. I just dont understand a lot of the new coding so I will stick to what I know & understand. Best wishes!

**Comment by nagmat84** [comment]
I assume this issue can be closed then?

I think it is very unfortunate that we were not able to help you. @d7415 pointed you to the link with the ZIP archive and the step-by-step instruction how to install Lychee from a released ZIP. Maybe the instructions can be improved. (There is always ways for improvement.) However, unless you are telling us _specifically_ which step did not work for you our which step you did not understand, we cannot help.

**Comment by qwerty287** [comment]
Going to close (user account is deleted)
