### ISSUE TITLE
HttpException An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1 near "(": syntax error

### ISSUE THREAD

**Issue by shutwin** [LycheeOrg/Lychee#1568]
```
HttpException
An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1 near "(": syntax error
```
How to solve this problem ， i use mysql, install 

![微信截图_20221027095047](https://user-images.githubusercontent.com/91580072/198172388-eb75d383-cda7-4e18-bf11-b3ed17d8a74b.png)
![微信截图_20221027095108](https://user-images.githubusercontent.com/91580072/198172396-04fd4928-3bda-4cc6-80e0-8a82670cfdb1.png)

**Comment by qwerty287** [comment]
Please provide more information.
- How did you install Lychee?
- OS, PHP and MySQL version
- After which installation step this occurs?
