### ISSUE TITLE
Unable to add photo, unable to fork [command -v exiftool]

### ISSUE THREAD

**Issue by pchampio** [LycheeOrg/Lychee#1596]
### Unable to add photo

```log
2022-11-23 12:35:02 UTC -- error   -- Illuminate\Foundation\Bootstrap\HandleExceptions::Illuminate\Foundation\Bootstrap\{closure} -- 38 -- exec(): Unable to fork [command -v exiftool]
2022-11-23 12:35:02 UTC -- error   -- App\Metadata\Extractor::createFromFile -- 97 -- exec(): Unable to fork [command -v exiftool]; caused by
```

### Output of the diagnostics  [REQUIRED]
Was unable to obtained the diagnostics.
(I'm running lychee with lychee-docker)

**Comment by d7415** [comment]
"Unable to fork" is usually a resource limit. Possibly one you've configured for Docker, possibly on the host.

re diagnostics, did they just not load? Have you tried running the supplied shell command from inside the container?

**Comment by pchampio** [comment]
The output of the diagnostics shell is the following:
```
❯ dc exec lychee php artisan lychee:diagnostics



In exec.php line 38:

  exec(): Unable to fork [command -v cwebp]

```

Host limit
```
❯ ulimit -a # On Host
-t: cpu time (seconds)              unlimited
-f: file size (blocks)              unlimited
-d: data seg size (kbytes)          unlimited
-s: stack size (kbytes)             8192
-c: core file size (blocks)         0
-m: resident set size (kbytes)      unlimited
-u: processes                       7687
-n: file descriptors                1024
-l: locked-in-memory size (kbytes)  65536
-v: address space (kbytes)          unlimited
-x: file locks                      unlimited
-i: pending signals                 7687
-q: bytes in POSIX msg queues       819200
-e: max nice                        0
-r: max rt priority                 0
-N 15:                              unlimited
```


Container limit
```
❯ dc exec lychee sh
# ulimit -a # In container
time(seconds)        unlimited
file(blocks)         unlimited
data(kbytes)         unlimited
stack(kbytes)        8192
coredump(blocks)     unlimited
memory(kbytes)       unlimited
locked memory(kbytes) 65536
process              unlimited
nofiles              1048576
vmemory(kbytes)      unlimited
locks                unlimited
rtprio               0
```

Before the big lychee refactor, 'exiftool forking' worked (if it used it)

**Comment by pchampio** [comment]
A more concrete error is the following `“fork retry: Resource temporarily unavailable”`.

Upon inspection, it is related to my server and container.
As even with `apt update` commands,  executed without any lychee config (`docker run --rm -it --entrypoint '' lycheeorg/lychee:dev bash`) it throws an error.
Whereas `apt update` on my local computer does not throw any errors.

---

However older version of the container did not had this issue.


```bash
~/APP me@server
❯ docker run --rm -it --entrypoint '' lycheeorg/lychee:dev bash
root@1406debbf9e0:/var/www/html/Lychee# apt update
Get:1 http://deb.debian.org/debian bookworm InRelease [164 kB]
Get:2 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
Get:3 http://deb.debian.org/debian bookworm-updates InRelease [49.6 kB]
Get:4 http://deb.debian.org/debian bookworm/main amd64 Packages [8761 kB]
Fetched 9022 kB in 2s (4486 kB/s)
Reading package lists... Done
E: Problem executing scripts APT::Update::Post-Invoke 'rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true' 
E: Sub-process returned an error code  # <-------------------- HERE
root@1406debbf9e0:/var/www/html/Lychee# 
root@1406debbf9e0:/var/www/html/Lychee# 
exit
~/APP
~/APP me@server

❯ docker run --rm -it --entrypoint '' lycheeorg/lychee:testing-1436240777 bash 
dockerUnable to find image 'lycheeorg/lychee:testing-1436240777' locally
testing-1436240777: Pulling from lycheeorg/lychee
7d63c13d9b9b: Pull complete 
447883d0678f: Pull complete 
3afcc8b5d7b5: Pull complete 
ffb73062252d: Pull complete 
6d4bae5cdd15: Pull complete 
97fdeb884a72: Pull complete 
Digest: sha256:e20d188b7e8e919dd0b1feac77348b4b158f1d6f0d530fff4c9a6f7ead2556a8
Status: Downloaded newer image for lycheeorg/lychee:testing-1436240777
root@31ca3f28afc5:/var/www/html/Lychee# apt update
Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
Get:2 http://security.debian.org/debian-security bullseye-security InRelease [48.4 kB]
Get:3 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
Get:4 http://deb.debian.org/debian bullseye/main amd64 Packages [8184 kB]
Get:5 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [14.6 kB]
Get:6 http://security.debian.org/debian-security bullseye-security/main amd64 Packages [206 kB]
Fetched 8613 kB in 2s (3898 kB/s)                         
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
91 packages can be upgraded. Run 'apt list --upgradable' to see them. # <------- everything fine
root@31ca3f28afc5:/var/www/html/Lychee# 
```

**Comment by brentkearney** [comment]
I have run into the [same issue](https://github.com/LycheeOrg/Lychee-Docker/issues/143) with 4.7.0. Did you find a solution?

**Comment by pchampio** [comment]
Nope, I didn't found a solution.

**Comment by brentkearney** [comment]
> "Unable to fork" is usually a resource limit. Possibly one you've configured for Docker, possibly on the host.
> 
> re diagnostics, did they just not load? Have you tried running the supplied shell command from inside the container?

Usually, but in this case, most of the functions in the container still work. The albums I created with a previous version of lychee, before pulling images of new versions, are still there, and I can view the images, download them, etc.. So those are forking processes fine. I just can't upload new photos or run the Diagnostics link.

Next I'm going to try downgrading to a previous image version. Hopefully the database changes from migrations don't break everything!

**Comment by d7415** [comment]
> I can view the images, download them, etc.. So those are forking processes fine.

None of these actions involve starting an external process. Uploading new photos (depending on settings) and running Diagnostics do.

**Comment by ferozsalam** [comment]
I'm seeing this issue as well – load average on my machine is <0.2, memory usage is at ~50%. This is a recent development that occurred when I upgraded to a newer version of Lychee. I've run previous versions for a few years without issue.

My configuration is very similar to that posted by @pchampio. Restarting doesn't meaningfully solve the problem – it's present as soon as the containers are running, which suggests to me that it isn't a resources issue.

**Comment by d7415** [comment]
> which suggests to me that it isn't a resources issue

To be clear, resources are not limited to CPU and memory.

It also looks like this could be fixed in some cases by [upgrading Docker](https://github.com/alexjustesen/speedtest-tracker/discussions/541). In any case, this does not appear to be a Lychee issue.
