### ISSUE TITLE
[Enhancement] Disallow access to a subalbum in an album shared with a user

### ISSUE THREAD

**Issue by qwerty287** [LycheeOrg/Lychee#1614]
*Explain in a few words which functionality or improvements you would like to see in Lychee.*
If an album is shared with somebody, the user also has access to all of its subalbums (which is good). However, an option to disallow access to certain subalbums would be nice.

**Comment by ildyria** [comment]
@qwerty287 With the new rights, can you check if that is still needed?

**Comment by qwerty287** [comment]
Yes, seems working
