### ISSUE TITLE
[Enhancement] Choose which metadata to display

### ISSUE THREAD

**Issue by TarryDan** [LycheeOrg/Lychee#1616]
I'd like there to be a method in Settings for non-power-users to choose what metadata is displayed in the sidebar infobox about their pictures 

(or if it's easy, an accessible recipe tutorial for people to adjust this in the code)

Cheers all!

**Comment by ildyria** [comment]
The following should give you a head start.

https://github.com/LycheeOrg/Lychee-front/blob/master/scripts/main/sidebar.js#L230
https://github.com/LycheeOrg/Lychee-front/blob/master/scripts/main/sidebar.js#L424
https://lycheeorg.github.io/docs/frontend.html
