### ISSUE TITLE
[Enhancement] Clean deletion

### ISSUE THREAD

**Issue by Mr-Oca** [LycheeOrg/Lychee#1623]
When you delete a picture, it leaves on the server a lot of empty folders (thumbs, medium, etc).
It would be nice to have a cleaner deletion of files with the deletion of the folders as well.

**Comment by ildyria** [comment]
Such folders barely take space and I don't know how many pictures you have on your Lychee instance, but I have about 40 000. The more pictures you have the less likely you are to have empty folders.

Now if we do a quick analysis, on my instance in `public/uploads/medium` I have:
```
▶ find . -type d -printf '\n' | wc -l
3098
▶ find . -type d -empty -printf '\n' | wc -l
270
```
3098 folders of which 270 are actually empty, which is less than 9%.

As an empty folder is about 4KB, those 270 empty folders represent 1080 KB hence barely 1 MB, which is still **less than half of a single full size picture**.

I am sorry, but the complexity to add a check whether the directory is empty before removing it is not worth the space gained.

You could write a simple shell script that literally does that for you:
```
find . -type d -empty -print -delete
```

**Comment by Mr-Oca** [comment]
It's not about the space, I just like to keep things clean. 
I thought that one folder = one picture, but I understand that's not the case.
And I understand that it would not be a worthy work to check if the folder is empty before deleting it.
So I'll work on my OCD : )
Thanks for the answer !
