### ISSUE TITLE
Webpage is blank after update to master f6a2615

### ISSUE THREAD

**Issue by sigulete** [LycheeOrg/Lychee#1639]
I have updated to master f6a2615 (5 commits from where I started) and now the webpage is blank.
There is no visible error and when I run diagnostic in the command line, there is no indication of errors either.

I'm using PHP 8.1.8

**Note:** I changed `cache` and `session` from redis to file, because `phpredis` was unable to install with the new PHP 8.1.8. But the webpage was working fine before the update. I just wanted to mentioned that.

**Comment by qwerty287** [comment]
Can you check the `logs` table in the database for some logging message?

**Comment by ildyria** [comment]
You can also check in `<path-to-Lychee>/storage/logs/laravel.log` if there are any errors that showed up too.

**Comment by sigulete** [comment]
The file `laravel.log` doesn't exist in this directory, or any other directory under `<path-to-Lychee>`

**Comment by qwerty287** [comment]
Can you check the logs table in the database for some logging message?

laravel.log is only used for SQL logging which should be disabled in production.

**Comment by sigulete** [comment]
The last entrance in the table is from 7hrs ago:
`User (xxx) has logged in from aa.bb.cc.dd
`

There are no errors and no new entrances in the table. I tried opening the webpage and refresh my browser several times.

**Comment by sigulete** [comment]
The problem was local in my laptop. 
I deleted all cookies for my website and now the Login dialog is popping up again.
I will close this bug.

Thanks for your support. Hope I didn't waste your time.
