### ISSUE TITLE
[Enhancement] user note only available to admin

### ISSUE THREAD

**Issue by qwerty287** [LycheeOrg/Lychee#1641]
*Explain in a few words which functionality or improvements you would like to see in Lychee.*
A simple feature to store a short note for every user which is only available to the admin. Idea: always being able to know who is who even if somebody changes the username.

**Comment by lukewatts** [comment]
Do we have any preference for the type of field here? Is a simple text input OK (varchar(255)), or do we want a textarea (TEXT field in DB)?

**Comment by ildyria** [comment]
Either of the two is fine with me. I think 255 chars is enough to add a decent note. e.g this test is just 123 characters.
