### ISSUE TITLE
[Enhancement] add config to disallow changing username

### ISSUE THREAD

**Issue by qwerty287** [LycheeOrg/Lychee#1644]
*Explain in a few words which functionality or improvements you would like to see in Lychee.*
Add a config options that only allows admins to change username, but not the users themselves.

**Comment by ildyria** [comment]
You mean lock by default. :)

**Comment by qwerty287** [comment]
Not sure if I understand you, I mean that you can't change the username as regular user, only as admin. I don't think this should be "by default" but as an optional config, or can you explain more what you mean?

**Comment by d7415** [comment]
I read @ildyria's comment as "mark users as restricted by default", but I think this is aimed specifically at usernames and users would still be able to change passwords?

I'm not sure of the use case, but *shrug*

**Comment by qwerty287** [comment]
Yes, that's what I mean. Still allow changing the password, but not the username. Also, I'd prefer a global config option. I don't think this will add much code so I don't see any issues here, but I'm also open to other suggestion (as alternative you could also just use some custom CSS to hide the username input field).
