### ISSUE TITLE
request for generate hidden links button

### ISSUE THREAD

**Issue by audioscavenger** [LycheeOrg/Lychee#1645]
### Detailed description of the problem
Request

Can we please add an option to generate hidden links to albums or album download links pretty please?
Managing users by hand has become a headache

Thank you

**Comment by ildyria** [comment]
I am not sure I understand what you mean. You can set your album as _public_ & _hidden_ already.
And as a result they are no longer shown to anyone aside from the owner (and the person it has been shared to).

**Comment by qwerty287** [comment]
Duplicate of https://github.com/LycheeOrg/Lychee/issues/1423
