### ISSUE TITLE
Tags do not appear on symbolic link imports

### ISSUE THREAD

**Issue by grainsoflight** [LycheeOrg/Lychee#1648]
When importing photos using symbolic links to the originals, the existing tags on image do not appear in lychee

**Comment by grainsoflight** [comment]
They also don't seem to be read from full files that are imported either. Specifically IPTC Keywords. They are there in the file and still attached if the file is downloaded at original size, but lychee does not display them

**Comment by d7415** [comment]
Please reopen using the supplied template.
