### ISSUE TITLE
Tags/ Keywords Do Not Appear

### ISSUE THREAD

**Issue by grainsoflight** [LycheeOrg/Lychee#1651]
### Detailed description of the problem [REQUIRED]
Existing keyword tags do not appear in lychee when images are imported. They are however still in the file as they appear in the metadata when the file is downloaded from Lychee

### Steps to reproduce the issue
Import photos into lychee or add them using symbolic link. View photo, note that "tags" is empty
**Screenshots**
![Screenshot 2022-12-22 at 7 30 46 PM](https://user-images.githubusercontent.com/29415011/209253253-18aaa48e-73a6-4602-b214-a4d6ac9de132.png)
![Screenshot 2022-12-22 at 7 29 46 PM](https://user-images.githubusercontent.com/29415011/209253259-abf57a65-7204-4526-ba8a-e43aa99b01e8.png)

### Output of the diagnostics  [REQUIRED]
 Diagnostics
    -------
    Warning: Dropbox import not working. dropbox_key is empty.
    Warning: You may experience problems when uploading a photo of large size. Take a look in the FAQ for details.
    Warning: You may experience problems when uploading a photo of large size. Take a look in the FAQ for details.
    Warning: You may experience problems when uploading a photo of large size or handling many/large albums. Take a look in the FAQ for details.

    System Information
    --------------
    Lychee Version (release):        4.4.0
    DB Version:                      4.4.0
    
    composer install:                --no-dev
    APP_ENV:                         production
    APP_DEBUG:                       false
    
    System:                          Linux
    PHP Version:                     8.1
    PHP User agent:                  Lychee/4 (https://lycheeorg.github.io/)
    Max uploaded file size:          2M
    Max post size:                   8M
    Max execution time:              30
    SQLite Version:                  3.36.0
    
    Imagick:                         1
    Imagick Active:                  1
    Imagick Version:                 1808
    GD Version:                      2.4.0-dev

Request space usage

    Config Information
    --------------
    version:                         040400
    check_for_updates:               0
    sorting_Photos_col:              taken_at
    sorting_Photos_order:            ASC
    sorting_Albums_col:              max_taken_at
    sorting_Albums_order:            ASC
    imagick:                         1
    skip_duplicates:                 0
    small_max_width:                 0
    small_max_height:                360
    medium_max_width:                1920
    medium_max_height:               1080
    lang:                            en
    layout:                          1
    image_overlay_type:              desc
    default_license:                 none
    compression_quality:             90
    full_photo:                      1
    delete_imported:                 0
    Mod_Frame:                       1
    Mod_Frame_refresh:               30
    thumb_2x:                        1
    small_2x:                        1
    medium_2x:                       1
    landing_page_enable:             0
    landing_owner:                   John Smith
    landing_title:                   John Smith
    landing_subtitle:                Cats, Dogs & Humans Photography
    landing_facebook:                https://www.facebook.com/JohnSmith
    landing_flickr:                  https://www.flickr.com/JohnSmith
    landing_twitter:                 https://www.twitter.com/JohnSmith
    landing_instagram:               https://instagram.com/JohnSmith
    landing_youtube:                 https://www.youtube.com/JohnSmith
    landing_background:              dist/cat.jpg
    site_title:                      Lychee v4
    site_copyright_enable:           1
    site_copyright_begin:            2019
    site_copyright_end:              2019
    additional_footer_text:          
    display_social_in_gallery:       0
    public_search:                   1
    SL_enable:                       0
    SL_for_admin:                    0
    public_recent:                   0
    recent_age:                      1
    public_starred:                  0
    downloadable:                    0
    photos_wraparound:               1
    map_display:                     0
    zip64:                           1
    map_display_public:              0
    map_provider:                    Wikimedia
    force_32bit_ids:                 0
    map_include_subalbums:           0
    update_check_every_days:         3
    has_exiftool:                    0
    share_button_visible:            0
    import_via_symlink:              0
    has_ffmpeg:                      1
    location_decoding:               0
    location_decoding_timeout:       30
    location_show:                   1
    location_show_public:            0
    rss_enable:                      0
    rss_recent_days:                 7
    rss_max_items:                   100
    prefer_available_xmp_metadata:   1
    editor_enabled:                  1
    lossless_optimization:           0
    swipe_tolerance_x:               150
    swipe_tolerance_y:               250
    local_takestamp_video_formats:   .avi|.mov
    log_max_num_line:                1000
    unlock_password_photos_with_url_param: 0
    nsfw_visible:                    1
    nsfw_blur:                       0
    nsfw_warning:                    0
    nsfw_warning_admin:              0
    map_display_direction:           1
    album_subtitle_type:             oldstyle
    upload_processing_limit:         4
    public_photos_hidden:            1
    new_photos_notification:         0
### Browser and system

Safari
Mac OS Ventura
Lychee v4 QNAP Package

**Comment by qwerty287** [comment]
`Lychee Version (release):        4.4.0`

Please update and check again. This is totally working for me, and the current version is 4.6.2.

**Comment by d7415** [comment]
`has_exiftool:                    0`

I think there were some improvements to our use of imagick for metadata during that gap too.

**Comment by grainsoflight** [comment]
Ill have to try a different type of install, there doesn't seem to be an updated version of the QNAP app, unless I'm missing something.

**Comment by grainsoflight** [comment]
Docker install fixed the metadata issue, but the share button does nothing. Enabling downloads only remains true until the screen is refreshed, the it turns itself off again despite the option remaining checked.

**Comment by qwerty287** [comment]
Share button issue is tracked in #1674

**Comment by ildyria** [comment]
> **Docker install fixed the metadata issue**

So this issue is closed.
