### ISSUE TITLE
Migration fails after #1631

### ISSUE THREAD

**Issue by qwerty287** [LycheeOrg/Lychee#1656]
I was just trying to update my PR #1631 to the latest head but unfortunately, in my case the migration `2022_12_07_141854_rename_capabilities` fails with `SQLSTATE[23000]: Integrity constraint violation: 19 FOREIGN KEY constraint failed (SQL: DROP TABLE users) `... any ideas?
In case it matters, migration fails both on my forked `master` branch as well as the `num_album_photos` branch.

_Originally posted by @evoludolab in https://github.com/LycheeOrg/Lychee/issues/1539#issuecomment-1364453142_

**Comment by qwerty287** [comment]
@evoludolab Created this issue to track it. Which DB are you using? Maybe we should remove https://github.com/LycheeOrg/Lychee/blob/master/database/migrations/2022_12_07_175257_rename_attributes_grants.php#L15 to always disable the constraints.

**Comment by evoludolab** [comment]
It's always nice when problems get solved while sleeping! Just to confirm, I am using SQLite but @ildyria seems to have figured that out already. Happy holidays and thank you so much for the incredible response time!
