### ISSUE TITLE
Error message using share button (owner id must be a non zero positive integer)

### ISSUE THREAD

**Issue by oblomow** [LycheeOrg/Lychee#1658]
### Detailed description of the problem 
I can no longer share images using the share button in the album view.

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Go to an image
2. Click on the share button
3. nothing happens.
4. Going to the sharing option in the settings gives the error: owner id must be a non zero positive integer

**Screenshots**
![image](https://user-images.githubusercontent.com/427760/209443357-1d5c0960-9fe0-45d8-a298-894758fea332.png)

My id is indeed 0 in the mysql database

### Output of the diagnostics  [REQUIRED]

Diagnostics
-----------
Info: Latest version of PHP is 8.1

System Information
------------------
Lychee Version (git):                    master (6460503) -- Up to date (13 minutes ago).
DB Version:                              4.6.3

composer install:                        --no-dev
APP_ENV:                                 local
APP_DEBUG:                               false

System:                                  FreeBSD
PHP Version:                             8.0.24
PHP User agent:                          Lychee/4 (https://lycheeorg.github.io/)
Timezone:                                Europe/Amsterdam
Max uploaded file size:                  100M
Max post size:                           100M
Max execution time:                      0
MySQL Version:                           8.0.30

exec() Available:                        yes
Imagick Available:                       1
Imagick Enabled:                         1
Imagick Version:                         1692
GD Version:                              2.3.3
Number of foreign key:                   24 found.

Config Information
------------------
version:                                 040603
check_for_updates:                       1
sorting_photos_col:                      taken_at
sorting_photos_order:                    ASC
sorting_albums_col:                      title
sorting_albums_order:                    DESC
imagick:                                 1
skip_duplicates:                         0
small_max_width:                         0
small_max_height:                        360
medium_max_width:                        1920
medium_max_height:                       1080
lang:                                    en
layout:                                  1
image_overlay_type:                      date
default_license:                         CC-BY-NC-ND-4.0
compression_quality:                     90
grants_full_photo_access:                1
delete_imported:                         0
mod_frame_enabled:                       1
mod_frame_refresh:                       30
thumb_2x:                                1
small_2x:                                1
medium_2x:                               1
landing_page_enable:                     1
site_owner:                              
landing_title:                          
landing_subtitle:                       
sm_facebook_url:                         
sm_flickr_url:                           
sm_twitter_url:                          
sm_instagram_url:                        
sm_youtube_url:                          
landing_background:                      dist/finland.jpg
site_title:                              fotos
footer_show_copyright:                   1
site_copyright_begin:                    1984
site_copyright_end:                      2022
footer_additional_text:                 
footer_show_social_media:                0
public_search:                           0
SL_enable:                               0
SL_for_admin:                            0
public_recent:                           0
recent_age:                              1
public_starred:                          0
grants_download:                         1
photos_wraparound:                       1
map_display:                             0
zip64:                                   1
map_display_public:                      0
map_provider:                            OpenStreetMap.org
force_32bit_ids:                         0
map_include_subalbums:                   0
update_check_every_days:                 3
has_exiftool:                            1
share_button_visible:                    0
import_via_symlink:                      0
has_ffmpeg:                              0
location_decoding:                       0
location_decoding_timeout:               30
location_show:                           0
location_show_public:                    0
rss_enable:                              0
rss_recent_days:                         7
rss_max_items:                           100
prefer_available_xmp_metadata:           0
editor_enabled:                          1
lossless_optimization:                   0
swipe_tolerance_x:                       150
swipe_tolerance_y:                       250
local_takestamp_video_formats:           .avi|.mov
log_max_num_line:                        1000
unlock_password_photos_with_url_param:   0
nsfw_visible:                            1
nsfw_blur:                               0
nsfw_warning:                            0
nsfw_warning_admin:                      0
nsfw_banner_override:                    
map_display_direction:                   1
album_subtitle_type:                     oldstyle
upload_processing_limit:                 4
public_photos_hidden:                    1
new_photos_notification:                 0
legacy_id_redirection:                   1
zip_deflate_level:                       6
SA_enabled:                              1
default_album_protection:                1

**Comment by ildyria** [comment]
This will be fixed very soon with #1602

**Comment by oblomow** [comment]
great! thank you. keep up the good work.

**Comment by ildyria** [comment]
Fixed as #1602 has been merged.
