### ISSUE TITLE
Migration 2022_12_10_183251_increment_user_i_ds failing

### ISSUE THREAD

**Issue by verymilan** [LycheeOrg/Lychee#1664]
Hi there, I was updating to v4.6.4 release using the master branch. Sadly one of the database migration is failig using postgres:

```
   INFO  Running migrations.

  2022_12_10_183251_increment_user_i_ds ................................................................................................... 6ms FAIL

In Connection.php line 760:

  SQLSTATE[23503]: Foreign key violation: 7 ERROR:  update or delete on table "users" violates foreign key constraint "base_albums_owner_id_foreign" on table "base_albums"
  DETAIL:  Key (id)=(0) is still referenced from table "base_albums". (SQL: update "users" set "id" = 1 where "id" = 0)


In Connection.php line 570:

  SQLSTATE[23503]: Foreign key violation: 7 ERROR:  update or delete on table "users" violates foreign key constraint "base_albums_owner_id_foreign" on table "base_albums"
  DETAIL:  Key (id)=(0) is still referenced from table "base_albums".
```

**Comment by ildyria** [comment]
Hi, sorry for this.

Unfortunately I don't have a postgresql install to test.
Could you try rerunning the migration with this file instead of the one in master:
https://github.com/LycheeOrg/Lychee/blob/hotfixes/database/migrations/2022_12_10_183251_increment_user_i_ds.php

**Comment by verymilan** [comment]
Thanks for the fast hotfix! Tho I am sorry to say, that the error appears to be identical. :/
I have replaced the contents of this file on this location, hope this was correct.

**Comment by ildyria** [comment]
> I have replaced the contents of this file on this location, hope this was correct.

That was the intent. :( That sucks.

**Comment by ildyria** [comment]
I'll try to get a postgresql DB running tomorrow to test that locally.

**Comment by qwerty287** [comment]
Actually foreign key constraints should've been disabled for all DB types in the migration, that's a really weird that it fails with this error.
