### ISSUE TITLE
[Mobile Feature Request] Send Photos from Gallery to my Lychee app

### ISSUE THREAD

**Issue by anjanesh** [LycheeOrg/Lychee#1677]
*Explain in a few words which functionality or improvements you would like to see in Lychee.*
Would there be an option to send photos directly from the gallery of an iPhone or Android Gallery to our personal Lychee website ?

**Comment by ildyria** [comment]
If someone has the time to implement it... sure.

**Comment by anjanesh** [comment]
What does implementation technique require ? Native mobile app development using Kotlin / Swift to send data to the  Lychee website ?

**Comment by qwerty287** [comment]
This is more or less a duplicate of #1013. This will include this feature (read the issue desc).
