### ISSUE TITLE
Updating manually shows SQL-Error: Unknown column 'may_administrate'

### ISSUE THREAD

**Issue by BMerz** [LycheeOrg/Lychee#1678]
### Detailed description of the problem [REQUIRED]
I have Lychee v4.6.2 installed and want to update to v4.6.5. I followed the steps in the docu for manual update ([Link](https://lycheeorg.github.io/docs/update.html#update-manually))
Usually I could then open Lychee in the browser, log in, and then apply the update.
With v4.6.5 I can't even log in and the error message is shown:

500
HttpException

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'may_administrate' in 'where clause' (SQL: select count(*) as aggregate from `users` where `may_administrate` = 1)

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Stop Apache2
2. move new files in place (except the ones mentioned in the Docu).
3. Start Apache2
4. Navigate with browser to the Lychee-Server
5. Error message is shown.

### Output of the diagnostics  [REQUIRED]
`php artisan lychee:diagnostics`
In Connection.php line 760:
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'may_administrate' in 'where clause' (SQL: se  
  lect count(*) as aggregate from `users` where `may_administrate` = 1)                                 

In Connection.php line 414:
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'may_administrate' in 'where clause'

### Browser and system
Server: Debian11 with Apache2 and MariaDB
Client: Firefox

**Comment by d7415** [comment]
Sometimes Laravel caches in annoying ways. Try `php artisan cache:clear`

**Comment by BMerz** [comment]
Hello @d7415 ,
have cleared the cache according to your recommendation but issue still there.
I have tried even server reboot

**Comment by ildyria** [comment]
Nah, it's not caching, it is the logic this time. I'll fix it.

**Comment by BMerz** [comment]
Hi @ildyria,
thanks for the quick fix. Meanwhile I updated and it works :-)
Great support!
