### ISSUE TITLE
Is there a way to remove the Public folder?

### ISSUE THREAD

**Issue by leemediagroup** [LycheeOrg/Lychee#1685]
We are really just look to remove this folder and remove the option for users to upload photos as public (we want to be sure everything stays private). Is there a way to do that? I looked at some of the templates to see if there was something I could easily hide, but I'm not sure where to you.

**Comment by ildyria** [comment]
I think you are misunderstanding the role of the public folder. It only shows pictures that have been manually set to public.

However if you really want to hide it you can use the following custom css in the setting page:
```css
div[data-id="public"] {
display:none;
}
```
