### ISSUE TITLE
[Enhancement]  It does not currently seem possible to make private photos or albums public on mobile.

### ISSUE THREAD

**Issue by vjuliano** [LycheeOrg/Lychee#1689]
I was trying to make a private album public while using my Android device.  It did not seem to be possible.  I know the flow to do so on the desktop.  It would be nice to be able to do so on mobile.

It is possible I just could not figure out how to do it though.

**Comment by ildyria** [comment]
Tap `+` in top right corner => Album visibility. It is working, just tested on my phone with latest version.

**Comment by vjuliano** [comment]
Oh,   I expected the + to act as an add button, as it does on the desktop.  In this case it acts more like a hamburger menu than a plus.

**Comment by ildyria** [comment]
> Oh, I expected the + to act as an add button, as it does on the desktop. In this case it acts more like a hamburger menu than a plus.

Indeed. This should be made clearer.
