### ISSUE TITLE
error when migrating to latest 4.x

### ISSUE THREAD

**Issue by tadeussenf** [LycheeOrg/Lychee#1695]
### Detailed description of the problem [REQUIRED]
when running php artisan migrate i am getting the following error:
```
   INFO  Running migrations.

  2018_08_15_103716_move_photos ............................................................................ 12ms FAIL

In Connection.php line 760:

  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fa
  ils (`lychee`.`photos`, CONSTRAINT `photos_album_id_foreign` FOREIGN KEY (`album_id`) REFERENCES `albums` (`id`) ON
   DELETE CASCADE) (SQL: insert into `photos` (`id`, `album_id`, `title`, `description`, `url`, `tags`, `public`, `ty
  pe`, `width`, `height`, `size`, `iso`, `aperture`, `make`, `lens`, `model`, `shutter`, `focal`, `takestamp`, `star`
  , `thumbUrl`, `thumb2x`, `checksum`, `medium`, `small`, `license`, `updated_at`, `created_at`) values (150757936724
  12, 15075791937499, Schweiz Oktober 2017 395, , f74c006a3e61ff4061260f3075698683.JPG, , 1, image/jpeg, 640, 480, 47
  2.7 KB, 32, f/2.2, Apple, , iPhone 5s, 1/1786 s, 4.2 mm, 2017-10-05 14:55:09, 0, f74c006a3e61ff4061260f3075698683.j
  peg, 1, ec7ebc99bfc2bc58514b216f13771af7a4c8135f, , , none, 2023-01-07 17:29:38, 2023-01-07 17:29:38))


In Connection.php line 545:

  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fa
  ils (`lychee`.`photos`, CONSTRAINT `photos_album_id_foreign` FOREIGN KEY (`album_id`) REFERENCES `albums` (`id`) ON
   DELETE CASCADE)
```

**Comment by ildyria** [comment]
From which version are you migrating ?  Because this looks awfully far.

**Comment by tadeussenf** [comment]
> From which version are you migrating ? Because this looks awfully far.

Currently I am running 3.1.6, which is the lastest 3.x version - am I right?

**Comment by ildyria** [comment]
Would you mind mailing me a dump of your SQL DB ?
That way I can build a v3 instance and debug that problem. :|
You will find my mail address on my [personal website](https://benoit.viguier.nl/).

**Comment by tadeussenf** [comment]
> Would you mind mailing me a dump of your SQL DB ? That way I can build a v3 instance and debug that problem. :| You will find my mail address on my [personal website](https://benoit.viguier.nl/).

sure, I dropped you an email. tyvm!

**Comment by ildyria** [comment]
I had a look at your DB, there are some problems in it. Namely album 15075791937499 is missing.
I see only 3 albums in the lychee_album table. But some pictures are referencing that album with id 15075791937499,
as a result, this create a constraint violation.
I'll try to create a fix.

**Comment by tadeussenf** [comment]
@ildyria Wow, thank you very much for your support and your engagement!
