### ISSUE TITLE
[Enhancement] Automatic/Scheduled Folder Sync 

### ISSUE THREAD

**Issue by MrSiO** [LycheeOrg/Lychee#1700]
Hi.
I'm currently using the option "_Import from server_" to import camera pictures from my DVR (mapped the DVR's folder as a Lychee container volume)

Works great, but since the cameras are constantly adding new pictures to that folder, I'm looking for a way to constantly sync (_at least once per hour_) the photos...  or at least a quick "sync" button...

Could there be a schedule or automatic folder sync when pictures are added to the volume?

Only found this post related:  https://github.com/LycheeOrg/Lychee/issues/291
Has this been futher developped since?

Thx!

**Comment by d7415** [comment]
Hi, there's a console command that can be run using e.g. cron https://lycheeorg.github.io/docs/faq_general.html#can-i-set-up-lychee-to-watch-a-folder-for-new-images-and-automatically-add-them-to-albums
