### ISSUE TITLE
Cannot add or update a child row: a foreign key constraint fails

### ISSUE THREAD

**Issue by DKeppi** [LycheeOrg/Lychee#1717]
Since i installed version 4.6.5 (i have only php 8.0 available on my NAS)and made the migration of 
"2022_12_10_183251_increment_user_i_ds.php" i have problems with importing photos to the DB

Go to a album, import photo via + and Upload photo, following errors occur immediately

------------------------------------------------------------------------------------------------------
2023-01-16` 10:06:32 UTC -- error   -- PDOStatement::execute -- 545 -- SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`lychee`.`photos`, CONSTRAINT `photos_owner_id_foreign` FOREIGN KEY (`owner_id`) REFERENCES `users` (`id`))

2023-01-16 10:06:32 UTC -- error   -- App\Models\Photo::performInsert -- 105 -- SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`lychee`.`photos`, CONSTRAINT `photos_owner_id_foreign` FOREIGN KEY (`owner_id`) REFERENCES `users` (`id`)); caused by

2023-01-16 10:06:32 UTC -- error   -- Illuminate\Database\Connection::runQueryCallback -- 760 -- SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`lychee`.`photos`, CONSTRAINT `photos_owner_id_foreign` FOREIGN KEY (`owner_id`) REFERENCES `users` (`id`)) (SQL: insert into `photos` (`updated_at`, `created_at`, `title`, `description`, `tags`, `type`, `iso`, `aperture`, `make`, `model`, `lens`, `shutter`, `focal`, `taken_at`, `taken_at_orig_tz`, `latitude`, `longitude`, `altitude`, `img_direction`, `location`, `live_photo_content_id`, `is_public`, `is_starred`, `album_id`, `owner_id`, `original_checksum`, `checksum`, `id`, `legacy_id`) values (2023-01-16 10:06:29.290315, 2023-01-16 10:06:29.290315, 0AFA2C8D-D15E-485B-8147-B91B6B7F0A5B, ?, ?, image/jpeg, 160, f/1.6, Apple, iPhone 13 mini, iPhone 13 mini back dual wide camera 5.1mm f/1.6, 1/49 s, 5 mm, 2022-06-05 19:18:10.000000, +02:00, ?, ?, ?, ?, ?, ?, 0, 0, IPgtfh4B-pccJuO6MP259Q_j, 0, b6cbbd81b9c745fde8c2a9859bd695c78cc2e43a, b6cbbd81b9c745fde8c2a9859bd695c78cc2e43a, V_iiFTohMnK7LzEoR3isRbxR, 16738635919078)); caused by

2023-01-16 10:06:32 UTC -- error   -- App\Models\Photo::performInsert -- 105 -- SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`lychee`.`photos`, CONSTRAINT `photos_owner_id_foreign` FOREIGN KEY (`owner_id`) REFERENCES `users` (`id`)) (SQL: insert into `photos` (`updated_at`, `created_at`, `title`, `description`, `tags`, `type`, `iso`, `aperture`, `make`, `model`, `lens`, `shutter`, `focal`, `taken_at`, `taken_at_orig_tz`, `latitude`, `longitude`, `altitude`, `img_direction`, `location`, `live_photo_content_id`, `is_public`, `is_starred`, `album_id`, `owner_id`, `original_checksum`, `checksum`, `id`, `legacy_id`) values (2023-01-16 10:06:29.290315, 2023-01-16 10:06:29.290315, 0AFA2C8D-D15E-485B-8147-B91B6B7F0A5B, ?, ?, image/jpeg, 160, f/1.6, Apple, iPhone 13 mini, iPhone 13 mini back dual wide camera 5.1mm f/1.6, 1/49 s, 5 mm, 2022-06-05 19:18:10.000000, +02:00, ?, ?, ?, ?, ?, ?, 0, 0, IPgtfh4B-pccJuO6MP259Q_j, 0, b6cbbd81b9c745fde8c2a9859bd695c78cc2e43a, b6cbbd81b9c745fde8c2a9859bd695c78cc2e43a, V_iiFTohMnK7LzEoR3isRbxR, 16738635919078)); caused by

2023-01-16 10:06:32 UTC -- error   -- App\Models\Photo::performInsert -- 122 -- unable to persist model to DB after 5 unsuccessful attempts; caused by

2023-01-16 10:06:32 UTC -- error   -- App\Exceptions\ModelDBException::create -- 50 -- Updating photo failed; caused by

------------------------------------------------------------------------------------------------------

The problem is, that the insert statement includes the owner_id 0, which is not available anymore.
My workaround was a new user with user_id 0 that it works, but hopefully you can fix the insert statement for importing new pictures instead

Thanks in advance

**Comment by ildyria** [comment]
https://github.com/LycheeOrg/Lychee/blob/master/app/Console/Commands/Sync.php#L31
Needs also to be changed to a `1`

**Comment by DKeppi** [comment]
Anything else to change, still got the same errors.
Insert statement again with 0

**Comment by ildyria** [comment]
I used a clean v4.6.5, did `composer install`, _`migrate fresh`_ (:warning: DO NOT DO THAT!!)
but I am unable to reproduce your bug.

Can you tell me more about your install ?  sqlite ? Mysql ? 
Could you please fill the diagnostic page, that would be quite useful...

If all else fail you can always send me a dump of your DB so I can have a look. You will find my mail on my personal website...

**Comment by DKeppi** [comment]
I host it on a Synology NAS Webstation with php8.0.23 and MariaDB10.3.32

Diagnostics
    -------
    Warning: Dropbox import not working. dropbox_key is empty.
    Warning: You may experience problems when uploading a photo of large size. Take a look in the FAQ for details.
    Info: Latest version of PHP is 8.1
    Warning: Default timezone not properly set; you might experience strange results when importing photos without explicit EXIF timezone


System Information
    --------------
    Lychee Version (git):                    master (182001f) -- More than 30 commits behind (12 hours ago).
    DB Version: 4.6.5
    composer install: --no-dev
    APP_ENV: production
    APP_DEBUG: true
    System: Linux
    PHP Version: 8.0.23
    PHP User agent: Lychee/4 (https://lycheeorg.github.io/)
    Timezone: CET
    Max uploaded file size: 32M
    Max post size: 32M
    Max execution time: 240
    MySQL Version: 10.3.32-MariaDB
    exec() Available: yes
    Imagick Available: 1
    Imagick Enabled: 1
    Imagick Version: 1691
    GD Version: bundled (2.1.0 compatible)
    Number of foreign key: 11 found.



Does that help?

**Comment by ildyria** [comment]
That helps A LOT !

```
* 26b5393b (tag: v4.6.5) v4.6.5 (#1666) << YOUR DB VERSION
* d982ef15 allow username change (#1667)
* 2dcc23ec Fixes for v4.6.4 (#1665)
* 6a61bc69 (tag: v4.6.4) release v4.6.4 (#1661)
* f3c43c67 Remove (broken and unused) installer scripts (#1662)
* baddcfd9 Create admin during installation, allow multiple admins (#1602)
* 64605031 fixes #1656 (#1657)
* c699fce6 Apply rights naming convention (#1539)
* 7eef85ac Add number of foreign key check and listing option (#1655)
* 5b0d944d Remove and clean up unused files (#1649)
* ba76b8fb Full URL for metadata (#1653)
* 7730da23 Fix workflow warnings (#1654)
* 182001fd FIX CICD workflow shield (#1640) << YOUR FILE VERSION
```

**Comment by ildyria** [comment]
I do not know how you did your update but your `.git` is completely off which leads me to believe that your files are outdated and behind the database. (I am actually quite surprised your install is not breaking more. :') )

**Comment by DKeppi** [comment]
Normally i update with git, but i dont want to be on 4.7 (i have only php 8.0) so i made the last update manually via zip File and migrated!

Is there another way to have an updated/actual 4.6.5, im not very good at git 🙈

**Comment by d7415** [comment]
You can run `git fetch --all` to get everything from GitHub, then `git checkout v4.6.5` to check out that tag. You may need to force it (I think it will tell you) to overwrite the files you changed manually.

**Comment by ildyria** [comment]
Or:
```sh
git stash # put all the changes made to the side
git stash clear # remove all those (we won't need them anyway
git fetch # see what is behind
git checkout v4.6.5 # switch to version 4.6.5: Instead of git pull
```

**Comment by DKeppi** [comment]
Thanks for the help

When i made `git checkout v4.6.5` it tells me

```
error: The following untracked working tree files would be overwritten by checkout:
        app/Actions/Diagnostics/Pipes/Checks/ForeignKeyListInfo.php
        app/Actions/Diagnostics/Pipes/Infos/CountForeignKeyInfo.php
        app/Console/Commands/CreateUser.php
        app/Console/Commands/UpdateUser.php
        app/DTO/AbstractAlbumDTO.php
        app/DTO/Rights/AlbumRightsDTO.php
        app/DTO/Rights/GlobalRightsDTO.php
        app/DTO/Rights/PhotoRightsDTO.php
        app/DTO/Rights/RootAlbumRightsDTO.php
        app/DTO/Rights/SettingsRightsDTO.php
        app/DTO/Rights/UserManagementRightsDTO.php
        app/DTO/Rights/UserRightsDTO.php
        app/DTO/UserWithCapabilitiesDTO.php
        app/Exceptions/AdminUserAlreadySetException.php
        app/Exceptions/AdminUserRequiredException.php
        app/Exceptions/Handlers/AdminSetterHandler.php
        app/Http/Controllers/Administration/UsersController.php
        app/Http/Controllers/Install/SetUpAdminController.php
        app/Http/Middleware/AdminUserStatus.php
        app/Http/Middleware/Checks/HasAdminUser.php
        app/Http/Redirections/ToAdminSetter.php
        app/Http/Requests/AbstractEmptyRequest.php
        app/Http/Requests/Import/CancelImportServerRequest.php
        app/Http/Requests/Install/SetUpAdminRequest.php
        app/Http/Requests/Logs/ClearLogsRequest.php
        app/Http/Requests/Logs/ShowLogsRequest.php
        app/Http/Requests/Photo/ClearSymLinkRequest.php
        app/Http/Requests/Settings/AbstractSettingRequest.php
        app/Http/Requests/Settings/GetSetAllSettingsRequest.php
        app/Http/Requests/Settings/MigrateRequest.php
        app/Http/Requests/Settings/SetCSSSettingRequest.php
        app/Http/Requests/Settings/SetDefaultLicenseSettingRequest.php
        app/Http/Requests/Settings/SetDropboxKeySettingRequest.php
        app/Http/Requests/Settings/SetImageOverlaySettingRequest.php
        app/Http/Requests/Settings/SetLangSettingRequest.php
        app/Http/Requests/Settings/SetLayoutSettingRequest.php
        app/Http/Requests/Settings/SetLocationDecodingSettingRequest.php
        app/Http/Requests/Settings/SetLocationShowPublicSettingRequest.php
        app/Http/Requests/Settings/SetLocationShowSettingRequest.php
        app/Http/Requests/Settings/SetMapDisplayPublicSettingRequest.php
        app/Http/Requests/Settings/SetMapDisplaySettingRequest.php
        app/Http/Requests/Settings/SetMapIncludeSubAlbumsSettingRequest.php
        app/Http/Requests/Settings/SetMapProviderSettingRequest.php
        app/Http/Requests/Settings/SetNSFWVisibilityRequest.php
        app/Http/Requests/Settings/SetNewPhotosNotificationSettingRequest.php
        app/Http/Requests/Settings/SetPublicSearchSettingRequest.php
        app/Http/Requests/Settings/SetSortingSettingsRequest.php
        app/Http/Requests/Settings/UpdateRequest.php
        app/Http/Requests/User/ChangeLoginRequest.php
        app/Http/Requests/User/ChangeTokenRequest.php
        app/Http/Requests/User/U2FRequest.php
        app/Http/Requests/Users/AddUserRequest.php
        app/Http/Requests/Users/DeleteUserRequest.php
        app/Http/Requests/Users/ListUsersRequest.php
        app/Http/Requests/Users/SetUserSettingsRequest.php
        app/Http/Requests/WebAuthn/DeleteCredentialRequest.php
        app/Http/Requests/WebAuthn/ListCredentialsRequest.php
        app/Policies/BasePolicy.php
        app/Policies/SettingsPolicy.php
        database/migrations/2022_12_07_141854_rename_capabilities.php
        database/migrations/2022_12_07_143755_add_default_protection_option.php
        database/migrations/2022_12_07_164417_config_uniformize_rights.php
        database/migrations/2022_12_07_175257_rename_attributes_grants.php
        database/migrations/2022_12_10_183251_increment_user_i_ds.php
        database/migrations/2022_12_21_212143_use_webp_for_example.php
        database/migrations/2022_12_25_103052_bump_version040604.php
        database/migrations/2022_12_26_101639_allow_username_change.php
        database/migrations/2022_12_26_111139_bump_version040605.php
        public/dist/cat.webp
        resources/views/install/setup-admin.blade.php
        resources/views/install/setup-success.blade.php
Please move or remove them before you switch branches.
Aborting
```

Should i delete them manually or is there an option to force the overwriting?

**Comment by ildyria** [comment]
That is why I told you to do `git stash` :)

**Comment by DKeppi** [comment]
I have done `git stash` and `git stash clear`

**Comment by ildyria** [comment]
that is very surprising.

**Comment by ildyria** [comment]
I think I know why, those files are not tracked yet.
You can fix it with:
```
git clean -n # check the list of files to be deleted
git clean -f # do the actual deletion
```

**Comment by DKeppi** [comment]
Thx that helped, checking now the diagnostics page and if the upload works again

**Comment by DKeppi** [comment]
Diagnostics page:

Error: /volume1/web/lychee/.git (and subdirectories) are not executable, check the permissions

System Information
    --------------
    Lychee Version (git):                ?? (26b5393) -- Could not compare.
    DB Version:                              4.6.5



A `chmod -R +x /volume1/web/lychee/.git` does not help


And also the Upload brings the same error as before, due to the insert statement has the owner_id 0
I changed the https://github.com/LycheeOrg/Lychee/blob/master/app/Console/Commands/Sync.php#L31 before to 1

**Comment by ildyria** [comment]
> A chmod -R +x /volume1/web/lychee/.git does not help

It needs to be executable by the web-user not the current one, so probably `chown -R www-data:www-data .git` would fix it.
Nevertheless quite an annoying bug. Would you mind sending me a dump of your DB so I can have a look at what is wrong in it?

**Comment by DKeppi** [comment]
Sent the Dump of my DB via E-Mail

**Comment by ildyria** [comment]
Found the problem: The `albums` table for some reason has a left over of `owner_id` column.

When executing in `AbstractAddStrategy.php`:
```php
	protected function setParentAndOwnership(): void
	{
		if ($this->parameters->album !== null) {
			$this->photo->album_id = $this->parameters->album->id;
			// Avoid unnecessary DB request, when we access the album of a
			// photo later (e.g. when a notification is sent).
			$this->photo->setRelation('album', $this->parameters->album);
			$this->photo->owner_id = $this->parameters->album->owner_id;
		} else {
			$this->photo->album_id = null;
			// Avoid unnecessary DB request, when we access the album of a
			// photo later (e.g. when a notification is sent).
			$this->photo->setRelation('album', null);
			/** @var int */
			$userId = Auth::id() ?? throw new UnauthenticatedException();
			$this->photo->owner_id = $userId;
		}
	}
```
The code is going to fetch the album and access `owner_id` which is the intended behavior. The implementation should forward that `owner_id` attribute to `base_albums` if `owner_id` did not exists.
Executing the following sql command on your database will solve your problems.
```sql
ALTER TABLE `albums` DROP `owner_id`;
```

**Comment by DKeppi** [comment]
THX, now it works :)
