### ISSUE TITLE
[Enhancement] Hide Album Name and Time Overlay

### ISSUE THREAD

**Issue by PinkalShah** [LycheeOrg/Lychee#1721]
I would like to know , can i hide public album name and time/date ? 
We have created photos for as album cover which represents the Album name itself.

If these settings are not available in UI then can i do it via custom CSS?

**Comment by ildyria** [comment]
1. all public album name & time date or just some? 
2. If it is all of them, it is easily doable with custom css.

**Comment by PinkalShah** [comment]
Hi @ildyria,

All public album name and time date.

Can you help me with Custom CSS?

**Comment by ildyria** [comment]
Probably something like that.
```css
div.album div.overlay {
	display:none !important;
}
```

**Comment by PinkalShah** [comment]
@ildyria,

Not working.

**Comment by ildyria** [comment]
It is on my side which means that you are either not up to date or you did not do a full refresh of the page.

**Comment by PinkalShah** [comment]
@ildyria : I will update the version and check one my time from my side.

**Comment by PinkalShah** [comment]
@ildyria : it's working now.

Thanks a ton.

**Comment by ildyria** [comment]
Reopening because it might be a nice to have setting.
