### ISSUE TITLE
[Enhancement] Save the creation date of files and be able to sort the album by creation date instead of downloading

### ISSUE THREAD

**Issue by DearFox** [LycheeOrg/Lychee#1727]
I have a lot of photos and drawings that I want to be able to upload with the file creation date saved, but at this point I haven't figured out if it's possible to do that.

**Comment by ildyria** [comment]
![image](https://user-images.githubusercontent.com/627094/214033516-af0c95a0-00d2-49e3-80b6-a6e7d4cf40a2.png)
There is literally a button to do that.
press `i` to display the side panel and click on the pen near the upload date.
It is also possible to sort pictures by upload date.

As such I consider this resolved and already implemented.

**Comment by DearFox** [comment]
> ![image](https://user-images.githubusercontent.com/627094/214033516-af0c95a0-00d2-49e3-80b6-a6e7d4cf40a2.png) There is literally a button to do that. press `i` to display the side panel and click on the pen near the upload date. It is also possible to sort pictures by upload date.
> 
> As such I consider this resolved and already implemented.

Yes, I know that it is possible to change the date, but it is very inconvenient when you have a bunch of files.
The upload date is pretty arbitrary if you're uploading more than 1 file, and that's not very appropriate either.
As far as I know, it is possible to get the file creation date, and I requested that this date be automatically added to one of the fields. For example, when uploading a video, it has a shooting date, so I would like to have something like this for png , gif , jpg...

**Comment by DearFox** [comment]
I spent more than 2 or 3 hours yesterday to change the upload date to the file creation date, and I had less than a hundred files.
And this feature would make life easier in situations like mine.

**Comment by ildyria** [comment]
I am not sure I understand what you want. If the exif data is present, then it will appear in the take date
> Camera
> Captured	Jun 2, 2019, 6:32:22 PM UTC

**Comment by DearFox** [comment]
> I am not sure I understand what you want. If the exif data is present, then it will appear in the take date
> 
> > Camera
> > Captured	Jun 2, 2019, 6:32:22 PM UTC

I uploaded my drawings and animations, I don't think they have that.
And is this data saved after processing the photo?
Or maybe there is some program that can create this data for the file?

I'm just not sure that exif data is in png and gif
At least in all the programs in which I work - there is no way to write such data
At least I have never seen it.

**Comment by ildyria** [comment]
Those data are usually directly integrated in the photo, e.g. by the camera or software like Lightroom.

I would recommend looking at those: https://www.geckoandfly.com/7987/how-to-change-exif-data-date-and-camera-properties-with-free-editor/ Because Lychee is using those data to fill up internal fields for the pictures. :|

As far as I know, it is not possible to retrieve the creation time of the picture when uploading. Let me clarify this.
On your computer, your file has a creation time/date and modified time/date. We are not able to access that data.

**Comment by DearFox** [comment]
> Those data are usually directly integrated in the photo, e.g. by the camera or software like Lightroom.
> 
> I would recommend looking at those: https://www.geckoandfly.com/7987/how-to-change-exif-data-date-and-camera-properties-with-free-editor/ Because Lychee is using those data to fill up internal fields for the pictures. :|
> 
> As far as I know, it is not possible to retrieve the creation time of the picture when uploading. Let me clarify this. On your computer, your file has a creation time/date and modified time/date. We are not able to access that data.
I did some searching and this is what I found:
Js code that can get this data from a file
Drag and drop a file there and the site console will display information, including the creation / editing time 

https://codepen.io/harryheman/pen/BajvQmB


![image](https://user-images.githubusercontent.com/59219907/214068700-18ce9ef4-49ba-40cb-8cd4-685e4e5c2123.png)

**Comment by ildyria** [comment]
I did not know we had access to such data.
