### ISSUE TITLE
[Enhancement] Use LastModified date when no exif data are found

### ISSUE THREAD

**Issue by ildyria** [LycheeOrg/Lychee#1729]
Original issue: #1727

![See here](https://user-images.githubusercontent.com/59219907/214068700-18ce9ef4-49ba-40cb-8cd4-685e4e5c2123.png)

When uploading a file, we have access to extra meta-data. We can use those to fill up dates when provided.

- [x] : Fetch data and replace when no Exif data are provided
- [x] : Add config option to enable / disable this functionality.

**Comment by wladif** [comment]
@ildyria I have some free time this days and I could try to implement this. Is it ok with you?

**Comment by ildyria** [comment]
Go for it ! :) 
It is written as "project for voluneers" so pretty much up for grab ! :)

**Comment by wladif** [comment]
@ildyria With the current php-exif lib I'm having a hard time figuring out if an images has Exif data or not. As far as I can tell, when Imagemagick is used, the library will always return some an Exif instance, even if the image doesn't have exif. I find this to be a bit confusing. Is this something intended or is there a plan to refactor it? How can I check if a file has actual exif data or not ? Thanks

**Comment by ildyria** [comment]
Thanks for pointing that one out. I fixed the return type of the reader: https://github.com/LycheeOrg/php-exif/pull/62 to reflect this behavior.

Yes this behavior is working as expected. Exif data is also size etc...
What matters in your case is whether some of the data in the Exif object are there or not.
See here https://github.com/LycheeOrg/php-exif/blob/master/lib/PHPExif/Exif.php

**Comment by wladif** [comment]
@ildyria There is already a config for this functionality. The config was included in #1821, it's called: `use_last_modified_date_when_no_exif_date`.
