### ISSUE TITLE
UX broken on version 4.7.0 for Safari iPhone

### ISSUE THREAD

**Issue by Binnette** [LycheeOrg/Lychee#1744]
### Detailed description of the problem [REQUIRED]
Navigating between pictures of the same album is boken in version 4.7.0 on Safari iPhone 15.4.1
With version 4.7.0 when sliding right, instead of jumping to next picture it show pictures infos and then interface is broken.
See screenshot

I tested the live [demo](https://lycheeorg.github.io/demo/) on the same device, navigation is working fine.

NB : regression concern only safari on iPhone. I tested version 4.7.0 on Firefox Mobile, navigation is working fine.

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Install Lychee 4.70
2. Create an album with a least 2 pictures
3. Click on the first picture to open it fullscreen
4. Slide your finger to the right to show next picture
5. BUG! Instead of showing next picture, it show picture info and the interface is broken

**Screenshots**

![photo_2023-01-30_23-27-13](https://user-images.githubusercontent.com/6597721/215614556-d73951d4-cbb2-4ef1-92e7-5cf630346aff.jpg)

![photo_2023-01-30_23-25-33](https://user-images.githubusercontent.com/6597721/215614553-75727399-efc5-45c1-a51b-03679e8763e3.jpg)

### Output of the diagnostics  [REQUIRED]

    Diagnostics
    -------
    Warning: /home/yunohost.app/lychee/uploads/ is owned by group www-data, but should be owned by one out of lychee
    Warning: /home/yunohost.app/lychee/uploads/ has permissions 0750, but should have 2775
    Warning: /home/yunohost.app/lychee/uploads/medium is owned by group www-data, but should be owned by one out of lychee
    Warning: /home/yunohost.app/lychee/uploads/medium has permissions 0750, but should have 2775
    Warning: /home/yunohost.app/lychee/uploads/medium/67 is owned by group www-data, but should be owned by one out of lychee
    Warning: /home/yunohost.app/lychee/uploads/medium/67 has permissions 0770, but should have 2775
    Warning: /home/yunohost.app/lychee/uploads/medium/67/4c is owned by group www-data, but should be owned by one out of lychee
    Warning: /home/yunohost.app/lychee/uploads/medium/67/4c has permissions 0770, but should have 2775
    Warning: /home/yunohost.app/lychee/uploads/medium/81 has permissions 0775, but should have 2775
    Warning: /home/yunohost.app/lychee/uploads/medium/43 is owned by group www-data, but should be owned by one out of lychee
    Warning: 669 more directories with wrong owner
    Warning: 1314 more directories with wrong permissions
    Warning: Dropbox import not working. dropbox_key is empty.
    Warning: You may experience problems when uploading a photo of large size or handling many/large albums. Take a look in the FAQ for details.
    Info: Latest version of PHP is 8.2
    Warning: Default timezone not properly set; you might experience strange results when importing photos without explicit EXIF timezone

    System Information
    --------------
    Lychee Version (release):                4.7.0
    DB Version:                              4.7.0
    
    composer install:                        --no-dev
    APP_ENV:                                 production
    APP_DEBUG:                               false
    
    System:                                  Linux
    PHP Version:                             8.1.14
    PHP User agent:                          Lychee/4 (https://lycheeorg.github.io/)
    Timezone:                                UTC
    Max uploaded file size:                  512M
    Max post size:                           512M
    Max execution time:                      30
    MySQL Version:                           10.5.18-MariaDB-0+deb11u1
    
    exec() Available:                        yes
    Imagick Available:                       1
    Imagick Enabled:                         1
    Imagick Version:                         1691
    GD Version:                              2.3.3
    Number of foreign key:                   11 found.

    Config Information
    --------------
    version:                                 040700
    check_for_updates:                       0
    sorting_photos_col:                      taken_at
    sorting_photos_order:                    ASC
    sorting_albums_col:                      max_taken_at
    sorting_albums_order:                    ASC
    imagick:                                 1
    skip_duplicates:                         0
    small_max_width:                         0
    small_max_height:                        360
    medium_max_width:                        1920
    medium_max_height:                       1080
    lang:                                    en
    layout:                                  1
    image_overlay_type:                      desc
    default_license:                         none
    compression_quality:                     90
    grants_full_photo_access:                1
    delete_imported:                         0
    mod_frame_enabled:                       1
    mod_frame_refresh:                       30
    thumb_2x:                                1
    small_2x:                                1
    medium_2x:                               1
    landing_page_enable:                     0
    site_owner:                              John Smith
    landing_title:                           John Smith
    landing_subtitle:                        Cats, Dogs & Humans Photography
    sm_facebook_url:                         https://www.facebook.com/JohnSmith
    sm_flickr_url:                           https://www.flickr.com/JohnSmith
    sm_twitter_url:                          https://www.twitter.com/JohnSmith
    sm_instagram_url:                        https://instagram.com/JohnSmith
    sm_youtube_url:                          https://www.youtube.com/JohnSmith
    landing_background:                      dist/cat.webp
    site_title:                              Lychee v4
    footer_show_copyright:                   1
    site_copyright_begin:                    2019
    site_copyright_end:                      2019
    footer_additional_text:                  
    footer_show_social_media:                0
    public_search:                           0
    SL_enable:                               0
    SL_for_admin:                            0
    public_recent:                           0
    recent_age:                              1
    public_starred:                          0
    grants_download:                         0
    photos_wraparound:                       1
    map_display:                             0
    zip64:                                   1
    map_display_public:                      0
    map_provider:                            Wikimedia
    force_32bit_ids:                         0
    map_include_subalbums:                   0
    update_check_every_days:                 3
    has_exiftool:                            0
    share_button_visible:                    0
    import_via_symlink:                      0
    has_ffmpeg:                              1
    location_decoding:                       0
    location_decoding_timeout:               30
    location_show:                           1
    location_show_public:                    0
    rss_enable:                              0
    rss_recent_days:                         7
    rss_max_items:                           100
    prefer_available_xmp_metadata:           0
    editor_enabled:                          1
    lossless_optimization:                   0
    swipe_tolerance_x:                       150
    swipe_tolerance_y:                       250
    local_takestamp_video_formats:           .avi|.mov
    log_max_num_line:                        1000
    unlock_password_photos_with_url_param:   0
    nsfw_visible:                            1
    nsfw_blur:                               0
    nsfw_warning:                            0
    nsfw_warning_admin:                      0
    nsfw_banner_override:                    
    map_display_direction:                   1
    album_subtitle_type:                     oldstyle
    upload_processing_limit:                 4
    public_photos_hidden:                    1
    new_photos_notification:                 0
    legacy_id_redirection:                   1
    zip_deflate_level:                       6
    SA_enabled:                              1
    default_album_protection:                1
    album_decoration:                        layers
    album_decoration_orientation:            row
    allow_username_change:                   1

### Browser and system

Safara and iPhone 15.4.1

**Comment by ildyria** [comment]
I don't have iphones, so I am unable to reproduce. :(

**Comment by ildyria** [comment]
@nicokaiser Could you have a look at that one, pretty please?

**Comment by nicokaiser** [comment]
I cannot test in Safari 15, because I updated all of my devices to iOS 16...
This might be related to https://github.com/LycheeOrg/Lychee-front/pull/335 because `overflow: clip` was introduced there, which is only supported in Safari 16.

One might  argue that every device which supports iOS/Safari 15 also supports iOS/Safari 16, but I don't know if it would be possible to live without `overflow: clip` and hence support many older browsers (now that we transpile WebAuthn https://github.com/LycheeOrg/Lychee-front/issues/380 and polyfill ResizeObserver https://github.com/LycheeOrg/Lychee/issues/2081 )...

**Comment by qwerty287** [comment]
@Binnette which version were you using before the upgrade?

**Comment by doclbn** [comment]
I can confirm @Binnette‘s issues. Mine appeared after migrating from 4.6.2 to 4.7.0.

Hope this helps,
-doclbn

**Comment by jscmidt** [comment]
Lychee still isn‘t working on iPhone 7 (no iOS 16 compatibility).
What Information do you need?

Edit:
It is not working at my installation (v4.11.0), however it is working at the demo (v4.2.1).

**Comment by ildyria** [comment]
> It is not working at my installation (v4.11.0), however it is working at the demo (v4.2.1).

This is probably due to some layout change that Matthias did months ago.
Unfortunately I am still in the same state. Can't really fix anything as I don't have apple devices.

That being said. It would be very helpful for me if you could have a look at the `livewire/more-work` branch and see how this is behaving on iphone. I am currently working on a huge refactoring of the front-end...
