### ISSUE TITLE
Live photos from iPhone are sometimes broken

### ISSUE THREAD

**Issue by jockebr** [LycheeOrg/Lychee#1746]
### Detailed description of the problem [REQUIRED]
When uploading live photos from my iPhone, as a foo.jpg + foo.mov pair, sometimes Lychee does not associate and pair them. 

When it doesn't, I will have two entries in the album. One for the .jpg and one for the .mov. I can click on either and get the expected result. 

When it does pair them, the thumbnail will show a "live" indicator overlay, which is fine, and the thumbnail will be the expected image, but clicking on it will show a black picture. 

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Add/upload files of a live photo pair (jpg+mov) from the iPhone. Have tried various ways through the web interface; clicking the [+] -> upload photo; or drag-dropping files into an album; one file at a time or a pair of jpg+mov, or many files as a batch. Successful pairing seems random.
2. Observe what the seemingly random result of pairing these files as a live photo is. If paired; 
3. Observe that the thumbnail is showing the expected result and has a live icon in the corner.
4. Click the thumbnail
5. Observe nothing :(

**Screenshots**
Here is an unsuccessful pairing, showing the jpg and mov as separate entries in the album. The filenames are identical, save for the extension. 
https://i.imgur.com/eGmU0Hx.png

Here is a successful pairing, showing the "live" icon overlay in the corner. 
https://i.imgur.com/s7I5NQW.png

Clicking on that will show nothing but black along with a 🚫 stop sign on the live icon overlay
https://i.imgur.com/RkzcER3.png

### Output of the diagnostics  [REQUIRED]
Diagnostics here: https://pastebin.com/EZxqJmwm

### Browser and system
I am using a curated docker image provided by linuxserver.io, https://github.com/linuxserver/docker-lychee, but this seems like a bug with the software itself rather than their side. 

As browser I'm using Firefox which is kept updated, so the latest version, or at least a reasonably recent one, on Windows 10. Files from the iPhone were copied over to local hdd before uploading to Lychee. Files are fine on local hdd with seemingly no pattern to successful/failing pairing.

**Comment by FartherOut** [comment]
I have the same issue,.
Every live photo shows up as black when trying to view them.
I also tried to convert the video file from HEVC/H.265 to AVC/H.264 to see if this is the problem but it didn't solve anything.
"Normal" (not part of photo/video duo) H.264 videos plays as expected.

Docker on Ubuntu 20.04
Edge 109.0.1518.70 on windows 10
Safari on iOS 16.3

**Comment by ildyria** [comment]
Unfortunately, I don't have an Iphone to test. Would any of you be able to provide us with a zip of a file that breaks ?

**Comment by ezek1el** [comment]
I have the same problem with my Galaxy S21FE Android phone. On my desktop, I can view the images without any problems. Converting the images to another file format is just an inconvenient workaround at the moment. Without conversion, the thumbnail shows the image, but when you click on it to view it, you only get a black screen showing only the LIVE tag. The original can be viewed without any problems.

Lychee 4.7.3 
Diagnostics: [https://pastebin.com/a0x1wrgq](https://pastebin.com/a0x1wrgq)
Firefox 112.0.2 on Windows 10
