### ISSUE TITLE
No preview of photos after upload, but no error and diagnostic looks fine

### ISSUE THREAD

**Issue by MagnusHL** [LycheeOrg/Lychee#1747]
### Detailed description of the problem
I am a new user to Lychee and finished the installation on a sharedhost.
The Installation is almost working, I don't get any errors but I cannot see the Image.

## Video of Upload
[Video](https://screen.hinzke.de/L136L0NK)

## Diagnostic output
[Diagnostic output in PasteBin](https://pastebin.hinzke.de/?c1f6b6c30b1b074a#A2p1VBGw2FmdtjZSwamKGrP3X1ATroHXDkeYwUrCUava)

## Update output
[Update output](https://pastebin.hinzke.de/?8ef08ea8560c9ce2#BtvRk6uPo3MEizd6bxks168md2c7YusoREZWNuzRgCYD)

### Browser and system
Chrome, Safari

**Comment by ildyria** [comment]
Hi, thank you for following the template and sorry for the late reply.

> I am a new user to Lychee and finished the installation on a sharedhost. The Installation is almost working, I don't get any errors but I cannot see the Image.

Can you check the url of the image using the Inspect tools with like F12 / Ctrl/Command+Shift+I  ?
Seems like the href data in the url are broken for some reason...

**Comment by MagnusHL** [comment]
Hi!

Thanks for reply!
https://pastebin.hinzke.de/?453c4729aadb5ff4#HB9a4tmFg8NC9Abjj2ahbRoebpENqmfTE1sRMsip2Whm

I don't see any mistake.
Files are on the filesystem: https://pastebin.hinzke.de/?c697f3003df0d453#2KnZsDi7HhGXa81gEA5sQjxDtXBhfoPuN5LRHxfXHjb8

**Comment by MagnusHL** [comment]
It is a problem with the file system rights. The directories need to be accessible by other.

All new directories get the wrong permission. How can I fix it?

**Comment by qwerty287** [comment]
Do you have shell access?

**Comment by MagnusHL** [comment]
Yes, I have.

**Comment by qwerty287** [comment]
Then you should be able to change the file/dir permissions using `chmod` (or I get your point wrong)

**Comment by MagnusHL** [comment]
Correct, but your app creates new folders and this folder got the wrong rights.

**Comment by MagnusHL** [comment]
![CleanShot 2023-02-08 at 20 01 36@2x](https://user-images.githubusercontent.com/6343677/217626781-a0f6c2b9-72a1-46f6-aca5-e8928f45a3eb.png)

**Comment by MagnusHL** [comment]
![CleanShot 2023-02-08 at 20 01 36@2x](https://user-images.githubusercontent.com/6343677/217626959-9ff81fbd-52ba-4e41-af21-b2ca3dd23150.png)

The other directories I chmoded and the marked one, is a new upload.

**Comment by qwerty287** [comment]
Ah, that's what you mean. You should definitely be able to just chmod them once (otherwise this would be really weird behavior), but I need to investigate a bit more... Are the shell user and the user which executes the php scripts if the website is opened the same? Or is it possible that something's mixed up here (if you upload via web interface, this shouldn't happen though)?

**Comment by d7415** [comment]
@MagnusHL Are your directories configured according to https://lycheeorg.github.io/docs/#directory-permissions (specifically the sgid bits)?

**Comment by MagnusHL** [comment]
Hi!

I set the correct right (755), but every new directory ist getting 750.
That is something I cannot control.

Upload from other php apps get 755, upload with ftp too.

umask is 0022 so 0755 would be fine.

Hope you have any idears?

**Comment by fungalcofe** [comment]
Hi,

I just installed Lychee using Yunohost.
Upload is working fine, however, I can't see pictures: they all result in an HTTP 403.

I had to change the `/home/yunohost.apps/lychee` from `750` to `755` and job's done.

<details>
<summary>initial thought, but I was wrong, expand for original</summary>
I've checked directories right, and they look good to me:

``` shell
ls -l uploads/
total 40
drwxrwsr-x  2 root   lychee 4096 Apr  8 19:49 big
drwxrwsr-x  2 root   lychee 4096 Apr  8 19:49 import
drwxrwsr-x 81 root   lychee 4096 Apr  8 19:53 medium
drwxrwsr-x 45 lychee lychee 4096 Apr  8 19:53 medium2x
drwxrwsr-x 81 lychee lychee 4096 Apr  8 19:53 original
drwxrwsr-x  2 root   lychee 4096 Apr  8 19:49 raw
drwxrwsr-x 81 root   lychee 4096 Apr  8 19:53 small
drwxrwsr-x 81 lychee lychee 4096 Apr  8 19:53 small2x
drwxrwsr-x 81 root   lychee 4096 Apr  8 19:53 thumb
drwxrwsr-x 81 lychee lychee 4096 Apr  8 19:53 thumb2x
```

``` shell
ls -l uploads/small2x/
total 316
drwxrwsr-x 3 lychee lychee 4096 Apr  8 19:53 0a
```

``` shell
ls -l uploads/small2x/0a/aa/
total 92
-rw-rw-r-- 1 lychee lychee 91597 Apr  8 19:53 377fc6ae95956cd62935adac5bf2.jpg
```

I also notice the file `dist/user.css` ends in HTTP 403.

```
ls -l /var/www/lychee/public/dist
total 1580
-rwxrwsr-x 1 lychee lychee  172010 Mar  8 11:22 cat.webp
-rwxrwsr-x 1 lychee lychee       0 Apr  8 19:49 custom.js
drwxrwsr-x 2 lychee lychee    4096 Mar  8 11:22 fonts
-rwxrwsr-x 1 lychee lychee   94020 Mar  8 11:22 frontend.css
-rwxrwsr-x 1 lychee lychee   69784 Mar  8 11:22 frontend.html
-rwxrwsr-x 1 lychee lychee 1109853 Mar  8 11:22 frontend.js
-rwxrwsr-x 1 lychee lychee   52329 Mar  8 11:22 landing.css
-rwxrwsr-x 1 lychee lychee  102953 Mar  8 11:22 landing.js
-rw-r----- 1 lychee lychee     661 Apr  8 19:50 user.css
```
</details>
