### ISSUE TITLE
Share icon not active after update to 4.7.0

### ISSUE THREAD

**Issue by MrLivre** [LycheeOrg/Lychee#1752]
### Detailed description of the problem [REQUIRED]
I have updated to 4.7.0 and the share icon doesn't work since

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Go to an apublic album 
2. Click on a photo
3. Click on the share icon
4. Nothng happen

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

### Output of the diagnostics  [REQUIRED]
Diagnostics
    -------
    Warning: Dropbox import not working. dropbox_key is empty.
    Info: Latest version of PHP is 8.2

    System Information
    --------------
    Lychee Version (release):                4.7.0
    DB Version:                              4.7.0
    
    composer install:                        --no-dev
    APP_ENV:                                 production
    APP_DEBUG:                               false
    
    System:                                  Linux
    PHP Version:                             8.1.14
    PHP User agent:                          Lychee/4 (https://lycheeorg.github.io/)
    Timezone:                                Europe/Paris
    Max uploaded file size:                  32M
    Max post size:                           128M
    Max execution time:                      200
    MySQL Version:                           10.6.12-MariaDB
    
    exec() Available:                        yes
    Imagick Available:                       1
    Imagick Enabled:                         1
    Imagick Version:                         1808
    GD Version:                              2.3.3
    Number of foreign key:                   11 found.

    Config Information
    --------------
    version:                                 040700
    check_for_updates:                       1
    sorting_photos_col:                      taken_at
    sorting_photos_order:                    DESC
    sorting_albums_col:                      max_taken_at
    sorting_albums_order:                    ASC
    imagick:                                 1
    skip_duplicates:                         0
    small_max_width:                         0
    small_max_height:                        360
    medium_max_width:                        1920
    medium_max_height:                       1080
    lang:                                    fr
    layout:                                  1
    image_overlay_type:                      desc
    default_license:                         reserved
    compression_quality:                     90
    grants_full_photo_access:                1
    delete_imported:                         0
    mod_frame_enabled:                       1
    mod_frame_refresh:                       30
    thumb_2x:                                1
    small_2x:                                1
    medium_2x:                               1
    landing_page_enable:                     1
    site_owner:                              Bernard Bourcy
    landing_title:                           Bernard Bourcy Photographies
    landing_subtitle:                        Mes photos prises le long de mes randonnées.
    sm_facebook_url:                         https://www.facebook.com/bernard.bourcy
    sm_flickr_url:                           
    sm_twitter_url:                          
    sm_instagram_url:                        
    sm_youtube_url:                          
    landing_background:                      dist/02-IMG_1897.JPG
    site_title:                              Bernard Bourcy Photographies
    footer_show_copyright:                   1
    site_copyright_begin:                    2004
    site_copyright_end:                      2023
    footer_additional_text:                  
    footer_show_social_media:                0
    public_search:                           1
    SL_enable:                               0
    SL_for_admin:                            0
    public_recent:                           0
    recent_age:                              1
    public_starred:                          0
    grants_download:                         0
    photos_wraparound:                       1
    map_display:                             0
    zip64:                                   1
    map_display_public:                      0
    map_provider:                            Wikimedia
    force_32bit_ids:                         1
    map_include_subalbums:                   0
    update_check_every_days:                 3
    has_exiftool:                            0
    share_button_visible:                    0
    import_via_symlink:                      0
    has_ffmpeg:                              0
    location_decoding:                       0
    location_decoding_timeout:               30
    location_show:                           1
    location_show_public:                    0
    rss_enable:                              0
    rss_recent_days:                         7
    rss_max_items:                           100
    prefer_available_xmp_metadata:           0
    editor_enabled:                          1
    lossless_optimization:                   0
    swipe_tolerance_x:                       150
    swipe_tolerance_y:                       250
    local_takestamp_video_formats:           .avi|.mov
    log_max_num_line:                        1000
    unlock_password_photos_with_url_param:   0
    nsfw_visible:                            1
    nsfw_blur:                               0
    nsfw_warning:                            0
    nsfw_warning_admin:                      0
    nsfw_banner_override:                    
    map_display_direction:                   1
    album_subtitle_type:                     oldstyle
    upload_processing_limit:                 4
    public_photos_hidden:                    1
    new_photos_notification:                 0
    legacy_id_redirection:                   1
    zip_deflate_level:                       6
    SA_enabled:                              1
    default_album_protection:                1
    album_decoration:                        layers
    album_decoration_orientation:            row
    allow_username_change:                   1

**Comment by oblomow** [comment]
Same here. 
![afbeelding](https://user-images.githubusercontent.com/427760/217512359-4e16f232-01c8-4b18-9d92-54ccd1e4d005.png)


    System Information
    --------------
  Lychee Version (git):                    master (5533538) -- Up to date (54 minutes ago).
  DB Version:                              4.7.1
  System:                                  FreeBSD
  PHP Version:                             8.1.13
  PHP User agent:                          Lychee/4 (https://lycheeorg.github.io/)
  Timezone:                                Europe/Amsterdam
  MySQL Version:                           8.0.31

**Comment by qwerty287** [comment]
@MrLivre this is fixed in 4.7.1
@oblomow this is another issue. Did you enable the option in the global settings (this is new since 4.7.1)?

**Comment by oblomow** [comment]
yes: 

![afbeelding](https://user-images.githubusercontent.com/427760/217576323-e47e9e59-bea3-4df6-aaec-fa262bc583f2.png)

**Comment by qwerty287** [comment]
https://github.com/LycheeOrg/Lychee-front/pull/392 should fix it
