### ISSUE TITLE
[Enhancement] Re-create size variants when missing.

### ISSUE THREAD

**Issue by afranchuk** [LycheeOrg/Lychee#1760]
I'd like to backup my Lychee photos, but only the originals, because backing up the originals as well as the size variants uses about 80% more disk space (for my images at least)! I read the code briefly and couldn't see anywhere where the size variants are recreated if they are missing (though the creation code does check whether they already exist and skips creation, so maybe I missed something?). In the worst-case where I have to restore from backups, I'd only have the originals (ideally, to save space), but would like Lychee to fill in the missing sizes. If this might be inefficient to add as an on-the-fly feature, I'd be happy with some CLI command to do it once. Thanks!

**Comment by ildyria** [comment]
In my case, I have:
```
▶ du -sh uploads/*
206G	uploads/big
4.0K	uploads/import
14G	uploads/medium
4.0K	uploads/medium2x
8.6G	uploads/original
1.1G	uploads/raw
1.5G	uploads/small
4.0K	uploads/small2x
2.2G	uploads/thumb
195M	uploads/thumb2x
4.0K	uploads/tracks
```
So the other size variants are about 12% of a full back-up (code size compared to upload is negligible).

Nevertheless:
`php artisan lychee:generate-thumbs --help` will provide the tools to do that generation.
https://github.com/LycheeOrg/Lychee/blob/master/app/Console/Commands/GenerateThumbs.php

In theory there should also be the ghostbuster command but I haven't tested it for a long time:
https://github.com/LycheeOrg/Lychee/blob/master/app/Console/Commands/Ghostbuster.php

While the GhostBuster command should be exactly covering your case, for your backup you can also you can just skip the size_variants, but then you will need to go to your Database and **remove all size variants with of type strictly greater than 0** : https://github.com/LycheeOrg/Lychee/blob/master/app/Enum/SizeVariantType.php#L12

**Comment by ildyria** [comment]
This should probably be added to:
https://lycheeorg.github.io/docs/faq_general.html
https://lycheeorg.github.io/docs/faq_installation.html
https://lycheeorg.github.io/docs/faq_troubleshooting.html

I do not know however which section it should go in.

**Comment by afranchuk** [comment]
Excellent, I was hoping there was already a command to do it!

I'd say it would be appropriate under FAQ, however I think the "question" should be "what files should I backup" and the answer should give the broad response ("uploads and the database") as well as a subheading about the fact that thumbs can be regenerated.

Personally I'd prefer the files to be rearranged such that all generated size variant directories reside in their _own_ directory (i.e. not as siblings to the originals directory, if that makes sense), but it's not a huge deal.

**Comment by ildyria** [comment]
> Personally I'd prefer the files to be rearranged such that all generated size variant directories reside in their _own_ directory (i.e. not as siblings to the originals directory, if that makes sense), but it's not a huge deal.

That is already the case. If you look in the Upload directory, all the size_variants are in the medium/small/thumb etc directory while the originals are in big/original directory (we had a change of infrastructure a few months back thus the duplicate).

**Comment by afranchuk** [comment]
I meant that all originals (big/original) are in one directory (e.g. `user_uploads`) and the size_variant dirs are somewhere entirely different (e.g. `derived`). More accurately, I wouldn't consider the size variants as `uploads`. And from a data-centric point of view, I'd like to be able to point Lychee at a directory to use (on my NAS) for the originals, while keeping the derived size variants local (both for access speed and to not automatically back them up with the rest of the NAS). It's not a big deal though, I can work around it with symlinks to get the files where I want them.

**Comment by afranchuk** [comment]
For example:
```
uploads/
  - big/
  - original/
  - raw/
derived/
  - medium/
  - small/
  - thumb/
```
