### ISSUE TITLE
notifcation emails not sending (4.7.0)

### ISSUE THREAD

**Issue by ryanfiller** [LycheeOrg/Lychee#1763]
Hi, I am on v 4.7.0 (running the docker image `lscr.io/linuxserver/lychee:latest`)

<details>
<summary>Diagnostics</summary>
<pre>
-----------
Warning: Dropbox import not working. dropbox_key is empty.
Warning: You may experience problems when uploading a photo of large size. Take a look in the FAQ for details.
Info: Latest version of PHP is 8.2
Error: /app/www/.git (and subdirectories) are not executable, check the permissions
Foreign key: albums.parent_id               → albums.id            : RESTRICT
Foreign key: albums.id                      → base_albums.id       : RESTRICT
Foreign key: albums.cover_id                → photos.id            : CASCADE
Foreign key: base_albums.owner_id           → users.id             : RESTRICT
Foreign key: photos.album_id                → albums.id            : RESTRICT
Foreign key: photos.owner_id                → users.id             : RESTRICT
Foreign key: size_variants.photo_id         → photos.id            : RESTRICT
Foreign key: sym_links.size_variant_id      → size_variants.id     : RESTRICT
Foreign key: tag_albums.id                  → base_albums.id       : RESTRICT
Foreign key: user_base_album.base_album_id  → base_albums.id       : CASCADE
Foreign key: user_base_album.user_id        → users.id             : CASCADE

System Information
------------------
Lychee Version (git):                    ?? (60c6f34) -- Could not compare.
DB Version:                              4.7.0

composer install:                        --no-dev
APP_ENV:                                 production
APP_DEBUG:                               false

System:                                  Linux
PHP Version:                             8.1.14
PHP User agent:                          Lychee/4 (https://lycheeorg.github.io/)
Timezone:                                America/Chicago
Max uploaded file size:                  20M
Max post size:                           200M
Max execution time:                      200
MySQL Version:                           10.6.12-MariaDB-log

exec() Available:                        yes
Imagick Available:                       1
Imagick Enabled:                         1
Imagick Version:                         1808
GD Version:                              bundled (2.1.0 compatible)
Number of foreign key:                   11 found.

Config Information
------------------
version:                                 040700
check_for_updates:                       0
sorting_photos_col:                      taken_at
sorting_photos_order:                    DESC
sorting_albums_col:                      max_taken_at
sorting_albums_order:                    ASC
imagick:                                 1
skip_duplicates:                         0
small_max_width:                         0
small_max_height:                        360
medium_max_width:                        1920
medium_max_height:                       1080
lang:                                    en
layout:                                  1
image_overlay_type:                      desc
default_license:                         none
compression_quality:                     90
grants_full_photo_access:                1
delete_imported:                         0
mod_frame_enabled:                       1
mod_frame_refresh:                       30
thumb_2x:                                1
small_2x:                                1
medium_2x:                               1
landing_page_enable:                     0
site_owner:                              Gabby & Ryan
landing_title:                           John Smith
landing_subtitle:                        Cats, Dogs & Humans Photography
sm_facebook_url:                         
sm_flickr_url:                           
sm_twitter_url:                          
sm_instagram_url:                        
sm_youtube_url:                          
landing_background:                      dist/cat.webp
site_title:                              G & R
footer_show_copyright:                   0
site_copyright_begin:                    2019
site_copyright_end:                      2019
footer_additional_text:                  
footer_show_social_media:                0
public_search:                           1
SL_enable:                               0
SL_for_admin:                            0
public_recent:                           1
recent_age:                              1
public_starred:                          0
grants_download:                         0
photos_wraparound:                       1
map_display:                             0
zip64:                                   1
map_display_public:                      0
map_provider:                            Wikimedia
force_32bit_ids:                         0
map_include_subalbums:                   0
update_check_every_days:                 3
has_exiftool:                            1
share_button_visible:                    0
import_via_symlink:                      0
has_ffmpeg:                              1
location_decoding:                       0
location_decoding_timeout:               30
location_show:                           0
location_show_public:                    0
rss_enable:                              0
rss_recent_days:                         7
rss_max_items:                           100
prefer_available_xmp_metadata:           0
editor_enabled:                          1
lossless_optimization:                   0
swipe_tolerance_x:                       150
swipe_tolerance_y:                       250
local_takestamp_video_formats:           .avi|.mov
log_max_num_line:                        1000
unlock_password_photos_with_url_param:   0
nsfw_visible:                            1
nsfw_blur:                               0
nsfw_warning:                            0
nsfw_warning_admin:                      0
nsfw_banner_override:                    
map_display_direction:                   1
album_subtitle_type:                     oldstyle
upload_processing_limit:                 4
public_photos_hidden:                    1
new_photos_notification:                 1
legacy_id_redirection:                   1
zip_deflate_level:                       6
SA_enabled:                              1
default_album_protection:                1
album_decoration:                        layers
album_decoration_orientation:            row
allow_username_change:                   1
</pre>
</details>

**Comment by d7415** [comment]
Have you set the relevant [options](https://lycheeorg.github.io/docs/configuration.html#mailer-options) in the way that container image requires?

Alternatively, there's an official image at [LycheeOrg/Lychee-Docker](https://github.com/LycheeOrg/Lychee-Docker) (`lycheeorg/lychee`).

**Comment by ryanfiller** [comment]
I had issues with the official image recognizing my database, although I'm willing to explore that more if that's the most correct answer.

I may have misunderstood how the notifications work, do I need to set up a separate email service and then hook it up to Lychee via the config tokens you linked to?

**Comment by d7415** [comment]
> do I need to set up a separate email service and then hook it up to Lychee via the config tokens you linked to?

Lychee can't magically send emails. You can configure a MTA on the host (container), use an existing SMTP server or any of the other options in the page I linked. But whichever you pick, you need to tell Lychee what to use.

**Comment by ryanfiller** [comment]
> You can configure a MTA on the host (container)

I may be misunderstanding again, but what do you mean here? Add an smtp server to my Lychee stack, or is there some way to turn on an included one?

**Comment by d7415** [comment]
It's possible (though unlikely) that the image you're using ships with one. Otherwise you could build an image with one installed. You'd need to make sure it was configured to send mail in a compatible way though. In most cases, especially with Docker involved, you'd be better off with an SMTP server or service though.

**Comment by ryanfiller** [comment]
Thank you. I'm closing this issue, it seems unrelated to Lychee and I'm sure I can figure out how to configure the integration once I get the other service up and running.
