### ISSUE TITLE
400 Bad Request Header Exception Invalid token on fresh install on yunohost 11.1.11.2 (stable)

### ISSUE THREAD

**Issue by DavidLep0le** [LycheeOrg/Lychee#1767]
### Detailed description of the problem [REQUIRED]
*A clear and concise description of what the bug is.*
After a fresh install on a newly install of yunohost i got a [lychee] 400 Bad Request Header Exception Invalid token
### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Go to 'lychee app on a YunoHost 11.1.11.2 (stable) '
2. Click on 'the app button, fill user/ pass and i got the issue'

4. See error*: 400 Bad Request Header Exception Invalid token

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

### Output of the diagnostics  [REQUIRED]
*(Settings => [Diagnostics or https://example.com/Diagnostics or `php artisan lychee:diagnostics](https://paste.yunohost.org/raw/ajidigemaw)`)*

### Browser and system
firefox mint-001-1.0 and chromium Version 109.0.5414.119 (Build officiel) for Linux Mint (64 bits)
copy of the post on yunohost forum :

## :uk:/:us:   
Hello
I got these issue for several weeks.
I don't find solution and it happen on a fresh install.

### My YunoHost server
**Hardware:**  computer at home / Linux 5.10.0-21-amd64 x86_64
CPU : AMD Ryzen 7 3700X 8-Core Processor (16 cores) Ram : 31.34 GB
**YunoHost version:** YunoHost 11.1.11.2 (stable)
**I have access to my server :** Through SSH | through the webadmin | direct access via keyboard / screen | ALL 3
**Are you in a special context or did you perform some particular tweaking on your YunoHost instance ?** : yes
**If yes, please explain:**
it's a machine with several HD

*sda 
├─sda1 1,1T /media/AAA
└─sda2 6,1T /media/VIDZ
*sdb 9,1T  
└─sdb1 9,1T /media/10TERABYTES
*sdc 9,1T 
├─sdc1 8,1T /media/10_Tera_V2
└─sdc2 1005,9G /media/BBB
*sdd 3,6T 
└─sdd1 3,6T /media/3T---BK-up
*nvme0n1 931,5G
├─nvme0n1p1  /boot        
├─nvme0n1p5  [SWAP]
└─nvme0n1p6  /
**If your request is related to an app, specify its name and version:**  lychee Version : 4.7.0~ynh1

### Description of my issue

 **provide detailed error messages and logs if you can**:log for a new install : https://paste.yunohost.org/raw/ajidigemaw

There is these line into logs :

*2023-02-28 22:35:24,661: INFO - [##################..] > Configuring permissions...
*2023-02-28 22:35:24,661: DEBUG - + ynh_permission_update --permission=main --add=visitors
*2023-02-28 22:35:24,711: DEBUG - + add=visitors
&
*2023-02-28 22:35:24,995: INFO - [##################+.] > Reloading NGINX web server...
*2023-02-28 22:35:24,995: DEBUG - + ynh_systemd_action --service_name=nginx --action=reload

At the end we got:
*2023-02-28 22:35:25,093: INFO - [####################] > Installation of lychee completed
*2023-02-28 22:35:25,093: DEBUG - + ynh_exit_properly
*2023-02-28 22:35:26,095: DEBUG - Checking that required services are up and running...
*2023-02-28 22:35:26,734: SUCCESS - Installation terminée

I perform a fresh install on a new yunohost instance.
I just type the user/pass same as the user for nextcloud.
and i got the error :
[lychee] 400 Bad Request Header Exception Invalid token

---------------------------------------------
## :fr: 
Bonjour
Ce problème persiste...
J'ai aussi mis quelquechose sur le github de yunohost

Je n'ai pas de solution, c'est une installation neve de ynohost et de lychee.
Juste après le rensignement du user/pass ça plante en 400 Bad Request Header Exception Invalid token

**Hardware:**  computer at home / Linux 5.10.0-21-amd64 x86_64
CPU : AMD Ryzen 7 3700X 8-Core Processor (16 cores) Ram : 31.34 GB
**YunoHost version:** YunoHost 11.1.11.2 (stable)
**accès  server :**  SSH |  webadmin | direct accès via clavier / écran | 
**contexte** : oui
**explication:**
Machine avec plusieurs disques

*sda 
├─sda1 1,1T /media/AAA
└─sda2 6,1T /media/VIDZ
*sdb 9,1T  
└─sdb1 9,1T /media/10TERABYTES
*sdc 9,1T 
├─sdc1 8,1T /media/10_Tera_V2
└─sdc2 1005,9G /media/BBB
*sdd 3,6T 
└─sdd1 3,6T /media/3T---BK-up
*nvme0n1 931,5G
├─nvme0n1p1  /boot        
├─nvme0n1p5  [SWAP]
└─nvme0n1p6  /
**version de l'app concernée:**  lychee Version : 4.7.0~ynh1

### Description du problème

 **logs**: https://paste.yunohost.org/raw/ajidigemaw

dans les logs il y a :
*2023-02-28 22:35:24,661: INFO - [##################..] > Configuring permissions...
*2023-02-28 22:35:24,661: DEBUG - + ynh_permission_update --permission=main --add=visitors
*2023-02-28 22:35:24,711: DEBUG - + add=visitors
&
*2023-02-28 22:35:24,995: INFO - [##################+.] > Reloading NGINX web server...
*2023-02-28 22:35:24,995: DEBUG - + ynh_systemd_action --service_name=nginx --action=reload

mais à la fin on a 
*2023-02-28 22:35:25,093: INFO - [####################] > Installation of lychee completed
*2023-02-28 22:35:25,093: DEBUG - + ynh_exit_properly
*2023-02-28 22:35:26,095: DEBUG - Checking that required services are up and running...
*2023-02-28 22:35:26,734: SUCCESS - Installation terminée
 
Toute l'installation semble fonctionner;
on peut acceder à une fenêtre de lychee qui demande un utilisateur mot de passe.
Une fois renseignée ces deux infos l'erreur s'active :

hop un écran avec
[lychee] 400 Bad Request Header Exception Invalid token

--------------------------------------------------

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Go to 'lychee app on a YunoHost 11.1.11.2 (stable) '
2. Click on 'the app button, fill user/ pass and i got the issue'

4. See error*: 400 Bad Request Header Exception Invalid token

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

### Output of the diagnostics  [REQUIRED]
*(Settings => [Diagnostics or https://example.com/Diagnostics or `php artisan lychee:diagnostics](https://paste.yunohost.org/raw/ajidigemaw)`)*

### Browser and system
firefox mint-001-1.0 and chromium Version 109.0.5414.119 (Build officiel) for Linux Mint (64 bits)
![Capture du 2023-03-02 16-21-50](https://user-images.githubusercontent.com/74555046/222471534-4208a8e0-a335-4b77-a6fa-5ff83d065d92.png)
![Capture du 2023-03-02 16-19-50](https://user-images.githubusercontent.com/74555046/222471559-7555c660-db6e-4170-a752-5a3db0038f45.png)
![Capture du 2023-03-02 16-24-55](https://user-images.githubusercontent.com/74555046/222472138-cc160c6e-d05b-4e31-bd3f-f868ac6ae7c1.png)

**Comment by ildyria** [comment]
My instincts tell me this is because you have a Bearer Token that is used by Yuno.
https://github.com/LycheeOrg/Lychee/blob/master/app/Services/Auth/SessionOrTokenGuard.php#L307 See here.
I would suggest to edit your `.env`  and set 
`ENABLE_TOKEN_AUTH` to `false` see here: https://github.com/LycheeOrg/Lychee/blob/master/config/auth.php

This will disable the token authentication and skip this problem.

I strongly believe this is something that should be fixed on https://github.com/YunoHost-Apps/lychee_ynh

**Comment by DavidLep0le** [comment]
Hello,
thanks for this track:

I find the yunohost .env in var
nano /var/www/lychee/.env

But it don’t work, nano said .env couldn’t be edit…
So several questions :
    Where is the .env file to modify it …?
    does Yunohost got a token service to modify ?

Thanks for helping

**Comment by ildyria** [comment]
I don't use Yuno, so you will need to see that with them. My guess is that this is in https://github.com/YunoHost-Apps/lychee_ynh/blob/master/conf/.env.example or something similar.

For the side of Lychee, this issue is now out of scope so I will be closing it. It is on you to figure out how to edit that `.env` file to reflect your settings.

**Comment by ericgaspar** [comment]
`ENABLE_TOKEN_AUTH=false` do not solve the issue
