### ISSUE TITLE
Mod Welcome = Landing Page 

### ISSUE THREAD

**Issue by LRZNc** [LycheeOrg/Lychee#1768]
hello..
Would you like to use welcome mode as the homepage?
I really liked the layout of the page,
Example, and right after the animation the public albums appear

**Comment by ildyria** [comment]
I guess you mean the welcome text becomes stand alone separated from the actual landing picture and thus can be used on its own.

I am totally fine with that, but I doubt anyone in the team would currently have the time to implement it.

Todo:

- [ ] : add setting to select if albums or landing image is displayed after welcome text.
- [ ] : implement the actual front side.
