### ISSUE TITLE
[DOCUMENTATION] Users API documentation incorrect

### ISSUE THREAD

**Issue by adimajo** [LycheeOrg/Lychee#1770]
### Detailed description of the problem [REQUIRED]
The "User" endpoints in the documentation [https://lycheeorg.github.io/docs/api.html#apiuserlist](https://lycheeorg.github.io/docs/api.html#apiuserlist) are incorrect

### Steps to reproduce the issue
Try to go to the endpoint documented /api/User::Create => endpoint does not exist
Try to go to the undocumented endpoint /api/User**s**::**c**reate => OK

Same for all other functions w.r.t. User**s**, missing the s and the second argument is lowercase (like all other endpoints!).

### Output of the diagnostics  [REQUIRED]
Not Applicable

### Browser and system
Ubuntu 22.04 / Chrome and / or Python (Pychee)

**Comment by qwerty287** [comment]
These API documentation is completely outdated, so there will be more information that's not longer correct. We're looking into automatically generated API docs that are always up-to-date then, but this will probably take a while to arrive, we have other priorities currently.

**Comment by adimajo** [comment]
Thanks for the quick answer; I didn't see any API-related questions so I thought I'd post this issue...
I see the routes are defined in [routes/api.php](https://github.com/LycheeOrg/Lychee/blob/master/routes/api.php) but I don't know any PHP so I won't be able to help w.r.t. auto generating docs.
