### ISSUE TITLE
Choose thumbnails for videos [Enhancement]

### ISSUE THREAD

**Issue by sigulete** [LycheeOrg/Lychee#1776]
Hi,

Is it possible to change the thumbnail picked automatically for videos?
Also, I didn't have ffmpeg setup in my server in the beginning, so only the latest videos have a thumbnail. Is it possible to run a script to create thumbnails retrospectively?

**Comment by qwerty287** [comment]
> Is it possible to run a script to create thumbnails retrospectively?

The easiest way might be to just re-upload the videos, I would have to take some look at the code to find out how to create thumbnails afterwards.

**Comment by tomstgeorge** [comment]
Is there any way to manually create and then upload (via FTP) a thumbnail for video and to add it to the video for those that do not have ffmpeg on shared hosting
