### ISSUE TITLE
Updating 4.4.0 to 4.7.0 fails with 403: incorrect username or password

### ISSUE THREAD

**Issue by mniemela** [LycheeOrg/Lychee#1779]
### Detailed description of the problem [REQUIRED]
I get error 403: Incorrect username or password when trying to migrate from 4.4.0 to 4.7.0. I tried this multiple times by rolling back the virtual machine to the state before upgrade attempt. This seems to be the same bug as issue #1456, except I don't have a massive amount of pictures.

### Steps to reproduce the issue
1. Execute following commands on the system with Lychee 4.4.0:

root@foo:~# cd /var/www/html/
root@foo:/var/www/html# wget https://github.com/LycheeOrg/Lychee/releases/download/v4.7.0/Lychee.zip
root@foo:/var/www/html# mv Lychee Lychee-old
root@foo:/var/www/html# unzip Lychee.zip
...
root@foo:/var/www/html# cp Lychee-old/.env Lychee/.env
root@foo:/var/www/html# mv Lychee-old/public/uploads/ Lychee/public/uploads/
root@foo:/var/www/html# chown -R www-data:www-data Lychee

2. Go to the web page. It shows the error message. Entering the admin username and password has no effect.

**Screenshots**
![image](https://user-images.githubusercontent.com/7679721/226974451-e459f28b-5585-44fc-940a-a6dae1125695.png)

### Output of the diagnostics  [REQUIRED]
I can't access the diagnostics in the state.

### Browser and system
Chrome/Windows 11 as client.

Lychee is running on Ubuntu 22.04 LTS and mysql as database.

**Comment by mniemela** [comment]
Anything new about this?

**Comment by ildyria** [comment]
I'll try to have a look today.

**Comment by ildyria** [comment]
```
Documents/Projects/Lychee  v4.4.0 ✗                                                                      1y154d ⚑ ◒  ⍉
▶ composer install  
php-http/discovery contains a Composer plugin which is currently not in your allow-plugins config. See https://getcomposer.org/allow-plugins
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - phpspec/prophecy is locked to version 1.14.0 and an update of this package was not requested.
    - phpspec/prophecy 1.14.0 requires php ^7.2 || ~8.0, <8.2 -> your php version (8.2.5) does not satisfy that requirement.
  Problem 2
    - phpspec/prophecy 1.14.0 requires php ^7.2 || ~8.0, <8.2 -> your php version (8.2.5) does not satisfy that requirement.
    - phpunit/phpunit 9.5.10 requires phpspec/prophecy ^1.12.1 -> satisfiable by phpspec/prophecy[1.14.0].
    - phpunit/phpunit is locked to version 9.5.10 and an update of this package was not requested.
```
That's going to be a problem...

**Comment by ildyria** [comment]
I am getting close to having a fix for you but it will force you to bump to version 4.8.
