### ISSUE TITLE
[Demo] Upgrade to a newer version, current: 4.2

### ISSUE THREAD

**Issue by math-GH** [LycheeOrg/Lychee#1782]
### Detailed description of the problem [REQUIRED]
The current version of the demo is 4.2.1

![grafik](https://user-images.githubusercontent.com/1645099/229267980-ae2de03d-cbdf-421f-8795-b697c922b62e.png)
(Screen shot from the login screen)

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
see: https://lycheeorg.github.io/demo/

**Comment by ildyria** [comment]
The demo is not a server really running. It is hosted on githubPages as It is a static website where the AJAX requests responses are mocked...

**Comment by qwerty287** [comment]
There was a suggestion somewhere to ask some hoster to sponsor a little vps so we can set up a real demo server.

**Comment by ildyria** [comment]
That would be great, but I lack the time for that. :/
