### ISSUE TITLE
FORCE_MIGRATION_IN_PRODUCTION=1 is being ignored

### ISSUE THREAD

**Issue by meulie** [LycheeOrg/Lychee#1802]
I have 'FORCE_MIGRATION_IN_PRODUCTION=1' in my .env file, but when I go to Diagnostics and click on 'Update available!', I still get:

Update not applied: `APP_ENV` in `.env` is `production` and `force_migration_in_production` is set to `0`.

Lychee Version (git):                    master (2f74019)

**Comment by ildyria** [comment]
Go into settings -> more settings (at the bottom) -> look in the Admin section.
There you will find the `force_migration_in_production` setting.
