### ISSUE TITLE
[Enhancement] Link to site

### ISSUE THREAD

**Issue by VegarOyfoss** [LycheeOrg/Lychee#1807]
I am using Lychee in a sub-domain for my site, and I am running it next to a word press installation. 
On my top menu I will have a link to the gallery which would be "gallery.website.com". But once someone clicks this link, there is no easy way to add a link to get my back to my main site "www.website.com"

It would be great to have a feature to place a link on the top to go back

**Comment by arthurmv** [comment]
I think you can enable landing page or modify the footer.
At Settings in the end, press the red button called `More`. Then you'll see a section named `Mod Welcome`, there you can change the value of `landing_page_enable` from `0` to `1`, then add a link in HTML format on `landing_subtitle`.
I didn't give a try but maybe you can add a link in this way.

**Comment by ildyria** [comment]
> I think you can enable landing page or modify the footer. At Settings in the end, press the red button called `More`. Then you'll see a section named `Mod Welcome`, there you can change the value of `landing_page_enable` from `0` to `1`, then add a link in HTML format on `landing_subtitle`. I didn't give a try but maybe you can add a link in this way.

In Vegar specific use case, he already has a website, so a landing page does not bring much.
What he wants is that orange arrow which allows him to go back to his main website from his gallery.
![image](https://user-images.githubusercontent.com/627094/234233301-d44f44fa-abf1-475e-801f-cc2c10451dca.png)
