### ISSUE TITLE
Parser Error

### ISSUE THREAD

**Issue by tjdrakechoto** [LycheeOrg/Lychee#1813]
### Parser Error [REQUIRED]
*After a long time, `i tried accessing my lychee directory it shows parser error  *

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Go to '(https://istrivemarketplace.com/gallery/)'
2. Click on link
3. Shows error

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

### Output of the diagnostics  [REQUIRED]
*(Settings => Diagnostics or https://example.com/Diagnostics or `php artisan lychee:diagnostics`)*

### Browser and system
![Screenshot istrive](https://user-images.githubusercontent.com/127910773/235085025-e295fc5e-b980-4dca-91ca-f599b584f892.png)

**Comment by ildyria** [comment]
Your link seems to be working fine to me.
I don't see any error, could you be a bit more descriptive ? :|
