### ISSUE TITLE
Tag Albums does not render the slideshow (left right icons)

### ISSUE THREAD

**Issue by naezeroth** [LycheeOrg/Lychee#1849]
When you create a tag album, you have to manually click into each photo and click the x button to see other pictures, whereas in other normal albums you can use the left <- , right -> key or swipe on mobile.

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Create tag album with tag 'test'
2. Add the tag 'test' to multiple images
3. Open the tag album and open an image, you will not be able to swipe or use left/right keys to move between photos.

### Output of the diagnostics  [REQUIRED]

    Diagnostics
    -----------
    Warning: /var/www/html/Lychee/public/uploads/medium/05 has permissions 0755, but should have 2775
    Warning: /var/www/html/Lychee/public/uploads/medium/05/b9 has permissions 0755, but should have 2775
    Warning: /var/www/html/Lychee/public/uploads/medium/08 has permissions 0755, but should have 2775
    Warning: /var/www/html/Lychee/public/uploads/medium/08/4f has permissions 0755, but should have 2775
    Warning: /var/www/html/Lychee/public/uploads/medium/d2 has permissions 0755, but should have 2775
    Warning: 37 more directories with wrong permissions
    Warning: Dropbox import not working. dropbox_key is empty.
    Warning: git (software) is not available.
    Foreign key: albums.parent_id               → albums.id            : RESTRICT
    Foreign key: albums.id                      → base_albums.id       : RESTRICT
    Foreign key: albums.cover_id                → photos.id            : CASCADE
    Foreign key: base_albums.owner_id           → users.id             : RESTRICT
    Foreign key: jobs_history.owner_id          → users.id             : RESTRICT
    Foreign key: photos.album_id                → albums.id            : RESTRICT
    Foreign key: photos.owner_id                → users.id             : RESTRICT
    Foreign key: size_variants.photo_id         → photos.id            : RESTRICT
    Foreign key: sym_links.size_variant_id      → size_variants.id     : RESTRICT
    Foreign key: tag_albums.id                  → base_albums.id       : RESTRICT
    Foreign key: user_base_album.base_album_id  → base_albums.id       : CASCADE
    Foreign key: user_base_album.user_id        → users.id             : CASCADE

    System Information
    ------------------
    Lychee Version (git):                    ?? (f53455e) -- Could not compare.
    DB Version:                              4.7.3
    
    composer install:                        --no-dev
    APP_ENV:                                 production
    APP_DEBUG:                               false
    
    System:                                  Linux
    PHP Version:                             8.2.4
    PHP User agent:                          Lychee/4 (https://lycheeorg.github.io/)
    Timezone:                                Australia/Sydney
    Max uploaded file size:                  100M
    Max post size:                           100M
    Max execution time:                      3600
    MySQL Version:                           10.11.2-MariaDB-1:10.11.2+maria~ubu2204
    
    exec() Available:                        yes
    Imagick Available:                       1
    Imagick Enabled:                         1
    Imagick Version:                         1691
    GD Version:                              2.3.3
    Number of foreign key:                   12 found.

    Config Information
    ------------------
    version:                                 040703
    check_for_updates:                       0
    sorting_photos_col:                      taken_at
    sorting_photos_order:                    ASC
    sorting_albums_col:                      max_taken_at
    sorting_albums_order:                    ASC
    imagick:                                 1
    skip_duplicates:                         0
    small_max_width:                         0
    small_max_height:                        360
    medium_max_width:                        1920
    medium_max_height:                       1080
    lang:                                    en
    layout:                                  1
    image_overlay_type:                      desc
    default_license:                         none
    compression_quality:                     90
    grants_full_photo_access:                1
    delete_imported:                         0
    mod_frame_enabled:                       1
    mod_frame_refresh:                       30
    thumb_2x:                                1
    small_2x:                                1
    medium_2x:                               1
    landing_page_enable:                     0
    site_owner:                              John Smith
    landing_title:                           John Smith
    landing_subtitle:                        Cats, Dogs & Humans Photography
    sm_facebook_url:                         https://www.facebook.com/JohnSmith
    sm_flickr_url:                           https://www.flickr.com/JohnSmith
    sm_twitter_url:                          https://www.twitter.com/JohnSmith
    sm_instagram_url:                        https://instagram.com/JohnSmith
    sm_youtube_url:                          https://www.youtube.com/JohnSmith
    landing_background:                      dist/cat.webp
    site_title:                              Lychee v4
    footer_show_copyright:                   1
    site_copyright_begin:                    2023
    site_copyright_end:                      2099
    footer_additional_text:                  
    footer_show_social_media:                0
    public_search:                           0
    SL_enable:                               0
    SL_for_admin:                            0
    public_recent:                           0
    recent_age:                              1
    public_starred:                          0
    grants_download:                         0
    photos_wraparound:                       1
    map_display:                             0
    zip64:                                   1
    map_display_public:                      0
    map_provider:                            Wikimedia
    force_32bit_ids:                         0
    map_include_subalbums:                   0
    update_check_every_days:                 3
    has_exiftool:                            1
    share_button_visible:                    0
    import_via_symlink:                      0
    has_ffmpeg:                              1
    location_decoding:                       0
    location_decoding_timeout:               30
    location_show:                           1
    location_show_public:                    0
    rss_enable:                              0
    rss_recent_days:                         7
    rss_max_items:                           100
    prefer_available_xmp_metadata:           0
    editor_enabled:                          1
    lossless_optimization:                   0
    swipe_tolerance_x:                       150
    swipe_tolerance_y:                       250
    local_takestamp_video_formats:           .avi|.mov
    log_max_num_line:                        1000
    unlock_password_photos_with_url_param:   0
    nsfw_visible:                            1
    nsfw_blur:                               0
    nsfw_warning:                            0
    nsfw_warning_admin:                      0
    nsfw_banner_override:                    
    map_display_direction:                   1
    album_subtitle_type:                     oldstyle
    upload_processing_limit:                 4
    public_photos_hidden:                    1
    new_photos_notification:                 0
    legacy_id_redirection:                   1
    zip_deflate_level:                       6
    SA_enabled:                              1
    default_album_protection:                1
    album_decoration:                        layers
    album_decoration_orientation:            row
    allow_username_change:                   1
    public_on_this_day:                      0
    auto_fix_orientation:                    1
    use_job_queues:                          0

### Browser and system
Firefox 112.0.2 (64-bit) MacOS 13.1

**Comment by ildyria** [comment]
Hi, 
thank you for following the template it was really useful. :)
Please update to latest version.
This is already fixed. See https://github.com/LycheeOrg/Lychee/pull/1828

**Comment by naezeroth** [comment]
You're a legend!
