### ISSUE TITLE
Not possible to change licence in Lychee 4.8.1

### ISSUE THREAD

**Issue by mniemela** [LycheeOrg/Lychee#1853]
### Detailed description of the problem [REQUIRED]
For me changing licence in Lychee 4.8.1 doesn't work, because pressing the button doesn't do anything.

### Steps to reproduce the issue
1. Go to any photo album
2. Click on the pen icon next to licence
3. Nothing happens

**Screenshots**
![image](https://github.com/LycheeOrg/Lychee/assets/7679721/5b2c8186-ae2d-4a0b-8cac-b37ba920845f)

### Output of the diagnostics  [REQUIRED]
Nothing relevant visible there.

```
    Diagnostics
    -------
    Warning: Dropbox import not working. dropbox_key is empty.
    Warning: Pictures that are rotated lose their metadata! Please install Imagick to avoid that.
    Info: Latest version of PHP is 8.2
    Warning: Default timezone not properly set; you might experience strange results when importing photos without explicit EXIF timezone
```

### Browser and system
Edge/Windows 11

**Comment by ildyria** [comment]
Confirmed issue in the front-end:
```
Uncaught TypeError: Cannot set properties of undefined (setting 'textContent')
    at Object.initSetAlbumLicenseDialog [as readyCB] (frontend.js:2173:133)
    at Object.t [as show] (frontend.js:21:7700)
    at album.setLicense (frontend.js:2173:481)
    at HTMLDivElement.<anonymous> (frontend.js:4167:1161)
    at HTMLDivElement.dispatch (frontend.js:2:43336)
    at y.handle (frontend.js:2:41320)
```

**Comment by ThanasisMpalatsoukas** [comment]
i created a pull request on [Lychee-front](https://github.com/LycheeOrg/Lychee-front) for this with a pull request #401
