### ISSUE TITLE
500 HttpException Target class [log-viewer] does not exist in V4.9.0

### ISSUE THREAD

**Issue by JeanMartinelle** [LycheeOrg/Lychee#1855]
Hi, I just download the Lychee.zip for the 4.9.0 version.
I upload all the files on my online site without issues.
When I try to visualize my photo site (https://www.photos.martinelle.fr/public/) I got the error : 

500
HttpException
Target class [log-viewer] does not exist.

May be I forgot to do something ? I just have access to the file and database on my server.

Have you some idea what's wrong ?
Thanks by advance for your help

Jean

**Comment by qwerty287** [comment]
Did you install the composer dependencies?

**Comment by ildyria** [comment]
I can confirm the bug. I need to rebuild the release.

**Comment by mlapaglia** [comment]
I am on docker image 4.9.2 but am still seeing this issue

**Comment by ildyria** [comment]
~~If you check the actual Lychee version via the left menu, you will notice that something went wrong with the packing of docker image 4.9.2.
I have this on my home server and it is stuck on 4.9.1 for some reason. :(~~

Figured it out.
I was on dev which is built nightly.

~~Use `latest` or `v4.9.2`~~

~~This is no longer a problem with Lychee but with Lychee-docker.~~

**Comment by ildyria** [comment]
Issue is fixed. Tested on my prod server with Docker compose.

In the case of Docker, you may need to set up a few parameters in your apache nginx config.
In the case of nginx in the location block:
```
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Forwarded-Host $host;
proxy_set_header X-Forwarded-Server $host;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header Host $host;
# This line is optional and may help in some cases.
# proxy_set_header X-Forwarded-Port $server_port;
```

In the case of Apache (in my case):
```
<VirtualHost *:443>
        ServerName lychee.mydomain.com
        ServerAdmin EMAIL
        ProxyPreserveHost On
        ProxyRequests Off
        SSLEngine On
        SSLCertificateFile      /etc/letsencrypt/live/.../fullchain.pem
        SSLCertificateKeyFile   /etc/letsencrypt/live/.../privkey.pem
        ProxyPass / http://127.0.0.1:8080/
        ProxyPassReverse / http://127.0.0.1:8080/
        ErrorLog ${APACHE_LOG_DIR}/finance_error.log
        CustomLog ${APACHE_LOG_DIR}/finance_access.log combined
        RequestHeader set X-Forwarded-Proto expr=%{REQUEST_SCHEME}
        RequestHeader set X-Forwarded-SSL expr=%{HTTPS}
</VirtualHost>
```
