### ISSUE TITLE
4.9.1 release missing

### ISSUE THREAD

**Issue by gramakri** [LycheeOrg/Lychee#1860]
### Detailed description of the problem [REQUIRED]

4.9.1 release is tagged but a release is missing - https://github.com/LycheeOrg/Lychee/releases

Because of this Lychee.zip is also not generated/downloadable.

**Comment by d7415** [comment]
It looks like 4.9.1 failed to fix the issue it was released for, so has been removed. Hopefully a 4.9.2 will follow soon.

**Comment by ildyria** [comment]
> It looks like 4.9.1 failed to fix the issue it was released for, so has been removed. Hopefully a 4.9.2 will follow soon.

Yes I killed it for that reason sadly. CSP proves to be trickier than expected.
