### ISSUE TITLE
Can't remove album permissions - v4.9.2

### ISSUE THREAD

**Issue by Rendili** [LycheeOrg/Lychee#1868]
### Detailed description of the problem [REQUIRED]
Adding permissions to an album is ok, but once a user has been given permission to an album it is not possible to remove that users permissions from an album again.

### Steps to reproduce the issue

1. Open an album
2. Click on the "share this album with users" button top right
3. Tick a user and click "Save"
4. Click on the "share this album with users" button top right
5. Untick a user and click "Save"
6. Click on the "share this album with users" button top right
7. The permission is not removed

--------------

1. Settings
2. Sharing
3. Tick some permissions to remove
4. Click "Remove"
5. An error appears "Error: Forbidden - Insufficient privileges"

![image](https://github.com/LycheeOrg/Lychee/assets/30532082/2298e4f7-3e9a-4c14-b343-86d824f4b35c)

### Output of the diagnostics  [REQUIRED]
    Diagnostics
    -------
    Warning: Dropbox import not working. dropbox_key is empty.
    Warning: git (software) is not available.
    Foreign key: access_permissions.user_id     → users.id             : CASCADE
    Foreign key: albums.id                      → base_albums.id       : NO ACTION
    Foreign key: base_albums.owner_id           → users.id             : NO ACTION
    Foreign key: jobs_history.owner_id          → users.id             : NO ACTION
    Foreign key: photos.album_id                → albums.id            : NO ACTION
    Foreign key: photos.owner_id                → users.id             : NO ACTION
    Foreign key: size_variants.photo_id         → photos.id            : NO ACTION
    Foreign key: sym_links.size_variant_id      → size_variants.id     : NO ACTION
    Foreign key: tag_albums.id                  → base_albums.id       : NO ACTION

    System Information
    --------------
    Lychee Version (git):                    ?? (a3423b6) -- Could not compare.
    DB Version:                              4.9.2
    
    composer install:                        --no-dev
    APP_ENV:                                 production
    APP_DEBUG:                               false
    
    System:                                  Linux
    PHP Version:                             8.2.5
    PHP User agent:                          Lychee/4 (https://lycheeorg.github.io/)
    Timezone:                                Europe/London
    Max uploaded file size:                  150M
    Max post size:                           150M
    Max execution time:                      3600
    SQLite Version:                          3.40.1
    
    exec() Available:                        yes
    Imagick Available:                       1
    Imagick Enabled:                         1
    Imagick Version:                         1691
    GD Version:                              2.3.3
    Number of foreign key:                   9 found.

    Config Information
    --------------
    version:                                 040902
    check_for_updates:                       0
    sorting_photos_col:                      taken_at
    sorting_photos_order:                    ASC
    sorting_albums_col:                      max_taken_at
    sorting_albums_order:                    ASC
    imagick:                                 1
    skip_duplicates:                         0
    small_max_width:                         0
    small_max_height:                        360
    medium_max_width:                        1920
    medium_max_height:                       1080
    lang:                                    en
    layout:                                  1
    image_overlay_type:                      desc
    default_license:                         none
    compression_quality:                     90
    grants_full_photo_access:                1
    delete_imported:                         0
    mod_frame_enabled:                       1
    mod_frame_refresh:                       30
    thumb_2x:                                1
    small_2x:                                1
    medium_2x:                               1
    landing_page_enable:                     0
    site_owner:                              John Smith
    landing_title:                           John Smith
    landing_subtitle:                        Cats, Dogs & Humans Photography
    sm_facebook_url:                         https://www.facebook.com/JohnSmith
    sm_flickr_url:                           https://www.flickr.com/JohnSmith
    sm_twitter_url:                          https://www.twitter.com/JohnSmith
    sm_instagram_url:                        https://instagram.com/JohnSmith
    sm_youtube_url:                          https://www.youtube.com/JohnSmith
    landing_background:                      dist/cat.webp
    site_title:                              Shared Albums
    footer_show_copyright:                   0
    site_copyright_begin:                    2019
    site_copyright_end:                      2019
    footer_additional_text:                  
    footer_show_social_media:                0
    public_search:                           0
    SL_enable:                               0
    SL_for_admin:                            0
    recent_age:                              1
    grants_download:                         0
    photos_wraparound:                       1
    map_display:                             0
    zip64:                                   1
    map_display_public:                      0
    map_provider:                            Wikimedia
    force_32bit_ids:                         0
    map_include_subalbums:                   0
    update_check_every_days:                 3
    has_exiftool:                            1
    share_button_visible:                    0
    import_via_symlink:                      0
    has_ffmpeg:                              1
    location_decoding:                       0
    location_decoding_timeout:               30
    location_show:                           1
    location_show_public:                    0
    rss_enable:                              0
    rss_recent_days:                         7
    rss_max_items:                           100
    prefer_available_xmp_metadata:           0
    editor_enabled:                          1
    lossless_optimization:                   0
    swipe_tolerance_x:                       150
    swipe_tolerance_y:                       250
    local_takestamp_video_formats:           .avi|.mov
    log_max_num_line:                        1000
    unlock_password_photos_with_url_param:   0
    nsfw_visible:                            1
    nsfw_blur:                               0
    nsfw_warning:                            0
    nsfw_warning_admin:                      0
    nsfw_banner_override:                    
    map_display_direction:                   1
    album_subtitle_type:                     oldstyle
    upload_processing_limit:                 4
    public_photos_hidden:                    1
    new_photos_notification:                 0
    legacy_id_redirection:                   1
    zip_deflate_level:                       6
    SA_enabled:                              1
    default_album_protection:                1
    album_decoration:                        layers
    album_decoration_orientation:            row
    allow_username_change:                   0
    auto_fix_orientation:                    1
    use_job_queues:                          0
    random_album_id:                         starred
    use_last_modified_date_when_no_exif_date: 0

### Browser and system
Edge, Chrome

**Comment by ildyria** [comment]
That is indeed a problem.

**Comment by ildyria** [comment]
Was able to reproduce the first bug.
I am not able to reproduce the second bug, but I found another one (wrong table).

**Comment by Rendili** [comment]
Testing this after updating to v4.9.3 looks like this has all been fixed.
Thanks for your time and effort with all the latest updates.
