### ISSUE TITLE
Getting "server error or api not found" on initial Install

### ISSUE THREAD

**Issue by flyerfocus** [LycheeOrg/Lychee#1877]
Hello, I am using a shared server with a /public_html directory under my home directory.  From what I have been reading I suspect that may have something to do with why this error is happening.

I have downloaded using git clone https://github.com/electerious/Lychee.git

I then copied the entire directory structure into my ~/public_html directory.

I then went to http://myipaddress/~myusername and I get a black screen with the "server error or api not found" error.

uname -a = Linux web1.escape.com 4.18.0-348.7.1.el8_5.x86_64 #1 SMP Tue Dec 21 13:57:48 EST 2021 x86_64 x86_64 x86_64 GNU/Linux

Client: Win 10
Browser: Both Edge & Firefox

### Detailed description of the problem [REQUIRED]
*A clear and concise description of what the bug is.*

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
4. See error*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

### Output of the diagnostics  [REQUIRED]
*(Settings => Diagnostics or https://example.com/Diagnostics or `php artisan lychee:diagnostics`)*

**Comment by ildyria** [comment]
Hi,

Your issue is about electerious/Lychee, not LycheeOrg/Lychee.
electerious is the very old version of Lychee (v3) and no longer supported, we are currently on version 4.9.2.

Closing.

**Comment by ildyria** [comment]
https://lycheeorg.github.io/docs
https://lycheeorg.github.io/docs/releases.html
