### ISSUE TITLE
thumb 404

### ISSUE THREAD

**Issue by sunosv** [LycheeOrg/Lychee#1892]
### Detailed description of the problem [REQUIRED]
Long time no see, I noticed that it has now been updated to version 4.9.2
I feel that it has greatly improved. Thank you for your hard work
But I encountered a problem, maybe only winNT exists.
Thumb load address escape error
Currently, I have found that it only appears in thumb
There is no similar situation in medium, medium2x, small, or small2x

`http://192.168.6.6:70/uploads/thumb%0E%C2%9B%EF%BF%BD0f4777a108888bf0e4dd23.jpeg`
`
Because there was garbled code here
**thumb%0E%C2%9B%EF%BF%BD**

`http://192.168.6.6:70/uploads/small2x/0e/9b/21c7e30f4777a108888bf0e4dd23.jpg`

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Click on a single image
2. View browser developer tools
4. See error*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*
[![pCGMSj1.png](https://s1.ax1x.com/2023/06/21/pCGMSj1.png)](https://imgse.com/i/pCGMSj1)
[![pCGMaD0.png](https://s1.ax1x.com/2023/06/21/pCGMaD0.png)](https://imgse.com/i/pCGMaD0)
[![pCGIilT.png](https://s1.ax1x.com/2023/06/21/pCGIilT.png)](https://imgse.com/i/pCGIilT)
### Output of the diagnostics  [REQUIRED]
 Diagnostics
    -------
    Warning: Dropbox import not working. dropbox_key is empty.
    Warning: zend.assertions is enabled although Lychee is not in debug mode. Outside of debugging, code generation for assertions is recommended to be disabled for efficiency reasons
    Info: Latest version of PHP is 8.2
    Foreign key: access_permissions.user_id     → users.id             : CASCADE
    Foreign key: albums.parent_id               → albums.id            : RESTRICT
    Foreign key: albums.id                      → base_albums.id       : RESTRICT
    Foreign key: albums.cover_id                → photos.id            : CASCADE
    Foreign key: base_albums.owner_id           → users.id             : RESTRICT
    Foreign key: jobs_history.owner_id          → users.id             : RESTRICT
    Foreign key: photos.album_id                → albums.id            : RESTRICT
    Foreign key: photos.owner_id                → users.id             : RESTRICT
    Foreign key: size_variants.photo_id         → photos.id            : RESTRICT
    Foreign key: sym_links.size_variant_id      → size_variants.id     : RESTRICT
    Foreign key: tag_albums.id                  → base_albums.id       : RESTRICT
    Foreign key: albums.parent_id               → albums.id            : RESTRICT
    Foreign key: albums.id                      → base_albums.id       : RESTRICT
    Foreign key: albums.cover_id                → photos.id            : CASCADE
    Foreign key: base_albums.owner_id           → users.id             : RESTRICT
    Foreign key: page_contents.page_id          → pages.id             : RESTRICT
    Foreign key: photos.album_id                → albums.id            : RESTRICT
    Foreign key: photos.owner_id                → users.id             : RESTRICT
    Foreign key: size_variants.photo_id         → photos.id            : RESTRICT
    Foreign key: sym_links.size_variant_id      → size_variants.id     : RESTRICT
    Foreign key: tag_albums.id                  → base_albums.id       : RESTRICT
    Foreign key: user_base_album.base_album_id  → base_albums.id       : CASCADE
    Foreign key: user_base_album.user_id        → users.id             : CASCADE
    Foreign key: web_authn_credentials.user_id  → users.id             : RESTRICT
    Foreign key: albums.parent_id               → albums.id            : RESTRICT
    Foreign key: albums.id                      → base_albums.id       : RESTRICT
    Foreign key: albums.cover_id                → photos.id            : CASCADE
    Foreign key: base_albums.owner_id           → users.id             : RESTRICT
    Foreign key: photos.album_id                → albums.id            : RESTRICT
    Foreign key: photos.owner_id                → users.id             : RESTRICT
    Foreign key: size_variants.photo_id         → photos.id            : RESTRICT
    Foreign key: sym_links.size_variant_id      → size_variants.id     : RESTRICT
    Foreign key: tag_albums.id                  → base_albums.id       : RESTRICT
    Foreign key: user_base_album.base_album_id  → base_albums.id       : CASCADE
    Foreign key: user_base_album.user_id        → users.id             : CASCADE

    System Information
    --------------
    Lychee Version (release):                4.9.2
    DB Version:                              4.9.2
    
    composer install:                        --no-dev
    APP_ENV:                                 production
    APP_DEBUG:                               false
    
    System:                                  WINNT
    PHP Version:                             8.1.2
    PHP User agent:                          Lychee/4 (https://lycheeorg.github.io/)
    Timezone:                                Asia/Shanghai
    Max uploaded file size:                  3210M
    Max post size:                           3210M
    Max execution time:                      300
    MySQL Version:                           5.7.28
    
    exec() Available:                        yes
    Imagick Available:                       1
    Imagick Enabled:                         1
    Imagick Version:                         1808
    GD Version:                              bundled (2.1.0 compatible)
    Number of foreign key:                   35 found.

**Comment by ildyria** [comment]
Sorry for the delay.
Knowing the code of Lychee, my guess is that something is going wrong in your DB.

Could you make the following query:
```sql
SELECT * FROM `size_variants` WHERE `short_path` LIKE 'thumb\\%0E\\%C2\\%9B\\%EF\\%BF%';
```
Hopefully this should give us a list of all the broken thumbs.
