### ISSUE TITLE
[Enhancement] Add more permission levels to album permissions

### ISSUE THREAD

**Issue by Rendili** [LycheeOrg/Lychee#1905]
It would be really useful to have a bit more control over who can do what in albums, more granularity of permissions a person can have in an album would be great.

The main one for me is giving the ability for someone who is not an owner of an album to upload photos to the album.

This would be a great addition in the scenario where someone could create a new album at an event where family / friends were also attending and everyone could upload their photos to the same album to share with everyone else.

The following permission levels would be really good, each one as a tickbox in the GUI (except maybe for Owner):

- **Owner** (as today, the owner of the album, can modify everything about the album and edit permissions)
- **Upload** (only available to a person once View has been granted and gives the ability to upload photos to the album)
- **Edit / Delete** (only available to a person once View has been granted and gives the ability to edit photos and delete photos)
- **View** (gives only the ability to view the photos in the album, but not edit (not able to edit tags, description, title, rotate photo, etc.), delete or upload)

**Comment by ildyria** [comment]
Hi, thank you for the idea.
This is actually already on our radar:

See: https://github.com/LycheeOrg/Lychee/issues/1462 
And: 
https://github.com/LycheeOrg/Lychee/blob/20da3a1076c7347ef76ed3e86ecac6bbd7bd043e/app/Models/AccessPermission.php#L58-L74

**Comment by Rendili** [comment]
excellent, thanks for the link, that is pretty much covers everything.

sorry for the duplicate, my search of existing didn't include those key words.

if there is anything i can help with let me know, adding an upload permission at an album level would enable me to use this much more extensively

**Comment by ildyria** [comment]
Redesigning the sharing menu would be an improvement.
We don't have the API end point to modify the access rights yet (still need to be implemented, you can give a try at it :) ).

Some of the access rights integrations are already there. e.g. 
https://github.com/LycheeOrg/Lychee/blob/master/app/Policies/AlbumPolicy.php#L171
