### ISSUE TITLE
No composer available

### ISSUE THREAD

**Issue by ThierryIT** [LycheeOrg/Lychee#1909]
### Detailed description of the problem [REQUIRED]
*A clear and concise description of what the bug is.*
1) when trying for the first time to reach my Lychee website (fresh install)

403
This is the root directory and MUST NOT BE PUBLICLY ACCESSIBLE.
To access Lychee, go [here](https://www1.dagga-boys.org/public/).

After clicking on it as requested:

503
../vendor/autoload.php not found.
Please do: composer install --no-dev --prefer-dist

In the Lychee folder, I only have the folder "composer-cache" , the file "composer.json" and "composer.lock". 

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Go to 'the URL of my Lychee website'
4. See error: 
503
../vendor/autoload.php not found.
Please do: composer install --no-dev --prefer-dist

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

### Output of the diagnostics  [REQUIRED]
*(Settings => Diagnostics or https://example.com/Diagnostics or `php artisan lychee:diagnostics`)*

/var/www/html/Lychee$ sudo php artisan lychee:diagnostics
PHP Warning:  require(/var/www/html/Lychee/vendor/autoload.php): Failed to open stream: No such file or directory in /var/www/html/Lychee/artisan on line 18
PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/html/Lychee/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/Lychee/artisan:18
Stack trace:
#0 {main}
  thrown in /var/www/html/Lychee/artisan on line 18

### Browser and system
Browser: Brave [Version 1.52.126](https://brave.com/latest/)
System: Ubuntu

**Comment by qwerty287** [comment]
Install composer on your system and install dependencies with `cpmposer install`. And RTFM before opening an issue, please. Every requirement should be listed there.
