### ISSUE TITLE
Usage of legacy OpenStreetMap tile URLs

### ISSUE THREAD

**Issue by otbutz** [LycheeOrg/Lychee#1934]
International style: https://github.com/openstreetmap/operations/issues/737

The new URL format: `http://tile.openstreetmap.org/{z}/{x}/{y}.png`

The old subdomains of tile.openstreetmap.de are getting retired on 2023-08-01 see https://community.openstreetmap.org/t/a-b-c-tile-openstreetmap-de-subdomains-von-tile-openstreetmap-de-werden-aufgehoben/100830

The new URL format: `http://tile.openstreetmap.de/{z}/{x}/{y}.png`

**Comment by ildyria** [comment]
Unfortunately I don't have the time to implement that change. I don't think it should be hard though.
Probably some modifications in 
https://github.com/LycheeOrg/Lychee-front/blob/master/scripts/main/mapview.js
https://github.com/LycheeOrg/Lychee/blob/master/config/secure-headers.php
And maybe some other files

**Comment by qwerty287** [comment]
See https://github.com/LycheeOrg/Lychee-front/pull/406 and #1935

**Comment by otbutz** [comment]
@qwerty287 the German style URLs are fixed but the international style still uses the {s}.tile.osm.org domain which should be changed to tile.openstreetmap.org

**Comment by qwerty287** [comment]
But the forum post you linked above only mentioned the .de domains, or did I miss something?

**Comment by otbutz** [comment]
See the very first link to https://github.com/openstreetmap/operations/issues/737
