### ISSUE TITLE
Internal server error on photo upload (permissions?)

### ISSUE THREAD

**Issue by mateusz-holysz** [LycheeOrg/Lychee#1948]
### Detailed description of the problem [REQUIRED]

It is not possible to add new photos. The (gui) upload lychee page shows an internal server error and in the logs there is the following entry: 
App\Http\Requests\Photo\AddPhotoRequest::processValidatedValues:39 Cannot assign string to property App\Http\Requests\Photo\AddPhotoRequest::$fileLastModifiedTime of type ?int

Owner and group of public/uploads and public/sym directories are dedicated docker user and users.
See my docker compose file attached.

### Steps to reproduce the issue
1. Go to any existing folder or create new one.
2. Click on "+" and click on "Upload photo". 
3. See that photo upload failed due to server error.
4. See error in logs: App\Http\Requests\Photo\AddPhotoRequest::processValidatedValues:39 Cannot assign string to property App\Http\Requests\Photo\AddPhotoRequest::$fileLastModifiedTime of type ?int

### Output of the diagnostics  [REQUIRED]

Diagnostics
-----------
Warning: /var/www/html/Lychee/public/uploads/ is owned by group users, but should be owned by one out of root
Warning: /var/www/html/Lychee/public/uploads/import is owned by group users, but should be owned by one out of root
Warning: /var/www/html/Lychee/public/uploads/small2x is owned by group users, but should be owned by one out of root
Warning: /var/www/html/Lychee/public/uploads/small2x/8c is owned by group users, but should be owned by one out of root
Warning: /var/www/html/Lychee/public/uploads/small2x/8c/32 is owned by group users, but should be owned by one out of root
Warning: 5166 more directories with wrong owner
Warning: Dropbox import not working. dropbox_key is empty.
Warning: You may experience problems when uploading a photo of large size. Take a look in the FAQ for details.
Warning: You may experience problems when uploading a photo of large size. Take a look in the FAQ for details.
Warning: Using 32 bit PHP, recommended upgrade to 64 bit
Warning: git (software) is not available.

System Information
------------------
Lychee Version (git):                    ?? (a52fd8e) -- Could not compare.
DB Version:                              4.9.4

composer install:                        --no-dev
APP_ENV:                                 production
APP_DEBUG:                               false

System:                                  Linux
PHP Version:                             8.2.7
PHP User agent:                          Lychee/4 (https://lycheeorg.github.io/)
Timezone:                                Europe/Warsaw
Max uploaded file size:                  2M
Max post size:                           8M
Max execution time:                      0
MySQL Version:                           10.6.12-MariaDB-log

exec() Available:                        yes
Imagick Available:                       1
Imagick Enabled:                         1
Imagick Version:                         1691
GD Version:                              2.3.3
Number of foreign key:                   11 found.

Config Information
------------------
version:                                 040904
check_for_updates:                       0
sorting_photos_col:                      taken_at
sorting_photos_order:                    ASC
sorting_albums_col:                      max_taken_at
sorting_albums_order:                    ASC
imagick:                                 1
skip_duplicates:                         0
small_max_width:                         0
small_max_height:                        360
medium_max_width:                        1920
medium_max_height:                       1080
lang:                                    en
layout:                                  1
image_overlay_type:                      desc
default_license:                         reserved
compression_quality:                     90
grants_full_photo_access:                1
delete_imported:                         0
mod_frame_enabled:                       1
mod_frame_refresh:                       30
thumb_2x:                                1
small_2x:                                1
medium_2x:                               1
landing_page_enable:                     0
site_owner:                              A. M. Sz. A. G. Hołyszowie
landing_title:                           John Smith
landing_subtitle:                        Cats, Dogs & Humans Photography
sm_facebook_url:                         https://www.facebook.com/JohnSmith
sm_flickr_url:                           https://www.flickr.com/JohnSmith
sm_twitter_url:                          https://www.twitter.com/JohnSmith
sm_instagram_url:                        https://instagram.com/JohnSmith
sm_youtube_url:                          https://www.youtube.com/JohnSmith
landing_background:                      dist/cat.webp
site_title:                              Lychee v4
footer_show_copyright:                   0
site_copyright_begin:                    2019
site_copyright_end:                      2019
footer_additional_text:                  
footer_show_social_media:                0
public_search:                           0
SL_enable:                               0
SL_for_admin:                            0
recent_age:                              1
grants_download:                         0
photos_wraparound:                       1
map_display:                             0
zip64:                                   1
map_display_public:                      0
map_provider:                            Wikimedia
force_32bit_ids:                         0
map_include_subalbums:                   0
update_check_every_days:                 3
has_exiftool:                            1
share_button_visible:                    0
import_via_symlink:                      0
has_ffmpeg:                              1
location_decoding:                       0
location_decoding_timeout:               30
location_show:                           1
location_show_public:                    0
rss_enable:                              0
rss_recent_days:                         7
rss_max_items:                           100
prefer_available_xmp_metadata:           0
editor_enabled:                          1
lossless_optimization:                   0
swipe_tolerance_x:                       150
swipe_tolerance_y:                       250
local_takestamp_video_formats:           .avi|.mov
log_max_num_line:                        1000
unlock_password_photos_with_url_param:   0
nsfw_visible:                            1
nsfw_blur:                               0
nsfw_warning:                            0
nsfw_warning_admin:                      0
nsfw_banner_override:                    
map_display_direction:                   1
album_subtitle_type:                     oldstyle
upload_processing_limit:                 1
public_photos_hidden:                    1
new_photos_notification:                 0
legacy_id_redirection:                   1
zip_deflate_level:                       6
SA_enabled:                              1
default_album_protection:                1
album_decoration:                        layers
album_decoration_orientation:            row
allow_username_change:                   1
auto_fix_orientation:                    1
use_job_queues:                          0
random_album_id:                         starred
use_last_modified_date_when_no_exif_date: 0

### Browser and system
Firefox 115.0.2 Fedora 38
Chrome 115.0.5790.85 Android 13

[stack.txt](https://github.com/LycheeOrg/Lychee/files/12121784/stack.txt)

**Comment by ammannc** [comment]
This is not a problem with permissions. I haven't figured out a proper fix yet, but setting fileLastModifiedTime to null on line 39 in App\Http\Requests\Photo\AddPhotoRequest is a quick workaround.

**Comment by mateusz-holysz** [comment]
Should I be able to apply this workaround on my own, or do I have to wait for a new lychee version?

**Comment by ildyria** [comment]
A pull request would be better (though there might be some trickery to be applied).
