### ISSUE TITLE
Lazy loading required for recursive album download

### ISSUE THREAD

**Issue by ammannc** [LycheeOrg/Lychee#1950]
### Setting Model::shouldBeStrict(); in /app/Providers/AppServiceProvider.php breaks recursive album download.

When downloading an album with subfolders containing images, the zip file is empty due to an error with lazy loading:
```
Illuminate\Database\Eloquent\Model::handleLazyLoadingViolation:563 Attempted to lazy load [size_variants] on model [App\Models\Photo] but lazy loading is disabled.
App\Actions\Album\Archive::compressAlbum:197 Attempted to lazy load [size_variants] on model [App\Models\Photo] but lazy loading is disabled.;
```

### Steps to reproduce the issue
Download an album with sub-albums containing images.

### Output of the diagnostics  [REQUIRED]
    System Information
    --------------
    Lychee Version (git):                    master (2d899a1) -- Up to date (14 seconds ago).
    DB Version:                              4.9.4
    
    composer install:                        --no-dev
    APP_ENV:                                 production
    APP_DEBUG:                               true
    
    System:                                  Linux
    PHP Version:                             8.2.8
    PHP User agent:                          Lychee/4 (https://lycheeorg.github.io/)
    Timezone:                                Europe/Paris
    Max uploaded file size:                  500M
    Max post size:                           500M
    Max execution time:                      200
    MySQL Version:                           10.5.19-MariaDB-0+deb11u2
    
    exec() Available:                        yes
    Imagick Available:                       1
    Imagick Enabled:                         1
    Imagick Version:                         1691
    GD Version:                              2.3.3
    Number of foreign key:                   11 found.
    
    zip64:                                   1

### Browser and system
Debian 11
Firefox 115.0.2

**Comment by ildyria** [comment]
From my understanding it is because when we query a model with it's relations, the subsequent relations are not populated.
Because an albums has sub albums (children). When we try to query the picture list of those, it breaks.

In that specific case, it might be better to simply disable the `Model::shouldBeStrict()` and eat the recursive SQL queries.
