### ISSUE TITLE
API requests outdated in documentation. Album::setPublic is missing.

### ISSUE THREAD

**Issue by jereminius** [LycheeOrg/Lychee#1965]
### Detailed description of the problem [REQUIRED]
API requests outdated in documentation. Album::setPublic is missing.
App\Http\Controllers\HoneyPotController::throwNotFound:66 The route api/Album::setPublic could not be found.

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Try to call Album::setPublic 
2. Go to logs
3. App\Http\Controllers\HoneyPotController::throwNotFound:66 The route api/Album::setPublic could not be found.

### Output of the diagnostics  [REQUIRED]
Diagnostics
    -------
    Warning: Dropbox import not working. dropbox_key is empty.
    Warning: You may experience problems when uploading a photo of large size. Take a look in the FAQ for details.
    Error: /app/www/.git (and subdirectories) are not executable, check the permissions
    Foreign key: access_permissions.user_id     → users.id             : CASCADE
    Foreign key: albums.parent_id               → albums.id            : RESTRICT
    Foreign key: albums.id                      → base_albums.id       : RESTRICT
    Foreign key: albums.cover_id                → photos.id            : CASCADE
    Foreign key: base_albums.owner_id           → users.id             : RESTRICT
    Foreign key: jobs_history.owner_id          → users.id             : RESTRICT
    Foreign key: photos.album_id                → albums.id            : RESTRICT
    Foreign key: photos.owner_id                → users.id             : RESTRICT
    Foreign key: size_variants.photo_id         → photos.id            : RESTRICT
    Foreign key: sym_links.size_variant_id      → size_variants.id     : RESTRICT
    Foreign key: tag_albums.id                  → base_albums.id       : RESTRICT

    System Information
    --------------
    Lychee Version (git):                    ?? (a52fd8e) -- Could not compare.
    DB Version:                              4.9.4
    
    composer install:                        --no-dev
    APP_ENV:                                 production
    APP_DEBUG:                               false
    
    System:                                  Linux
    PHP Version:                             8.2.8
    PHP User agent:                          Lychee/4 (https://lycheeorg.github.io/)
    Timezone:                                Europe/London
    Max uploaded file size:                  20M
    Max post size:                           200M
    Max execution time:                      200
    MySQL Version:                           10.11.4-MariaDB-log
    
    exec() Available:                        yes
    Imagick Available:                       1
    Imagick Enabled:                         1
    Imagick Version:                         1809
    GD Version:                              bundled (2.1.0 compatible)
    Number of foreign key:                   11 found.

    Config Information
    --------------
    version:                                 040904
    check_for_updates:                       0
    sorting_photos_col:                      created_at
    sorting_photos_order:                    ASC
    sorting_albums_col:                      max_taken_at
    sorting_albums_order:                    ASC
    imagick:                                 1
    skip_duplicates:                         0
    small_max_width:                         0
    small_max_height:                        360
    medium_max_width:                        1920
    medium_max_height:                       1080
    lang:                                    sk
    layout:                                  1
    image_overlay_type:                      none
    default_license:                         none
    compression_quality:                     90
    grants_full_photo_access:                1
    delete_imported:                         0
    mod_frame_enabled:                       1
    mod_frame_refresh:                       30
    thumb_2x:                                1
    small_2x:                                1
    medium_2x:                               1
    landing_page_enable:                     0
    site_owner:                              
    landing_title:                           John Smith
    landing_subtitle:                        Cats, Dogs & Humans Photography
    sm_facebook_url:                         
    sm_flickr_url:                           
    sm_twitter_url:                          
    sm_instagram_url:                        
    sm_youtube_url:                          
    landing_background:                      dist/cat.webp
    site_title:                              lychee
    footer_show_copyright:                   1
    site_copyright_begin:                    2019
    site_copyright_end:                      2019
    footer_additional_text:                  
    footer_show_social_media:                0
    public_search:                           0
    SL_enable:                               0
    SL_for_admin:                            0
    recent_age:                              1
    grants_download:                         0
    photos_wraparound:                       1
    map_display:                             0
    zip64:                                   1
    map_display_public:                      0
    map_provider:                            Wikimedia
    force_32bit_ids:                         0
    map_include_subalbums:                   0
    update_check_every_days:                 3
    has_exiftool:                            1
    share_button_visible:                    0
    import_via_symlink:                      0
    has_ffmpeg:                              1
    location_decoding:                       0
    location_decoding_timeout:               30
    location_show:                           0
    location_show_public:                    0
    rss_enable:                              0
    rss_recent_days:                         7
    rss_max_items:                           100
    prefer_available_xmp_metadata:           0
    editor_enabled:                          1
    lossless_optimization:                   0
    swipe_tolerance_x:                       150
    swipe_tolerance_y:                       250
    local_takestamp_video_formats:           .avi|.mov
    log_max_num_line:                        1000
    unlock_password_photos_with_url_param:   0
    nsfw_visible:                            1
    nsfw_blur:                               0
    nsfw_warning:                            0
    nsfw_warning_admin:                      0
    nsfw_banner_override:                    
    map_display_direction:                   1
    album_subtitle_type:                     oldstyle
    upload_processing_limit:                 4
    public_photos_hidden:                    1
    new_photos_notification:                 0
    legacy_id_redirection:                   1
    zip_deflate_level:                       6
    SA_enabled:                              1
    default_album_protection:                1
    album_decoration:                        layers
    album_decoration_orientation:            row
    allow_username_change:                   1
    auto_fix_orientation:                    1
    use_job_queues:                          0
    random_album_id:                         starred
    use_last_modified_date_when_no_exif_date: 0

**Comment by qwerty287** [comment]
Since 4.8.1 your instance can have its own documentation. See https://github.com/LycheeOrg/Lychee/pull/1827

**Comment by jereminius** [comment]
> Since 4.8.1 your instance can have its own documentation. See #1827

Can I add ::setPublic to my API somehow?

**Comment by ildyria** [comment]
You could, but I don't see the point:
![image](https://github.com/LycheeOrg/Lychee/assets/627094/c424db79-720b-47d9-8850-6bcf0b99c360)

**Comment by jereminius** [comment]
Right, it makes sense.
