### ISSUE TITLE
The CSS tweaks to disable auto zoom in/out no longer work

### ISSUE THREAD

**Issue by Lingxi-Li** [LycheeOrg/Lychee#1973]
### Detailed description of the problem [REQUIRED]
*A clear and concise description of what the bug is.*

In browsing pictures, when there is no mouse movement for a few seconds, the picture will auto zoom in. At mouse movement, it will auto zoom out again. This back-and-forth flickering causes dizziness for me and I want to disable it. The tweaks in #718 do not work for me.

### Steps to reproduce the issue
**Steps to reproduce the behavior:**

1. Follow tweaks in #718 
2. Auto zoom in/out is still there

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

N/A

### Output of the diagnostics  [REQUIRED]
*(Settings => Diagnostics or https://example.com/Diagnostics or `php artisan lychee:diagnostics`)*

~~~
Diagnostics
    -------
    Warning: Dropbox import not working. dropbox_key is empty.
    Warning: Online updates are disabled by configuration
    Foreign key: access_permissions.user_id     → users.id             : CASCADE
    Foreign key: albums.id                      → base_albums.id       : NO ACTION
    Foreign key: base_albums.owner_id           → users.id             : NO ACTION
    Foreign key: jobs_history.owner_id          → users.id             : NO ACTION
    Foreign key: photos.album_id                → albums.id            : NO ACTION
    Foreign key: photos.owner_id                → users.id             : NO ACTION
    Foreign key: size_variants.photo_id         → photos.id            : NO ACTION
    Foreign key: sym_links.size_variant_id      → size_variants.id     : NO ACTION
    Foreign key: tag_albums.id                  → base_albums.id       : NO ACTION
~~~

### Browser and system

Microsoft Edge on Windows 11

**Comment by Lingxi-Li** [comment]
Looks like duplicate of #985. Will try the solution there.

**Comment by Lingxi-Li** [comment]
The solution mentioned in #718 no longer works. Please help. This flickering is way too annoying. Cannot use the product without it disabled.

**Comment by Lingxi-Li** [comment]
I think it's because the numbers in pixels there do not fit my monitor resolution. Need to fine tune it with try-out. But again, this may well cause issue on another monitor setup. Need a more robust solution that works for all.

**Comment by Lingxi-Li** [comment]
This issue is even worse with video. Whenever I seek, I move the mouse, and the video zooms out, only to zoom back in 3 secs later... Basically unusable. Sorry to say, but this feature is an over design, trying to outsmart its users.

**Comment by Lingxi-Li** [comment]
I've found the right numbers. Now, the animation first shrinks and then enlarges back to its original size 🤣

**Comment by ildyria** [comment]
- [ ] Add setting to config to enable zoom full-screen and hide header bar
- [ ] Disable auto-hide header bar on timer if above setting is set to false.

*Marked as Livewire because it will most likely be easier to integrate to the new front-end*
