### ISSUE TITLE
Changing language throws error (black home page)

### ISSUE THREAD

**Issue by a-camacho** [LycheeOrg/Lychee#1975]
### Detailed description of the problem

Changing language from EN to PT for example, breaks gallery.
Homepage is black, errors in console loading .JS.

Getting into database, and changing back to EN solves the problem.

### Steps to reproduce the issue
1. Install Lychee using docker-compose template.
2. Add some photos using `en` language
3. Go to admin and change language to `pt`
4. Save language settings and refresh homepage

**Screenshots**
_Don't have them, sorry._

### Output of the diagnostics
*(Settings => Diagnostics or https://example.com/Diagnostics or `php artisan lychee:diagnostics`)*
_Did fix the problem, so don't have diagnostics any more._
_Could reproduce the problem and get back with them, as soon as I have time for it._

### Browser and system
- Debian 11 - Docker Swarm - Docker compose deployed.
- Accessing with Firefox on Mac OS X (Intel, Mac OS 13.5)

**Comment by d7415** [comment]
~Can't reproduce.~ User ignored template, but this is probably worth a look anyway,

**Comment by a-camacho** [comment]
Updated with template, sorry.

**Comment by d7415** [comment]
Looks like only PT is broken.

**Comment by d7415** [comment]
This is fixed in master. As you're using Docker, it will be in the `:dev` image later today and in the `:latest` image at the next Lychee release.
