### ISSUE TITLE
[Enhancement] Add search / filter for 'Move' destination album list

### ISSUE THREAD

**Issue by vjuliano** [LycheeOrg/Lychee#1989]
When moving a photo, a list of possible destination albums appears, with 'New Album' and 'Unsorted' at the top.  As this list can get quite long, containing the entire expanded album tree, and seems to be sorted by modification date, albums can sometimes be difficult to find.  It would be nice to be able to type the first few letters of an album name and have the list filter down to possible matches.  

Or if it is simpler (although I think this would be less useful), add a config to allow the list to be sorted alphabetically.  

Starting the list with the folder lists collapsed to top level and allowing the user to expand as they drill down may help the issue as well.

**Comment by ildyria** [comment]
Already implemented... in the alpha version using Livewire.
![menuMove](https://github.com/LycheeOrg/Lychee/assets/627094/835d2227-23aa-413c-94b7-62b6c6a2d7a1)
![MenuMoveFilter](https://github.com/LycheeOrg/Lychee/assets/627094/f34b39b8-1f3b-41ae-a4fc-d5effb1c9dc9)

Though New Album may not be a solution yet (not sure if I will add it back).

Note that this version is not going to be live before a while as I am doing this on my free time:
- between the GF,
- the 12h/week competitive dancing training
- and my 40h/week work.

Help is always welcome to make this version 5.0.0 go live faster.
If you want to have a look, the branch is `livewire/more-work`.

**Comment by vjuliano** [comment]
Sweet.  Ok I will have a look.

**Comment by vjuliano** [comment]
How do I trigger the filtering in the livewire move menu?   It seems to be behaving the same as the old one for me.  I cleared cache and refreshed.  Diagnostics lists version running as 'Lychee Version (git):                    livewire/more-work (c50e30d)'

**Comment by ildyria** [comment]
you need to go to `lychee.example.com/livewire/` instead of `lychee.example.com/` :)

and set up in your `.env`
```
# enable Livewire
LIVEWIRE_ENABLED=true
```
Do note this is alpha, and it is using Livewire v3 which is still in beta stages, so some parts are... capricious...
e.g. if you go into an album and then back, the cog wheel no longer work in the header.

Also the move photos is not implemented yet, only move albums.
