### ISSUE TITLE
[Enhancement] Improved install instructions for running Lychee in a subdirectory on Apache

### ISSUE THREAD

**Issue by 01tot10** [LycheeOrg/Lychee#1993]
Hey all,

I'd like to try out Lychee to host my photography. While the project is generally documented in a decent way, I got stuck trying to setup Lychee in a subdirectory instead of the webroot on my Apache-based web server (ex. `www.example.com/lychee`). 

I see people have managed to get it going using either symlinks, mod_rewrite and/or fiddling with some Apache configuration files. At the moment this information is quite scattered, and I found it hard to scrape together a concise installation procedure. My naive attempts ended up in both getting a `403 ERROR` related to the root being exposed and my `.env`-file being served.

If someone with a more clear picture of what is needed could chip in and give instructions on the installation procedure, I could try that out on my end, verify that things are working, and compile a step-by-step guide for the benefit of others. This could also potentially be added to the documentation.

**Comment by 01tot10** [comment]
Here are some tutorials that deal with setting up Lychee on Apache outside the webroot:

- https://www.addictivetips.com/ubuntu-linux-tips/set-up-lychee-photo-management-tool-on-linux/
- https://www.maketecheasier.com/set-up-linux-photo-management-system-with-lychee/
- https://idroot.us/how-to-install-lychee-on-ubuntu-14-04/

All of the aforementioned set up Lychee in `https://www.example.com/Lychee`, and seemingly achieve this via tweaking a configuration file in `/etc/apache2/sites-available/lychee.conf`. On the other hand, the FAQ suggests using symlinks, but the instructions are not very detailed:
https://lycheeorg.github.io/docs/faq_installation.html#can-i-host-lychee-with-a-subpath-with-apache-like-httpsexampledevlychee
Finally, there's a bunch of posts in the issue tracker related to the topic, but it's very hard to make an overview. Here's an example using `.htaccess` for the same thing  https://github.com/LycheeOrg/Lychee/issues/664.

For a non-expert it's hard to see the connection between these approaches, and what are the pros and cons.

**Comment by d7415** [comment]
> Here are some tutorials that deal with setting up Lychee on Apache outside the webroot:
> 
>     * https://www.addictivetips.com/ubuntu-linux-tips/set-up-lychee-photo-management-tool-on-linux/
> 
>     * https://www.maketecheasier.com/set-up-linux-photo-management-system-with-lychee/
> 
>     * https://idroot.us/how-to-install-lychee-on-ubuntu-14-04/

None of these are the current version of Lychee.



> On the other hand, the FAQ suggests using symlinks, but the instructions are not very detailed:
> https://lycheeorg.github.io/docs/faq_installation.html#can-i-host-lychee-with-a-subpath-with-apache-like-httpsexampledevlychee

This is.

**Comment by 01tot10** [comment]
> None of these are the current version of Lychee.
> 
> > On the other hand, the FAQ suggests using symlinks, but the instructions are not very detailed:
> > https://lycheeorg.github.io/docs/faq_installation.html#can-i-host-lychee-with-a-subpath-with-apache-like-httpsexampledevlychee
> 
> This is.

OK, perfect. It would seem like symlinking is the way to go, then.

**Comment by 01tot10** [comment]
I haven't gotten quite in to the symlinking part yet, since I'm having trouble preventing the `403 ERROR` and serving the `.env` file.

### Install procedure so far:

My system qualifies the `Server Requirements` in https://lycheeorg.github.io/docs/installation.html. I've also created a database for Lychee in my mariaDB instance.

Getting the files in place:
> sudo git clone https://www.github.com/LycheeOrg/Lychee /var/www/html/Lychee
> sudo chown -R www-data:www-data /var/www/html/Lychee

Install and run composer for the project:
> sudo -u www-data php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
> sudo -u www-data php -r "if (hash_file('sha384', 'composer-setup.php') === 'e21205b207c3ff031906575712edab6f13eb0b361f2085f1f1237b7126d785e826a450292b6cfd1d64d92e6563bbde02') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
> sudo -u www-data php composer-setup.php;
> sudo php composer-setup.php
> sudo -u www-data php -r "unlink('composer-setup.php');"
> sudo -u www-data php composer.phar install --no-dev

At this point, my APP_KEY is set by composer, so I don't have to run `php artisan key:generate`. I'm not sure if I should run `php artisan migrate`, since it is not mentioned in https://lycheeorg.github.io/docs/installation.html. I assume the same can be achieved via the web installer.

Now at this point, not having created any symlinks, going to `https://my.url/Lychee/` results in the `403 ERROR`. Also, loading `https://my.url/Lychee/.env` shows my environment file, so I'm hesitant to go further. Have I done something wrong, or should I do something additional to fix the problem?

**Comment by d7415** [comment]
> Now at this point, not having created any symlinks, going to `https://my.url/Lychee/` results in the `403 ERROR`. Also, loading `https://my.url/Lychee/.env` shows my environment file, so I'm hesitant to go further. Have I done something wrong, or should I do something additional to fix the problem?

> Yes, just create a Symbolic Link and allow your apache configuration to follow them. At website.com root ln -s Lychee/public pics and you will get exactly what you want: website.com/pics

You need to symlink the `public` directory, not the Lychee root.

**Comment by 01tot10** [comment]
> > Now at this point, not having created any symlinks, going to `https://my.url/Lychee/` results in the `403 ERROR`. Also, loading `https://my.url/Lychee/.env` shows my environment file, so I'm hesitant to go further. Have I done something wrong, or should I do something additional to fix the problem?
> 
> Yes, just create a Symbolic Link and allow your apache configuration to follow them. At website.com root ln -s Lychee/public pics and you will get exactly what you want: website.com/pics
> 
> You need to symlink the `public` directory, not the Lychee root.

Thanks for your assistance! 

I feel like there's something missing with the given solution. I understand how linking `A` to `B/public` will make `A` appear as if it were `B/public`, but it will not do anything to `B` itself and to the other files/directories within it.

E.g. If I create the symlink as
> cd /var/www/html
> sudo ln -s Lychee/public/ pics

, then going to `https://my.url/pics/` will definitely appear as if I was in `https://my.url/Lychee/public/`. But I can still go to `https://my.url/Lychee/` and get the `403 ERROR` and see my `.env` file in `https://my.url/Lychee/.env`. I.e. `B` is still intact and served by Apache, as it doesn't care about those symlinks. I feel like this shouldn't be the case, and something should be done to prevent `B` from being served.

**Comment by d7415** [comment]
Yes, the Lychee directory should not be accessible. The idea is that you put it elsewhere or block it by other means.

**Comment by 01tot10** [comment]
> Yes, the Lychee directory should not be accessible. The idea is that you put it elsewhere or block it by other means.

Thanks! Yes, I think I got the idea, but I think the documentation is a bit vague on this part, and the step doesn't feel fully trivial. I get it that there are different web server configurations, but giving some directions for the users could really benefit the project!

> The idea is that you put it elsewhere...

So would this mean that the step `sudo git clone https://www.github.com/LycheeOrg/Lychee /var/www/html/Lychee` is false, and one should rather clone to outside `/var/www/html/`?

> ... or block it by other means.

And this to me would point to some Apache configuration file, or is there some other way?

Thanks for the assistance!

**Comment by 01tot10** [comment]
Judging by the silence, it appears more certain that the above steps are not fully trivial, which would confirm my initial confusion. I'll try to look for instructions on how to proceed, and keep the thread posted once I find something. In the meanwhile, if someone has a working system running on top of Apache, with the configuration described in the thread, don't hesitate to share!

**Comment by webberian** [comment]
I'm trying to achieve the same thing, with the added complication of being on shared hosting and thus not having access to CLI, symlinks, or other "fancy" server settings.

The idea for my set-up is the following:

- public address: `domain.com/lycheepublic`
- "internal name/URL" of the public folder: `/var/www/vhosts/domain.com/httpdocs/lycheepublic/`
- Lychee top-level, not wide open to the internet: `/var/www/vhosts/domain.com/lycheesecret/`


In order to achieve this, I have modified `index.php` in the Public folder so that the directory calls are made to the following:

e.g. `require_once '/var/www/vhosts/domain.com/lycheesecret/bootstrap/PanicAttack.php';`

In the `.env` file, I have made the following modifications:

```
APP_URL=https://domain.com/lycheepublic

# folders in which the files will be stored
# LYCHEE_UPLOADS="/var/www/html/Lychee-Laravel/public/uploads/"
LYCHEE_UPLOADS="/var/www/vhosts/domain.com/httpdocs/lycheepublic/uploads/"

# url to access those files
# LYCHEE_UPLOADS_URL="uploads/"
LYCHEE_UPLOADS_URL="/var/www/vhosts/domain.com/httpdocs/lycheepublic/uploads/"
```

However, when I access https:// `domain.com/lycheepublic`, I get the following error:

```
500 HttpException

file_get_contents(/var/www/vhosts/domain.com/lycheesecret/public/dist/frontend.html): Failed to open stream: No such file or directory
```

So what seems to be happening is that Lychee is taking my top-level directory and appending the default public folder structure. I get the feeling that the folder and url settings in the `.env` are either being ignored or interpreted incorrectly...

**Comment by ildyria** [comment]
> `LYCHEE_UPLOADS_URL="/var/www/vhosts/domain.com/httpdocs/lycheepublic/uploads/"`

This should be 
> `LYCHEE_UPLOADS_URL="https://domain.com/lycheepublic/uploads/"`

However I do agree there is something weird going on.

**Comment by 01tot10** [comment]
I managed to cram myself forward with the installation, but not quite till the very end.

Basically, as @d7415 mentioned earlier, having the whole `Lychee` folder in the web root (ex. `/var/www/html`) is a security threat, and a good approach is to store the folder elsewhere. Thus, I moved my files outside, e.g.:
```
sudo mv /var/www/html/Lychee/ /var/www/
```

Then, in order to have my desired URL (ex. `https://my.url/photos/`) point to `/var/www/Lychee/public/`, I went about the Alias route, as it was a bit better documented online compared to the symlink approach. I'm using a Debian-based server running Apache 2.4, and in my case this required modifying `/etc/apache2/mods-available/alias.conf` to include:
```
Alias /photos /var/www/Lychee/public
<Directory /var/www/Lychee/public>
   Options FollowSymLinks
   AllowOverride All
   Require all granted
</Directory>
```

At this point, going to `https://my.url/photos/` results in the installer being invoked, and neither `https://my.url/Lychee/` nor `https://my.url/Lychee/.env` exists anymore. Yey!

**Comment by 01tot10** [comment]
While I was able to get the installer to finish with this setup, I'm not able to upload photos to my freshly configured Lychee instance. Trying to upload photos through the web interface results in:
```
App\Http\Requests\Photo\AddPhotoRequest::processValidatedValues:39 Cannot assign string to property App\Http\Requests\Photo\AddPhotoRequest::$fileLastModifiedTime of type ?int
```

I'm not exactly sure, what could be the cause of this. In addition to setting the database credentials during the install procedure, I've edited my `.env`-file to have the `APP_URL` pointing to `https://my.url/photos/`. Moreover, I've tried different combinations of the `LYCHEE_UPLOADS[_URL]`, `LYCHEE_DIST[_URL]` and `LYCHEE_SYM[_URL]` variables, with the ones that make most sense to me being: 
```
LYCHEE_UPLOADS="/var/www/Lychee/public/uploads/"
LYCHEE_DIST="/var/www/Lychee/public/dist/"
LYCHEE_SYM="/var/www/Lychee/public/sym/"
LYCHEE_UPLOADS_URL="https://my.url/photos/uploads/"
LYCHEE_DIST_URL="https://my.url/photos/dist/"
LYCHEE_SYM_URL="https://my.url/photos/sym/"
```

At this point, I'm not sure whether the error is due to a misconfiguration in the `.env`-file, or something with the more exotic subdirectory setup that I have. Here's the output from the [Diagnostics](https://github.com/LycheeOrg/Lychee/files/12682811/diagnostics.log). Here's also the partly censored [.env-file](https://github.com/LycheeOrg/Lychee/files/12682852/env.txt).

I would appreciate any help!

**Comment by ildyria** [comment]
> While I was able to get the installer to finish with this setup, I'm not able to upload photos to my freshly configured Lychee instance. Trying to upload photos through the web interface results in:
> 
> ```
> App\Http\Requests\Photo\AddPhotoRequest::processValidatedValues:39 Cannot assign string to property App\Http\Requests\Photo\AddPhotoRequest::$fileLastModifiedTime of type ?int
> ```

Which web-browser are you using ? :thinking:

**Comment by 01tot10** [comment]
> > While I was able to get the installer to finish with this setup, I'm not able to upload photos to my freshly configured Lychee instance. Trying to upload photos through the web interface results in:
> > ```
> > App\Http\Requests\Photo\AddPhotoRequest::processValidatedValues:39 Cannot assign string to property App\Http\Requests\Photo\AddPhotoRequest::$fileLastModifiedTime of type ?int
> > ```
> 
> Which web-browser are you using ? 🤔

Hey @ildyria! Thanks for the idea. I'm using Firefox, but I just tested with Chromium, and it produces the same outcome. I can try some further alternatives, though, if you think it might be browser-related!

**Comment by ildyria** [comment]
Could you inspect the request, and check the value sent in `fileLastModifiedTime` ?

**Comment by 01tot10** [comment]
> Could you inspect the request, and check the value sent in `fileLastModifiedTime` ?

I hope I'm doing this right (I'm not really a web developer), but inspecting the POST Request in Firefox console gives me:
```
-----------------------------352320885419670745681174683993
Content-Disposition: form-data; name="fileLastModifiedTime"

1692731990017
```

Does that make sense?

**Comment by ildyria** [comment]
@01tot10 could you try the `fix-type` branch from https://github.com/LycheeOrg/Lychee/pull/2024 if it solve your problem?

**Comment by ildyria** [comment]
@01tot10 Once you have your Lychee install up and running in subdirectory, feel free to update our documentation https://github.com/LycheeOrg/LycheeOrg.github.io :)

I think this would fit into: https://lycheeorg.github.io/docs/advanced-setups.html (probably a new section)

**Comment by 01tot10** [comment]
> @01tot10 could you try the `fix-type` branch from #2024 if it solve your problem?

Holy smokes, that seems to have done it, at least the photo uploaded like butter!

Thanks a lot for your time. I'll continue exploring and see if there is something else that is not quite right.

**Comment by 01tot10** [comment]
> @01tot10 Once you have your Lychee install up and running in subdirectory, feel free to update our documentation https://github.com/LycheeOrg/LycheeOrg.github.io :)
> 
> I think this would fit into: https://lycheeorg.github.io/docs/advanced-setups.html (probably a new section)

Thanks, and yes, that was my initial plan! I'll first confirm that everything is running as expected, and then add my install procedure for future reference.

**Comment by ildyria** [comment]
Done. Thanks! :)
