### ISSUE TITLE
[Enhancement] Album Delete Confirmation

### ISSUE THREAD

**Issue by Chagrilled** [LycheeOrg/Lychee#2011]
Now I'm definitely the idiot here for accidentally clicking the delete for my entire album rather than a photo within it when spamming to delete multiple, but being able to zoop away possible hundreds of photos without an undo operation feels like it should have an extra `ARE YOU REALLY SURE` confirmation modal for albums with contents 🤔

**Comment by ildyria** [comment]
I think this should make you happy (preview of v5)
![image](https://github.com/LycheeOrg/Lychee/assets/627094/6b05e4a4-c598-4120-aebd-3cc3021d59bd)

![image](https://github.com/LycheeOrg/Lychee/assets/627094/9b159b03-3d74-4cb7-8d86-d3a1e00d5fc7)

You will have to go into **Danger zone** -> then **Delete**.
At that point, I can't make it more stupid proof. :)
