### ISSUE TITLE
[Enhancement] Helmchart

### ISSUE THREAD

**Issue by breuerfelix** [LycheeOrg/Lychee#2021]
Hey guys,

I wrote a HelmChart for lychee (https://github.com/breuerfelix/lychee-helmchart) and just wanted to share this information.
Since i use it myself i will maintain it and also enhance this if some other people have other needs (since right now it might be generic but fits my needs of course).

I thought i mention it here so maybe we can make some link to the readme? Or do you have other plans / ideas on how to reach more people that search for a kubernetes deployment for lychee?
If not, you can just close this issue and thats fine :)

Cheers

**Comment by d7415** [comment]
Sounds like a good fit for https://lycheeorg.github.io/docs/advanced-setups.html#other-means-of-distributions

Would you like to open a PR to https://github.com/LycheeOrg/LycheeOrg.github.io?

**Comment by breuerfelix** [comment]
done: https://github.com/LycheeOrg/LycheeOrg.github.io/pull/104/files

**Comment by ildyria** [comment]
Thank you!
