### ISSUE TITLE
Project use libraries incompatible with Raspberry Pi 3 (32 bit systems)

### ISSUE THREAD

**Issue by RoiArthurB** [LycheeOrg/Lychee#2028]
### Detailed description of the problem [REQUIRED]
This project now uses the `zipstream-php` which doesn't have any compatible version with 32 bits systems (as Raspberry Pi 3).

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Install latest release
2. Run `composer install`
3. See error*

### Output of the diagnostics  [REQUIRED]
*(Settings => Diagnostics or https://example.com/Diagnostics or `php artisan lychee:diagnostics`)*

```
    Diagnostics
    -------
    Warning: Dropbox import not working. dropbox_key is empty.
    Info: Latest version of PHP is 8.2
    Warning: Using 32 bit PHP, recommended upgrade to 64 bit
```

```
$ composer install --no-dev --prefer-dist
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - maennchen/zipstream-php is locked to version 3.1.0 and an update of this package was not requested.
    - maennchen/zipstream-php 3.1.0 requires php-64bit ^8.1 -> the php-64bit package is disabled by your platform config. Enable it again with "composer config platform.php-64bit --unset".
```

**Comment by qwerty287** [comment]
I see the issue, however, RPI 3 is 64bit-compatible. You can try to "upgrade" this (i.e. reinstall with 64bit)
