### ISSUE TITLE
400 bad request response if protected by http basic auth

### ISSUE THREAD

**Issue by Phaengris** [LycheeOrg/Lychee#2042]
### Detailed description of the problem [REQUIRED]

When Lychee is behind an http basic auth, it always responds with the error 400 Bad Request Header Exception Invalid token.

### Steps to reproduce the issue

1. Install Lychee
2. Configure an http basic auth, e.g. place .htaccess into the Lychee public directory
3. Go to the Lychee page
4. Enter http auth credentials
5. See error 400 in the browser

### Output of the diagnostics  [REQUIRED]

Not relevant. Affects Lychee 4.13.0 at least.

### Browser and system

Not relevant.

### Possible reason

Similar issue is described here https://github.com/LycheeOrg/Lychee/issues/1767

with the link to the corresponding part of the code https://github.com/LycheeOrg/Lychee/blob/master/app/Services/Auth/SessionOrTokenGuard.php#L307C55-L307C55

When the "Authorization" header is provided, Lychee considers the whole content of it as a token.

While the "http basic" authorization header looks like that
```
Authorization: Basic <encoded>
```
The existence of any "Authorization" header causes Lychee to consider it as it's own authorization header, failing when it's not the case.

### Proposition

I didn't submit a PR because of there are many ways to workaround / solve this problem and I'm not sure what your preference could be :)

1. Parse the token, trying to determine the type of the authorization header.
2. Apply token-based authorization only to API requests, leaving browser requests out of scope.
3. Change the format of Lychee's authorization tokens, using format `Authorization: <scheme> <encoded>` as recommended
https://www.rfc-editor.org/rfc/rfc1945#section-11 so it'd look like `Authorization: Bearer <encoded>` \
https://security.stackexchange.com/questions/108662/why-is-bearer-required-before-the-token-in-authorization-header-in-a-http-re
4. Introduce Lychee-specific authorization http header, like X-Lychee-API-Token, which would be probably most safe solution which definitely wouldn't break common authorization schemes.

### Current workaround

Disable Lychee's token-based http authorization as proposed in https://github.com/LycheeOrg/Lychee/issues/1767#issuecomment-1452071900

**Comment by ildyria** [comment]
Hi sorry for the silence, was quite busy IRL.

**I am in favor of 3 or 4.**
Unfortunately I don't have the time to work on that but would certainly welcome a pull request.

2 is not a possibility because most API requests are actually done via the browser/AJAX once you pass the first GET.
