### ISSUE TITLE
 /var/www/html/Lychee/vendor does not exist and could not be created

### ISSUE THREAD

**Issue by fede1581** [LycheeOrg/Lychee#2048]
Detailed description of the problem [REQUIRED]
I'm unable to install Lychee.

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. In the step "Run composer install --no-dev to install dependencies" it gives me an error: " /var/www/html/Lychee/vendor does not exist and could not be created". 

### Output of the diagnostics  [REQUIRED]
composer install --no-dev 
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Package operations: 107 installs, 0 updates, 0 removals

In Filesystem.php line 270:
                                                                        
  /var/www/html/Lychee/vendor does not exist and could not be created.  

### Browser and system
Brave
Ubuntu 22.04

**Comment by d7415** [comment]
> /var/www/html/Lychee/vendor does not exist and could not be created.


Looks like a permissions issue. Make sure the user you're running is has write access to `/var/www/html/Lychee/`
