### ISSUE TITLE
Upload videos has different behavior on different browsers

### ISSUE THREAD

**Issue by huntson** [LycheeOrg/Lychee#2054]
### Detailed description of the problem [REQUIRED]
Cannot seem to upload videos properly.  Photos work without issue.  I have tried the usual clearing caches as well as different computers and browsers.

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Go to local instance of Lychee
2. Login to a user that has write privileges
3. Upload a video
4. See error of video not uploading at all in Chrome & Safair and uploading to 100% and then erroring out in Firefox

**Screenshots**
![Screenshot 2023-11-13 at 12 16 58 PM](https://github.com/LycheeOrg/Lychee/assets/38994011/8cadbb84-f1d3-41eb-89e1-2c6d0c87cc2a)

### Output of the diagnostics  [REQUIRED]

    Diagnostics
    -------
    Warning: /var/www/html/Lychee/public/uploads/ has permissions 2777, but should have 2775
    Warning: /var/www/html/Lychee/public/uploads/import has permissions 2777, but should have 2775
    Warning: /var/www/html/Lychee/public/uploads/medium has permissions 2777, but should have 2775
    Warning: /var/www/html/Lychee/public/uploads/medium/00 has permissions 2777, but should have 2775
    Warning: /var/www/html/Lychee/public/uploads/medium/00/03 has permissions 2777, but should have 2775
    Warning: 4925 more directories with wrong permissions
    Warning: Dropbox import not working. dropbox_key is empty.
    Error: APP_URL does not match the current url. This will break WebAuthn authentication. Please update APP_URL to reflect this change.
    Warning: git (software) is not available.
    Foreign key: access_permissions.user_id     → users.id             : CASCADE
    Foreign key: albums.parent_id               → albums.id            : RESTRICT
    Foreign key: albums.id                      → base_albums.id       : RESTRICT
    Foreign key: albums.cover_id                → photos.id            : CASCADE
    Foreign key: base_albums.owner_id           → users.id             : RESTRICT
    Foreign key: jobs_history.owner_id          → users.id             : RESTRICT
    Foreign key: photos.album_id                → albums.id            : RESTRICT
    Foreign key: photos.owner_id                → users.id             : RESTRICT
    Foreign key: size_variants.photo_id         → photos.id            : RESTRICT
    Foreign key: sym_links.size_variant_id      → size_variants.id     : RESTRICT
    Foreign key: tag_albums.id                  → base_albums.id       : RESTRICT

    System Information
    --------------
    Lychee Version (git):                    ?? (a87d2e2) -- Could not compare.
    DB Version:                              4.13.0
    
    composer install:                        --no-dev
    APP_ENV:                                 production
    APP_DEBUG:                               false
    
    System:                                  Linux
    PHP Version:                             8.2.7
    PHP User agent:                          Lychee/4 (https://lycheeorg.github.io/)
    Timezone:                                America/New_York
    Max uploaded file size:                  100M
    Max post size:                           100M
    Max execution time:                      3600
    MySQL Version:                           11.1.2-MariaDB-1:11.1.2+maria~ubu2204
    
    exec() Available:                        yes
    Imagick Available:                       1
    Imagick Enabled:                         1
    Imagick Version:                         1691
    GD Version:                              2.3.3
    Number of foreign key:                   11 found.

    Config Information
    --------------
    version:                                 041300
    check_for_updates:                       0
    sorting_photos_col:                      taken_at
    sorting_photos_order:                    ASC
    sorting_albums_col:                      max_taken_at
    sorting_albums_order:                    ASC
    imagick:                                 1
    skip_duplicates:                         0
    small_max_width:                         0
    small_max_height:                        360
    medium_max_width:                        1920
    medium_max_height:                       1080
    lang:                                    en
    image_overlay_type:                      desc
    default_license:                         none
    compression_quality:                     90
    grants_full_photo_access:                1
    delete_imported:                         0
    mod_frame_enabled:                       1
    mod_frame_refresh:                       30
    thumb_2x:                                1
    small_2x:                                1
    medium_2x:                               1
    landing_page_enable:                     0
    site_owner:                              John Smith
    landing_title:                           John Smith
    landing_subtitle:                        Cats, Dogs & Humans Photography
    sm_facebook_url:                         https://www.facebook.com/JohnSmith
    sm_flickr_url:                           https://www.flickr.com/JohnSmith
    sm_twitter_url:                          https://www.twitter.com/JohnSmith
    sm_instagram_url:                        https://instagram.com/JohnSmith
    sm_youtube_url:                          https://www.youtube.com/JohnSmith
    landing_background:                      dist/cat.webp
    site_title:                              Lychee v4
    footer_show_copyright:                   0
    site_copyright_begin:                    2019
    site_copyright_end:                      2019
    footer_additional_text:                  
    footer_show_social_media:                0
    public_search:                           0
    SL_enable:                               0
    SL_for_admin:                            0
    recent_age:                              1
    grants_download:                         0
    photos_wraparound:                       1
    map_display:                             0
    zip64:                                   1
    map_display_public:                      0
    map_provider:                            Wikimedia
    force_32bit_ids:                         0
    map_include_subalbums:                   0
    update_check_every_days:                 3
    has_exiftool:                            1
    share_button_visible:                    0
    import_via_symlink:                      0
    has_ffmpeg:                              1
    location_decoding:                       0
    location_decoding_timeout:               30
    location_show:                           1
    location_show_public:                    0
    rss_enable:                              0
    rss_recent_days:                         7
    rss_max_items:                           100
    prefer_available_xmp_metadata:           0
    editor_enabled:                          1
    lossless_optimization:                   0
    swipe_tolerance_x:                       150
    swipe_tolerance_y:                       250
    local_takestamp_video_formats:           .avi|.mov
    log_max_num_line:                        1000
    unlock_password_photos_with_url_param:   0
    nsfw_visible:                            1
    nsfw_blur:                               0
    nsfw_warning:                            0
    nsfw_warning_admin:                      0
    nsfw_banner_override:                    
    map_display_direction:                   1
    album_subtitle_type:                     oldstyle
    upload_processing_limit:                 4
    public_photos_hidden:                    1
    new_photos_notification:                 0
    legacy_id_redirection:                   1
    zip_deflate_level:                       6
    SA_enabled:                              1
    default_album_protection:                1
    album_decoration:                        layers
    album_decoration_orientation:            row
    allow_username_change:                   1
    auto_fix_orientation:                    1
    use_job_queues:                          0
    random_album_id:                         starred
    use_last_modified_date_when_no_exif_date: 0
    ffmpeg_path:                             /usr/bin/ffmpeg
    ffprobe_path:                            /usr/bin/ffprobe
    layout:                                  justified
### Browser and system
Sonoma Mac running Firefox, Chrome, and Safari

**Comment by ildyria** [comment]
Have you checked the logs ?
There should be info of why there is a crash there.

**Comment by huntson** [comment]
I have looked at the logs in docker and nothing is really standing out.  Is there a certain verbosity that needs to be enabled?

**Comment by ildyria** [comment]
In theory no, you may want to have a look at the nginx logs and `storage/logs/laravel.log` (If I am not wrong). That crash is very weird. :(

**Comment by huntson** [comment]
Nothing is in laravel.log

**Comment by ildyria** [comment]
@huntson Sorry to ask you that, but would it be possible for you to send that broken video to my mail address so that I can investigate more what is going on?
