### ISSUE TITLE
reset admin password without ssh

### ISSUE THREAD

**Issue by tasiotas** [LycheeOrg/Lychee#2059]
Hi,

I installed Lychee via FTP. How can I reset admin password without ssh access ?

Thank you

**Comment by ildyria** [comment]
**You can't. You need to write a small script that you upload yourself and execute it.**
As this is extremely unsafe, such thing will never be implemented in Lychee.

You can try this script in `reset_admin.php` which you place in `<path_to_lychee>/public/reset_admin.php` and then access it from your web. Do be sure to delete the script once done. I have no clue if it works but it is worth a try.

```php
<?php

exec("cd ..; php artisan lychee:reset_admin", $output, $retval);
echo "Returned with status $retval and output:\n";
print_r($output);
```

**Comment by tasiotas** [comment]
yey, it worked!

Just had to use `create_user --may-administrate` instead of `reset_admin`

Thank you

**Comment by tasiotas** [comment]
this doesnt work on v5 anymore

returns:
```
Returned with status 255 and output: Array ( )
```

I don't see any changes to `create_user`, any ideas?

**Comment by ildyria** [comment]
Have you tried `lychee:update_user <username> <password>` (without the `<` and `>` obviously) ?
