### ISSUE TITLE
Custom js give error when i try to add matomo code

### ISSUE THREAD

**Issue by bussekas** [LycheeOrg/Lychee#2061]
Hi

I find on Lychee Documentation to add Matomo tracking code into Lychee.
https://lycheeorg.github.io/docs/external_tracking.html

i add into config file correct address values:
SECURITY_HEADER_SCRIPT_SRC_ALLOW=https://analytics.example.com/matomo.js
SECURITY_HEADER_CSP_CONNECT_SRC=https://analytics.example.com/matomo.js

var _paq = window._paq = window._paq || [];
_paq.push(['trackPageView']);
_paq.push(['enableLinkTracking']);
(function () {
    var u = "https://analytics.example.com/";
    _paq.push(['setTrackerUrl', u + 'matomo.php']);
    _paq.push(['setSiteId', '<site-id>']);
    var d = document, g = d.createElement('script'), s = d.getElementsByTagName('script')[0];
    g.async = true;
    g.src = u + 'matomo.js';
    s.parentNode.insertBefore(g, s);
})();

navigation.addEventListener("navigate", function (e) {
    _paq.push(['setDocumentTitle', document.title]);
    _paq.push(['trackPageView']);
});

then add with correct changed values matomo and ID and when i try to save, i get error.

what i did wrong?

i have fresh 4.13.0 version

**Comment by ildyria** [comment]
Hi sorry for the late reply.

> i get error.

What do you mean by that ? Is it a Lychee error ? Is it a JS error ? Is it a console log error ?

**Comment by bussekas** [comment]
When i add into custom js code. i take sample for showing problem from matomo (https://lycheeorg.github.io/docs/external_tracking.html)

then i get error into website.
![error](https://github.com/LycheeOrg/Lychee/assets/28824069/db7d57c2-02ad-45f2-90bf-8c8b6c174364)

**Comment by ildyria** [comment]
can you open `https://<link to your website>/dist/custom.js` and see if there is content in it?

**Comment by bussekas** [comment]
![white page](https://github.com/LycheeOrg/Lychee/assets/28824069/e354537e-00ed-4264-9511-69a3db63c85c)
i can see only white page when i add this link but site logged in behind this link.

**Comment by ildyria** [comment]
I assume you have an ftp or ssh access can you check the content of `<path-to-lychee>/public/dist/custom.js` ? 
Seems like a write access problem to me.

**Comment by bussekas** [comment]
Hi
i fix solution that i take this custom.js and add info by notepad++. 777 for testing was not helping.
