### ISSUE TITLE
[Enhancement] Fix the settings dialogs to be horizontal just like most people have their monitors

### ISSUE THREAD

**Issue by tlhintoq** [LycheeOrg/Lychee#2065]
*Explain in a few words which functionality or improvements you would like to see in Lychee.*

Having vertical (portrait orientation) dialogs when the vast majority of monitors are horizontal (landscape orientation) is user UNfriendly.
Constantly having to scroll a narrow dialog on a wide monitor is annoying, over and over and over and over.
![image](https://github.com/LycheeOrg/Lychee/assets/11351506/22245f9c-9845-436f-aa12-9451dadf3174)

**Comment by ildyria** [comment]
Off topic.

**Comment by tlhintoq** [comment]
@ildyria 

How is an enhancement "off topic"?  Should it have been tagged differently?  I didn't mark it as a bug.  Its an enhancement.  An improvement to the user experience.

**Comment by ildyria** [comment]
Maybe because it does not concern Lychee but Lychee Slicer Pro?

**Comment by tlhintoq** [comment]
I:m an idiot.  Sorry about that
