### ISSUE TITLE
Album allow public upload but disallow deletion

### ISSUE THREAD

**Issue by ethaniel86** [LycheeOrg/Lychee#2068]
As per title, i can't seems to configure this. 
My goal is to create an public album allow anyone/anonymous to upload photos but disallow delete permission.

**Comment by ildyria** [comment]
1. Access Rights management is not available yet (but soonTM)
2. It will be:
    > My goal is to create an public album allow ~~anyone/anonymous~~ **logged-in users** to upload photos but disallow delete permission.

Allowing anyone/anonymous to upload is too much of a security risk, we are not allowing that directly from the UI.
However if you want to shoot yourself in the foot, it is be possible by changing one flag in the database:
https://github.com/LycheeOrg/Lychee/blob/master/app/Policies/AlbumPolicy.php#L161
```php
	public function canUpload(User $user, ?AbstractAlbum $abstractAlbum = null): bool
	{
		// The upload right on the root album is directly determined by the user's capabilities.
		if ($abstractAlbum === null || !$abstractAlbum instanceof BaseAlbum) {
			return $user->may_upload;
		}

		return $this->isOwner($user, $abstractAlbum) ||
			$abstractAlbum->current_user_permissions()?->grants_upload === true ||
			$abstractAlbum->public_permissions()?->grants_upload === true;
	}

```
You just need to find the line in the `access_permissions` table with the `user_id = null` and `album = <albumID>` and set  `grants_upload` to `1`.
^ that part you can probably already do.
