### ISSUE TITLE
Can I directly upload a directory and automatically create a new photo album?

### ISSUE THREAD

**Issue by JoviLau** [LycheeOrg/Lychee#2070]
1、Can I directly upload a catalog and automatically create a new album?
2、Can the default visible value of the album be set in the background or modified with one click?

**Comment by ildyria** [comment]
1. You need to use the console import function.
2. there is a `default_album_protection` setting you may want to use.
Default protection for newly created albums. 1 = private, 2 = public, 3 = inherit from parent

**Comment by JoviLau** [comment]
> 1. 您需要使用控制台导入功能。
> 2. 您可能需要使用`default_album_protection`设置。
>    新创建的相册的默认保护。 1 = 私有，2 = 公共，3 = 从父级继承
