### ISSUE TITLE
Database installation

### ISSUE THREAD

**Issue by jessease** [LycheeOrg/Lychee#2074]
Hi I am not able to create the database. I get a popup that says "unable to create the database, double check your host, username, and password and ensure the specified user has the rights to modify and add content to the database" I have specified the correct use with all granted permissions and it will not install. Thanks for any tips :)

**Comment by ildyria** [comment]
"unable to create the database" This errors tells me that you are not using the [latest](https://github.com/LycheeOrg/Lychee/releases/tag/v4.13.0) version of Lychee.
**This error message does not even exists in our code base.**

Please read the docs: https://lycheeorg.github.io/docs/

The database installation is run by doing `php artisan migrate`.
