### ISSUE TITLE
update to 5.0, Login does not work

### ISSUE THREAD

**Issue by haivala** [LycheeOrg/Lychee#2087]
### Detailed description of the problem [REQUIRED]
`Too few arguments to function App\Policies\AlbumPolicy::canEdit(), 1 passed in /var/www/html/lychee/vendor/laravel/framework/src/Illuminate/Auth/Access/Gate.php on line 811 and exactly 2 expected`
Getting this error after login.
Without login everything works.

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Login
2. get this error

### Output of the diagnostics  [REQUIRED]
*(Settings => Diagnostics or https://example.com/Diagnostics or `php artisan lychee:diagnostics`)*
Warning: 1562 more directories with wrong owner
Warning: 1562 more directories with wrong permissions
Warning: Dropbox import not working. dropbox_key is empty.
Error: mysql db driver selected and PHP mysqli extension not activated
Info: Latest version of PHP is 8.3
Warning: Online updates are disabled by configuration

System Information
------------------
Lychee Version (git):                    master (f3be74f) -- Up to date (unknown).
DB Version:                              5.0.0

composer install:                        --no-dev
APP_ENV:                                 production
APP_DEBUG:                               false

System:                                  Linux
PHP Version:                             8.2.13
PHP User agent:                          Lychee/4 (https://lycheeorg.github.io/)
Timezone:                                Europe/Helsinki
Max uploaded file size:                  500M
Max post size:                           300M
Livewire chunk size:                     12.00 MB
Max execution time:                      0
MySQL Version:                           10.11.6-MariaDB-1:10.11.6+maria~ubu2204

exec() Available:                        yes
Imagick Available:                       1
Imagick Enabled:                         1
Imagick Version:                         1809
GD Version:                              bundled (2.1.0 compatible)
Number of foreign key:                   11 found.
### Browser and system
FF 121

**Comment by ildyria** [comment]
Hummm very weird, as I don't have this on my side.

Are you login with a normal user or Admin ?

I will try to fix this ASAP but that may need to wait Wednesday...

**Comment by ildyria** [comment]
BTW you will be happy to know that I started working on the Oauth client.

Can you set the DEBUG mode on and provide me with the exception trace so I can localize this Gate error

**Comment by haivala** [comment]
> Hummm very weird, as I don't have this on my side.
> 
> Are you login with a normal user or Admin ?
> 
> I will try to fix this ASAP but that may need to wait Wednesday...

normal user

**Comment by haivala** [comment]
in[ /var/www/html/lychee/app/Policies/AlbumPolicy.php ](file:///var/www/html/lychee/app/Policies/AlbumPolicy.php#L222)(line 222)

         * @param User               $user
         * @param AbstractAlbum|null $album the album; `null` designates the root album
         *
         * @return bool
         */
        public function canEdit(User $user, AbstractAlbum|null $album): bool
        {
            // The root album and smart albums get a pass
            if ($album === null || $album instanceof BaseSmartAlbum) {
                return $user->may_upload;
            }

in[ /var/www/html/lychee/vendor/laravel/framework/src/Illuminate/Auth/Access/Gate.php ](file:///var/www/html/lychee/vendor/laravel/framework/src/Illuminate/Auth/Access/Gate.php#L811)-> canEdit (line 811)

            if (! is_callable([$policy, $method])) {
                return;
            }
            if ($this->canBeCalledWithUser($user, $policy, $method)) {
                return $policy->{$method}($user, ...$arguments);
            }
        }

**Comment by haivala** [comment]
With admin user it works

**Comment by haivala** [comment]
```
Error	18:10:53	production	App\Actions\HoneyPot\BasePipe::throwNotFound:40 The route uploads/thumb could not be found.
Error	18:07:54	production	App\Policies\AlbumPolicy::canEdit:222 Too few arguments to function App\Policies\AlbumPolicy::canEdit(), 1 passed in /var/www/html/lychee/vendor/laravel/framework/src/Illuminate/Auth/Access/Gate.php on line 811 and exactly 2 expected
Error	18:06:31	production	App\Policies\AlbumPolicy::canEdit:222 Too few arguments to function App\Policies\AlbumPolicy::canEdit(), 1 passed in /var/www/html/lychee/vendor/laravel/framework/src/Illuminate/Auth/Access/Gate.php on line 811 and exactly 2 expected
Notice	18:06:31	production	App\Livewire\Components\Modals\Login::submit:84 User 
```

**Comment by ildyria** [comment]
Found it, fix is on its way.
