### ISSUE TITLE
Cover of sensitive albums not blurred

### ISSUE THREAD

**Issue by mashb1t** [LycheeOrg/Lychee#2088]
### Detailed description of the problem
A sensitive album cover isn't blurred in the preview, despite nsfw_blur being set to 1.

### Steps to reproduce the issue
**Steps to reproduce the behaviour:**
1. Create Album
2. Make Album sensitive
3. Go to main page / album where the album is located at
4. See cover not blurred

https://github.com/LycheeOrg/Lychee/blob/master/app/View/Components/Gallery/Album/Thumbs/Album.php#L68

### Output of the diagnostics
Config Information
    ------------------
        version:                                 050000
        check_for_updates:                       0
        sorting_photos_col:                      created_at
        sorting_photos_order:                    DESC
        sorting_albums_col:                      max_taken_at
        sorting_albums_order:                    DESC
        imagick:                                 1
        skip_duplicates:                         0
        small_max_width:                         0
        small_max_height:                        360
        medium_max_width:                        1920
        medium_max_height:                       1080
        lang:                                    en
        image_overlay_type:                      desc
        default_license:                         CC-BY-NC-ND-4.0
        compression_quality:                     90
        grants_full_photo_access:                1
        delete_imported:                         0
        mod_frame_enabled:                       1
        mod_frame_refresh:                       30
        thumb_2x:                                1
        small_2x:                                1
        medium_2x:                               1
        landing_page_enable:                     0
        site_owner:                              <removed>
        landing_title:                           <removed>
        landing_subtitle:                        <removed>
        sm_facebook_url:                         
        sm_flickr_url:                           
        sm_twitter_url:                          
        sm_instagram_url:                        
        sm_youtube_url:                          
        landing_background:                      dist/cat.webp
        site_title:                              <removed>
        footer_show_copyright:                   1
        site_copyright_begin:                    2023
        site_copyright_end:                      2023
        footer_additional_text:                  
        footer_show_social_media:                1
        search_public:                           1
        SL_enable:                               0
        SL_for_admin:                            0
        recent_age:                              1
        grants_download:                         0
        photos_wraparound:                       1
        map_display:                             0
        zip64:                                   1
        map_display_public:                      0
        map_provider:                            Wikimedia
        force_32bit_ids:                         0
        map_include_subalbums:                   0
        update_check_every_days:                 3
        has_exiftool:                            1
        share_button_visible:                    0
        import_via_symlink:                      0
        has_ffmpeg:                              1
        location_decoding:                       0
        location_decoding_timeout:               30
        location_show:                           1
        location_show_public:                    0
        rss_enable:                              0
        rss_recent_days:                         7
        rss_max_items:                           100
        prefer_available_xmp_metadata:           0
        editor_enabled:                          1
        lossless_optimization:                   0
        swipe_tolerance_x:                       150
        swipe_tolerance_y:                       250
        local_takestamp_video_formats:           .avi|.mov
        log_max_num_line:                        1000
        unlock_password_photos_with_url_param:   0
        nsfw_visible:                            1
        nsfw_blur:                               1
        nsfw_warning:                            1
        nsfw_warning_admin:                      1
        nsfw_banner_override:                    
        map_display_direction:                   1
        album_subtitle_type:                     oldstyle
        upload_processing_limit:                 4
        new_photos_notification:                 0
        legacy_id_redirection:                   1
        zip_deflate_level:                       6
        SA_enabled:                              1
        default_album_protection:                3
        album_decoration:                        all
        album_decoration_orientation:            row
        allow_username_change:                   1
        auto_fix_orientation:                    1
        use_job_queues:                          0
        random_album_id:                         starred
        use_last_modified_date_when_no_exif_date: 0
        ffmpeg_path:                             /usr/bin/ffmpeg
        ffprobe_path:                            /usr/bin/ffprobe
        layout:                                  justified
        date_format_photo_thumb:                 M j, Y, g:i:s A e
        date_format_photo_overlay:               M j, Y, g:i:s A e
        date_format_sidebar_uploaded:            M j, Y, g:i:s A e
        date_format_sidebar_taken_at:            M j, Y, g:i:s A e
        date_format_hero_min_max:                F Y
        date_format_hero_created_at:             M j, Y, g:i:s A T
        date_format_album_thumb:                 M Y
        upload_chunk_size:                       0
        nsfw_banner_blur_backdrop:               1
        search_pagination_limit:                 1000
        search_minimum_length_required:          4
        photo_layout_justified_row_height:       320
        photo_layout_masonry_column_width:       300
        photo_layout_grid_column_width:          250
        photo_layout_square_column_width:        200
        photo_layout_gap:                        12
        display_thumb_album_overlay:             always
        display_thumb_photo_overlay:             hover

### Browser and system
Chrome Version 120.0.6099.129 (Official Build) (arm64)
Linux 5.10.0-26-amd64 #1 SMP Debian 5.10.197-1 (2023-09-29) x86_64 GNU/Linux with Docker

**Comment by ildyria** [comment]
tailwindcss is being a bit too aggressive and removed the blurred property...

**Comment by ildyria** [comment]
Fix is on its way.

**Comment by mashb1t** [comment]
thank you for the prompt response & fix, much appreciate it

**Comment by ildyria** [comment]
In the mean time you can add the following to your `user.css` (in your settings)

```css

	.blurred span {
		overflow: hidden;
	}

	.blurred img {
		/* Safari 6.0 - 9.0 */
		-webkit-filter: blur(5px);
		filter: blur(5px);
	}
```

It will provide the same effect.
