### ISSUE TITLE
Volume estimation appears to be off

### ISSUE THREAD

**Issue by raharth** [LycheeOrg/Lychee#2099]
### Detailed description of the problem [REQUIRED]
Today I ran a file that was estimated to use about 180ml of resin. My VAT holds about 240ml of resin, but I still ran out of resin resulting in a failed print. It appreas as if lychee is undererstimating the volume by about 30%, which is quite significant.

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
Run the file through the printer. I'm happy to provide the file to a personal account, but I don't want to upload it publically since it is a paid file.

**Comment by d7415** [comment]
Not this software.
