### ISSUE TITLE
Lychee 5.0.0 || Installation issue

### ISSUE THREAD

**Issue by pinalgirkar** [LycheeOrg/Lychee#2100]
### Detailed description of the problem [REQUIRED]
I installed this [lychee package](https://github.com/LycheeOrg/Lychee/releases/download/v5.0.0/Lychee.zip) and installed in a CentOS 7 server with the following configuration: Apache 2.4, PHP 8.2, and MySQL 5.7. However after successful installation when I visit the admin URL [[protocol]]://[[domain_name]]/[[directory_name]]/public/gallery.

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Go to '[[protocol]]://[[domain_name]]/[[directory_name]]/public'
2. And then follow the installation wizard until the end
3. Then visit the url given in the button open lychee
4.  The below page loads, but unable to access anything 
5. See error

**Screenshots**
![image](https://github.com/LycheeOrg/Lychee/assets/106646072/84a4b98d-8b01-4e02-9c38-3d7d01198028)
![image](https://github.com/LycheeOrg/Lychee/assets/106646072/ab8e0895-8e97-4ef2-a8a4-178a3dff65af)

### Browser and system
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

###Query
Is there any package available which can be used without node and npm ? As mentioned in the readme.md file Installation section.

### Note
I have attached a log files which are generated at [[path_to_install_directory]]/storage/logs
[daily-2023-12-26.log](https://github.com/LycheeOrg/Lychee/files/13770324/daily-2023-12-26.log)
[errors.log](https://github.com/LycheeOrg/Lychee/files/13770302/errors.log)
[notice-2023-12-26.log](https://github.com/LycheeOrg/Lychee/files/13770303/notice-2023-12-26.log)

**Comment by ildyria** [comment]
If you click on frame that is normal.
Just a minor bug I need to fix (to make the button disappear when access are not given to public on the starred album).

You should be able to login with the top left button.

> Is there any package available which can be used without node and npm ? As mentioned in the readme.md file Installation section.

That step is only required to build the front-end, after that they can be removed.
**Alternatively if you use the zip archive you need neither composer nor npm & node.**
