### ISSUE TITLE
v5 - Selected image not shown after upgrading to 5.0

### ISSUE THREAD

**Issue by oblomow** [LycheeOrg/Lychee#2102]
### Detailed description of the problem 
After upgrading to 5.0 I can upload new images. The album and thumbnail are shown, but when I click on an image the screen turns black. No image. Further testing reveals that this also the case with existing albums.

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. go to an album
2. click on an image
3. see black screen

**Screenshots**
I see these messages in the error.log

<img width="1014" alt="image" src="https://github.com/LycheeOrg/Lychee/assets/427760/723620d8-ae71-49e2-84b3-452ba42ad0c1">

￼
### Output of the diagnostics  [REQUIRED]
*(Settings => Diagnostics or https://example.com/Diagnostics or `php artisan lychee:diagnostics`)*
Diagnostics
-----------
Info: Latest version of PHP is 8.3

System Information
------------------
Lychee Version (git):                    master (97b5e96) -- Up to date (3 minutes ago).
DB Version:                              5.0.0

composer install:                        --no-dev
APP_ENV:                                 local
APP_DEBUG:                               false

System:                                  FreeBSD
PHP Version:                             8.2.13
PHP User agent:                          Lychee/4 (https://lycheeorg.github.io/)
Timezone:                                Europe/Amsterdam
Max uploaded file size:                  100M
Max post size:                           100M
Livewire chunk size:                     12.00 MB
Max execution time:                      0
MySQL Version:                           8.0.35

exec() Available:                        yes
Imagick Available:                       1
Imagick Enabled:                         1
Imagick Version:                         1808
GD Version:                              2.3.3
Number of foreign key:                   13 found.

Config Information
------------------
version:                                 050000
check_for_updates:                       1
sorting_photos_col:                      taken_at
sorting_photos_order:                    ASC
sorting_albums_col:                      title
sorting_albums_order:                    DESC
imagick:                                 1
skip_duplicates:                         0
small_max_width:                         0
small_max_height:                        360
medium_max_width:                        1920
medium_max_height:                       1080
lang:                                    en
image_overlay_type:                      date
default_license:                         CC-BY-NC-ND-4.0
compression_quality:                     90
grants_full_photo_access:                1
delete_imported:                         0
mod_frame_enabled:                       1
mod_frame_refresh:                       30
thumb_2x:                                1
small_2x:                                1
medium_2x:                               1
landing_page_enable:                     1
site_owner:                             
landing_title:                          
landing_subtitle:                        Why stop now?
sm_facebook_url:                         
sm_flickr_url:                           
sm_twitter_url:                          
sm_instagram_url:                        
sm_youtube_url:                          
landing_background:                      dist/finland.jpg
site_title:                              fotos
footer_show_copyright:                   1
site_copyright_begin:                    1984
site_copyright_end:                      2023
footer_additional_text:                  
footer_show_social_media:                0
search_public:                           0
SL_enable:                               0
SL_for_admin:                            0
recent_age:                              1
grants_download:                         1
photos_wraparound:                       1
map_display:                             0
zip64:                                   1
map_display_public:                      0
map_provider:                            OpenStreetMap.org
force_32bit_ids:                         0
map_include_subalbums:                   0
update_check_every_days:                 3
has_exiftool:                            1
share_button_visible:                    1
import_via_symlink:                      0
has_ffmpeg:                              0
location_decoding:                       0
location_decoding_timeout:               30
location_show:                           0
location_show_public:                    0
rss_enable:                              0
rss_recent_days:                         7
rss_max_items:                           100
prefer_available_xmp_metadata:           0
editor_enabled:                          1
lossless_optimization:                   0
swipe_tolerance_x:                       150
swipe_tolerance_y:                       250
local_takestamp_video_formats:           .avi|.mov
log_max_num_line:                        1000
unlock_password_photos_with_url_param:   0
nsfw_visible:                            1
nsfw_blur:                               0
nsfw_warning:                            0
nsfw_warning_admin:                      0
nsfw_banner_override:                    
map_display_direction:                   1
album_subtitle_type:                     oldstyle
upload_processing_limit:                 4
new_photos_notification:                 0
legacy_id_redirection:                   1
zip_deflate_level:                       6
SA_enabled:                              1
default_album_protection:                1
allow_username_change:                   1
album_decoration:                        layers
album_decoration_orientation:            row
auto_fix_orientation:                    1
use_job_queues:                          0
random_album_id:                         starred
use_last_modified_date_when_no_exif_date: 0
ffmpeg_path:                             
ffprobe_path:                            
layout:                                  justified
date_format_photo_thumb:                 M j, Y, g:i:s A e
date_format_photo_overlay:               M j, Y, g:i:s A e
date_format_sidebar_uploaded:            M j, Y, g:i:s A e
date_format_sidebar_taken_at:            M j, Y, g:i:s A e
date_format_hero_min_max:                F Y
date_format_hero_created_at:             M j, Y, g:i:s A T
date_format_album_thumb:                 M Y
upload_chunk_size:                       0
nsfw_banner_blur_backdrop:               0
search_pagination_limit:                 1000
search_minimum_length_required:          4
photo_layout_justified_row_height:       320
photo_layout_masonry_column_width:       300
photo_layout_grid_column_width:          250
photo_layout_square_column_width:        200
photo_layout_gap:                        12
display_thumb_album_overlay:             always
display_thumb_photo_overlay:             hover

### Browser and system
viewing on:
Firefox 121.0
Macbook 14.2.1

**Comment by ildyria** [comment]
You need to set up your `APP_URL` in your `.env` and it will be working fine.

I will try to come up with a work around but not guaranteed.

**Comment by ildyria** [comment]
To me it looks like the URL is not properly applied.
Are you having some specific settings for `LYCHEE_UPLOADS_URL` ?
If you have the line followed by blank, just remove it from your `.env`
Because that is the only explanation I have in your case.

**Comment by oblomow** [comment]
> You need to set up your `APP_URL` in your `.env` and it will be working fine.
> 
> I will try to come up with a work around but not guaranteed.

APP_URL is set. 

I will try what removing LYCHEE_UPLOADS_URL will do.

**Comment by ildyria** [comment]
I just tested locally, I believe `LYCHEE_UPLOADS_URL` is the culprit in your case. I am preparing a PR to have more details in the diagnostics :)

**Comment by oblomow** [comment]
> I just tested locally, I believe `LYCHEE_UPLOADS_URL` is the culprit in your case. I am preparing a PR to have more details in the diagnostics :)

Commeniting 'LYCHEE_UPLOADS_URL'  did the trick. Thanks!
( have told you that I like the new look-n-feel of v5?  I like it.)

Now I have to figure out how to share individual files using a link in this new versio, and then I'm all set to enter 2024.

**Comment by ildyria** [comment]
Sharing individual pictures is no longer supported, you will pretty much need to copy the link of the image (via right click -> copy URL...) .
We removed it as it was a PITA to managed.
On the other hand we significantly improved the UI for sharing albums with already existing users.
