### ISSUE TITLE
Post-5.0.0: Upgrade instructions (and possibly post-merge hook) missing npm commands

### ISSUE THREAD

**Issue by TwizzyDizzy** [LycheeOrg/Lychee#2104]
### Detailed description of the problem [REQUIRED]
The documentation on updating [using git](https://lycheeorg.github.io/docs/update.html#update-using-git) Lychee has not been updated to reflect changes to version 5.0.0. It seems though, installation instructions already reflect the use of npm: https://lycheeorg.github.io/docs/#installing-lychee

It seems what is missing from the update instructions is an `npm install` and and `npm run build` in order to `vite build` and generate the assets.

And if I'm not mistaken, this is also missing in the post-merge hook in the `./scripts/post-merge` hook.

If you need any additional information (and also if you want a PR for the documentation), please let me know.

Cheers
Thomas

### Steps to reproduce the issue
-

**Screenshots**
-

### Output of the diagnostics  [REQUIRED]
Without this step in the update procedure, the following error will appear in `/path/to/lychee/storage/logs/errors.log` (reflected as a status code 500 error when accessing Lychee): 

```
[2023-12-26 14:39:56] local.ERROR: Illuminate\Foundation\Vite::manifest:708 Vite manifest not found at: /path/to/lychee/public/build/manifest.json
App\Http\Middleware\MigrationStatus::handle:55 Vite manifest not found at: /path/to/lychee/public/build/manifest.json; caused by
Livewire\Mechanisms\ExtendBlade\ExtendedCompilerEngine::handleViewException:708 Vite manifest not found at: /path/to/lychee/public/build/manifest.json (View: /path/to/lychee/resources/views/components/layouts/app.blade.php); caused by
App\Http\Middleware\MigrationStatus::handle:55 Vite manifest not found at: /path/to/lychee/public/build/manifest.json (View: /path/to/lychee/resources/views/components/layouts/app.blade.php); caused by
Livewire\Mechanisms\ExtendBlade\ExtendedCompilerEngine::handleViewException:708 Vite manifest not found at: /path/to/lychee/public/build/manifest.json (View: /path/to/lychee/resources/views/components/layouts/app.blade.php) (View: /path/to/lychee/resources/views/components/layouts/app.blade.php); caused by
App\Http\Middleware\MigrationStatus::handle:55 Vite manifest not found at: /path/to/lychee/public/build/manifest.json (View: /path/to/lychee/resources/views/components/layouts/app.blade.php) (View: /path/to/lychee/resources/views/components/layouts/app.blade.php); caused by
```

### Browser and system
-

**Comment by ildyria** [comment]
Thank you! Good spot.

I added it to the release : https://github.com/LycheeOrg/Lychee/releases/tag/v5.0.0 But forgot about the upgrade page.

**Comment by ildyria** [comment]
I like the idea of the post-merge hook :)

**Comment by ildyria** [comment]
If you could take care of the PR in https://github.com/LycheeOrg/LycheeOrg.github.io that would be helpful as I am quite handful with all the other bugs popping up. :sob:

**Comment by TwizzyDizzy** [comment]
So, here are two PRs:
* for documentation: https://github.com/LycheeOrg/LycheeOrg.github.io/pull/108
* for the post-merge script: https://github.com/LycheeOrg/Lychee/pull/2109

Cheers
Thomas

**Comment by ildyria** [comment]
Fixed. :)
