### ISSUE TITLE
css and js assets not loaded after upgrade to v5 using docker

### ISSUE THREAD

**Issue by ynsta** [LycheeOrg/Lychee#2106]
### Detailed description of the problem

Hello,

Since I restarted my docker with v5 version the assets does not load, the app try to load them with http scheme instead of https. So CSP prevents loading of assets.

The APP_URL starts with https:// and I also tried to set APP_FORCE_HTTPS=true without success.

Here is an example of message from chrome console

Refused to load the stylesheet 'http://REMOVED.ORG/dist/user.css' because it violates the following Content Security Policy directive: "style-src 'self' 'unsafe-inline'". Note that 'style-src-elem' was not explicitly set, so 'style-src' is used as a fallback.

Same error with firefox.

My reverse proxy is traefik it used to work in v4.

**Comment by ildyria** [comment]
Can you set in your `.env` the following
```
LIVEWIRE_ENABLED=false
```
And retry, I find this error surprising.

**Comment by ynsta** [comment]
Still got lots of CSP errors in the console.

**Comment by ildyria** [comment]
Issue seems similar to that one:
https://github.com/LycheeOrg/Lychee-Docker/issues/171

Try to add in your `.env`:
```
TRUSTED_PROXIES=*
```

**Comment by ynsta** [comment]
Still got some errors of unsafe inline. The main issue is that the all links in the html source does not respect the APP_URL scheme but use http instead. I think it might be able reduce the security checks by changing headers in traefik as a workaround but I would prefer that the app use the indicated app url. Is there a way to force https in app url ?

```html
--
<!DOCTYPE HTML>
<html lang="fr">
	<head>
		<meta charset="UTF-8">
        <link type="text/css" rel="stylesheet" href="http://MASKED.org/dist/user.css">
<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1.0, maximum-scale=4.0, user-scalable=yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="generator" content="Lychee v4">
<!--General Meta Data -->
<title>Photos</title>
<meta name="description" content="">
<meta name="author" content="MASKED">
<meta name="publisher" content="MASKED">
<!-- Twitter Meta Data -->
<meta name="twitter:title" content="Photos">
<meta name="twitter:description" content="">
<meta name="twitter:image" content="">
<!-- OpenGraph Meta Data (e.g. used by Facebook) -->
<meta property="og:title" content="Photos">
<meta property="og:description" content="">
<meta property="og:image" content="">
<meta property="og:url" content="http://MASKED.org/gallery">

<link rel="shortcut icon" href="http://MASKED.org/favicon.ico">
<link rel="apple-touch-icon" href="http://MASKED.org/img/apple-touch-icon-ipad.png" sizes="120x120">
<link rel="apple-touch-icon" href="http://MASKED.org/img/apple-touch-icon-iphone.png" sizes="152x152">
<link rel="apple-touch-icon" href="http://MASKED.org/img/apple-touch-icon-iphone-plus.png" sizes="180x180">		
...
```

**Comment by ildyria** [comment]
Actually already implemented. :smile: 
```
APP_FORCE_HTTPS=true
```

**Comment by ynsta** [comment]
Yes maybe I need to relaunch something in the container ? The env is correctly set in the container as displayed by the `env  | grep APP` command :

```
APP_FORCE_HTTPS=true
APP_URL=https://MASKED.org
```

but the html source code is still using http and not https.

**Comment by haivala** [comment]
I'm using nginx docker container and I had to set `fastcgi_param HTTPS on;` to get this to work. Before it was not nesessity

**Comment by ildyria** [comment]
My mistake on APP_FORCE_HTTPS it seems to only be used in the links, but not in the resources (will need to look more into this).

BTW using apache I have the following set:
```apache
    Header always set Strict-Transport-Security "max-age=31536000"
    BrowserMatch "MSIE [2-6]" nokeepalive ssl-unclean-shutdown downgrade-1.0 force-response-1.0
    BrowserMatch "MSIE [17-9]" ssl-unclean-shutdown

    RequestHeader set X-Forwarded-Proto https
    RequestHeader set X-Forwarded-SSL expr=%{HTTPS}
```

**Comment by ynsta** [comment]
> I'm using nginx docker container and I had to set `fastcgi_param HTTPS on;` to get this to work. Before it was not nesessity

Thanks @haivala I set this by overloading /etc/nginx/nginx.conf with a mounted file in my docker compose and it works.

**Comment by sloniupl** [comment]
Is there any way to load this as an env not to have a separate nginx.conf loaded? Just asking in case in future it would change?
Btw. it also fixed my issue that i had on some lychee galeries:
![image](https://github.com/LycheeOrg/Lychee/assets/5970551/3cbf111a-6325-4beb-b870-1c1d6a5068dd)

After adding separate /etc/nginx/nginx.conf with added fastcgi_param HTTPS on; it is working correctly now.

**Comment by haivala** [comment]
@ildyria just so that you know: before the urls of assets were relative and now they have the protocol and host in them in the header links. Also random pic api point returns whole urls now.

**Comment by 907739769** [comment]
> Issue seems similar to that one: [LycheeOrg/Lychee-Docker#171](https://github.com/LycheeOrg/Lychee-Docker/issues/171)
> 
> Try to add in your `.env`:
> 
> ```
> TRUSTED_PROXIES=*
> ```

Problem solved👍

**Comment by ildyria** [comment]
> Also random pic api point returns whole urls now.

Yes, that is because Livewire now uses full url `https://example.com/gallery/albumID/photoID` instead of Fragments `https://example.com/gallery#albumID/photoID`.

This is why we just strengthen the diagnostics with #2105

**Comment by d7415** [comment]
> Yes, that is because Livewire now uses full url ... instead of Fragments

Or (IIRC) relative URLs. Frameworks seem to hate them, but they solve so many problems.

**Comment by joffotron** [comment]
> ```apache-config
>     RequestHeader set X-Forwarded-Proto https
>     RequestHeader set X-Forwarded-SSL expr=%{HTTPS}
> ```

For anyone coming across this, I had to set these in my apache proxy -> docker config (as well as the env vars mentioned) to make it work
