### ISSUE TITLE
V5: After the update, the download & original buttons disappeared from photo View.

### ISSUE THREAD

**Issue by SilkeKohl** [LycheeOrg/Lychee#2117]
After updating to the latest version, the photo share button disappeared.

**Comment by ildyria** [comment]
This is intended.

1. It is no longer possible to make singular photo public, it is either the full album or nothing.
2. The use case was too limited when you could just copy the URL of said photo.

However I do agree that two things are missing in the photo view:
1. Open original.
2. Download button.

My mistake. I will work on adding those back. Shouldn't take long.

However don't expect the view link (like `https://lychee.test/view?p=QHe_fvA4TP7q4hwb2p3Gp5h3`) anymore.
That one is dead as you can just copy the URL now.
