### ISSUE TITLE
[Enhancement] Error: APP_URL does not match the current url. This will break WebAuthn authentication.

### ISSUE THREAD

**Issue by LudovicRousseau** [LycheeOrg/Lychee#2121]
In my diagnostics page I have:
```
  Warning: APP_URL contains a sub-path. This may impact your WebAuthn authentication.
  Error: APP_URL does not match the current url. This will break WebAuthn authentication.
  Error: APP_URL does not match the current url. This will prevent images to be properly displayed.
```
I understand the warning line is related to https://github.com/LycheeOrg/Lychee/issues/2113

For the 2 error lines I propose to also display the "current url" computed by Lychee so that I can know what Lychee is expected in `APP_URL`.
I read the [source code](https://github.com/LycheeOrg/Lychee/blob/master/app/Actions/Diagnostics/Pipes/Checks/AppUrlMatchCheck.php#L25) but it is not clear to me what `APP_URL` should contain to make Lychee happy.

**Comment by ildyria** [comment]
While I agree with you, my concern is about revealing info when posting the diagnostics when creating an issue (basically just being able to copy-paste the full diagnostic page).
What would you suggest in such case ? :confused: 

BTW I am thinking about your use-case under folders, I will probably need to have to add another config in `.env` for those.

**Comment by d7415** [comment]
> While I agree with you, my concern is about revealing info when posting the diagnostics when creating an issue (basically just being able to copy-paste the full diagnostic page).
> What would you suggest in such case ? 😕

We could put the potentially sensitive stuff in a tooltip?

**Comment by LudovicRousseau** [comment]
I tooltip would be fine.
Or the complete message in `storage/logs/daily-*` or something similar.
