### ISSUE TITLE
Page format/view funky after update to 5.0.0 and 5.0.1

### ISSUE THREAD

**Issue by blaine07** [LycheeOrg/Lychee#2122]
### Detailed description of the problem [REQUIRED]
I log in on desktop; it formats page all funky and is... broken?

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Log in
2. See the weird mess i'll show in pictures?

**Screenshots**
![Screenshot 2023-12-28 084131](https://github.com/LycheeOrg/Lychee/assets/63940698/e853770e-10f6-4594-b581-42d6c842da63)

### Output of the diagnostics  [REQUIRED]
I would be happy to DM them to someone but not sure they'll actually be required?

Immich is running on a Unraid Server using Linuxserver.io Lychee image. Device accessing is a Windows 10 device with Chrome V120 BUT browser seems to be irrelvant. Page doesn't format correctly accessing from on my MAC either.

Is this something I have done/that I can fix?

**Comment by blaine07** [comment]
Also, trying to access "LOGS" in browser results in this; if related?

![Screenshot 2023-12-28 084919](https://github.com/LycheeOrg/Lychee/assets/63940698/bad7b577-a248-4aee-a9fb-a4c2a6ae837a)

**Comment by blaine07** [comment]
For what it's worth, if it helps anyone else, the "APP_FORCE_HTTPS=true" and "APP_URL=https://domain.mydomain.net" was the resolution - REMEMBER this was with/on Linuxserver Docker Container and using Cloudflare Proxy as my reverse proxy.

**Comment by ildyria** [comment]
Literally what I was going to say: :laughing: 

1. Fix your `APP_URL`,
2. set up your reverse proxy to forward https,
3. `TRUSTED_PROXIES=*`
4. `APP_FORCE_HTTPS=true`
