### ISSUE TITLE
[5.0, master] login window says update is always available

### ISSUE THREAD

**Issue by haivala** [LycheeOrg/Lychee#2125]
### Detailed description of the problem [REQUIRED]
I use master branch from the github.

### Output of the diagnostics  [REQUIRED]
    System Information
    ------------------
        Lychee Version (git):                    master (33354a2) -- More than 30 commits behind (22 hours ago).
        DB Version:                              5.0.2

**Comment by ildyria** [comment]
Something is not going well here.

**Comment by ildyria** [comment]
Can you check your logs for an Error ?
Because that code is working fine locally on my end.
My guess is that the json request to https://api.github.com/repos/LycheeOrg/Lychee/commits is not being executed properly or crashing.

**Comment by ildyria** [comment]
That specific string ("More than 30 commits behind (22 hours ago)") is set in :
https://github.com/LycheeOrg/Lychee/blob/master/app/Metadata/Versions/GitHubVersion.php#L89
Using:
https://github.com/LycheeOrg/Lychee/blob/master/app/Metadata/Versions/Remote/AbstractGitRemote.php#L63
Which uses data from:
https://github.com/LycheeOrg/Lychee/blob/master/app/Metadata/Versions/Remote/AbstractGitRemote.php#L42
Fetching data from request:
https://github.com/LycheeOrg/Lychee/blob/master/app/Metadata/Versions/Remote/GitCommits.php#L47
Using the Commit request:
https://github.com/LycheeOrg/Lychee/blob/master/app/Metadata/Json/CommitsRequest.php
The request is executed here where the Log error should be seen.
https://github.com/LycheeOrg/Lychee/blob/master/app/Metadata/Json/JsonRequestFunctions.php#L67

**Comment by haivala** [comment]
Hmm. I updated the master and tried to find the error but seems like everything is now working as expected. I'll open new issue if this happens again. Thank you!
