### ISSUE TITLE
V 5.0.2 - cover for upper level album cannot be set - error 500

### ISSUE THREAD

**Issue by robs-fotoalbum** [LycheeOrg/Lychee#2126]
### Detailed description of the problem [REQUIRED]
If you want to set an album cover for a top level album, the right click on the lower level album and the select results in http exception 500 "Unable to call component method. Public method [setAsCover] not found on component"

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. select lower level album
2. right click
3. select cover
4. see error

**Screenshots**
![grafik](https://github.com/LycheeOrg/Lychee/assets/111909427/99378ad7-58fa-4a6c-b19f-2089e4bdc0d0)
![grafik](https://github.com/LycheeOrg/Lychee/assets/111909427/2fd84f58-f861-4f45-9c9d-e1c225b72c83)
![grafik](https://github.com/LycheeOrg/Lychee/assets/111909427/0665a8d7-974e-435e-bf6f-1163026cb9d3)

**Error Log**
![grafik](https://github.com/LycheeOrg/Lychee/assets/111909427/75cfea79-7332-4b36-91d0-760009060919)

### Output of the diagnostics  [REQUIRED]
![grafik](https://github.com/LycheeOrg/Lychee/assets/111909427/cce2d560-0676-4154-bae0-3690c5c813c9)

### Browser and system
Firefox 121, Mac OS 14, Lychee 5.0.2. hosted on PikaPods

**Comment by ildyria** [comment]
Should be fixed on master.
Will be published either on 5.0.3 or on nightly build.
