### ISSUE TITLE
Blur overlay for sensitive albums skippable

### ISSUE THREAD

**Issue by mashb1t** [LycheeOrg/Lychee#2136]
### Detailed description of the problem [REQUIRED]
As far as i could see the mentioned issue in https://github.com/LycheeOrg/Lychee/pull/2090#issuecomment-1869057194 has not yet been fixed.

When scrolling on a sensitive page and the banner is shown one can simply scroll down and see the content while the banner is still visible.

Same settings as in https://github.com/LycheeOrg/Lychee/issues/2088

**Comment by ildyria** [comment]
Which version are you using?

**Comment by ildyria** [comment]
I can 100% guarantee you this is fixed on master branch.

**Comment by mashb1t** [comment]
I'm sorry, still had modifications active which prevented the fixes to take effect.
Thank you for the implenentation, much appreciated.
