### ISSUE TITLE
[Enhancement] Option to disable photo banner in the album view

### ISSUE THREAD

**Issue by pawelmalak** [LycheeOrg/Lychee#2146]
It would be nice to be able to disable photo banner added in v5 and to force *compact* view across all albums.

Banner view:
![image](https://github.com/LycheeOrg/Lychee/assets/24780509/69401c5a-586c-4d9c-a445-b6995002924a)

Compact view:
![image](https://github.com/LycheeOrg/Lychee/assets/24780509/35462c82-b310-4cbf-8cd8-4584e1b7372b)

**Comment by pawelmalak** [comment]
Here is a temporary JS workaround to remove banner and recreate the header:
```js
if (window.location.pathname.split('/').length > 2) {
  document
    .querySelector('#lychee_view_content > .w-full.text-neutral-200.relative')
    .remove();

  const header = document.createElement('h1');
  header.className = 'font-bold text-2xl text-text-main-0';
  header.textContent = document
    .getElementById('backButton')
    .nextElementSibling.textContent.trim();

  document
    .querySelector('#lychee_view_content > .w-full.px-7 > .order-1')
    .prepend(header);
}
```

**Comment by ildyria** [comment]
Already planned.

⁣Get BlueMail for Android ​

**Comment by Gendra13** [comment]
What would also be a nice option:
If you could select a specific image from the album, that is used for the banner, instead of a random one (similar to the album thumbnail)
