### ISSUE TITLE
Demo site is broken

### ISSUE THREAD

**Issue by adamshand** [LycheeOrg/Lychee#2148]
### Detailed description of the problem [REQUIRED]

Demo site linked on the front page of the Lychee website is down.  

Screenshot attached.

<img width="454" alt="image" src="https://github.com/LycheeOrg/Lychee/assets/130651/7cbedf65-a8b1-477f-a164-4fe19474ecd3">

**Comment by d7415** [comment]
This has now been fixed. Thanks for the report!
