### ISSUE TITLE
Swiping L/R no longer works on mobile for v5.0.2

### ISSUE THREAD

**Issue by binarydad** [LycheeOrg/Lychee#2151]
I'm running v5.0.2 on Docker. Most things seem fine, but noticed when browsing on mobile, I can no longer swipe left and right when viewing photos. Instead, I have to tap (twice) to use the L/R buttons. Really quite a jarring change. I am using Firefox for Android. 

Not sure if this is a feature or a bug. Thanks!

**Comment by kamil4** [comment]
Already being worked on: #2140
