### ISSUE TITLE
WebAuthn Option Disappeared in Login screen in v5

### ISSUE THREAD

**Issue by elquimista** [LycheeOrg/Lychee#2154]
### Detailed description of the problem [REQUIRED]
After upgrading from 4.13.0 to 5.0.0, I can no longer see webauthn option in login popup. In 4.13.0, I used to see a key icon in the top left corner of the login popup and was able to login with biometric mechanism, but that button is no longer there and I can't find it anywhere else.

Tried it again after upgrading from 5.0.0 to 5.0.1, and to 5.0.2 and it's still not there.

### Browser and system
Chrome and Safari on macOS Sonoma.

**Comment by elquimista** [comment]
There's also another related issue that prevents from registering a new webauthn credentials in webauthn settings once logged in. Chrome dev tools console shows something like "419 unknown status SessionExpiredError".

**Comment by ildyria** [comment]
Lemme check that webauthn thingy.

**Comment by ildyria** [comment]
Fix is on it's way.
