### ISSUE TITLE
Error displaying enlarged images when accessing a public album without being logged in

### ISSUE THREAD

**Issue by Gendra13** [LycheeOrg/Lychee#2158]
### Detailed description of the problem [REQUIRED]
When accessing a public album without beeing logged in, I can see all the thumbnails, but as soon as I click on an image to enlarge it, it will not open. However, when I am logged in, everything works fine.

The logfiles show a lot lines like
`Error | 2024-01-03 20:08:06 | production | App\Actions\HoneyPot\BasePipe::throwNotFound:40  The route  gallery/qTFtqhAnxk-quFj9fiy9DepV/sym/4e81cfae609da92f69c17943d383927836019e4a2a7e476678624542d1d9f810.jpg  could not be found.`

When checking the tracelog of my browser I found the following:
All the small (working) images are located under the path
`https://lychee.mydomain.de/sym/<imageid>.jpg`
however the defective images are looked up under the path
`https://lychee.mydomain.de/gallery/<galleryid>/sym/<imageid>.jpg`

If I manually remove the additional `/gallery/<galleryid>/` and manually try to open the image it works fine. So I believe that part should not be in the image path. However, I don't understand why this is only the case when I am visiting the album without being logged in.

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Create an album and upload some images
2. Make the album public (doesn't matter if hidden or not)
3. Open the album without beeing logged in
4. Click on a small image in the gallery to enlarge it
5. The image will not load

**Screenshots**
When opening the album, all the small images are loading fine:
![Thumbnails](https://github.com/LycheeOrg/Lychee/assets/52973190/ecb92e48-2123-4353-87bd-a1ff1895344f)

When clicking on the first image, no large image is loading and I can see some 404 errors in the tracelog. Notice the different path of the jpg files compared to the first image
![after clicking](https://github.com/LycheeOrg/Lychee/assets/52973190/8218a7d4-ff52-4d91-b03f-047daa283179)

### Output of the diagnostics  [REQUIRED]

    Diagnostics
    -----------
        Warning: /var/www/html/lychee/public/sym/ has permissions 0755, but should have 2775
        Warning: Dropbox import not working. dropbox_key is empty.
        Info: Latest version of PHP is 8.3
        Warning: Default timezone not properly set; you might experience strange results when importing photos without explicit EXIF timezone
         Foreign key: access_permissions.user_id     → users.id             : CASCADE
         Foreign key: albums.parent_id               → albums.id            : RESTRICT
         Foreign key: albums.id                      → base_albums.id       : RESTRICT
         Foreign key: albums.cover_id                → photos.id            : CASCADE
         Foreign key: base_albums.owner_id           → users.id             : RESTRICT
         Foreign key: jobs_history.owner_id          → users.id             : RESTRICT
         Foreign key: photos.album_id                → albums.id            : RESTRICT
         Foreign key: photos.owner_id                → users.id             : RESTRICT
         Foreign key: size_variants.photo_id         → photos.id            : RESTRICT
         Foreign key: sym_links.size_variant_id      → size_variants.id     : RESTRICT
         Foreign key: tag_albums.id                  → base_albums.id       : RESTRICT
     

    System Information
    ------------------
        Lychee Version (release):                5.0.2
        DB Version:                              5.0.2
        
        composer install:                        --no-dev
        APP_ENV:                                 production
        APP_DEBUG:                               false
        APP_URL:                                 set
        
        System:                                  Linux
        PHP Version:                             8.2.14
        PHP User agent:                          Lychee/4 (https://lycheeorg.github.io/)
        Timezone:                                UTC
        Max uploaded file size:                  1024M
        Max post size:                           1024M
        Livewire chunk size:                     12.00 MB
        Max execution time:                      300
        MySQL Version:                           10.6.12-MariaDB-0ubuntu0.22.04.1
        
        exec() Available:                        yes
        Imagick Available:                       1
        Imagick Enabled:                         1
        Imagick Version:                         1691
        GD Version:                              2.3.3
        Number of foreign key:                   11 found.
     
 

    Config Information
    ------------------
        version:                                 050002
        check_for_updates:                       1
        sorting_photos_col:                      taken_at
        sorting_photos_order:                    ASC
        sorting_albums_col:                      max_taken_at
        sorting_albums_order:                    ASC
        imagick:                                 1
        skip_duplicates:                         0
        small_max_width:                         0
        small_max_height:                        360
        medium_max_width:                        1920
        medium_max_height:                       1080
        lang:                                    en
        image_overlay_type:                      none
        default_license:                         reserved
        compression_quality:                     90
        grants_full_photo_access:                1
        delete_imported:                         0
        mod_frame_enabled:                       0
        mod_frame_refresh:                       30
        thumb_2x:                                1
        small_2x:                                1
        medium_2x:                               1
        landing_page_enable:                     0
        site_owner:                              John Smith
        landing_title:                           John Smith
        landing_subtitle:                        Cats, Dogs & Humans Photography
        sm_facebook_url:                         https://www.facebook.com/JohnSmith
        sm_flickr_url:                           https://www.flickr.com/JohnSmith
        sm_twitter_url:                          https://www.twitter.com/JohnSmith
        sm_instagram_url:                        https://instagram.com/JohnSmith
        sm_youtube_url:                          https://www.youtube.com/JohnSmith
        landing_background:                      dist/cat.webp
        site_title:                              Lychee v5
        footer_show_copyright:                   1
        site_copyright_begin:                    2019
        site_copyright_end:                      2019
        footer_additional_text:                  
        footer_show_social_media:                0
        search_public:                           0
        SL_enable:                               1
        SL_for_admin:                            0
        recent_age:                              1
        grants_download:                         0
        photos_wraparound:                       1
        map_display:                             1
        zip64:                                   1
        map_display_public:                      1
        map_provider:                            OpenStreetMap.de
        force_32bit_ids:                         0
        map_include_subalbums:                   1
        update_check_every_days:                 3
        has_exiftool:                            0
        share_button_visible:                    0
        import_via_symlink:                      0
        has_ffmpeg:                              0
        location_decoding:                       1
        location_decoding_timeout:               30
        location_show:                           1
        location_show_public:                    0
        rss_enable:                              0
        rss_recent_days:                         7
        rss_max_items:                           100
        prefer_available_xmp_metadata:           0
        editor_enabled:                          1
        lossless_optimization:                   0
        swipe_tolerance_x:                       150
        swipe_tolerance_y:                       250
        local_takestamp_video_formats:           .avi|.mov
        log_max_num_line:                        1000
        unlock_password_photos_with_url_param:   0
        nsfw_visible:                            1
        nsfw_blur:                               0
        nsfw_warning:                            0
        nsfw_warning_admin:                      0
        nsfw_banner_override:                    
        map_display_direction:                   1
        album_subtitle_type:                     oldstyle
        upload_processing_limit:                 4
        new_photos_notification:                 0
        legacy_id_redirection:                   1
        zip_deflate_level:                       6
        SA_enabled:                              1
        default_album_protection:                1
        album_decoration:                        none
        album_decoration_orientation:            row
        allow_username_change:                   1
        auto_fix_orientation:                    1
        use_job_queues:                          0
        random_album_id:                         starred
        use_last_modified_date_when_no_exif_date: 0
        ffmpeg_path:                             
        ffprobe_path:                            
        layout:                                  justified
        date_format_photo_thumb:                 M j, Y, g:i:s A e
        date_format_photo_overlay:               M j, Y, g:i:s A e
        date_format_sidebar_uploaded:            M j, Y, g:i:s A e
        date_format_sidebar_taken_at:            M j, Y, g:i:s A e
        date_format_hero_min_max:                F Y
        date_format_hero_created_at:             M Y
        date_format_album_thumb:                 M Y
        upload_chunk_size:                       0
        nsfw_banner_blur_backdrop:               0
        search_pagination_limit:                 1000
        search_minimum_length_required:          4
        photo_layout_justified_row_height:       320
        photo_layout_masonry_column_width:       300
        photo_layout_grid_column_width:          250
        photo_layout_square_column_width:        200
        photo_layout_gap:                        12
        display_thumb_album_overlay:             always
        display_thumb_photo_overlay:             hover`

### Browser and system
Ubuntu 22.04 LTS and Firefox 121 (64bit)

**Comment by ildyria** [comment]
Thanks for the report. I know where to fix that one.
