### ISSUE TITLE
Hide smart albums via CSS is not working in version 5.0.2

### ISSUE THREAD

**Issue by sigulete** [LycheeOrg/Lychee#2163]
### Detailed description of the problem [REQUIRED]
The instructions explained in the [documentation](https://lycheeorg.github.io/docs/faq_general.html#how-to-hide-smart-albums) are not working in version 5.0.2.

Would you be able to confirm if there is a necessity to updae the docs?

### Steps to reproduce the issue
1. Click on 'Settings' 
2. Paste the code from the documentation into 'Personalize CSS'
3. Clean cache
4. Re-open website

### Output of the diagnostics  [REQUIRED]

  Diagnostics
    -----------
    Info: Latest version of PHP is 8.3
    Warning: Online updates are disabled by configuration
    Foreign key: access_permissions.user_id     → users.id             : CASCADE
    Foreign key: albums.id                      → base_albums.id       : NO ACTION
    Foreign key: base_albums.owner_id           → users.id             : NO ACTION
    Foreign key: jobs_history.owner_id          → users.id             : NO ACTION
    Foreign key: photos.album_id                → albums.id            : NO ACTION
    Foreign key: photos.owner_id                → users.id             : NO ACTION
    Foreign key: size_variants.photo_id         → photos.id            : NO ACTION
    Foreign key: sym_links.size_variant_id      → size_variants.id     : NO ACTION
    Foreign key: tag_albums.id                  → base_albums.id       : NO ACTION

    System Information
    ------------------
    Lychee Version (git):                    ?? (33354a2) -- Could not compare.
    DB Version:                              5.0.2
    
    composer install:                        --no-dev
    APP_ENV:                                 production
    APP_DEBUG:                               false
    APP_URL:                                 set
    
    System:                                  Linux
    PHP Version:                             8.2.7
    PHP User agent:                          Lychee/4 (https://lycheeorg.github.io/)
    Timezone:                                Australia/Melbourne
    Max uploaded file size:                  5G
    Max post size:                           5G
    Livewire chunk size:                     12.00 MB
    Max execution time:                      3600
    SQLite Version:                          3.40.1
    
    exec() Available:                        yes
    Imagick Available:                       1
    Imagick Enabled:                         1
    Imagick Version:                         1691
    GD Version:                              2.3.3
    Number of foreign key:                   9 found.

    Config Information
    ------------------
    version:                                 050002
    check_for_updates:                       0
    sorting_photos_col:                      taken_at
    sorting_photos_order:                    ASC
    sorting_albums_col:                      title
    sorting_albums_order:                    DESC
    imagick:                                 1
    skip_duplicates:                         1
    small_max_width:                         0
    small_max_height:                        360
    medium_max_width:                        1920
    medium_max_height:                       1080
    lang:                                    en
    image_overlay_type:                      date
    default_license:                         none
    compression_quality:                     90
    grants_full_photo_access:                1
    delete_imported:                         0
    mod_frame_enabled:                       1
    mod_frame_refresh:                       30
    thumb_2x:                                1
    small_2x:                                1
    medium_2x:                               1
    landing_page_enable:                     0
    site_owner:                              Owner
    landing_title:                           Title
    landing_subtitle:                        Family Photos
    sm_facebook_url:                         
    sm_flickr_url:                           
    sm_twitter_url:                          
    sm_instagram_url:                        
    sm_youtube_url:                          
    landing_background:                      dist/cat.webp
    site_title:                              Photos
    footer_show_copyright:                   0
    site_copyright_begin:                    2000
    site_copyright_end:                      3000
    footer_additional_text:                  
    footer_show_social_media:                0
    search_public:                           0
    SL_enable:                               0
    SL_for_admin:                            0
    recent_age:                              1
    grants_download:                         0
    photos_wraparound:                       1
    map_display:                             1
    zip64:                                   1
    map_display_public:                      0
    map_provider:                            OpenStreetMap.org
    force_32bit_ids:                         0
    map_include_subalbums:                   0
    update_check_every_days:                 3
    has_exiftool:                            0
    share_button_visible:                    1
    import_via_symlink:                      0
    has_ffmpeg:                              1
    location_decoding:                       1
    location_decoding_timeout:               30
    location_show:                           1
    location_show_public:                    0
    rss_enable:                              0
    rss_recent_days:                         7
    rss_max_items:                           100
    prefer_available_xmp_metadata:           0
    editor_enabled:                          1
    lossless_optimization:                   0
    swipe_tolerance_x:                       150
    swipe_tolerance_y:                       250
    local_takestamp_video_formats:           .avi|.mov
    log_max_num_line:                        1000
    unlock_password_photos_with_url_param:   0
    nsfw_visible:                            1
    nsfw_blur:                               0
    nsfw_warning:                            0
    nsfw_warning_admin:                      0
    nsfw_banner_override:                    
    map_display_direction:                   1
    album_subtitle_type:                     oldstyle
    upload_processing_limit:                 8
    new_photos_notification:                 0
    legacy_id_redirection:                   1
    zip_deflate_level:                       6
    SA_enabled:                              1
    default_album_protection:                1
    album_decoration:                        all
    album_decoration_orientation:            row
    allow_username_change:                   1
    auto_fix_orientation:                    1
    use_job_queues:                          0
    random_album_id:                         starred
    use_last_modified_date_when_no_exif_date: 0
    ffmpeg_path:                             /bin/ffmpeg
    ffprobe_path:                            /bin/ffprobe
    layout:                                  square
    date_format_photo_thumb:                 M j, Y, g:i:s A e
    date_format_photo_overlay:               M j, Y, g:i:s A e
    date_format_sidebar_uploaded:            M j, Y, g:i:s A e
    date_format_sidebar_taken_at:            M j, Y, g:i:s A e
    date_format_hero_min_max:                F Y
    date_format_hero_created_at:             M j, Y, g:i:s A T
    date_format_album_thumb:                 M Y
    upload_chunk_size:                       0
    nsfw_banner_blur_backdrop:               0
    search_pagination_limit:                 1000
    search_minimum_length_required:          4
    photo_layout_justified_row_height:       320
    photo_layout_masonry_column_width:       300
    photo_layout_grid_column_width:          250
    photo_layout_square_column_width:        200
    photo_layout_gap:                        12
    display_thumb_album_overlay:             always
    display_thumb_photo_overlay:             hover

### Browser and system
Vivaldi, Firefox
Linux

**Comment by ildyria** [comment]
Hi,

indeed, this is no longer working (due to the large refactoring of the front-end).

I think in that specific case (disabling smart albums), it would be easier to simply add a toggle options in the settings to _enable/disable_ the smart albums.

Either on option to disable all the smart albums or 1 per smart album...

Opinions?

**Comment by kamil4** [comment]
I agree; it should be a proper option rather than a CSS hack. We should make an inventory of the options already there; don't we already have some options that determine whether to display smart albums in public mode? If we wanted to minimize the number of options, we could probably refactor it into just two: one providing a comma-separatedlist of smart albums to display when authenticated, and another with the same info when in public mode.

**Comment by ildyria** [comment]
Actually there is already an option for that since version **4.6.4**, released on December 26th 2022... :roll_eyes: 
See `SA_enabled` in your config.
