### ISSUE TITLE
Universal Drag & Drop and Paste to upload no longer work when using Livewire

### ISSUE THREAD

**Issue by Catsumori** [LycheeOrg/Lychee#2168]
### Detailed description of the problem [REQUIRED]
On the v4 Frontend you were able to paste (ctrl + v) or drag and drop an image/gif/webm anywhere on the page to upload an image to the current album or to Unsorted if on the home Gallery page. This no longer works on Lychee v5 when using Livewire. Upload via drag and drop does work but only if you first bring up the 'Upload Photo' menu with the prompt to drag and drop. Universal Drag and Drop/Paste were what drew me to Lychee in the first place as a replacement to Imgur which has that functionality

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Log In
2. Right Click -> Paste or Ctrl + v to attempt to paste an image/video anywhere on the page or Drag & Drop an image/video
3. Nothing happens

### Browser and system
Tried using Chrome and Firefox on Windows 10 and Ubuntu

**Comment by TheDrew2013** [comment]
Same here. This was one of the reasons I chose Lychee over other options, and it was present in v4.

**Comment by ildyria** [comment]
Yeah yeah I know. I'm working on adding it back in V6.

**Comment by TheDrew2013** [comment]
That's cool. I found the .env value to disable livewire and my v5 instance is working as expected again. :)
