### ISSUE TITLE
[Enhancement] Option to download a single photo instead of the entire album

### ISSUE THREAD

**Issue by pawelmalak** [LycheeOrg/Lychee#2174]
Option to download a single photo in different qualities like it was possible in v4. 

Right now it's not possible to download a single photo in the original quality, you have to download the entire album in zip format, which is inconvenient, especially on mobile devices.

A button to open photo in original quality in new tab, so it can be easily saved on desktop/mobile, would be a nice addition.

**Comment by ildyria** [comment]
Yeah I need to add those buttons back.

**Comment by ildyria** [comment]
Duplicate #2117
