### ISSUE TITLE
Minor bug: In the photo details page, there is an 'f /' too much for the aperture value.

### ISSUE THREAD

**Issue by Gendra13** [LycheeOrg/Lychee#2186]
### Detailed description of the problem [REQUIRED]
When showing the exif information of an image, the aperture value has two sets of 'f /' (like '**f /** f/3.2') instead of one.

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Open an image
2. Click on 'i' to open the about page

**Screenshots**
![aperture](https://github.com/LycheeOrg/Lychee/assets/52973190/ee6b8820-e3c6-4856-9352-65efe3486dd7)

### Output of the diagnostics  [REQUIRED]
    Diagnostics
    -----------
        Warning: /var/www/html/lychee/public/sym/ has permissions 0755, but should have 2775
        Warning: Dropbox import not working. dropbox_key is empty.
        Info: Latest version of PHP is 8.3
        Warning: Default timezone not properly set; you might experience strange results when importing photos without explicit EXIF timezone
     

    System Information
    ------------------
        Lychee Version (release):                5.0.2
        DB Version:                              5.0.2
        
        composer install:                        --no-dev
        APP_ENV:                                 production
        APP_DEBUG:                               false
        APP_URL:                                 set
        APP_DIR:                                 default
        LOG_VIEWER_ENABLED:                      true
        LIVEWIRE_ENABLED:                        true
        
        System:                                  Linux
        PHP Version:                             8.2.14
        PHP User agent:                          Lychee/4 (https://lycheeorg.github.io/)
        Timezone:                                UTC
        Max uploaded file size:                  1024M
        Max post size:                           1024M
        Livewire chunk size:                     12.00 MB
        Max execution time:                      300
        MySQL Version:                           10.6.12-MariaDB-0ubuntu0.22.04.1
        
        exec() Available:                        yes
        Imagick Available:                       1
        Imagick Enabled:                         1
        Imagick Version:                         1691
        GD Version:                              2.3.3
        Number of foreign key:                   11 found.

### Browser and system
Ubuntu 22.04 LTS

**Comment by ildyria** [comment]
Fix is on its way.
