### ISSUE TITLE
allow multiple virtual domains in APP_URL

### ISSUE THREAD

**Issue by mjechow** [LycheeOrg/Lychee#2189]
I have set APP_URL to https://photo.examle.org and everything is working properly. Unfortunately, my page is also accessible via https://photos.example.org, https://fotos.example.org and https://foto.example.org. Is it possible to configure APP_URL accordingly (i.e., with a comma separated list).?

**Comment by d7415** [comment]
This is not currently possible. #2182 may be sufficient depending on your use case.

**Comment by ildyria** [comment]
@mjechow I think you are mis-understanding.

Change #2182 will allow that for you.
However WebAuthn won't be available then.

What is not planned is supporting multiple APP_URL values, because the framework (Laravel) does not support it. :(

**Comment by mjechow** [comment]
Thanks for the clarification!
