### ISSUE TITLE
[Enhancement] Add the option to select a specific image for the album banner (like with the album cover)

### ISSUE THREAD

**Issue by Gendra13** [LycheeOrg/Lychee#2202]
With the last update came to option to disable the album banner globally (compact view), thanks a lot for that.

However, it would also be a very nice feature, to have the ability to select a specific image from the album that is always displayed as the banner instead of a random one. This could be done the same way you can currently select a specific album cover.

Together with such a feature, it would also be nice, if you could enable/disable the compact view option per album instead of it being a global setting.

**Comment by ildyria** [comment]
Yes I am aware of this one, just lack of time for implementation.
That would also be a nice project for someone who wants to get their hand dirty and dive a bit in the code of Lychee (wouldn't be as difficult as the cover one).
