### ISSUE TITLE
Import from Dropbox does nothing, how to debug?

### ISSUE THREAD

**Issue by MisterC925** [LycheeOrg/Lychee#2215]
### Detailed description of the problem [REQUIRED]
I had an install of Lychee v4 working with dropbox, but due to some issues with my webhost I ended up making a new Lychee v5.1.0 instance using the official docker image and was just going to re-import all of my photos from Dropbox.

I generated a new API key for my dropbox app that had worked previously and entered it into the config.

Now when I click "+" and then "Import from Dropbox" nothing happens.

Using the web console I see no network activity, no script errors, etc, just nothing.

I used Dropbox's API tester to make sure my auth key worked and it does. 

Something I noticed is all of the Lychee docs refer to a 'Drop ins" key but it doesn't appear that dropbox offers the ability to create a drop ins key anymore just a general API key?

Is there a way to debug where this is breaking down?

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Go to "+"
2. Click on "Import from dropbox"
(No action happens from here)

### Output of the diagnostics  [REQUIRED] 

NOTE: Instance is behind a load balancer, so the instance listens on port 80/http but the app_url refers to the load balancer listing at 443/https which is why the two APP_URL errors appear.  It does not seem to affect the serving of images.

   Diagnostics
    -----------
        Warning: zend.assertions is disabled although Lychee is in debug mode. For easier debugging code generation for assertions should be enabled.
        Error: APP_URL (https://lychee.***************aphy.com) does not match the current url (http://lychee.***************aphy.com).
               This will break WebAuthn authentication.
        Error: APP_URL (https://lychee.***************aphy.com) does not match the current url (http://lychee.***************aphy.com).
               This will prevent images from being properly displayed.
        Info: Latest version of PHP is 8.3
        Warning: git (software) is not available.

### Browser and system
MacOS Firefox 121 and Chrome 120 for client, oracle linux + docker for server.

**Comment by ildyria** [comment]
You can temporarily disable the Livewire front-end for this import (set `LIVEWIRE_ENABLED=false` in your `.env`), I haven't had time to dig into the Dropbox stuff to be honest.

**Comment by ildyria** [comment]
> NOTE: Instance is behind a load balancer, so the instance listens on port 80/http but the app_url refers to the load balancer listing at 443/https which is why the two APP_URL errors appear. It does not seem to affect the serving of images.

You should still set your `APP_URL` to use https. Your load balancer should also make sure to forward the https proto or you might encounter some troubles during uploads. Similarly be sure to have set your `TRUSTED_PROXY` in your `.env`

**Comment by MisterC925** [comment]
Thank you

I'll try the TRUSTED_PROXY setting.  Right now the load balancer is https only  (as is my APP_URL) and uploading images through it seems to be working just fine. 

Could this be the cause of the dropbox issue or is that going to be something else?

**Comment by MisterC925** [comment]
I've added the TRUSTED_PROXY and things still aren't working with Dropbox but the error messages about APP_URL are gone.

**Comment by MisterC925** [comment]
> You can temporarily disable the Livewire front-end for this import (set `LIVEWIRE_ENABLED=false` in your `.env`), I haven't had time to dig into the Dropbox stuff to be honest.

This worked.  

Thanks!
