### ISSUE TITLE
GUI update via Diagnostics page not available

### ISSUE THREAD

**Issue by ttrvl** [LycheeOrg/Lychee#2228]
After updating to 5.0.3 feature "Check for update" not showing at "Diagnostics" page.

**Steps to reproduce the behavior:**
1. Go to 'Diagnostics'
2. First text will be Diagnostics block instead of "Check for updates" or "Update available" message like before.

**Screenshots**
1st site:
![изображение](https://github.com/LycheeOrg/Lychee/assets/155813776/660065f9-145f-40bc-8afe-a33662f4ca58)
2nd site:
![изображение](https://github.com/LycheeOrg/Lychee/assets/155813776/73945dd2-61a0-4c8c-8193-c481e6f76578)

### Output of the diagnostics 

    Diagnostics
    -----------
        Warning: Dropbox import not working. dropbox_key is empty.
        Warning: zend.assertions is disabled although Lychee is in debug mode. For easier debugging code generation for assertions should be enabled.
        Info: Latest version of PHP is 8.3
     

    System Information
    ------------------
        Lychee Version (git):                    master (6fc6c10) -- Up to date (38 minutes ago).
        DB Version:                              5.1.0
        
        composer install:                        --no-dev
        APP_ENV:                                 production
        APP_DEBUG:                               true
        APP_URL:                                 set
        APP_DIR:                                 default
        LOG_VIEWER_ENABLED:                      true
        LIVEWIRE_ENABLED:                        true
        
        System:                                  Linux
        PHP Version:                             8.2.7
        PHP User agent:                          Lychee/4 (https://lycheeorg.github.io/)
        Timezone:                                Europe/Moscow
        Max uploaded file size:                  200M
        Max post size:                           100M
        Livewire chunk size:                     12.00 MB
        Max execution time:                      300
        MySQL Version:                           10.11.4-MariaDB-1~deb12u1-log
        
        exec() Available:                        yes
        Imagick Available:                       1
        Imagick Enabled:                         1
        Imagick Version:                         1691
        GD Version:                              2.3.3
        Number of foreign key:                   12 found.
     

    Config Information
    ------------------
        version:                                 050100
        check_for_updates:                       0
        sorting_photos_col:                      taken_at
        sorting_photos_order:                    DESC
        sorting_albums_col:                      max_taken_at
        sorting_albums_order:                    DESC
        imagick:                                 1
        skip_duplicates:                         0
        small_max_width:                         0
        small_max_height:                        360
        medium_max_width:                        1920
        medium_max_height:                       1080
        lang:                                    en
        image_overlay_type:                      none
        default_license:                         CC-BY-NC-SA-4.0

### Browser and system
Lychee installed on Debian Linux 12.4
Browser tried (windows): Firefox 121.0.1, Google Chrome 120.0.6099.225
Via mobile device same result.

### Additional info

I have two sites witch Lychee (both on same server), both have same issue after updating to 5.0.3
One of instances I had updated by console with "git pull" and all other steps to 5.1.0 - no changes. (1st screenshot)
Second instance I decided to not update for testing means (if needed by) (2nd screenshot)

No errors showing in Lychee logs or webserver logs.

**Comment by ildyria** [comment]
I think I forgot to add that functionality in the v5 (as in, I forgot to add the button).

**Comment by ildyria** [comment]
I think this is done since the module maintenance page is completed.
