### ISSUE TITLE
Wrong Lychee version for Version 5.1.1 .zip file

### ISSUE THREAD

**Issue by LudovicRousseau** [LycheeOrg/Lychee#2235]
### Detailed description of the problem
The archive .zip file provides the file `version.md` which contains:
```
$ cat version.md 
5.1.0
```
I would expect `5.1.1` instead.

### Steps to reproduce the issue
1. download https://github.com/LycheeOrg/Lychee/releases/download/v5.1.1/Lychee.zip
2. extract the files
3. see by yourself

**Comment by ildyria** [comment]
WTF.

**Comment by LudovicRousseau** [comment]
It is strange because the change 5.1.0 to 5.1.1 is listed in https://github.com/LycheeOrg/Lychee/compare/v5.1.0...v5.1.1

**Comment by ildyria** [comment]
Fixed. Thank you.

Yeah the zip file is attached manually to the release. It seems that my github refused to do `git pull` 3 times for no reason. Should be fix now.

**Comment by LudovicRousseau** [comment]
I have the problem with the `Lychee.zip` file but NOT with the `Source code (zip)` file.

**Comment by ildyria** [comment]
```
...
  adding: Lychee/vendor/maennchen/zipstream-php/.phpdoc/template/base.html.twig (deflated 61%)
  adding: Lychee/vendor/maennchen/zipstream-php/.editorconfig (deflated 53%)
  adding: Lychee/vendor/maennchen/zipstream-php/LICENSE (deflated 41%)
  adding: Lychee/vendor/maennchen/zipstream-php/psalm.xml (deflated 55%)
  adding: Lychee/vendor/maennchen/zipstream-php/README.md (deflated 68%)
  adding: Lychee/scripts/ (stored 0%)
  adding: Lychee/scripts/install_files.php (deflated 52%)
  adding: Lychee/scripts/post-merge (deflated 67%)
  adding: Lychee/scripts/pre-commit (deflated 57%)
  adding: Lychee/scripts/gen_release.php (deflated 61%)

Documents/Projects/Lychee-dist  master ✗                                                                                                                                                      1h13m ⚑ ◒  
▶ cat version.md
5.1.1%                                
```

**Comment by ildyria** [comment]
thank you for the quick heads up!
