### ISSUE TITLE
.env.example not included in the 5.1.1 release zip

### ISSUE THREAD

**Issue by tobogdan** [LycheeOrg/Lychee#2237]
### Detailed description of the problem
As the title says, the .env.example file is not included in the 5.1.1 release zip (and potentially others)

### Steps to reproduce the issue
1. Go to the Release page and download the 5.1.1 release zip
2. Extract the files and search for the .env.example (or .env) files and see that they're missing
3. Look at the installation guide and become confused: https://lycheeorg.github.io/docs/installation.html#application-settings

**Comment by ildyria** [comment]
I checked, and I unfortunately came to the conclusion that you are blind. :|
![image](https://github.com/LycheeOrg/Lychee/assets/627094/ddd40b9a-228a-4780-afd6-1da79804987a)

**Comment by tobogdan** [comment]
I re-downloaded and re-unzipped and you're right. I have no idea why the file wasn't there the first time. Maybe it is user error.
However, that was super rude :|

**Comment by kamil4** [comment]
@tobogdan Please try not to take it personally. I think @ildyria has lived in the Netherlands for so long now that the Dutch rudeness is beginning to rub off on him (I "escaped" after just five years yet it changed me for life :rofl:).
