### ISSUE TITLE
subdomain install does not redirect to /gallery anymore

### ISSUE THREAD

**Issue by haivala** [LycheeOrg/Lychee#2240]
### Detailed description of the problem [REQUIRED]
title, It should redirect to `/gallery`
env APP_DIR is not used

### Steps to reproduce the issue
1. Go to base url
2. white page appears

### Output of the diagnostics  [REQUIRED]
System Information
------------------
Lychee Version (git):                    master (40591a1) -- Up to date (unknown).
DB Version:                              5.1.1

composer install:                        --no-dev
APP_ENV:                                 production
APP_DEBUG:                               false
APP_URL:                                 set
APP_DIR:                                 default
LOG_VIEWER_ENABLED:                      true
LIVEWIRE_ENABLED:                        true

System:                                  Linux
PHP Version:                             8.2.15
PHP User agent:                          Lychee/4 (https://lycheeorg.github.io/)
Timezone:                                Europe/Helsinki
Max uploaded file size:                  500M
Max post size:                           300M
Livewire chunk size:                     12.00 MB
Max execution time:                      0
MySQL Version:                           10.11.6-MariaDB-1:10.11.6+maria~ubu2204

exec() Available:                        yes
Imagick Available:                       1
Imagick Enabled:                         1
Imagick Version:                         1809
GD Version:                              bundled (2.1.0 compatible)
Number of foreign key:                   12 found.

**Comment by ildyria** [comment]
Can you press F12, and check the console ? 
I smell some CSP error there.

Do you have `LEGACY_V4_REDIRECT` set to `false` or `true`?

**Comment by haivala** [comment]
It was true and when I set it false redirect works again

**Comment by ildyria** [comment]
Can you check that your CSP has the following value: `sha256-9zK0oWYjhW+ACIwFsQ6ksB1HCJ5EoUi+lRyrSt465A4=`

Or to be more precise:
```
form-action 'self'; img-src 'self' https://maps.wikimedia.org/osm-intl/ https://tile.openstreetmap.org/ https://tile.openstreetmap.de/ https://a.tile.openstreetmap.fr/osmfr/ https://b.tile.openstreetmap.fr/osmfr/ https://c.tile.openstreetmap.fr/osmfr/ https://a.osm.rrze.fau.de/osmhd/ https://b.osm.rrze.fau.de/osmhd/ https://c.osm.rrze.fau.de/osmhd/ data: blob:; media-src 'self' blob:; object-src 'none'; script-src 'self' 'report-sample' 'unsafe-eval' 'unsafe-hashes' 'sha256-FdKE+KVp/tkYM5hwGXGeKZ1EmS4DJ8kbnsKo5YymNrc=' 'sha256-bY67+0U7yUmtjaisfHv+mZXHsAptKwcV1a4EacCUL5M=' 'sha256-fwPcZ6SFcvBLfJYjzlBRZfKzcidwsD4GPcmkVECbSKM=' 'sha256-FCPseLYJ4+r0Mbp93zyaq/x4zQEEPLgEectDgkA/V3A=' 'sha256-T0Fzr5h5zkZyE3QOpQ9anSTcWp19WQ14eO86qdlSdvA=' 'sha256-CL4mGy9ZhHM+PkLDZsWVuM25kEFBv3FXlmWe/O9Unmc=' 'sha256-9zK0oWYjhW+ACIwFsQ6ksB1HCJ5EoUi+lRyrSt465A4=' 'sha256-hHvKTS0wUaMuiFMar2j4TbjYjlLQMR/c5b0bA9DLi6g=' https://www.dropbox.com/static/api/1/dropins.js; style-src 'self' 'unsafe-inline'
```

![image](https://github.com/LycheeOrg/Lychee/assets/627094/4c7aa880-46db-4077-8390-bfd33ee4aa31)

**Comment by ildyria** [comment]
Wait... gimme a sec.

**Comment by ildyria** [comment]
I know why it is not working... FML.

```html
<script>
	// Dirty work around.
	const hashMatch = document.location.hash.replace("#", "").split("/");
	const albumID = hashMatch[0] ?? '';
	const photoID = hashMatch[1] ?? '';
	if (photoID !== '') {
		window.location = 'https://lychee.test/gallery/' + albumID + '/' + photoID;
	} else if (albumID !== '') {
		window.location = 'https://lychee.test/gallery/' + albumID;
	} else {
		window.location = 'https://lychee.test/gallery';
	}
</script>
```
Obviously because the route is provided... this is breaking.
Hot fix time...

**Comment by ildyria** [comment]
@haivala can you check if this fixes it: https://patch-diff.githubusercontent.com/raw/LycheeOrg/Lychee/pull/2241.patch

**Comment by ildyria** [comment]
@haivala could you check this for me: https://github.com/LycheeOrg/Lychee/releases/tag/v5.1.2 ? 
Or latest master ?

**Comment by haivala** [comment]
Sorry, I were not on comp since now.
using `LEGACY_V4_REDIRECT` set to true.
On latest master, redirect from `/` to `/gallery` works but it flashes white screen. Any chance to get it redirect sooner?
`/gallery#OO1G5ahoUqecUhHTlOZ_VrSD` is still showing frontpage.

**Comment by ildyria** [comment]
> it flashes white screen

that is because it is doing a first rendering in order to access the fragment before doing the redirection. 
I can change the color of the background to make it less obvious but unfortunately this is a necessary step.
