### ISSUE TITLE
Download photo/open in new tab buttons are not working on mobile

### ISSUE THREAD

**Issue by pawelmalak** [LycheeOrg/Lychee#2247]
### Detailed description of the problem
Buttons to download a photo or to open it in a new tab are not working. They're overlayed by a bar with star, delete, rotate etc. buttons. It happens in both portrait and landscape modes. 

**Screenshots**
![image](https://github.com/LycheeOrg/Lychee/assets/24780509/34a8a3cd-6e6f-4d5a-a86f-309a741c7187)

![image](https://github.com/LycheeOrg/Lychee/assets/24780509/0482f041-6993-46e6-8cd3-b91525d47b23)

### Browser and system
iPhone 13 mini
iOS 16.3.1
Safari

**Comment by ildyria** [comment]
Yeah mobile layout is not well supported. Need to work on that, haven't had time to test it.
