### ISSUE TITLE
Cannot upload photo: error message

### ISSUE THREAD

**Issue by oblomow** [LycheeOrg/Lychee#2248]
### Detailed description of the problem [REQUIRED]
Cannot upload photos

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1.logon to lychee
2. select an existing album
3. upload a photo
4. error:  App\Factories\AlbumFactory::findAbstractAlbumOrFail(): Argument #1 ($albumID) must be of type string, null given, called in /vol/www/data/albums/app/Jobs/ProcessImageJob.php on line 63

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

### Output of the diagnostics  [REQUIRED]
*Diagnostics
-----------
Info: Latest version of PHP is 8.3
Info: Found 52 small that could be generated.
     You can use `php artisan lychee:generate_thumbs small 52` to generate them.
Info: Found 1190 small2x that could be generated.
     You can use `php artisan lychee:generate_thumbs small2x 1190` to generate them.
Info: Found 105 medium that could be generated.
     You can use `php artisan lychee:generate_thumbs medium 105` to generate them.
Info: Found 159 medium2x that could be generated.
     You can use `php artisan lychee:generate_thumbs medium2x 159` to generate them.

System Information
------------------
Lychee Version (git):                    master (b560ff5) -- Up to date (0 seconds ago).
DB Version:                              5.1.2

composer install:                        --no-dev
APP_ENV:                                 local
APP_DEBUG:                               false
APP_URL:                                 set
APP_DIR:                                 default
LOG_VIEWER_ENABLED:                      true
LIVEWIRE_ENABLED:                        true

System:                                  FreeBSD
PHP Version:                             8.2.13
PHP User agent:                          Lychee/4 (https://lycheeorg.github.io/)
Timezone:                                Europe/Amsterdam
Max uploaded file size:                  100M
Max post size:                           100M
Livewire chunk size:                     12.00 MB
Max execution time:                      0
MySQL Version:                           8.0.35

exec() Available:                        yes
Imagick Available:                       1
Imagick Enabled:                         1
Imagick Version:                         1808
GD Version:                              2.3.3
Number of foreign key:                   14 found.

Config Information
------------------
version:                                 050102
check_for_updates:                       1
sorting_photos_col:                      taken_at
sorting_photos_order:                    ASC
sorting_albums_col:                      title
sorting_albums_order:                    DESC
imagick:                                 1
skip_duplicates:                         0
small_max_width:                         0
small_max_height:                        360
medium_max_width:                        1920
medium_max_height:                       1080
lang:                                    en
image_overlay_type:                      date
default_license:                         CC-BY-NC-ND-4.0
compression_quality:                     90
grants_full_photo_access:                1
delete_imported:                         0
mod_frame_enabled:                       1
mod_frame_refresh:                       30
thumb_2x:                                1
small_2x:                                1
medium_2x:                               1
landing_page_enable:                     1
site_owner:                              Marc
landing_title:                           Marc
landing_subtitle:                        Why stop now?
sm_facebook_url:                         
sm_flickr_url:                           
sm_twitter_url:                          
sm_instagram_url:                        
sm_youtube_url:                          
landing_background:                      dist/finland.jpg
site_title:                              bospaling fotos
footer_show_copyright:                   1
site_copyright_begin:                    1984
site_copyright_end:                      2024
footer_additional_text:                  
footer_show_social_media:                0
search_public:                           0
SL_enable:                               0
SL_for_admin:                            0
recent_age:                              1
grants_download:                         1
photos_wraparound:                       1
map_display:                             0
zip64:                                   1
map_display_public:                      0
map_provider:                            OpenStreetMap.org
force_32bit_ids:                         0
map_include_subalbums:                   0
update_check_every_days:                 3
has_exiftool:                            1
share_button_visible:                    1
import_via_symlink:                      0
has_ffmpeg:                              0
location_decoding:                       0
location_decoding_timeout:               30
location_show:                           0
location_show_public:                    0
rss_enable:                              0
rss_recent_days:                         7
rss_max_items:                           100
prefer_available_xmp_metadata:           0
editor_enabled:                          1
lossless_optimization:                   0
swipe_tolerance_x:                       150
swipe_tolerance_y:                       250
local_takestamp_video_formats:           .avi|.mov
log_max_num_line:                        1000
unlock_password_photos_with_url_param:   0
nsfw_visible:                            1
nsfw_blur:                               0
nsfw_warning:                            0
nsfw_warning_admin:                      0
nsfw_banner_override:                    
map_display_direction:                   1
album_subtitle_type:                     oldstyle
upload_processing_limit:                 4
new_photos_notification:                 1
legacy_id_redirection:                   1
zip_deflate_level:                       6
SA_enabled:                              1
default_album_protection:                1
allow_username_change:                   1
album_decoration:                        layers
album_decoration_orientation:            row
auto_fix_orientation:                    1
use_job_queues:                          0
random_album_id:                         starred
use_last_modified_date_when_no_exif_date: 0
ffmpeg_path:                             
ffprobe_path:                            
layout:                                  justified
date_format_photo_thumb:                 M j, Y, g:i:s A e
date_format_photo_overlay:               M j, Y, g:i:s A e
date_format_sidebar_uploaded:            M j, Y, g:i:s A e
date_format_sidebar_taken_at:            M j, Y, g:i:s A e
date_format_hero_min_max:                F Y
date_format_hero_created_at:             M j, Y, g:i:s A T
date_format_album_thumb:                 M Y
upload_chunk_size:                       0
nsfw_banner_blur_backdrop:               0
search_pagination_limit:                 1000
search_minimum_length_required:          4
photo_layout_justified_row_height:       320
photo_layout_masonry_column_width:       300
photo_layout_grid_column_width:          250
photo_layout_square_column_width:        200
photo_layout_gap:                        12
display_thumb_album_overlay:             always
display_thumb_photo_overlay:             hover
use_album_compact_header:                0
default_album_thumb_aspect_ratio:        1/1
login_button_position:                   left
back_button_enabled:                     0
back_button_text:                        Return to Home
back_button_url:                         /
current_job_processing_visible:          1

**Comment by ildyria** [comment]
@oblomow can you try this https://patch-diff.githubusercontent.com/raw/LycheeOrg/Lychee/pull/2249.patch ? 
Should fix it :)

**Comment by oblomow** [comment]
Yes! that was it. Thanks again for your always quick response! Have a good weekend.
