### ISSUE TITLE
Cannot assign null to property App\Livewire\Components\Pages\Settings::$css of type string

### ISSUE THREAD

**Issue by sayem314** [LycheeOrg/Lychee#2255]
### Detailed description of the problem [REQUIRED]
*A clear and concise description of what the bug is.*

### Steps to reproduce the issue
1. Go to '.../settings'

**Screenshots**
![image](https://github.com/LycheeOrg/Lychee/assets/14138401/49a6a13f-9f5c-4e6a-a3c1-df26cfd63e8f)

### Output of the diagnostics  [REQUIRED]
https://paste.ubuntu.com/p/XtszRpH2xV/

### Browser and system
- Chrome in Manjaro Linux

**Comment by ildyria** [comment]
Can you check that the `user.css` file exists in `public/dist/` ?

**Comment by sayem314** [comment]
@ildyria it's on the official docker image. can confirm this issue still exists on v5.1.2.

**Comment by ildyria** [comment]
> @ildyria it's on the official docker image. can confirm this issue still exists on v5.1.2.

That is quite normal... #2256 is not part of release 5.1.2.

You can check the `nightly` build instead.
