### ISSUE TITLE
Image selecting does not work on chrome + MacOS

### ISSUE THREAD

**Issue by ildyria** [LycheeOrg/Lychee#2361]
### Discussed in https://github.com/LycheeOrg/Lychee/discussions/2358

<div type='discussions-op-text'>

<sup>Originally posted by **Puupuls** April  8, 2024</sup>
### Lychee version

v5.1.2

### Which PHP version are you using?

PHP 8.3

### Detailed description of the problem

I can select all images using Controll + A But cannot then deselect anything or just select only few of the imagesControl

### Steps to reproduce the issue

1) Open any album
2) Try to select multiple images

### Diagnostics [REQUIRED]

    Diagnostics
    -----------
    Warning: /v**********************lic/uploads/ has permissions 2775, but should have 2770
    Warning: /v**********************lic/uploads/tracks has permissions 2775, but should have 2770
    Warning: /v**********************lic/uploads/original has permissions 2775, but should have 2770
    Warning: /v**********************lic/uploads/original/82 has permissions 2775, but should have 2770
    Warning: /v**********************lic/uploads/original/82/2a has permissions 2775, but should have 2770
    Warning: 93 more directories with wrong permissions
    Warning: Dropbox import not working. dropbox_key is empty.
    Warning: lossless_optimization set to 1 but svgo not found!
    Info: Latest version of PHP is 8.3
    Warning: Default timezone not properly set; you might experience strange results when importing photos without explicit EXIF timezone
    Warning: Online updates are disabled by configuration

    System Information
    ------------------
    Lychee Version (tag):                    v5.2.0 (31a394b) -- Up to date (11 hours ago).
    DB Version:                              5.2.0
    
    composer install:                        --no-dev
    APP_ENV:                                 production
    APP_DEBUG:                               false
    APP_URL:                                 set
    APP_DIR:                                 default
    LOG_VIEWER_ENABLED:                      true
    LIVEWIRE_ENABLED:                        true
    
    System:                                  Linux
    PHP Version:                             8.2.7
    PHP User agent:                          Lychee/4 (https://lycheeorg.github.io/)
    Timezone:                                UTC
    Max uploaded file size:                  100M
    Max post size:                           100M
    Livewire chunk size:                     12.00 MB
    Max execution time:                      3600
    MySQL Version:                           10.11.7-MariaDB-1:10.11.7+maria~ubu2204
    
    exec() Available:                        yes
    Imagick Available:                       1
    Imagick Enabled:                         1
    Imagick Version:                         1691
    GD Version:                              2.3.3
    Number of foreign key:                   12 found.

### Browser & System [REQUIRED]

**Chrome: Version 123.0.6312.107 (Official Build) (arm64)
MacOS: Sonoma Version 14.4.1 (23E224) on M3**

### Please confirm (incomplete submissions will not be addressed)

- [X] I have provided easy and step-by-step instructions to reproduce the bug.
- [X] I understand my bug report will be removed if I haven't met the criteria above.</div>

For better tracking.

**Comment by jsaathof** [comment]
I am having issues selecting multiple issues with Lychee 5.2.2 (Docker image) on macOS Sonoma 14.4.1 with both Firefox 125.0.2 and Safari Version 17.4.1. Haven't tried Chrome. 

When selecting (or clicking) on a photo the larger version opens. I had partial lick with Safari Control-click on a photo but that opened a transparent menu. When clicking somewhere else (not on another photo or a button!) I could get the photo selected.

I encountered this when trying to move photos from the Unsorted album to an album I created. I used to use the "Import from server" but that now shows a message that I have to use `php artisan lychee:sync`.

**Comment by ildyria** [comment]
> When selecting (or clicking) on a photo the larger version opens. I had partial lick with Safari Control-click on a photo but that opened a transparent menu. When clicking somewhere else (not on another photo or a button!) I could get the photo selected.

Yes, I know and I haven't had time to dig into it... That is purely MacOs related (because of this stupid right click behaviour when doing control click).

> I encountered this when trying to move photos from the Unsorted album to an album I created. I used to use the "Import from server" but that now shows a message that I have to use php artisan lychee:sync.

Unrelated, maybe it will come back but that needs some refactoring in the backend...

**Comment by rikkoenig** [comment]
Confirmed seen (cannot select images other than ctl+a) in 
MacOS Sonoma 14.4.1, 
Firefox 125.0.3, 
Lychee 5.2.2. 

When using ctl+click on Safari 17.4.1 (19618.1.15.11.14), I get the pop-up menu, and the image is blue-border-selected. I can click outside the image and ctl+click others in this manner to multi-select images. I can then right-click to perform an action on all selected images.

FWIW, using non-Apple keyboard and mouse.

**Comment by ildyria** [comment]
Aimed to be fixed with v6.
