### ISSUE TITLE
[5.2.0] Maps on image detail is not updated when switching left right.

### ISSUE THREAD

**Issue by ildyria** [LycheeOrg/Lychee#2412]
### Discussed in https://github.com/LycheeOrg/Lychee/discussions/2406

<div type='discussions-op-text'>

<sup>Originally posted by **Colossus68** April 25, 2024</sup>
Hi, I'm new to Lychee. 
Maps in the detail block of a photo are not updated when moving directly from one image to the next (swipe, keyboard or next/previous button). All other image data is updated, including GPS values. Only when I return to the album first and then open the next image is the map also updated. I have tested all map providers. Is this behaviour intentional?</div>

**Comment by Colossus68** [comment]
The JS-functions displayMap() and displayOnMap() are not called when the image is changed. They are only triggered when the image is called up from the album.
