### ISSUE TITLE
#2392 recurring in Lychee 5.2.2 ("CC-BY-SA" is not a valid backing value for enum)

### ISSUE THREAD

**Issue by mniemela** [LycheeOrg/Lychee#2415]
### Discussed in https://github.com/LycheeOrg/Lychee/discussions/2414

<div type='discussions-op-text'>

<sup>Originally posted by **mniemela** April 28, 2024</sup>
### Lychee version

v5.2.2

### Which PHP version are you using?

PHP 8.2

### Detailed description of the problem

Issue #2392 is recurring in v5.2.2 with a slightly different old licence.

![image](https://github.com/LycheeOrg/Lychee/assets/7679721/66816da2-de63-48df-914e-d37681af9b43)

### Steps to reproduce the issue

Same as in issue #2392: 

1. Update from Lychee 4.12.0 to Lychee 5.2.2.
2. Go to a folder with old licence name, in this case "CC-BY-SA"
3. Error should be visible.

### Diagnostics [REQUIRED]

No errors in diagnostics.

### Browser & System [REQUIRED]

Windows 11 & Edge

### Please confirm (incomplete submissions will not be addressed)

- [X] I have provided easy and step-by-step instructions to reproduce the bug.
- [X] I understand my bug report will be removed if I haven't met the criteria above.</div>

**Comment by ildyria** [comment]
You didn't need to convert it to an issue...
Fix is on its way.
