### ISSUE TITLE
If you can read me, it means that you misconfigured Lychee.

### ISSUE THREAD

**Issue by sloniupl** [LycheeOrg/Lychee#2419]
I started receiving below notification on one of my galleries recently:

"If you can read me, it means that you misconfigured Lychee.
Please check that:

your APP_URL is properly set to the correct url.
For example: APP_URL=https://lychee.example.com
if you are working behind a reverse proxy, that TRUSTED_PROXIES is set to the forwarding ip.
For example: TRUSTED_PROXIES=*
Note that the wildcard value (*) is a very insecure option and not recommended.
if you are working behind an apache reverse proxy, that the forwarding headers are properly set.
For example: RequestHeader set X-Forwarded-Proto https is set.
if the CSP is blocking your assets because serving http, you need to force https.
This is done by setting APP_FORCE_HTTPS=true"

![image](https://github.com/LycheeOrg/Lychee-Docker/assets/5970551/6fb8586d-07b2-4143-8ea7-8a94a8c5d175)

I tried to check/change settings mentioned in this message but nothing changed.
I compared docker compose settings for this gallery with my other gallery that is still working and i don't see anything different.

Googling the problem didn't help as it searching a lot of other galleries with the same problem :)

Lychee Version: 5.1.2 (release)
Lychee Commit:  067ac87
https://github.com/LycheeOrg/Lychee/commit/067ac87d5aa8bd4d403fe77e9b0271b8acf789ae

**Comment by Tiritibambix** [comment]
Same problem here

**Comment by sloniupl** [comment]
Unfortunately i didn't found a solution and it is now happening on all of my Lyche instances. Is there anything we can do about it?

**Comment by SKR-974** [comment]
Same problem after updating version 4.11.0 at 5.3.0

**Comment by d7415** [comment]
I'm going to move this to the Lychee repo, as it doesn't look Docker-specific.

We will need more information to debug though. Particular examples:

- Are you hosting Lychee at a subpath?
- Have you tried connecting directly (without any reverse proxy)
- Is your APP_URL set correctly?

**Comment by sloniupl** [comment]
I'm hosting lychee as subdomain and also as a direct domain. 
Without reverse proxy it was showing up partially (interface was loading but no content etc) as the APP_URL was configured correctly for the domain that was in reverse proxy.

Don't know what changed recently but all my galleries are working again correctly.
I have auto-update enabled on my docker images so something changed and it's working correctly now :)

**Comment by SKR-974** [comment]
I can access the site only by being on the local network by using an address 192.168.x.x: 8080,
There he displays the presentation page correctly with my image in the background,
But when I entered the gallery, I only have black squares with the name of the photos,
And from the external address through the reverse proxy I have the message "If you can read me, it means that you misconfigured Lychee."

I have never encountered a problem with the old updates until the 4.11.0,
The problem occurred from 4.11.0 to 5.3.0,
