### ISSUE TITLE
Sharing - Select all users

### ISSUE THREAD

**Issue by igg55555** [LycheeOrg/Lychee#2452]
### Discussed in https://github.com/LycheeOrg/Lychee/discussions/2451

<div type='discussions-op-text'>

<sup>Originally posted by **igg55555** June  3, 2024</sup>
Please create an option to share with all users.  I am wanting all of my albums to be private, but available to all users.  I need to create 100+ users and will be adding more occasionally.  99 percent of these users will all be given the same permissions.

Having to go through every album and sub-album to share to a new user every time one is added would be incredibly cumbersome. </div>

**Comment by ildyria** [comment]
Please do not create issues from discussions.
