### ISSUE TITLE
[Enhancement] Counters for Number of Views

### ISSUE THREAD

**Issue by tobogdan** [LycheeOrg/Lychee#259]
As the title says, if it's possible to add a viewcount tracker for each item. 

On what I am hosting (on 4.0.0), we'd like to know how many times certain items were viewed, so having some tracking mechanism for it would be great.

**Comment by timo-reymann** [comment]
Would it be a possibility to allow users injecting javascript? This way it would be pretty simple to use tools like Matomo or Google Analytics to get exactly that.

If thats an option would also take a look implementing it and creating a PR.

Sounds similar to https://github.com/LycheeOrg/Lychee/issues/348#issue-498453161

**Comment by ildyria** [comment]
@timo-reymann the ability to inject JS is already implemented:
https://github.com/LycheeOrg/Lychee/pull/1697

**Comment by timo-reymann** [comment]
@ildyria Ah alrighty, didnt see that. Unfortunately the CSP is not allowing matomo code execution never the less :/

**Comment by ildyria** [comment]
You can fix that by changing this file: https://github.com/LycheeOrg/Lychee/blob/master/config/secure-headers.php
I think we would accept a Pull request providing an optional support for that.
