### ISSUE TITLE
Watch folder

### ISSUE THREAD

**Issue by alamparelli** [LycheeOrg/Lychee#291]
Dear, 
is there some planning to add a watching routine to import on backend new photos added in a specific folder?

Have a great day.

**Comment by ildyria** [comment]
related https://github.com/LycheeOrg/Lychee-Laravel/pull/237

**Comment by ildyria** [comment]
@d7415 where are you on that one ? :wink:

**Comment by d7415** [comment]
> @d7415 where are you on that one ? wink

Well now that the sync command exists...

```sh
man crontab
man systemd.timer
```
?

**Comment by ildyria** [comment]
So I guess we can close that one ? :D

**Comment by d7415** [comment]
Works for me. If I get time I might add an example to the documentation, but that's about as far as I was planning to take this. It's why I wanted the ability to run it from a shell.

**Comment by d7415** [comment]
Added to [FAQ](https://github.com/LycheeOrg/Lychee-Laravel/wiki/FAQ#can-i-set-up-lychee-to-watch-a-folder-for-new-images-and-automatically-add-them-to-albums)
