### ISSUE TITLE
[Enhancement] 2FA via Laravel

### ISSUE THREAD

**Issue by mannp** [LycheeOrg/Lychee#298]
*Explain in a few words which functionality or improvements you would like to see in Lychee.*

I recently installed your server app and am liking it very much, thank you.

I have it web facing with a fqdn and all is working fine via https.

Having my precious files protected by 2fa would put me more at ease though :)

InvoiceNinja use Laravel and implemented 2fa via its existing libraries (from memory)

I wondered if this was something you would consider adding?

Thanks for your consideration/

**Comment by ildyria** [comment]
I once hadded f2a with the Google authenticator to another laravel app so this is definitely feasible.

At the moment we are about 2,75 developers working on the project and we would like to finish packing up the v4 base functions before adding other extra.

Any help is always welcomed. 

⁣--

Kind regards

Benoît Viguier

sent from my phone.​

Le 5 juil. 2019 à 17:54, à 17:54, mannp <notifications@github.com> a écrit:

**Comment by mannp** [comment]
That's great news and thanks for the possibility at least :)

Happy to test but pascal was the last coding I did ;)

**Comment by ShapeShifter499** [comment]
I have to mention although I really can't help much, don't know enough programing yet. I would love to see Yubikey support.

**Comment by ildyria** [comment]
We now support the use of WebAuthn.
