### ISSUE TITLE
Photo anniversary notifications

### ISSUE THREAD

**Issue by fluxie38** [LycheeOrg/Lychee#323]
Hello,

Google photos has a feature which I really like. It scans your photos every day and when you have an album with the same date it sends you a message saying "today 5 years ago you were doing this" with a link to the album.

I have moved from Google to Lychee (for obvious reasons) and I was wondering whether such a feature exists or could be created.
Maybe with a RSS plugin ?

Any help or suggestions would be much appreciated.

**Comment by d7415** [comment]
This interests me, but there are a lot of implementation details. I wonder if an email might be appropriate, but we don't really use email in Lychee...

I've moved it here because we've stopped active development on v3, so it has a better chance of getting implemented here.

**Comment by fluxie38** [comment]
I was hoping that there was already a solution or something which we could build on.
I'm new to php and Lychee so I'm not likely to be very efficient or of much help.
I don't mind communicating further by mail if you think it is easier.

**Comment by fluxie38** [comment]
I have developed a solution with a bash shell script which calls MySQL to interrogate the Lychee database, a python script which filters the results and which then emails the name of and links to the albums found.
I'm sure there are more elegant ways of doing it but it works. 
I can document it and post it here if there's interest in it.

**Comment by ABLomas** [comment]
This is very nice feature and also can be extended in many ways.
How smart albums are created? If they can be created dynamically "when requested" then this should be easy - add folder "date-based searches", inside "photos this day", "photos this month", "photos you did 3 years ago" and so on. Going into this folder? Then simple SQL query would allow to get all photos matching criteria.
Sending email notifications is different task and probably harder to integrate (it requires some kind of cron job (web cron sucks), UI to enter lots of params), smart folders should be not so hard, no?

**Comment by ildyria** [comment]
We now have On this day smart album.
