### ISSUE TITLE
Import enhancements

### ISSUE THREAD

**Issue by d7415** [LycheeOrg/Lychee#371]
From #368.

> changing the behavior of duplicate photo detection, reporting the number of skipped duplicate entries to the user, etc is left for a future PR...

_Originally posted by @kamil4 in https://github.com/LycheeOrg/Lychee-Laravel/pull/368#issuecomment-541489036_

**Comment by ildyria** [comment]
@kamil4 what is the status of that one?

**Comment by kamil4** [comment]
#894 addresses the bulk of it.
