### ISSUE TITLE
How to +

### ISSUE THREAD

**Issue by JacquelinDV** [LycheeOrg/Lychee#425]
### Detailed description of the problem
*A clear and concise description of what the bug is.*

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
4. See error*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

### Output of the diagnostics
*(Settings => Diagnostics or https://example.com/Diagnostics )*

**Comment by JacquelinDV** [comment]
1. I have tried to chang the directory od "uploads" creating a symbolic link between te lycee pluin directory and an uploads directory on another disk:Mesae " Erreur API or server not found "
2. I have modified in the ".env" file wit the line "LYCHEE_UPLOADS" as LYCHEE_UPLOADS="/media/jacque/data/MesPhotos/uploads/", the result is the same!
Where is re documentation?

**Comment by d7415** [comment]
- Was it working before you moved it?
- Does the new location have the correct permissions?

In future, please fill in the issue template - it's there for a reason.

**Comment by JacquelinDV** [comment]
Yes Lychee i working before moving it and te new location ave the same permissions:
     - Owner: www-data:www-data
     : Right 775 and import 777.

An abstract of .env;

# folders in which the files will be stored
# LYCHEE_DIST="/var/www/html/Lychee-Laravel/public/dist/"
# LYCHEE_UPLOADS="/var/www/html/lychee/public/uploads/"
LYCHEE_UPLOADS="/media/jacquelin/data/MesPhotos/uploads/"

# url to access those files
# LYCHEE_DIST_URL="dist/"
# LYCHEE_UPLOADS_URL="uploads/"

When I use the line LYCHEE_UPLOADS="/var/www/html/lychee/public/uploads/" all is good, All the product possibilities are active an functional.
When I use the lineLYCHEE_UPLOADS="/media/jacquelin/data/MesPhotos/uploads/":
     - I can connect Lychee
    - I can use SETTINGS, USERS, SHARING
    - I can't use LOGS, DIAGNOSTIC: Server error or API not found
      I can run trough the structure of the "directories" of the pictures with rhe view of rhe directory picture but I can't see te pictures under: Server error or API not found
I think that the call of an image is not te same at the picture level and at the structure level! 
Bonne soirée

**Comment by nagmat84** [comment]
As this issue got stalled, I am closing it.
