### ISSUE TITLE
[Enhancement] User with read access cannot download albums

### ISSUE THREAD

**Issue by OmniTroid** [LycheeOrg/Lychee#438]
### Detailed description of the problem
When an album is shared with a user, they can't use the Download feature.

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Create a new user and album
2. Share the album with the user
3. Log in with the user
4. The function to download albums is not available (usually accessed through right-clicking the album)

Related to https://github.com/LycheeOrg/Lychee-Laravel/issues/437

**Comment by ildyria** [comment]
Thank you for reporting this. As the multiple user set up is not that heavily used, we did not expect that one.

**Comment by the-technat** [comment]
I'm affected of this issue too. We're using Lychee for our charity to publish photos to the public but also view them internally using a non-admin user. How hard would it be to fix this?

**Comment by ildyria** [comment]
> I'm affected of this issue too. We're using Lychee for our charity to publish photos to the public but also view them internally using a non-admin user. How hard would it be to fix this?

with #1403  it should be way easier

**Comment by kamil4** [comment]
Have you tried setting the `downloadable` flag in the advanced config to `1`? I believe it will do what you need. Read the documentation [here](https://lycheeorg.github.io/docs/settings.html#downloadable).

**Comment by the-technat** [comment]
Thanks @kamil4 for your hint! That actually solved the problem for me.

**Comment by kamil4** [comment]
I'm closing it as "Not an issue", though I added a "Documentation" tag as well. While the option _is_ documented, I agree that it's not easy to find.
