### ISSUE TITLE
[Enhancement] make image versions available

### ISSUE THREAD

**Issue by ezzra** [LycheeOrg/Lychee#441]
Depending on your workflow you sometimes might have different versions of a single image, for example when you try out different edit styles. Tools like digikam make it possible to save and access versions of your photos.

It would be great to have a possibility to save versions also within lychee. I could imagine for example, that you just see a small thin mark like a number or an icon in the overview. In the preview you could access the version by scrolling up and down. 

I see that this could be complicated for the backend structure, and it would be necessary to have it in mind for all the delete/move/copy etc. operations.

**Comment by d7415** [comment]
To me this feels like adding complexity. The only way I could see it reasonably working would be to group "versions" of the same image into a (sub)album for each image.

**Comment by ezzra** [comment]
> To me this feels like adding complexity

of course it is

**Comment by gardiol** [comment]
This is not the scope of Lychee i think.. This is web gallery of photos, not a photo storage / manage tool like digikam Lightbox or such

**Comment by ildyria** [comment]
Lychee is generating multiple sizes from the original image.
Sizes are configurable in settings.
