### ISSUE TITLE
[Enhancement] image processing queue

### ISSUE THREAD

**Issue by pchampio** [LycheeOrg/Lychee#443]
I'm using Lychee on a small instance, (only 2cores and 2go of ram). 
When uploading 70+ photos at the same time, the instance CPU/RAM goes ham, and some of the PHP requests are failing. This causes undesirably API request fails, which messes up the upload.

I thinks the issue is because too many concurrent *image processing* job are launch at once.
What I would love to have is a image processing queue that limits the number of concurrent job.
We would have in the UI another image uploading status, `Waiting for processing` that would add up to the current: `Failing`, `Processing`, ... https://github.com/LycheeOrg/Lychee-Laravel/blob/ce689ab60e6ab52aa65c1dc0d5ed3c2a7e87b402/app/Locale/English.php#L356-L391

And I think the implementation should be fairly simple, we would only need to add a FIFO queue to https://github.com/LycheeOrg/Lychee-Laravel/blob/bae5f2bbea823f5b0bfc154464dbf16e86ddb7db/app/ModelFunctions/PhotoFunctions.php#L597-L608

What do you think? 
Is this already implemented in another way?

---
BTW, awesome job girls&guys! :heart:

**Comment by ildyria** [comment]
To be honest, I don't really know how this limitation works. For me it feels like it is an Apache limitation, I know my server can handle up to 8 request at the same time. I never really dug further than that.

**Comment by pchampio** [comment]
Hum, I think this request is fixed in https://github.com/LycheeOrg/Lychee-Laravel/pull/336

**Comment by ildyria** [comment]
@pchampio No, this is different. **Upload != Import**

- Upload: from your computer = pictures are sent to the server
- Import: pictures are already on the server and imported via path.

**Comment by pchampio** [comment]
Ohh, thanks!

**Comment by d7415** [comment]
This should be fixed in #919.
