### ISSUE TITLE
Wrong rotation of photos when imported from server

### ISSUE THREAD

**Issue by Alcatr4zz** [LycheeOrg/Lychee#460]
### Detailed description of the problem
When importing a photo that was taken in landscape mode via "Import from Server" the photo is rotated upside down. This does not happen when uploading the same photo from the web interface. Note that I activated the import_via_symlink option, though I don't think this is related.

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Place the appended photo on the server (I put it into a zip file to make sure it is uploaded here as is). It was taken on an iPhone 6 btw.
2. Import the photo via "Import from Server".
3. Check that all generated photo sizes are upside down. When showing the original file from the web-interface, its orientation is correct though.

**Screenshots**
[img.zip](https://github.com/LycheeOrg/Lychee-Laravel/files/4396159/img.zip)
<img width="1278" alt="Bildschirmfoto 2020-03-27 um 23 19 44" src="https://user-images.githubusercontent.com/7276366/77805112-77ba1f80-7081-11ea-9d7b-0f72c8179208.png">

### Output of the diagnostics
    Diagnostics
    -----------
    Info: Latest version of PHP is 7.4
    Warning: Using 32 bit PHP, recommended upgrade to 64 bit
    Warning: Dropbox import not working. dropbox_key is empty.

    System Information
    ------------------
    Lychee-front Version:      3.2.16
    Lychee Version (git):      e1b7d30 (master) - Data not in Cache
    DB Version:                040000
    System:                    Linux
    PHP Version:               7.3
    MySQL Version:             10.3.22-MariaDB-0+deb10u1
    
    Lychee total space:        1.13 GB
    Upload folder space:       844.08 MB
    System total space:        116.97 GB
    System free space:         104.68 GB (89%)
    
    Imagick:                   1
    Imagick Active:            1
    Imagick Version:           1690
    GD Version:                2.2.5

    Config Information
    ------------------
    version:                   040000
    check_for_updates:         0
    sorting_Photos_col:        takestamp
    sorting_Photos_order:      ASC
    sorting_Albums_col:        max_takestamp
    sorting_Albums_order:      DESC
    imagick:                   1
    skip_duplicates:           1
    small_max_width:           0
    small_max_height:          360
    medium_max_width:          1920
    medium_max_height:         1080
    lang:                      de
    layout:                    2
    image_overlay:             0
    image_overlay_type:        desc
    default_license:           none
    compression_quality:       90
    full_photo:                1
    delete_imported:           0
    Mod_Frame:                 1
    Mod_Frame_refresh:         30
    thumb_2x:                  1
    small_2x:                  1
    medium_2x:                 1
    landing_page_enable:       0
    landing_owner:             John Smith
    landing_title:             John Smith
    landing_subtitle:          Cats, Dogs & Humans Photography
    landing_facebook:          https://www.facebook.com/JohnSmith
    landing_flickr:            https://www.flickr.com/JohnSmith
    landing_twitter:           https://www.twitter.com/JohnSmith
    landing_instagram:         https://instagram.com/JohnSmith
    landing_youtube:           https://www.youtube.com/JohnSmith
    landing_background:        dist/cat.jpg
    site_title:                Lychee
    site_copyright_enable:     0
    site_copyright_begin:      2019
    site_copyright_end:        2019
    additional_footer_text:    
    display_social_in_gallery: 0
    public_search:             0
    public_recent:             0
    recent_age:                1
    public_starred:            0
    downloadable:              1
    photos_wraparound:         1
    map_display:               1
    zip64:                     1
    map_display_public:        0
    map_provider:              Wikimedia
    force_32bit_ids:           0
    map_include_subalbums:     0
    update_check_every_days:   3
    has_exiftool:              0
    share_button_visible:      1
    import_via_symlink:        1
    has_ffmpeg:                1

### Browser and system
Tested on MacOS 10.14 in Safari. The server is a Raspberry Pi 4.

**Comment by coq-verif-tweetnacl** [comment]
Interesting one. :sweat_smile:

**Comment by ildyria** [comment]
hahaha. Nice bug :sweat_smile:

**Comment by ildyria** [comment]
Those are the two files that need to be modified:
https://github.com/LycheeOrg/Lychee-Laravel/blob/master/app/Image/GdHandler.php
https://github.com/LycheeOrg/Lychee-Laravel/blob/master/app/Image/ImagickHandler.php

**Comment by ildyria** [comment]
Weird. When I upload the pictures it does not pose a problem.

**Comment by ildyria** [comment]
Could not reproduce. :(

**Comment by d7415** [comment]
> Could not reproduce (even by following your steps exactly with the IMPORT from server and not upload). :(

Same.

**Comment by Alcatr4zz** [comment]
Strange... I'll further investigate this by starting with a fresh install. At least I can say it's not browser-dependent. Tested with Safari on MacOS and Chrome on Windows.

**Comment by Alcatr4zz** [comment]
Ok, I did a fresh install and I found the culprit. It is my very own import_via_symlink option. When turning it off, the photo is shown as it should be. When turning the option on the photo is imported upside down. The problem only occurs with my iPhone6 photos. The ones from my FujiFilm camera work fine.
I don't know where to even start debugging this, so I'll need your php-expert help ;-)

So the updated steps to reproduce this issue should look like this:
1. Place the appended photo on the server.
2. Turn on "import_via_symlink" in the advanced options.
3. Import the photo via "Import from Server".
4. Check that all generated photo sizes are upside down. When showing the original file from the web-interface, its orientation is correct though.

**Comment by Alcatr4zz** [comment]
I finally understood what's going on.

When using the import_via_symlink option we don't want the original files to be modified by Lychee. That's why I've forbidden write access to my photo folder for Lychee.

Now, the first step that Lychee does on import is to autorotate the photo, overwriting the original one. The photo is now correctly rotated. But obviously it's not when write access is forbidden. Instead the orientation information is still only located in the image's EXIF information. After autorotation the thumbnails and small/medium images are created. In the imagick implementation `stripImage` is responsible for removing the EXIF orientation flag. That means we're loosing our rotation information and the photo will be displayed with a wrong orientation. The same applies to the gd implementation, since `imagecreatefromjpeg` will throw away our EXIF too.

The most simple solution that came to my mind was to simply remove the autorotation and stripImage and to completely rely on the orientation EXIF that would now still be part of the image. Turns out that not all browsers support the orientation flag (of course it's Microsoft Edge...).

The solution I want to propose and that I will make a pull-request soon is the following:
* Do not autoRotate the original image when import_via_symlink is activated, since we don't want to touch it.
* When creating the smaller versions via `crop` or `scale` perform cropping/scaling based on the full original image, autorotate the small version and save it. For the use cases where the autorotation was already done on the original image this should come with almost zero additional performance costs.

Please tell me what you think. I already have a working version ready for both gd and imagick.

**Comment by d7415** [comment]
> I finally understood what's going on.

That makes sense and explains the issue.

> Turns out that not all browsers support the orientation flag (of course it's Microsoft Edge...).

I knew there'd be one...

> The solution I want to propose and that I will make a pull-request soon is the following:
> 
>     * Do not autoRotate the original image when import_via_symlink is activated, since we don't want to touch it.

I'm inclined to agree with this because I see that as the main usage, but I'm curious whether anyone has a differing opinion.

>     * When creating the smaller versions via `crop` or `scale` perform cropping/scaling based on the full original image, autorotate the small version and save it. For the use cases where the autorotation was already done on the original image this should come with almost zero additional performance costs.

So if I'm reading this right, the Imagick process is:
**current**: big -> stripImage -> crop/scale -> medium/small
**proposed**: big -> rotate -> stripImage -> crop/scale -> medium/small
?

**Comment by Alcatr4zz** [comment]
> **proposed**: big -> rotate -> stripImage -> crop/scale -> medium/small

Almost. Performance-wise it should be more effective to do the rotation after the scaling, so:
**proposed**: big -> crop/scale -> rotate -> stripImage -> medium/small

**Comment by d7415** [comment]
That makes sense. Unless you could temporarily store the rotated big image somewhere. That's probably not worth it though.

It seems a little wasteful, but there's a good reason behind it and the logic seems sound. If it's trivial to put it behind a `import_via_symlink` test that might be nice, but if not it doesn't sound like a lot of overhead.

I wouldn't merge such a thing without @ildyria's review though.
