### ISSUE TITLE
Remove tests from Lychee releases to reduce size

### ISSUE THREAD

**Issue by essembeh** [LycheeOrg/Lychee#481]
### Detailed description of the problem
Lychee-v3.2.16.zip was 583K, Lychee-v4.0.0.zip is 45M.
Taking a look to the zip content, some test files are present:
Lychee-v4.0.0/tests/Feature: 20,2 MiB
Lychee-v4.0.0/vendor/php-ffmpeg/php-ffmpeg/tests/files: 9,6 MiB

Maybe the build shouldn't contain these huge files?

**Comment by d7415** [comment]
One of the disadvantages of frameworks :( I agree that we probably don't need to include the tests in the release .zip though.

**Comment by ildyria** [comment]
@essembeh nicely spotted for the test files.

**Comment by d7415** [comment]
@essembeh Thanks!
