### ISSUE TITLE
[Enhancement] Display version

### ISSUE THREAD

**Issue by ildyria** [LycheeOrg/Lychee#485]
If one go to Diagnostic currently, this is what we see:
```
    System Information
    --------------
    Lychee-front Version:      4.0.0
    Lychee Version (git):      49d5862 (master) - Up to date (3 minutes ago).
    DB Version:                040001
    System:                    Linux
    PHP Version:               7.4
    MySQL Version:             10.3.22-MariaDB-1
    
    Imagick:                   1
    Imagick Active:            1
    Imagick Version:           1690
    GD Version:                2.2.5
```

The problem is when doing the update from the GUI the Lychee-front version is not correct anymore (even if up to date) because we do not update the sub module.

The second problem is in the case of the release, the Lychee-front version is not available.  
We should hide this (currently it is asking to do `git submodule init ; git submodule update`).

The third problem is in the case of the release, we should make the distincting between the version used as released (get the data from `version.md`) and the version used when using `git`.

**Comment by LudovicRousseau** [comment]
I just installed Lychee 4.0.1 from the .zip file and I have:
```System Information
    --------------
    Lychee-front Version:      -
    Lychee Version (git):      No git data found. Probably installed from release or could not read .git
```
This is not really helpful.

I also note that I still have version 4.0.0 (and not 4.0.1) if I select "À propos de Lychee" or in the login dialog.
