### ISSUE TITLE
[Enhancement] Document migration from 4.0.0 to 4.0.1

### ISSUE THREAD

**Issue by LudovicRousseau** [LycheeOrg/Lychee#486]
Yesterday I installed and migrated to Lychee 4.0.0 using the .zip file.
The .zip file created the directory `Lychee-v4.0.0`.
On disk I have:
```
Lychee -> Lychee-v4.0.0
Lychee-v4.0.0
```
I use a symbolic link from `Lychee` to `Lychee-v4.0.0`.

The .zip for version 4.0.1 created a new folder and I now have:
```
Lychee -> Lychee-v4.0.0
Lychee-v4.0.0
Lychee-v4.0.1
```
I can't just modify the symbolic link since the images are in `Lychee-v4.0.0/public/uploads/big/`, etc.
I need to copy/move them from `Lychee-v4.0.0/` to `Lychee-v4.0.1/`.

Can you provide a script to run to migrate from `Lychee-v4.0.0` to `Lychee-v4.0.1`?

En even better solution would be to have Lychee in two distinct directories:
- (static) code in `Lychee-v4.0.0/`
- images, configuration, logs, etc. in `Lychee-data/` or something similar.

One benefit is that www-data only need read access for `Lychee-v4.0.0/` and read-write access only for `Lychee-data/`.

**Comment by ildyria** [comment]
Interesting use case.
Also, there should be the possibility to change your upload folders, your can't you just use the `.env` ?

**Comment by LudovicRousseau** [comment]
Good idea.

Now I have in my `.env`:
```
LYCHEE_DIST="/var/www/Lychee-data/public/dist/"
LYCHEE_UPLOADS="/var/www/Lychee-data/public/uploads/"
```
And in the Apache2 `/etc/apache2/sites-available/lychee.conf` file
```
  Alias "/dist/" "/var/www/Lychee-data/public/dist/"
  Alias "/uploads/" "/var/www/Lychee-data/public/uploads/"
```
It works fine.

I then recreated the `Lychee-v4.0.1` from the .zip file. But I get the error:
```
[Sun Apr 19 16:13:15.013467 2020] [php7:error] [pid 13890] [client 2a01:e0a:c3:6d10:e8be:a4f8:325d:3bc3:52889] PHP Fatal error:  Uncaught ErrorException: file_put_contents(/home/rousseau/xxx/Lychee-v4.0.1/storage/framework/views/bb5ff9139363f512f2c3a5f6491234a43d1a6875.php): failed to open stream: Permission denied in /home/rousseau/xxx/Lychee-v4.0.1/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:133\nStack trace:\n#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'file_put_conten...', '/home/rousseau/...', 133, Array)\n#1 /home/rousseau/xxx/Lychee-v4.0.1/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(133): file_put_contents('/home/rousseau/...', '<?php $__env->s...', 0)\n#2 /home/rousseau/xxx/Lychee-v4.0.1/vendor/laravel/framework/src/Illuminate/View/Compilers/BladeCompiler.php(150): Illuminate\\Filesystem\\Filesystem->put('/home/rousseau/...', '<?php $__env->s...')\n#3 /home/rousseau/xxx/Lychee-v4.0.1/vendor/laravel/framework/src/Illuminate/V in /home/rousseau/xxx/Lychee-v4.0.1/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php on line 133
```
I used:
```
$ chmod g+w Lychee-v4.0.1/storage/framework/views
$ sudo chgrp www-data Lychee-v4.0.1/storage/framework/views
```
to give write access to www-data for the `Lychee-v4.0.1/storage/framework/views/` directory.
This time I have no error in the Apache2 logs but I have a HTML page "Error 500".

Upgrade to a newer version of Lychee will now be easier.
But it is unfortunate I still have to use: `sudo chown -R www-data Lychee-v4.0.1` and give write access to (too) many files.

**Comment by ildyria** [comment]
In theory you should just need to give write access to the `storage` part if I am not wrong.
Also storage contains also the `cache` and `sessions` folders which need write access.

If you get an error 500, by passing to `APP_DEBUG` to `true` you should get more details.

**Comment by LudovicRousseau** [comment]
Exact @ildyria 
I just did `sudo chown -R rousseau .` to reset the onwer of the files.
Then I did:
```
sudo chgrp www-data -R storage
chmod g+w -R storage
```
so that www-data (which is is the group www-data) has write access to all files in `storage/`.

Maybe you want to update the doc at https://github.com/LycheeOrg/Lychee/wiki/Install#3-set-storage-permissions-for-uploads and also the installation procedure at https://github.com/LycheeOrg/Lychee/releases/tag/v4.0.1

**Comment by LudovicRousseau** [comment]
With my split between Lychee itself and the pictures I have 2 directories:
- `Lychee` with the code of Lychee
- `Lychee-data` containing:
```
Lychee-data/
└── public
    ├── dist
    │   ├── fonts
    │   └── resources
    └── uploads
        ├── big
        ├── import
        ├── medium
        ├── raw
        ├── small
        └── thumb
```
- my `Lychee/.env` contains:
```
LYCHEE_DIST="/var/www/Lychee-data/public/dist/"
LYCHEE_UPLOADS="/var/www/Lychee-data/public/uploads/"
```

The upgrade script when a new version of Lychee is available is simple:
```
mv Lychee Lychee.old
unzip Lychee.zip
cp Lychee.old/.env Lychee
chmod g+w -R Lychee/storage
sudo chgrp www-data -R Lychee/storage
cd Lychee
php artisan key:generate
php artisan migrate
```
I just checked it works fine with the migration from 4.0.4 to 4.0.5 of Lychee.

The hierarchy `Lychee-data/public/` is writeable by the group www-data so that apache process can modify the files.
The files in `Lychee` are read only for apache. No write access needed.

**Comment by ildyria** [comment]
Niiiice :smiley:

**Comment by ildyria** [comment]
@LudovicRousseau can you add those information in the Wiki ? :+1:

**Comment by LudovicRousseau** [comment]
Editing the wiki was my initial plan.
I don't know _where_ to add this in the wiki. We already have 2 install pages:
* https://github.com/LycheeOrg/Lychee/wiki/Install
* https://github.com/LycheeOrg/Lychee/wiki/Install-Steps-on-Debian-Testing

I don't think we should create a **third** install page.

**Comment by d7415** [comment]
Yeah. I'd suggest maybe its own page - "Separating code and photos" or something? Either that or a FAQ, but it might be big for a FAQ. I guess you could do a page and link from FAQ?

**Comment by ildyria** [comment]
I still have plans to rewrite the install page of the FAQ (and merge them).

**Comment by ildyria** [comment]
@LudovicRousseau did quite a lot of rewrite here: https://lycheeorg.github.io/docs/ :smiley:

**Comment by ildyria** [comment]
added: https://lycheeorg.github.io/docs/distributions.html

**Comment by LudovicRousseau** [comment]
Thanks
