### ISSUE TITLE
Windows 10 installation?

### ISSUE THREAD

**Issue by maryandmike** [LycheeOrg/Lychee#487]
Yes, the title says it all.  We would really like to upgrade to v4.  Do you have instructions for Windows 10 IIS?

**Comment by ildyria** [comment]
https://stackoverflow.com/a/45464268/3981163
This should give you a head start.

**Comment by maryandmike** [comment]
Thx for that!  Now laravel is running.  One note, there is a typo in the instructions that is very important:  In the 'Create Laravel Project' section, 'cd c:/intepub'  should be 'cd c:/inetpub'
Thx again, now I will try Lychee install.

**Comment by maryandmike** [comment]
Now I have laravel running, but still can’t get lychee going. Any help would be appreciated.
...Ed

**Comment by ildyria** [comment]
So when you did 
`composer create-project laravel/laravel laravel "5.3.*"`  which created a `Laravel` folder
Instead that is where you should have done `git clone git@github.com:LycheeOrg/Lychee.git`

Laravel is not a dependency you need to install but the base framework on which we built the version 4, it included in the `vendor` folder. 

Once in the cloned `Lychee` folder, there you need to do `composer install --no-dev`.

If you like quicker interactions, feel free to drop by our gitter: https://gitter.im/LycheeOrg/Lobby :)

**Comment by maryandmike** [comment]
Oh!  I see.  Thx.  So, if I can get laravel running I should be able to get laravel-lychee running.  I have the old version 3 of lychee working fine.  Is there an installer for the new v4?  That would be nice.

**Comment by maryandmike** [comment]
Ok, this is what I get:

Lychee-installer

Php (version 7.3.0 required) 7.3.0
openssl
pdo
mbstring
tokenizer
JSON
exif
gd
Php exec() available
Next

Next screen is:
Lychee-installer
Please fix the errors before going to the next step.

. executable writable readable exists
storage/framework/ executable writable readable exists
storage/logs/ executable writable readable exists
bootstrap/cache/ executable writable readable exists
public/dist/ executable writable readable exists
public/img/ executable writable readable exists
public/sym/ executable writable readable exists
public/uploads/ executable writable readable exists
public/uploads/big/ executable writable readable exists
public/uploads/import/ executable writable readable exists
public/uploads/medium/ executable writable readable exists
public/uploads/raw/ executable writable readable exists
public/uploads/small/ executable writable readable exists
public/uploads/thumb/ executable writable readable exists
Re-check

What are the errors??

**Comment by ildyria** [comment]
Good new you found the installer. :smiley: 

For the second one, isn't there some red marks ?

**Comment by maryandmike** [comment]
No, everything is black.

**Comment by maryandmike** [comment]
I'm using the new MS-Edge browser.

**Comment by ildyria** [comment]
> No, everything is black.

That is not helping indeed.

**Comment by maryandmike** [comment]
ok, I'll try chrome

**Comment by ildyria** [comment]
![](https://raw.githubusercontent.com/LycheeOrg/Lychee/master/docs/images/install-5.png)

This is what you should see.

**Comment by maryandmike** [comment]
nope, same exact thing with chrome

**Comment by ildyria** [comment]
![](https://raw.githubusercontent.com/LycheeOrg/Lychee/master/docs/images/install-error.png) that is what you should get if there is an error.

```html
<span>public/uploads/small/</span>
<span class="perm float-right">
 <i class="fa fa-fw fa-exclamation-circle error"></i>
 executable</span>                    <span class="perm float-right">
 <i class="fa fa-fw fa-check-circle-o success"></i>
 writable</span>                    <span class="perm float-right">
 <i class="fa fa-fw fa-check-circle-o success"></i>
 readable</span>                    <span class="perm float-right">
 <i class="fa fa-fw fa-check-circle-o success"></i>
 exists</span>                    <li class="list__item list__item--permissions">
```
At least in the source code you can trace where the `error` are.

**Comment by maryandmike** [comment]
ok, so I took the source into my server, still couldn't get it to display.  Must be something wrong with the css.  I'll keep trying.

**Comment by ildyria** [comment]
Did you use the release zip or a git clone ? 

Thank you for continuing pushing. Because it also makes me find bugs.

**Comment by maryandmike** [comment]
Sorry for the long display.  Here is the source:


<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Lychee Installer</title>
        <link rel="icon" type="image/png" href="http://127.0.0.1:3317/installer/assets/img/favicon/favicon-16x16.png" sizes="16x16"/>
        <link rel="icon" type="image/png" href="http://127.0.0.1:3317/installer/assets/img/favicon/favicon-32x32.png" sizes="32x32"/>
        <link rel="icon" type="image/png" href="http://127.0.0.1:3317/installer/assets/img/favicon/favicon-96x96.png" sizes="96x96"/>
        <link href="http://127.0.0.1:3317/installer/assets/css/style.css" rel="stylesheet"/>
    </head>
    <body>
        <div class="master">
            <div class="box">
                <div class="header">
                    <h1 class="header__title">Lychee-installer</h1>
                </div>
                <ul class="step">
                    <li class="step__divider"></li>
                    <li class="step__item " title="Apply the database migration">
											<i class="step__icon fa fa-server" aria-hidden="true"></i>
										</li>
                    <li class="step__divider"></li>
					<li class="step__item " title="Setting the environment">
											<i class="step__icon fa fa-cog" aria-hidden="true"></i>
										</li>
                    <li class="step__divider"></li>
                    <li class="step__item     active
"  title="Checking Permissions">
										<a href="http://127.0.0.1:3317/install/perm"><i class="step__icon fa fa-key" aria-hidden="true"></i></a>
										</li>
                    <li class="step__divider"></li>
                    <li class="step__item " title="Checking Requirements">
											<a href="http://127.0.0.1:3317/install/req"><i class="step__icon fa fa-list" aria-hidden="true"></i></a>
										</li>
                    <li class="step__divider"></li>
                    <li class="step__item "  title="Welcome!">
					<a href="http://127.0.0.1:3317/install"><i class="step__icon fa fa-home" aria-hidden="true"></i></a>
					</li>
                    <li class="step__divider"></li>
                </ul>
                <div class="main">

								<p class="alert alert-danger text-center">
					<strong>Please fix the errors before going to the next step.</strong>
				</p>
				
				
    <ul class="list">
            <li class="list__item list__item--permissions">
        <span>.</span>
                    <span class="perm float-right">
    <i class="fa fa-fw fa-exclamation-circle error"></i>
 executable</span>                    <span class="perm float-right">
    <i class="fa fa-fw fa-check-circle-o success"></i>
 writable</span>                    <span class="perm float-right">
    <i class="fa fa-fw fa-check-circle-o success"></i>
 readable</span>                    <span class="perm float-right">
    <i class="fa fa-fw fa-check-circle-o success"></i>
exists</span>                    <li class="list__item list__item--permissions">
        <span>storage/framework/</span>
                    <span class="perm float-right">
    <i class="fa fa-fw fa-exclamation-circle error"></i>
 executable</span>                    <span class="perm float-right">
    <i class="fa fa-fw fa-check-circle-o success"></i>
 writable</span>                    <span class="perm float-right">
    <i class="fa fa-fw fa-check-circle-o success"></i>
 readable</span>                    <span class="perm float-right">
    <i class="fa fa-fw fa-check-circle-o success"></i>
exists</span>                    <li class="list__item list__item--permissions">
        <span>storage/logs/</span>
                    <span class="perm float-right">
    <i class="fa fa-fw fa-exclamation-circle error"></i>
 executable</span>                    <span class="perm float-right">
    <i class="fa fa-fw fa-check-circle-o success"></i>
 writable</span>                    <span class="perm float-right">
    <i class="fa fa-fw fa-check-circle-o success"></i>
 readable</span>                    <span class="perm float-right">
    <i class="fa fa-fw fa-check-circle-o success"></i>
exists</span>                    <li class="list__item list__item--permissions">
        <span>bootstrap/cache/</span>
                    <span class="perm float-right">
    <i class="fa fa-fw fa-exclamation-circle error"></i>
 executable</span>                    <span class="perm float-right">
    <i class="fa fa-fw fa-check-circle-o success"></i>
 writable</span>                    <span class="perm float-right">
    <i class="fa fa-fw fa-check-circle-o success"></i>
 readable</span>                    <span class="perm float-right">
    <i class="fa fa-fw fa-check-circle-o success"></i>
exists</span>                    <li class="list__item list__item--permissions">
        <span>public/dist/</span>
                    <span class="perm float-right">
    <i class="fa fa-fw fa-exclamation-circle error"></i>
 executable</span>                    <span class="perm float-right">
    <i class="fa fa-fw fa-check-circle-o success"></i>
 writable</span>                    <span class="perm float-right">
    <i class="fa fa-fw fa-check-circle-o success"></i>
 readable</span>                    <span class="perm float-right">
    <i class="fa fa-fw fa-check-circle-o success"></i>
exists</span>                    <li class="list__item list__item--permissions">
        <span>public/img/</span>
                    <span class="perm float-right">
    <i class="fa fa-fw fa-exclamation-circle error"></i>
 executable</span>                    <span class="perm float-right">
    <i class="fa fa-fw fa-check-circle-o success"></i>
 writable</span>                    <span class="perm float-right">
    <i class="fa fa-fw fa-check-circle-o success"></i>
 readable</span>                    <span class="perm float-right">
    <i class="fa fa-fw fa-check-circle-o success"></i>
exists</span>                    <li class="list__item list__item--permissions">
        <span>public/sym/</span>
                    <span class="perm float-right">
    <i class="fa fa-fw fa-exclamation-circle error"></i>
 executable</span>                    <span class="perm float-right">
    <i class="fa fa-fw fa-check-circle-o success"></i>
 writable</span>                    <span class="perm float-right">
    <i class="fa fa-fw fa-check-circle-o success"></i>
 readable</span>                    <span class="perm float-right">
    <i class="fa fa-fw fa-check-circle-o success"></i>
exists</span>                    <li class="list__item list__item--permissions">
        <span>public/uploads/</span>
                    <span class="perm float-right">
    <i class="fa fa-fw fa-exclamation-circle error"></i>
 executable</span>                    <span class="perm float-right">
    <i class="fa fa-fw fa-check-circle-o success"></i>
 writable</span>                    <span class="perm float-right">
    <i class="fa fa-fw fa-check-circle-o success"></i>
 readable</span>                    <span class="perm float-right">
    <i class="fa fa-fw fa-check-circle-o success"></i>
exists</span>                    <li class="list__item list__item--permissions">
        <span>public/uploads/big/</span>
                    <span class="perm float-right">
    <i class="fa fa-fw fa-exclamation-circle error"></i>
 executable</span>                    <span class="perm float-right">
    <i class="fa fa-fw fa-check-circle-o success"></i>
 writable</span>                    <span class="perm float-right">
    <i class="fa fa-fw fa-check-circle-o success"></i>
 readable</span>                    <span class="perm float-right">
    <i class="fa fa-fw fa-check-circle-o success"></i>
exists</span>                    <li class="list__item list__item--permissions">
        <span>public/uploads/import/</span>
                    <span class="perm float-right">
    <i class="fa fa-fw fa-exclamation-circle error"></i>
 executable</span>                    <span class="perm float-right">
    <i class="fa fa-fw fa-check-circle-o success"></i>
 writable</span>                    <span class="perm float-right">
    <i class="fa fa-fw fa-check-circle-o success"></i>
 readable</span>                    <span class="perm float-right">
    <i class="fa fa-fw fa-check-circle-o success"></i>
exists</span>                    <li class="list__item list__item--permissions">
        <span>public/uploads/medium/</span>
                    <span class="perm float-right">
    <i class="fa fa-fw fa-exclamation-circle error"></i>
 executable</span>                    <span class="perm float-right">
    <i class="fa fa-fw fa-check-circle-o success"></i>
 writable</span>                    <span class="perm float-right">
    <i class="fa fa-fw fa-check-circle-o success"></i>
 readable</span>                    <span class="perm float-right">
    <i class="fa fa-fw fa-check-circle-o success"></i>
exists</span>                    <li class="list__item list__item--permissions">
        <span>public/uploads/raw/</span>
                    <span class="perm float-right">
    <i class="fa fa-fw fa-exclamation-circle error"></i>
 executable</span>                    <span class="perm float-right">
    <i class="fa fa-fw fa-check-circle-o success"></i>
 writable</span>                    <span class="perm float-right">
    <i class="fa fa-fw fa-check-circle-o success"></i>
 readable</span>                    <span class="perm float-right">
    <i class="fa fa-fw fa-check-circle-o success"></i>
exists</span>                    <li class="list__item list__item--permissions">
        <span>public/uploads/small/</span>
                    <span class="perm float-right">
    <i class="fa fa-fw fa-exclamation-circle error"></i>
 executable</span>                    <span class="perm float-right">
    <i class="fa fa-fw fa-check-circle-o success"></i>
 writable</span>                    <span class="perm float-right">
    <i class="fa fa-fw fa-check-circle-o success"></i>
 readable</span>                    <span class="perm float-right">
    <i class="fa fa-fw fa-check-circle-o success"></i>
exists</span>                    <li class="list__item list__item--permissions">
        <span>public/uploads/thumb/</span>
                    <span class="perm float-right">
    <i class="fa fa-fw fa-exclamation-circle error"></i>
 executable</span>                    <span class="perm float-right">
    <i class="fa fa-fw fa-check-circle-o success"></i>
 writable</span>                    <span class="perm float-right">
    <i class="fa fa-fw fa-check-circle-o success"></i>
 readable</span>                    <span class="perm float-right">
    <i class="fa fa-fw fa-check-circle-o success"></i>
exists</span>                </ul>

        <div class="buttons">
        <a class="button" href="http://127.0.0.1:3317/install/perm">
            <i class="fa fa-refresh" aria-hidden="true" > Re-check</i>
        </a>
    </div>
    

			</div>
		</div>
	</div>
</body>
</html>

**Comment by maryandmike** [comment]
[source.txt](https://github.com/LycheeOrg/Lychee/files/4517228/source.txt)

**Comment by maryandmike** [comment]
I use the release zip, couldn't get the git clone to work, had access violation.

**Comment by maryandmike** [comment]
clone not close

**Comment by ildyria** [comment]
Okay I found a few bugs in the release sorrryyyy.

**Comment by maryandmike** [comment]
ok, I need to break for about 1 hr, will try then.

**Comment by ildyria** [comment]
Here is the latest build: https://github.com/LycheeOrg/Lychee/releases/tag/v4.0.2

Please try this one, this should hopefully solve some your issues...

> I use the release zip, couldn't get the git clone to work, had access violation.

My mistake, I assumed you used git with ssh credentials, the correct command should have been: `git clone https://github.com/LycheeOrg/Lychee`

**Comment by maryandmike** [comment]
ok, thx, I'll try again. Maybe us MS users can benefit from this.  You know, there are lots of MS users that would like to use Lychee.

**Comment by maryandmike** [comment]
Progress, but no success yet.  Now I can see the permissions issue.  All 14 are red-ex on executable.  I have tried every combination of permissions, but no luck.

**Comment by maryandmike** [comment]
Ok, progress, but no success yet.  Now I can see the permissions display, all 14 are red-ex on 'executable'.  I have tried every combination of permissions to no success.

**Comment by maryandmike** [comment]
I tried going the manual route, but this is what I get:

$ php artisan key:generate
In Compiler.php line 36:
  Please provide a valid cache path.

**Comment by ildyria** [comment]
O.O First time I see this error.

**Comment by ildyria** [comment]
See this: https://laracasts.com/discuss/channels/laravel/error-please-provide-a-valid-cache-path-please-help

**Comment by maryandmike** [comment]
ok, progress, no more compiler error and the migration looks like it worked.  Now what?

**Comment by ildyria** [comment]
Did you generate the key ?  `php artisan key:generate` 
If so you should be able to access it now. :)

**Comment by maryandmike** [comment]
Lychee installer is still stuck at permissions, all red-ex on 'executable'.

**Comment by maryandmike** [comment]
Yes, key:generate worked, when I try to access the website I get, error 500.

**Comment by ildyria** [comment]
edit your .env and set `APP_DEBUG` to true, it should give you an idea of what is going wrong.

Also if you did the migration, you should have a `installed.log` file at the root of your directory.
So you should now be able to remove the `.NO_SECURE_KEY` file (probably the reason why you are redirected to the install page).

**Comment by maryandmike** [comment]
ok, Do you want to get some sleep?  We can work on it tomorrow.

**Comment by ildyria** [comment]
It is still 20:46 here but I have Clan Battle on World of Warship in 15 minutes. I'll check if they need me. :laughing: 

EDIT: They don't need me yet.

**Comment by maryandmike** [comment]
Looks like an SQL issue.

**Comment by ildyria** [comment]
Surprising.

**Comment by maryandmike** [comment]
Error:
SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client (SQL: select * from information_schema.tables where table_schema = database/LLychee and table_name = configs and table_type = 'BASE TABLE')

**Comment by maryandmike** [comment]
Finally, success, had to put the entire db path in the .env file.  All is working now!

But the installer is still not working, stuck on red-ex 'executable'.

**Comment by ildyria** [comment]
Maybe a windows bug ? :s

**Comment by ildyria** [comment]
> Finally, success, had to put the entire db path in the .env file. All is working now!
> 
> But the installer is still not working, stuck on red-ex 'executable'.

Should be fixed. If you want to give it a try on master. @maryandmike 

Additionally, if you can write a quick guide of how to install Lychee on Windows that would be super nice. :)

**Comment by Fireballcz** [comment]
Successfully, long-term working Windows 10 Pro x64 (currently 20H2) installation and manual upgrades of Lychee v4 (now 4.2.2) on APACHE v.2.4 x64 (I hate IIS), PHP v.7.4.16 x64 

CLEAN INSTALL:
1) Install Apache, PHP, MariaDB and make sure everything is wokring (my docs folder is D:\www)
2) Install Composer, set PATH in Windows system variables to Composer
3) Install ffmepg Windows binaries (extract ffmpeg.exe + ffplay.exe somewhere, in my case D:\ffmpeg, set PATH in Windows system variables
4) Test ffmpeg functionality (visible response in command prompt when executing "ffmpeg", no matter where CMD opened)
5) Extract Lychee to your folder (D:\www\lychee)
6) Open command prompt as admin, cd to Lychee (D:\www\lychee), run "composer install" (no quotes)
7) Generate key by "php artisan key:generate" (no quotes)
8) Install Imagemagick, set PATH in Windows system variables 
9) Finished 
Try upload some images (check thumbs and midres images creation). If everything is OK, you should be able to upload also videos (check thumbs creation)

Get Composer here: https://getcomposer.org/download/ 

Additional helpful sources (usable without Xampp for which were written, a bit old, but in priciple OK):
https://bountify.co/xampp-ffmpeg-php
https://ourcodeworld.com/articles/read/349/how-to-install-and-enable-the-imagick-extension-in-xampp-for-windows

Note: Even if everything works OK, you may get this (not important) warning in php error log:
`Version warning: Imagick was compiled against ImageMagick version <some number> but version <some other number> is loaded. Imagick will run but may behave surprisingly in Unknown on line <some next another number>`
It happens, when your Imagemagick binaries are too different by their versions.

UPGRADE:
1) Make bulletproof backup uf your current installation, do not forget this, you had been warned!
2) Download the latest release of LL
3) Replace all existing files in Lychee dir (D:\www\lychee), except uploads/ and dist/user.css
4) Admin CMD to D:\www\lychee and execute "php artisan migrate" (no quotes)
5) Finished

2021-04-14
Upgrade note: the latest releases do not require point 4) during upgrade. If everything is OK, and previous Lychee version was also OK, then the first run, after manual upgrade, will help to migrate Lychee automatically thru web browser.

BTW: My last installation of LL is completely outside www docs folder, in D:\lychee and Lychee subfolder "public" is aliased in httpd.conf, to avoid recursive browsing or so, as follows:
```
<IfModule alias_module>
    Alias /lychee "D:/lychee/public"
    <Directory D:/lychee/public>
        Options All
        AllowOverride All
        Require all granted
    </Directory>
</IfModule>
```
Calling Lyche by "https://www.domain.com/lychee"

Im also forcing http to https by adding these few rows into `D:\lychee\public\.htaccess` :
```
# http -> https
RewriteCond %{HTTPS} off
RewriteRule .* https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
RewriteCond %{HTTP_HOST} !^www\. [NC]
RewriteRule .* https://www.%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
```
Of course, RewriteEngine must be On

**Comment by Schmunzel-ersatz** [comment]
I just tried to install lychee and got so far that the lychee install routine in the browser starts.
Sadly it shows all directories in red for execute while read and write is shown in green.
I use windows 10 with php 7.4.9 64bit thread safe and apache 2.4
I wonder how I would be able to get more information on what exactly fails.

Id appreciate every help

thks  in advance

Schmunzel

**Comment by ildyria** [comment]
Use the master version. I believe the version 4.0.6 is still "broken".
Cf comment a bit above: https://github.com/LycheeOrg/Lychee/issues/487#issuecomment-656241567

**Comment by Schmunzel-ersatz** [comment]
Got it 
thks for the prompt answer
regards
Stephan

    Am Sonntag, 30. August 2020, 21:33:15 MESZ hat Benoît Viguier <notifications@github.com> Folgendes geschrieben:  
 
 


Use the master version. I believe the version 4.0.6 is still "broken".
