### ISSUE TITLE
Class 'Migration' not found

### ISSUE THREAD

**Issue by LudovicRousseau** [LycheeOrg/Lychee#493]
### Detailed description of the problem
I try to migrate from 4.0.1 to 4.0.2

### Steps to reproduce the issue
1. unzip Lychee-v4.0.2.zip
1. cp Lychee-v4.0.1/.env Lychee-v4.0.2
1. cd Lychee-v4.0.2
2. php artisan key:generate -> no error
3. php artisan migrate

**Screenshots**
```
$ php artisan migrate

In 2020_04_22_155712_bump_version040002.php line 6:
                               
  Class 'Migration' not found  
```

### Output of the diagnostics
Unavailable since Lychee is not yet working correctly.

### Browser and system
Debian GNU/Linux
No browser involved at this step

**Comment by ildyria** [comment]
Already fixed. :)
https://github.com/LycheeOrg/Lychee/commit/9ded2e8d86ef491bcc14e3ccac9b3189759f807b

**Comment by ildyria** [comment]
Wait what.
