### ISSUE TITLE
No screen to set the admin login and password

### ISSUE THREAD

**Issue by Nordikk** [LycheeOrg/Lychee#494]
I followed the documentation, but there is no screen to set the admin login and password. 
All I get is the demo screen with John Smith's cat. I will attach a [screenshot.](https://imgur.com/a/dSRpLwb) (I would upload it to my site, but, you know  へ‿(ツ)‿ㄏ)

I've tried it with every version from 4.0.0 to 4.0.2, but it will just take me to the John Smith screen everytime. It is a beautiful cat tho.

**Comment by ildyria** [comment]
Did you click on Gallery in the top right? :)

**Comment by Nordikk** [comment]
Yes, the site is not found (404). I've cloned the git repo and also tried it with the zip version, but either versions won't work.

**Comment by ildyria** [comment]
> Yes, the site is not found (404). I've cloned the git repo and also tried it with the zip version, but either versions won't work.

Okay, that is more worry some because this is where you should have the admin request etc. :thinking:

**Comment by Nordikk** [comment]
Do you need some additional info? I've tried it over and over, everytime the gallery was not found.

**Comment by ildyria** [comment]
how did you do the install ? via the command line (composer, migrations...) or directly from the website ?
Did you see something like that:
![](https://raw.githubusercontent.com/LycheeOrg/Lychee/master/docs/images/install-3.png)

**Comment by Nordikk** [comment]
I did that via command line, the installer also won't show for me.

**Comment by ildyria** [comment]
Installer will only show if `.env` does not exists and if the `config` table is not present (migration not done).

**Comment by Nordikk** [comment]
I've tried that now, now it show's a 404 for the install page

https://imgur.com/a/2RAM51t

**Comment by ildyria** [comment]
GRBLLLLL Raaaa it works then it does not anymore. What is wrong. >_<

Sorry.

**Comment by Nordikk** [comment]
I've tried the migration from v3 to v4 beforehand, but it didn't work either, so I tried a fresh install and I'm constantly wondering what I am doing wrong :D

**Comment by ildyria** [comment]
Okay for some reason I can reproduce your bug and the worst part is I don't understand where it comes from...

My server has been running Lychee v4 for 2 years without any problem. I don't get it.

**Comment by ildyria** [comment]
Once you have done your migration and the key generation in command line, you should be able to do:
` php artisan lychee:diagnostics`

**Comment by Nordikk** [comment]
Here's the output from the diagnostics:
https://pastebin.com/y6HS5xti

**Comment by ildyria** [comment]
Thanks. I'm actively looking at it. This is super surprising.

**Comment by Nordikk** [comment]
Quick notation: The diagnostics is showing php version 7.4, because it was installed with the latest dist-upgrade, but it's not active. I'm using php 7.3.

**Comment by ildyria** [comment]
gotcha but this should not be of matter :)

**Comment by ildyria** [comment]
What really does not make sens is that the full build is passing.

**Comment by ildyria** [comment]
Found it. @Nordikk please check that apache2 (or whatever engine you use)  allows htaccess override for rewrite.

**Comment by Nordikk** [comment]
Will check it, wait a second.

Works. Thank you so much. :) 

![image](https://user-images.githubusercontent.com/48895515/80019702-367a2b80-84d8-11ea-92af-6c0479410792.png)

**Comment by ildyria** [comment]
HELL YEAH! :sunglasses:

**Comment by Nordikk** [comment]
What's the matter with the frontpage with John Smith's photos? Can you disable it somehow?

I could just redirect my vhost to /public/gallery, just wondering.

**Comment by ildyria** [comment]
Sure, just go to advance Settings (More at the bottom of the Setting page) and disable the landing page. :)

**Comment by ildyria** [comment]
Now that you figured out why it does not work, I highly suggest you to try the migration with from a Lychee v3 installation. :) That way you will not have to reupload everything.

**Comment by Nordikk** [comment]
Maybe I've deleted my v3, just maybe. :D 

Other question: can I disable the copyright notice on the footer?

edit: nevermind, found it ^^
