### ISSUE TITLE
Incorrect documentation for https://github.com/LycheeOrg/Lychee/releases/tag/v4.0.2

### ISSUE THREAD

**Issue by LudovicRousseau** [LycheeOrg/Lychee#497]
### Detailed description of the problem

The installation procedure indicates:

> Packaged version of Lychee including the vendor folder.
> Install process is as follow:
> 
> - extract the zip file.
> - create your database and user manually
> - sudo chown -R www-data:www-data .
> 
> From that point you can access from your browser the Lychee installation and follow the installation steps or you can do the steps:
> 
> - cp .env.example .env
> - edit .env
> - php artisan key:generate
> - php artisan migrate
> - sudo chown -R www-data:www-data *

The problem is that you can't modify any file after the first "sudo chown". The files now belongs to www-data and can't be modified by the user.

The real process is:
- extract the zip file.
- create your database and user manually
- cp .env.example .env
- edit .env
- php artisan key:generate
- php artisan migrate
- sudo chown -R www-data:www-data *

The "chown" should even be restricted to only the 3 directories:

- storage/
- public/uploads/
- public/dist/

But that is another story.

**Comment by ildyria** [comment]
Well we still need write access on `.`for the `installed.log` (and `.env` when using the online installer).
Additionally it is also needed in the case of the `.NO_SECURE_KEY`.

While in the case of `installed.log` and `.NO_SECURE_KEY` we can move them to storage, we still need to be able to write in `.` for `.env`

**Comment by LudovicRousseau** [comment]
My proposed documentation is when you do NOT configure Lychee using the web interface.
It can be used when you migrate from a previous version of Lychee and you reuse the `.env` file.

In fact we have 3 installation cases:
1. new install and configuration with the web interface
1. new install and configuration by editing the `.env` file by hand
1. migration from a previous version of Lychee 4

Maybe the case 3 should be documented at https://github.com/LycheeOrg/Lychee/wiki/Update#update-manually

I will try to improve the wiki page.
