### ISSUE TITLE
Issues running `php artisan migrate`

### ISSUE THREAD

**Issue by unindented** [LycheeOrg/Lychee#501]
### Detailed description of the problem

I'm following the steps to upgrade from 3.x to 4.0.2. When I get to running `php artisan migrate`, I see the following errors:

```
$ php artisan migrate

In Connection.php line 670:
  SQLSTATE[HY000] [1045] Access denied for user 'unindentedphotos'@'brockway.dreamhost.com' (using password: NO) (SQL: select * from information_schema.tables where table_schema = un
  indentedphotos and table_name = migrations and table_type = 'BASE TABLE')

In PDOConnection.php line 31:
  SQLSTATE[HY000] [1045] Access denied for user 'unindentedphotos'@'brockway.dreamhost.com' (using password: NO)

In PDOConnection.php line 27:
  SQLSTATE[HY000] [1045] Access denied for user 'unindentedphotos'@'brockway.dreamhost.com' (using password: NO)
```

Database user matches what I configured in `.env`, but database host doesn't. It also says it didn't use a password, even though I configured one... My `.env` looks like this:

```
DB_CONNECTION=mysql
DB_HOST=mysql.unindented.org
DB_PORT=3306
DB_DATABASE=unindentedphotos
DB_USERNAME=unindentedphotos
DB_PASSWORD=XXXXXXXXXXXX
DB_LOG_SQL=false
```

### Steps to reproduce the issue

1. Configure the database to be on a remote host.
2. Run `php artisan migrate`.

**Screenshots**

<img width="1680" alt="Screen Shot 2020-04-23 at 4 30 12 PM" src="https://user-images.githubusercontent.com/69485/80159395-ba3b2300-857f-11ea-8e22-247583bbfb62.png">

### Output of the diagnostics

N/A

### Browser and system

Lychee commit #096213d
PHP 7.3.12
Composer 1.10.5

**Comment by ildyria** [comment]
That is very weird.

Can you try to edit `config/database.php` around lines 43-56 to see if that helps? i.e. force the parameters.

**Comment by d7415** [comment]
> Database user matches what I configured in `.env`, but database host doesn't.

I think the host in the error will be your Lychee hostname? The error comes from the server, and is authenticating you as user@host.

> It also says it didn't use a password, even though I configured one... My `.env` looks like this:

That one's weird. Was your Lychee v3 also set up with the same remote mysql server? What version of mysql/mariadb is the DB server using?

**Comment by unindented** [comment]
> I think the host in the error will be your Lychee hostname?

Correct.

> Was your Lychee v3 also set up with the same remote mysql server?

Yup, same Lychee host, same database host, same database username and password.

> What version of mysql/mariadb is the DB server using?

mysql Ver 14.14 Distrib 5.7.29

**Comment by ildyria** [comment]
Can you try this : https://stackoverflow.com/a/56461181/3981163 ?

**Comment by unindented** [comment]
Same errors after running that command...

**Comment by d7415** [comment]
I'm running out of ideas. Is there anything logged at the server end?

**Comment by unindented** [comment]
When I run the command from the CLI, the only errors I see are the ones I posted. When I go through the installation wizard on a browser, the step that's supposed to run the migrations just redirects me back to the first step.

**Comment by unindented** [comment]
The only way to set `DB_HOST` is through the `.env` file, right? There's nothing else that could be interfering here?

**Comment by d7415** [comment]
Sorry, I meant the database server.

**Comment by ildyria** [comment]
> The only way to set `DB_HOST` is through the `.env` file, right? There's nothing else that could be interfering here?

Well, you could try to use https://github.com/LycheeOrg/Lychee/blob/master/config/database.php
to force the values.

**Comment by unindented** [comment]
@ildyria yeah, I did that too, but had no effect.

**Comment by unindented** [comment]
@d7415 I don't have access to the server logs, it's a managed MySQL installation.

**Comment by ildyria** [comment]
@unindented would you give a shot to SQLite3 ? it is supported by the v4 and may be an okay alternative for you. See here some arguments: https://www.sqlite.org/whentouse.html

**Comment by unindented** [comment]
@ildyria ah, that's a great idea actually! I don't need a remote database at all! Let me try.

**Comment by unindented** [comment]
Using `DB_CONNECTION=sqlite` allowed the installer to move forward and finish successfully. However, after installation finishes, accessing the root redirects me to the installer again...

<img width="1043" alt="Screen Shot 2020-05-09 at 5 51 49 PM" src="https://user-images.githubusercontent.com/69485/81488454-e14f5100-921d-11ea-9b72-172f8dc9c8de.png">

**Comment by ildyria** [comment]
Okay, that one is surprising. Let me try this on my side.

EDIT: worked super fine.

**Comment by ildyria** [comment]
@unindented can you check:

- that you have an `installed.log` file at the root of Lychee.
- that you DO NOT have a `.NO_SECURE_KEY` file at the root of Lychee.
- that the field `APP_KEY` is not empty in your `.env` file.

**Comment by unindented** [comment]
Once the installer finishes, all those things are true:
- I have an `installed.log`
- I do not have a `.NO_SECURE_KEY`
- `APP_KEY` is set

However if I then try to access the root of the app, the installer shows up again, and:
- `installed.log` disappears
- `.NO_SECURE_KEY` appears
- `APP_KEY` remains as it was

**Comment by ildyria** [comment]
> `.NO_SECURE_KEY` appears

VERY WEIRD.

Because this means that the https://github.com/LycheeOrg/Lychee/blob/master/app/Exceptions/Handlers/NoEncryptionKey.php is triggered

**Comment by unindented** [comment]
`storage/logs/laravel.log` shows the following error after the installer completes successfully (not  sure if that's expected):

```
[2020-05-10 15:53:29] production.ERROR: No application encryption key has been specified. {"exception":"[object] (RuntimeException(code: 0): No application encryption key has been specified. at /home/user/my-site/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:44)
[stacktrace]
#0 /home/user/my-site/vendor/laravel/framework/src/Illuminate/Support/helpers.php(422): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}('')
#1 /home/user/my-site/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(48): tap('', Object(Closure))
#2 /home/user/my-site/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(24): Illuminate\\Encryption\\EncryptionServiceProvider->key(Array)
#3 /home/user/my-site/vendor/laravel/framework/src/Illuminate/Container/Container.php(803): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}(Object(Illuminate\\Foundation\\Application), Array)
#4 /home/user/my-site/vendor/laravel/framework/src/Illuminate/Container/Container.php(685): Illuminate\\Container\\Container->build(Object(Closure))
#5 /home/user/my-site/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(794): Illuminate\\Container\\Container->resolve('encrypter', Array, true)
#6 /home/user/my-site/vendor/laravel/framework/src/Illuminate/Container/Container.php(633): Illuminate\\Foundation\\Application->resolve('encrypter', Array)
#7 /home/user/my-site/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(779): Illuminate\\Container\\Container->make('encrypter', Array)
#8 /home/user/my-site/vendor/laravel/framework/src/Illuminate/Container/Container.php(949): Illuminate\\Foundation\\Application->make('encrypter')
#9 /home/user/my-site/vendor/laravel/framework/src/Illuminate/Container/Container.php(877): Illuminate\\Container\\Container->resolveClass(Object(ReflectionParameter))
#10 /home/user/my-site/vendor/laravel/framework/src/Illuminate/Container/Container.php(838): Illuminate\\Container\\Container->resolveDependencies(Array)
#11 /home/user/my-site/vendor/laravel/framework/src/Illuminate/Container/Container.php(685): Illuminate\\Container\\Container->build('App\\\\Http\\\\Middle...')
#12 /home/user/my-site/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(794): Illuminate\\Container\\Container->resolve('App\\\\Http\\\\Middle...', Array, true)
#13 /home/user/my-site/vendor/laravel/framework/src/Illuminate/Container/Container.php(633): Illuminate\\Foundation\\Application->resolve('App\\\\Http\\\\Middle...', Array)
#14 /home/user/my-site/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(779): Illuminate\\Container\\Container->make('App\\\\Http\\\\Middle...', Array)
#15 /home/user/my-site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(204): Illuminate\\Foundation\\Application->make('App\\\\Http\\\\Middle...')
#16 /home/user/my-site/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(178): Illuminate\\Foundation\\Http\\Kernel->terminateMiddleware(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\RedirectResponse))
#17 /home/user/my-site/public/index.php(58): Illuminate\\Foundation\\Http\\Kernel->terminate(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\RedirectResponse))
#18 {main}
"}
```

**Comment by unindented** [comment]
This is what `.env` looks like after installation finishes:

```
APP_NAME=Photos
APP_ENV=local
APP_KEY=base64:<base64 key>
APP_DEBUG=true
APP_URL=https://<app url>

LOG_CHANNEL=stack

DB_CONNECTION=sqlite

TIMEZONE=UTC
```

**Comment by ildyria** [comment]
As it should. >_<

**Comment by ildyria** [comment]
Wait it is saying `[2020-05-10 15:53:29] production.ERROR` instead of `[2020-05-10 15:53:29] local.ERROR`. Which means it does not read the `.env`

**Comment by ildyria** [comment]
You could try this: https://laracasts.com/discuss/channels/requests/no-supported-encrypter-found?page=1#reply=150113
I'm still really surprised but I think this is also related to your first issue where it was not pulling the data from your `.env`.

**Comment by ildyria** [comment]
Can you have a look at this too: https://laracasts.com/discuss/channels/laravel/laravel-not-reading-env-file-in-homestead?page=1#reply=358414

**Comment by ildyria** [comment]
No answers. Issue seems dead.
