### ISSUE TITLE
SQLite DB - DB does not exist

### ISSUE THREAD

**Issue by palitu** [LycheeOrg/Lychee#503]
### Detailed description of the problem
when starting using docker and setting the env `DB_CONNECTION=sqlite` lychee  wont start, giving the following error:

```
lychee_laravel | In Connection.php line 669:
lychee_laravel |                                                                       
lychee_laravel |   Database (lychee) does not exist. (SQL: PRAGMA foreign_keys = ON;)  
lychee_laravel |                                                                       
lychee_laravel | 
lychee_laravel | In SQLiteConnector.php line 34:
lychee_laravel |                                      
lychee_laravel |   Database (lychee) does not exist.  
lychee_laravel |                                      
lychee_laravel | 
```

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. using the default docker-compose.yml, remove the sections for mysql, change the DB_CONNECTION to sqlite
2. `docker-compose up
3. startup completes, with the errors "Database (lychee) does not exist. (SQL: PRAGMA foreign_keys = ON;)` and `Database (lychee) does not exist`
4. 

**Screenshots**
N/A

### Output of the diagnostics
N/A

### Browser and system
Ubuntu 18.04, Docker and Compose. image `lycheeorg/lychee-laravel`

**Comment by d7415** [comment]
Hi,

Did you create the sqlite database first?

**Comment by ildyria** [comment]
Considering migrating this to https://github.com/LycheeOrg/Lychee-Laravel-Docker

**Comment by ildyria** [comment]
added test: https://github.com/LycheeOrg/Lychee/pull/506

**Comment by palitu** [comment]
> Hi,
> 
> Did you create the sqlite database first?

@d7415 - no i tried to find the location of where it needs to be created, but a quick search through the source did not give me the answer.  i found here:

`'database' => env('DB_DATABASE', database_path('database.sqlite')),` but couldnt find where database_path is defined.  and then once that is defined i can mount the volume locally.


@ildyria - if you suggest i should, no worries.  that being said it is probably worth documenting some of the basics to installing with SQLite.  especially the location a the command for creating a sqlite DB.

let me know if i should move this

thanks for your help.

**Comment by d7415** [comment]
> @d7415

That would be your first problem.

> i found here:

Where?

> `'database' => env('DB_DATABASE', database_path('database.sqlite')),` but couldnt find where database_path is defined. and then once that is defined i can mount the volume locally.

Did you try `DB_DATABASE=/path/to/your/db.sqlite`? If that fails, try with `"quotes"` like the other strings.

> it is probably worth documenting some of the basics to installing with SQLite

I'm not opposed to this, but the readme does (currently) say "To run Lychee, everything you need is a web-server with PHP 7.3 or later and a MySQL-Database"

**Comment by ildyria** [comment]
> Did you try `DB_DATABASE=/path/to/your/db.sqlite`? If that fails, try with `"quotes"` like the other strings.

Actually, I found out by adding sqlite support to travis that you just need to do:

`touch database/database.sqlite;`

to create the database: https://github.com/LycheeOrg/Lychee/blob/master/.travis.yml#L63

here is the `.env` I used: https://github.com/LycheeOrg/Lychee/blob/master/.env.sqlite.travis

**Comment by palitu** [comment]
> not really a coder, just a keen "fiddler".  thanks

That's how most of us start!
