### ISSUE TITLE
No screen to set the admin login and password the return

### ISSUE THREAD

**Issue by mingus52** [LycheeOrg/Lychee#504]
### Detailed description of the problem
I've a similar issue to "Nordikk"

I can't use the web installer, and i don't understand why ! The page is not found

And when i'm installing lychee in cli ; i've the same error "Nordikk" had >> No screen to set the admin login and password

### What i've done

-Installing all the requirements
-Activate Apache Mods (rewrite and ssl)
-Launch with www-data the command "composer install --no-dev"

### Browser and system
Firefox 68.7.0esr on Debian Buster

**Comment by mingus52** [comment]
I forgot to add the code above in my vhost configuration file 
```
<Directory /var/www/lychee>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
</Directory>
```

**Comment by mingus52** [comment]
This resolved the problem i'had.

Sorry for the inconvenience

**Comment by d7415** [comment]
Thanks for posting the solution - Hopefully it will help someone else!

**Comment by ildyria** [comment]
Related: https://github.com/LycheeOrg/Lychee/wiki/I-have-an-Error-404-when-I-open--gallery,-what-can-I-do%3F :)
