### ISSUE TITLE
skinny documentation

### ISSUE THREAD

**Issue by fl1tz** [LycheeOrg/Lychee#505]
### Detailed description of the problem
The documentation doesn't work for me. I don't know which steps or lines of thought are missing. I give up - after half a night of fumbling. I can neither update nor get the new software to run.
Too bad. Up to version 3.1.6, Lychee was fine software. Thanks for that.

**Comment by d7415** [comment]
Hi. Thanks for using Lychee! If you let us know where it failed we might be able to help you debug.complete the process, or fix a bug or gap in the documentation.

**Comment by ildyria** [comment]
Are you using Apache or Nginx ?

**Comment by fl1tz** [comment]
Thanks for your answers. yesterday I was too frustrated and too tired to describe my mistakes
I installed Lychee on a hoster. I'm assuming Apache2. I have successfully carried out the following steps:
* git clone https://www.github.com/LycheeOrg/Lychee lychee 
_lychee installed on the webspace_
* cd lychee	   											 
 _changed to the directory_
* composer install --no-dev								 
_package manager installed_
* sudo chgrp www-data -R storage public/dist public/sym public/uploads 
sudo chmod -R 775 storage/* app/* public/dist public/sym public/uploads bootstrap/
sudo chmod 775 .
_the storage permissions for uploads_
....................						
* then I downloaded the .env and .... don't know, I just added the access data to the database data; and I don't know -> should I register a user in the database beforehand? Yes No? should there be further changes in the .env? should i make lychee / public root? if yes how? ...

* the next step was no longer working
* I called up lychee in the browser with the path (no idea where is the installer?)  ... / lychee / public
* .... error ... no call of the page
I've tried everything possible; after half a night it had enough
I'm probably too stupid for that

**Comment by d7415** [comment]
> Thanks for your answers. yesterday I was too frustrated and too tired to describe my mistakes

I know that feeling...

>     * then I downloaded the .env and .... don't know, I just added the access data to the database data; and I don't know -> should I register a user in the database beforehand? Yes No? should there be further changes in the .env? should i make lychee / public root? if yes how? ...

The database needs to be created, but it will sort the tables out for you. The DB settings are the main purpose, though while debugging you may wish to set `APP_DEBUG=true`. That's best turned off once everything's working though.

The root should be the `public` folder.

>     * I called up lychee in the browser with the path (no idea where is the installer?)  ... / lychee / public

~~The installer won't run if there's a `.env` file. We should clear that up in the docs - the installer is newer than the documentation!~~ Corrected by @ildyria below!

The installer isn't essential - if you follow the steps on the install page you should be covered.

Thanks - this is already showing some gaps in the docs!

**Comment by ildyria** [comment]
> Thanks for your answers. yesterday I was too frustrated and too tired to describe my mistakes
> I installed Lychee on a hoster. I'm assuming Apache2. I have successfully carried out the following steps:
> 
> * git clone https://www.github.com/LycheeOrg/Lychee lychee
>   _lychee installed on the webspace_

:heavy_check_mark:
> * cd lychee
>   _changed to the directory_

:heavy_check_mark:
> * composer install --no-dev
>   _package manager installed_

:heavy_check_mark:

> * sudo chgrp www-data -R storage public/dist public/sym public/uploads
>   sudo chmod -R 775 storage/* app/* public/dist public/sym public/uploads bootstrap/
>   sudo chmod 775 .
>   _the storage permissions for uploads_

:heavy_check_mark:

> * then I downloaded the .env and .... don't know, I just added the access data to the database data; and I don't know -> should I register a user in the database beforehand? Yes No? should there be further changes in the .env? should i make lychee / public root? if yes how? ...

In the `.env` you can set up the login info to the database. That can be the same info as the previous Lychee database, during the migration Lychee v4 will take care of porting the database.

> * the next step was no longer working
> * I called up lychee in the browser with the path (no idea where is the installer?)  ... `/lychee/public`

:heavy_check_mark:

> * .... error ... no call of the page
>   I've tried everything possible; after half a night it had enough
>   ~I'm probably too stupid for that~

Naaaah, it also took me quite a long time to figure out what I forgot : #494
And someone else had the similar one: #504

https://github.com/LycheeOrg/Lychee/wiki/I-have-an-Error-404-when-I-open--gallery,-what-can-I-do%3F

**Comment by ildyria** [comment]
> The installer won't run if there's a `.env` file. We should clear that up in the docs - the installer is newer than the documentation!

Wrong. The installer will be called if one of those conditions is true:
- no access to the database
- the secure key is not set (via e.g. `php artisan key:generate`)
- the Config table does not exists in the database (if access is given)

> The installer isn't essential - if you follow the steps on the install page you should be covered.

True.

**Comment by fl1tz** [comment]
Many thanks and special thanks to @ildyria for your encouragement. This is a lot of stuff. I can imagine that this can help: 'It should allow .htaccess override'. But I can only test that tomorrow. I wish you a happy evening!

**Comment by ildyria** [comment]
Fixed.

**Comment by fl1tz** [comment]
sorry that it took a while. I have a new job. - I have a shared hoster and cannot install the composer.
I get this: ...
`../vendor/autoload.php not found.
Please do: composer install --no-dev --prefer-dist`

**Comment by ildyria** [comment]
maybe you should use the release then: https://github.com/LycheeOrg/Lychee/releases/tag/v4.0.4 which provides you with the vendor files.

**Comment by fl1tz** [comment]
Thanks a lot. I am currently using this version.

**Comment by fl1tz** [comment]
![vendor](https://user-images.githubusercontent.com/37076834/81694255-68403b80-9461-11ea-996d-d36c4a297c3c.jpg)

**Comment by ildyria** [comment]
![yes](https://user-images.githubusercontent.com/627094/81694708-f4eaf980-9461-11ea-87e9-2bb040af404e.png)

**Comment by fl1tz** [comment]
I'm just trying filezilla now. Database is prepared. I will see.

**Comment by fl1tz** [comment]
which link is required for access? a relative or absolute path? (excuse me I am not a developer. )

```apache
<Directory /(relative or absolute?)path/to/your/lychee>
	Options Indexes FollowSymLinks
	AllowOverride All
	Require all granted
</Directory>
```

**Comment by ildyria** [comment]
Absolute path.

**Comment by fl1tz** [comment]
Okay

**Comment by fl1tz** [comment]
Do I have to individualize something here -> 

> sudo chown -R www-data: www-data .

**Comment by ildyria** [comment]
Just make sure your webserver has the ownership or write access. to the Lychee files.

**Comment by fl1tz** [comment]
Thank you. None of this was necessary. I uploaded Lychee using filezilla. Then I called Lychee in the browser. It was possible to enter the data for the database and everything worked. - Now I'm going to migrate the data.

![l01](https://user-images.githubusercontent.com/37076834/81700723-5a8eb400-9469-11ea-8d3e-356743b6b369.jpg)
![l02](https://user-images.githubusercontent.com/37076834/81700726-5b274a80-9469-11ea-99a4-bf66f8e0f463.jpg)
![l03](https://user-images.githubusercontent.com/37076834/81700728-5bbfe100-9469-11ea-8f73-32007c687034.jpg)
![l04](https://user-images.githubusercontent.com/37076834/81700729-5cf10e00-9469-11ea-80a4-346c8b95f93a.jpg)
![l05](https://user-images.githubusercontent.com/37076834/81700732-5d89a480-9469-11ea-9fe5-562734749f80.jpg)
![l06](https://user-images.githubusercontent.com/37076834/81700740-5ebad180-9469-11ea-947b-807ec296e9f1.jpg)

**Comment by ildyria** [comment]
:)

**Comment by fl1tz** [comment]
Had I known that, I wouldn't have done anything on the console. - The migration is still ongoing. I will get in touch later on.

**Comment by ildyria** [comment]
well via the console you get a better support on master and you are not forced to follow releases. :)

**Comment by fl1tz** [comment]
Well, then I have to familiarize myself with it.
For information:
I use the shared hoster strato with apache, php 7.3 and ssl access.

**Comment by fl1tz** [comment]
Many thanks for the support!
