### ISSUE TITLE
Update Lychee on shared hosted server without SSH

### ISSUE THREAD

**Issue by stoneubi** [LycheeOrg/Lychee#507]
I installed Lychee Version 4.0.1 on a shared hosted server without SS via Softaculous Apps Installer. 

Acutally I want to update to Version 4.0.2 and followed the manual update:

    1. Download the newest Version
    2. Replace all existing files, excluding uploads/ and dist/user.css
    3. Execute php artisan migrate

The problem is that on the shared hosted server without SSH access the php artisan migrate command cannot be executed. 

Feature request: 
*the easy way: it would be great to have a function within the Diagnose view to execute the migration
* the better way: as I uploaded the files the diagnose view shows: 
   
     System Information
    --------------
    _Lychee-front Version:       4.0.1 (c41683e)
    Lychee Version (release):   4.0.2
    DB Version:                 4.0.1_

It would be great if lychee automatically excecutes the migration command, if the Lychee Version and DB Version is different. 

Anyhow: a great feature request would be to have a automatically update process within lychee for above mentioned environment. 

Many thanks
Stoneubi

**Comment by ildyria** [comment]
Actually... Fixed with #499

This is already fixed in the sense we just need to do create release 4.0.3 and you will find a button in the Diagnostic to apply the migration. :)

On the bright side, there was no database modification (aside from the version number) from 4.0.1 to 4.0.2 and there won't be either for 4.0.3

**Comment by stoneubi** [comment]
Perfect :-)

Many thanks for the quick repsonse and congratulation for this great photo management tool.

**Comment by ildyria** [comment]
Et voila! fixed with https://github.com/LycheeOrg/Lychee/releases/tag/v4.0.3
