### ISSUE TITLE
Feature: New smart album "Random"

### ISSUE THREAD

**Issue by muuvmuuv** [LycheeOrg/Lychee#51]
Would be nice to have a smart album that shows a random image in X sec/min or on each page load. We had this feature in our previously used tool and some employees would like to have it back.

I‘d program it myself, but would take a long time, as I am a frontend/node-backend dev, not PHP. Anyway, with good hints and tips (and I saw a well-documented plugin.md here), I would take that effort.

**Comment by ildyria** [comment]
Covered by Frame.
