### ISSUE TITLE
Main directory template

### ISSUE THREAD

**Issue by danieldotnet** [LycheeOrg/Lychee#514]
Hello,
Perhaps not entirely appropriate my question here.
I would like to include Google Analytics in my photo album. But I don't know the main directory of the template. Can someone give me a hint?

**Comment by ildyria** [comment]
You can try to add your code in the `additional_footer_text` setting.
Or you can try to edit: 
https://github.com/LycheeOrg/Lychee/blob/master/resources/views/layouts/simple.blade.php
https://github.com/LycheeOrg/Lychee/blob/master/resources/views/layouts/gallery.blade.php

Additionally you may need to tweek:
https://github.com/LycheeOrg/Lychee/blob/master/config/secure-headers.php

**Comment by danieldotnet** [comment]
Thank you, this helps.
