### ISSUE TITLE
Subfolders available?

### ISSUE THREAD

**Issue by Juliush14** [LycheeOrg/Lychee#517]
Hi,

Is it possible to create folders inside another folder? If so, how to do that?

Sincerely,
Julius

**Comment by ildyria** [comment]
Either press `n` (as **N**ew) or use the add menu.
![Screenshot (33)](https://user-images.githubusercontent.com/627094/80621138-2c5fac00-8a47-11ea-849e-050f740d3b7d.png)

**Comment by ildyria** [comment]
https://github.com/LycheeOrg/Lychee/wiki/FAQ#how-can-i-set-thumbnails-for-my-albums Done.
