### ISSUE TITLE
Short ID left for old albums

### ISSUE THREAD

**Issue by oblomow** [LycheeOrg/Lychee#519]
### Detailed description of the problem [REQUIRED]
Share map with 'Hidden' option no longer works as expected. Behaviour changed after update to v4.

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Go to a map
2. Click on album visibility
3. Scroll down to Hidden, only people with the direct link can view this album
4. In previous Lychee versions the gallery number would change to a large random ('secret') number. This way you could share the link with other people.

### Output of the diagnostics  [REQUIRED]

    Diagnostics
    -------
    Info: Latest version of PHP is 7.4
    Warning: Dropbox import not working. dropbox_key is empty.
    Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.

    System Information
    --------------
    Lychee Version (git):       master (499eef6) - Up to date (12 minutes ago).
    DB Version:                 4.0.3
    
    composer install:           --no-dev
    APP_ENV:                    local
    APP_DEBUG:                  false
    
    System:                     FreeBSD
    PHP Version:                7.3
    MySQL Version:              5.7.29-log
    
    Imagick:                    1
    Imagick Active:             1
    Imagick Version:            1690
    GD Version:                 2.2.5

Request space usage

    Config Information
    --------------
    version:                    040003
    check_for_updates:          1
    sorting_Photos_col:         takestamp
    sorting_Photos_order:       ASC
    sorting_Albums_col:         title
    sorting_Albums_order:       DESC
    imagick:                    1
    skip_duplicates:            0
    small_max_width:            0
    small_max_height:           360
    medium_max_width:           1920
    medium_max_height:          1080
    lang:                       en
    layout:                     1
    image_overlay:              0
    image_overlay_type:         exif
    default_license:            none
    compression_quality:        90
    full_photo:                 1
    delete_imported:            0
    Mod_Frame:                  1
    Mod_Frame_refresh:          30
    thumb_2x:                   1
    small_2x:                   1
    medium_2x:                  1
    landing_page_enable:        1
    landing_owner:              ****
    landing_title:              ****
    landing_subtitle:           ****
    landing_facebook:           
    landing_flickr:             
    landing_twitter:            
    landing_instagram:          
    landing_youtube:            
    landing_background:         ****
    site_title:                 ****
    site_copyright_enable:      1
    site_copyright_begin:       2020
    site_copyright_end:         2020
    additional_footer_text:     
    display_social_in_gallery:  0
    public_search:              0
    SL_enable:                  0
    SL_for_admin:               0
    public_recent:              0
    recent_age:                 0
    public_starred:             0
    downloadable:               0
    photos_wraparound:          1
    map_display:                0
    zip64:                      1
    map_display_public:         0
    map_provider:               OpenStreetMap.org
    force_32bit_ids:            0
    map_include_subalbums:      0
    update_check_every_days:    3
    has_exiftool:               1
    share_button_visible:       0
    import_via_symlink:         0
    has_ffmpeg:                 0
    location_decoding:          0
    location_decoding_timeout:  30
    location_show:              0
    location_show_public:       0

### Browser and system
MacOS 10.13.6 /Safari 13.1

**Comment by tmp-hallenser** [comment]
Could you describe a bit more your steps? Under maps, I don't see a setting for album visibility.

**Comment by oblomow** [comment]
![Screen Shot 2020-04-30 at 16 39 25](https://user-images.githubusercontent.com/427760/80723721-44940180-8b01-11ea-828d-d3e8c30607fc.jpg)

see attachment. It's in the upper right menu.

**Comment by tmp-hallenser** [comment]
I don't see the link to the map functionality, hence I would assign the bug to @ildyria :) (I don't know how Lychee v3 behaved).

**Comment by ildyria** [comment]
What **map** are you talking about ? Because I get the feeling that you are not talking about the same thing as us.

Additionally, I don't remember the v3 having the map functionality.

As for sharing an album, the process is still the same, you set the visibility and you share the URL.
I don't remember the URL changing to a large random number in the v3.

**Comment by d7415** [comment]
Ok, as I see it:

 - You seem to be saying "maps" but meaning "albums"
 - I've just tried in v3 and the album URL behaviour was the same

In short, I don't understand the issue.

@ildyria beat me to it, but I'll leave mine here too.

**Comment by oblomow** [comment]
If I go to any map (album) on my Lychee website, I can share a map using these options:

![Screen Shot 2020-05-01 at 13 29 08](https://user-images.githubusercontent.com/427760/80802558-effb8f80-8baf-11ea-853e-5f34f03bcf09.jpg)

 I then select the option 'only people with the direct link can view this album' .
<checking>
Mmm. Strange. I have some older albums that have names like gallery#15, gallery#12 etc. So I assumed the name changed to a random number ('security by obscurity').  If I share theses albums the names are easy to guess.


for example: https://albums.bospaling.nl/gallery#6 
compared to https://albums.bospaling.nl/gallery#15475788754862


Perhaps I discovered an old bug, but I just tried to share an old albums after updating to version 4 and noticed this behaviour.

**Comment by d7415** [comment]
Yup. That's the bug.

I'm not sure it's something we should change automatically because it will break links. Were these albums imported from v3?

**Comment by oblomow** [comment]
Yes, old these albums were already in Lychee v3 before updating to v4.

**Comment by d7415** [comment]
Ok. No bug. That was standard behaviour before March 2016 ( LycheeOrg/Lychee-v3@976635254e3eb8d2333e9e66760234ea24571b80 ). You can either manually change your album ID or it may be easier to create a new album and move the photos across.

**Comment by oblomow** [comment]
OK. thanks. There albums were indeed uploaded jan. 2016
Sorry for the confusion!

**Comment by oblomow** [comment]
I'll buy ildyria a beer when I meet him since we're in the same city.

**Comment by ildyria** [comment]
No problem. :) 
It is better to have someone reporting a bug which is not one rather than someone not reporting a bug at all. :+1:

**Comment by ildyria** [comment]
> I'll buy ildyria a beer when I meet him since we're in the same city.

 :open_mouth:  Let's wait May 20th then ! :smile:
