### ISSUE TITLE
Copy Paste link not working Firefox win10

### ISSUE THREAD

**Issue by jsanfe** [LycheeOrg/Lychee#521]
### Detailed description of the problem [REQUIRED]
Trying to use the direct link inside each photo, does not work in firefox. Also tried in Edge and its working fine.

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Go to a photo
2. Click on share
3. Click on Direct Link
3. Click any link
4. Paste in other firefox tab. (copy does not work)

**Screenshots**
*If applicable, add screenshots to help explain your problem.*
![lychee](https://user-images.githubusercontent.com/33582696/80743184-d5c4a180-8b1c-11ea-9448-4e62a9f755cb.jpg)

### Output of the diagnostics  [REQUIRED]
    Diagnostics
    -------
    Info: Latest version of PHP is 7.4
    Warning: Dropbox import not working. dropbox_key is empty.

    System Information
    --------------
    Lychee Version (git):       master (499eef6) - Data not in Cache
    DB Version:                 4.0.3
    
    composer install:           --no-dev
    APP_ENV:                    local
    APP_DEBUG:                  false
    
    System:                     Linux
    PHP Version:                7.3
    MySQL Version:              10.3.22-MariaDB-0+deb10u1
    
    Imagick:                    1
    Imagick Active:             1
    Imagick Version:            1690
    GD Version:                 2.2.5

### Browser and system
Firefox 75.0 Windows 10

**Comment by ildyria** [comment]
https://github.com/LycheeOrg/Lychee-front/issues/167 related

Are you using https?

**Comment by jsanfe** [comment]
not yet...

**Comment by nagmat84** [comment]
As the feature is only supported by browsers, if the website uses HTTPS this is nothing Lychee can solve.

So I am closing this issue.
