### ISSUE TITLE
Share Button on Albums or Tag resumen

### ISSUE THREAD

**Issue by jsanfe** [LycheeOrg/Lychee#522]
With the current version of Lychee, i can share each photo, but no the entire album. 
Also would be a great idea that if i make a search, example: nature, would be ideal if you could share the search result, or group it into an album.
Only Jpg its allowed?

**Comment by ildyria** [comment]
> With the current version of Lychee, i can share each photo, but no the entire album.

I'm pretty sure you can share an album, just copy paste the URL link (but you need to set the proper visibility first).

**Comment by jsanfe** [comment]
i mean, like the invidual photo, in the menu right, you have a button to share...

**Comment by d7415** [comment]
If you want the social links for an album, you need to set the sharing settings (eye icon) to "Share button is visible".
