### ISSUE TITLE
[Enhancement] Possible age Verification 

### ISSUE THREAD

**Issue by fotocreativo** [LycheeOrg/Lychee#524]
Hello, everyone. I hope I'm in the right place with my question. Is there a way to add an age verification to a specific folder that you choose in Lychee? Since I am a photographer who also takes cgi pictures, which are not suitable for young people. Even if these pictures are harmless, the German law is very restrictive concerning such sites. A help would be a small query in Lychee v4.0.2 which verifies the age. And a hint that you could enter manually. An imprint / privacy policy that I create as a html page and then link to it would be great if you could implement that. Many thanks to the community who continue to develop Lychee.

**Comment by ildyria** [comment]
@fotocreativo Can you check if this https://github.com/LycheeOrg/Lychee/pull/822 would solve your issue  or does it need to be an explicit age verification (which we all know can just be by passed by a 15 yo kid).

**Comment by ildyria** [comment]
This should be fixed with https://github.com/LycheeOrg/Lychee/commit/27e4428786c2cacface06c8986d62db02ee0dfaf

It is not on the full website but per album.
