### ISSUE TITLE
v4 upgrade clarification

### ISSUE THREAD

**Issue by alex-phillips** [LycheeOrg/Lychee#525]
@ildyria I'm working on the LSIO container for v4 (this is hackerman in the Discord!). Just wanted to clarify a couple of things to make sure I have the upgrade running as smoothly as possible:

1. It looks like the upgrade resets the admin account. I haven't tried it with multiple users. But if I try and upgrade from an existing v3 installation to v4, the first page load prompts me to create the admin account. Is this normal?
2. Regarding video thumbnail generation - in the past we had to slightly modify the code to include the ffmpeg binary paths. It doesn't look like if I upload a video it's generating a thumbnail. Anything special we need to do here?
3. It looks like all of the settings are getting reset. Is there a way to preserve settings?

If you want to chat in discord, just ping me! Thanks again for the great project!

**Comment by d7415** [comment]
> 1. It looks like the upgrade resets the admin account. I haven't tried it with multiple users. But if I try and upgrade from an existing v3 installation to v4, the first page load prompts me to create the admin account. Is this normal?

I *think* that's deliberate.

> 2. Regarding video thumbnail generation - in the past we had to slightly modify the code to include the ffmpeg binary paths. It doesn't look like if I upload a video it's generating a thumbnail. Anything special we need to do here?

If you need to change the binary paths you'll need to look [here](https://github.com/LycheeOrg/Lychee/blob/master/app/ModelFunctions/PhotoFunctions.php#L479) or figure out why it's not in php's `PATH`.
 
> 3. It looks like all of the settings are getting reset. Is there a way to preserve settings?

Many of the settings are different. We might migrate some, but I'd have to look - @ildyria might know. If you want to write something to migrate specific settings, look at the migrations in `database/migrations/`.

**Comment by ildyria** [comment]
> > 1. It looks like the upgrade resets the admin account. I haven't tried it with multiple users. But if I try and upgrade from an existing v3 installation to v4, the first page load prompts me to create the admin account. Is this normal?
> 
> I _think_ that's deliberate.

Actually this is necessary. The v4 uses the Laravel facade to generate the hash and verify them while Lychee v3 does this manually. The v4 has thus the agility to switch between different hashing schemes.

> It looks like all of the settings are getting reset. Is there a way to preserve settings?

Indeed, but some of the settings might be portable. To be honest I just did not bother. :sweat_smile:
