### ISSUE TITLE
Typora integration

### ISSUE THREAD

**Issue by BobAnkh** [LycheeOrg/Lychee#526]
Typora has the functions of automatically upload the pictures inserted to image host. It uses picgo or custom command line.

Is there a way to combine Lychee and typora(or picgo) that I can upload pictures inserted in Typora to Lychee and if so, how I can configure it? (I think it is more convenient for me to write markdown)

Thank you!

**Comment by d7415** [comment]
Really you'd need to ask them, especially as they appear to be closed source and aiming for a paid model, I see no benefit in our dedicating time to this.

Essentially, you'd either need to interface with the [API](https://github.com/LycheeOrg/Lychee/wiki/Server-API) directly, or upload a file and then use something like [this](https://github.com/LycheeOrg/Lychee/wiki/FAQ#can-i-set-up-lychee-to-watch-a-folder-for-new-images-and-automatically-add-them-to-albums) to import them into Lychee.

Honestly, I'm not convinced Lychee is a good fit for this task. It's designed as a gallery, not content storage.
