### ISSUE TITLE
Unable to disable landing page after upgrading from v3 to v4

### ISSUE THREAD

**Issue by aceface25** [LycheeOrg/Lychee#527]
### Unable to disable landing page after upgrading from v3 to v4
I upgraded from Lychee 3 to Lychee 4.0.2 and now I cannot access my site.  The page only loads the default landing page (John Smith Cats) with bare formatting and presents no UI with which to navigate.  I have tried manually setting "landing_page_enable" to "0" in the lychee_settings table in mysql to no avail.  The output of "php artisan lychee:diagnostics" is below.  Is there any mechanism to disable the landing page without going through the site UX?

Thanks in advance,

-Brian

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Install Lychee v3
2. Upgrade to Lychee v4
3. View site (tested in Firefox, Edge, and Safari Mobile)

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

### Output of the diagnostics  [REQUIRED]

```
System Information
------------------
Lychee Version (git):       master (5935f48) - Data not in Cache
DB Version:                 4.0.2

composer install:           --no-dev
APP_ENV:                    local
APP_DEBUG:                  false

System:                     Linux
PHP Version:                7.4
MySQL Version:              8.0.20

Imagick:                    1
Imagick Active:             1
Imagick Version:            1687
GD Version:                 2.2.5

Config Information
------------------
version:                    040002
check_for_updates:          0
sorting_Photos_col:         takestamp
sorting_Photos_order:       ASC
sorting_Albums_col:         max_takestamp
sorting_Albums_order:       ASC
imagick:                    1
skip_duplicates:            0
small_max_width:            0
small_max_height:           360
medium_max_width:           1920
medium_max_height:          1080
lang:                       en
layout:                     1
image_overlay:              1
image_overlay_type:         exif
default_license:            reserved
compression_quality:        90
full_photo:                 1
delete_imported:            0
Mod_Frame:                  1
Mod_Frame_refresh:          30
thumb_2x:                   1
small_2x:                   1
medium_2x:                  1
landing_page_enable:        1
landing_owner:              John Smith
landing_title:              John Smith
landing_subtitle:           Cats, Dogs & Humans Photography
landing_facebook:           https://www.facebook.com/JohnSmith
landing_flickr:             https://www.flickr.com/JohnSmith
landing_twitter:            https://www.twitter.com/JohnSmith
landing_instagram:          https://instagram.com/JohnSmith
landing_youtube:            https://www.youtube.com/JohnSmith
landing_background:         dist/cat.jpg
site_title:                 Lychee v4
site_copyright_enable:      1
site_copyright_begin:       2019
site_copyright_end:         2019
additional_footer_text:
display_social_in_gallery:  0
public_search:              0
SL_enable:                  0
SL_for_admin:               0
public_recent:              0
recent_age:                 1
public_starred:             0
downloadable:               0
photos_wraparound:          1
map_display:                0
zip64:                      1
map_display_public:         0
map_provider:               Wikimedia
force_32bit_ids:            0
map_include_subalbums:      0
update_check_every_days:    3
has_exiftool:               0
share_button_visible:       0
import_via_symlink:         0
has_ffmpeg:                 1
location_decoding:          0
location_decoding_timeout:  30
location_show:              1
location_show_public:       0`
```

### Browser and system
Windows 10 - Firefox, Edge
Safari - macOS

**Comment by d7415** [comment]
>  I have tried manually setting "landing_page_enable" to "0" in the lychee_settings table in mysql to no avail. 

> Is there any mechanism to disable the landing page without going through the site UX?

That's it.

> landing_page_enable: 1

Did you set it back?

> and presents no UI with which to navigate

Did you try the "gallery" link?

**Comment by ildyria** [comment]
>  lychee_settings table in mysql 

All tables prefixed by `lychee_` are used in the v3, not by the v4. The tables used by the v4 (so far) are: `albums`, `configs`, `logs`, `migrations`, `pages`, `page_contents`, `photos`, `sym_links`, `users`, `user_album`

By the way, the landing page is disable by default now if I'm not mistaken: 
https://github.com/LycheeOrg/Lychee/blob/master/database/migrations/2019_09_28_171753_config_fix.php#L310

**Comment by ildyria** [comment]
any news ?

**Comment by ildyria** [comment]
No news.
