### ISSUE TITLE
Patch import uploads to public instead of private by default

### ISSUE THREAD

**Issue by skydivercactus** [LycheeOrg/Lychee#528]
### Detailed description of the problem [REQUIRED]
Essentially some people might not want to default it be public or maybe possible to have options to force upload in admin account to folder/album as private? 

It won't be a much of issues if Lychee allow batch control of setting photo public/private.  

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
php artisan lychee:sync /path/to/import

You will see imported photo under public folder and currently there isn't any way to batch make photo private/public. 

**Screenshots**
N/A

### Output of the diagnostics  [REQUIRED]

    Diagnostics
    -------
    Info: Latest version of PHP is 7.4
    Warning: Dropbox import not working. dropbox_key is empty.

### Browser and system
Running on:

    System Information
    --------------
    Lychee Version (git):       No git data found.
    DB Version:                 4.0.3
    
    composer install:           --no-dev
    APP_ENV:                    local
    APP_DEBUG:                  false
    
    System:                     FreeBSD
    PHP Version:                7.3
    MySQL Version:              10.2.31-MariaDB
    
    Imagick:                    1
    Imagick Active:             1
    Imagick Version:            1690
    GD Version:                 2.2.5

**Comment by tmp-hallenser** [comment]
Do you want to give it a try? Here are some hints to start with:

1. Add parameters to console command
https://github.com/LycheeOrg/Lychee/blob/499eef635f8e019d5f7018eea27e0360c42ccdac/app/Console/Commands/Sync.php#L20
https://github.com/LycheeOrg/Lychee/blob/499eef635f8e019d5f7018eea27e0360c42ccdac/app/Console/Commands/Sync.php#L72

2. Pass it to the import controller
https://github.com/LycheeOrg/Lychee/blob/499eef635f8e019d5f7018eea27e0360c42ccdac/app/Console/Commands/Sync.php#L85

3. Folders / Photos creation is called here:
https://github.com/LycheeOrg/Lychee/blob/1d70bdcf50dc2f4497cc0eb2a3769daffd652051/app/Http/Controllers/ImportController.php#L391
https://github.com/LycheeOrg/Lychee/blob/1d70bdcf50dc2f4497cc0eb2a3769daffd652051/app/Http/Controllers/ImportController.php#L367

**Comment by skydivercactus** [comment]
> 
> 
> Do you want to give it a try? Here are some hints to start with:
> 
>     1. Add parameters to console command
>        https://github.com/LycheeOrg/Lychee/blob/499eef635f8e019d5f7018eea27e0360c42ccdac/app/Console/Commands/Sync.php#L20
>        
>        https://github.com/LycheeOrg/Lychee/blob/499eef635f8e019d5f7018eea27e0360c42ccdac/app/Console/Commands/Sync.php#L72
> 
>     2. Pass it to the import controller
>        https://github.com/LycheeOrg/Lychee/blob/499eef635f8e019d5f7018eea27e0360c42ccdac/app/Console/Commands/Sync.php#L85
> 
>     3. Folders / Photos creation is called here:
>        https://github.com/LycheeOrg/Lychee/blob/1d70bdcf50dc2f4497cc0eb2a3769daffd652051/app/Http/Controllers/ImportController.php#L391
>        
>        https://github.com/LycheeOrg/Lychee/blob/1d70bdcf50dc2f4497cc0eb2a3769daffd652051/app/Http/Controllers/ImportController.php#L367

Yeah that so helpful, maybe updating the FAQ to include the option to "sync" to a album. I haven't really play around with the user as ID as can't really find any documentation on the user ID. I assume it store in database.

I am now able to create a album associated to that user and sync directory to album and permission defaults to album setting.
