### ISSUE TITLE
Footer linkable. 

### ISSUE THREAD

**Issue by fotocreativo** [LycheeOrg/Lychee#529]
I am trying to place the link button „HOSTED WITH LYCHEE“. Would ist be possible in you could make the footer linkable in the Settings? In would be really friendly of you could insert that. So I would have a possibility to easily instert an imprint. Thanks a lot.

**Comment by ildyria** [comment]
Hummm I thought I fixed that.

**Comment by fotocreativo** [comment]
That would be great.i just can‘t get it together...:-( Or do you have a guess? Greetings Mario.

**Comment by ildyria** [comment]
As soon as the PR is merged you should be able to use html code in the advanced setting `additional_footer_text`.

**Comment by fotocreativo** [comment]
Thanks, i‘ll try ist now. Thanks a lot.

**Comment by fotocreativo** [comment]
Yes show,but not clickable for a link.

**Comment by ildyria** [comment]
I said, **when merged**. :sweat_smile: 

First I need to wait for the CI to pass:
https://github.com/LycheeOrg/Lychee/pull/530/checks?check_run_id=640345994
https://github.com/LycheeOrg/Lychee/pull/530/checks?check_run_id=640347096

**Comment by fotocreativo** [comment]
I need an „imprint“ (Impressum) in Germany. Without this you will get a Warnung from lawyers in Germany.

**Comment by ildyria** [comment]
I know. This is exactly the reason why we added this.
See here: https://github.com/LycheeOrg/Lychee-v3/issues/5

**Comment by fotocreativo** [comment]
Thanks for your help.

**Comment by ildyria** [comment]
Was fixed with: https://github.com/LycheeOrg/Lychee/pull/257

But the update of the laravel framework from version 6 to version 7 changed the syntax for allowed html in blade template from `{{ $var }}` to `{!! $var !!}`.

**Comment by fotocreativo** [comment]
Now I'm a little confused as to what's next. Will this be installed via an update? Or does it only need to download certain parts of it?

**Comment by fotocreativo** [comment]
The first idea was to create an own html page and link it, which is not that difficult. Since it is possible to enter a footer text, I thought it might be the easiest way. But I've been sitting there all morning trying to solve it differently, but without success.

**Comment by ildyria** [comment]
So if you have access to the database, you can actually create pages directly in Lychee (via SQL request), it supports markdown.

![](https://raw.githubusercontent.com/LycheeOrg/Lychee/master/docs/images/page1.png)
![](https://raw.githubusercontent.com/LycheeOrg/Lychee/master/docs/images/page2.png)

That is how I created: https://photography.viguier.nl/about

**Comment by ildyria** [comment]
@fotocreativo if you do a `git pull` in your lychee installations, this should be fixed.

**Comment by fotocreativo** [comment]
/git (and subdirectories) are not executable, check the permission. Lychee is provided by my provider, but I also use fileZilla. Which flags do I have to set? 
Which folders do I have to give write permission (777)?  Your side is great! Just what I had in mind.

**Comment by ildyria** [comment]
> Lychee is provided by my provider

Suprising.

Then I assume you are not using the master branch but the release channel ? If so sadly you will have to wait for the version 4.0.4

The other approach is to git clone the repository locally and do `make dist`. This will generate an archive containing the release files.

As for the folder requiring write access: `storage`, `dist` and `public` (and subfolders). Though I would not recommend 777, but change the group ownership and give the said group read-write-execute.

If it says git is not executable, it means that you need to also give write access to the `.git` (and subfolders) at the root of the repository.

**Comment by fotocreativo** [comment]
I have written to the provider, thank you very much for your help! 

Greetings
www.FotoCreativo.de
