### ISSUE TITLE
[Enhancement] - Add LYCHEE_UPLOADS_URL to secure-headers.php

### ISSUE THREAD

**Issue by hxrsmurf** [LycheeOrg/Lychee#533]
Sorry I'm new to PHP. I can't seem to figure out how to add the LYCHEE_UPLOADS_URL environment variable to the secure-headers.php to allow images to be loaded from another server (CDN). This may also be useful for others that want to off-load the images,

**Comment by ildyria** [comment]
You can use `env('LYCHEE_UPLOADS_URL', 'https://lycheeorg.github.io/')` to access the environment variable and add it around https://github.com/LycheeOrg/Lychee/blob/master/config/secure-headers.php#L394

`https://lycheeorg.github.io/`will be a safe default value by default.

**Comment by hxrsmurf** [comment]
Thank you. I feel like an idiot. I was missing the ```/``` in the ENV variable. That's why I couldn't get the env PHP function to work.
