### ISSUE TITLE
[Enhancement] Importing from CLI

### ISSUE THREAD

**Issue by benoitjpnet** [LycheeOrg/Lychee#536]
I already use the "import from server" in the web interface but I would like to directly import pictures from the server with a CLI command (no need to use the web interface), bonus point if you can specify a path other than the default "uploads/import".

**Comment by d7415** [comment]
See the command referenced [here](https://github.com/LycheeOrg/Lychee/wiki/FAQ#can-i-set-up-lychee-to-watch-a-folder-for-new-images-and-automatically-add-them-to-albums)

**Comment by benoitjpnet** [comment]
Wow amazing! Thanks, my bad didn't see it.
