### ISSUE TITLE
Invalid exif geolocation causes db error

### ISSUE THREAD

**Issue by csaxx** [LycheeOrg/Lychee#539]
### Error when upload photos with invalid geo info
During upload, I noticed some photos produced errors ("something went wrong, error22003). After some digging in the log files this turned out to be due to invalid geo info. In my case, for whatever reason, the longitude was set to -4367743116.3897 which resulted in: "error","App\\ModelFunctions\\PhotoFunctions::save","692","Something went wrong, error 22003, SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'longitude' at row 1

I realize that this is caused by an external problem, but in my opinion, it would be preferable to just disable the respective fields automatically instead of requiring the user to sift through photos individually to remove exif data that is broken anyway.

**Comment by tmp-hallenser** [comment]
Do you want to give it a try to fix it?

Here's a similar check for the creation data:
https://github.com/LycheeOrg/Lychee/blob/7c51bd4a06bc92d26b01b81f46dfea54936f0714/app/Metadata/Extractor.php#L130-L140

The latitude must be a number between -90 and 90 and the latitude between -180 and 180.

I would suggest to set both to null if latitude or latitude is out-of-range.

**Comment by csaxx** [comment]
Thanks for the indication where to look. I'm not great with php but this seems to work for me:
```php
// We need to make sure, latitude is between -90/90 and longitude is between -180/180
// We set values to null in case we're out of bounds
if ($metadata['latitude'] !== null || $metadata['longitude'] !== null) {
		$latitude = $metadata['latitude'];
		$longitude = $metadata['longitude'];
		if ($latitude < -90 || $latitude > 90 || $longitude < -180 || $longitude > 180) {
				$metadata['latitude'] = null;
				$metadata['longitude'] = null;
				Logs::notice(__METHOD__, __LINE__, 'Latitude/Longitude (' . $latitude . '/' . $longitude . ') out of bounds (needs to be between -90/90 and -180/180)');
		}
}
```
