### ISSUE TITLE
Very slow upload speed

### ISSUE THREAD

**Issue by Betalord** [LycheeOrg/Lychee#548]
Hi,
I'm experiencing very slow upload speeds, so I was wondering what upload protocol/mechanism does lychee use? My problem is this: I have installed lychee on a VPS (that is behind 200 Mbps port, I've run some test and it actually almost arrives at 200 Mbps, so we're fine there). I did ipref3 test on my laptop and VPS and measured speeds around 3 to 4 Mbps (my laptop is behind a 20 Mbps line though). When uploading photos to lychee album, it takes ~55 seconds to upload a 3.78 MB photo. That means 0.5 Mbps, which is several times less than the bandwidth test showed using ipref3.

Have any of you guys experimented similar slow downs? Is the problem on my side (laptop/VPS) or is it lychee? How can I figure it out?

```
 Diagnostics
    -------
    Warning: Dropbox import not working. dropbox_key is empty.



    System Information
    --------------
    Lychee Version (git):       master (7b7ad39) - Data not in Cache
    DB Version:                 4.0.3
    
    composer install:           --no-dev
    APP_ENV:                    local
    APP_DEBUG:                  false
    
    System:                     Linux
    PHP Version:                7.4
    MySQL Version:              8.0.19-0ubuntu5
    
    Imagick:                    1
    Imagick Active:             1
    Imagick Version:            1690
    GD Version:                 2.2.5



    Config Information
    --------------
    version:                    040003
    check_for_updates:          0
    sorting_Photos_col:         id
    sorting_Photos_order:       ASC
    sorting_Albums_col:         id
    sorting_Albums_order:       ASC
    imagick:                    1
    skip_duplicates:            0
    small_max_width:            0
    small_max_height:           360
    medium_max_width:           1920
    medium_max_height:          1080
    lang:                       en
    layout:                     1
    image_overlay:              1
    image_overlay_type:         desc
    default_license:            reserved
    compression_quality:        90
    full_photo:                 1
    delete_imported:            0
    Mod_Frame:                  1
    Mod_Frame_refresh:          30
    thumb_2x:                   1
    small_2x:                   1
    medium_2x:                  1
    landing_page_enable:        0
    landing_owner:              Betalord
    landing_title:              Betalord
    landing_subtitle:           Personal galleries
    landing_facebook:           
    landing_flickr:             
    landing_twitter:            
    landing_instagram:          
    landing_youtube:            
    landing_background:         dist/cat.jpg
    site_title:                 Lychee v4
    site_copyright_enable:      1
    site_copyright_begin:       2009
    site_copyright_end:         2020
    additional_footer_text:     
    display_social_in_gallery:  0
    public_search:              0
    SL_enable:                  0
    SL_for_admin:               0
    public_recent:              0
    recent_age:                 1
    public_starred:             0
    downloadable:               0
    photos_wraparound:          1
    map_display:                0
    zip64:                      1
    map_display_public:         0
    map_provider:               Wikimedia
    force_32bit_ids:            0
    map_include_subalbums:      0
    update_check_every_days:    3
    has_exiftool:               0
    share_button_visible:       0
    import_via_symlink:         0
    has_ffmpeg:                 1
    location_decoding:          0
    location_decoding_timeout:  30
    location_show:              1
    location_show_public:       0
```

**Comment by ildyria** [comment]
> When uploading photos to lychee album, it takes ~55 seconds to upload a 3.78 MB photo. That means 0.5 Mbps, which is several times less than the bandwidth test showed using ipref3.

That is really surprising and there should not be a bottle neck here, at least not limited by Laravel or Lychee. One of the limiting factor could be the processing of the picture, but that is different.

Have you tried to upload the picture via SCP and see how long it takes if you do a `./artisan lychee:synch` ?

**Comment by Betalord** [comment]
Yep, when I try to upload big files via WinSCP (using sftp protocol) it goes about 0.5 Mbps too (I assumed that was due to sftp overhead or something). I tried doing both at the same time, uploading images via lychee and uploading large file via WinSCP, and the speed actually dropped at about half for both (together still at 5 Mbps), so it seems like some kind of a limit (VPS side?). Strange. But I can assume it's not lychee's fault?

**Comment by ildyria** [comment]
The problem is not Lychee.

My guess is that the problem is your **home** upload speed. I would highly suggest you do a speed test on your own home connection. https://www.speedtest.net/

If you have access to a really fast upload speed somewhere (e.g. a University with double band fiber) and test from there.

This is my Uni connection, whenever I need to upload a video or a few hundreds of pictures this is where I go. 
```
▶ ./speedtest-cli 
Retrieving speedtest.net configuration...
Testing from SURFnet bv...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by NovoServe (Doetinchem) [31.75 km]: 12.46 ms
Testing download speed................................................................................
Download: 726.64 Mbit/s
Testing upload speed................................................................................................
Upload: 769.70 Mbit/s
```

**Comment by Betalord** [comment]
I just did that test, I get:
29 Mbps download / 2.5 Mbps upload
It's upload that counts in this case. Note that I did this speed test while uploading photos to lychee, so my upload is 2.5+5=3 Mbps, which makes sense. So I don't understand how I'm getting only 0.5 Mbps... ah well, I'm not sure what to do about it, but at least I'm glad it's no lychee's fault :)

**Comment by ildyria** [comment]
I would redo the test while not uploading pictures... also note that 2.5 Mbps = 312.5 kB/s.
