### ISSUE TITLE
[Enhancement] Improve Performance for large photo set

### ISSUE THREAD

**Issue by zhanglix** [LycheeOrg/Lychee#549]
I deployed a Lychee container on a raspberry pi 4  board, and migrated lots of photos (above 100 GB) from 'shotwell' to lychee yesterday and got about 500+ albums because 'shotwell' grouped all photos by date taken. And it is very slow whenever need to load albums list .

I spend about half a day to merge all those 'daily albums' into 'monthly' one to reduce the amount of albums to less then 100. Now the loading time is about 2-3s, still slow but tolorable.

Another problem is some leaf albums have lots of photos(eg, the recent 'album' has 3000+ photos ), and it is impossible to load. 

My question is it possible to

- Make Albums list loading in milliseconds instead of seconds 
    - Maybe sort all photos into 'logical albums' of years and months, and generate albums list and their thumbs into static file or cache automatically

- Make  it possible to show Album  containing (1000+) photos
   - one possible solution is to place one placeholder for each photo on the page and loading the actual thumbnail asynchronously when a placeholder is about to be scrolled into the visible area.

- Is It possible to make  `php artisan lychee:sync`  to make use of  multiple cpu cores? 

---------
ps: this is diagnostics from my Lychee instance 

    Diagnostics
    -----------
    Info: Latest version of PHP is 7.4
    Warning: Using 32 bit PHP, recommended upgrade to 64 bit
    Warning: Dropbox import not working. dropbox_key is empty.

    System Information
    ------------------
    Lychee-front Version:      3.2.16
    Lychee Version (git):      bae5f2b (master) - Data not in Cache
    DB Version:                040000
    System:                    Linux
    PHP Version:               7.3
    MySQL Version:             10.1.44-MariaDB-0ubuntu0.18.04.1
    
    Lychee total space:        188.98 MB
    Upload folder space:       8.00 B
    System total space:        9.78 GB
    System free space:         8.47 GB (86%)
    
    Imagick:                   1
    Imagick Active:            1
    Imagick Version:           1690
    GD Version:                2.2.5

    Config Information
    ------------------
    version:                   040000
    check_for_updates:         0
    sorting_Photos_col:        takestamp
    sorting_Photos_order:      ASC
    sorting_Albums_col:        max_takestamp
    sorting_Albums_order:      ASC
    imagick:                   1
    skip_duplicates:           0
    small_max_width:           0
    small_max_height:          360
    medium_max_width:          1920
    medium_max_height:         1080
    lang:                      en
    layout:                    0
    image_overlay:             1
    image_overlay_type:        desc
    default_license:           none
    compression_quality:       90
    full_photo:                1
    delete_imported:           0
    Mod_Frame:                 1
    Mod_Frame_refresh:         30
    thumb_2x:                  1
    small_2x:                  1
    medium_2x:                 1
    landing_page_enable:       1
    landing_owner:             Zhang Li
    landing_title:             Zhang Li
    landing_subtitle:          Photography of Happy Memories
    landing_facebook:          
    landing_flickr:            
    landing_twitter:           
    landing_instagram:         
    landing_youtube:           
    landing_background:        dist/cat.jpg
    site_title:                Lychee v4
    site_copyright_enable:     1
    site_copyright_begin:      2019
    site_copyright_end:        2019
    additional_footer_text:    
    display_social_in_gallery: 0
    public_search:             0
    public_recent:             0
    recent_age:                1
    public_starred:            0
    downloadable:              0
    photos_wraparound:         1
    map_display:               0
    zip64:                     1
    map_display_public:        0
    map_provider:              Wikimedia
    force_32bit_ids:           0
    map_include_subalbums:     0
    update_check_every_days:   3
    has_exiftool:              1
    share_button_visible:      0
    import_via_symlink:        0
    has_ffmpeg:                1

**Comment by d7415** [comment]
>       * Maybe sort all photos into 'logical albums' of years and months, and generate albums list and their thumbs into static file or cache automatically

This would be a *very* specific solution to your use case, and could be accomplished by arranging your albums like that in subalbums.

>     * Make  it possible to show Album  containing (1000+) photos

This does work. The only bug I'm aware of with this is specific to password protected albums in Safari (#446)

>       * one possible solution is to place one placeholder for each photo on the page and loading the actual thumbnail asynchronously when a placeholder is about to be scrolled into the visible area.

I think we do this to some extent already - IIRC we load asynchronously, but don't wait for scrolling. I may be wrong though.

**Comment by zhanglix** [comment]
> > ```
> > * Make  it possible to show Album  containing (1000+) photos
> > ```
> 
> 
> This does work. The only bug I'm aware of with this is specific to password protected albums in Safari (#446)
> 
> 
> > ```
> >   * one possible solution is to place one placeholder for each photo on the page and loading the actual thumbnail asynchronously when a placeholder is about to be scrolled into the visible area.
> > ```
> 
> 
> I think we do this to some extent already - IIRC we load asynchronously, but don't wait for scrolling. I may be wrong though.

I think you are right. The problem I encountered does nothing todo with loading thumbnails for now.  when I clicked the "Recent Album",  the alblum::get() call  timeout.  I will try the latest docker later to see if it will be resolved 

![Screen Shot 2020-05-12 at 9 36 13 PM](https://user-images.githubusercontent.com/8109462/81698929-3c40ac80-9499-11ea-8ca3-5bc77a817a93.png)

**Comment by ildyria** [comment]
I'm working on simplifying the code base on that one.

**Comment by ildyria** [comment]
@zhanglix can you check again now that #625 is merged ?

**Comment by ildyria** [comment]
also for albums with a large number of photos, i think only a pagination system can help.

**Comment by zhanglix** [comment]
> @zhanglix can you check again now that #625 is merged ?

Do you mean the performance will be  improved? I will check it this weekend.

**Comment by zhanglix** [comment]
@ildyria Did you update the docker image for  linux/arm/v7? I can not pull lycheeorg/lychee-larave:dev with new version.
```
zhangli@pi ~ % docker pull lycheeorg/lychee-laravel:dev
dev: Pulling from lycheeorg/lychee-laravel
Digest: sha256:ec42cb4c6e0cfe171b8ca043188a64b78cdff62320d4e8bcd4be4771ea3ec1c6
Status: Image is up to date for lycheeorg/lychee-laravel:dev
docker.io/lycheeorg/lychee-laravel:dev
```

**Comment by d7415** [comment]
That doesn't match the has that Docker Hub is showing me... https://hub.docker.com/layers/lycheeorg/lychee-laravel/dev/images/sha256-c48cc2395e8e21cdc420996983c08e36afe1d560718cedad961143943a990401?context=explore

**Comment by zhanglix** [comment]
I updated the docker to latest dev version, and it works well.

I noticed that if I was viewing a big album and scrolling down to the very bottom of it, the photos located in the current view got loaded first. I think this is pretty nice! 👍

**Comment by ildyria** [comment]
Seems problem is fixed.
