### ISSUE TITLE
Investigate adding a git hook to handle artisan and composer

### ISSUE THREAD

**Issue by d7415** [LycheeOrg/Lychee#552]
It should be possible to install a git `post-merge` hook through an optional script or through composer to automatically run `php artisan migrate` and `composer install --no-dev` after each pull.

This is here so that I don't forget about it and to give everyone an opportunity to comment about the idea in general and about defaults - Should it be installed by default, but can be disabled or should the user have to actively install it?

- [x] Write a hook to include as an example
- [ ] Figure out how to present this to users
 - - [x] Installation instructions?
 - - [x] FAQ?
 - - [ ] Installer UI?
 - - [x] Composer?
 - - [x] Script to install it?

**Comment by ildyria** [comment]
Already implemented. :p

**Comment by ildyria** [comment]
see settings:
- `force_migration_in_production`
- `apply_composer_update`

Also see here: https://github.com/LycheeOrg/Lychee/blob/master/app/ControllerFunctions/Update/Apply.php

**Comment by d7415** [comment]
> Already implemented. :p

Only for the update UI - not for any other pulls.

**Comment by d7415** [comment]
Implemented in #553.
