### ISSUE TITLE
[Enhancement] report files not imported by sync

### ISSUE THREAD

**Issue by zhanglix** [LycheeOrg/Lychee#557]
When I see some error logs like this " Photo format not supported", I wish to know which file is it so that I can decide if I can convert it to supported format.

```
2020-05-14 00:39:47 -- error   -- App\ModelFunctions\PhotoFunctions::file_type -- 129 -- Photo format not supported
```

**Comment by ildyria** [comment]
Feel free to modify https://github.com/LycheeOrg/Lychee/blob/master/app/ModelFunctions/PhotoFunctions.php#L124 and submit a PR :)
