### ISSUE TITLE
Debian installation not working

### ISSUE THREAD

**Issue by Nobrac** [LycheeOrg/Lychee#559]
Hello there.

I followed the official installation guide on Github:

https://github.com/LycheeOrg/Lychee/wiki/Install-Steps-on-Debian-Testing

But when I want to access Lychee I only get a blank white page.

![Lychee_Blank_page](https://user-images.githubusercontent.com/22682116/81854117-bc304a80-955d-11ea-8f5b-b90708e95ce0.JPG)

I'm using the latest version of Debian 10.

Maybe I'm just forgetting something. I reinstalled the whole Debian 10 virtual machine several times now but it's always the same problem.

Thank you for your help.

Best regards
Nobrac

**Comment by d7415** [comment]
Open the Inspector in your browser and check the network tab.
Also, try running `php artisan lychee:diagnostics` from the command line.

It's possible you cloned while we briefly had a problem with php7.3 support.

**Comment by Nobrac** [comment]
Thank you for your answer.

I just reinstalled my virtual machine and took a fresh clone from the repository. It works now. Thanks. :)
