### ISSUE TITLE
Ability for shared users to download original photo & metadata

### ISSUE THREAD

**Issue by skydivercactus** [LycheeOrg/Lychee#563]
### Detailed description of the problem [REQUIRED]
Share albums doesn't have option to download original selection option. 

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Share a album/photo with another user
2. Login into other user
3. Access the photo/album, no option to download images.

Note: It is still possible to download the "open original" but when download it doesn't download with original metadata. If we already allow access to original photo, I think there should be option to download photo.

**Screenshots**

### Output of the diagnostics  [REQUIRED]
    System Information
    --------------
    Lychee Version (git):       No git data found.
    DB Version:                 4.0.4
    
    composer install:           --no-dev
    APP_ENV:                    local
    APP_DEBUG:                  false
    
    System:                     FreeBSD
    PHP Version:                7.3
    MySQL Version:              10.2.31-MariaDB
    
    Imagick:                    1
    Imagick Active:             1
    Imagick Version:            1690
    GD Version:                 2.2.5

### Browser and system
Firefox 76

**Comment by ildyria** [comment]
Duplicate: https://github.com/LycheeOrg/Lychee/issues/438
