### ISSUE TITLE
[Enhancement] HEIC format

### ISSUE THREAD

**Issue by zhanglix** [LycheeOrg/Lychee#564]
Do you have plans to support images  in HEIC file containers?

It seems that exiftool and imageMagicK already support HEIC format, doesn't it?

**Comment by ildyria** [comment]
If exiftool and imagemagick are supporting it, it can easily be added. This was requested for webp:
https://github.com/LycheeOrg/Lychee-v3/issues/341

See here for the PR:
https://github.com/LycheeOrg/Lychee/pull/476

**Comment by zhanglix** [comment]
I added two extentions to the $validExtensions array, add both format were processed correct.
```lang=php
public $validExtensions = [
		...
		'.webp',
                '.heic',
		'.nef',
		...
	];
```
I found that all my 'heic' files are live photos. Lychee detected them as live photos, but did NOT show the "video part" in the detail page.  I had to click the share button then copy the url of the "video part"  and paste that url in a new tab to view the video.

Are there any additional steps need to support live photos in 'heic' files?

**Comment by zhanglix** [comment]
since the browser do not support 'heic' photos, all thumbnails except the 200x200 one are in 'heic' format and will be show as a black box.

**Comment by zhanglix** [comment]
this is a detail page of a l'ive photos' in heic format. 
<img width="637" alt="Screen Shot 2020-05-18 at 12 18 45 AM" src="https://user-images.githubusercontent.com/8109462/82153948-384bca80-989d-11ea-99cd-933cb529e279.png">

**Comment by ildyria** [comment]
We added the possibility to allow upload of other files but they will not be processed: 
https://lycheeorg.github.io/docs/settings.html#raw_formats
As a result I would rather not see `.nef` to be added as there is no support for processing.
Lychee is not made with photo editing in mind. NEF files should be imported in Lightroom or other similar software and edited there (change exposure etc). If you do not edit your pictures  (color correction) then, you have no need to shoot RAW and should directly be in JPEG (*may be a controversial statement*).

This was discussed in the past https://github.com/LycheeOrg/Lychee-v3/issues/69 

As for the video part, I did not take part into this development so I cannot really help you on that one. :|

**Comment by tmp-hallenser** [comment]
The .heic file is actually just the image, there is always a corresponding .mov file containing the video. 

you can give these files a try:
https://developer.apple.com/live-photos/assets/boy.jpg and https://developer.apple.com/live-photos/assets/boy.mov
https://developer.apple.com/live-photos/assets/girl.jpg and https://developer.apple.com/live-photos/assets/girl.mov

**Comment by zhanglix** [comment]
> We added the possibility to allow upload of other files but they will not be processed:
> https://lycheeorg.github.io/docs/settings.html#raw_formats
> As a result I would rather not see `.nef` to be added as there is no support for processing.
I am fine with that.  I have no idea why there are some photos in '.nef' format in my photo library.

> The .heic file is actually just the image, there is always a corresponding .mov file containing the video.

I got it, thank you @tmp-hallenser.

It seems that there is not any browser supporting '.heic' image now. Is it possible to indicate Lychee to return a corresponding '.jpeg' file of a  '.heic' file to the browser?

**Comment by tmp-hallenser** [comment]
@zhanglix the trick is to define .heic files as raw files (I think you can define them under settings). The config parameter is I think raw_formats.

**Comment by zhanglix** [comment]
> @zhanglix the trick is to define .heic files as raw files (I think you can define them under settings). The config parameter is I think raw_formats.

After I set raw_format as  .heic, I got an Error: " Call to undefined method App\Metadata\Extractor::validate()  " when I sync a heic photo.

@tmp-hallenser any advise ?

**Comment by zhanglix** [comment]
I can not find validate() in https://github.com/LycheeOrg/Lychee/blob/master/app/Metadata/Extractor.php

Maybe the validate() call is not needed?

**Comment by zhanglix** [comment]
@tmp-hallenser it seems that once you defined .heic as raw, Lychee will not process it at all?

**Comment by zhanglix** [comment]
I think add .heic to raw_format is not a good idea. Lychee just save it.  

I think it is better to generate jpeg thumbnails for all supported photos format.

**Comment by ildyria** [comment]
> @tmp-hallenser it seems that once you defined .heic as raw, Lychee will not process it at all?

It will allow you to upload the picture, but indeed it will not do anything photo related.

**Comment by zhanglix** [comment]
Is it possible to make lychee generate all smaller version of photos in 'jpeg' format. After all, all those photos are intended to be viewed in a browser?

**Comment by zhanglix** [comment]
Maybe there is nothing wrong with the backend.

I found this warning in the browser on the detail page of a live photo in heic fomat.

<img width="632" alt="Screen Shot 2020-05-18 at 5 35 37 PM" src="https://user-images.githubusercontent.com/8109462/82198188-8bba2900-992e-11ea-91fa-8013dccffcf4.png">

And I think the "data-video-src" of the livephoto <div> is set correctly to the corresponding mov.

And I found that the mov file's first frame is very small, but not zero?

**Comment by d7415** [comment]
> Is it possible to make lychee generate all smaller version of photos in 'jpeg' format. After all, all those photos are intended to be viewed in a browser?

This would cause problems with e.g. animated gifs.

(yes, edge case, but when HEIC is less of an edge case, I expect browser support. Though apparently there are patent issues *sigh*)

**Comment by zhanglix** [comment]
> > Is it possible to make lychee generate all smaller version of photos in 'jpeg' format. After all, all those photos are intended to be viewed in a browser?
> 
> This would cause problems with e.g. animated gifs.

Ok, I think convert all to 'jpeg' is not a great idea.

**Comment by tmp-hallenser** [comment]
Let me find some time a look into that. 

I think, the desired behavior should be (and that's how it's supposed to be implemented): Lychee generates jpgs if you specifiy the file type as raw.

**Comment by ildyria** [comment]
Lychee *tries* to generate jpgs. :wink:

**Comment by zhanglix** [comment]
May be Lychee could use something like this https://alexcorvi.github.io/heic2any/ to convert heic on the fly?

**Comment by zhanglix** [comment]
It seems that the problem is caused by livePhotosKit.js which do not support heic as a image source. May be lychee can do some specific logic in livephoto procedure? such as convert all heic photos to jpeg  and save the original file for download only.

**Comment by tmp-hallenser** [comment]
> It seems that the problem is caused by livePhotosKit.js which do not support heic as a image source. May be lychee can do some specific logic in livephoto procedure? such as convert all heic photos to jpeg and save the original file for download only.

That's the intended behavior. Let me find some time looking into it.

**Comment by tmp-hallenser** [comment]
> May be Lychee could use something like this https://alexcorvi.github.io/heic2any/ to convert heic on the fly?

Actually, you need to do the conversion on the server. iOS uploads to lychee always a jpg even if the original file is a heic.

**Comment by tmp-hallenser** [comment]
Just create #574 

This should fix the issues with EXIF data extraction (exiftool needs to be version 10.10 or newer).

**Comment by tmp-hallenser** [comment]
Briefly looked into the thumbnail generation. 

We skip the thumbnail creation currently here: https://github.com/LycheeOrg/Lychee/blob/6fd8a8585b9810ad7db3d5b67fe3fc09894d9e98/app/ModelFunctions/PhotoFunctions.php#L398

What needs to be done imho:
1. convert to raw file into a jpg and store it under 'big' 
2. make we have a proper error handling if ImageMagick is not installed
3. Make sure, all files are delete when user triggers delete

Unfortunately, I'm pretty busy this week. Do you want to give it a try?

**Comment by zhanglix** [comment]
> > May be Lychee could use something like this https://alexcorvi.github.io/heic2any/ to convert heic on the fly?
> 
> Actually, you need to do the conversion on the server. iOS uploads to lychee always a jpg even if the original file is a heic.

Actually I just rsync the entire photo library to lychee server  then sync the originals directory with lychee. So the heic photos do not get converted.


> Unfortunately, I'm pretty busy this week. Do you want to give it a try?

I wish I can but I need to learn php first.  So I think all I can do is waiting :)

**Comment by ildyria** [comment]
Also be aware that raw files can be anything... pdf etc...

> I wish I can but I need to learn php first. So I think all I can do is waiting :)

You know C++. You should not have any problem doing PHP. :)

**Comment by tmp-hallenser** [comment]
@zhanglix The PR is ready for testing (#574 )

Could give it a thorough test? (different file types and different setting (w/ and w/o exiftool, ImageMagick)

Edit: Just saw that tests are failing. Will need to fix them

**Comment by tmp-hallenser** [comment]
Now it should be ready for testing.

@zhanglix would be great if you could help with testing.

**Comment by zhanglix** [comment]
> Now it should be ready for testing.
> 
> @zhanglix would be great if you could help with testing.

cool, I'll test it today.  Will I get the latest version if I use the docker image with `dev` tag?

**Comment by ildyria** [comment]
> Will I get the latest version if I use the docker image with `dev` tag?

I think you will get the latest version of the `master` branch. You will not get the changes made by @tmp-hallenser as they live on the `fix-564` branch.

**Comment by zhanglix** [comment]
I failed to setup lychee with fix-564 branch.  Would you please push a docker image with fix-564 tag?

**Comment by zhanglix** [comment]
Yeah, It works!

**Comment by zhanglix** [comment]
I will delete all heic file from Lychee and re-sync them again to see if all live-photos works.

**Comment by zhanglix** [comment]
By the way,  since I can convert .nef photos to jpeg using imagemagick after I installed `ufraw ufraw-batch ` on my raspberry pi.
```
sudo apt-get install ufraw ufraw-batch 
```
So I add .nef to the raw_formats and install `ufraw ufraw-batch`in the lychee container.  

I think it should work well, but Lychee throws an exception when it attempts to convert .nef photos.

here is the related logs:
```
ErrorException: getimagesize(): Read error! in /var/www/html/Lychee/app/Image/GdHandler.php:145
#1 /var/www/html/Lychee/app/Image/GdHandler.php(145): getimagesize('/tmp/lycheeX8yK...')   
#2 /var/www/html/Lychee/app/Image/ImageHandler.php(59): App\Image\GdHandler->crop('/tmp/lycheeX8yK', '/var/www/html/L...', 200, 200)  
```

```
    2020-05-22 23:54:37 -- error   -- App\Image\ImagickHandler::crop -- 157 -- no decode delegate for this image format `' @ error/constitute.c/ReadImage/560
    2020-05-22 23:54:37 -- notice  -- App\ModelFunctions\PhotoFunctions::createThumb -- 539 -- Photo URL is 4e9a70576101c31cfd8eb947b9500c73.nef
    2020-05-22 23:54:37 -- notice  -- App\Image\ImagickHandler::scale -- 110 -- Saving thumb to /tmp/lycheeX8yKOg
```

btw /tmp/lycheeX8yKOg is a empty file. so it seems Lychee failed to generate it.

**Comment by ildyria** [comment]
Lychee was never meant to convert RAW files such as .nef, .cr2 .arw etc.

If you shoot RAW, it is to be able to change exposure, dodge&burn, crop... later in a proper image processing software such as Lightroom, Photoshop, Capture One, Luminar, Darktable...
otherwise you better shoot JPEG.

*Lychee does not intend to provide those functionality.*

**Comment by tmp-hallenser** [comment]
> By the way, since I can convert .nef photos to jpeg using imagemagick after I installed `ufraw ufraw-batch ` on my raspberry pi.
> 
> ```
> sudo apt-get install ufraw ufraw-batch 
> ```
> 
> So I add .nef to the raw_formats and install `ufraw ufraw-batch`in the lychee container.
> 
> I think it should work well, but Lychee throws an exception when it attempts to convert .nef photos.
> 
> here is the related logs:
> 
> ```
> ErrorException: getimagesize(): Read error! in /var/www/html/Lychee/app/Image/GdHandler.php:145
> #1 /var/www/html/Lychee/app/Image/GdHandler.php(145): getimagesize('/tmp/lycheeX8yK...')   
> #2 /var/www/html/Lychee/app/Image/ImageHandler.php(59): App\Image\GdHandler->crop('/tmp/lycheeX8yK', '/var/www/html/L...', 200, 200)  
> ```
> 
> ```
>     2020-05-22 23:54:37 -- error   -- App\Image\ImagickHandler::crop -- 157 -- no decode delegate for this image format `' @ error/constitute.c/ReadImage/560
>     2020-05-22 23:54:37 -- notice  -- App\ModelFunctions\PhotoFunctions::createThumb -- 539 -- Photo URL is 4e9a70576101c31cfd8eb947b9500c73.nef
>     2020-05-22 23:54:37 -- notice  -- App\Image\ImagickHandler::scale -- 110 -- Saving thumb to /tmp/lycheeX8yKOg
> ```
> 
> btw /tmp/lycheeX8yKOg is a empty file. so it seems Lychee failed to generate it.

just pushed another bugfix, works on my dev environment now

**Comment by tmp-hallenser** [comment]
> Lychee was never meant to convert RAW files such as .nef, .cr2 .arw etc.
> 
> If you shoot RAW, it is to be able to change exposure, dodge&burn, crop... later in a proper image processing software such as Lightroom, Photoshop, Capture One, Luminar, Darktable...
> otherwise you better shoot JPEG.
> 
> _Lychee does not intend to provide those functionality._

Agree, but with heic format support, we implicitly also support RAW files.

**Comment by zhanglix** [comment]
@tmp-hallenser I found a bug in live photos. the video part of a live photo is stored in 'big' directory, but the url set for livephotokit.js are in 'raw' directory. So livephotos  didn't show properly.

Maybe it is a 'lycheefront' bug?

or I deployed the 'lycheefront' wrong?
I just checkout the 'fix-564' branch and copied all files in app and public/dists to the Lychee container.

**Comment by zhanglix** [comment]
> > Lychee was never meant to convert RAW files such as .nef, .cr2 .arw etc.
> > _Lychee does not intend to provide those functionality._
> 
> Agree, but with heic format support, we implicitly also support RAW files.

Yes, this is what I am expecting. 

The problem now is Lychee throws an exception and stops syncing. It means if you have .nef photos in your library, you can not add them to  the raw_formats.

**Comment by zhanglix** [comment]
I fix (may be dirty) the livephotourl path, and all livephotos in .heic formats work like charm now!

**Comment by tmp-hallenser** [comment]
> @tmp-hallenser I found a bug in live photos. the video part of a live photo is stored in 'big' directory, but the url set for livephotokit.js are in 'raw' directory. So livephotos didn't show properly.
> 
> Maybe it is a 'lycheefront' bug?
> 
> or I deployed the 'lycheefront' wrong?
> I just checkout the 'fix-564' branch and copied all files in app and public/dists to the Lychee container.

Thanks, just merged it into the branch

**Comment by tmp-hallenser** [comment]
> > > Lychee was never meant to convert RAW files such as .nef, .cr2 .arw etc.
> > > _Lychee does not intend to provide those functionality._
> > 
> > 
> > Agree, but with heic format support, we implicitly also support RAW files.
> 
> Yes, this is what I am expecting.
> 
> The problem now is Lychee throws an exception and stops syncing. It means if you have .nef photos in your library, you can not add them to the raw_formats.

What's your error? It works for me

**Comment by zhanglix** [comment]
this is the exception stack. the file `/tmp/lycheeRDyB` is empty.
```php
Start syncing.
Status: /conf/dev: 0%
Status: /conf/dev: 100%
Status: /conf/dev/test/: 0%
ErrorException: getimagesize(): Read error! in /var/www/html/Lychee/app/Image/GdHandler.php:145
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'getimagesize():...', '/var/www/html/L...', 145, Array)                                                           
#1 /var/www/html/Lychee/app/Image/GdHandler.php(145): getimagesize('/tmp/lycheeRDyB...')
#2 /var/www/html/Lychee/app/Image/ImageHandler.php(59): App\Image\GdHandler->crop('/tmp/lycheeRDyB...', '/var/www/html/L...', 200, 200)                                                                    
#3 /var/www/html/Lychee/app/ModelFunctions/PhotoFunctions.php(547): App\Image\ImageHandler->crop('/tmp/lycheeRDyB...', '/var/www/html/L...', 200, 200)                                                     
#4 /var/www/html/Lychee/app/ModelFunctions/PhotoFunctions.php(411): App\ModelFunctions\PhotoFunctions->createThumb(Object(App\Photo), '/tmp/lycheeRDyB...')                                                 
#5 /var/www/html/Lychee/app/Http/Controllers/ImportController.php(81): App\ModelFunctions\PhotoFunctions->add(Array, 1589649469, false, true)                                                               
#6 /var/www/html/Lychee/app/Http/Controllers/ImportController.php(369): App\Http\Controllers\ImportController->photo('/conf/dev/test/...', false, 1589649469, true)                                         
#7 /var/www/html/Lychee/app/Http/Controllers/ImportController.php(405): App\Http\Controllers\ImportController->server_exec('/conf/dev/test', 1589649469, false, true, NULL)                                 
#8 /var/www/html/Lychee/app/Console/Commands/Sync.php(85): App\Http\Controllers\ImportController->server_exec('/conf/dev', 0, false, true)                                                                  
#9 [internal function]: App\Console\Commands\Sync->handle()                                                                                                                                                 
#10 /var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(33): call_user_func_array(Array, Array)                                                                          
#11 /var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()                                                 
#12 /var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(91): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))                                                 
#13 /var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#14 /var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Container/Container.php(592): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)        
#15 /var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\Container\Container->call(Array)                                                                      
#16 /var/www/html/Lychee/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))    
#17 /var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#18 /var/www/html/Lychee/vendor/symfony/console/Application.php(912): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/html/Lychee/vendor/symfony/console/Application.php(264): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\Sync), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/html/Lychee/vendor/symfony/console/Application.php(140): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/html/Lychee/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))               
#24 {main}                                                                                                                                                                                                  
Done syncing.

```

**Comment by zhanglix** [comment]
And I think this error is more useful.

```
    2020-05-23 14:14:55 -- error   -- App\Image\ImagickHandler::crop -- 157 -- no decode delegate for this image format `' @ error/constitute.c/ReadImage/560

```

**Comment by zhanglix** [comment]
ImagickHandler->crop() failed to crop it  and caught the exception.
GdHandler->crop() didn't catch exception which causes the sync process aborted. 
Maybe Lychee need catch exceptions in GdHandler->crop() .

**Comment by zhanglix** [comment]
But I think the root cause is why the image being cropped is empty?
It seems that 	createJpgFromRaw() return a empty file?	
```	php			
    if ($kind == 'raw') {
        try {
            $frame_tmp = $this->createJpgFromRaw($photo);
       } catch (Exception $exception) {
           Logs::error(__METHOD__, __LINE__, $exception->getMessage());
       }
   }
```

**Comment by tmp-hallenser** [comment]
Hm, are you able to do the conversion using the command line? Just tried raw, new, cr2, heic and they were all working on dev environment.

**Comment by zhanglix** [comment]
I installed imagemagick in the container succeed to convert .nef to jpeg with /usr/bin/convert.

Ps: the .nef I used for testing:
[1B6AB843-376F-4FA4-B303-CF43A7DA1099_4.nef.zip](https://github.com/LycheeOrg/Lychee/files/4671344/1B6AB843-376F-4FA4-B303-CF43A7DA1099_4.nef.zip)

**Comment by zhanglix** [comment]
> I installed imagemagick in the container succeed to convert .nef to jpeg with /usr/bin/convert.
> 
> Ps: the .nef I used for testing:
> [1B6AB843-376F-4FA4-B303-CF43A7DA1099_4.nef.zip](https://github.com/LycheeOrg/Lychee/files/4671344/1B6AB843-376F-4FA4-B303-CF43A7DA1099_4.nef.zip)

it seems that some heic photos will cause exception now too.  I created an issue for more robust syncing.  https://github.com/LycheeOrg/Lychee/issues/592

**Comment by tmp-hallenser** [comment]
> > I installed imagemagick in the container succeed to convert .nef to jpeg with /usr/bin/convert.
> > Ps: the .nef I used for testing:
> > [1B6AB843-376F-4FA4-B303-CF43A7DA1099_4.nef.zip](https://github.com/LycheeOrg/Lychee/files/4671344/1B6AB843-376F-4FA4-B303-CF43A7DA1099_4.nef.zip)
> 
> it seems that some heic photos will cause exception now too. I created an issue for more robust syncing. #592

Could you share some photos throwing exceptions? That would help debugging.

**Comment by tmp-hallenser** [comment]
> I installed imagemagick in the container succeed to convert .nef to jpeg with /usr/bin/convert.
> 
> Ps: the .nef I used for testing:
> [1B6AB843-376F-4FA4-B303-CF43A7DA1099_4.nef.zip](https://github.com/LycheeOrg/Lychee/files/4671344/1B6AB843-376F-4FA4-B303-CF43A7DA1099_4.nef.zip)

Works for me with the latest fix. Please give it a second try.

**Comment by zhanglix** [comment]
> > I installed imagemagick in the container succeed to convert .nef to jpeg with /usr/bin/convert.
> > Ps: the .nef I used for testing:
> > [1B6AB843-376F-4FA4-B303-CF43A7DA1099_4.nef.zip](https://github.com/LycheeOrg/Lychee/files/4671344/1B6AB843-376F-4FA4-B303-CF43A7DA1099_4.nef.zip)
> 
> Works for me with the latest fix. Please give it a second try.

Woo!  It works to sync .nef now. 

There is still a problem with the detail pages of .nef photos. Lychee only generate one thumbnail of 200x200 for .nef so that the detail page can not show the photo.

It seems due to that Lychee extracted wrong dimensions of the photo?  
The actual size of the attached .nef photo is 4352x2868 while what extracted is 160x120
``` mysql
MariaDB [photos]> select * from photos where url like '%.nef' limit 10\G
*************************** 1. row ***************************
                id: 1590287393
             title: test_nef.nef
       description:
               url: 85920e8de86b15a6925e185bc1662866.nef
              tags:
            public: 0
          owner_id: 0
              type: raw
             width: 160
            height: 120
              size: 9.6 MB
               iso: 400
          aperture: f/5.6
              make: NIKON CORPORATION
             model: NIKON D5000
              lens:
           shutter: 1/3200 s
             focal: 70 mm
          latitude: NULL
         longitude: NULL
          altitude: NULL
      imgDirection: NULL
          location: NULL
         takestamp: 2017-01-25 14:01:02
              star: 0
          thumbUrl: 85920e8de86b15a6925e185bc1662866.jpeg
      livePhotoUrl: NULL
          album_id: 1589649469
          checksum: d094e34607e9ef891ee1dd58e4b11d1d9be7c70c
 livePhotoChecksum: NULL
           license: none
        created_at: 2020-05-24 10:30:52
        updated_at: 2020-05-24 10:30:52
            medium:
          medium2x:
             small:
           small2x:
           thumb2x: 0
livePhotoContentID: NULL
1 row in set (0.15 sec)
```

**Comment by zhanglix** [comment]
> > > I installed imagemagick in the container succeed to convert .nef to jpeg with /usr/bin/convert.
> > > Ps: the .nef I used for testing:
> > > [1B6AB843-376F-4FA4-B303-CF43A7DA1099_4.nef.zip](https://github.com/LycheeOrg/Lychee/files/4671344/1B6AB843-376F-4FA4-B303-CF43A7DA1099_4.nef.zip)
> > 
> > 
> > it seems that some heic photos will cause exception now too. I created an issue for more robust syncing. #592
> 
> Could you share some photos throwing exceptions? That would help debugging.

I located the file caused the exception.  The latest fix has fixed all of the problems but an empty thumbnail. 😃  

In case you are interested:

It is a video in a rare case that the video track duration is shorter than half of duration of the audio track.  When Lychee trying to extract a frame at the 'middle position',  it got nothing.

[meta_info.txt](https://github.com/LycheeOrg/Lychee/files/4672886/meta_info.txt)

**Comment by zhanglix** [comment]
> It seems due to that Lychee extracted wrong dimensions of the photo?
> The actual size of the attached .nef photo is 4352x2868 while what extracted is 160x120

It seem the latest fix introduced some bugs? It failed to process heic too .
[live_photo_in_heic.zip](https://github.com/LycheeOrg/Lychee/files/4672912/live_photo_in_heic.zip)

**Comment by zhanglix** [comment]
there are some error in the logs:

```php
    2020-05-24 11:47:45 -- error   -- App\ModelFunctions\PhotoFunctions::add -- 406 -- Division by zero
    2020-05-24 11:47:45 -- error   -- App\Image\ImagickHandler::scale -- 116 -- Invalid image geometry
    2020-05-24 11:47:44 -- notice  -- App\ModelFunctions\PhotoFunctions::createJpgFromRaw -- 507 -- Saving JPG of raw file to /tmp/lycheeGkl9eH.jpeg
    2020-05-24 11:47:44 -- error   -- App\Metadata\Extractor::extract -- 129 -- readlink(): Invalid argument
```
the exception of 'readlink()' caused all data in exif lost.

**Comment by zhanglix** [comment]
I did two dirty tricks, and everything seems work very well:

* comment out some code in Extrator.php, 
* hardcoded to extract frame from video at 0.1 second, then everything seems works well. 

Since it can not be called a fix, I just post the code here for reference only.

```php
// in Extractor.php line 115-138
               try {
			// this can throw an exception in the case of Exiftool adapter!
			$exif = $reader->read($filename);

			// if readlink($filename) == False then $realFile = $filename.
			// if readlink($filename) != False then $realFile = readlink($filename)
			// $realFile = readlink($filename) ? readlink($filename) : $filename;
			// if (Configs::hasExiftool() && file_exists($realFile . '.xmp')) {
			// 	// Don't use the same reader as the file in case it's a video
			// 	$sidecarReader = Reader::factory(Reader::TYPE_EXIFTOOL);
			// 	$sidecarData = $sidecarReader->read($realFile . '.xmp')->getData();
			// }
		} catch (\Exception $e) {
			// Use Php native tools
			Logs::error(__METHOD__, __LINE__, $e->getMessage());
			$reader = Reader::factory(Reader::TYPE_NATIVE);
			$exif = $reader->read($filename);
		}

		// if (Configs::get_value('prefer_available_xmp_metadata', '0') == '1') {
		// 	$exif->setData(array_merge($exif->getData(), $sidecarData));
		// } else {
		// 	$exif->setData(array_merge($sidecarData, $exif->getData()));
		// }

// in Extractor.php line  231
			// Video -> reuse fields
                        // $metadata['aperture'] = ($exif->getDuration() !== false) ? $exif->getDuration() : '';
			$metadata['aperture'] = '0.2'; #hard coded to small values
```

**Comment by tmp-hallenser** [comment]
The provided heic files should be working now. Would you mind sharing a failing video?

Disclaimer: Some images fail if you don't have exiftool installed. Imagick does the extraction of meta data fine, but reports a wrong width and height in some case (which causes an error eventually and thumbnails not being created)

**Comment by zhanglix** [comment]
> The provided heic files should be working now. Would you mind sharing a failing video?
> 

Cool. I will give it a try today.  

I synthesize one according to my failing video and verified that it will cause the same exception.
[test.mp4.zip](https://github.com/LycheeOrg/Lychee/files/4674884/test.mp4.zip)


> Disclaimer: Some images fail if you don't have exiftool installed. Imagick does the extraction of meta data fine, but reports a wrong width and height in some case (which causes an error eventually and thumbnails not being created)

This is not my cases since I am using a docker image provided by lychee.

**Comment by zhanglix** [comment]
@tmp-hallenser  the latest version of branch fix-564 works well on `.nef` and `.heic` photos.

And the failing video will still stop the syncing process. 

 I think don't let any individual photo (whether it is a corrupted file, or with an incorrect extension) stop Lychee from syncing other photos would be a good idea.

**Comment by d7415** [comment]
> It is a video in a rare case that the video track duration is shorter than half of duration of the audio track. When Lychee trying to extract a frame at the 'middle position', it got nothing.

That sounds corrupted?

**Comment by tmp-hallenser** [comment]
please give it another try.

**Comment by zhanglix** [comment]
It works for all my cases now:

- [x]  .heic with livephoto support
- [x]  .nef photos
- [x]  videos with extremely short "Track Duration" 

👍👍👍 @tmp-hallenser 😎

**Comment by zhanglix** [comment]
> > It is a video in a rare case that the video track duration is shorter than half of duration of the audio track. When Lychee trying to extract a frame at the 'middle position', it got nothing.
> 
> That sounds corrupted?

I think it is not corrupted since it is in well format. 

But you can get corrupted photos/videos if you are `scp`-ing photos to the server running Lychee when a network problem occurred.  So use `rsync` whenever possible.

**Comment by d7415** [comment]
> I think it is not corrupted since it is in well format.

Perhaps. I'd think "audio track length is similar to video track length" should be a safe assumption though. If someone wants to fix that, then fine, but I'm ok with that failing.

**Comment by ildyria** [comment]
is this one fixed?

**Comment by tmp-hallenser** [comment]
the video issue should be fixed.

**Comment by zhanglix** [comment]
BTW: 
Please DO NOT forget to install  `ufraw`, `ufraw-batch` in the released Lychee Docker Image.
