### ISSUE TITLE
Possible missing dependency: predis

### ISSUE THREAD

**Issue by d7415** [LycheeOrg/Lychee#566]
From LycheeOrg/Lychee-Laravel-Docker#53

> OS:raspberry 4B arm64
> docker:lycheeorg/lychee-laravel:latest
> 
> In the file '.env' 'CACHE_DRIVER=redis' then appears an error
> 
> ErrorClass 'Predis\Client' not found
> --
> in PredisConnector.php line 29
> at PredisConnector->connect(array('host' => '127.0.0.1', 'password' => null, 'port' => 6379, 'database' => 0), array())in RedisManager.php line 110

At a quick glance, it looks like `predis` is only listed as a "dev" requirement (admittedly for several of Lychee's requirements) so is not installed with `--no-dev`.

I'm not sure whether this is our problem or upstream.

**Comment by ildyria** [comment]
https://laravel.com/docs/7.x/redis

as said here: 

> **Predis has been abandoned by the package's original author and may be removed from Laravel in a future release.**

As a result I would not encourage further development in that direction.

**Comment by d7415** [comment]
Ok. Looks like php-redis is a sub, but needs to be installed via pecl or a package manager. I'll close this and return to the LLD issue.
