### ISSUE TITLE
Albums:get() returns empty thumbs array

### ISSUE THREAD

**Issue by markoph** [LycheeOrg/Lychee#567]
### Detailed description of the problem [REQUIRED]

`Albums:get()` returns empty thumbs field for album "MyPublicAlbum" which contains same photo as "Recent" smart album. Because of that (I guess) I don't see thumbnails for my albums...

Response from `Albums::get()`:

```json
{
   "smartalbums":{
      "unsorted":{
         "thumbs":[

         ],
         "thumbs2x":[

         ],
         "types":[

         ],
         "num":"0"
      },
      "public":{
         "thumbs":[

         ],
         "thumbs2x":[

         ],
         "types":[

         ],
         "num":"0"
      },
      "starred":{
         "thumbs":[

         ],
         "thumbs2x":[

         ],
         "types":[

         ],
         "num":"0"
      },
      "recent":{
         "thumbs":[
            "uploads\/thumb\/431503ef84e6769587a85cdb6f16da4d.jpeg"
         ],
         "thumbs2x":[
            "uploads\/thumb\/431503ef84e6769587a85cdb6f16da4d@2x.jpeg"
         ],
         "types":[
            "image\/jpeg"
         ],
         "num":"1"
      }
   },
   "albums":[
      {
         "id":"15895819761973",
         "title":"MyPublicAlbum",
         "public":"1",
         "full_photo":"1",
         "visible":"1",
         "parent_id":null,
         "description":"My album",
         "downloadable":"0",
         "share_button_visible":"0",
         "sysdate":"May 2020",
         "min_takestamp":"",
         "max_takestamp":"",
         "password":"0",
         "license":"none",
         "thumbs":[

         ],
         "thumbs2x":[

         ],
         "types":[

         ],
         "owner":"Admin",
         "albums":[

         ]
      }
   ],
   "shared_albums":[

   ]
}
```

Response from `Album::get()` after entering album:

```json
{
   "id":"15895819761973",
   "title":"MyPublicAlbum",
   "public":"1",
   "full_photo":"1",
   "visible":"1",
   "parent_id":null,
   "description":"My album",
   "downloadable":"0",
   "share_button_visible":"0",
   "sysdate":"May 2020",
   "min_takestamp":"",
   "max_takestamp":"",
   "password":"0",
   "license":"none",
   "thumbs":[

   ],
   "thumbs2x":[

   ],
   "types":[

   ],
   "owner":"Admin",
   "albums":[

   ],
   "photos":[
      {
         "id":"15895820037283",
         "title":"laniaka_cluster_-_milky_way",
         "tags":"",
         "star":"0",
         "album":"15895819761973",
         "width":"1200",
         "height":"800",
         "type":"image\/jpeg",
         "size":"208.5 KB",
         "iso":"",
         "aperture":"",
         "make":"",
         "model":"",
         "shutter":"",
         "focal":"",
         "lens":"",
         "latitude":null,
         "longitude":null,
         "altitude":null,
         "imgDirection":null,
         "location":null,
         "livePhotoContentID":null,
         "sysdate":"16 May 2020",
         "description":"",
         "license":"none",
         "medium":"",
         "medium_dim":"",
         "medium2x":"",
         "medium2x_dim":"",
         "small":"uploads\/small\/431503ef84e6769587a85cdb6f16da4d.jpeg",
         "small_dim":"540x360",
         "small2x":"uploads\/small\/431503ef84e6769587a85cdb6f16da4d@2x.jpeg",
         "small2x_dim":"1080x720",
         "thumbUrl":"uploads\/thumb\/431503ef84e6769587a85cdb6f16da4d.jpeg",
         "thumb2x":"uploads\/thumb\/431503ef84e6769587a85cdb6f16da4d@2x.jpeg",
         "url":"uploads\/big\/431503ef84e6769587a85cdb6f16da4d.jpeg",
         "livePhotoUrl":null,
         "cameraDate":"0",
         "takedate":"",
         "public":"2",
         "previousPhoto":"",
         "nextPhoto":""
      }
   ],
   "num":"1"
}
```
Logs:

```
    2020-05-16 01:13:08 -- notice  -- App\Metadata\GitHubFunctions::__construct -- 49 -- file_get_contents(/data/6/1/61e2f2a8-2ef1-4444-bf07-ae6f0b10f25c/ukazkovagaleria.sk/lychee/.git/HEAD): failed to open stream: No such file or directory
    2020-05-16 01:13:05 -- notice  -- App\Metadata\GitHubFunctions::__construct -- 49 -- file_get_contents(/data/6/1/61e2f2a8-2ef1-4444-bf07-ae6f0b10f25c/ukazkovagaleria.sk/lychee/.git/HEAD): failed to open stream: No such file or directory
    2020-05-16 01:11:32 -- notice  -- App\Image\ImagickHandler::scale -- 110 -- Saving thumb to /data/6/1/61e2f2a8-2ef1-4444-bf07-ae6f0b10f25c/ukazkovagaleria.sk/lychee/public/uploads/small/7175792b468a75be1cd84b599cbf40bf@2x.jpg
    2020-05-16 01:11:32 -- notice  -- App\Image\ImagickHandler::scale -- 110 -- Saving thumb to /data/6/1/61e2f2a8-2ef1-4444-bf07-ae6f0b10f25c/ukazkovagaleria.sk/lychee/public/uploads/small/7175792b468a75be1cd84b599cbf40bf.jpg
    2020-05-16 01:11:32 -- notice  -- App\ModelFunctions\PhotoFunctions::resizePhoto -- 645 -- No resize (image is too small: 3840x2160)!
    2020-05-16 01:11:32 -- notice  -- App\ModelFunctions\PhotoFunctions::resizePhoto -- 645 -- No resize (image is too small: 1920x1080)!
    2020-05-16 01:11:32 -- notice  -- App\Image\ImagickHandler::crop -- 153 -- Saving thumb to /data/6/1/61e2f2a8-2ef1-4444-bf07-ae6f0b10f25c/ukazkovagaleria.sk/lychee/public/uploads/thumb/7175792b468a75be1cd84b599cbf40bf@2x.jpeg
    2020-05-16 01:11:32 -- notice  -- App\Image\ImagickHandler::crop -- 153 -- Saving thumb to /data/6/1/61e2f2a8-2ef1-4444-bf07-ae6f0b10f25c/ukazkovagaleria.sk/lychee/public/uploads/thumb/7175792b468a75be1cd84b599cbf40bf.jpeg
    2020-05-16 01:11:32 -- notice  -- App\ModelFunctions\PhotoFunctions::createThumb -- 500 -- Photo URL is 7175792b468a75be1cd84b599cbf40bf.jpg
    2020-05-16 01:11:32 -- error   -- App\Metadata\Extractor::extract -- 104 -- Could not decode exiftool output
```

I see similar (closed) issue in frontend repository https://github.com/LycheeOrg/Lychee-front/issues/198. But `2020-05-16 01:11:32 -- error   -- App\Metadata\Extractor::extract -- 104 -- Could not decode exiftool output` is not mentioned.

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Clean installation _(tried all version from v4.0.0 to last v4.0.5; tried also git clone...; DB & files always removed before testing new version)_. All steps required to get Lychee running _(env, artisan  keg:generate, artisan migrate)_.
2. Upload new photo. It's immediately visible in "Unsorted" smart album as thumbnail.
3. Open Unsorted. Move photo to new album (doesn't matter if album was created before move; or through move process). Photo is now visible as thumbnail in Recent smart album. New album was added but it doesn't have thumbnail.
4. Open album. Photo is present.
5. Return to dashboard. Still no thumbnail.

**Screenshots**
I recoreded what happens when I try to move photo to album. https://www.dropbox.com/s/r1p7w0otce69dzd/lychee_issue_with_thumbs_2020-05-16T01-27.mp4?dl=0

### Output of the diagnostics  [REQUIRED]

    Diagnostics
    -------
    Warning: Dropbox import not working. dropbox_key is empty.

    System Information
    --------------
    Lychee Version (release):   4.0.5
    DB Version:                 4.0.5
    
    composer install:           --no-dev
    APP_ENV:                    production
    APP_DEBUG:                  true
    
    System:                     Linux
    PHP Version:                7.4
    MySQL Version:              10.3.21-MariaDB-1:10.3.21+maria~xenial-log
    
    Imagick:                    1
    Imagick Active:             1
    Imagick Version:            1673
    GD Version:                 bundled (2.1.0 compatible)

    Config Information
    --------------
    version:                    040005
    check_for_updates:          0
    sorting_Photos_col:         takestamp
    sorting_Photos_order:       ASC
    sorting_Albums_col:         max_takestamp
    sorting_Albums_order:       ASC
    imagick:                    1
    skip_duplicates:            0
    small_max_width:            0
    small_max_height:           360
    medium_max_width:           1920
    medium_max_height:          1080
    lang:                       en
    layout:                     1
    image_overlay:              1
    image_overlay_type:         desc
    default_license:            none
    compression_quality:        90
    full_photo:                 1
    delete_imported:            0
    Mod_Frame:                  1
    Mod_Frame_refresh:          30
    thumb_2x:                   1
    small_2x:                   1
    medium_2x:                  1
    landing_page_enable:        0
    landing_owner:              John Smith
    landing_title:              John Smith
    landing_subtitle:           Cats, Dogs & Humans Photography
    landing_facebook:           https://www.facebook.com/JohnSmith
    landing_flickr:             https://www.flickr.com/JohnSmith
    landing_twitter:            https://www.twitter.com/JohnSmith
    landing_instagram:          https://instagram.com/JohnSmith
    landing_youtube:            https://www.youtube.com/JohnSmith
    landing_background:         dist/cat.jpg
    site_title:                 Lychee v4
    site_copyright_enable:      1
    site_copyright_begin:       2019
    site_copyright_end:         2019
    additional_footer_text:     
    display_social_in_gallery:  0
    public_search:              0
    SL_enable:                  0
    SL_for_admin:               0
    public_recent:              0
    recent_age:                 1
    public_starred:             0
    downloadable:               0
    photos_wraparound:          1
    map_display:                0
    zip64:                      1
    map_display_public:         0
    map_provider:               Wikimedia
    force_32bit_ids:            0
    map_include_subalbums:      0
    update_check_every_days:    3
    has_exiftool:               1
    share_button_visible:       0
    import_via_symlink:         0
    has_ffmpeg:                 1
    location_decoding:          0
    location_decoding_timeout:  30
    location_show:              1
    location_show_public:       0
    rss_enable:                 0
    rss_recent_days:            7
    rss_max_items:              100

### Browser and system

System: Fedora 30, x86_64 Linux 5.5.8-100.fc30.x86_64
Browsers:
- Firefox 74.0 (64-bit)
- Google Chrome Version 81.0.4044.138 (Official Build) (64-bit)

**Comment by ildyria** [comment]
Hi, first of all, thank you a lot for providing us so many details. It helps a lot and is really appreciated.

That is really surprising as I cannot reproduce the error. :(

**Comment by markoph** [comment]
Hi,
no problem. I was unable to reproduce error on localhost myself yesterday. Today I used good old "var_dump debugging" method on server and fixed it few minutes before your comment.

In [app/ModelFunctions/AlbumFunctions.php#L145](https://github.com/LycheeOrg/Lychee/blob/6d93437eac3250f075e65df60f81f1aaf8bb4257/app/ModelFunctions/AlbumFunctions.php#L145) is `get_thumbs()` function with SQL statement builder:

```php
$photos = Photo::whereIn('album_id', $album_list)
	->orWhereIn('id', $childThumbIDs)
    	->orderBy('star', 'DESC')
	->orderBy(Configs::get_value('sorting_Photos_col'), Configs::get_value('sorting_Photos_order'))
	->orderBy('id', 'ASC')
	->limit(3)
	->get();
```

Values in `$album_list` are integer and query returned empty set. When I cast values of array to string, it works:

```php
$album_list = array_map('strval', $album_list);
$photos = Photo::whereIn('album_id', $album_list)
	->orWhereIn('id', $childThumbIDs)
	->orderBy('star', 'DESC')
	->orderBy(Configs::get_value('sorting_Photos_col'), Configs::get_value('sorting_Photos_order'))
	->orderBy('id', 'ASC')
	->limit(3)
	->get();
```

But I am not sure if there is some underlying issue or it's just some kind of server / DB incompatibility / strictness.

---

Do you want me to make PR with that one line or will you investigate further?

**Comment by ildyria** [comment]
By the way, with Laravel, the best way to do `var_dump($var)` debugging is actually to use `dd($var)`.
`dd($var)` will exit the script immediately but also provide a nice way to inspect variables. This is particularly useful for Objects. :)

**Comment by ildyria** [comment]
> But I am not sure if there is some underlying issue or it's just some kind of server / DB incompatibility / strictness.

That is likely to be my first guess too.

Congrats for debugging that one. :+1: Feel free to submit a PR. I can hardly see how I can investigate this further as I cannot reproduce the issue on my side. :sweat_smile: 

If you make a PR, don't forget to do `make formatting` in order to comply with the code style. :smiley:

**Comment by markoph** [comment]
FYI: No PR with this "hotfix" for now. I still don't like idea of casting integers to string (column in DB is bigint) and I need to understand what happend there `¯⁠\_(ツ)_/⁠¯`

I'll be be playing with Lychee and this particular installation more in the next few weeks. I'll try to find out more and return to you. Go ahead if you want to close issue until I have update.

**Comment by ildyria** [comment]
I will leave it open for now. :)

**Comment by ildyria** [comment]
@markoph can you have a look at the latest master version to see if that problem is still present or not ?

**Comment by markoph** [comment]
I was thinking about this bug yesterday. I'll have time next Monday so I'll update Lychee and try to reproduce bug on server in question. Thank you for ping :)

**Comment by markoph** [comment]
I am unable to reproduce issue I had. Looks like you fixed it "proper" way :) Thank you very much :+1:
