### ISSUE TITLE
[Enhancement] Multithreading

### ISSUE THREAD

**Issue by ghost** [LycheeOrg/Lychee#569]
*Explain in a few words which functionality or improvements you would like to see in Lychee.*
I'm trying to run `php artisan lychee:sync [directory]` to import all of my photos to Lychee, but it takes a very long time (a single directory/album with 500 photos took 4 hours to import) and I see that the app only uses 1 core for that.

![image](https://user-images.githubusercontent.com/51246620/82123566-5e3c7680-979a-11ea-8a7b-f7c3e7831c6a.png)

Is there a way to make it quicker?

**Comment by d7415** [comment]
It looks like this might be possible with `pthreads`. I don't think it's a high priority for us, but a PR would be interesting :)

**Comment by ildyria** [comment]
Good readings on the subject:
- https://github.com/krakjoe/parallel
- https://www.php.net/parallel

**Comment by pchampio** [comment]
Splitting the directory into 4 smaller one, and running multiple `php artisan lychee:sync [directory]/split{0,1,2,3}` might simply do the trick?
Implementing Multithreading inside the lychee command is not necessary in my opinion.

**Comment by nagmat84** [comment]
Can this issue be closed? It seems that the original issue has been solved by a work-around outside of Lychee.
