### ISSUE TITLE
[Enhancement] Upgrade for Version 4 on Sandstorm App Market?

### ISSUE THREAD

**Issue by JS-E** [LycheeOrg/Lychee#572]
Hey there!

Started using Lychee on my Sandstorm instance and i really like it, but i want to upgrade and get some of the cool updates you've added 👍 

Could the version on the Sandstorm app market be updated?

Thanks

**Comment by ildyria** [comment]
I don't know what Sandstorm is. We have no contact with them.

**Comment by JS-E** [comment]
Apologies, i didn't know this might be seperate from the Sandstorm version. https://sandstorm.io/ <- That's sandstorm and here is Lychee on the app market -> https://apps.sandstorm.io/app/z6rj6js4h8p8rjz2myp3dwmv3mcfv40qyfdn0d7714qxzvzvq3w0 App Market

**Comment by d7415** [comment]
Based on that page, you need to contact Jason Paryani.
