### ISSUE TITLE
[Enhancement] Support XMP sidecar files

### ISSUE THREAD

**Issue by alex-phillips** [LycheeOrg/Lychee#575]
I'm managing all of my photos through Digikam and have opted to not write / directly modify my images and instead write all metadata to XMP sidecar files. Would be great if lychee, when running `lychee:sync` could identify these files and use the metadata from them instead of the image (or use the image metadata and overwrite values from the XMP file if the field exists in both).

I'd be happy to help implement, but wanted to be sure this was of interest. Could also be controlled via an advanced config setting.

**Comment by alex-phillips** [comment]
I would also want XMP keywords to be converted into 'tags' in lychee so photos can be imported and already be tagged based on their metadata.

**Comment by tmp-hallenser** [comment]
I'd support that (although I'd add an option if image metadata or xmp data has higher priority)

**Comment by ildyria** [comment]
I support that too. Unfortunately I am lacking the time to implement it.

**Comment by alex-phillips** [comment]
@ildyria Exiftool actually already supports XMP files, so reading these in and merging the data turned out to be super simple: https://github.com/LycheeOrg/Lychee/pull/577
