### ISSUE TITLE
[Enhancement] Put the entire way to go to the directory (chemin-de-fer) in place of te directory in the top of the page

### ISSUE THREAD

**Issue by JacquelinDV** [LycheeOrg/Lychee#576]
Bonsoir,
In my albums I have some directory with the same name (Month, Year, Place... for example).
I think it will be cool to have in the top of all the album pages the way to arrive at this page, for example: Perso > 2008 > July > Biarritz or Rugby > 2010 > July > Biarritz...
Merci

**Comment by ildyria** [comment]
1 - This is front end related.
2 - already considered. See here: https://github.com/LycheeOrg/Lychee-front/issues/166

:smiley:
