### ISSUE TITLE
[Enhancement] Ghostbuster command to clean up dead symlinks

### ISSUE THREAD

**Issue by alex-phillips** [LycheeOrg/Lychee#578]
I'm importing my library via symlinks and the `lychee:sync` command but it doesn't look like the sync command removes photos if the image from the source directory is no longer there. I would opt to extend (or implement a new command) that scans the "big" directory for dead symlinks and cleans them up and removes them from the database.

I'm happy to implement this if it is something that will be accepted.

**Comment by ildyria** [comment]
> scans the "big" directory for dead symlinks and cleans them up and removes them from the database.

I think that indeed extending the `ghostbuster` command with this would be a great idea. :+1:
