### ISSUE TITLE
Picture ordering in albums

### ISSUE THREAD

**Issue by ildyria** [LycheeOrg/Lychee#58]
It would be nice if that setting can be adjusted per album instead of just server wide.
A default system like for licences would be convenient.

Use case: we might want some albums ordered by take date, others by title...

Additionally adding the possibility to reorder manually the pictures inside an album would be a nice addition. Something similar was already implemented in an old version of Lychee (after the fork but on the original repo). To manually reorder some pictures a lock key would be convenient to prevent users from moving pictures from A to B without wanting it.

**Comment by mck182** [comment]
I just wanted to add my support for this - I have exactly
those usecases - may different albums which simply
require different sorting options.

Having this would be really great!

**Comment by craig9** [comment]
I would also love a drag-drop sort option if that is possible.

**Comment by WWebber** [comment]
Yes, I also need an option for ordering images. At least by editing the index somehow..

**Comment by pa810p** [comment]
any release date planned for this feature?

**Comment by d7415** [comment]
> any release date planned for this feature?

I don't think anyone's actively working on it at the moment. PRs are welcome though!

**Comment by kamil4** [comment]
Well, it is listed under the [v4.0.2 milestone](https://github.com/LycheeOrg/Lychee-Laravel/milestone/3). In other words: we would prefer to push v4 out of the door first and *then* add this feature in a subsequent minor release.

**Comment by liqube** [comment]
That would be mighty nice indeed, and being able to set a album cover without staring

**Comment by Betalord** [comment]
I would like to propose this change too, that is an ability to order images arbitrarily (by drag dropping them or by some other mechanism). It seems a very basic feature for an album software, so should be prioritized in my opinion.

**Comment by ildyria** [comment]
> any release date planned for this feature?

Today.
