### ISSUE TITLE
[Enhancement] Default to RSS 2.0 to support enclosure tag

### ISSUE THREAD

**Issue by bennettscience** [LycheeOrg/Lychee#584]
I'm glad to see feeds in the last release!

The feed defaults to Atom 1.0, which doesn't support linking media. What do you think about defaulting to RSS 2.0 which would allow the actual image to be sent along in the feed? It would take a couple template tweaks in the `laravel-feed` views and a couple lines in the controller file.

**Comment by ildyria** [comment]
Feel free to open a PR ! :smiley:

**Comment by bennettscience** [comment]
Because I'm still not super familiar with Laravel, if I update the templates in the `vendor/` directory, will those be overwritten if you update the package with composer in the future?

**Comment by ildyria** [comment]
anything in vendor should not be edited as this will not be taken by Git for once and this will likely be overwritten by composer yes.

**Comment by ildyria** [comment]
What you can do however is : 
```
php artisan vendor:publish --provider="Spatie\Feed\FeedServiceProvider" --tag="views"
```

This will publish the rss views in the `resources/` folder, allowing you to modify them.
