### ISSUE TITLE
Uppercase and lowercase letters in the username

### ISSUE THREAD

**Issue by HansYeoh** [LycheeOrg/Lychee#593]
I don't know if it's bug. If I creat an account "Weirdo", then I can log in with username "weirdo" and same password. But I can't see any images which upload  by "Weirdo".

This is "Weirdo"
![Weirdo](https://user-images.githubusercontent.com/23377286/82736262-eef6f180-9d5a-11ea-9159-e185f5912cd5.jpg)
This is "weirdo"
![weirdo2](https://user-images.githubusercontent.com/23377286/82736266-f3bba580-9d5a-11ea-8b40-4a5a7308dc92.jpg)
This is the Settings page（weirdo）
![seeting_weirdo2](https://user-images.githubusercontent.com/23377286/82736283-08983900-9d5b-11ea-85c7-274e922b1828.jpg)
This is the Settings page（Weirdo）
![seeting_weirdo](https://user-images.githubusercontent.com/23377286/82736286-0df58380-9d5b-11ea-9d1b-caf508973046.jpg)

**Comment by ildyria** [comment]
That's weird.

**Comment by HansYeoh** [comment]
> That's weird.

I can create an account for you to test if necessary.I can email you the username and password.

**Comment by ildyria** [comment]
I already tested on a local, indeed, the login is working if you are providing the username without the capital letters. I'm not worried for the password as this one is hashed. But still this is surprising.

**Comment by ildyria** [comment]
Okay, good news. We enforce uniqueness of the username. So you cannot create 2 users named: `Test` and `test`

**Comment by HansYeoh** [comment]
Yeah if I create one account "Weirdo" then I can't create another account "weirdo" but I can still use both. And it seems that these two accounts are separate.

**Comment by ildyria** [comment]
Can you double check this upload, and visible image. I cannot reproduce here.
And the code is clear, it is the user ID that is being stored, so if you can log in with one, it should be the same user id as the second.

Which database are you using ?

**Comment by ildyria** [comment]
It weakens the security slightly but this is minimal as the main strength is the password.

**Comment by HansYeoh** [comment]
Correct the previous statement, two accounts are unseparated. "Test" and "test" are the same accounts. The problem may be that "Weirdo" is an administrator account. And my database is 10.4.11-MariaDB

**Comment by ildyria** [comment]
> The problem may be that "Weirdo" is an administrator account.

I think this is it. This is the only explanation.

We first try to authenticate against admin by taking the hash of the username and the hash of the password. If this works account gets `ID = 0`.

If it fails, we query the Database for a a user with username = 'weirdo', we hash the password and we compare with the password hash. If this succeed, the account get the ID of User where username = 'weirdo'. Otherwise fail.
There is no account where User has an ID = 0 which prevents any admin takeover. :)

We could add a test when creating a user to see whether the username hashed is equal to admin account username... Well after though still would not prevent the problem.

I guess the problem comes from the Eloquent query then.

**Comment by HansYeoh** [comment]
I suggest that only one of two accounts be allowed to log in or make username be case sensitive.

**Comment by ildyria** [comment]
Feel free to make a PR for that.
The relevant code is here: https://github.com/LycheeOrg/Lychee/blob/master/app/ModelFunctions/SessionFunctions.php#L105

**Comment by ildyria** [comment]
After further thoughts it is sadly due to the configuration of the database. Will dig further.

**Comment by HansYeoh** [comment]
I'm sorry that I can't make a PR for that because I'm not a programmer. But I can help to test the new code if needed. Thanks!

**Comment by ildyria** [comment]
This is due to the collation of the database: 
https://github.com/LycheeOrg/Lychee/blob/master/config/database.php#L52
We will need to figure out in a migration later.

**Comment by ildyria** [comment]
> I'm sorry that I can't make a PR for that because I'm not a programmer. But I can help to test the new code if necessary. Thanks!

Well it is really nice of you to open an issue. :smiley:

**Comment by HansYeoh** [comment]
> Well it is really nice of you to open an issue. :smiley: 

Please let me know if you have any new progress. Have a nice day.😄

**Comment by ildyria** [comment]
I think this has been fixed with the latest change on users.
