### ISSUE TITLE
Failing xmp file read results in fallback to native exif extraction

### ISSUE THREAD

**Issue by tmp-hallenser** [LycheeOrg/Lychee#596]
The current extraction of the xmp meta data reads like this:

```php
try {
			// this can throw an exception in the case of Exiftool adapter!
			$exif = $reader->read($filename);


			// if readlink($filename) == False then $realFile = $filename.
			// if readlink($filename) != False then $realFile = readlink($filename)
			$realFile = readlink($filename) ?: $filename;
			if (Configs::hasExiftool() && file_exists($realFile . '.xmp')) {
				// Don't use the same reader as the file in case it's a video
				$sidecarReader = Reader::factory(Reader::TYPE_EXIFTOOL);
				$sidecarData = $sidecarReader->read($realFile . '.xmp')->getData();


				// We don't want to overwrite the media's type with the mimetype of the sidecar file
				unset($sidecarData['type']);
			}
		} catch (\Exception $e) {
			// Use Php native tools
			Logs::error(__METHOD__, __LINE__, $e->getMessage());
			$reader = Reader::factory(Reader::TYPE_NATIVE);
			$exif = $reader->read($filename);
		}
```

If now the any of the following lines fails, we fall back to native exif data extraction.

```php
			// if readlink($filename) == False then $realFile = $filename.
			// if readlink($filename) != False then $realFile = readlink($filename)
			$realFile = readlink($filename) ?: $filename;
			if (Configs::hasExiftool() && file_exists($realFile . '.xmp')) {
				// Don't use the same reader as the file in case it's a video
				$sidecarReader = Reader::factory(Reader::TYPE_EXIFTOOL);
				$sidecarData = $sidecarReader->read($realFile . '.xmp')->getData();


				// We don't want to overwrite the media's type with the mimetype of the sidecar file
				unset($sidecarData['type']);
			}
```

This is not, what we want (at least imho). I'd prefer the following fallbacks:
1. If exif data extraction (from image) fails using the defined extraction tool, we fall back to the native tool
2. If the sidecar data extraction tool fails, we simply do nothing. The already extracted data should remain untouched.

The current behavior causes some troubles for the heic support #574 .

@alex-phillips @ildyria What do you think?

**Comment by ildyria** [comment]
> I'd prefer the following fallbacks:
> 
> 1. If exif data extraction (from image) fails using the defined extraction tool, we fall back to the native tool
> 2. If the sidecar data extraction tool fails, we simply do nothing. The already extracted data should remain untouched.

No strong opinion from my side. I'm fine with your fallback.

**Comment by d7415** [comment]
>     2. If the sidecar data extraction tool fails, we simply do nothing. The already extracted data should remain untouched.

If it exists, yes. On first pass it should probably fall back to the image metadata though?

**Comment by alex-phillips** [comment]
@tmp-hallenser That's a good point. If the EXIF succeeds but sidecar fails, it reverts falls into the catch. I can submit a PR with modified changes so that each of the 'try' extractions are self-contained.

**Comment by alex-phillips** [comment]
PR here: https://github.com/LycheeOrg/Lychee/pull/597

**Comment by ildyria** [comment]
done.
