### ISSUE TITLE
error running migrate

### ISSUE THREAD

**Issue by bw1984** [LycheeOrg/Lychee#602]
### Detailed description of the problem
running `php artisan migrate` gives the error "SQLSTATE[HY000] [2002] No such file or directory (SQL: select * from information_schema.tables where table_schema = lychee and table_name = migrations and table_type = 'BASE TABLE')"

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. open terminal
2. run `php artisan migrate`

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

### Output of the diagnostics  [REQUIRED]
```
Diagnostics
-----------
Info: Latest version of PHP is 7.4
Error: PHP zip extension not activated
Error: username not set in database
Error: password not set in database
Error: sorting_Photos not set in database
Error: sorting_Albums not set in database
Error: imagick not set in database
Error: skip_duplicates not set in database
Error: check_for_updates not set in database
Error: version not set in database
Error: SQLSTATE[HY000] [2002] No such file or directory (SQL: select `key`, `value`, `type_range` from `configs`)
Warning: Dropbox import not working. No property for dropbox_key.
Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.
Warning: Pictures that are rotated lose their metadata! Please install Imagick to avoid that.

System Information
------------------
Lychee Version (git):       master (0e3289c) - Data not in Cache
DB Version:                 4.0.0

composer install:           --no-dev
APP_ENV:                    production
APP_DEBUG:                  true

System:                     Darwin
PHP Version:                7.3
Unknown SQL Version:        unknown

Imagick:                    -
Imagick Active:             key not found in settings
Imagick Version:            -
GD Version:                 bundled (2.1.0 compatible)

Config Information
------------------
Error: SQLSTATE[HY000] [2002] No such file or directory (SQL: select `value`, `key` from `configs` where `confidentiality` <= 2)
```
### Browser and system
iTerm
OSX (running MAMP locally)
Apache

**Comment by bw1984** [comment]
seems like its fundamentally not able to connect to the database, which is strange because it installed as expected. i notice that APP_ENV says 'PRODUCTION' and see that this may be related to #501 but im not sure how to resolve

**Comment by ildyria** [comment]
Looks like the same problem indeed. Sadly, we don't know how to fix it. My guess is that it is most likely some server side problem rather than the installation. It looks like to me it is not reading `.env`

**Comment by ildyria** [comment]
Can you give a try to the latest master (at least run the diagnostic). This might give you better indications of what is going on.
