### ISSUE TITLE
assign permissions per shared album - (album visibility, download, move, delete)

### ISSUE THREAD

**Issue by kachijs** [LycheeOrg/Lychee#606]
It would be nice to assign permissions per shared album -  (album visibility, download, move, delete)

**Comment by ildyria** [comment]
Yes. Sharing is read only. Write access are not implemented yet.

**Comment by kachijs** [comment]
I changed the owner of the album to id=1 and while in my user (admin) added to her user "allow upload" option. When she logs in her account she is now able to see all the options (download, delete, visiblity) under album/photo.

**Comment by ildyria** [comment]
yes. That's normal. But the pictures uploaded will be under her "own", and of course, if she has ownership of an album or a photo, she can naturally delete it, move it, etc..

**Comment by kachijs** [comment]
Yes this is fine, but it would be nice for admin to control permissions in detail, but that would come with write access for shared albums i believe ?

**Comment by ildyria** [comment]
Could but this is quite a long shot on the plate of all the things we currently have to add.

**Comment by kachijs** [comment]
So to clarify things:

It would be nice to assign permissions per shared album -  (album visibility, download, move, delete)

**Comment by ildyria** [comment]
If you could edit your original post, and I will clean up the feed, that would be awesome! :+1:

**Comment by ildyria** [comment]
Done.
