### ISSUE TITLE
Apple live photo: Without sound and choppy playback

### ISSUE THREAD

**Issue by psirek** [LycheeOrg/Lychee#610]
### Detailed description of the problem [REQUIRED]
I have exported an apple live photo into two separate files:
- Image.jpg
- Image.mov

When importing them into Lychee using "Import from server" they get transformed into a functional live photo, e.g one entry in Lychee with a live photo icon in the upper left corner. When hovering over this icon, the video plays, but there is no sound. When uploading just the video part (Image.mov) I get a video in Lychee that I can play back with sound and smoother playback. 

I tried with a clean install og Lychee using the dockerhub image lycheeorg/lychee:dev. 

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Pull a docker hub image from lycheeorg/lychee:dev using docker-compose. The settings I used was:

> version: '3'
> 
> services:
>   lychee_db:
>     container_name: lychee_db
>     image: mariadb
>     command: --default-authentication-plugin=mysql_native_password
>     environment:
>      - MYSQL_ROOT_PASSWORD=rootPassword
>      - MYSQL_DATABASE=lychee
>      - MYSQL_USER=lychee
>      - MYSQL_PASSWORD=password
>     volumes:
>      - ./database/:/var/lib/mysql
>     networks:
>       - default
>     restart: unless-stopped
> 
>   lychee:
>     image: lycheeorg/lychee:dev
>     container_name: lychee_laravel
>     volumes:
>        - ./lychee/:/config
>        - /var/lxdData/lychee-test/:/picture
>     networks:
>       - default
>       - web-proxy
>     environment:
>       - PUID=1000
>       - PGID=1000
>       - PHP_TZ=America/New_York
>       - APP_URL=http://photoalbum.serek.eu
>       - DB_CONNECTION=mysql
>       - DB_HOST=lychee_db
>       - DB_PORT=3306
>       - DB_DATABASE=lychee
>       - DB_USERNAME=lychee
>       - DB_PASSWORD=password
>     restart: unless-stopped
>     depends_on:
>       - lychee_db
> 
> networks:
>   web-proxy:
>     external:
>       name: reverseproxy_web

2. Create a new user (first time always fails for me so I do a docker-compose down && docker-compose up -d)
3. Create new album and import images from server ("/picture")
4. Navigate to one of the imported live photos and hover the mouse over the live photo icon in the upper left corner.
5. There is no sound in the video playing and the playback is choppy, more so on Safari, less on Chrome.

**Screenshots**

### Output of the diagnostics  [REQUIRED]
Diagnostics
    -------
    Info: Latest version of PHP is 7.4
    Warning: Dropbox import not working. dropbox_key is empty.

    System Information
    --------------
    Lychee Version (git):       No git data found.
    DB Version:                 4.0.6
    
    composer install:           --no-dev
    APP_ENV:                    production
    APP_DEBUG:                  false
    
    System:                     Linux
    PHP Version:                7.3
    MySQL Version:              10.4.13-MariaDB-1:10.4.13+maria~bionic
    
    Imagick:                    1
    Imagick Active:             1
    Imagick Version:            1690
    GD Version:                 2.2.5

    Config Information
    --------------
    version:                    040006
    check_for_updates:          0
    sorting_Photos_col:         takestamp
    sorting_Photos_order:       ASC
    sorting_Albums_col:         max_takestamp
    sorting_Albums_order:       ASC
    imagick:                    1
    skip_duplicates:            0
    small_max_width:            0
    small_max_height:           360
    medium_max_width:           1920
    medium_max_height:          1080
    lang:                       en
    layout:                     1
    image_overlay:              1
    image_overlay_type:         desc
    default_license:            none
    compression_quality:        90
    full_photo:                 1
    delete_imported:            0
    Mod_Frame:                  1
    Mod_Frame_refresh:          30
    thumb_2x:                   1
    small_2x:                   1
    medium_2x:                  1
    landing_page_enable:        0
    landing_owner:              John Smith
    landing_title:              John Smith
    landing_subtitle:           Cats, Dogs & Humans Photography
    landing_facebook:           https://www.facebook.com/JohnSmith
    landing_flickr:             https://www.flickr.com/JohnSmith
    landing_twitter:            https://www.twitter.com/JohnSmith
    landing_instagram:          https://instagram.com/JohnSmith
    landing_youtube:            https://www.youtube.com/JohnSmith
    landing_background:         dist/cat.jpg
    site_title:                 Lychee v4
    site_copyright_enable:      1
    site_copyright_begin:       2019
    site_copyright_end:         2019
    additional_footer_text:     
    display_social_in_gallery:  0
    public_search:              0
    SL_enable:                  0
    SL_for_admin:               0
    public_recent:              0
    recent_age:                 1
    public_starred:             0
    downloadable:               0
    photos_wraparound:          1
    map_display:                1
    zip64:                      1
    map_display_public:         1
    map_provider:               Wikimedia
    force_32bit_ids:            0
    map_include_subalbums:      1
    update_check_every_days:    3
    has_exiftool:               1
    share_button_visible:       0
    import_via_symlink:         0
    has_ffmpeg:                 1
    location_decoding:          1
    location_decoding_timeout:  30
    location_show:              1
    location_show_public:       0
    rss_enable:                 0
    rss_recent_days:            7
    rss_max_items:              100
    prefer_available_xmp_metadata: 0

### Browser and system
I have tested using Chrome and Safari on MacOS.

**Comment by tmp-hallenser** [comment]
The problem is, we're using the LivePhotosKit Framework which somehow mutes the video (and does not provide an option to unmute). Documentation can be found here: https://developer.apple.com/documentation/livephotoskitjs

I'm sorry.

**Comment by psirek** [comment]
Ok, not much that can be done with that. I am closing this issue.
