### ISSUE TITLE
Fresh Install (Script goes back to welcome to lychee)

### ISSUE THREAD

**Issue by sysadminpower2019** [LycheeOrg/Lychee#611]
### Detailed description of the problem [REQUIRED]
*A clear and concise description of what the bug is.*
Cannot finish Lychee 4 install due to install script not working
### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Install lychee
2. Try to set up lychee with the web interface

### Browser and system
Debian 10

**Comment by sysadminpower2019** [comment]
only error i can find from /var/log/apache2

Fri Jun 05 23:27:07.425757 2020] [php7:error] [pid 16623] [client 79.202.35.91:43160] PHP Fatal error:  Uncaught ErrorException: file_put_contents(/var/www/html/Lychee/storage/framework/views/0b05a54961a648aa4a4076d41826a2c868a195fd.php): failed to open stream: Permission denied in /var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:133\nStack trace:\n#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'file_put_conten...', '/var/www/html/L...', 133, Array)\n#1 /var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(133): file_put_contents('/var/www/html/L...', '<?php $__env->s...', 0)\n#2 /var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/View/Compilers/BladeCompiler.php(150): Illuminate\\Filesystem\\Filesystem->put('/var/www/html/L...', '<?php $__env->s...')\n#3 /var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(51): Illuminate\\View\\Compilers\\BladeCompiler->compile('/var/www/html/L...')\n#4 /var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/View/View.php( in /var/www/html/Lychee/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php on line 133

**Comment by ildyria** [comment]
> ```
> Fri Jun 05 23:27:07.425757 2020] [php7:error] [pid 16623] [client 79.202.35.91:43160] PHP Fatal     error:
> Uncaught ErrorException: file_put_contents(/var/www/html/Lychee/storage/framework/views/0b05a54961a648aa4a4076d41826a2c868a195fd.php): failed to open stream: Permission denied 
> ```

Your storage and sub repositories does not have writing access.

Additionally you can still do `artisan lychee:diagnostics` to provide us with the requested informations...

**Comment by sysadminpower2019** [comment]
Diagnostics
-----------
Info: Latest version of PHP is 7.4
Error: username not set in database
Error: password not set in database
Error: sorting_Photos not set in database
Error: sorting_Albums not set in database
Error: imagick not set in database
Error: skip_duplicates not set in database
Error: check_for_updates not set in database
Error: version not set in database
Error: Database is behind file versions. Please apply the migration.
Error: SQLSTATE[HY000] [1045] Access denied for user 'lychee_user'@'localhost' (using password: YES) (SQL: select `key`, `value`, `type_range` from `configs`)
Warning: Dropbox import not working. No property for dropbox_key.
Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.
Warning: Pictures that are rotated lose their metadata! Please enable Imagick in settings to avoid that.

But I have already made the DB and created a user called lychee_user and then i follow along the steps from the web install interface.
 I get a page that asks me to input the db username, passsword etc. 
I put those in hit save and then install but thats when it just goes back to welcome to lychee.
What am i missing here

**Comment by d7415** [comment]
Did you check the permissions as instructed?

**Comment by sysadminpower2019** [comment]
yes thank you in the end the issue was with the DB itself. It could not read the username. I had to regrant privledges and flush. thanks
