### ISSUE TITLE
Server Error or API not found after successful installation

### ISSUE THREAD

**Issue by riccardolardi** [LycheeOrg/Lychee#612]
### Detailed description of the problem [REQUIRED]
I get `Server Error or API not found` error after successful installation due to `[404]: GET /php/index.php - No such file or directory`

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Install Lychee via composer or per zip release download
2. Create mysql database and user
3. Run PHP via `php -S 127.0.0.1:8888` inside `Lychee/public`
4. Navigate to 127.0.0.1:8888 and follow installation instructions
5. Installations finishes successfully
6. Reload page, get PHP error `[404]: GET /php/index.php - No such file or directory`

### Output of the diagnostics  [REQUIRED]
Diagnostics
-----------
Error: username empty or not set in database
Error: password empty or not set in database
Warning: Dropbox import not working. dropbox_key is empty.
Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.
Warning: Pictures that are rotated lose their metadata! Please install Imagick to avoid that.

System Information
------------------
Lychee Version (release):   4.0.6
DB Version:                 4.0.6

composer install:           --no-dev
APP_ENV:                    production
APP_DEBUG:                  true

System:                     Darwin
PHP Version:                7.4
MySQL Version:              8.0.18

Imagick:                    -
Imagick Active:             1
Imagick Version:            -
GD Version:                 bundled (2.1.0 compatible)

Config Information
------------------
version:                    040006
check_for_updates:          0
sorting_Photos_col:         takestamp
sorting_Photos_order:       ASC
sorting_Albums_col:         max_takestamp
sorting_Albums_order:       ASC
imagick:                    1
skip_duplicates:            0
small_max_width:            0
small_max_height:           360
medium_max_width:           1920
medium_max_height:          1080
lang:                       en
layout:                     1
image_overlay:              1
image_overlay_type:         desc
default_license:            none
compression_quality:        90
full_photo:                 1
delete_imported:            0
Mod_Frame:                  1
Mod_Frame_refresh:          30
thumb_2x:                   1
small_2x:                   1
medium_2x:                  1
landing_page_enable:        0
landing_owner:              John Smith
landing_title:              John Smith
landing_subtitle:           Cats, Dogs & Humans Photography
landing_facebook:           https://www.facebook.com/JohnSmith
landing_flickr:             https://www.flickr.com/JohnSmith
landing_twitter:            https://www.twitter.com/JohnSmith
landing_instagram:          https://instagram.com/JohnSmith
landing_youtube:            https://www.youtube.com/JohnSmith
landing_background:         dist/cat.jpg
site_title:                 Lychee v4
site_copyright_enable:      1
site_copyright_begin:       2019
site_copyright_end:         2019
additional_footer_text:     
display_social_in_gallery:  0
public_search:              0
SL_enable:                  0
SL_for_admin:               0
public_recent:              0
recent_age:                 1
public_starred:             0
downloadable:               0
photos_wraparound:          1
map_display:                0
zip64:                      1
map_display_public:         0
map_provider:               Wikimedia
force_32bit_ids:            0
map_include_subalbums:      0
update_check_every_days:    3
has_exiftool:               0
share_button_visible:       0
import_via_symlink:         0
has_ffmpeg:                 1
location_decoding:          0
location_decoding_timeout:  30
location_show:              1
location_show_public:       0
rss_enable:                 0
rss_recent_days:            7
rss_max_items:              100
prefer_available_xmp_metadata: 0

### Browser and system
Latest Chrome, Latest MacOS, running PHP via `php -S 127.0.0.1:8888` inside `Lychee/public`

**Comment by ildyria** [comment]
> `Imagick Active: 1`

Unrelated but you should set this value to `0` in the advanced settings as you don't have imagick available.

**Comment by ildyria** [comment]
I managed to reproduce it.

**Solved:**
Instead of doing `php -S 127.0.0.1:8888` inside the `public` directory,
Do `php artisan serve --port=8888` in the root.

I don't know what differences it applies but it seems to work.
Additionally I advise you redo the serve every once you change your `.env`

**Comment by riccardolardi** [comment]
@ildyria Thank you! That solved the issue.

**Comment by ildyria** [comment]
For the record, the `php artisan serve` command (or `php -S`) is only here for testing. You should run your server with Apache or Nginx or similar. :confused:

**Comment by ildyria** [comment]
Added to the FAQ: https://lycheeorg.github.io/docs/faq.html#i-have-an-error-404-and-im-using-php-s-what-can-i-do
