### ISSUE TITLE
Unclear how to go from v3 to v4 and use https://foobar.com/gallery/

### ISSUE THREAD

**Issue by DavidGriffith** [LycheeOrg/Lychee#614]
I have an existing v3 install of Lychee that is accessed by going to https://foobar.com/gallery/.  The upgrade instructions at https://lycheeorg.github.io/docs/upgrade.html seem to assume that any and all installation of Lychee will be accessed like this: https://gallery.foobar.com/.  Please clarify how to install v4 like this and how to convert a v3 installed that way to v4.

**Comment by d7415** [comment]
Try [this](https://lycheeorg.github.io/docs/faq.html#can-i-host-lychee-with-a-subpath-with-nginx-like-httpsexampledevlychee). I think Apache should sort itself out, but I haven't tried that myself.

**Comment by DavidGriffith** [comment]
I'm using Apache and it hasn't sorted itself out.

**Comment by ildyria** [comment]
https://github.com/LycheeOrg/Lychee/issues/349#issuecomment-569952470

**Comment by ildyria** [comment]
Added to the FAQ: https://lycheeorg.github.io/docs/faq.html#can-i-host-lychee-with-a-subpath-with-apache-like-httpsexampledevlychee
