### ISSUE TITLE
Sorting pictures

### ISSUE THREAD

**Issue by ulflieger** [LycheeOrg/Lychee#615]
Hi folks,
 I'm a newbie here on Github and not sure if I'm in the correct forum. 

I installed the Lychee picture gallery through my web host all-inkl.com. I would have the following question: When I upload pictures, the last uploaded picture is always set to position 1 in the thumbnail view. However, this is not optimal for my concern, because I want to accommodate chronological photos in the picture gallery. Is there no way to rearrange the pictures afterwards? Or to chronologically position the position of the uploaded pictures in the thumbnail view from the beginning, so that new pictures always appear last in the view?

Thanks in advance for your help!

**Comment by ildyria** [comment]
Hi, welcome to the userbase of Lychee. :smiley: 

You can change that setting:
![settings](https://user-images.githubusercontent.com/627094/84266936-962ea380-ab25-11ea-9b46-61704f8bc4c5.png)

**Comment by ulflieger** [comment]
Thanks a lot! That helped!
