### ISSUE TITLE
Server Error or API not found - cannot change visibility settings

### ISSUE THREAD

**Issue by sorcer1122** [LycheeOrg/Lychee#619]
### Detailed description of the problem [REQUIRED]
After updating Lychee (4.0.0 -> 4.0.6) I cannot make albums visible. I get 500 internal error. I have managed to find the following in the F12 console

![lychee](https://user-images.githubusercontent.com/15838362/84701737-6a5c5500-af4d-11ea-973e-97e089ad949e.png)
After moving my pics from 4.0.0 to 4.0.6 and going to the website, I was asked to set up 4.0.6 again and I used the same database I have been using for 4.0.0. There were no error but I suspect it may have affected something.

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Update from 4.0.0 to 4.0.6 manually
2. Go to your albums and try to change visibility settings
3. Error Server Error or API not found pops up

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

### Output of the diagnostics  [REQUIRED]

    System Information
    --------------
    Lychee Version (release):   4.0.6
    DB Version:                 4.0.6
    
    composer install:           --no-dev
    APP_ENV:                    production
    APP_DEBUG:                  true
    
    System:                     Linux
    PHP Version:                7.4
    MySQL Version:              10.3.23-MariaDB-1:10.3.23+maria~bionic-log
    
    Imagick:                    1
    Imagick Active:             1
    Imagick Version:            1687
    GD Version:                 2.3.0

    Config Information
    --------------
    version:                    040006
    check_for_updates:          1
    sorting_Photos_col:         id
    sorting_Photos_order:       DESC
    sorting_Albums_col:         title
    sorting_Albums_order:       DESC
    imagick:                    1
    skip_duplicates:            0
    small_max_width:            0
    small_max_height:           360
    medium_max_width:           1920
    medium_max_height:          1080
    lang:                       en
    layout:                     0
    image_overlay:              0
    image_overlay_type:         exif
    default_license:            reserved
    compression_quality:        90
    full_photo:                 1
    delete_imported:            1
    Mod_Frame:                  0
    Mod_Frame_refresh:          30
    landing_page_enable:        0
    landing_owner:              XXX 
    landing_title:              XXX
    landing_subtitle:           Cat, Dogs & Humans Photography
    landing_facebook:           
    landing_flickr:             
    landing_twitter:            
    landing_instagram:          
    landing_youtube:            
    landing_background:         dist/cat.jpg
    thumb_2x:                   1
    small_2x:                   0
    medium_2x:                  0
    site_title:                 Pictures
    site_copyright_enable:      1
    site_copyright_begin:       2015
    site_copyright_end:         2020
    additional_footer_text:     
    display_social_in_gallery:  0
    public_search:              0
    SL_enable:                  0
    SL_for_admin:               0
    public_recent:              0
    recent_age:                 1
    public_starred:             0
    downloadable:               0
    photos_wraparound:          1
    map_display:                1
    zip64:                      1
    map_display_public:         1
    map_provider:               OpenStreetMap.org
    force_32bit_ids:            0
    map_include_subalbums:      1
    update_check_every_days:    3
    has_exiftool:               0
    share_button_visible:       0
    import_via_symlink:         0
    has_ffmpeg:                 1
    location_decoding:          1
    location_decoding_timeout:  30
    location_show:              1
    location_show_public:       0
    rss_enable:                 0
    rss_recent_days:            7
    rss_max_items:              100
    prefer_available_xmp_metadata: 0

### Browser and system
Latest Firefox on MacOS and Windows.

**Comment by ildyria** [comment]
> Update from 4.0.0 to 4.0.6 manually

Can you be slightly more specific?
- Did you do `composer --install --no-dev` or did you use the release file ?
- Did you do `php artisan migrate` ?

Your error *"unknown column 'full_photo' ..."* should not happen. Something went wrong with your database. We do not remove that column in the migration code.

**Comment by sorcer1122** [comment]
> Did you do `composer --install --no-dev` or did you use the release file ?

I used a release file (Lychee.zip)



> Did you do `php artisan migrate` ?

Yes, I did and got 'nothing to migrate'.



> Something went wrong with your database

Yeah, this was my presumption. If I reinstall Lychee and create a new, empty DB for it, will I not lose my directory structure?

**Comment by ildyria** [comment]
> > Did you do `composer --install --no-dev` or did you use the release file ?
> 
> I used a release file (Lychee.zip)

:+1: 

> > Did you do `php artisan migrate` ?
> 
> Yes, I did and got 'nothing to migrate'.

:confused:  I was hoping something would be fixed there.

> > Something went wrong with your database
> 
> Yeah, this was my presumption. If I reinstall Lychee and create a new, empty DB for it, will I not lose my directory structure?

You will lose the directory structure... However, you can give a try to downloading every albums that you have (in one go). This will produce a single zip file with all your pictures and the directory structure preserved.

Another possibility you can try, before trying the reinstall, is to manually add a column `full_photo` of type `int` and with default value `1` in your database.

Another possibility is to create a second instance of lychee, let the migration run, and then compare the structure of the database between your broken version and a "new" version. That should fix things too.

**Comment by sorcer1122** [comment]
Thanks, I will try to add a column and report.

**Comment by sorcer1122** [comment]
OK, adding full_photo column fixed it! For the sake of those who will find this via search - you need to execute this command in you SQL editor - ALTER TABLE albums ADD COLUMN full_photo INT DEFAULT 1; and do flush privileges;

There may be other columns that are missing but at the moment it will do.

Many thanks for suggesting this. Now the task is to convert manual installation into composer install --no-dev. I am now closing this issue.
