### ISSUE TITLE
How to configure CloudFlare for Lychee?

### ISSUE THREAD

**Issue by BobAnkh** [LycheeOrg/Lychee#620]
This is a question for configuration.

I don't know the detailed steps needed to configure CloudFlare for Lychee, so could anybody tell me how to do it or relevant docs I should look up?

Simply turning on the CF's proxy results in showing nothing on the page.

**Comment by ildyria** [comment]
https://lycheeorg.github.io/docs/faq.html#how-can-i-see-the-correct-client-ip-address-when-running-lychee-behind-cloudflare
and https://github.com/LycheeOrg/Lychee/issues/314 should help you.

I don't use Cloudfare, so I can't really help you more than that.

**Comment by BobAnkh** [comment]
Thank you for your advice @ildyria . I have tried to do with [laravel-cloudflare](https://github.com/monicahq/laravel-cloudflare), but I failed.

What I have done:

1. type `composer require monicahq/laravel-cloudflare` in the teminal
2. modify `use Fideloper\Proxy\TrustProxies as Middleware;` in **Lychee/app/Http/Middleware/TrustProxies** to `use Monicahq\Cloudflare\Http\Middleware\TrustProxies as Middleware;`
3. type `php artisan cloudflare:reload` in the teminal

But these steps don't work. Maybe I use it incorrectly or lack other necessary steps? Nothing shows on the page with this error reported in the console:
> Refused to load the script 'https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js' because it violates the following Content Security Policy directive: "script-src 'self' 'report-sample' https://www.dropbox.com/static/api/1/dropins.js 'sha256-8bLztrDF3NUpheSuvAzpebgX1DpPJEfhmUHKTwGF4qA='". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

I don't know how to solve my problem. So I hope someone can help me or tell me the correct steps I should apply.

**Comment by d7415** [comment]
You need to allow ajax.cloudflare.com [here](https://github.com/LycheeOrg/Lychee/blob/master/config/secure-headers.php#L337) or disable ~whichever CF feature is calling that script.~ [this](https://support.cloudflare.com/hc/en-us/articles/200168056-What-does-Rocket-Loader-do-).

**Comment by BobAnkh** [comment]
Everything works well! Thank you very much for your help @d7415
