### ISSUE TITLE
[Enhancement] Add more licenses

### ISSUE THREAD

**Issue by mxmehl** [LycheeOrg/Lychee#622]
We started to use Lychee but noticed that only a handful of licenses are supported. For instance, some of our existing (and surely future) images are under CC-BY-2.0. We cannot label it as CC-BY-4.0 single-handedly though.

Is there a possibility to add more licenses? I do not expect Lychee to support [hundreds](https://spdx.org/licenses/), but perhaps one could add them in the admin panel manually?

Thanks for making this software even better!

**Comment by ildyria** [comment]
I don't have problem for this to be added. However most of us won't have the time to work on that one.
