### ISSUE TITLE
Intermittent blank page when accessing Lychee.

### ISSUE THREAD

**Issue by coridonhenshaw** [LycheeOrg/Lychee#627]
### Detailed description of the problem [REQUIRED]
When viewing the main page of a Lychee site, either as an unauthenticated visitor or authenticated user, Lychee occasionally fails to render and presents a blank page with no content. This appears to be due to a client-side race condition. When the page fails to render, the error

`"InvalidAccessError: CSSStyleSheet.cssRules getter: Can't access rules of still-loading stylsheet"`  in main.js 

appears in the Firefox Javascript developer console. The line number for the error varies; I've seen both 14151 and 180.

### Steps to reproduce the issue
Repeatedly refresh the main page of a functioning Lychee installation until a blank page appears. 

**Screenshots**
N/A

### Output of the diagnostics  [REQUIRED]

    Diagnostics
    -------
    Warning: Dropbox import not working. dropbox_key is empty.
    Warning: Pictures that are rotated lose their metadata! Please install Imagick to avoid that.

    System Information
    --------------
    Lychee Version (git):       No git data found.
    DB Version:                 4.0.6
    
    composer install:           --no-dev
    APP_ENV:                    production
    APP_DEBUG:                  false
    
    System:                     Linux
    PHP Version:                7.4
    MySQL Version:              10.1.44-MariaDB-0ubuntu0.18.04.1
    
    Imagick:                    -
    Imagick Active:             1
    Imagick Version:            -
    GD Version:                 2.3.0

    Config Information
    --------------
    version:                    040006
    check_for_updates:          0
    sorting_Photos_col:         takestamp
    sorting_Photos_order:       ASC
    sorting_Albums_col:         max_takestamp
    sorting_Albums_order:       ASC
    imagick:                    1
    skip_duplicates:            0
    small_max_width:            0
    small_max_height:           360
    medium_max_width:           1920
    medium_max_height:          1080
    lang:                       en
    layout:                     1
    image_overlay:              0
    image_overlay_type:         desc
    default_license:            none
    compression_quality:        90
    full_photo:                 1
    delete_imported:            0
    Mod_Frame:                  1
    Mod_Frame_refresh:          30
    thumb_2x:                   1
    small_2x:                   1
    medium_2x:                  1
    landing_page_enable:        0
    landing_owner:              John Smith
    landing_title:              John Smith
    landing_subtitle:           Cats, Dogs & Humans Photography
    landing_facebook:           https://www.facebook.com/JohnSmith
    landing_flickr:             https://www.flickr.com/JohnSmith
    landing_twitter:            https://www.twitter.com/JohnSmith
    landing_instagram:          https://instagram.com/JohnSmith
    landing_youtube:            https://www.youtube.com/JohnSmith
    landing_background:         dist/cat.jpg
    site_title:                 Lychee v4
    site_copyright_enable:      0
    site_copyright_begin:       2020
    site_copyright_end:         2020
    additional_footer_text:     
    display_social_in_gallery:  0
    public_search:              0
    SL_enable:                  0
    SL_for_admin:               0
    public_recent:              0
    recent_age:                 1
    public_starred:             0
    downloadable:               1
    photos_wraparound:          1
    map_display:                0
    zip64:                      1
    map_display_public:         0
    map_provider:               Wikimedia
    force_32bit_ids:            0
    map_include_subalbums:      0
    update_check_every_days:    3
    has_exiftool:               0
    share_button_visible:       0
    import_via_symlink:         0
    has_ffmpeg:                 0
    location_decoding:          0
    location_decoding_timeout:  30
    location_show:              0
    location_show_public:       0
    rss_enable:                 0
    rss_recent_days:            7
    rss_max_items:              100
    prefer_available_xmp_metadata: 0

### Browser and system
Client: Firefox 77.0.1 under both Windows 10 and OpenSUSE Leap. Other browsers not tested.

**Comment by ildyria** [comment]
Could not reproduce on Chrome.

**Comment by d7415** [comment]
I do all my testing in Firefox and have not encountered this.

**Comment by coridonhenshaw** [comment]
This seems to be a CPU-speed dependent race condition that only impacts desktop Firefox.

On a two core i3-4330 CPU, I get blank pages every dozen or so reloads, but I can't repeat the problem at all on a four core i5-4590. The Firefox configurations on both systems are substantively identical--both running Ublock Origin with all other extensions disabled for testing purposes.

Disabling all extensions on Firefox on my i3 does not help, nor does starting a clean Firefox profile, or switching between Windows 10 and Linux.

I can't trigger the problem on Edge (Chromium-based version), even on slow hardware, or on an Android tablet using Firefox mobile or Samsung's browser.

I don't have enough Javascript knowledge to debug this much further, especially as the code section that seems most vulnerable is minified.
