### ISSUE TITLE
Multiple content security policy errors with the default installation

### ISSUE THREAD

**Issue by coridonhenshaw** [LycheeOrg/Lychee#629]
### Detailed description of the problem [REQUIRED]
When using Lychee with Firefox 77, Firefox throws multiple content security policy errors at utils.js:35:9:

Error 1:

`Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). Source: (function (NAVIGATOR, OBJECT) {`

Error 2:

`Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). Source: (function (DOCUMENT, dispatchEvent, CUSTOM_EVENT, ERROR, DATE, setTimeout, OBJECT) {`

The Lychee debug bar must be disabled for these errors to manifest as Lychee does not generate CSP headers when the debug bar is enabled.

### Steps to reproduce the issue
Disable the debug bar in a working installation of Lychee.
Open the Javascript development console in Firefox.
Access (or refresh) the main page of the Lychee gallery.
Note CSP errors in the Javascript console.

**Screenshots**
N/A

### Output of the diagnostics  [REQUIRED]

    Diagnostics
    -------
    Warning: Dropbox import not working. dropbox_key is empty.
    Warning: Pictures that are rotated lose their metadata! Please install Imagick to avoid that.

    System Information
    --------------
    Lychee Version (git):       No git data found.
    DB Version:                 4.0.6
    
    composer install:           --no-dev
    APP_ENV:                    production
    APP_DEBUG:                  false
    
    System:                     Linux
    PHP Version:                7.4
    MySQL Version:              10.1.44-MariaDB-0ubuntu0.18.04.1
    
    Imagick:                    -
    Imagick Active:             1
    Imagick Version:            -
    GD Version:                 2.3.0

    Config Information
    --------------
    version:                    040006
    check_for_updates:          0
    sorting_Photos_col:         takestamp
    sorting_Photos_order:       ASC
    sorting_Albums_col:         max_takestamp
    sorting_Albums_order:       ASC
    imagick:                    1
    skip_duplicates:            0
    small_max_width:            0
    small_max_height:           360
    medium_max_width:           1920
    medium_max_height:          1080
    lang:                       en
    layout:                     1
    image_overlay:              0
    image_overlay_type:         desc
    default_license:            none
    compression_quality:        90
    full_photo:                 1
    delete_imported:            0
    Mod_Frame:                  1
    Mod_Frame_refresh:          30
    thumb_2x:                   1
    small_2x:                   1
    medium_2x:                  1
    landing_page_enable:        0
    landing_owner:              John Smith
    landing_title:              John Smith
    landing_subtitle:           Cats, Dogs & Humans Photography
    landing_facebook:           https://www.facebook.com/JohnSmith
    landing_flickr:             https://www.flickr.com/JohnSmith
    landing_twitter:            https://www.twitter.com/JohnSmith
    landing_instagram:          https://instagram.com/JohnSmith
    landing_youtube:            https://www.youtube.com/JohnSmith
    landing_background:         dist/cat.jpg
    site_title:                 Lychee v4
    site_copyright_enable:      0
    site_copyright_begin:       2020
    site_copyright_end:         2020
    additional_footer_text:     
    display_social_in_gallery:  0
    public_search:              0
    SL_enable:                  0
    SL_for_admin:               0
    public_recent:              0
    recent_age:                 1
    public_starred:             0
    downloadable:               1
    photos_wraparound:          1
    map_display:                0
    zip64:                      1
    map_display_public:         0
    map_provider:               Wikimedia
    force_32bit_ids:            0
    map_include_subalbums:      0
    update_check_every_days:    3
    has_exiftool:               0
    share_button_visible:       0
    import_via_symlink:         0
    has_ffmpeg:                 0
    location_decoding:          0
    location_decoding_timeout:  30
    location_show:              0
    location_show_public:       0
    rss_enable:                 0
    rss_recent_days:            7
    rss_max_items:              100
    prefer_available_xmp_metadata: 0

### Browser and system

Firefox 77.0.1. Tested under both Windows 10 and openSUSE Leap 15.1

**Comment by d7415** [comment]
I'm not convinced we should consider the debug bar part of "the default installation".

**Comment by ildyria** [comment]
Debugbar is **NOT** part of the default installation, see composer.json :
```json
"require-dev": {
        "ext-imagick": "*",
        "barryvdh/laravel-debugbar": "^3.3",
```

**Comment by d7415** [comment]
There we go. IMO the CSP should be set to the production settings by default. I suppose we could vary them depending on e.g. `APP=debug` (though that wouldn't have helped in this instance).

@coridonhenshaw How did you install the debugbar? Your diagnostics show composer was run with --no-dev (or, by the looks of it, a release zip)

**Comment by coridonhenshaw** [comment]
There seems to be some confusion here. I **do not** have debugbar installed. CSP errors happen with both a stock `--no--dev` Lychee install, created from `git clone`,  and with the Docker container.

I mentioned debugbar only because the logic in `config/secure-headers.php` suppresses CSP header generation when the debugbar is active, which seemed relevant as people who develop Lychee might be using debugbar, and, therefore, would not be able to reproduce the issue.

The default `--no-dev` CSP settings cause this issue. No special configuration is needed.

**Comment by d7415** [comment]
Sorry, I misread. In that case we may need more details as it appears to only be affecting you. I'll try to have another look tonight unless someone beats me to it.

**Comment by d7415** [comment]
Ok. First question: Where is utils.js, because it's not part of Lychee.

**Comment by coridonhenshaw** [comment]
I've done more testing on my side and it looks like utils.js in this case is part of EFF's Privacy Badger extension, which doesn't play nicely with Lychee's default CSP. This seems to be a Privacy Badger issue, and/or a problem with Firefox's CSP security model as it relates to code injection by extensions.

I'll file an issue with the Privacy Badger devs.
