### ISSUE TITLE
[Enhancement] Optimise uploaded images

### ISSUE THREAD

**Issue by mxmehl** [LycheeOrg/Lychee#630]
It would be useful to have tools like optipng run over newly uploaded images, or offer this as an option for all existing images in the database. In our tests at Free Software Foundation Europe, we've experienced an average space saving of 8-15% with the same quality.

The reason why this should be in Lychee directly is that the checksum of the pictures are in the database, and when running these tools on the files directly, the sums would not match any more.

Downside: the optimisiation might take some seconds depending on the file type and size. That is why this option should be called upon explicit request by the admin, and/or configurably during upload/import.

**Comment by d7415** [comment]
I can see some benefit, but I'm mostly of the opinion that processing should be done before a photo hits Lychee.

**Comment by tmp-hallenser** [comment]
The idea is interesting. Let me share my view:
We save 2 different kinds of image files within Lychee: (1) The original file and (2) scaled (and cropped) versions for lightbox and thumbnail.
(1) I'd vote against manipulating the original file since I'd like to retrieve the original file when downloading (file is only delivered to browser if user wants to download the original file)
(2) These files are delivered to the browser when viewing the album/photo. If some package delivers smaller files at same size, it's worth a thought.

@mxmehl Do you have benchmarks comparing imagick with optipng (and jpg equivalent tools)?

**Comment by mxmehl** [comment]
I agree that the original photo should not be touched.

Regarding benchmarks, just an example:

URL: https://pics.fsfe.org/uploads/medium/69a7e6a2a2e36b14fced8e1ab3044b66.png

```
$ optipng 69a7e6a2a2e36b14fced8e1ab3044b66.png 
** Processing: 69a7e6a2a2e36b14fced8e1ab3044b66.png
800x432 pixels, 4x8 bits/pixel, RGB+alpha
Reducing image to 3x8 bits/pixel, RGB
Input IDAT size = 142128 bytes
Input file size = 142233 bytes

Trying:
  zc = 9  zm = 8  zs = 0  f = 5		IDAT size = 126969
  zc = 9  zm = 8  zs = 1  f = 5		IDAT size = 122776
                               
Selecting parameters:
  zc = 9  zm = 8  zs = 1  f = 5		IDAT size = 122776

Output IDAT size = 122776 bytes (19352 bytes decrease)
Output file size = 122833 bytes (19400 bytes = 13.64% decrease)
```

There are many other tools which work for JPG and PNG alike, e.g. https://github.com/siiptuo/pio

**Comment by tmp-hallenser** [comment]
you can give the PR #659 a try. Don't forget to run `composer install` and `php artisan migrate`.

**Comment by ikosa** [comment]
https://github.com/LycheeOrg/Lychee/blob/6ec5f56ab90d9b0c15c18704a3f677420b162245/database/migrations/2020_07_11_104605_config_lossless_optimization.php#L22

i guess type_range has to be '0|1' isn't it? Othervise i'm getting error when changing value from settings.

**Comment by ildyria** [comment]
Well that is one possible value yes. Note that `BOOL` is defined above.
https://github.com/LycheeOrg/Lychee/blob/6ec5f56ab90d9b0c15c18704a3f677420b162245/database/migrations/2020_07_11_104605_config_lossless_optimization.php#L15

https://github.com/LycheeOrg/Lychee/blob/6ec5f56ab90d9b0c15c18704a3f677420b162245/database/migrations/2019_09_28_171753_config_fix.php#L124-L131
This is a good example of possibilities.
Note that we also allow other values, eg:
https://github.com/LycheeOrg/Lychee/blob/6ec5f56ab90d9b0c15c18704a3f677420b162245/database/migrations/2019_09_28_171753_config_fix.php#L180
