### ISSUE TITLE
[Enhancement] Add Regression tests.

### ISSUE THREAD

**Issue by ildyria** [LycheeOrg/Lychee#634]
Add more tests here https://github.com/LycheeOrg/Lychee/tree/master/tests/Feature :

- [x] #631
- [x] #635
- [x] #734
- [x] #643 
- [ ] #669 
- [x] #673
- [x] #781

**Comment by kamil4** [comment]
I would add #691 to the list. Password-protection is a tricky edge case, especially since it needs to be handled differently in regular browsing vs search.

**Comment by ildyria** [comment]
added #734 to the list

**Comment by nagmat84** [comment]
I have checked #635, #643 and #781. These bugs are definitely covered by the newly added authorization tests.
