### ISSUE TITLE
if .env is not writable, install fails with a 500. => catch the error.

### ISSUE THREAD

**Issue by Unresponsive** [LycheeOrg/Lychee#636]
I'm trying to follow this guide:
https://lycheeorg.github.io/docs/upgrade.html

First of all when I click to check requirements (as suggested there) it leads me to 'issues'?

Anyway, I extracted all files from zip file, moved all images from old 'uploads' to new 'uploads'. Then I tried accessing my site, the installation/upgrade goes OK until the last stage when it asks me to enter all mysql data. I enter that and after clicking "Save" or "Install" I get an error: "500 | Server Error"

![image](https://user-images.githubusercontent.com/12999520/85926661-8e9f2680-b8a9-11ea-9160-a501fc8ae8d7.png)

What am I doing wrong? I double checked Mysql connection using a separate php file, it works with lychee user and password. Should I enter all data with quotes or without? It is confusing, some entries in that file are quoted, some are not.

**Comment by Unresponsive** [comment]
(Debian 10, PHP 7.4.7)

**Comment by Unresponsive** [comment]
Solved, .env was not writeable.

**Comment by ildyria** [comment]
> I enter that and after clicking "Save" or "Install" I get an error: "500 | Server Error"

Interesting, Thank you for letting us know to add another check.

**Comment by ildyria** [comment]
This is now fixed with #636 . Thank you for reporting this error. :)

**Comment by ildyria** [comment]
> First of all when I click to check requirements (as suggested there) it leads me to 'issues'?

Also fixed. :+1:
