### ISSUE TITLE
504 Gateway timeout when processing images

### ISSUE THREAD

**Issue by astrofrog** [LycheeOrg/Lychee#637]
### Detailed description of the problem

When uploading an album of images that are 5-10Mb each to a lychee installation on a raspberry pi, some of the images fail to upload due to a 504 Gateway timeout during processing.

### Steps to reproduce the issue

I am using a very minimal docker-compose file:

```yaml
version: '3'

services:
  lychee:
    image: lycheeorg/lychee:dev
    container_name: lychee
    volumes:
      - ./lychee/conf:/conf
      - ./lychee/uploads:/uploads
      - ./lychee/sym:/sym
      - ./lychee/db:/db
    environment:
      - PHP_TZ=UTC
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/db/lychee.sqlite
    restart: unless-stopped
    ports:
      - 90:80
```

This is on a raspberry pi. If I then create an album and try and upload 50 images that are 5-10Mb, some of the processing steps fail:

<img width="545" alt="Screenshot 2020-06-27 at 21 54 12" src="https://user-images.githubusercontent.com/314716/85932697-375b7f00-b8c6-11ea-9625-50f37b87bca7.png">

with the following message in the console:

<img width="497" alt="Screenshot 2020-06-27 at 22 36 32" src="https://user-images.githubusercontent.com/314716/85933185-2f064280-b8cc-11ea-897e-f7c96e06e4e9.png">

Inspecting top in the raspberry pi shows that there are a number of ``php-fpm7.3`` processes running - my suspicion is that as more images start to be processed, the processing takes longer, which leads to timeouts - and this is an issue here because the computer is not very powerful.

Is there a way to allow the processing to take more time before timing out? Alternatively, is it possible to limit the number of concurrent processing steps?

### Output of the diagnostics

```
    Diagnostics
    -----------
    Info: Latest version of PHP is 7.4
    Warning: Using 32 bit PHP, recommended upgrade to 64 bit
    Warning: Dropbox import not working. dropbox_key is empty.

    System Information
    ------------------
    Lychee Version (git):       No git data found.
    DB Version:                 4.0.6
    
    composer install:           --no-dev
    APP_ENV:                    production
    APP_DEBUG:                  false
    
    System:                     Linux
    PHP Version:                7.3
    Max uploaded file size:     20M
    Max post size:              100M
    SQLite Version:             3.27.2
    
    Imagick:                    1
    Imagick Active:             1
    Imagick Version:            1690
    GD Version:                 2.2.5

    Config Information
    ------------------
    version:                    040006
    check_for_updates:          0
    sorting_Photos_col:         takestamp
    sorting_Photos_order:       ASC
    sorting_Albums_col:         max_takestamp
    sorting_Albums_order:       ASC
    imagick:                    1
    skip_duplicates:            0
    small_max_width:            0
    small_max_height:           360
    medium_max_width:           1920
    medium_max_height:          1080
    lang:                       en
    layout:                     1
    image_overlay:              1
    image_overlay_type:         desc
    default_license:            none
    compression_quality:        90
    full_photo:                 1
    delete_imported:            0
    Mod_Frame:                  1
    Mod_Frame_refresh:          30
    thumb_2x:                   1
    small_2x:                   1
    medium_2x:                  1
    landing_page_enable:        0
    landing_owner:              Thomas Robitaille
    landing_title:              Thomas Robitaille's Photos
    landing_subtitle:           Private Photos
    landing_facebook:           https://www.facebook.com/astrofrog
    landing_flickr:             https://www.flickr.com/thomasrobitaille
    landing_twitter:            https://www.twitter.com/astrofrog
    landing_instagram:          
    landing_youtube:            
    landing_background:         dist/cat.jpg
    site_title:                 Thomas Robitaille's Photos
    site_copyright_enable:      1
    site_copyright_begin:       2020
    site_copyright_end:         2020
    additional_footer_text:     
    display_social_in_gallery:  0
    public_search:              0
    SL_enable:                  0
    SL_for_admin:               0
    public_recent:              0
    recent_age:                 1
    public_starred:             0
    downloadable:               0
    photos_wraparound:          1
    map_display:                0
    zip64:                      1
    map_display_public:         0
    map_provider:               Wikimedia
    force_32bit_ids:            0
    map_include_subalbums:      0
    update_check_every_days:    3
    has_exiftool:               1
    share_button_visible:       0
    import_via_symlink:         0
    has_ffmpeg:                 1
    location_decoding:          0
    location_decoding_timeout:  30
    location_show:              1
    location_show_public:       0
    rss_enable:                 0
    rss_recent_days:            7
    rss_max_items:              100
    prefer_available_xmp_metadata: 0
    editor_enabled:             1
```

### Browser and system

Client: Google Chrome on MacOS X 10.15.5
Server: Raspberry Pi with Raspian

**Comment by astrofrog** [comment]
Investigating further, the timeout seems to happen if a processing step takes more than 60 seconds

**Comment by astrofrog** [comment]
I managed to track down the issue: https://github.com/LycheeOrg/Lychee-Docker/pull/67

**Comment by astrofrog** [comment]
The issue was indeed that my poor little Raspberry Pi was trying to process 6 large images concurrently which slowed thing down a lot, beyond the 60s default fastcgi timeout

**Comment by ildyria** [comment]
I think that limiting the concurrency might be a better approach.

**Comment by astrofrog** [comment]
@ildyria - I couldn't find how to do this, could you advise on the best approach?

**Comment by ildyria** [comment]
I don't use nginx but the following readings would be my entry point:
https://docs.nginx.com/nginx/admin-guide/security-controls/controlling-access-proxied-http/ 
https://serverfault.com/questions/787919/optimal-value-for-nginx-worker-connections

**Comment by pchampio** [comment]
somewhat related issue: https://github.com/LycheeOrg/Lychee/issues/443

I ended up using rsync to copy my photos to the server, and use the `php artisan lychee:sync /path/to/photo --album_id=X` to import large album.
This way, the import is done without multi-threading, which is faster, and less error prone on small servers.
