### ISSUE TITLE
Unable to turn off location display

### ISSUE THREAD

**Issue by ABLomas** [LycheeOrg/Lychee#641]
Latest master, older installation.
I want to hide GPS coordinates display (but keep other EXIF info, like exposure, camera model and so on).
Tried to turn off all map-related values in configuration - but i still have long/lat and alt information with photo.

From config:
    location_decoding:          0
    location_decoding_timeout:  30
    location_show:              0
    location_show_public:       0

Photo example with all coords turned off but displayed location:
https://pics.lag.lt/#15518217910869/15928555484092

Can hide map, yes:
    map_display:                0
    map_display_public:         0
    map_provider:               Wikimedia
...it's not displayed, but coordinates are still here.
IIRC it was working some time ago (i can choose to show coordinates only when logged in), guess this was changed when maps are added?

**Comment by tmp-hallenser** [comment]
these settings are related to the map and the location name, not the coordinates itself.

**Comment by ABLomas** [comment]
Looks like this is the case.
OK, in short - without making global changes - how can i hide lat/lon/alt - i commented them in public/dist/view.js (entire structure.location) but they are still shown - do i need to "refresh template" somehow?

**Comment by ABLomas** [comment]
Oh, this was "public/dist/main.js" instead, responsible for adding location information.
I will close this, should probably do proper enhancement request (setting to turn it on or off) in future.

**Comment by ildyria** [comment]
> I will close this, should probably do proper enhancement request (setting to turn it on or off) in future.

:+1:
