### ISSUE TITLE
Lychee install 4.06 install stops on the check permission step

### ISSUE THREAD

**Issue by ghosh8bigfoot** [LycheeOrg/Lychee#642]
### Detailed description of the problem [REQUIRED]
I downloaded the Lychee zip file and unpacked it under the root directory of my web server, When I go to the home page and go to Lychee/public directory - the installation starts. So far so good. However, on the third step of installation it stops with the permission check where it is all good with reading and writing but has red flags on executable. Does not allow me to proceed from here.

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Go to 'web home page'
2. Click on 'lychee/public'
3. Start Lychee installation
4. See error on third step

**Screenshots**
![image](https://user-images.githubusercontent.com/24318001/85959663-51976a80-b963-11ea-9c58-2468ce398ca7.png)

*If applicable, add screenshots to help explain your problem.*
How do I get past this?
### Output of the diagnostics  [REQUIRED]
*(Settings => Diagnostics or https://example.com/Diagnostics or `php artisan lychee:diagnostics`)*

**Comment by ildyria** [comment]
You need to give the execute permission to the said folders to your web user:

```
chmod a+x .
chmod  a+x storage/framework/
chmod  a+x storage/logs/
chmod  a+x bootstrap/cache/
... etc
```

**Comment by ghosh8bigfoot** [comment]
I am using windows 10 and I see that permissions on all users are allowed full control for all those directories.

**Comment by ildyria** [comment]
Should be fixed with the latest PR.
We are basically overriding the executable check in the case of Windows.

**Comment by ghosh8bigfoot** [comment]
Thank you. Let me give this a try.
