### ISSUE TITLE
Video thumbnail and aperture

### ISSUE THREAD

**Issue by ikosa** [LycheeOrg/Lychee#647]
Lychee cant create thumb for some of my old videos. Today i realize that ffmpeg can decode them. And the below lines are the responsible part of the code. When i comment out that part thumbnails are created.
What is the relation between aperture and video thumbnail creation? 
These videos cannot be played at the browser (some of them just played as audio) but that is another issue i will investigate later are there somehow a relation between aperture and html5 video support?
I think if it is possible all videos have to be thumbs to give an idea about that video if html5 didnt support that video i can download it.

https://github.com/LycheeOrg/Lychee/blob/f5ebb14de86caa5890e503efab83f62952d73116/app/ModelFunctions/PhotoFunctions.php#L542-L544

**Comment by ildyria** [comment]
A few lines later:
https://github.com/LycheeOrg/Lychee/blob/f5ebb14de86caa5890e503efab83f62952d73116/app/ModelFunctions/PhotoFunctions.php#L552

and 
https://github.com/LycheeOrg/Lychee/blob/f5ebb14de86caa5890e503efab83f62952d73116/app/Metadata/Extractor.php#L247-L249

Conclusion, aperture contains the duration of the video while the focal contains the frame rate.
