### ISSUE TITLE
No thumbnail for .png and .gifs

### ISSUE THREAD

**Issue by imiduno** [LycheeOrg/Lychee#651]
### Detailed description of the problem [REQUIRED]
No thumbnail is used for .png and .gifs files.
Whenever I upload a .png or. gif file, the dimensions are ignored when creating the thumbnail with the error: "744 - No resizing (the image is too small:…)". It's the big version of the image which is used in the gallery.
I tried 3 new installations of Lychee, one manually from the .zip version, and two from the master branch with composer. Always the same error. 

### Log:
![2020-07-06_17h39_01](https://user-images.githubusercontent.com/67915459/86611919-a6fcf880-bfaf-11ea-94cb-b3cfcff7299e.png)

### Steps to reproduce the issue

Fresh install of lychee-laravel > upload file > any PNG or GIF

**Screenshots**
![2020-07-06_17h18_41](https://user-images.githubusercontent.com/67915459/86609888-dcecad80-bfac-11ea-9b72-3434d6bcfdbf.png)

### Output of the diagnostics  [REQUIRED]
`   Diagnostics
    -------
    Info: Latest version of PHP is 7.4
    Warning: Dropbox import not working. dropbox_key is empty.

    System Information
    --------------
    Lychee Version (release):   4.0.6
    DB Version:                 4.0.6
    
    composer install:           --no-dev
    APP_ENV:                    production
    APP_DEBUG:                  false
    
    System:                     Linux
    PHP Version:                7.3
    SQLite Version:             3.26.0
    
    Imagick:                    1
    Imagick Active:             1
    Imagick Version:            1802
    GD Version:                 bundled (2.1.0 compatible)

    Config Information
    --------------
    version:                    040006
    check_for_updates:          0
    sorting_Photos_col:         takestamp
    sorting_Photos_order:       ASC
    sorting_Albums_col:         max_takestamp
    sorting_Albums_order:       ASC
    imagick:                    1
    skip_duplicates:            0
    small_max_width:            0
    small_max_height:           360
    medium_max_width:           1920
    medium_max_height:          1080
    lang:                       en
    layout:                     1
    image_overlay:              1
    image_overlay_type:         desc
    default_license:            none
    compression_quality:        90
    full_photo:                 1
    delete_imported:            0
    Mod_Frame:                  1
    Mod_Frame_refresh:          30
    thumb_2x:                   1
    small_2x:                   1
    medium_2x:                  1
    landing_page_enable:        0
    landing_owner:              John Smith
    landing_title:              John Smith
    landing_subtitle:           Cats, Dogs & Humans Photography
    landing_facebook:           https://www.facebook.com/JohnSmith
    landing_flickr:             https://www.flickr.com/JohnSmith
    landing_twitter:            https://www.twitter.com/JohnSmith
    landing_instagram:          https://instagram.com/JohnSmith
    landing_youtube:            https://www.youtube.com/JohnSmith
    landing_background:         dist/cat.jpg
    site_title:                 Lychee v4
    site_copyright_enable:      1
    site_copyright_begin:       2019
    site_copyright_end:         2019
    additional_footer_text:     
    display_social_in_gallery:  0
    public_search:              0
    SL_enable:                  0
    SL_for_admin:               0
    public_recent:              0
    recent_age:                 1
    public_starred:             0
    downloadable:               0
    photos_wraparound:          1
    map_display:                0
    zip64:                      1
    map_display_public:         0
    map_provider:               Wikimedia
    force_32bit_ids:            0
    map_include_subalbums:      0
    update_check_every_days:    3
    has_exiftool:               0
    share_button_visible:       0
    import_via_symlink:         0
    has_ffmpeg:                 0
    location_decoding:          0
    location_decoding_timeout:  30
    location_show:              1
    location_show_public:       0
    rss_enable:                 0
    rss_recent_days:            7
    rss_max_items:              100
    prefer_available_xmp_metadata: 0`

### Browser and system
Lychee v4.0.6 - Shared Server - Apache

**Comment by tmp-hallenser** [comment]
Could you share a sample? 

Please also give this one a try: https://xfer.w00t.cloud/inline/8TfmI/Screenshot%20from%202020-01-09%2021-35-35.png

**Comment by imiduno** [comment]
The problem arises with any png or gif. I tested with more than a hundred files that were well processed in Lychee v3, on the same server as this one. Your image has the same problem.

```
    2020-07-11 12:42:46 -- notice  -- App\ModelFunctions\PhotoFunctions::resizePhoto -- 744 -- No resize (image is too small: 0x720)!
    2020-07-11 12:42:46 -- notice  -- App\ModelFunctions\PhotoFunctions::resizePhoto -- 744 -- No resize (image is too small: 0x360)!
    2020-07-11 12:42:46 -- notice  -- App\ModelFunctions\PhotoFunctions::resizePhoto -- 744 -- No resize (image is too small: 3840x2160)!
    2020-07-11 12:42:46 -- notice  -- App\ModelFunctions\PhotoFunctions::resizePhoto -- 744 -- No resize (image is too small: 1920x1080)!
    2020-07-11 12:42:46 -- notice  -- App\Image\ImagickHandler::crop -- 153 -- Saving thumb to /home/laga8099/public_html/jv2/public/uploads/thumb/ab3f5c856b7b6ac7d1fb29255f867887.jpeg
```

Here is a sample:
![9468f54f234b268ad4495415240f3e4a](https://user-images.githubusercontent.com/67915459/87224452-cfa53980-c385-11ea-9cd8-35d9b799ba0c.png)

I don't have a lot of knowledge about servers and I have spent a lot of time testing everything described in the Lychee wiki (lycheeorg.github.io/docs/). A migration from v3, a new installation from scratch with ftp transfer only, with composer. With versions 4.0.0, 4.0.2 and 4.0.6 since the launch of v4. The whole installation goes perfectly, no errors, the rights of files / folders are ok. Everything works perfectly, there are only png and gif files which are problematic. No dimension is taken into account, and these files are always displayed as a square without thumb.
I necessarily forget something during installation or my shared server does not work properly with these types of files, but it is very surprising.

**Comment by tmp-hallenser** [comment]
Found the bug.

PHP-exif fails to extract the correct image dimensions unless you use exiftool.

Quick fix: Install exiftool and set config `has_exiftool` to 1.

**Comment by imiduno** [comment]
Thank you :)
I asked the administrators of the shared hosting if it was possible to install exiftool, but… it is not.
It is disappointing but I will have to stay on version 3.2 (with subfolders) for now.

**Comment by tmp-hallenser** [comment]
The upstream library should already be fixed. If you want, you could update the library PHP-EXIF manually. Then, it’s hopefully working.

**Comment by imiduno** [comment]
Yes, it's working! Thank you very much @tmp-hallenser You made my day!
