### ISSUE TITLE
[Enhancement] Add configurable option to have about-photo panel open by default

### ISSUE THREAD

**Issue by danshilm** [LycheeOrg/Lychee#653]
This is something that I find myself always opening manually and which I believe would be especially useful for people with wide enough screens. Of course, I believe it shouldn't apply to smaller screens like mobile phones (and tablets?) since the picture would be barely visible. 

However, this might be something that seems over the top, so a good compromise imo would be to make the about-panel's appearance persist throughout a user session. That way if I open it when I view my first picture after I sign in, it's open by default when I go to view another picture.

I'm actually gonna go dive in the codebase and see if I can make a PR for this if you guys have no issues with it.

**Comment by ildyria** [comment]
**I'm actually gonna go dive in the codebase and see if I can make a PR for this if you guys have no issues with it.**

I like that comment. :smiley: 

If you have any questions, feel free to drop by on gitter: https://gitter.im/LycheeOrg/Lobby

**Comment by LouisVallat** [comment]
A new mechanism has been introduced in PR https://github.com/LycheeOrg/Lychee-front/pull/276, which should fix this issue. With this PR, the sidebar's state/visibility is remembered during the whole browsing session.

Thanks for bringing this enhancement idea and helping improve Lychee :smile:
