### ISSUE TITLE
Video thumbnails are not generated after installing ffmpeg

### ISSUE THREAD

**Issue by candrea21** [LycheeOrg/Lychee#657]
Video thumbnails are not generated even thoug ffmpeg is installed. ffmpeg was installed after installation of Lychee.

**Comment by tmp-hallenser** [comment]
you need to set the parameter `has_ffmpeg` to 1 or reinstall Lychee.

**Comment by candrea21** [comment]
Thank you for your quick response. The problem was a bad configured PHP installation on my server, file execution outside webspace (open_basedir restriction in effect) was not allowed. Now everything works fine. Sorry for reporting an issue.
