### ISSUE TITLE
422 (Server error or API not found) when making a new album

### ISSUE THREAD

**Issue by alexbergsland** [LycheeOrg/Lychee#658]
### Detailed description of the problem [REQUIRED]
I got Lychee running yesterday, on a Ubuntu VM. I added a bunch of photos to upload/import.
When I tried to make an album I got 422 and gave it a rest til today, and now it worked, I was able to add a few nested albums no problem and added photos to them.
Then I selected some pics in Unsorted and tried to make an album for them and got the 422 again.
It might have something to do with starting in any of the Smart Albums. Because when I went into one of my already made albums I was able to make albums in there, same thing if I start on the "home page" and make an album from there, it works.

### Steps to reproduce the issue
1. Go to any of the smart albums
2. Click on + | New Album
3. Write something, click Create Album
4. See error 422 (Server error or API not found)

**Screenshots**
https://i.imgur.com/rmDCQFp.png

### Output of the diagnostics  [REQUIRED]

    Diagnostics
    -----------
    Warning: Dropbox import not working. dropbox_key is empty.

    System Information
    ------------------
    Lychee Version (git):       master (4524ec3) - Data not in Cache
    DB Version:                 4.0.6
    
    composer install:           --no-dev
    APP_ENV:                    production
    APP_DEBUG:                  true
    
    System:                     Linux
    PHP Version:                7.4
    Max uploaded file size:     500M
    Max post size:              500M
    MySQL Version:              8.0.20-0ubuntu0.20.04.1
    
    Imagick:                    1
    Imagick Active:             1
    Imagick Version:            1690
    GD Version:                 2.2.5

    Config Information
    ------------------
    version:                    040006
    check_for_updates:          0
    sorting_Photos_col:         takestamp
    sorting_Photos_order:       ASC
    sorting_Albums_col:         max_takestamp
    sorting_Albums_order:       ASC
    imagick:                    1
    skip_duplicates:            0
    small_max_width:            0
    small_max_height:           360
    medium_max_width:           1920
    medium_max_height:          1080
    lang:                       sv
    layout:                     1
    image_overlay:              1
    image_overlay_type:         desc
    default_license:            none
    compression_quality:        90
    full_photo:                 1
    delete_imported:            0
    Mod_Frame:                  1
    Mod_Frame_refresh:          30
    thumb_2x:                   1
    small_2x:                   1
    medium_2x:                  1
    landing_page_enable:        0
    landing_owner:              John Smith
    landing_title:              John Smith
    landing_subtitle:           Cats, Dogs & Humans Photography
    landing_facebook:           https://www.facebook.com/JohnSmith
    landing_flickr:             https://www.flickr.com/JohnSmith
    landing_twitter:            https://www.twitter.com/JohnSmith
    landing_instagram:          https://instagram.com/JohnSmith
    landing_youtube:            https://www.youtube.com/JohnSmith
    landing_background:         dist/cat.jpg
    site_title:                 Lychee v4
    site_copyright_enable:      1
    site_copyright_begin:       2019
    site_copyright_end:         2019
    additional_footer_text:     
    display_social_in_gallery:  0
    public_search:              0
    SL_enable:                  0
    SL_for_admin:               0
    public_recent:              0
    recent_age:                 1
    public_starred:             0
    downloadable:               0
    photos_wraparound:          1
    map_display:                0
    zip64:                      1
    map_display_public:         0
    map_provider:               Wikimedia
    force_32bit_ids:            0
    map_include_subalbums:      0
    update_check_every_days:    3
    has_exiftool:               0
    share_button_visible:       0
    import_via_symlink:         0
    has_ffmpeg:                 1
    location_decoding:          0
    location_decoding_timeout:  30
    location_show:              1
    location_show_public:       0
    rss_enable:                 0
    rss_recent_days:            7
    rss_max_items:              100
    prefer_available_xmp_metadata: 0
    editor_enabled:             1

### Browser and system
Firefox 78.0.1
Arch Linux

Lychee is running on Ubuntu 20.04 under Apache2 (and https) and database is mysql.

**Comment by ildyria** [comment]
> It might have something to do with starting in any of the Smart Albums. Because when I went into one of my already made albums I was able to make albums in there, same thing if I start on the "home page" and make an album from there, it works.

Nicely spotted, this is exactly that.
This is due to `parent_id: unsorted` (for example) and our validation verifies that it is an integer: 
```
{"message":"The given data was invalid.","errors":{"parent_id":["The parent id must be an integer."]}}
```

This should be fixed in the Front-end instead of the back-end.

**Comment by ildyria** [comment]
What basically need to be done is to add a check [here](https://github.com/LycheeOrg/Lychee-front/blob/master/scripts/main/album.js#L266) that if it is a smart album, then parent id is set to 0.

Some helper already provided: https://github.com/LycheeOrg/Lychee-front/blob/master/scripts/main/album.js#L10
