### ISSUE TITLE
Interface translation?

### ISSUE THREAD

**Issue by Oliverlin67** [LycheeOrg/Lychee#661]
Whether to allow me to provide traditional Chinese translation?(Lychee 4)

**Comment by tmp-hallenser** [comment]
Sure.

Please have a look into this directory: https://github.com/LycheeOrg/Lychee/tree/master/app/Locale
There you'll find our language packs.

**Comment by Oliverlin67** [comment]
So if I have translated Traditional Chinese language files, how should I use it? Do I need to modify the Lang.php ?
Following  is the language file I made😀
(Because Github prohibits uploading PHP, so change the extension to  TXT  file first)

[ChineseTraditional.txt](https://github.com/LycheeOrg/Lychee/files/4941569/ChineseTraditional.txt)
