### ISSUE TITLE
Files missing on clean installation

### ISSUE THREAD

**Issue by rainingmirrors** [LycheeOrg/Lychee#662]
### Detailed description of the problem

After downloading the zip-file and doing a clean install of Lychee via ftp I loaded the website and got the following error messages:

```
Warning: require(/data/web/e29333/html/lychee/public/../vendor/autoload.php): failed to open stream: No such file or directory in /data/web/e29333/html/lychee/public/index.php on line 43

Warning: require(/data/web/e29333/html/lychee/public/../vendor/autoload.php): failed to open stream: No such file or directory in /data/web/e29333/html/lychee/public/index.php on line 43

Fatal error: require(): Failed opening required '/data/web/e29333/html/lychee/public/../vendor/autoload.php' (include_path='.') in /data/web/e29333/html/lychee/public/index.php on line 43
```

Within the standard git package, the folder "vendor" and it's contents are missing. In the installation instructions I could not find any information on how to retrieve this folder. I tried installing via git client, that produced the same result, just as installing it on local and hosted web servers. Have I overlooked something when downloading or installing?

### Browser and system

Standard Linux Webhost as well as MAMP on OS X.
Tested with Firefox and Safari.

**Comment by ildyria** [comment]
You did not download the correct zip... See here: https://github.com/LycheeOrg/Lychee/releases/tag/v4.0.6 , You need to donwload Lychee.zip not "Source Code (zip)"

> I tried installing via git client, that produced the same result.

If you use the git client, then you need to use composer.

**Comment by rainingmirrors** [comment]
Thanks for the quick reply and clarification! 

I missed the link in the lefthand navigation and the fact, that I need to download that zip-file!
