### ISSUE TITLE
Error 500 on a fresh installation: Could not find driver

### ISSUE THREAD

**Issue by Durgon** [LycheeOrg/Lychee#672]
After creating the mysql database and assigning the database user the correct permissions, i receive an error 500 on installation with message: ` could not find driver (SQL: select * from information_schema.tables where table_schema = lychee and table_name = migrations and table_type = 'BASE TABLE') ` in browser
Output of `php artisan lychee:diagnostics`:
```
Diagnostics
-----------
Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.
Error: username empty or not set in database
Error: password empty or not set in database
Warning: Dropbox import not working. dropbox_key is empty.
Warning: Image optimizer enabled but cwebp not found!
Warning: Image optimizer enabled but jpegoptim not found!
Warning: Image optimizer enabled but optipng not found!
Warning: Image optimizer enabled but pngquant not found!
Warning: Image optimizer enabled but svgo not found!

System Information
------------------
Lychee Version (git):            master (febbad3) - Data not in Cache
DB Version:                      4.0.6

composer install:                --no-dev
APP_ENV:                         production
APP_DEBUG:                       true

System:                          Linux
PHP Version:                     7.4
Max uploaded file size:          2M
Max post size:                   8M
MySQL Version:                   8.0.20-0ubuntu0.20.04.1

Imagick:                         1
Imagick Active:                  1
Imagick Version:                 1690
GD Version:                      2.2.5
```
I have configured an sql user and password in the .env file.

**Comment by ildyria** [comment]
Okay, so from your diagnostic, I can tell that `php artisan lychee:diagnostics` is finding your driver and reading properly your `.env` file. The fact that we see these Error and Warnings also shows that you probably did `php artisan migrate`.

So this means that your php command line has access to the driver but not the php process that is used by your apache/nginx web server. That is the only explanation I have.

**Comment by Durgon** [comment]
Okay, thanks. I'll investigate the permissions issue then.

**Comment by ildyria** [comment]
Any updates?
