### ISSUE TITLE
Fresh install : Error 500

### ISSUE THREAD

**Issue by ghost** [LycheeOrg/Lychee#681]
Hello,

I installed the docker version from Linuxserver.io (v4.0.6-ls62).

I added my SQL informations on the config file and clicked on "install", it displays me en Error 500 with no additional error. 

![image](https://user-images.githubusercontent.com/206181/89089288-e9420b80-d39c-11ea-932b-b53e9ad07c1e.png)

SQL info:

DB_CONNECTION=mysql
DB_HOST=192.168.1.9
DB_PORT=3307
DB_DATABASE=lychee
DB_USERNAME=alex
DB_PASSWORD=removed
DB_LOG_SQL=false

I don't know how to provide more logs. I'm sorry.

Thank you

**Comment by d7415** [comment]
I don't know how their Docker image is set up. You may be able to follow https://lycheeorg.github.io/docs/faq.html#i-have-an-error-500-what-can-i-do

**Comment by ghost** [comment]
Thank your for your help, debug returns hundreds error, on the header the main error is: 
`SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client (SQL: select * from information_schema.tables where table_schema = lychee and table_name = migrations and table_type = 'BASE TABLE')`

**Comment by d7415** [comment]
That's one I haven't seen before. Have you tried connecting to the SQL server directly with a mysql client? (note: not locally on the SQL server)

**Comment by ghost** [comment]
I’m sorry I don’t understand. I use a docker version

**Comment by d7415** [comment]
Sorry, but I can't debug from that level of information. If you are unable to debug the SQL side I suggest you switch to the sqlite back end which simplifies the process significantly.

Alternatively, you could ask linuxserver.io whether they have any other ideas.
