### ISSUE TITLE
Does not create all photos symlink when after migrate from version-4-beta to 4.0.6 with official-docker

### ISSUE THREAD

**Issue by yoshinorin** [LycheeOrg/Lychee#684]
### Detailed description of the problem [REQUIRED]

After migrate `4.0.6` from `Version 4-beta`, some photos don't appear as below.

![image](https://user-images.githubusercontent.com/11273093/89309490-6ecfff00-d6ae-11ea-8499-00047b05ff3b.jpg)

I used `Version4-beta` with [lychee-docker: bigrob8181/lychee-laravel](https://github.com/LycheeOrg/Lychee-Docker). (Sorry, I don't remember which commit...) Today, I upgrade it to `4.0.6`. Also, I using [lychee-docker: latest](https://github.com/LycheeOrg/Lychee-Docker). 

I assume this caused by the symlink. Because, I have `1455` photos, but symlinks are only `485`. I checked it on the database.

Some of the photo's symlink were created when I click the album. But others never created.

### Steps to reproduce the issue

* Migrate v4-beta (Sorry, I don't remember which commit) to `4.0.6` with [lychee-docker](https://github.com/LycheeOrg/Lychee-Docker). 

### Output of the diagnostics  [REQUIRED]

```
    Diagnostics
    -------
    Info: Latest version of PHP is 7.4
    Warning: Dropbox import not working. dropbox_key is empty.



    System Information
    --------------
    Lychee Version (git):       No git data found.
    DB Version:                 4.0.6
    
    composer install:           --no-dev
    APP_ENV:                    local
    APP_DEBUG:                  true
    
    System:                     Linux
    PHP Version:                7.3
    MySQL Version:              10.4.7-MariaDB-1:10.4.7+maria~bionic-log
    
    Imagick:                    1
    Imagick Active:             1
    Imagick Version:            1690
    GD Version:                 2.2.5



    Config Information
    --------------
    version:                    040006
    check_for_updates:          1
    sorting_Photos_col:         takestamp
    sorting_Photos_order:       DESC
    sorting_Albums_col:         title
    sorting_Albums_order:       ASC
    imagick:                    1
    skip_duplicates:            0
    small_max_width:            0
    small_max_height:           360
    medium_max_width:           1920
    medium_max_height:          1080
    lang:                       en
    layout:                     1
    image_overlay:              1
    image_overlay_type:         exif
    default_license:            reserved
    compression_quality:        100
    full_photo:                 1
    delete_imported:            0
    Mod_Frame:                  0
    Mod_Frame_refresh:          30
    thumb_2x:                   1
    small_2x:                   1
    medium_2x:                  1
    landing_page_enable:        0
    landing_owner:              YoshinoriN
    landing_title:              YoshinoriN
    landing_subtitle:           Cats, Dogs & Humans Photography
    landing_facebook:           https://www.facebook.com/JohnSmith
    landing_flickr:             https://www.flickr.com/JohnSmith
    landing_twitter:            https://www.twitter.com/JohnSmith
    landing_instagram:          https://instagram.com/JohnSmith
    landing_youtube:            https://www.youtube.com/JohnSmith
    landing_background:         dist/cat.jpg
    site_title:                 Photo
    site_copyright_enable:      1
    site_copyright_begin:       2019
    site_copyright_end:         2019
    additional_footer_text:     
    display_social_in_gallery:  0
    public_search:              1
    SL_enable:                  1
    SL_for_admin:               1
    public_recent:              1
    recent_age:                 7
    public_starred:             1
    downloadable:               0
    photos_wraparound:          1
    map_display:                1
    zip64:                      1
    map_display_public:         1
    map_provider:               Wikimedia
    force_32bit_ids:            0
    map_include_subalbums:      1
    update_check_every_days:    1
    has_exiftool:               0
    share_button_visible:       0
    import_via_symlink:         0
    has_ffmpeg:                 1
    location_decoding:          0
    location_decoding_timeout:  30
    location_show:              1
    location_show_public:       0
    rss_enable:                 0
    rss_recent_days:            7
    rss_max_items:              100
    prefer_available_xmp_metadata: 0
```

### Browser and system

* Chrome 84.0.4147.105
* Ubuntu 20.04 (Host OS)

### Ouestion

* Why some of the photo's symlink never create?
* Is there any way to create all symlinks? (e.g. using by Laravel command)

Thank you :)

**Comment by d7415** [comment]
In older versions of the Docker image, the symlinks folder wasn't preserved. I suspect the missing ones are ones that are in the database but have been deleted.

I'm not at a suitable machine to check, but it should be possible to clear them out so that they're recreated. Depending on your settings they may expire soon anyway, but I'll try to take a look later if no-one beats me to it.

**Comment by d7415** [comment]
Right. So...

- It looks like the migration didn't work properly because you should have a `SL_life_time_days` configuration option.
- Because that doesn't exist, they should timeout at 3 days.
- Personally, I'd cheat, re-delete the symlinks folder and clear the DB table, but I am impatient and willing to accept any unexpected results....
- Another option would be to add `SL_life_time_days` and set it to a lower value. At this point 1 should do it. Once everything is working you could reset it to 3.

There is a chance that Lychee will get upset when it tries to delete a non-existent symlink, but I won't worry about that until/unless it happens.

**Comment by yoshinorin** [comment]
@d7415 
I deleted the sym_links table records once.
After that, all photos appear correctly.

Thank you very much :)
