### ISSUE TITLE
Failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by ChristopherBittner** [LycheeOrg/Lychee#685]
I'm using hosting24 as my domain host provider. 
I was able to install your plugin, create some albums and upload couple of photos.
Some time later it started to return this error upon every upload I try.

2020-08-08 18:15:10 -- notice  -- App\Metadata\GitHubFunctions::__construct -- 49 -- file_get_contents(/home/genuitxc/public_html/gallery/.git/HEAD): failed to open stream: No such file or directory

Not sure why your plugin would try to call git functionalities. 
Do you have any idea what is going on there?
I can provide more logs or info if needed.

**Comment by d7415** [comment]
That's not an error. That's just a notice. It shouldn't stop anything from working.

FWIW we check for the existence of git files as a method of version control for users who are downloading Lychee using git. If they are not found, we look elsewhere.

**Comment by ildyria** [comment]
> Not sure why your plugin would try to call git functionalities.

Just to know if you are up-to-date. Also this is not an `exec` call. @d7415 completed the answer.
