### ISSUE TITLE
Upload fails with some photos (pull request) ISOSPEEDRATINGS

### ISSUE THREAD

**Issue by danieljulia** [LycheeOrg/Lychee#687]
Several photo upload fail

### Steps to reproduce the issue

Just uploading some photos, it fails repeteadly giving an error message.
The error is registered in the logs as a php error in the explode php function

Seems related to the formatting of the ISOSPEEDRATINGS in some photos.

I have fixed it adding an exception and giving a 0 value in case it fails,

/vendor/lychee-org/php-exif/lib/PHPExif/Mapper/Native.php

With this the problem is fixed (sorry i know it should be a pull request)

    `  break;
                case self::ISOSPEEDRATINGS:
                  try{ 
                    $value = explode(" ", $value)[0];
                  }catch(Exception $e){
                     $value = 0;
                 }
                    break;`

**Comment by tmp-hallenser** [comment]
Could you share a sample file? Thanks!

**Comment by danieljulia** [comment]
You can try with this for instance https://www.dropbox.com/s/i6ggwqoyyh5jyw0/20140813_vacances_suecia_014_14982439200_o.jpg?dl=0

**Comment by tmp-hallenser** [comment]
I've created a fix in the php-exif library. Feel free to give it a test.

https://github.com/LycheeOrg/php-exif/pull/24

**Comment by ildyria** [comment]
Any update ?

**Comment by ildyria** [comment]
Fixed.
