### ISSUE TITLE
[Enhancement] Quasi-pull request: improved configuration block for Nginx

### ISSUE THREAD

**Issue by coridonhenshaw** [LycheeOrg/Lychee#688]
I can't find a way to submit a pull request against the Lychee documentation so I'm posting this here for consideration. I have written a new configuration block for using Lychee with Nginx, with the primary aim of improving the installation process for new users and improving maintainability.

When I installed Lychee, I ran into problems because the very simple Nginx configuration in the installation instructions didn't capture all of the endpoints the front end uses to communicate with the back end. I had to copy the Nginx configuration from the Docker version of Lychee to get a working install. My aim with the new code is to improve this experience for others.

This code may be relevant to:

https://lycheeorg.github.io/docs/installation.html#pretty-urls
https://lycheeorg.github.io/docs/upgrade.html#using-nginx
https://github.com/LycheeOrg/Lychee-Docker/blob/master/default.conf

Benefits:

1. The configuration block provides a heavily-commented turnkey setup template that requires minimal adjustment to work. 

2. Removed `if` directives. Nginx doesn't play well with `if` and the Nginx documentation strongly recommends that `if` should be avoided. `If`, as used in the existing Lychee configruation, has a higher priority than normal `location` directives, which makes the configuration difficult to reason with and prevents using additional `location` blocks to override the favicon or to drop requests by obvious bots.

3. Attack surface minimization. This Nginx configuration will only pass index.php to the php engine and will only serve known file types to clients. E.g., if someone accidentally leaves a database dump in public/, it won't be served.

4. Front-end requests to /Lychee-front/images/ are rewritten to the correct path. Eliminates untidy 404 errors when working with the front-end using developer tools.

5. Lower resource use. Missing files and other errors are handled directly by Nginx without calling the php engine. Options to drop HTTP/1.0 traffic, which is generally from hostile bots, and to close the connection in response to all errors.

Code:

[nginx.lychee.host.txt](https://github.com/LycheeOrg/Lychee/files/5081151/nginx.lychee.host.txt)

**Comment by ildyria** [comment]
Hi @coridonhenshaw you can submit PR to the documentation here:
https://github.com/LycheeOrg/LycheeOrg.github.io/

the documentation code is in https://github.com/LycheeOrg/LycheeOrg.github.io/tree/master/docs/md
and the html is generated via: https://github.com/LycheeOrg/LycheeOrg.github.io/blob/master/docs/makefile

**Comment by ildyria** [comment]
todo: add in the documentation how to add PR to the documentation. :smiley:

**Comment by mulimoen** [comment]
@coridonhenshaw I think there must be a rule missing on a first time install, `/install` is not routed correctly through to `index.php`, giving a `404` when doing the initial installation.

**Comment by ildyria** [comment]
@mulimoen Nicely spotted. Additionally also missing: `/gallery` and `/frame`  (and other pages that could be added later).

**Comment by ildyria** [comment]
Fixed.

**Comment by zeus86** [comment]
Nice nginx config, but I think it is not reflected by the docs at https://lycheeorg.github.io/docs/installation.html .
Quite vital convenience-features like `index index.php;` are missing, leading to the problem,that a fresh installation won't redirect you to the install-script nor to the index-page after installation (beside other things).
