### ISSUE TITLE
Unable to access more advanced settings

### ISSUE THREAD

**Issue by EriksonEnterprises** [LycheeOrg/Lychee#692]
### Detailed description of the problem [REQUIRED]
I have no ability to edit advanced settings like: Layout, Public Search, Site Title, ETC. I went through the setup and it let me setup an initial account that looks like the admin dashboard I've seen screenshots of, but when I go to the settings COG, all I see is: Change Login, Change Sorting, Set Dropbox, About Lychee, Diagnostics, Show Log, and Log Out. I also have no ability to add users?? Please let me know what I might need to do to fix this

### Output of the diagnostics  [REQUIRED]
Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
No critical problems found. Lychee should work without problems!

System Information
------------------
Lychee Version:  3.1.6
DB Version:      030102
System:          Linux
PHP Version:     7
MySQL Version:   50649
Imagick:         1
Imagick Active:  1
Imagick Version: 1802
GD Version:      bundled (2.1.0 compatible)
Plugins:         

### Browser and system
Apache and PHP through Linux

**Comment by ildyria** [comment]
![2020-08-19_1920x1080_10:34:09](https://user-images.githubusercontent.com/627094/90612021-c5d5e800-e207-11ea-891d-6c7f6ccfed73.png)


Read here: https://lycheeorg.github.io/docs/upgrade.html

**Comment by jamesautodude** [comment]
FRESH INSTALL, NOT AN UPGRADE!

> ![2020-08-19_1920x1080_10:34:09](https://user-images.githubusercontent.com/627094/90612021-c5d5e800-e207-11ea-891d-6c7f6ccfed73.png)
> 
> Read here: https://lycheeorg.github.io/docs/upgrade.html

**Comment by d7415** [comment]
> FRESH INSTALL, NOT AN UPGRADE!

@ildyria's point is that you are using an unsupported version - you are not even using the most recent version of Lychee-v3 (which is 3.2.16). You appear to be using the last electerious release, and then asking for support in a different repository. I suggest you either try v4.0.6 or go to wherever you obtained the obsolete version and ask them for support instead.
