### ISSUE TITLE
Sometimes get message: Missing Parameters

### ISSUE THREAD

**Issue by EriksonEnterprises** [LycheeOrg/Lychee#693]
### Detailed description of the problem [REQUIRED]
Sometimes when I click on an album while logged in after awhile... It says:

Missing Parameters. Can not execute function Lychee\Access\Admin::setPositionAction

### Output of the diagnostics  [REQUIRED]
Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
No critical problems found. Lychee should work without problems!

System Information
------------------
Lychee Version:  3.1.6
DB Version:      030102
System:          Linux
PHP Version:     7
MySQL Version:   50649
Imagick:         1
Imagick Active:  1
Imagick Version: 1802
GD Version:      bundled (2.1.0 compatible)
Plugins:

**Comment by ildyria** [comment]
![2020-08-19_1920x1080_10:34:09](https://user-images.githubusercontent.com/627094/90612021-c5d5e800-e207-11ea-891d-6c7f6ccfed73.png)


Read here: https://lycheeorg.github.io/docs/upgrade.html

**Comment by jamesautodude** [comment]
This is a fresh install. I didn't upgrade!

> ![2020-08-19_1920x1080_10:34:09](https://user-images.githubusercontent.com/627094/90612021-c5d5e800-e207-11ea-891d-6c7f6ccfed73.png)
> 
> Read here: https://lycheeorg.github.io/docs/upgrade.html
