### ISSUE TITLE
Server Returned an Unknown Response

### ISSUE THREAD

**Issue by EriksonEnterprises** [LycheeOrg/Lychee#694]
### Detailed description of the problem [REQUIRED]
Says "Server Returned an Unknown Response. Please look at the console of your browser for further details".

In the console it says:
{description: "Upload failed. Server returned an unkown error!", params: XMLHttpRequest, response: ""}
description: "Upload failed. Server returned an unkown error!"
params: XMLHttpRequest {onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, …}
response: ""
__proto__: Object

What does this mean? only happens when I try to upload a photo to an album

### Output of the diagnostics  [REQUIRED]
Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
No critical problems found. Lychee should work without problems!

System Information
------------------
Lychee Version:  3.1.6
DB Version:      030102
System:          Linux
PHP Version:     7
MySQL Version:   50649
Imagick:         1
Imagick Active:  1
Imagick Version: 1802
GD Version:      bundled (2.1.0 compatible)
Plugins:

**Comment by ildyria** [comment]
![2020-08-19_1920x1080_10:34:09](https://user-images.githubusercontent.com/627094/90612021-c5d5e800-e207-11ea-891d-6c7f6ccfed73.png)


Read here: https://lycheeorg.github.io/docs/upgrade.html

**Comment by jamesautodude** [comment]
FRESH INSTALL, I DID NOT UPGRADE!

> ![2020-08-19_1920x1080_10:34:09](https://user-images.githubusercontent.com/627094/90612021-c5d5e800-e207-11ea-891d-6c7f6ccfed73.png)
> 
> Read here: https://lycheeorg.github.io/docs/upgrade.html

**Comment by ildyria** [comment]
Please do not shout.

Your installation **clearly** states you are using Lychee Version: 3.1.6

If it is a Fresh installation, then you will have no problem installing version 4 from here: https://github.com/LycheeOrg/Lychee/releases

**Comment by EriksonEnterprises** [comment]
> Please do not shout.
> 
> Your installation **clearly** states you are using Lychee Version: 3.1.6
> 
> If it is a Fresh installation, then you will have no problem installing version 4 from here: https://github.com/LycheeOrg/Lychee/releases

Looks like I freaking downloaded the wrong version. You are right, thank you. Just been frustrated for over 3 hours trying to figure it out. Thank goodness I haven't uploaded anything! THANK YOU
