### ISSUE TITLE
Unexpected "=" in vender/laravel

### ISSUE THREAD

**Issue by EriksonEnterprises** [LycheeOrg/Lychee#698]
### Detailed description of the problem [REQUIRED]
Parse error: syntax error, unexpected '=' in /vendor/laravel/framework/src/Illuminate/Support/Arr.php on line 416

which is:
[$value, $key] = static::explodePluckParameters($value, $key);

why would that be happening?

Version 4.0.6

**Comment by ildyria** [comment]
That is VERY weird.

Can you gives us more information, such as what did you do to get this error ? Which version of php you are using, is this when you use artisan ?

**Comment by ildyria** [comment]
Doing a quick google up leads me to guess that you are using a php version which we are not supporting anymore:
https://laracasts.com/discuss/channels/laravel/unexpected-illuminatesupportarrphp-on-line-388

Please make sure you are using **at least** PHP 7.2, ideally upgrade to PHP 7.4 as we may update some breaking change in a near future...

Note that anything below 7.2 is not even supported officially anymore by php: https://www.php.net/supported-versions.php

**Comment by jamesautodude** [comment]
Great looks like the highest version they offer is 7.0 with the hosting company I'm with :( Guess I can't use this. Thanks anyways!

**Comment by jamesautodude** [comment]
I just chatted with them and they upped it to 7.4, thank goodness. Going to test it out now, thank you

**Comment by EriksonEnterprises** [comment]
OMFG IT WORKS!! THANKS!

**Comment by EriksonEnterprises** [comment]
Do you happen to know the code for Pacific Standard Time for the TIMEZONE inside the config/app.php file?

**Comment by EriksonEnterprises** [comment]
Now I'm getting this error:
/.git/HEAD: failed to open stream: No such file or directory

**Comment by EriksonEnterprises** [comment]
Console says:
public/api/Albums::get 400 (Bad Request)

**Comment by ildyria** [comment]
What do you mean by this error ? 

Is it in the logs ? If so it is totally fine. see here:
https://lycheeorg.github.io/docs/faq.html#why-are-there-messages-about-git-files-in-my-logs-eg-githead-failed-to-open-stream-no-such-file-or-directory

**Comment by EriksonEnterprises** [comment]
Well after the setup, I tried to access it and I got the prompt to set my username and password, but then it disappears and it keeps saying "Error: Session Timeout" over and over again and wont let me do anything

**Comment by ildyria** [comment]
> public/api/Albums::get 400 (Bad Request)

Even though it is a 400 instead of 500, can you please have a look at this:
https://lycheeorg.github.io/docs/faq.html#when-i-do-x-i-get-an-error-api-not-found-what-can-i-do

Additionally, you can switch `APP_DEBUG` to `true` in your `.env` file, this will display helpful debug informations.
Don't forget to switch it back to `false` after.

**Comment by ildyria** [comment]
> Well after the setup, I tried to access it and I got the prompt to set my username and password, but then it disappears and it keeps saying "Error: Session Timeout" over and over again and wont let me do anything

Can you join the gitter ? https://gitter.im/LycheeOrg/Lobby (you just need to login with your github account)
It will be easier to debug. 👍

**Comment by EriksonEnterprises** [comment]
> > Well after the setup, I tried to access it and I got the prompt to set my username and password, but then it disappears and it keeps saying "Error: Session Timeout" over and over again and wont let me do anything
> 
> Can you join the gitter ? https://gitter.im/LycheeOrg/Lobby (you just need to login with your github account)
> It will be easier to debug. 👍

Just signed up, I'm on there now
