### ISSUE TITLE
Help needed: Installing

### ISSUE THREAD

**Issue by Aevaris** [LycheeOrg/Lychee#700]
### Detailed description of the problem [REQUIRED]
*A clear and concise description of what the bug is.*

Hi all, I am limitedly familiar with web servers, but got Lychee 3, Joomla, and some other systems to install but am having a real hard time with Lychee 4. I am installing on a Synology NAS using PHP 7.3. I'm trying to install fresh with Lychee 4.

I extracted the latest Release directory and basically have problems from there. I get a 403 on the main Lychee directory and a 404 on the Lychee/public directory as it navigates me to Lychee/public/install which doesn't exist. 

Is there something I missed?

**Comment by ildyria** [comment]
My guess is the rewrite module of Apache missing, or the configuration of Nginx.

**Comment by Aevaris** [comment]
I switched my backend from Nginx to Apache 2.4 and the issue went away. *shrug* Thanks!
