### ISSUE TITLE
the original of the Photo don't exist in Lychee/public/uploads/big

### ISSUE THREAD

**Issue by JacquelinDV** [LycheeOrg/Lychee#702]
Bonjour,
When I want see the initial photo, I have the response: 403  FORBIDDEN You don't have permission to access this resource.
I query the uploads/big directory and I notice that for all the photos which I do not access the original image the name of the file refers to a link in the upload /import directory which does not contain any files because it is for me a temporary working directory that allows updating the photos in Lychee.
How to recreate these photos in uploads/big to have a coherent set that can be downloaded?

Par exemple:
lrwxrwxrwx 1 www-data www-data       158 mars   6 14:06 fffbc79d6601dea19c164bac5833666e.jpg -> '/var/www/html/Lychee/public/uploads/import/Photos/5 Août 2017 - Mariage/Mariage-Civil/Champagne-sur-la-plage/plage-greg-85.jpg'
lrwxrwxrwx 1 www-data www-data        80 mars   5 22:21 fffe9aa7ae8a1816ca90eb4fdf77d742.JPG -> '/var/www/html/Lychee/public/uploads/import/Photos/2006/07 - Juillet/DSCN7742.JPG'
when I make a download to backup my photos I have some thousands of following lines:
2020-08-22 17:03:45 -- error   -- App\Http\Controllers\{closure} -- 786 -- Original photo missing: /var/www/html/Lychee/public/uploads/big/ab13bda20942a13742d9340aaaa9039d.JPG
    2020-08-22 17:03:45 -- error   -- App\Http\Controllers\{closure} -- 786 -- Original photo missing: /var/www/html/Lychee/public/uploads/big/65540bb1c062e9cb1aaf7f8ebe8d70cb.JPG
    2020-08-22 17:03:45 -- error   -- App\Http\Controllers\{closure} -- 786 -- Original photo missing: /var/www/html/Lychee/public/uploads/big/194047374ad3302bf04e50fc6efeefa0.JPG
    2020-08-22 17:03:45 -- error   -- App\Http\Controllers\{closure} -- 786 -- Original photo missing: /var/www/html/Lychee/public/uploads/big/8650ad37d5b559a06ecae81af5268f19.JPG
    2020-08-22 17:03:45 -- error   -- App\Http\Controllers\{closure} -- 786 -- Original photo missing: /var/www/html/Lychee/public/uploads/big/b53013cc56826761abaef6040bc65e91.JPG
    2020-08-22 17:03:45 -- error   -- App\Http\Controllers\{closure} -- 786 -- Original photo missing: /var/www/html/Lychee/public/uploads/big/d8e85095daca0a0277f6b54920b553c2.JPG
    2020-08-22 17:03:45 -- error   -- App\Http\Controllers\{closure} -- 786 -- Original photo missing: /var/www/html/Lychee/public/uploads/big/3a4f66a1e0cbee9669f109aa10b32c90.JPG
    2020-08-22 17:03:45 -- error   -- App\Http\Controllers\{closure} -- 786 -- Original photo missing: /var/www/html/Lychee/public/uploads/big/8e3a9867606e94ca312b27326913f7fb.JPG
    2020-08-22 17:03:45 -- error   -- App\Http\Controllers\{closure} -- 786 -- Original photo missing: /var/www/html/Lychee/public/uploads/big/d3d47e2ac1abba564ed6e9f9f6b46054.JPG
    2020-08-22 17:03:45 -- error   -- App\Http\Controllers\{closure} -- 786 -- Original photo missing: /var/www/html/Lychee/public/uploads/big/eb5573f5718d948d6d737299cf8394df.JPG
    2020-08-22 17:03:45 -- error   -- App\Http\Controllers\{closure} -- 786 -- Original photo missing: /var/www/html/Lychee/public/uploads/big/9afef2e06e697c5bfb03038836da80d9.JPG
    2020-08-22 17:03:45 -- error   -- App\Http\Controllers\{closure} -- 786 -- Original photo missing: /var/www/html/Lychee/public/uploads/big/6f67a962bd8889b085ebe3d24666707a.JPG

Diagnostics:
  Diagnostics
    -------
    Warning: Dropbox import not working. dropbox_key is empty.

    System Information
    --------------
    Lychee Version (git):            master (3203891) - Data not in Cache
    DB Version:                      4.0.6
    
    composer install:                dev
    APP_ENV:                         local
    APP_DEBUG:                       true
    
    System:                          Linux
    PHP Version:                     7.4
    Max uploaded file size:          500M
    Max post size:                   500M
    MySQL Version:                   10.1.44-MariaDB-0ubuntu0.18.04.1
    
    Imagick:                         1
    Imagick Active:                  1
    Imagick Version:                 1687
    GD Version:                      2.3.0
    
    Lychee total space:              37.84 GB
    Upload folder space:             36.50 GB
    System total space:              226.78 GB
    System free space:               128.84 GB (56%)

    Config Information
    --------------
    version:                         040006
    check_for_updates:               1
    sorting_Photos_col:              takestamp
    sorting_Photos_order:            ASC
    sorting_Albums_col:              title
    sorting_Albums_order:            ASC
    imagick:                         1
    skip_duplicates:                 1
    small_max_width:                 0
    small_max_height:                360
    medium_max_width:                1920
    medium_max_height:               1080
    lang:                            fr
    layout:                          1
    image_overlay:                   1
    image_overlay_type:              exif
    default_license:                 reserved
    compression_quality:             90
    full_photo:                      1
    delete_imported:                 1
    Mod_Frame:                       0
    Mod_Frame_refresh:               30
    thumb_2x:                        1
    small_2x:                        1
    medium_2x:                       1
    landing_page_enable:             0
    landing_owner:                   JDV
    landing_title:                   Mes Albums
    landing_subtitle:                Ma famille, mes voyages, mes amis...
    landing_facebook:                https://www.facebook.com/JohnSmith
    landing_flickr:                  https://www.flickr.com/JohnSmith
    landing_twitter:                 https://www.twitter.com/JohnSmith
    landing_instagram:               https://instagram.com/JohnSmith
    landing_youtube:                 https://www.youtube.com/JohnSmith
    landing_background:              dist/cat.jpg
    site_title:                      Mes Photos
    site_copyright_enable:           1
    site_copyright_begin:            1900
    site_copyright_end:              2020
    additional_footer_text:          
    display_social_in_gallery:       0
    public_search:                   0
    SL_enable:                       0
    SL_for_admin:                    0
    public_recent:                   0
    recent_age:                      10
    public_starred:                  0
    downloadable:                    1
    photos_wraparound:               1
    map_display:                     0
    zip64:                           1
    map_display_public:              0
    map_provider:                    Wikimedia
    force_32bit_ids:                 0
    map_include_subalbums:           0
    update_check_every_days:         3
    has_exiftool:                    1
    share_button_visible:            1
    import_via_symlink:              1
    has_ffmpeg:                      1
    location_decoding:               1
    location_decoding_timeout:       30
    location_show:                   1
    location_show_public:            0
    rss_enable:                      0
    rss_recent_days:                 7
    rss_max_items:                   100
    prefer_available_xmp_metadata:   0
    editor_enabled:                  1
    lossless_optimization:           0
    swipe_tolerance_x:               150
    swipe_tolerance_y:               250
    local_takestamp_video_formats:   .avi|.mov

**Comment by d7415** [comment]
> import_via_symlink:              1

This setting (which defaults off) causes Lychee to use symlinks instead of moving or copying files from the import directory. If you have deleted the original files, they are now gone and only the resized versions remain.

**Comment by JacquelinDV** [comment]
OK, I don't find this info in the documentation! Could you update the
documentation please.
Merci

Le sam. 22 août 2020 à 20:24, Martin Stone <notifications@github.com> a
écrit :

**Comment by d7415** [comment]
We probably could use a proper reference for the advanced settings, but unfortunately to get into your situation it is necessary to ignore the message "Changing these advanced settings can be harmful to the stability, security and performance of this application. You should only modify them if you are sure of what you are doing." as that setting defaults to `0`.

**Comment by ildyria** [comment]
https://lycheeorg.github.io/docs/settings.html < to be updated.

**Comment by d7415** [comment]
> https://lycheeorg.github.io/docs/settings.html < to be updated.

Ah, I thought we had one, but in a rush only searched for that setting.

**Comment by JacquelinDV** [comment]
Merci
