### ISSUE TITLE
Fresh installation: "The POST method is not supported for this route"

### ISSUE THREAD

**Issue by apfelbox** [LycheeOrg/Lychee#707]
### Detailed description of the problem [REQUIRED]
*A clear and concise description of what the bug is.*
I just installed Lychee, it's a completely new and fresh installation.
After configuring Caddy and PHP, setting up the database and the `.env`, I am now greeted with:

![2020-08-30 at 22 57](https://user-images.githubusercontent.com/1032411/91669319-4e139180-eb14-11ea-8774-2dd0be456eba.jpg)

Again, 100% fresh installation, I never opened it in the browser.

The `Session::init` request fails apparently:

![2020-08-30 at 22 59](https://user-images.githubusercontent.com/1032411/91669349-89ae5b80-eb14-11ea-8945-2b90f98c9b09.jpg)

![2020-08-30 at 23 00](https://user-images.githubusercontent.com/1032411/91669355-93d05a00-eb14-11ea-8b56-779e1ba6a81f.jpg)

The response does seem to come from the app and not the web server, as it has all the headers set:

![2020-08-30 at 23 00](https://user-images.githubusercontent.com/1032411/91669367-a8145700-eb14-11ea-9b14-7dd6220b7093.jpg)

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
I really just installed it, configured everything and I see this.
I can share the caddy / PHP config, if that helps

**Screenshots**
See above

### Output of the diagnostics  [REQUIRED]
<details>
<summary>Diagnostics</summary>

```
Diagnostics
-----------
Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.
Error: username empty or not set in database
Error: password empty or not set in database
Warning: Dropbox import not working. dropbox_key is empty.
Warning: Image optimizer enabled but cwebp not found!
Warning: Image optimizer enabled but gifsicle not found!
Warning: Image optimizer enabled but jpegoptim not found!
Warning: Image optimizer enabled but optipng not found!
Warning: Image optimizer enabled but pngquant not found!
Warning: Image optimizer enabled but svgo not found!

System Information
------------------
Lychee Version (git):            master (d08f2ee) - Data not in Cache
DB Version:                      4.0.6

composer install:                --no-dev
APP_ENV:                         production
APP_DEBUG:                       false

System:                          Linux
PHP Version:                     7.4
Max uploaded file size:          2M
Max post size:                   8M
MySQL Version:                   8.0.21-0ubuntu0.20.04.4

Imagick:                         1
Imagick Active:                  1
Imagick Version:                 1690
GD Version:                      2.3.0

Config Information
------------------
version:                         040006
check_for_updates:               0
sorting_Photos_col:              takestamp
sorting_Photos_order:            ASC
sorting_Albums_col:              max_takestamp
sorting_Albums_order:            ASC
imagick:                         1
skip_duplicates:                 0
small_max_width:                 0
small_max_height:                360
medium_max_width:                1920
medium_max_height:               1080
lang:                            en
layout:                          1
image_overlay:                   1
image_overlay_type:              desc
default_license:                 none
compression_quality:             90
full_photo:                      1
delete_imported:                 0
Mod_Frame:                       1
Mod_Frame_refresh:               30
thumb_2x:                        1
small_2x:                        1
medium_2x:                       1
landing_page_enable:             0
landing_owner:                   John Smith
landing_title:                   John Smith
landing_subtitle:                Cats, Dogs & Humans Photography
landing_facebook:                https://www.facebook.com/JohnSmith
landing_flickr:                  https://www.flickr.com/JohnSmith
landing_twitter:                 https://www.twitter.com/JohnSmith
landing_instagram:               https://instagram.com/JohnSmith
landing_youtube:                 https://www.youtube.com/JohnSmith
landing_background:              dist/cat.jpg
site_title:                      Lychee v4
site_copyright_enable:           1
site_copyright_begin:            2019
site_copyright_end:              2019
additional_footer_text:
display_social_in_gallery:       0
public_search:                   0
SL_enable:                       0
SL_for_admin:                    0
public_recent:                   0
recent_age:                      1
public_starred:                  0
downloadable:                    0
photos_wraparound:               1
map_display:                     0
zip64:                           1
map_display_public:              0
map_provider:                    Wikimedia
force_32bit_ids:                 0
map_include_subalbums:           0
update_check_every_days:         3
has_exiftool:                    0
share_button_visible:            0
import_via_symlink:              0
has_ffmpeg:                      0
location_decoding:               0
location_decoding_timeout:       30
location_show:                   1
location_show_public:            0
rss_enable:                      0
rss_recent_days:                 7
rss_max_items:                   100
prefer_available_xmp_metadata:   0
editor_enabled:                  1
lossless_optimization:           1
swipe_tolerance_x:               150
swipe_tolerance_y:               250
local_takestamp_video_formats:   .avi|.mov
```
</details>

### Browser and system
Firefox 80.0
macOS 10.15.6

**Comment by d7415** [comment]
My hunch is that your Caddy configuration isn't rewriting the URLs in a way that Lychee expects - I checked, and `Session::init` is definitely declared as `POST`.

The Caddy configuration might help (though I have limited experience with Caddy)

Aside: I like the collapsed Diagnostics :)

**Comment by ildyria** [comment]
> Aside: I like the collapsed Diagnostics :)

Agreed. :o

**Comment by apfelbox** [comment]
Hi and thank you for your responses!

It really looks like an application issue, as if I do the POST request with a HTML request, I see the default Symfony error page:

![2020-08-30 at 23 36](https://user-images.githubusercontent.com/1032411/91669997-b7e26a00-eb19-11ea-9f29-9390b350e2d9.jpg)

I also put a `echo $_SERVER["REQUEST_METHOD"];` at the top of the `index.php`, so the file gets the correct method:

![2020-08-30 at 23 55](https://user-images.githubusercontent.com/1032411/91670294-596abb00-eb1c-11ea-8e3b-41c9cafbf911.jpg)


Request URI is correct as well:

![2020-08-30 at 23 57](https://user-images.githubusercontent.com/1032411/91670314-8919c300-eb1c-11ea-9870-e63d27490115.jpg)

---

Here is my caddy config:

```
{
    experimental_http3
    email ...
}

(headers) {
    header {
        Referrer-Policy no-referrer-when-downgrade
        Strict-Transport-Security max-age=31536000
        X-Content-Type-Options nosniff
        X-XSS-Protection "1; mode=block"
        -X-Powered-By
        -Server
    }
}

example.org {
    import headers
    encode gzip zstd
    root * /var/www/photos/public
    file_server
    php_fastcgi 127.0.0.1:9100
}


www.example.org {
    redir https://example.org{uri}
}
```

I will try to debug this a bit further and see where it gets me.

> Aside: I like the collapsed Diagnostics :)

Haha thx, I see that from time to time in other issues and thought it might get a bit long otherwise.

**Comment by apfelbox** [comment]
I just saw that the request goes out to `/php/index.php` instead of just `/index.php`. ~~Maybe that's the error?~~ that looks correct.

**Comment by ildyria** [comment]
No, that is not an error.
See here: https://github.com/LycheeOrg/Lychee/blob/master/routes/web.php#L41

**Comment by apfelbox** [comment]
Okay, so I just dumped the route collection in

`Illuminate\Routing\CompiledRouteCollection:126`
![2020-08-31 at 00 10](https://user-images.githubusercontent.com/1032411/91670489-57a1f700-eb1e-11ea-8f8c-7f850e2cf57f.jpg)

and the route collection is empty??

![2020-08-31 at 00 10](https://user-images.githubusercontent.com/1032411/91670492-61c3f580-eb1e-11ea-924d-45648b28cdcb.jpg)

**Comment by apfelbox** [comment]
I think I found the issue. The base path in the request looks wrong:

![2020-08-31 at 00 13](https://user-images.githubusercontent.com/1032411/91670534-d26b1200-eb1e-11ea-86bf-68dc5f28f6ba.jpg)

Both `baseUrl` and `basePath` should be `/`.

**Comment by apfelbox** [comment]
So, one last update before 😴 :

I traced it through the whole app to actually point to a possible issue in Symfony itself (https://github.com/symfony/symfony/issues/37995). Let's wait and see what they say.

**Comment by Victor-Morel** [comment]
I have a similar issue on a fresh install on Debian 10 using PostgreSQL and Nginx, both with the 4.2.2 release and the master branch.
Has anyone found a workaround to make it work? 
It seems surprising to me to have such an unresolved issue with a pretty standard configuration.

**Comment by ildyria** [comment]
@Victor-Morel it seems that the issue is still live: https://github.com/symfony/symfony/issues/37995

That being said, I am quite surprised that you have the said issue with Nginx as quite a significant part of our users also are on Nginx without the issue.
I would suggest you have a deeper look at your Nginx configuration. This may help you: https://lycheeorg.github.io/docs/#nginx

**Comment by nagmat84** [comment]
> I traced it through the whole app to actually point to a possible issue in Symfony itself (https://github.com/symfony/symfony/issues/37995). Let's wait and see what they say.

The upstream bug report has been closed. The problem has been fixed and was (see upstream) not a bug in Symfony, but in Caddy. Newer releases of Caddy are fixed and the OP confirmed that.

So I am closing this issue, too.
