### ISSUE TITLE
PHP 7.4.3

### ISSUE THREAD

**Issue by effatee** [LycheeOrg/Lychee#711]
Hi,
Should Lychee be able to work with PHP7.4.3 ?
(So far my installation is failling in the sense the first start doesn't seem to be satisfactory, see screenshot)

Kind regards

![Capture d’écran 2020-09-02 à 15 54 33](https://user-images.githubusercontent.com/55504376/91992774-d2445f80-ed34-11ea-9e10-f0adc91776ad.png)

**Comment by d7415** [comment]
Yes, it should. For further support please open an issue in this repository, following the template provided.

**Comment by ildyria** [comment]
Yes. But the biggest problem here is that it seems that it's not finding the CSS. 

⁣Télécharger BlueMail pour Android ​

Le 2 sept. 2020 à 15:59, à 15:59, efftee <notifications@github.com> a écrit:

**Comment by effatee** [comment]
Corrected css issue somehow. 
Ran into new problem -> created issue (712) as requested with diagnostic details.
Thank you.
