### ISSUE TITLE
Failling First start

### ISSUE THREAD

**Issue by effatee** [LycheeOrg/Lychee#712]
### Detailed description of the problem [REQUIRED]
After installation following documentation, first start doesn't work. 
Getting a temporary error : Server error or API not found

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Install following steps in documentation (https://lycheeorg.github.io/docs/installation.html)
2. Already created db in mysql
3. Already filled .env file with db connection, host, database, password, and redis host passwd and port
4. Configured apache2 with https redirect and valid certificate, pointing to public/ folder
5. chowned uploads/ and dist/ to webserver user
6. chmoded uploads/ and dist/ to 775
7. ran a php artisan migrate
2. Go to lychee index page for first start

**Screenshots**
![Capture d’écran 2020-09-02 à 16 31 18](https://user-images.githubusercontent.com/55504376/91997015-eb9bda80-ed39-11ea-8618-2b81b671e340.png)

### Output of the diagnostics  [REQUIRED]
Diagnostics
-----------
Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.
Error: username empty or not set in database
Error: password empty or not set in database
Warning: Dropbox import not working. dropbox_key is empty.
Warning: Image optimizer enabled but cwebp not found!
Warning: Image optimizer enabled but gifsicle not found!
Warning: Image optimizer enabled but jpegoptim not found!
Warning: Image optimizer enabled but optipng not found!
Warning: Image optimizer enabled but pngquant not found!
Warning: Image optimizer enabled but svgo not found!

System Information
------------------
Lychee Version (git):            master (55d9dac) - Data not in Cache
DB Version:                      4.0.6

composer install:                --no-dev
APP_ENV:                         production
APP_DEBUG:                       false

System:                          Linux
PHP Version:                     7.4
Max uploaded file size:          2M
Max post size:                   8M
MySQL Version:                   10.3.22-MariaDB-1ubuntu1

Imagick:                         1
Imagick Active:                  1
Imagick Version:                 1690
GD Version:                      2.2.5

Config Information
------------------
version:                         040006
check_for_updates:               0
sorting_Photos_col:              takestamp
sorting_Photos_order:            ASC
sorting_Albums_col:              max_takestamp
sorting_Albums_order:            ASC
imagick:                         1
skip_duplicates:                 0
small_max_width:                 0
small_max_height:                360
medium_max_width:                1920
medium_max_height:               1080
lang:                            en
layout:                          1
image_overlay:                   1
image_overlay_type:              desc
default_license:                 none
compression_quality:             90
full_photo:                      1
delete_imported:                 0
Mod_Frame:                       1
Mod_Frame_refresh:               30
thumb_2x:                        1
small_2x:                        1
medium_2x:                       1
landing_page_enable:             0
landing_owner:                   John Smith
landing_title:                   John Smith
landing_subtitle:                Cats, Dogs & Humans Photography
landing_facebook:                https://www.facebook.com/JohnSmith
landing_flickr:                  https://www.flickr.com/JohnSmith
landing_twitter:                 https://www.twitter.com/JohnSmith
landing_instagram:               https://instagram.com/JohnSmith
landing_youtube:                 https://www.youtube.com/JohnSmith
landing_background:              dist/cat.jpg
site_title:                      Lychee v4
site_copyright_enable:           1
site_copyright_begin:            2019
site_copyright_end:              2019
additional_footer_text:
display_social_in_gallery:       0
public_search:                   0
SL_enable:                       0
SL_for_admin:                    0
public_recent:                   0
recent_age:                      1
public_starred:                  0
downloadable:                    0
photos_wraparound:               1
map_display:                     0
zip64:                           1
map_display_public:              0
map_provider:                    Wikimedia
force_32bit_ids:                 0
map_include_subalbums:           0
update_check_every_days:         3
has_exiftool:                    1
share_button_visible:            0
import_via_symlink:              0
has_ffmpeg:                      1
location_decoding:               0
location_decoding_timeout:       30
location_show:                   1
location_show_public:            0
rss_enable:                      0
rss_recent_days:                 7
rss_max_items:                   100
prefer_available_xmp_metadata:   0
editor_enabled:                  1
lossless_optimization:           1
swipe_tolerance_x:               150
swipe_tolerance_y:               250
local_takestamp_video_formats:   .avi|.mov

### Browser and system
Browser Firefox 80
System Ubuntu Server 20.04

**Comment by ildyria** [comment]
Thank you, can you apply this: https://lycheeorg.github.io/docs/faq.html#when-i-do-x-i-get-an-error-api-not-found-what-can-i-do
and tell us what is going on during the `php/index.php` call ? Yes, the file does not exists, it is normal, we take care of that: 
https://github.com/LycheeOrg/Lychee/blob/55d9dacc96215b00b92facd52efa0b7ff37b6eab/routes/web.php#L41

Did you set your `APP_URL` in your `.env` ?

**Comment by effatee** [comment]
Thank you @ildyria  !

This worked. Process was good. 
I did have a 404 and the pointed documentation had the correct answer.

Had to adjust directory options in the `apache2.conf`
After a `systemctl reload apache2` all was fine.
(Yes `APP_URL` was indeed previously set)

Funny how I already had these exact settings for the `www/` folder above `Lychee/` but still had to write a new section in the conf file for the Lychee folder. I would have thought these were recursive. But no. :) 

Thank you !
