### ISSUE TITLE
[Enhancement] Option to disable auto zoom and auto hide buttons

### ISSUE THREAD

**Issue by haertig** [LycheeOrg/Lychee#718]
When looking at individual photos within an album, I would prefer that it not do an "auto zoom" of the image like it currently does after a few seconds.  Give us an option to turn this off.  Or a way to set the timeout for the auto zoom (setting that to a very large number would effectively prevent Lychee from auto zooming).  I find that Lychee is constantly zooming and un-zooming images.  Someone walks across the floor, you touch the desk your computer is sitting on, you accidentally move the mouse - all these innocent things will trigger an un-zoom.  Which is then followed a few seconds later with an auto zoom.  I would prefer the image just to stay un-zoomed all the time.  This has the added benefit of allowing the control icons to be seen all the time.

The FAQ tells how to eliminate the zoom animation via CSS changes.  Thus the zoom becomes an instantaneous screen change rather than an animated screen change.  But the FAQ doesn't mention how to get rid of the zoom completely.

Somewhat related to this are the previous and forward icons that appear on the left and right sides of the screen.  They do not appear until you move the cursor over to the edge of the screen.  This can be confusing to new Lychee users, because you can't normally see these forward and back icons until after you move your mouse cursor over to the side of the screen.  Which implies that you have to know that those icons are there (but hidden) in the first place.  If you don't know they're there, why would you move your mouse pointer over to the side in the first place?  Just leave those icons in view all the time.

These changes might be easily accomplished by making the timings of these screen gyrations/movements settable in the database (I assume they are hard coded currently).  Then using Advanced Settings one could make these timings extremely long, so as to functionally eliminate this animated behavior.

I realize someone probably put in a lot of time coding these animations and screen movements.  However for many people, myself included, unrequested and unexpected automatic screen changes are a problem, not an enhancement. "Auto hide" is something that the user should always be allowed to disable.

**Comment by kamil4** [comment]
I'm looking into this. Your major wish can be accomplished using the following user.css:

```
#imageview.full #image {
    top: 60px;
    right: 30px;
    bottom: 30px;
    left: 30px;
    max-width: calc(100% - 60px);
    max-height: calc(100% - 90px);
}
```

**Comment by kamil4** [comment]
As to the previous/next buttons, try the following:
```
#imageview .arrow_wrapper a#next,
#imageview .arrow_wrapper a#previous {
    transform: translateX(0);
}
```
You'll probably also want:
```
#imageview .arrow_wrapper:hover a#next,
#imageview .arrow_wrapper:hover a#previous {
    opacity: 1;
}
```
Though the buttons may then permanently overlap an image. You can send the image to the front with this:
```
#imageview #image {
    z-index: 1;
}
```
Or maybe better adjust the margins of the image:
```
#imageview #image, 
#imageview.full #image  {
    left: 40px;
    right: 40px;
    max-width: calc(100% - 80px);
}
```
I hope this helps!

**Comment by haertig** [comment]
Wow!  Excellent response.  Unbelievably fast.  Thank you very much!

I implemented all your suggestions above, choosing the "adjust the margins" suggestion over the "send the image to the front" suggestion.  In my case, I don't think it matters much which solution I chose.  I don't have many (any?) super wide images so the buttons don't overlap in the first place.

The one remaining thing, is that the buttons at the top (back, star, share, info, trash, etc.) still auto-hide themselves rather than staying fixed.  Based on my personal preferences, keeping them fixed would be the final thing I'd want to tweak related to this request for enhancement.

So far I am very impressed with Lychee.  And I am even more impressed with the response I got here.  Amazing job, thanks for your hard work - it is much appreciated!

**Comment by kamil4** [comment]
> Wow! Excellent response. Unbelievably fast. Thank you very much!

We aim to please :smile:.

> I implemented all your suggestions above, choosing the "adjust the margins" suggestion over the "send the image to the front" suggestion. In my case, I don't think it matters much which solution I chose. I don't have many (any?) super wide images so the buttons don't overlap in the first place.

Even though most of my images are in the 4:3 ratio, I like to have two browser windows side-by-side so for me they usually overlap.

> The one remaining thing, is that the buttons at the top (back, star, share, info, trash, etc.) still auto-hide themselves rather than staying fixed. Based on my personal preferences, keeping them fixed would be the final thing I'd want to tweak related to this request for enhancement.

OK, try this:

```
.header--hidden {
    transform: translateY(0);
}
```

This tweak is a little more risky than the previous ones because the code of the front end in several places acts differently depending on whether the header is visible or not; with this tweak, we "lie" to it. So if you notice any strange behavior around that, please report back and we'll see what more we can do.

**Comment by haertig** [comment]
I just found one problem.  This was BEFORE adding your latest .header--hidden tweak.

I was viewing an individual photo in an album, then I went back to the album page (where each of the individual pictures is displayed), then I tried to go back to its parent page (the one where you choose which album you want to view).  It did not go back to that parent page, it said "Error: Server error or API not found".  It was stuck at this point, at least for going back to the "choose album" page (I did not try other operations at this time).  The GUI was not frozen ... I could click that back arrow and the error message would glide down from the top , then glide back up, and I could hit "back" again and the error message would repeat.  So the application was still running, it was just afraid to go back to the "choose album" page.

I closed the web browser window (not the browser itself, just the tab holding Lychee).  I opened a new tab with Lychee, was required to login again, and everything was working fine.  I could not reproduce the error.  If I can reproduce the error with further testing I will report back.  One thing that probably isn't related, but may be, is that when I experienced the error, my web browser had been sitting on an individual image view for quite some time (several hours).  During my attempts to reproduce the error just now, I have not yet had the opportunity to sit on an open image view for an extended period of time.

I will attempt to reproduce my error during the rest of today, before I add your newest tweak (the .header--hidden) one.  The last thing we want to do is introduce another variable into the equation.  I will attempt to reproduce the error for a while before moving on to other tweaks.

Thanks!

**Comment by kamil4** [comment]
You probably had a session timeout. See `SESSION_LIFETIME` in `.env`; I believe it defaults to 120 minutes, so you may want to bump it up. In principle though you should get a timeout message followed by a browser redirect to the front page so that you can log back in, rather than a server error.

Anyway, I can't imagine any CSS tweaks triggering that...

**Comment by haertig** [comment]
Ah, that makes sense.  It's entirely possible that an attempted "timeout message and browser redirect" could have gotten gobbled up by one of my add-ons: ScriptSafe, AdBlockPlus, Ghostery, etc.  I believe I have my personal domain (that is hosting Lychee) exempted, but because I just installed Lychee and haven't gotten everything 100% fully tested, it could very well be that I have some script/privacy thing not set exactly right.  I am using Chromium (not Chrome) browser on a Linux box BTW.  That's basically the parent of Chrome, but before Google gets ahold of it and adds all kinds of tracking/snooping to it.

OK, I'll move on and try the .header--hidden tweak soon!

**Comment by haertig** [comment]
OK, after initial test, that .header--hidden tweak works.  If I see any strange behavior, I will report it.

As of now, Lychee is tuned exactly the way I would like it.  I am still flabbergasted at the amazing level of support I received.  It is so fun to stumble into an application that is fantastic for your needs, and ends up having a phenomenal level of developer support as well.  These application gems are few and far between.  The only other one I can think of off the top of my head is Calibre (ebook management software).  Lychee is in good company.

Thanks again!

**Comment by kamil4** [comment]
FYI, if you feel like reproducing the error you saw, you can always set the session lifetime to `1` (minute) and let it sit idle for that long. I just did that but could not reproduce your issue.

For issues like timeouts, and if it seems like the front end and the server have somehow gotten out of sync, a reload of the tab in your web browser generally clears things up. Our error handling code can be imperfect and in such situations getting the "Server error" message is not unusual. It's rarely a serious issue though.

Enjoy your install!
