### ISSUE TITLE
Server error 500 after apt upgrade with Lychee 4.0.5 and Ubuntu 18.04

### ISSUE THREAD

**Issue by mniemela** [LycheeOrg/Lychee#720]
### Detailed description of the problem
I'm running Lychee 4.0.5 in a Ubuntu 18.04 VM. It worked fine, until I run "apt upgrade", after which it started showing Server Error 500.

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Run Lychee 4.0.5 in Ubuntu 18.04
2. Run "sudo apt upgrade"
3. Go to the Lychee page, it shows Server Error 500. Setting debug to true gives more detailed report.

**Screenshots**
*If applicable, add screenshots to help explain your problem.*
![image](https://user-images.githubusercontent.com/7679721/92721834-5cad4480-f36f-11ea-9d3c-d59585fcd861.png)

### Output of the diagnostics
    Diagnostics
    -----------
    Info: Latest version of PHP is 7.4
    Error: PHP mbstring extension not activated
    Error: PHP gd extension not activated
    Error: PHP zip extension not activated
    Error: mysql db driver selected and PHP mysqli extension not activated
    Error: mysql db driver selected and PHP pdo_mysql extension not activated
    Error: username not set in database
    Error: password not set in database
    Error: sorting_Photos not set in database
    Error: sorting_Albums not set in database
    Error: imagick not set in database
    Error: skip_duplicates not set in database
    Error: check_for_updates not set in database
    Error: version not set in database
    Error: Database is behind file versions. Please apply the migration.
    Error: could not find driver (SQL: select `key`, `value`, `type_range` from `configs`)
    Warning: Dropbox import not working. No property for dropbox_key.
    Warning: Pictures that are rotated lose their metadata! Please enable Imagick in settings to avoid that.

    System Information
    ------------------
    You must be logged to see this.

    Config Information
    ------------------
    You must be logged to see this.

**Comment by d7415** [comment]
```
Error: mysql db driver selected and PHP mysqli extension not activated
Error: mysql db driver selected and PHP pdo_mysql extension not activated
```

Something in the upgrade has disabled or removed your php plugins, including the mysql ones.

**Comment by mniemela** [comment]
PHP claims they are enabled, though.

foo@bar:~$ php -v
PHP 7.4.10 (cli) (built: Sep  9 2020 06:36:14) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.10, Copyright (c), by Zend Technologies
foo@bar:~$ php -m
[PHP Modules]
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
imagick
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tidy
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

**Comment by d7415** [comment]
Your php-cli is at 7.4 but Lychee is being run with 7.3 (hence the `Info: Latest version of PHP is 7.4` message). You may need to adjust your apache/nginx settings. Or a reboot might be sufficient.

**Comment by mniemela** [comment]
Looks like there was some PHP 7.2 remnant enabled in Apache, and disabling it fixed this. Thanks!
