### ISSUE TITLE
Unable to upload larger image (40 MB)

### ISSUE THREAD

**Issue by klausmcm** [LycheeOrg/Lychee#722]
I've been trying to upload a large image (40 MB and 23000 x 2000 pixels) and this screen has been up for at least half an hour now.

![image](https://user-images.githubusercontent.com/14914359/93158439-f6068e80-f6c0-11ea-95d1-b8a83a147a75.png)

I'm running Lychee using docker on my server (debian 10) and an image that's 5 MB (3000 x 2000 pixels) takes about 5 seconds to upload and show up in a gallery. I also use nginx as a reverse proxy and I set **client_max_body_size 200m;**.

Screenshot of traffic inspection
![image](https://user-images.githubusercontent.com/14914359/93158589-40880b00-f6c1-11ea-842c-bb7c2f98a523.png)

Running `top` on my server does not indicate that any image processing is being done and the nginx logs also are not showing any erros.

I'd appreciate help with this issue. Thanks,

**Comment by kamil4** [comment]
If things hung like that, you should just hit Reload in your browser. It won't magically fix the underlying problem but you will at least have a working session again.

I'm guessing an issue with the image processing engine (either Image Magick or GD), or perhaps the server is running out of memory. Do you see any relevant errors under _Show Logs_? Can you provide a URL to the image in question so that we can try to reproduce it?

**Comment by klausmcm** [comment]
Thanks, I have been getting around the stuck screen by reloading.

I just checked the logs. This is what I see (and nothing else after that line) when I upload the larger image(s)

```
2020-09-15 05:09:32 -- notice  -- App\Metadata\GitHubFunctions::__construct -- 49 -- Undefined offset: 2
```

I also tried uploading an image (.png) of similar dimensions (23000 x 3000 px, all white) that I created to test. This is the result

![image](https://user-images.githubusercontent.com/14914359/93168428-ae3f3180-f6d7-11ea-8cd7-4c8a73061201.png)

And in the logs

```
2020-09-15 05:14:11 -- error   -- App\Image\ImagickHandler::crop -- 157 -- Failed to read the file
```

**Comment by ildyria** [comment]
> 2020-09-15 05:09:32 -- notice  -- App\Metadata\GitHubFunctions::__construct -- 49 -- Undefined offset: 2

That is more worry some. :thinking:

**Comment by chrissearle** [comment]
Hmm

Just had the same thing.

102 files. 32 OK - 70 stuck in processing.

Have tried re-uploading some of the ones that failed - same issue.

All of them get a 0byte 302 FOUND response.

So - I checked the sizes.

All images 20Mb or less are OK.

All images over 20Mb are failing.

Nginx and php are set to 100Mb for me.

I also get the App\Metadata\GitHubFunctions::__construct -- 49 -- Undefined offset: 2 messages in the logs.

This is running 4.0.6 docker image.

**Comment by chrissearle** [comment]
Comment to my post - in the nginx.conf I have:

```
location ~ [^/]\.php(/|$) {
            fastcgi_split_path_info ^(.+?\.php)(/.*)$;

            try_files $uri $document_root$fastcgi_script_name =404;

            # Mitigate https://httpoxy.org/ vulnerabilities
            fastcgi_param HTTP_PROXY "";

            fastcgi_pass unix:/run/php/php7.3-fpm.sock;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PHP_VALUE "post_max_size=100M
                max_execution_time=200
                upload_max_filesize=20M
                memory_limit=256M";
            fastcgi_param PATH /usr/local/bin:/usr/bin:/bin;
            include fastcgi_params;
        }
```

I will have to do a custom nginx conf mount to set the upload_max_filesize there too

**Comment by ildyria** [comment]
>                 upload_max_filesize=20M

This is pretty self explanatory

**Comment by chrissearle** [comment]
> > ```
> >             upload_max_filesize=20M
> > ```
> 
> This is pretty self explanatory

Yep - just spotted the "Advanced configuration" section on https://github.com/LycheeOrg/Lychee-Docker

**Comment by klausmcm** [comment]
Thanks, I also finally found that the relevant config is in **/etc/nginx/nginx/conf**.

This is what is in my config now

```
upload_max_filesize=200M
memory_limit=512M
```

The **Uploading** window is no longer stuck on **Processing** and now shows this error when I upload an image with larger resolution (I also see this when I upload a test image that's 23000 x 3000 px and all white and only 200 Kb in size)

![image](https://user-images.githubusercontent.com/14914359/93235305-35b98e80-f732-11ea-842a-d4587f040c34.png)

And in the logs

```
    2020-09-15 15:59:03 -- error   -- App\Image\ImagickHandler::crop -- 157 -- Failed to read the file
    2020-09-15 15:59:03 -- notice  -- App\ModelFunctions\PhotoFunctions::createThumb -- 597 -- Photo URL is 58b8e5facd1dba560ed2b3167c41df1c.png
```

Any ideas of what I could do to fix this? Any other debugging I can do?

@chrissearle Are you now able to upload the images that are larger than 20 Mb?

**Comment by kamil4** [comment]
I just created an image of the same dimensions in gimp and I was able to upload it successfully.

I think you are running into some limit here due to the massive size of the image in question (gimp warned me that it needed >600 MB to store it in memory, though, as you say, it was only around 200 KB on disk).

Do you have any resource limits set for ImageMagick? E.g., if you are using a system-installed one, check the `/etc/ImageMagick-7/policy.xml` file.

FYI, I was using ImageMagick 7.0.10.23 and pecl-imagick 3.4.4, with no limits set. My PHP `memory_limit` is 128 MB. When I turned off imagick support in Lychee in the advanced config (going back to PHP built-in GD), it started failing, with errors in the log of my http daemon about hitting the PHP memory size limit. When I increased that to 1024 MB, I instead got an error from `exif_read_data` in Lychee: `File not supported`.

So yeah, such massive images can trigger all sorts of issues in PHP at the moment although, with some luck, it is possible to get them to work with ImageMagick at least.

**Comment by klausmcm** [comment]
@kamil4 Thanks for trying. I also used gimp and saw the same warning.

I see that under **Settings/Image Processing**, `imagick` is set to `1`. I don't have imagick installed on the server host but I think the docker image has imagick installed? Doing an `apt list --installed` in the docker image shows me **imagemagick-6-common** but I don't see an *ImageMagick* folder under `/etc`. Is there somewhere in the docker image that I can tweak the limits? I can definitely allocate 1 GB of memory for this purpose.

**Comment by kamil4** [comment]
Sorry, I've never used that docker image. Somebody else will have to chime in. @d7415?

**Comment by d7415** [comment]
> Is there somewhere in the docker image that I can tweak the limits?

`/etc/ImageMagick-6/policy.xml`

**Comment by klausmcm** [comment]
> > Is there somewhere in the docker image that I can tweak the limits?
> 
> `/etc/ImageMagick-6/policy.xml`

My bad. I didn't see the folders with capitalized letters as being listed first when I did `ls`.

**Comment by d7415** [comment]
> My bad. I didn't see the folders with capitalized letters as being listed first when I did `ls`.

If it makes you feel better, I had to go back a second time too.

**Comment by klausmcm** [comment]
> > My bad. I didn't see the folders with capitalized letters as being listed first when I did `ls`.
> 
> If it makes you feel better, I had to go back a second time too.

A little ;p

**Comment by klausmcm** [comment]
I tweaked `/etc/ImageMagick-6/policy.xml` a bit

![image](https://user-images.githubusercontent.com/14914359/93251698-5e00b780-f749-11ea-9577-2c72b72bd8b9.png)

I increased **memory** to **1024MiB** and set **width** and **height** to **50KP**. I'm assuming **KP** means kilopixel so I should now be able to upload images that are up to 50KP x 50 KP.

Thank you everyone for the assistance.

**Comment by d7415** [comment]
This would probably be useful in the docs...

**Comment by klausmcm** [comment]
I'd be happy to contribute. Is this something I can add and then have one of you maintainers review?

**Comment by d7415** [comment]
> I'd be happy to contribute. Is this something I can add and then have one of you maintainers review?

That would be really useful, thanks. The docs (and website) are built from [this](https://github.com/LycheeOrg/LycheeOrg.github.io) repo. The source for the documentation specifically is [here](https://github.com/LycheeOrg/LycheeOrg.github.io/tree/master/docs/md) and can be edited in markdown. The project can then be built from the root using `make all` (possibly just `make`....).

I guess it would be a FAQ, but there may be a more suitable place. If you feel like adding something like the above to "Contributing" that might be useful too :)

Once done, just submit a PR to that repo and we'll have a look. If you have trouble building feel free to just PR the source and we can deal with that.

**Comment by klausmcm** [comment]
I'll take a look. Likely FAQ/Problems is where I will add content since there is already an entry discussing large uploads.
