### ISSUE TITLE
Album title length limit

### ISSUE THREAD

**Issue by klausmcm** [LycheeOrg/Lychee#723]
When I create a new album, the length of the title is limited to 50 characters. Is there a setting to change that to allow for longer titles? I couldn't find one in the documentation.

Thanks,

**Comment by kamil4** [comment]
Yeah, I agree that 50 is kind-of short...

Oddly enough, the limit is actually 100 on the server side. It appears that the front end enforces a smaller limit though?! Should be trivial to fix...

**Comment by klausmcm** [comment]
That would be much appreciated.

Is a constraint for the length required?

**Comment by d7415** [comment]
> Is a constraint for the length required?

Yes, for defining the database field.

**Comment by ildyria** [comment]
Not to be annoying but if you have that long titles you should seriously consider using the description field...

**Comment by klausmcm** [comment]
Fair suggestion. I'll try to work around using sub-albums as well. 100 characters limit might be also ok that @kamil4 committed. Thank you.
