### ISSUE TITLE
[Enhancement] Login on direct album url if not logged in and album needs it

### ISSUE THREAD

**Issue by chrissearle** [LycheeOrg/Lychee#725]
It would be nice if we could have something similar to the password prompt that pops up when you visit a password protected album URL directly for when you visit an album URL and that album requires you to be logged in as a user to see it - a pop-over login or a redirect to login with return url to send you back to the album after login.

**Comment by ildyria** [comment]
Isn't this done now ? :)

**Comment by kamil4** [comment]
I don't think so (I just tried). The request, as I understand it, concerns private albums (with a known URL). The only way we support login is from the albums view. If you try a private album's URL, you get redirected to the public albums view and that's it.

**Comment by ildyria** [comment]
Ha right I thought this was the sharing with password thing...

**Comment by ildyria** [comment]
This is now done. Just tested.
