### ISSUE TITLE
Force HTTPS redirect.

### ISSUE THREAD

**Issue by Anandir** [LycheeOrg/Lychee#726]
Good afternoon,
first of all, thanks for your amazing and hard work on Lychee!
I've tried, on a shared host, to write a rewrite rule to force Lychee to redirect to the https site.
I've made something like:

`RewriteEngine On`
`RewriteCond %{SERVER_PORT} 80`
`RewriteRule ^(.*)$ https://<url>/$1 [R]`
`RewriteRule ^$ /public [L]`

But if I open the `http` site, it moves directly to `http://<url>/public` and not to `https://<url>/public` .

I've tried something like:

`RewriteEngine On`
`RewriteCond %{SERVER_PORT} 80`
`RewriteRule ^(.*)$ https://<url>/$1 [R,L]`
`RewriteRule ^$ /public [L]`

And the sites redirect to `https://<url>` correctly (not to /public because of the L flag before, I know).
I've also tried a chained rule (putting [R,C] to the https rule and [L,C] to the public rule) with no luck.

What am I doing wrong?
Is it possible, in the first place, to do that?

Of course if I point the browser to `https://<url>/public` everything works like charm.

Thanks a lot in advance :-)!

Best regards.

**Comment by ildyria** [comment]
https://stackoverflow.com/a/27029144/3981163
