### ISSUE TITLE
PHP extensions list

### ISSUE THREAD

**Issue by kamil4** [LycheeOrg/Lychee#728]
The list of PHP extensions in the documentation needs to be updated:
* zlib is not listed (zip is possibly obsolete?)
* Ffmpeg PHP Extension is installed via composer so no point in listing it
* BCMath -- what needs it? I don't have that extension...

**Comment by d7415** [comment]
>     * BCMath -- what needs it? I don't have that extension...

`composer.lock` seems to have it as "suggested". It looks like it was added in #457.

**Comment by ildyria** [comment]
BCMath: https://laravel.com/docs/8.x/#server-requirements

**Comment by ildyria** [comment]
BCMath is now needed to be able to use U2F. I also added it in the composer.json requirement.
