### ISSUE TITLE
Moving albums gives a confirmation prompt with titles "Untitled"

### ISSUE THREAD

**Issue by chrissearle** [LycheeOrg/Lychee#730]
### Detailed description of the problem [REQUIRED]

When I move an album into another album I get the confirmation prompt:

Are you sure you want to move the album 'Untitled' into the album 'Untitled' ?

It all works - its just the titles on this dialog

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Create two albums at the top level
2. In one of them choose move
3. Select the other album as destination
4. Confirmation dialog appears

**Screenshots**

<img width="260" alt="Lychee v4 - foo2 2020-09-18 10-17-18" src="https://user-images.githubusercontent.com/49564/93574127-52570000-f998-11ea-8fca-45148073ac4a.png">

### Output of the diagnostics  [REQUIRED]

    Diagnostics
    -------
    Info: Latest version of PHP is 7.4
    Warning: Dropbox import not working. dropbox_key is empty.

    System Information
    --------------
    Lychee Version (git):       No git data found.
    DB Version:                 4.0.6
    
    composer install:           --no-dev
    APP_ENV:                    production
    APP_DEBUG:                  false
    
    System:                     Linux
    PHP Version:                7.3
    PostgreSQL Version:         PostgreSQL 12.4 (Debian 12.4-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
    
    Imagick:                    1
    Imagick Active:             1
    Imagick Version:            1690
    GD Version:                 2.2.5

### Browser and system

Seen the same on both chrome and firefox on both mac and linux.

**Comment by ildyria** [comment]
Is it still the case on Master ? :thinking:

**Comment by ildyria** [comment]
Confirmed to be fixed on master.
