### ISSUE TITLE
Zip album downloads are all corrupt

### ISSUE THREAD

**Issue by gdureuil** [LycheeOrg/Lychee#731]
Hello. I have a problem with Lychee. Every zip created when downloading an album is corrupt. Cant open them with windows explorer or 7zip. Tried downloading with Firefox 80 or Edge 85 (chromium based) and I have the same result. The same applies if I select only two photos and right click to download them.

1. Go in an album.
2. Click on download album.
3. Try to open zip, it's corrupt. 7zip says "archive.zip can't be opened as an archive".

    Diagnostics
    -------
    Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.
    Warning: Dropbox import not working. dropbox_key is empty.
    Warning: lossless_optimization set to 1 but cwebp not found!
    Warning: lossless_optimization set to 1 but svgo not found!

    System Information
    --------------
    Lychee Version (git):            master (b684ee0) - Up to date (21 hours ago).
    DB Version:                      4.0.6
    
    composer install:                --no-dev
    APP_ENV:                         local
    APP_DEBUG:                       false
    
    System:                          Linux
    PHP Version:                     7.4
    Max uploaded file size:          100M
    Max post size:                   100M
    MySQL Version:                   10.3.23-MariaDB-0+deb10u1-log
    
    Imagick:                         1
    Imagick Active:                  1
    Imagick Version:                 1690
    GD Version:                      2.2.5

   Config Information
    --------------
    version:                         040006
    check_for_updates:               0
    sorting_Photos_col:              title
    sorting_Photos_order:            ASC
    sorting_Albums_col:              title
    sorting_Albums_order:            ASC
    imagick:                         1
    skip_duplicates:                 1
    small_max_width:                 0
    small_max_height:                360
    medium_max_width:                1920
    medium_max_height:               1080
    lang:                            en
    layout:                          0
    image_overlay:                   0
    image_overlay_type:              desc
    default_license:                 none
    compression_quality:             90
    full_photo:                      1
    delete_imported:                 0
    Mod_Frame:                       1
    Mod_Frame_refresh:               30
    thumb_2x:                        1
    small_2x:                        1
    medium_2x:                       1
    landing_page_enable:             0
    landing_owner:                   
    landing_title:                   
    landing_subtitle:                
    landing_facebook:                
    landing_flickr:                  
    landing_twitter:                 
    landing_instagram:               
    landing_youtube:                 
    landing_background:              
    site_title:                      Lychee
    site_copyright_enable:           0
    site_copyright_begin:            2010
    site_copyright_end:              2020
    additional_footer_text:          
    display_social_in_gallery:       0
    public_search:                   0
    SL_enable:                       0
    SL_for_admin:                    0
    public_recent:                   0
    recent_age:                      1
    public_starred:                  0
    downloadable:                    0
    photos_wraparound:               1
    map_display:                     0
    zip64:                           1
    map_display_public:              0
    map_provider:                    Wikimedia
    force_32bit_ids:                 0
    map_include_subalbums:           0
    update_check_every_days:         3
    has_exiftool:                    0
    share_button_visible:            0
    import_via_symlink:              0
    has_ffmpeg:                      1
    location_decoding:               0
    location_decoding_timeout:       30
    location_show:                   0
    location_show_public:            0
    rss_enable:                      0
    rss_recent_days:                 7
    rss_max_items:                   100
    prefer_available_xmp_metadata:   0
    editor_enabled:                  1
    lossless_optimization:           1
    swipe_tolerance_x:               150
    swipe_tolerance_y:               250
    local_takestamp_video_formats:   .avi|.mov

**Comment by gdureuil** [comment]
Here is a little more information.

Can't open zip with Windows Explorer (Windows 10 version 2004 x64)
Can't open zip with 7zip 19.00 x64
I can open the zip with no error with Winrar 5.91 x64

**Comment by kamil4** [comment]
Confirmed; it's a new regression. It worked as of 9c65f67 so I'm guessing the Laravel upgrade broke it somehow. There's an extra newline (?) at the beginning of the file that `unzip` under Linux ignores (with a warning) but `7z` indeed fails.

**Comment by ildyria** [comment]
https://stackoverflow.com/questions/61781737/laravel-response-download-broke-my-zip-file hummmm

**Comment by ildyria** [comment]
:sunglasses:

**Comment by gdureuil** [comment]
Just updated and can confirm it works now. Thanks for all your work on Lychee !
