### ISSUE TITLE
Don't work album's thumbnails

### ISSUE THREAD

**Issue by Dernogard** [LycheeOrg/Lychee#732]
### Detailed description of the problem [REQUIRED]
I created few albums and uploaded some files to. These files has "webp" extensions and they work fine. But don't work album's thumbnails. I think it may be because unsupported extension so please add it in future.
`    2020-09-24 18:33:43 -- error   -- App\Image\GdHandler::createImage -- 277 -- Type of photo "18" is not supported
    2020-09-24 18:33:43 -- notice  -- App\ModelFunctions\PhotoFunctions::createThumb -- 597 -- Photo URL is 9877752e48273e7642dddde2dc5d483e.webp`

Then I tried to upload jpg and png files for thumbnails purpose but they don't upload at all:
` 2020-09-24 18:43:21 -- notice  -- App\ModelFunctions\PhotoFunctions::createThumb -- 597 -- Photo URL is 3e6a7c93785dd351feb0dbb4c467f822.png
    2020-09-24 18:43:21 -- notice  -- App\Configs::hasImagick -- 240 -- hasImagick : false
    2020-09-24 18:43:21 -- notice  -- App\Configs::hasImagick -- 240 -- hasImagick : false`

> Server returned an unknown response. Please take a look at the console of your browser for further details

`Content Security Policy: Параметры страницы заблокировали загрузку ресурса inline («script-src»). Source: (function(){var e={exports:{}};e.exports=(e=>{var t={};function n(o){if(t[o])return t[o].exports;var a=t[o]={i:o,l:!1,exports:{}};return e[o].call(a.exports,a,a.exports,n),a.l=!0,a.exports}return n.m=e,n.c=t,n.d=(e,t,o)=>{n.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:o})},n.r=e=>{"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},n.t=(e,t)=>{if(1&t&&(e=n(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var o=Object.create(null);if(n.r(o),Object.defineProperty(o,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var a in e)n.d(o,a,(t=>e[t]).bind(null,a));return o},n.n=e=>{var t=e&&e.__esModule?()=>e.default:()=>e;return n.d(t,"a",t),t},n.o=(e,t)=>Object.prototype.hasOwnProperty.call(e,t),n.p="",n(n.s=15)})([function(e,t,n){"use strict"…`

Then I wanted to upload with ftp and will dissapointed that this CMS storaging all files in one folder so it's impossible. But anyway I saw these png files in the server !  I mean I can see files with png extension ( in the /uploads/big ) that shown me error when I tried to upload them.

**Link to the site with problem**
http://example.com/public/

### Output of the diagnostics  [REQUIRED]
    Warning: Dropbox import not working. dropbox_key is empty.
    Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.
    Warning: Pictures that are rotated lose their metadata! Please install Imagick to avoid that.

**Comment by d7415** [comment]
We need the full diagnostics. I suspect you're not using imagick and that gd doesn't support webp.

**Comment by ildyria** [comment]
We do appreciate that you give us a link to your gallery so we can have a look for ourselves. However, **DO NOT USE public in such way** make sure that there is no access to the under laying layer and that http://example.com/.env in your case is not exposed. You do not want your database (`ksdzvkte_mlp`) password and usernames to be publicly accessible.** 

I edited your issue to preserve your privacy and deleted the info from the history for your own security.

**Comment by kamil4** [comment]
Our handling of `.webp` files is certainly inconsistent. Looking inside `app/ModelFunctions/PhotoFunctions.php`, `.webp` is included in `$validExtensions` but not in `$validTypes`. No wonder it doesn't work...

**Comment by Dernogard** [comment]
> We need the full diagnostics. I suspect you're not using imagick and that gd doesn't support webp.

`


    Diagnostics
    -------
    Warning: Dropbox import not working. dropbox_key is empty.
    Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.
    Warning: Pictures that are rotated lose their metadata! Please install Imagick to avoid that.




    System Information
    --------------
    Lychee Version (release):   4.0.6
    DB Version:                 4.0.6
    
    composer install:           --no-dev
    APP_ENV:                    production
    APP_DEBUG:                  false
    
    System:                     Linux
    PHP Version:                7.4
    MySQL Version:              5.7.31-cll-lve
    
    Imagick:                    -
    Imagick Active:             1
    Imagick Version:            -
    GD Version:                 2.2.5




    Config Information
    --------------
    version:                    040006
    check_for_updates:          0
    sorting_Photos_col:         takestamp
    sorting_Photos_order:       ASC
    sorting_Albums_col:         max_takestamp
    sorting_Albums_order:       ASC
    imagick:                    1
    skip_duplicates:            0
    small_max_width:            0
    small_max_height:           360
    medium_max_width:           1920
    medium_max_height:          1080
    lang:                       ru
    layout:                     1
    image_overlay:              1
    image_overlay_type:         desc
    default_license:            none
    compression_quality:        90
    full_photo:                 1
    delete_imported:            0
    Mod_Frame:                  1
    Mod_Frame_refresh:          30
    thumb_2x:                   1
    small_2x:                   1
    medium_2x:                  1
    landing_page_enable:        0
    landing_owner:              John Smith
    landing_title:              John Smith
    landing_subtitle:           Cats, Dogs & Humans Photography
    landing_facebook:           https://www.facebook.com/JohnSmith
    landing_flickr:             https://www.flickr.com/JohnSmith
    landing_twitter:            https://www.twitter.com/JohnSmith
    landing_instagram:          https://instagram.com/JohnSmith
    landing_youtube:            https://www.youtube.com/JohnSmith
    landing_background:         dist/cat.jpg
    site_title:                 Lychee v4
    site_copyright_enable:      1
    site_copyright_begin:       2019
    site_copyright_end:         2019
    additional_footer_text:     
    display_social_in_gallery:  0
    public_search:              0
    SL_enable:                  0
    SL_for_admin:               0
    public_recent:              0
    recent_age:                 1
    public_starred:             0
    downloadable:               0
    photos_wraparound:          1
    map_display:                0
    zip64:                      1
    map_display_public:         0
    map_provider:               Wikimedia
    force_32bit_ids:            0
    map_include_subalbums:      0
    update_check_every_days:    3
    has_exiftool:               0
    share_button_visible:       0
    import_via_symlink:         0
    has_ffmpeg:                 0
    location_decoding:          0
    location_decoding_timeout:  30
    location_show:              1
    location_show_public:       0
    rss_enable:                 0
    rss_recent_days:            7
    rss_max_items:              100
    prefer_available_xmp_metadata: 0`

**Comment by Dernogard** [comment]
> Our handling of `.webp` files is certainly inconsistent. Looking inside `app/ModelFunctions/PhotoFunctions.php`, `.webp` is included in `$validExtensions` but not in `$validTypes`. No wonder it doesn't work...

Yeah, I wrote that I'm understand that in my first message. Anyway images with "webp" extensions are work fine just don't work thumbnails. So I speak about png thumbnails. I could use png-files for albums with webp-files but png wasn't uploading.

**Comment by kamil4** [comment]
Sorry for the delay in getting back to you. I looked at your diagnostics and it appears that your php installation is missing the `imagick` extension, but in Lychee settings you have `imagick` set to `1` so it tries to use it and fails. That is why `png` and `jpg` don't work for you.

Please either install the imagick extension or set the Lychee `imagick` config to `0`.

I will now look into our `webp` support...

**Comment by ildyria** [comment]
Can we close that one ?

**Comment by kamil4** [comment]
I would close it...
