### ISSUE TITLE
Problem with Image Upload when importing from Server

### ISSUE THREAD

**Issue by rainingmirrors** [LycheeOrg/Lychee#733]
### Detailed description of the problem [REQUIRED]
I upload images via ftp to the import folder, create a new album and start importing the images, checking the "delete images on import" box. Since my php max_execution_time is limited to 180 sec by my hosting provider, on nearly every album the import procedure is cut short and delivers the standard error 'failed'. With every resume of the import procedure, the last image of the current import is lost and needs to be re-uploaded by hand.

For example.

Last correctly imported image (and shown in the album) is
10.jpg
then 
11.jpg goes missing
and
12.jpg is the next one where the import resumes.

### Output of the diagnostics  [REQUIRED]
*(Settings => Diagnostics or https://example.com/Diagnostics or `php artisan lychee:diagnostics`)*

    Diagnostics
    -----------
    Info: Latest version of PHP is 7.4
    Warning: Dropbox import not working. dropbox_key is empty.
    Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.

    System Information
    ------------------
    Lychee Version (release):   4.0.6
    DB Version:                 4.0.6
    
    composer install:           --no-dev
    APP_ENV:                    production
    APP_DEBUG:                  false
    
    System:                     Linux
    PHP Version:                7.3
    MySQL Version:              5.7.29-32-log
    
    Imagick:                    1
    Imagick Active:             1
    Imagick Version:            1687
    GD Version:                 bundled (2.1.0 compatible)

    Config Information
    ------------------
    version:                    040006
    check_for_updates:          1
    sorting_Photos_col:         title
    sorting_Photos_order:       ASC
    sorting_Albums_col:         title
    sorting_Albums_order:       ASC
    imagick:                    1
    skip_duplicates:            0
    small_max_width:            0
    small_max_height:           360
    medium_max_width:           1920
    medium_max_height:          1080
    lang:                       de
    layout:                     1
    image_overlay:              1
    image_overlay_type:         desc
    default_license:            reserved
    compression_quality:        90
    full_photo:                 1
    delete_imported:            0
    Mod_Frame:                  1
    Mod_Frame_refresh:          30
    thumb_2x:                   1
    small_2x:                   1
    medium_2x:                  1
    landing_page_enable:        1
    landing_owner:              Martin Skopal
    landing_title:              Martin Skopal | wachau.photo | Galerie
    landing_subtitle:           Bilder, die Geschichten erzählen
    landing_facebook:           https://www.facebook.com/wachauphoto
    landing_flickr:             
    landing_twitter:            https://www.twitter.com/wachauphoto
    landing_instagram:          https://instagram.com/wachauphoto
    landing_youtube:            
    landing_background:         uploads/big/e1302789efb59827b4822fcf998746e5.jpg
    site_title:                 Martin Skopal | wachau.photo | Galerie
    site_copyright_enable:      1
    site_copyright_begin:       2001
    site_copyright_end:         2020
    additional_footer_text:     
    display_social_in_gallery:  1
    public_search:              0
    SL_enable:                  0
    SL_for_admin:               0
    public_recent:              0
    recent_age:                 1
    public_starred:             0
    downloadable:               0
    photos_wraparound:          1
    map_display:                0
    zip64:                      1
    map_display_public:         0
    map_provider:               Wikimedia
    force_32bit_ids:            0
    map_include_subalbums:      0
    update_check_every_days:    3
    has_exiftool:               0
    share_button_visible:       0
    import_via_symlink:         0
    has_ffmpeg:                 0
    location_decoding:          0
    location_decoding_timeout:  30
    location_show:              1
    location_show_public:       0
    rss_enable:                 0
    rss_recent_days:            7
    rss_max_items:              100
    prefer_available_xmp_metadata: 0
    editor_enabled:             1

### Browser and system

Safari, Mac OS X 10.14.6

**Comment by kamil4** [comment]
I wouldn't think that it's due to `max_execution_time` as we reset the limit for every new photo being imported using `set_time_limit`. I'm guessing your provider set some timeout external to php in their http server.

Anyway, back to your problem. I can see how this could happen, since we delete the image source early in the import process, so if that import fails... We should try to move that delete operation later. In the meantime, I recommend that you don't use the delete option and instead rely on the `skip_duplicates` config.
