### ISSUE TITLE
Image rotation is fundamentally broken

### ISSUE THREAD

**Issue by kamil4** [LycheeOrg/Lychee#741]
I believe the interactive image rotation feature as currently implemented is fundamentally broken.

The underlying problem is that the server modifies the content of the images but does not change their URLs in the process. Since the original images are likely to be already cached by the client, inconsistencies are pretty much guaranteed.

The front end tries to work around these issues by attaching a random query to the image URL to force a reload. But it does so only for the image currently being displayed (we are in the photo view at the time) and for the parent album, and not fully correctly at that (HiDPI is not handled properly).

If the image being modified happens to be the album thumb, that thumb will not change. Worse, if the user browses through the images and albums back and forth, the random query will eventually get dropped from the image URL and we are back to square one.

I think the only way to make it work reliably is for the server to rename the image files while rotating them (if symlinking is enabled, we can get away with simply generating new symlinks though), and for the front end to force a full reload of the albums tree, as we already do for operations such as image addition or deletion.

There is also another minor bug in the implementation in that it doesn't correctly handle missing intermediate image sizes (those fields should be empty in the DB but after the rotation they show `x` I believe).

**Comment by d7415** [comment]
I think the title is a little extreme, but we are browser based, so I suppose working around the cache is our problem.

Renaming seems a little heavy handed, but I guess we're already processing here. And the only alternative I can think of isn't much better (and would add work at the wrong times).

One down side is that any hotlinks will break - we might need to make that clear to the user. Or I suppose we could link the old name to the new name, but that sounds excessive.

**Comment by kamil4** [comment]
What's the alternative you were thinking of? Preventing the images from being cached in the first place? Or is there some way to purge a URL from the cache using JS (I think I looked for it at one point and failed)?

We essentially go out of our way to break hot linking already -- isn't that the whole point behind the symlink feature? I don't think that the photo id would need to change as you rotate so linking that way should be fine?

And yeah, the title might be harsh but I still think that it accurately reflects the current state
of this feature. I wasn't around when it was merged so I don't know how much effort was involved. Looking at the code though, I can certainly see and even appreciate @tmp-hallenser's struggle to work around the cache, and then even to modify `album.json`... It's a gallant effort but also one that was, fundamentally, bound to fail.

And it's frustrating because the only solutions I can think of are extremely crude. Renaming is crude (the old, stale image will remain in the cache) and forcing a reload of `albums.json` is known to be a performance problem for users with many albums. But we don't have anything better right now... Perhaps @ildyria is right that the front end needs a rewrite...

**Comment by d7415** [comment]
I feel there *should* be a way to cache-bust in JS, but I don't know of one. My idea was to store a query string in the DB, so that it's static per image, but can be changed trivially. Then apply that to every image.

The symlink feature basically breaks hotlinking, but is optional. Someone's bound to show up complaining that they rotated their image and now the link they posted to some forum/website is broken.

**Comment by d7415** [comment]
> The symlink feature basically breaks hotlinking, but is optional. Someone's bound to show up complaining that they rotated their image and now the link they posted to some forum/website is broken.

Just to add I think this is fine, but we should make it as clear as possible before rotation as there'll be no going back.

**Comment by kamil4** [comment]
Now that I think about it, cache busting wouldn't work anyway since it would affect only the current session, not anybody else who has viewed that album earlier and has the content cached...

**Comment by kgnfth** [comment]
i rotared an image and now the image wont load 😥

**Comment by kamil4** [comment]
The thumbnail in the album view or the individual photo view?

Perhaps it could be due to the issue I noted in the last paragraph of my first post. If so, that should be, in principle, easily fixable. Can you check if you have any of those erroneous `x` entries in the database? You can find them with the following SQL query:

```
select id from photos where medium = 'x' or 'medium2x' = 'x' or small = 'x' or small2x = 'x';
```

**Comment by kgnfth** [comment]
> The thumbnail in the album view or the individual photo view?
> 
> Perhaps it could be due to the issue I noted in the last paragraph of my first post. If so, that should be, in principle, easily fixable. Can you check if you have any of those erroneous `x` entries in the database? You can find them with the following SQL query:
> 
> ```
> select id from photos where medium = 'x' or 'medium2x' = 'x' or small = 'x' or small2x = 'x';
> ```

its from the individual photo view
pls see the this video https://streamable.com/1rm4mu

**Comment by kamil4** [comment]
OK, let's fix your database for now:

```
update photos set small = '' where small = 'x';
update photos set small2x = '' where small2x = 'x';
update photos set medium = '' where medium = 'x';
update photos set medium2x = '' where medium2x = 'x';
```

See if that fixes that image for you. Obviously, we'll also need to fix Lychee so that it doesn't corrupt the database like that in the future when performing rotation...

**Comment by kgnfth** [comment]
> OK, let's fix your database for now:
> 
> ```
> update photos set small = '' where small = 'x';
> update photos set small2x = '' where small2x = 'x';
> update photos set medium = '' where medium = 'x';
> update photos set medium2x = '' where medium2x = 'x';
> ```
> 
> See if that fixes that image for you. Obviously, we'll also need to fix Lychee so that it doesn't corrupt the database like that in the future when performing rotation...

Thanks its fixed
