### ISSUE TITLE
Video thumbnails are gereated for *.mp4 videos but not for *.mov videos

### ISSUE THREAD

**Issue by candrea21** [LycheeOrg/Lychee#742]
### Detailed description of the problem [REQUIRED]
Video thumbnails are (sometimes) gereated for *.mp4 videos but not for *.mov videos. There are any errors in the logs.

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Upload a *.mov videos

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

### Output of the diagnostics  [REQUIRED]
```
Diagnostics
-----------
Info: Latest version of PHP is 7.4
Warning: Using 32 bit PHP, recommended upgrade to 64 bit
Warning: Dropbox import not working. dropbox_key is empty.
Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.

System Information
------------------
Lychee Version (git):       No git data found.
DB Version:                 4.0.6

composer install:           --no-dev
APP_ENV:                    production
APP_DEBUG:                  true

System:                     Linux
PHP Version:                7.3
MySQL Version:              10.3.23-MariaDB-0+deb10u1

Imagick:                    1
Imagick Active:             1
Imagick Version:            1690
GD Version:                 2.2.5

Config Information
------------------
version:                    040006
check_for_updates:          0
sorting_Photos_col:         takestamp
sorting_Photos_order:       DESC
sorting_Albums_col:         max_takestamp
sorting_Albums_order:       DESC
imagick:                    1
skip_duplicates:            0
small_max_width:            0
small_max_height:           360
medium_max_width:           1920
medium_max_height:          1080
lang:                       en
layout:                     1
image_overlay:              1
image_overlay_type:         desc
default_license:            none
compression_quality:        90
full_photo:                 1
delete_imported:            0
Mod_Frame:                  1
Mod_Frame_refresh:          30
thumb_2x:                   1
small_2x:                   1
medium_2x:                  1
landing_page_enable:        0
landing_owner:              xxx
landing_title:              xxx
landing_subtitle:           
landing_facebook:           
landing_flickr:             
landing_twitter:            
landing_instagram:          
landing_youtube:            
landing_background:         dist/cat.jpg
site_title:                 Lychee (xxx)
site_copyright_enable:      1
site_copyright_begin:       2020
site_copyright_end:         2020
additional_footer_text:     
display_social_in_gallery:  0
public_search:              0
SL_enable:                  0
SL_for_admin:               0
public_recent:              0
recent_age:                 1
public_starred:             0
downloadable:               0
photos_wraparound:          1
map_display:                1
zip64:                      1
map_display_public:         0
map_provider:               Wikimedia
force_32bit_ids:            0
map_include_subalbums:      0
update_check_every_days:    3
has_exiftool:               1
share_button_visible:       1
import_via_symlink:         0
has_ffmpeg:                 1
location_decoding:          1
location_decoding_timeout:  30
location_show:              1
location_show_public:       0
rss_enable:                 0
rss_recent_days:            7
rss_max_items:              100
prefer_available_xmp_metadata: 1
```

### Browser and system
MacOS, Firefox, Raspberry Pi, all latest versions.

**Comment by kamil4** [comment]
I just tried with the 4.0.6 release and I'm unable to reproduce this. Is this happening will all `mov` files for you? Can you try, say, https://file-examples-com.github.io/uploads/2018/04/file_example_MOV_1920_2_2MB.mov ?

How was your Lychee installed?

**Comment by candrea21** [comment]
With your ```mov``` file it do not happen. My Lychee is installed via GitHub, checking out latest release, i.e., 4.0.6. 
Can you point me to the code lines, where the thumbnails are generated? 
Have you (also) installed exiftool?

**Comment by kamil4** [comment]
exiftool shouldn't matter as we normally don't use it for videos, at least not if ffmpeg is installed. But yes, I do have it installed.

It would be easiest if you posted a sample `mov` file that demonstrates the problem but since you are willing to experiment, here you go. The method you need to play with is:

https://github.com/LycheeOrg/Lychee/blob/0e3289c295f731030d999c76c807619b0e1886d9/app/ModelFunctions/PhotoFunctions.php#L545

We normally try to extract a still frame from the middle of the video file:

https://github.com/LycheeOrg/Lychee/blob/0e3289c295f731030d999c76c807619b0e1886d9/app/ModelFunctions/PhotoFunctions.php#L557-L558

(we store the length of video files in `aperture`). My guess is that your `mov` files are slightly malformed and do not contain their length in the headers. In principle, we do have fallback code that should then try to extract the first still frame from the video:

https://github.com/LycheeOrg/Lychee/blob/0e3289c295f731030d999c76c807619b0e1886d9/app/ModelFunctions/PhotoFunctions.php#L566-L570

However, that code is effectively unreachable since we bail early due to the following test at the very beginning of this method:

https://github.com/LycheeOrg/Lychee/blob/0e3289c295f731030d999c76c807619b0e1886d9/app/ModelFunctions/PhotoFunctions.php#L547-L549

So what you should do is comment out the above test and see if that fixes it. Do let us know what the result is as we would like to fix it in the mainline as well!

**Comment by candrea21** [comment]
Thank you for your explanations. I did as you suggested, but it did not solve the problem.
Interesstingly I have two different servers running the exact same version of Lychee. The problem occures only for one of the two installations. I know it sounds strange and it is very hard to diagnose...

**Summary:**
- I have two servers S1 and S2 running Lychee
- I have two videos V1 and V2
- Thumbnails are generated for V1 and V2 on server S1.
- Thumbnails are generated for V1 on server S2, but not for V2.

**Comment by kamil4** [comment]
Bugger... OK, what's different between servers S1 and S2? Are the ffmpeg versions different (`ffmpeg -version`)?

For V2 on S2, is the metadata extracted correctly? I.e., in the Lychee UI, when you open the info sidebar for that video file, are resolution, duration, and frame rate listed or not?

Do you have access to the command line on that server? Can you try extracting the duration, i.e., `ffprobe -select_streams v:0 -show_entries stream=duration source.mov`? Then, can you try extracting the frame manually, i.e., `ffmpeg -ss [offset] -i source.mov -frames:v 1 output.jpg` where `[offset]` is the duration of the video divided by 2?

**Comment by candrea21** [comment]
I found the error! 

What you wrote above works on S1 and S2, but ffmpeg versions are different.

**Steps to reproduce:**
1. Have server S1 working
2. Set up server S2 (without ffmpeg)
3. Migrate video V2 from S1 to S2
4. Install ffmpeg on S2
5. Upload test video V1 to S2 -> thumbnail is generated
6. Upload video V2 to S2 (where it already exists) -> thumbnail is NOT generated
7. Delete V2 (and its copy) from S2
8. Upload video V2 to S2 -> thumbnail is generated

As it seems, video thumbnails are not regenerated for videos that already exist and are reuploaded. They must be deleted befor reuploading.

Thank you very much for your support. Lychee is great photo-management-system and everyone who contributes is awesome.

**Comment by kamil4** [comment]
Yeah, Lychee avoids keeping duplicates. You can influence it somewhat using the `skip_duplicates` config option. Also, in a situation as you described above, the solution is to invoke `php artisan lychee:video_data` from the command line, which will attempt to regenerate any missing metadata/thumbnails.
