### ISSUE TITLE
Internal Server Error when accessing RSS feed

### ISSUE THREAD

**Issue by bannisdale** [LycheeOrg/Lychee#747]
### Detailed description of the problem
I try to open the RSS feed after enabling it in the options. It returns "Error 500"

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Open gallery
2. Try to open RSS feed
3. Internal Server Error appears

Alternatively:
1. Give general URL to feed reader
2. Try to subscribe to feed
3. Subscription fails

**Screenshots**

![image](https://user-images.githubusercontent.com/42511384/94908830-8d7e2680-04a2-11eb-9473-3ff695e09543.png)

![image](https://user-images.githubusercontent.com/42511384/94908971-bf8f8880-04a2-11eb-8d0f-b8e554a16f74.png)

From the feed reader import:
![image](https://user-images.githubusercontent.com/42511384/94909029-d930d000-04a2-11eb-86c2-bd52d18b6c78.png)

### Output of the diagnostics

    Diagnostics
    -------
    Warning: Dropbox import not working. dropbox_key is empty.
    Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.

    System Information
    --------------
    Lychee Version (release):   4.0.6
    DB Version:                 4.0.6
    
    composer install:           --no-dev
    APP_ENV:                    production
    APP_DEBUG:                  false
    
    System:                     Linux
    PHP Version:                7.4
    MySQL Version:              10.3.24-MariaDB
    
    Imagick:                    1
    Imagick Active:             1
    Imagick Version:            1690
    GD Version:                 bundled (2.1.0 compatible)

    Config Information
    --------------
    version:                    040006
    check_for_updates:          0
    sorting_Photos_col:         takestamp
    sorting_Photos_order:       ASC
    sorting_Albums_col:         max_takestamp
    sorting_Albums_order:       DESC
    imagick:                    1
    skip_duplicates:            0
    small_max_width:            0
    small_max_height:           360
    medium_max_width:           1920
    medium_max_height:          1080
    lang:                       en
    layout:                     1
    image_overlay:              1
    image_overlay_type:         desc
    default_license:            reserved
    compression_quality:        90
    full_photo:                 1
    delete_imported:            0
    Mod_Frame:                  1
    Mod_Frame_refresh:          30
    thumb_2x:                   1
    small_2x:                   1
    medium_2x:                  1
    landing_page_enable:        1
    landing_owner:              ---
    landing_title:              ---
    landing_subtitle:           ---
    landing_facebook:           
    landing_flickr:             
    landing_twitter:            
    landing_instagram:          
    landing_youtube:            
    landing_background:         dist/cat.jpg
    site_title:                 ---
    site_copyright_enable:      1
    site_copyright_begin:       2018
    site_copyright_end:         2020
    additional_footer_text:     
    display_social_in_gallery:  0
    public_search:              0
    SL_enable:                  0
    SL_for_admin:               0
    public_recent:              0
    recent_age:                 1
    public_starred:             0
    downloadable:               0
    photos_wraparound:          1
    map_display:                0
    zip64:                      1
    map_display_public:         0
    map_provider:               Wikimedia
    force_32bit_ids:            0
    map_include_subalbums:      0
    update_check_every_days:    3
    has_exiftool:               0
    share_button_visible:       0
    import_via_symlink:         0
    has_ffmpeg:                 1
    location_decoding:          0
    location_decoding_timeout:  30
    location_show:              0
    location_show_public:       0
    rss_enable:                 1
    rss_recent_days:            14
    rss_max_items:              100
    prefer_available_xmp_metadata: 0

### Browser and system

Win 10, multiple browsers (Firefox, Opera, Chrome)

**Comment by ildyria** [comment]
I tested locally on my installation. It seems to work fine. 🤔

Can you enable 
`APP_DEBUG:                  true`
in your `.env` and try to load the feed to see which error you get ?

**Comment by bannisdale** [comment]
I did enable it and got a cascade of errors. If I get this correctly, the RSS handler wants to get the file and the file size, but the file size can't be evaluated, so the whole thing crashes.

![image](https://user-images.githubusercontent.com/42511384/95560053-fcb2c800-0a18-11eb-81e4-099dab3bf44c.png)

The file that is given exists, but I realized that the folder `upload` is displayed two times (see highlighted text), so it might be that the requested image is searched in `/public/uploads/uploads/big/` instead of `public/uploads/big/`.

However, adding a symbolical link to `/uploads/` pointing at the current folder so that `public/uploads/uploads/big/` could be resolved didn't fix anything, so there might be something else going on.

**Comment by ildyria** [comment]
it should not be `public/uploads/uploads/big/`  that is for sure.

What is the call stack looking like ? 
Because this is clearly the last call of the stack, but I would like to know what it looks like above (which function called it etc)

**Comment by ildyria** [comment]
My guess is this is crashing here:
https://github.com/LycheeOrg/Lychee/blob/fa21ad8f353d3dc109b31def9ad550adcaa38a59/app/Http/Controllers/RSSController.php#L45-L46
And I think this is because of the `public_path` and `['url']` is incorrect.

**Comment by bannisdale** [comment]
What do you need? Should I past a screenshot of the (quite long) call stack? Or do a write-up of the functions?

The RSSController is definitely part of it:

![image](https://user-images.githubusercontent.com/42511384/95569626-1c9cb880-0a26-11eb-880d-63506be7174f.png)

Given that it works for you, it might be something in the settings that's not set correctly but that is called by the RSS Controller? Gallery is working flawlessly, though. :)

**Comment by ildyria** [comment]
I just noticed that the code does not look like the same as I have and then noticed `Lychee Version (release):   4.0.6`

As it is working fine on my prod server (which is running the latest version: _master_), I can only assume this is a bug in the 4.0.6 that we solved at some point...

It looks like we REALLY need to do a new release. Sadly I don't have the time to build it right now.
(we also need to write the change log https://lycheeorg.github.io/docs/releases.html )

I would have liked to say you can double check by replacing that specific file with the new one, but as we did a lot of change in the current version, this would break your installation for sure.

**Comment by bannisdale** [comment]
Well, I guess I'll wait for the next release then. :)

**Comment by ildyria** [comment]
@bannisdale can you try this one: https://github.com/LycheeOrg/Lychee/releases/tag/v4.0.7 ?

**Comment by bannisdale** [comment]
Will do and report back, but it might take a day or two.

**Comment by ildyria** [comment]
@bannisdale any update ?

**Comment by bannisdale** [comment]
@ildyria Thanks for the ping / sorry for the delay. 

Updated the instance and RSS looks good now. Thanks!
