### ISSUE TITLE
artisan:video_data does not generate video thumbnails

### ISSUE THREAD

**Issue by haivala** [LycheeOrg/Lychee#751]
### Detailed description of the problem [REQUIRED]
running artisan:video_data does not generate video thumbnails or any errors

### Steps to reproduce the issue
running artisan:video_data does not generate video thumbnails or any errors

### Output of the diagnostics  [REQUIRED]

    Diagnostics
    -------
```
    Info: Latest version of PHP is 7.4
    Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.
    Warning: Dropbox import not working. dropbox_key is empty.




    System Information
    --------------
    Lychee Version (git):            master (174c910) - Data not in Cache
    DB Version:                      4.0.6
    
    composer install:                --no-dev
    APP_ENV:                         local
    APP_DEBUG:                       true
    
    System:                          Linux
    PHP Version:                     7.3
    Max uploaded file size:          150M
    Max post size:                   200M
    MySQL Version:                   10.4.14-MariaDB
    
    Imagick:                         1
    Imagick Active:                  1
    Imagick Version:                 1691
    GD Version:                      2.3.0




    Config Information
    --------------
    version:                         040006
    check_for_updates:               1
    sorting_Photos_col:              takestamp
    sorting_Photos_order:            ASC
    sorting_Albums_col:              max_takestamp
    sorting_Albums_order:            DESC
    imagick:                         1
    skip_duplicates:                 0
    small_max_width:                 0
    small_max_height:                360
    medium_max_width:                1920
    medium_max_height:               1080
    lang:                            en
    layout:                          1
    image_overlay:                   1
    image_overlay_type:              exif
    default_license:                 none
    compression_quality:             90
    full_photo:                      1
    delete_imported:                 1
    Mod_Frame:                       0
    Mod_Frame_refresh:               30
    landing_page_enable:             0
    landing_owner:                   Entropy ry
    landing_title:                   Entropy ry
    landing_subtitle:                Party Photography
    landing_facebook:                https://www.facebook.com/EntropyRy
    landing_flickr:                  
    landing_twitter:                 
    landing_instagram:               
    landing_youtube:                 
    landing_background:              dist/cat.jpg
    thumb_2x:                        1
    small_2x:                        0
    medium_2x:                       0
    site_title:                      ePics
    site_copyright_enable:           1
    site_copyright_begin:            2000
    site_copyright_end:              2020
    public_search:                   1
    additional_footer_text:          
    display_social_in_gallery:       0
    public_recent:                   1
    recent_age:                      1
    SL_enable:                       0
    SL_for_admin:                    0
    public_starred:                  0
    downloadable:                    0
    photos_wraparound:               1
    map_display:                     1
    zip64:                           1
    map_display_public:              0
    map_provider:                    OpenStreetMap.org
    force_32bit_ids:                 0
    map_include_subalbums:           0
    update_check_every_days:         3
    has_exiftool:                    0
    share_button_visible:            0
    import_via_symlink:              0
    has_ffmpeg:                      1
    location_decoding:               0
    location_decoding_timeout:       30
    location_show:                   1
    location_show_public:            0
    rss_enable:                      0
    rss_recent_days:                 7
    rss_max_items:                   100
    prefer_available_xmp_metadata:   0
    editor_enabled:                  1
    lossless_optimization:           0
    swipe_tolerance_x:               150
    swipe_tolerance_y:               250
    local_takestamp_video_formats:   .avi|.mov
```

**Comment by haivala** [comment]
running the command gives:
```
Will attempt to generate up to 100 video thumbnails/metadata with a timeout of 600 seconds...
Processing VID_20181124_233942...
Processing VID_20181125_010252...
Processing VID_20181125_035148...
Processing VID_20181125_033313...
Processing VID_20181125_013036...
```
and nothing else
ffmpeg-php is installed with composer and ffmpeg is installed to the server

**Comment by kamil4** [comment]
Could you update your installation to the latest commit and try again? I made some changes to the `video_data` command the other day. While they are unlikely to fix your problem, they may result in some additional diagnostic messages that would shed light on what might be going on...

So I understand that those videos do not have thumbnails? How about metadata? In the Lychee UI, when you open the info sidebar while viewing the video files, are resolution, duration, and frame rate listed in the `Video` section or not?

My guess would be that the Lychee server can't find your `ffmpeg`/`ffprobe` binaries for some reason. Are they in the default path? There is an entry about it in the FAQ (https://lycheeorg.github.io/docs/faq.html#why-dont-my-videos-have-thumbnails) though the answer doesn't match the current source code...

**Comment by haivala** [comment]
Updated, no change. I can watch the videos but they don't have thumbnails.

The metadata: There is size and format which are right but there isn't duration or frame rate and the resolution is 0 x 0.

binaries are at `/usr/bin/ffmpeg` and /usr/bin/ffprobe`. is this the default? tried that FAQ thing: no change.

**Comment by kamil4** [comment]
Something definitely goes wrong with the invocation of `ffprobe` and `ffmpeg` then. Can you upload a new video file and then check your logs (e.g., `php artisan lychee:logs` or `Show Logs` in the UI) and see if there are any recent errors that look relevant?

Can you try running `ffprobe` and `ffmpeg` from the command line and see if they work as expected? Lychee invokes them as follows:
```
/usr/bin/ffprobe [source-video-file] -show_streams -print_format json
/usr/bin/ffmpeg -y -ss [half of video file duration in seconds] -i [source-video-file] -vframes 1 -f image2 output.jpeg
```
Also, just to be sure, run the php interpreter interactively (`php -a`) and execute:
```
echo exec('command -v ffprobe');
```
It should print `/usr/bin/ffprobe`...

**Comment by haivala** [comment]
Uploaded a new video and all of the metadata can be now seen in info dialogue but no thumbnail and got this in the log: 
`2020-10-09 05:46:31 -- error   -- App\ModelFunctions\PhotoFunctions::add -- 410 -- Unable to load FFProbe`

Both of those commands work as expected.

```
php > echo exec('command -v ffprobe');
/usr/bin/ffprobe
```

**Comment by haivala** [comment]
btw, just a thought, it would be nice if this command could be able to convert videos to smaller size in resolution

**Comment by kamil4** [comment]
Do you understand by any chance what changed so that you get the metadata now? Did you change anything based on that FAQ I linked to earlier? It sounds like you might have; what did you change exactly? Because based on the current behavior of your installation it seems like you managed to fix _half_ of the problem. The metadata is now extracted correctly (we use `php-exif` for that purpose, found under `vendor/lychee/`; did you change anything there? It internally uses `ffprobe`) but the thumbnail extraction is still not working; that code is here:

https://github.com/LycheeOrg/Lychee/blob/fa21ad8f353d3dc109b31def9ad550adcaa38a59/app/ModelFunctions/PhotoFunctions.php#L542

As to your second point, yes, it would be nice. Our video support is extremely rudimentary and in my opinion only really suitable for very short clips. And it's not easy to improve. For images we convert them to different resolutions at upload time because it's relatively quick but for large videos that could take forever and would have to be done in the background to avoid browser timeouts and such. As far as I know, the HTML5-based video viewer available in the browser, which is what we use, doesn't have good support for multiple resolutions. We would need to use something else for playback... Perhaps I should open a separate enhancement issue with a call for volunteers about this...

**Comment by haivala** [comment]
I think the video without the metadata is one of those videos I have uploaded when the video support was introduced long time ago. So there is no way I could know what I did between :) My update procedure is git pull, composer install, artisan migrate and I have not touched the code.

I suggest that this command could have option to forcefully update the matadata and the thumbnail as it seems that it does not do the same things as when I upload the files. This way I would not need to upload the files again and again.

Yeah that is true that Lychee only suits for very short clips. I'm in a situation where I have 4K max 30s videos uploaded but I think HD quality would be enough for storing those. I would wait to get proper support in HTML5 player rather than use some other means to play the videos although this look promising: https://plyr.io/ for example.

**Comment by haivala** [comment]
I was able to get this working with:
```php
       /**
         * @param Photo $photo
         *
         * @return string Path of the video frame
         */
        public function extractVideoFrame(Photo $photo): string
        {
                if (!Configs::hasFFmpeg()){
                        Logs::notice(__METHOD__, __LINE__, 'Failed to extract snapshot: bad config: ' . Configs::hasFFmpeg());
                        return '';
                }
                if ($photo->aperture === '') {
                        $path = Storage::path('big/' . $photo->url);
                        $info = $this->metadataExtractor->extract($path, 'video');
                        $photo->aperture = $info['aperture'];
                }

                $ffmpeg = FFMpeg\FFMpeg::create();
                $video = $ffmpeg->open(Storage::path('big/' . $photo->url));
                $tmp = tempnam(sys_get_temp_dir(), 'lychee') . '.jpeg';
                Logs::notice(__METHOD__, __LINE__, 'Saving frame to ' . $tmp);
```
so basically I extract the aperture if it does not exist. Feel free to add this to this repo with modifications (like updating the aperture to the db).
Also this issue can be closed.

**Comment by ildyria** [comment]
Will be closed Soon.
