### ISSUE TITLE
[Enhancement] Rework header - too many buttons in lightbox

### ISSUE THREAD

**Issue by tmp-hallenser** [LycheeOrg/Lychee#756]
The current lightbox has 11 icons (star, public settings, 2x rotate, share, sidebar, map, move, trash, fullscreen, more (open original, download)). On mobile devices, these are too many to display properly.

I'd suggest to regroup them following the frequency on usage. A possible split could be:
* star
* share (include here public settings as well as download, open original)
* sidebar
* map
* fullscreen
* more (everything related to image manipulation)
** move
** trash 
** 2x rotate

**Comment by ildyria** [comment]
already fixed if I'm not wrong.
