### ISSUE TITLE
ZIP download "fails"

### ISSUE THREAD

**Issue by dennis9819** [LycheeOrg/Lychee#759]
### Detailed description of the problem [REQUIRED]
All ZIP downloads for an Download "fail". Firefox and Safari mark them as "Failed" but if I rename the .part file to .zip the downloaded file is fine. All Images are there. 
The file downloads until 99% then fails.
Firefox inspector tools displays the warning 'Response has been truncated'.
I've checked the headers and they seem to be correct. File size is correct and is equal to the length of the working .part file. 
Firefox and Safari display a filesize of 424MB which is correct.
Chrome says "Network error"

I'm using the latest version with docker and nginx with let's encrypt as an proxy for all my containers.

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
This error is reproducable and occures every time i try to download an album.

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

### Output of the diagnostics  [REQUIRED]
*(Settings => Diagnostics or https://example.com/Diagnostics or `php artisan lychee:diagnostics`)*
Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.
No critical problems found. Lychee should work without problems!

System Information
------------------
Lychee Version:  3.1.1
DB Version:      030100
System:          Linux
PHP Version:     5.5
MySQL Version:   50549
Imagick:         1
Imagick Active:  1
Imagick Version: 1655
GD Version:      2.1.1-dev
Plugins:         

### Browser and system
Firefox 81.0.2 on Windows 10
Safari on latest iOS
Chrome 86 on Window 10

**Comment by ildyria** [comment]
> Lychee Version: 3.1.1

Please upgrade to version 4.
https://lycheeorg.github.io/docs/upgrade.html

**Comment by ildyria** [comment]
Additionally:
> PHP Version: 5.5

Please upgrade to **at least** version 7.3, I recommend going for version 7.4 as 7.3 will be EoL in 2 months.
Anyway, Lychee v4 will not install if you don't have at least 7.3, and I can already tell you we will drop 7.3 in 2 months:
https://www.php.net/supported-versions.php
