### ISSUE TITLE
I can't  see the check for update button in the GUI

### ISSUE THREAD

**Issue by ccbcfan** [LycheeOrg/Lychee#761]
firefox brower, php exec is not available.

    Diagnostics
    -------
    Info: Latest version of PHP is 7.4
    Warning: Dropbox import not working. dropbox_key is empty.

    System Information
    --------------
    Lychee Version (git):            master (e5273b3) - Data not in Cache
    DB Version:                      4.0.7
    
    composer install:                --no-dev
    APP_ENV:                         production
    APP_DEBUG:                       true
    
    System:                          Linux
    PHP Version:                     7.3
    Max uploaded file size:          200M
    Max post size:                   200M
    MySQL Version:                   5.5.62-log
    
    Imagick:                         1
    Imagick Active:                  1
    Imagick Version:                 1687
    GD Version:                      bundled (2.1.0 compatible)

    Config Information
    --------------
    version:                         040007
    check_for_updates:               1
    sorting_Photos_col:              title
    sorting_Photos_order:            DESC
    sorting_Albums_col:              id
    sorting_Albums_order:            DESC
    imagick:                         1
    skip_duplicates:                 0
    small_max_width:                 0
    small_max_height:                360
    medium_max_width:                1920
    medium_max_height:               1080
    lang:                            简体中文
    layout:                          1
    image_overlay:                   1
    image_overlay_type:              desc
    default_license:                 none
    compression_quality:             90
    full_photo:                      1
    delete_imported:                 0
    Mod_Frame:                       0
    Mod_Frame_refresh:               30
    thumb_2x:                        1
    small_2x:                        1
    medium_2x:                       1
    landing_page_enable:             0
    landing_owner:                  cfan
    landing_title:                   cfan
    landing_subtitle:                Cats, Dogs & Humans Photography
    landing_facebook:                https://www.facebook.com/JohnSmith
    landing_flickr:                  https://www.flickr.com/JohnSmith
    landing_twitter:                 https://www.twitter.com/JohnSmith
    landing_instagram:               https://instagram.com/JohnSmith
    landing_youtube:                 https://www.youtube.com/JohnSmith
    landing_background:              dist/cat.jpg
    site_title:                      Lychee
    site_copyright_enable:           0
    site_copyright_begin:            2019
    site_copyright_end:              2020
    additional_footer_text:          
    display_social_in_gallery:       0
    public_search:                   0
    SL_enable:                       0
    SL_for_admin:                    0
    public_recent:                   0
    recent_age:                      1
    public_starred:                  0
    downloadable:                    1
    photos_wraparound:               1
    map_display:                     0
    zip64:                           1
    map_display_public:              0
    map_provider:                    Wikimedia
    force_32bit_ids:                 0
    map_include_subalbums:           0
    update_check_every_days:         1
    has_exiftool:                    0
    share_button_visible:            1
    import_via_symlink:              0
    has_ffmpeg:                      1
    location_decoding:               0
    location_decoding_timeout:       30
    location_show:                   1
    location_show_public:            0
    rss_enable:                      0
    rss_recent_days:                 7
    rss_max_items:                   100
    prefer_available_xmp_metadata:   1
    editor_enabled:                  1
    lossless_optimization:           0
    swipe_tolerance_x:               150
    swipe_tolerance_y:               250
    local_takestamp_video_formats:   .avi|.mov|.mp4
    log_max_num_line:                1000

**Comment by ildyria** [comment]
https://github.com/LycheeOrg/Lychee/blob/e5273b37ef0eaaaa6d9078efd8865e7d2c94b6cd/app/ControllerFunctions/Update/Check.php#L53-L80

Look at line 68. 

We need `exec` to ... execute `git`. So if this is not available we do not display the button.
