### ISSUE TITLE
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'lychee_db.pages' doesn't exist (SQL: select * from `pages` where `enabled` = 1 and `link` = /public order by `order` asc limit 1)

### ISSUE THREAD

**Issue by dodolereporter** [LycheeOrg/Lychee#762]
I have this error :
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'lychee_db.pages' doesn't exist (SQL: select * from `pages` where `enabled` = 1 and `link` = /public order by `order` asc limit 1)

My .env : 
![28363E99-CA9B-4A7F-A0D6-AE284670352E](https://user-images.githubusercontent.com/60071624/96950548-8bfbb900-14b8-11eb-8baf-154e2b3248e3.jpeg)

I m using phpmyadmin

**Comment by ildyria** [comment]
Did you apply the migration ? `php artisan migrate` ?

**Comment by dodolereporter** [comment]
I have Forget sorry 
Tank you
