### ISSUE TITLE
[Enhancement] Display PHP limit values in diagnostics page

### ISSUE THREAD

**Issue by norey** [LycheeOrg/Lychee#763]
@ildyria's idea

I was having trouble uploading images > 20MB and I completely forgot to consider the `upload_max_filesize` PHP setting. So why not add those max/limit values in the Diagnostics page for easier debugging?

**Comment by ildyria** [comment]
Actually... Fun fact, they already are. E.g. for my install:
```

    System:                          Linux
    PHP Version:                     7.4
    Max uploaded file size:          500M
    Max post size:                   500M
    MySQL Version:                   10.3.24-MariaDB-1
```
