### ISSUE TITLE
Error while manual Upgrade from Lychee 4.0.6 to 4.0.7

### ISSUE THREAD

**Issue by prbt2016** [LycheeOrg/Lychee#765]
Hello,

I  was in the process of upgrading Lychee from 4.0.6 to 4.0.7 on Centos 6.9 with PHP 7.3.11, MYSQL 5.5.62 and Apache 2.2.34. I followed the following steps to upgrade : 

https://lycheeorg.github.io/docs/update.html#update-manually

1. Downloaded latest version i.e 4.0.7

2. Replaced all the existing files , excluding public/uploads, public/dist/user.css and also .env file(which holds the database details).

After that when i try to visit  admin panel url i get a blank page like this : 

![lychee](https://user-images.githubusercontent.com/17871448/97553474-7d069080-19fb-11eb-8bb3-a0f90a6ba739.png)

So to debug the issue I checked in /storage/logs/laravel.log it shows that : 

`[2020-10-29 09:17:43] production.ERROR: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'smart' in 'where clause' (SQL: select * from `albums` where `public` = 1 and `visible_hidden` = 1 and `parent_id` is null and `smart` = 0 order by `max_takestamp` asc) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'smart' in 'where clause' (SQL: select * from `albums` where `public` = 1 and `visible_hidden` = 1 and `parent_id` is null and `smart` = 0 order by `max_takestamp` asc) at /{{PATH}}/{{TO}}/{{PUBLIC_HTML}}/{{LYCHEE-DIR}}/vendor/laravel/framework/src/Illuminate/Database/Connection.php:671)`

Full output of laravel.log I have attached for your reference : 

[lychee_laravel.log](https://github.com/LycheeOrg/Lychee/files/5457396/lychee_laravel.log)

The script searches for columns that are in latest version. How would I achieve third step mentioned in docs i.e 

3. 'Go into the Diagnostic page and click on the Apply migration' button as mentioned in official site documentation.

Is there any way so that I could reach the 3rd step and perform upgrade via browser?.  

Since I am on shared hosting platform and have no access to command line, cannot use other methods mentioned in documentation.

So my query is how to upgrade any 4.0.x version to any other 4.0.x version via browser?. What are the exact steps?.

**Comment by ildyria** [comment]
Ah, I see the problem.

thank you for pointing that one up.

In the mean time, the fastest way to "fix" this is to remove the `.env` file or edit it to remove the encryption key (`APP_KEY=`).

This will trigger a redirection to `/install`, just follow the steps again quickly. The last one will be the application of the `migration` which should fix the missing column.
