### ISSUE TITLE
Failed to upload image and report error

### ISSUE THREAD

**Issue by dourylee** [LycheeOrg/Lychee#767]
Failed to upload image and report error，as shown in the figure.

When I upload an image, it will report the following error

![微信截图_20201101174843](https://user-images.githubusercontent.com/22514904/97799924-ce1cbb80-1c6b-11eb-851c-9067f4e9c771.png)
![微信截图_20201101175306](https://user-images.githubusercontent.com/22514904/97799928-d5dc6000-1c6b-11eb-92bc-c3506b12fae0.png)
So how to solve this problem?

**Comment by dourylee** [comment]
What template?

Docker:18.09.2
CPU:arm64v8
Image tag:lycheeorg/lychee:latest

I've deployed it several times, but it's all wrong

**Comment by d7415** [comment]
> What template?

The one that was shown when you opened this issue, that you had to actively delete to post this issue in its current form.
