### ISSUE TITLE
Uploads often get stuck in Firefox

### ISSUE THREAD

**Issue by rbren** [LycheeOrg/Lychee#768]
### Detailed description of the problem [REQUIRED]
About 1% of my photos get stuck, either
* stopped at 99% uploaded
* stuck in the `processing` phase

Certain photos seem more likely to trigger this. When it happens several times with the same photo, uploading it to `unsorted` rather than a particular album seems to fix the issue.

### Steps to reproduce the issue
* Create a new album
* bulk upload ~100 high-quality photos

**Screenshots**
*If applicable, add screenshots to help 
<img width="562" alt="Screen Shot 2020-11-02 at 9 05 04 AM" src="https://user-images.githubusercontent.com/7611973/97885005-cc4b0a80-1cf4-11eb-9887-08bb96a71035.png">
<img width="566" alt="Screen Shot 2020-11-02 at 9 04 29 AM" src="https://user-images.githubusercontent.com/7611973/97885007-cc4b0a80-1cf4-11eb-9981-0626d8a393e8.png">

explain your problem.*

### Output of the diagnostics  [REQUIRED]
*(Settings => Diagnostics or https://example.com/Diagnostics or `php artisan lychee:diagnostics`)*

```



    Diagnostics
    -------
    Info: Latest version of PHP is 7.4
    Warning: Dropbox import not working. dropbox_key is empty.




    System Information
    --------------
    Lychee Version (git):            No git data found.
    DB Version:                      4.0.6
    
    composer install:                --no-dev
    APP_ENV:                         production
    APP_DEBUG:                       false
    
    System:                          Linux
    PHP Version:                     7.3
    Max uploaded file size:          20M
    Max post size:                   100M
    MySQL Version:                   8.0.22
    
    Imagick:                         1
    Imagick Active:                  1
    Imagick Version:                 1690
    GD Version:                      2.2.5

    
    Lychee total space:              33.78 MB
    Upload folder space:             8.00 B
    System total space:              78.71 GB
    System free space:               64.72 GB (82%)




    Config Information
    --------------
    version:                         040006
    check_for_updates:               0
    sorting_Photos_col:              takestamp
    sorting_Photos_order:            ASC
    sorting_Albums_col:              max_takestamp
    sorting_Albums_order:            ASC
    imagick:                         1
    skip_duplicates:                 0
    small_max_width:                 0
    small_max_height:                360
    medium_max_width:                1920
    medium_max_height:               1080
    lang:                            en
    layout:                          1
    image_overlay:                   1
    image_overlay_type:              desc
    default_license:                 none
    compression_quality:             90
    full_photo:                      1
    delete_imported:                 0
    Mod_Frame:                       1
    Mod_Frame_refresh:               30
    thumb_2x:                        1
    small_2x:                        1
    medium_2x:                       1
    landing_page_enable:             0
    landing_owner:                   John Smith
    landing_title:                   John Smith
    landing_subtitle:                Cats, Dogs & Humans Photography
    landing_facebook:                https://www.facebook.com/JohnSmith
    landing_flickr:                  https://www.flickr.com/JohnSmith
    landing_twitter:                 https://www.twitter.com/JohnSmith
    landing_instagram:               https://instagram.com/JohnSmith
    landing_youtube:                 https://www.youtube.com/JohnSmith
    landing_background:              dist/cat.jpg
    site_title:                      Lychee v4
    site_copyright_enable:           1
    site_copyright_begin:            2019
    site_copyright_end:              2019
    additional_footer_text:          
    display_social_in_gallery:       0
    public_search:                   0
    SL_enable:                       0
    SL_for_admin:                    0
    public_recent:                   0
    recent_age:                      1
    public_starred:                  0
    downloadable:                    0
    photos_wraparound:               1
    map_display:                     0
    zip64:                           1
    map_display_public:              0
    map_provider:                    Wikimedia
    force_32bit_ids:                 0
    map_include_subalbums:           0
    update_check_every_days:         3
    has_exiftool:                    1
    share_button_visible:            0
    import_via_symlink:              0
    has_ffmpeg:                      1
    location_decoding:               0
    location_decoding_timeout:       30
    location_show:                   1
    location_show_public:            0
    rss_enable:                      0
    rss_recent_days:                 7
    rss_max_items:                   100
    prefer_available_xmp_metadata:   0
    editor_enabled:                  1
    lossless_optimization:           0
    swipe_tolerance_x:               150
    swipe_tolerance_y:               250
    local_takestamp_video_formats:   .avi|.mov
```

### Browser and system
Firefox on OS X

**Comment by rbren** [comment]
Would also like to say - this problem was _way_ worse in Lychee v3. Huge thanks to the folks maintaining and improving Lychee!

**Comment by ildyria** [comment]
When this happens, it usually means to us that PHP crashed on the server side either due to:

- lack of memory available to process the picture with imagick, or some other crash for some other reason, etc.
- the image was too big (in your case >20MB).

Your diagnostics says:
```
Max uploaded file size:          20M
```

By increasing this value this should solve some of your crash upload cases.

**Comment by rbren** [comment]
Nothing over 20M, and can confirm that the backend didn't crash.

I actually gave Chrome a shot, and it works perfectly. So I think this is a FF-specific bug

**Comment by ildyria** [comment]
Well that is somewhat good to know. :sweat_smile:

**Comment by kamil4** [comment]
I hate such bugs :frowning_face:.

So do you _have_ to upload a batch of photos for this to get triggered or have you seen it happen when uploading just a single photo at a time as well?

**Comment by kamil4** [comment]
Also, @rbren, how did you verify that the backend didn't crash?

**Comment by rbren** [comment]
I would upload a big batch, and one or two would get stuck. But if I tried to upload those one or two individually, they'd get stuck over and over again. So it seemed to be photo-specific.

The backend is running inside Kubernetes, which would have told me if the container restarted. Unless the backend gracefully recovers without killing the container?

Unfortunately I haven't been able to repro, even with the same photos. So there's something state-dependent going on here.

I'm OK with closing this given how hard it seems to be to repro. Will ping here again if I manage to get more details

**Comment by ildyria** [comment]
If you arrive to a state where processing the image exhaust the memory, the php process will crash. The thing is, why php dies, it does not means that the server running it dies with it. The server will spawn a new instance of php for each upload.
