### ISSUE TITLE
[BUG] Sorting/ordering albums by take date of photos inside not working properly

### ISSUE THREAD

**Issue by Julianoe** [LycheeOrg/Lychee#770]
I feel i tried everything but since I upgraded to v4 I can't find any way to make my albums sorted the same way they were in the previous version.
It'd be cool if we could just very simply have a sorting option to order albums by time the photos were taken. I guess something along the lines of "sort by most recent photo inside" or "sort by most ancient photo inside" said album.

For more clarity, some example usecase:
I create an album in november 2020 for a shoot I did in june 2020, with this type of sorting, it would just fall chronologically at its right place between july 2020 shoot album and may 2020 shoot album.

**Comment by Julianoe** [comment]
I just want to add that I'm using Lychee in french and it seems there is some problems with translation in the settings/sorting menu. Switching to english makes it more clear what sorting option does what, I realise that the sorting option I'm looking for exists with "latest take date" or "oldest take date"... BUT it seems it does not work. Once sorted this way the albums are still mixed in a way I'm not sure i understand. 

With options set like : 
- sort albums by _latest take date_ in an _descending_ order
- sort photos by _take date_ in an _ascending_ order

I still have albums from 2018 (with photos all taken the same day in 2018) mixed with 2020 albums for example...

**Comment by ildyria** [comment]
That is weird as it is working totally fine here.
> - sort albums by latest take date in an descending order
> - sort photos by take date in an ascending order

I literally have the same setting.

> Once sorted this way the albums are still mixed in a way I'm not sure i understand.

If there are pictures without timestamp, it will be messing up the ordering.

Would it be possible for you to provide us a mysql dump of your photos and albums table ?

Also which version 4 are you using ? v4.0.7 ? the master branch ?

**Comment by kamil4** [comment]
If the gallery is public, can you share a link? It will give us only partial information (frontend side) but better this than nothing...

**Comment by ocai** [comment]
Not OP but running into the same issue on v4.0.8 running in Linuxserver's latest Docker image. I have sort albums and sort photos in the exact same setting. Here's a link to my public gallery: https://photos.olivercai.com/. The album order is out of whack despite the photo taken dates being shown correctly.

I originally wanted to sort by album creation time but this was ordering it wrong as well. So for a while I was resorting to sorting by the album description and I would stick the date into the description and sorting would work that way.
[lychee.sql.zip](https://github.com/LycheeOrg/Lychee/files/5611551/lychee.sql.zip)

**Comment by ildyria** [comment]
Thank you for providing the sql, it really helps. 
The `min_takestamp` and `max_takestanp` column at empty. That's problem.

Now, let's see how we can fix this.
I did notice some pictures not having takestamps but that shouldn't be of influence.

**Comment by ocai** [comment]
Are `min_takestamp` and `max_takestamp` a recent addition? I'm looking at my albums table and see that only the last 2 albums have it populated. Everything before were albums that were migrated over from a pre-LycheeOrg v3.1.6 installation. It looks like maybe these aren't captured from migrated albums?

**Comment by ildyria** [comment]
humm quite possible yes.

**Comment by ildyria** [comment]
I added a new command to solve this.

**Comment by kamil4** [comment]
Well, we do invoke takestamp recalculation from within database migration:

https://github.com/LycheeOrg/Lychee/blob/8da832e62f0095f0971247e42624e93225128386/database/migrations/2018_08_15_103716_move_photos.php#L89

So in principle this should work.  A new command is a good idea anyway. I'm a little surprised that you added it to routes though -- are you planning to add a GUI on the front end side for it?

**Comment by ildyria** [comment]
it is already added, you just need to call example.com/Albums/RebuildTakestamps (since last commit)

**Comment by ildyria** [comment]
you need to be logged as admin though.

**Comment by ocai** [comment]
Just tested this by updating files in the last commit and restarting the container. Logged in as admin and went to /Albums/RebuildTakestamps which returned true. Checked the albums table and it looks like it reset the takestamps on the last 2 albums since they're now both NULL and didn't populate it on any of the other albums.

**Comment by ildyria** [comment]
Okay, that is NOT the expected behaviour.

**Comment by kamil4** [comment]
@ocai, if you are doing the update via git, can you try the `fix-reset-takestamp` branch and see if rebuilding the takestamps fixes it for you?

**Comment by ocai** [comment]
> 
> 
> @ocai, if you are doing the update via git, can you try the `fix-reset-takestamp` branch and see if rebuilding the takestamps fixes it for you?

I ended up installing Lychee in a new VM (previously had it in a Docker container) to test out this branch and indeed, it looks like min/max takestamps are now populated upon photo upload.
