### ISSUE TITLE
View All Pictures [Enhancement]

### ISSUE THREAD

**Issue by kgnfth** [LycheeOrg/Lychee#774]
*Explain in a few words which functionality or improvements you would like to see in Lychee.*

it would be great if there was a All smart album that lists all the pictures

**Comment by ildyria** [comment]
1- I don't think this is such a great idea, as you may have A LOT of pictures for once and we don't have pagination yet implemented.
2- You can equivalently use the search functionality: it is likely that all your pictures have a similar name format: IMG_xxx, so if you just search for IMG, you will also get all the pictures.

**Comment by ildyria** [comment]
If someone wants to give it a go, please have a look at this.
https://github.com/LycheeOrg/Lychee/tree/master/app/SmartAlbums

Such would be pretty straight forward to implement.

**Comment by kgnfth** [comment]
@ildyria 

i finally made it
like this

```
<?php

namespace App\SmartAlbums;

use App\Models\Photo;
use Illuminate\Database\Eloquent\Builder;

class AllAlbum extends SmartAlbum
{

	public function get_title()
	{
		return 'all';
	}

	public function get_photos(): Builder
	{
		return Photo::getAll()->where(fn ($q) => $this->filter($q));
        }
    
}
```

`/Models/Photo.php`

```
public function scopegetAll($query)
{
       return $query->orderBy('photos.id', 'ASC');
}
```
