### ISSUE TITLE
Nginx configuration to use with docker, fresh install

### ISSUE THREAD

**Issue by dolie** [LycheeOrg/Lychee#775]
Hello, 
I am trying to use Lychee with docker (because I am not a PHP expert), with nginx (neither nginx expert).
May you provide classic nginx configuration or subpage nginx configuration ? 🙏  

I tried to, but I get :
> "The ressource at « http://[myurl].com/photos/dist/main.js?1604699362 » has been blocked because of a MIME type (« text/html ») incorrect (X-Content-Type-Options: nosniff).  

on firefox...

Here is my failed nginx config attempt

```
upstream backend_lychee {
  server 127.0.0.1:2507;
}

server {
  gzip on;
  listen 80;
  server_name [myurl].com
  charset UTF-8;

  location = / {
    root /home/username/myProjectFolder;
    try_files /index.html =404;
  }

  location ^~ /photos {
    auth_basic "!";
    auth_basic_user_file /etc/nginx/.htpasswd;
    include proxy_params;
    proxy_pass http://backend_lychee/$1;
  }
}
```

**Comment by dolie** [comment]
I can make it work on 'standalone' website, but not on a subpage website (i get a 404)

Successful standalone website / nginx config
```
  1 upstream docker-lychee {
  2         server 127.0.0.1:2507;
  3 }
  4
  5
  6 server {
  7         listen 80;
  8         server_name mysite.com www.mysite.com;
  9         charset UTF-8;
 10
 11         location / {
 12                 proxy_pass         http://docker-lychee;
 13                 proxy_redirect     off;
 14                 proxy_set_header   Host $host;
 15                 proxy_set_header   X-Real-IP $remote_addr;
 16                 proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
 17                 proxy_set_header   X-Forwarded-Host $server_name;
 18         }
 19 }
```

Failed Lychee integrated in existing website (404 on lychee Page) :  

```
  1 upstream backend_lychee {
  2   server 127.0.0.1:2507;
  3 }
  4
  5 server {
  6         listen 80;
  7         root /home/user/projectFolder;
  8         server_name myExistingSite.com www.myExistingSite.com;
  9         index index.html
 10         charset UTF-8;
 11
 12   location = / {
 13     try_files /index.html =404;
 14   }
 15
 16   location = /index.html {
 17     try_files /index.html =404;
 18   }
 19
 20   location = /robots.txt {
 21     try_files /robots.txt =404;
 22   }
 23
 27
 28   location /photos {
 29         auth_basic "!";
 30         auth_basic_user_file /etc/nginx/.htpasswd;
 33         proxy_pass http://backend_lychee;
 34         proxy_redirect off;
 35         proxy_set_header Host $host;
 36         proxy_set_header X-Real-IP $remote_addr;
 37         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
 38         proxy_set_header X-Forwarded-Host $server_name;
 39
 42   }
 43 }
```

**Comment by ildyria** [comment]
Would that help you https://lycheeorg.github.io/docs/faq.html#can-i-host-lychee-with-a-subpath-with-nginx-like-httpsexampledevlychee ?

**Comment by d7415** [comment]
I think the problem is that the Docker image is being sent www.myExistingSite.com/photos/index.php and so doesn't know what to do with it. You'll either need to do something like @ildyria [posted](#issuecomment-723473736) on the Docker side or rewrite the URL before you send it.

**Comment by dolie** [comment]
@ildyria As I use docker, this do not help.

Unfortunatly I decided to use another tool. I really need a step by step guide.  
Also, I use large pictures and big movies, so I need a tool that import them directly from the server (without the constraints of import from web client to server)

I will keep an eye on Lychee (features and docs), because the UI was really what I was looking for.

Thank you for your time and your help !

**Comment by d7415** [comment]
> @ildyria As I use docker, this do not help.

You can mount an alternative nginx.conf into the Docker image ( https://github.com/LycheeOrg/Lychee-Docker#advanced-configuration )

> Unfortunatly I decided to use another tool. I really need a step by step guide.

Fair enough. We provide step by step for most use cases (including "Lychee in a subdirectory" and "Lychee in Docker"). My general suggestion is that if you have a complicated use-case you should understand the tools because otherwise it *will* come crashing down.

> Also, I use large pictures and big movies, so I need a tool that import them directly from the server (without the constraints of import from web client to server)

Lychee has an "Import from Server" option which sounds like exactly this. It can also be triggered from a shell.
