### ISSUE TITLE
Backup possible?

### ISSUE THREAD

**Issue by Powerbock** [LycheeOrg/Lychee#778]
Hello

I want or need to reinstall Lychee. How can I transfer my images from one system to another system? How can I create a backup and restore it on the new system?

Kind Regards
Powerbock

**Comment by d7415** [comment]
https://lycheeorg.github.io/docs/faq.html#how-can-i-back-up-my-installation
https://lycheeorg.github.io/docs/faq.html#how-can-i-migrate-my-installation-to-a-new-host
