### ISSUE TITLE
Can't rename tag album

### ISSUE THREAD

**Issue by nickelsound** [LycheeOrg/Lychee#783]
### Detailed description of the problem [REQUIRED]
*The attempt to rename a tag album causes an error*

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Create a new tag album
2. Rename it
3. Refresh the list of albums
4. The name won't change
5. You will see this error in the browser console 
main.js?1604924851:1071 Uncaught TypeError: Cannot set property 'title' of undefined
    at Object.action [as fn] (main.js?1604924851:1071)
    at HTMLAnchorElement.t.buttons.action.o.onclick (main.js?1604924851:20)

### Output of the diagnostics  [REQUIRED]
*(Settings => Diagnostics or https://example.com/Diagnostics or `php artisan lychee:diagnostics`)*
Diagnostics
    -------
    Warning: You may experience problems when uploading a photo of large size. Take a look in the FAQ for details.
    Warning: Dropbox import not working. dropbox_key is empty.

    System Information
    --------------
    Lychee Version (git):            master (fab30a5) - Probably more than 30 commits behind master
    DB Version:                      4.0.7
    
    composer install:                --no-dev
    APP_ENV:                         production
    APP_DEBUG:                       false
    
    System:                          Linux
    PHP Version:                     7.4
    Max uploaded file size:          20M
    Max post size:                   100M
    MySQL Version:                   10.0.38-MariaDB-0ubuntu0.16.04.1
    
    Imagick:                         1
    Imagick Active:                  1
    Imagick Version:                 1673
    GD Version:                      2.3.0
    
    Lychee total space:              647.43 MB
    Upload folder space:             574.02 MB
    System total space:              48.29 GB
    System free space:               34.82 GB (72%)

    Config Information
    --------------
    version:                         040007
    check_for_updates:               0
    sorting_Photos_col:              takestamp
    sorting_Photos_order:            ASC
    sorting_Albums_col:              max_takestamp
    sorting_Albums_order:            ASC
    imagick:                         1
    skip_duplicates:                 0
    small_max_width:                 0
    small_max_height:                360
    medium_max_width:                1920
    medium_max_height:               1080
    lang:                            cz
    layout:                          0
    image_overlay:                   0
    image_overlay_type:              desc
    default_license:                 none
    compression_quality:             90
    full_photo:                      1
    delete_imported:                 0
    Mod_Frame:                       1
    Mod_Frame_refresh:               30
    thumb_2x:                        1
    small_2x:                        1
    medium_2x:                       1
    landing_page_enable:             0
    landing_owner:                   Pavel Lukes
    landing_title:                   Pavel Lukes
    landing_subtitle:                Fotky
    landing_facebook:                
    landing_flickr:                  
    landing_twitter:                 
    landing_instagram:               
    landing_youtube:                 
    landing_background:              dist/cat.jpg
    site_title:                      Fotky
    site_copyright_enable:           0
    site_copyright_begin:            2019
    site_copyright_end:              2019
    additional_footer_text:          
    display_social_in_gallery:       0
    public_search:                   0
    SL_enable:                       0
    SL_for_admin:                    0
    public_recent:                   0
    recent_age:                      1
    public_starred:                  0
    downloadable:                    0
    photos_wraparound:               1
    map_display:                     1
    zip64:                           1
    map_display_public:              0
    map_provider:                    Wikimedia
    force_32bit_ids:                 0
    map_include_subalbums:           0
    update_check_every_days:         3
    has_exiftool:                    0
    share_button_visible:            0
    import_via_symlink:              0
    has_ffmpeg:                      1
    location_decoding:               1
    location_decoding_timeout:       30
    location_show:                   1
    location_show_public:            0
    rss_enable:                      0
    rss_recent_days:                 7
    rss_max_items:                   100
    prefer_available_xmp_metadata:   0
    editor_enabled:                  1
    lossless_optimization:           0
    swipe_tolerance_x:               150
    swipe_tolerance_y:               250
    local_takestamp_video_formats:   .avi|.mov
    log_max_num_line:                1000

### Browser and system
Chromium: 86.0.4240.183 (64bit)
Windows 10

**Comment by nickelsound** [comment]
![2020-11-09 15_14_48-Window](https://user-images.githubusercontent.com/7345913/98552133-659e9180-229e-11eb-80c5-fb4ce6adf5ec.png)
Uncaught TypeError: Cannot set property 'title' of undefined
    at Object.action [as fn] (main.js?1604924851:1071)
    at HTMLAnchorElement.t.buttons.action.o.onclick (main.js?1604924851:20)
action @ main.js?1604924851:1071
t.buttons.action.o.onclick @ main.js?1604924851:20

**Comment by ildyria** [comment]
Fixed.
