### ISSUE TITLE
mail section  in .env

### ISSUE THREAD

**Issue by peteman52** [LycheeOrg/Lychee#790]
Does the mail-section in .env serve any purpose (if correctly filled of course) ?

MAIL_DRIVER=smtp
MAIL_HOST=
MAIL_PORT=
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_ENCRYPTION=

**Comment by ildyria** [comment]
> Does the mail-section in .env serve any purpose (if correctly filled of course) ?

No, not at the moment.
