### ISSUE TITLE
Installing Lychee from release: Setup via Webinterface

### ISSUE THREAD

**Issue by ghost** [LycheeOrg/Lychee#791]
### After I install Lychee from the newest release (described below) and go to https://lychee.domain.tld wich is linked to /var/www/Lychee (only for testing purposes; i know that it's unsecure) I get the following prompt:
```
403
This is the root directory and it MUST NOT BE PUBLICALLY ACCESSIBLE.
To access Lychee, go here.
```
That means, that Lychee is installed.
When I click on "go here" I'm redirected to https://lychee.domain.tld/install and now I get the following error message:
```
Not Found
The requested URL was not found on this server.
```

### Steps to reproduce the issue
Installation:
1.) cd /var/www
2.) wget https://github.com/LycheeOrg/Lychee/releases/download/v4.0.7/Lychee.zip
3.) unzip Lychee.zip
4.) cd Lychee
5.) chown -R www-data:www-data /var/www
6.) Setup vHost for Apache2 and SSL Certificate
7.) goto https://lychee.domain.tld

### Output of the diagnostics
```
# php artisan lychee:diagnostics

Diagnostics
-----------
Error: Database is behind file versions. Please apply the migration.
Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.
Warning: Pictures that are rotated lose their metadata! Please enable Imagick in settings to avoid that.
Error: username not set in database
Error: password not set in database
Error: sorting_Photos not set in database
Error: sorting_Albums not set in database
Error: imagick not set in database
Error: skip_duplicates not set in database
Error: check_for_updates not set in database
Error: version not set in database
Error: SQLSTATE[HY000] [1698] Access denied for user 'forge'@'localhost' (SQL: select `key`, `value`, `type_range` from `configs`)
Warning: Dropbox import not working. No property for dropbox_key.

System Information
------------------
Lychee Version (release):        4.0.7
DB Version:                      4.0.0

composer install:                --no-dev
APP_ENV:                         production
APP_DEBUG:                       false

System:                          Linux
PHP Version:                     7.4
Max uploaded file size:          2M
Max post size:                   8M
Unknown SQL Version:             unknown

Imagick:                         1
Imagick Active:                  key not found in settings
Imagick Version:                 1690
GD Version:                      2.2.5

Config Information
------------------
Error: SQLSTATE[HY000] [1698] Access denied for user 'forge'@'localhost' (SQL: select * from `configs` where `confidentiality` <= 2 order by `id` asc)
```

So, I know that I didn't create the database, but after all I've read now there should be a web installer after these steps?

**Comment by ildyria** [comment]
> but after all I've read now there should be a web installer after these steps?

Yes, you just mis-configured your apache part.

Link your lychee.domain.tld to `/var/www/Lychee/public` instead of `/var/www/Lychee` :)

**Comment by ildyria** [comment]
Also those two values:
```
Max uploaded file size:          2M
Max post size:                   8M
```
Are REALLY low, you may want to multiply the first one by 20 and the second one by 10. :)

**Comment by ildyria** [comment]
Aside from that you are doing pretty good. :+1:

**Comment by ghost** [comment]
Thank you :)

> Also those two values:
> 
> ```
> Max uploaded file size:          2M
> Max post size:                   8M
> ```
> 
> Are REALLY low, you may want to multiply the first one by 20 and the second one by 10. :)

You're right, I'll correct this

> > but after all I've read now there should be a web installer after these steps?
> 
> Yes, you just mis-configured your apache part.
> 
> Link your lychee.domain.tld to `/var/www/Lychee/public` instead of `/var/www/Lychee` :)

But this doesn't change the result. Now I'm directly redirected to https://lychee.domain.tld/install and getting the same error message:
```
Not Found

The requested URL was not found on this server.
```

EDIT:
That's how my /var/www/Lychee/public/ is looking like:
```
# ls -la public 
total 84
drwxr-xr-x  7 www-data www-data  4096 Oct  9 11:15 .
drwxr-xr-x 12 www-data www-data  4096 Nov 16 19:05 ..
drwxr-xr-x  3 www-data www-data  4096 Oct  9 11:15 dist
-rw-r--r--  1 www-data www-data 33412 Oct  9 11:15 favicon.ico
-rw-r--r--  1 www-data www-data  1097 Oct  9 11:15 .htaccess
drwxr-xr-x  2 www-data www-data  4096 Oct  9 11:15 img
-rw-r--r--  1 www-data www-data  2614 Oct  9 11:15 index.php
drwxr-xr-x  3 www-data www-data  4096 Oct  9 11:15 installer
-rw-r--r--  1 www-data www-data   270 Oct  9 11:15 robots.txt
drwxr-xr-x  2 www-data www-data  4096 Oct  9 11:15 sym
drwxr-xr-x  8 www-data www-data  4096 Oct  9 11:15 uploads
-rw-r--r--  1 www-data www-data   387 Oct  9 11:15 .user.ini
-rw-r--r--  1 www-data www-data  1193 Oct  9 11:15 web.config
```
And /var/www/Lychee/public/installer 
```
# ls -la public/installer 
total 12
drwxr-xr-x 3 www-data www-data 4096 Oct  9 11:15 .
drwxr-xr-x 7 www-data www-data 4096 Oct  9 11:15 ..
drwxr-xr-x 5 www-data www-data 4096 Oct  9 11:15 assets
```

**Comment by ildyria** [comment]
Okay, the fact that you are directly redirected to lychee.domain.tld/install is good news. :)

However because you are getting an error message, I guess it means that Rewrite mod is not enabled.
```apache
<VirtualHost *:80>
    Protocols h2 h2c http/1.1
    ServerName lychee.domain.tld

    DocumentRoot /var/www/Lychee/public

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
    <Directory "/var/www/Lychee">
    AllowOverride All
    </Directory>
</VirtualHost>
```

**Comment by ildyria** [comment]
PS: it is normal to not "find" some of the files. They are directly managed by lychee:

https://github.com/LycheeOrg/Lychee/blob/f6693e7974041714e898d2fee73ac0be25bbabba/routes/install.php#L26-L30

Basically what is happening, is upon reception:
1. Apache check if the file exists
2. if it does not exist, rewrite the URL as a query to index.php (thus hiding 404 error)
3. Index.php check if such virtual url exists and return the requested page or 404.

This is why we have the `public/.htaccess` taking care of it:
https://github.com/LycheeOrg/Lychee/blob/f6693e7974041714e898d2fee73ac0be25bbabba/public/.htaccess#L1-L21

**Comment by ghost** [comment]
It's working now :D

The `mod_rewrite` was already enabled.
The problem was that I've comletely forgotten the Apache Code Hardening before two years or so.
Therefor I changed added the following to ` /etc/apache2/conf-enabled/security.conf`:
```
<Directory />
AllowOverride None
Require all denied
</Directory>
```
So now your vHost including
```
    <Directory "/var/www/Lychee">
    AllowOverride All
    </Directory>
```
solved my problem.

So thank you a  lot, and sorry for this issue :/

**Comment by Cockhash** [comment]
And is there any documentation, about what to change in .env?

**Comment by ildyria** [comment]
> So thank you a lot, and sorry for this issue :/

No worries, as you can see we are pretty active on helping. :)
