### ISSUE TITLE
[Enhancement] Oauth client

### ISSUE THREAD

**Issue by haivala** [LycheeOrg/Lychee#792]
Could we use https://github.com/knpuniversity/oauth2-client-bundle or similar to login?
I haven't checked yet so I'll ask is this using symfony guard?

In my use case I would need to connect to symfony oauth server to login.

**Comment by ildyria** [comment]
This should be doable, but you will need to associate an ID to such users (0 being admin).
Also there is no such thing as `ID = 0` in the User table (in order to prevent someone else to log as admin obviously).
Admin username and passwords are stored in the config tables and both _protected_ by bcrypt.

**Comment by haivala** [comment]
the password is not needed and the id is not needed.

login happens in the another service and that authenticates the user in lychee. username can be the only thing to that is compared and used in the login. so if your username is admin in other service then you could login as admin

**Comment by ildyria** [comment]
As follows, "_Admin_" (in italic) is understood as a role, not as a username.

True, but you still need a local relationship between `username` and `id`.
The ID locally is what allows us to know who as ownership. :)

Note that the _Admin_ username **is not known**, actually we don't care what username you are using. Admin role is determined by `ID == 0`.

Login as admin is slightly different that login as a user:
https://github.com/LycheeOrg/Lychee/blob/f6693e7974041714e898d2fee73ac0be25bbabba/app/Http/Controllers/SessionController.php#L126-L147

Log as admin:
https://github.com/LycheeOrg/Lychee/blob/f6693e7974041714e898d2fee73ac0be25bbabba/app/ModelFunctions/SessionFunctions.php#L177-L186

Log as user:
https://github.com/LycheeOrg/Lychee/blob/f6693e7974041714e898d2fee73ac0be25bbabba/app/ModelFunctions/SessionFunctions.php#L150-L160

Additionally, I would still keep the username - password for _Admin_, as a backup solution. What I mean is that it should not be possible to disable login as _Admin_ user, however adding a secondary login option for the _Admin_ is totally thinkable.

**Comment by haivala** [comment]
Oauth Autohorization code workflow works like this (minus the secrets we need to define in both services)
1. client requests authentication which means lychee as whole service
2. server authenticates the service with the server user creds on the server
3. lychee then has access to server user entity and in this case it can be only the username
4. lychee gets the user json with the username from the server
5. lychee matches the username to lychee user
6. lychee then logs matched user in without any other questions (or creates a new account without or with random password)

So this does not need to take to account the ID thing nor how the login happens after the authentication as we can trust the username to be right one. of course we can pass any other info to lychee too (like the server side user id which we should do so that users at the server cannot change their account in lychee by changing their username. usually there is email check too)
We should not disable the normal login in any case so that if the oauth server is down we can still login. oauth would be just a button under the login form.

**Comment by ildyria** [comment]
So if I understood correctly:
```
                                          GitHub/Google
User                                        Facebook
 +        Authenticate himself with            +
 +------------------------------------------>  |
 |                                             |
 |                   Lychee                    |
 |                      +                      |
 |  Authenticate me     |                      |
 +--------------------> |                      |
 |  against GH/G/F      |    Who is            |
 |  with token "Oauth"  +--------------------> |
 |                      |    "Oauth"           |
 |                      |                      |
 |                      |                      |
 |                      |    "Oauth" is        |
 |                      +<---------------------+
 |                      |    user XYZ          |
 |                      |                      |
 |                      |                      v
```
```
 |                      |
 |               +------+-----+
 |               | search for |
 |               |username XYZ|
 |               | and get ID |
 |               +------+-----+
 |                      |
 | Okay you are logged  |
 +<---------------------+
 |  as XYZ with ID=...  |
 |                      |
 v                      v
```

> as we can trust the username to be right one

Why? why can't a user change his username afterwards and thus trick Lychee into thinking he is someone else?
> like the server side user id which we should do so that users at the server cannot change their account in lychee by changing their username. 

Okay then I am happier. :)

> We should not disable the normal login in any case so that if the oauth server is down we can still login. oauth would be just a button under the login form.

Yep, totally agree. :+1: 

PS: diagram made with [asciiflow](http://asciiflow.com/)

Implementation wise in the Lychee side, you will probably have to add a new table to make the link between {"username", "UUID", "Facebook/GH/..."} from your json return and the actual local user ID.

**Comment by d7415** [comment]
[This](https://en.wikipedia.org/wiki/OAuth#OpenID_vs._pseudo-authentication_using_OAuth) may be worth a read (yes, it's Wikipedia, but still).

**Comment by haivala** [comment]
> Laravel passport is built on top of the League OAuth2 server 

from: https://morioh.com/p/e411fb98492b
but apparently lychee auth system is custom made?

This is pretty good example on what I would actually need: https://github.com/MacsiDigital/laravel-oauth2-client

**Comment by ildyria** [comment]
> but apparently lychee auth system is custom made?

Yes, since v3 actually, this was necessary for legacy purposes so that users could migrate easily from v3 to v4:
- https://github.com/LycheeOrg/Lychee-v3
- https://github.com/electerious/Lychee

The auth system is not complex to be honest (cf above comment: https://github.com/LycheeOrg/Lychee/issues/792#issuecomment-729810380)

> This is pretty good example on what I would actually need: MacsiDigital/laravel-oauth2-client

Feel free to create a PR to add support for such authentication method. :)

**Comment by haivala** [comment]
Is this still the way to go or has the recent auth system modifications changed how this should be done?

**Comment by ildyria** [comment]
No, [this](https://github.com/LycheeOrg/Lychee/issues/792#issuecomment-729810380) is no longer the way to go.

https://laravel.com/docs/9.x/socialite should be used.
Thanks to our refactoring, it should also be rather easy to integrate as we now also use the `Auth` facade to login.

There is also a large variety of providers available here to integrate with Socialite: https://socialiteproviders.com/
https://socialiteproviders.com/about/#provider-issues

**Comment by ildyria** [comment]
@haivala 
FYI:

https://github.com/LycheeOrg/Lychee/assets/627094/f6c4c509-1280-478a-9162-776342b5626c
