### ISSUE TITLE
[Enhancement] Document how to use Lychee

### ISSUE THREAD

**Issue by berndbausch** [LycheeOrg/Lychee#804]
I know I am a choosing beggar, but while Lychee looks good, I have not found out how to use it. It currently runs in a Docker container on a small server.

Here are a few things that should be documented:

- How to make photos public after uploading them. In bulk, if possible.
- How to move photos to different albums (or put the same photo in several albums; I don't know if that feature exists). Also in bulk.
- How to share something. The share page says "Sharing list is empty!", and I don't know how to fill it.
- The typical or intended workflows

Since I don't believe in receiving/complaining without giving, I would be very happy to write such documentation. However, I currently don't know how to do the above things (I am slowly getting there by randomly left- and right-clicking on various pages). If these things can't be done, there needs to be some documentation what can be done, and how to do it. If such documentation exists already, I managed to miss it. It should be highlighted, for example by a HELP button in Lychee.

**Comment by ildyria** [comment]
- Documentation can be edited here, see Readme for instructions: https://github.com/LycheeOrg/Lycheeorg.github.io

> * How to make photos public after uploading them. In bulk, if possible.

1. Per album: make the album public - click on the eye in the top right.
2. Per picture: on the photo view, click on the eye in the top right.

Public album will be visible when not being logged. Public pictures needs to be shared via the `/view` link provided.

We recommend using method 1.

> * How to move photos to different albums (or put the same photo in several albums; I don't know if that feature exists). Also in bulk.

To move pictures, just right click on them. To move in bulk, you can select multiple pictures at once by keeping the CTRL key pressed. SHIFT key pressed if you want to make a range selection.

> * How to share something. The share page says "Sharing list is empty!", and I don't know how to fill it.

The share list only shows across users. Above the share list you have a form which allow you to select which album to which user.

> * The typical or intended workflows

**Basic**:

1. create a new album *A*.
2. make album public.
3. upload pictures in album *A*.

- Visitors can access pictures in *A* directly.

**Advanced 1**:

1. create a new album *A*, make it public & hidden.
2. go into album *A* and create a sub-album *B*, make it public.
3. stay in album *A* create second sub-album *C*, make it public.
4. upload pictures in sub-album *B*.
5. upload pictures in sub-album *C*.

- Visitors cannot see album *A*.
- Visitor with a direct link to album *A* can open album *A* and see and open album *B* and album *C*.
- Visitors with direct link to album *B* or album *C* can go back one level and see the content of album *A*, *B* and *C*.

**Advanced 2**:

1. create a new album *A*, do NOT make it public.
2. go into album *A* and create a sub-album *B*, make it public.
3. stay in album *A* create second sub-album *C*, make it public.
4. upload pictures in sub-album *B*.
5. upload pictures in sub-album *C*.

- Visitors cannot see album *A*.
- Visitors with direct link to album *B* or album *C* cannot go back one level and see the content of album *A*, they are limited to the content of album *B* (respectively *C*).

**Expert 1**:

1. create user Alpha.
2. create a new album *A*.
3. upload pictures in *A*.
4. in the sharing panel, select user Alpha, select album *A*, Share.
5. log out and log in as Alpha.

- Visitors cannot access *A*.
- User Alpha can see album *A*.
- User Alpha cannot upload pictures in *A*.

**Expert 2**:

1. create user Alpha.
2. create user Beta with upload rights.
3. log out and log in as Beta.
2. create a new album *A*.
3. upload pictures in *A*.
4. in the sharing panel, select user Alpha, select album *A*, Share.
5. log out and log in as Alpha.

- Visitors cannot access *A*.
- User Alpha can see album *A*.
- User Alpha cannot upload pictures in *A*.
- Admin can see everything.

**Comment by ildyria** [comment]
@berndbausch I gave you the requested information. Maybe now you can write the documentation as you proposed...

**Comment by ildyria** [comment]
@berndbausch any news?

**Comment by ildyria** [comment]
Author of this issue is a dick. Closing.
