### ISSUE TITLE
Debug newbie pi-user error 'Mbstring' & 'Gd'

### ISSUE THREAD

**Issue by macabongx** [LycheeOrg/Lychee#809]
With close to zero linux knowledge i followed couples different guides to reach to web UI installation stage. 
Im stuck at 'please fix the errors before going to the next step'. Which are 'Mbstring' and 'Gd'

### Output of the diagnostics
Diagnostics
-----------
Warning: Using 32 bit PHP, recommended upgrade to 64 bit
Error: sqlite db driver selected and PHP sqlite3 extension not activated
Warning: You may experience problems when uploading a photo of large size. Take a look in the FAQ for details.
Warning: You may experience problems when uploading a photos of large size. Take a look in the FAQ for details.
Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.
Warning: Pictures that are rotated lose their metadata! Please enable Imagick in settings to avoid that.
Error: username not set in database
Error: password not set in database
Error: sorting_Photos not set in database
Error: sorting_Albums not set in database
Error: imagick not set in database
Error: skip_duplicates not set in database
Error: check_for_updates not set in database
Error: version not set in database
Error: could not find driver (SQL: PRAGMA foreign_keys = ON;)
Warning: Dropbox import not working. No property for dropbox_key.

System Information
------------------
Lychee Version (git):            master (8da832e) - Data not in Cache
DB Version:                      4.0.0

composer install:                --no-dev
APP_ENV:                         production
APP_DEBUG:                       true

System:                          Linux
PHP Version:                     7.4
Max uploaded file size:          2M
Max post size:                   8M
Unknown SQL Version:             unknown

Imagick:                         1
Imagick Active:                  key not found in settings
Imagick Version:                 1690
GD Version:                      2.2.5

Config Information
------------------
Error: could not find driver (SQL: PRAGMA foreign_keys = ON;)
root@raspberrypi:/var/www/html/Lychee# 

### Browser and system
Lychee 4 installed on Raspberry Pi 4 model B 4GB ram. Stock Pi OS lite (no desktop).
Installed with composer, php, mariadb.
Headless-mode remoting using ipadOS with SSH client & safari browser.
Please help & thanks.

**Comment by d7415** [comment]
https://lycheeorg.github.io/docs/installation.html#server-requirements

**Comment by macabongx** [comment]
Thanks for quick reply. Im sorry i ran this but the issue is still there:

pi@raspberrypi:~ $ sudo apt-get install -y php-mbstring php-gd
Reading package lists... Done
Building dependency tree       
Reading state information... Done
php-gd is already the newest version (2:7.4+79+0~20201020.27+debian10~1.gbp95ec92).
php-mbstring is already the newest version (2:7.4+79+0~20201020.27+debian10~1.gbp95ec92).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by ildyria** [comment]
Can you restart your webserver? apache/nginx needs to reload the configuration. :)

**Comment by macabongx** [comment]
> Can you restart your webserver? apache/nginx needs to reload the configuration. :)

Yes i did but still, im new to all this to be honest. Mostly copy&paste guides:
 service apache2 restart

**Comment by d7415** [comment]
> hp-gd is already the newest version (2:7.4+79+0~20201020.27+debian10~1.gbp95ec92).
> php-mbstring is already the newest version (2:7.4+79+0~20201020.27+debian10~1.gbp95ec92).

That implies they were already there. Are you sure those are the dependencies missing?

**Comment by macabongx** [comment]
Probably the bug lies somewhere else. I will try to collect the guides that ive been following and see if you can spot any
Here is a screenshot: https://imgur.com/a/HSDxuzY
P/S:
$ service apache2 status
● apache2.service - The Apache HTTP Server
   Loaded: loaded (/lib/systemd/system/apache2.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2020-12-06 13:31:36 GMT; 9min ago
     Docs: https://httpd.apache.org/docs/2.4/
  Process: 826 ExecStart=/usr/sbin/apachectl start (code=exited, status=0/SUCCESS)
 Main PID: 830 (apache2)
    Tasks: 7 (limit: 4915)
   CGroup: /system.slice/apache2.service
           ├─830 /usr/sbin/apache2 -k start
           ├─831 /usr/sbin/apache2 -k start
           ├─832 /usr/sbin/apache2 -k start
           ├─833 /usr/sbin/apache2 -k start
           ├─834 /usr/sbin/apache2 -k start
           ├─835 /usr/sbin/apache2 -k start
           └─836 /usr/sbin/apache2 -k start

Dec 06 13:31:36 raspberrypi systemd[1]: Starting The Apache HTTP Server...
Dec 06 13:31:36 raspberrypi apachectl[826]: AH00558: apache2: Could not reliably determine the server'
Dec 06 13:31:36 raspberrypi systemd[1]: Started The Apache HTTP Server.
lines 1-19/19 (END)

**Comment by d7415** [comment]
I think we have a winner.

Apache / Lychee is using PHP8, but the modules you have installed are PHP7.4.

You'll either need to make apache use PHP7.4 (probably safer) or try to find those modules for PHP8 - should be `sudo apt install php8.0-mbstring php8.0-gd`

**Comment by ildyria** [comment]
but it says `PHP Version: 7.4` in the diagnostic

**Comment by macabongx** [comment]
D7415 is correct. I installed php 8.0. So i updated 8.0-mbstring and 8.0-Gd fixed the issue. but now i hit "500 - server error" on next page 'public/install/env'
Should we continue or close?

**Comment by ildyria** [comment]
Well.. Lychee is not prepared for Php 8 yet... We don't have the CI for it.

**Comment by macabongx** [comment]
Ouch sorry i over update/install stuff.
How can i reverse to 7.4

**Comment by d7415** [comment]
> How can i reverse to 7.4

Try `sudo apt remove php8.0` You may also need to install 7.4, but it looks like that's probably there.

**Comment by macabongx** [comment]
Your right lol. How silly i am
php -v
PHP 7.4.13 (cli) (built: Nov 30 2020 20:40:09) ( NTS )
Thanks for your time. You guys are the best. I will try again tonight lets hope.

**Comment by ildyria** [comment]
> Ouch sorry i over update/install stuff.
> How can i reverse to 7.4

No worries, I would like to make Lychee php 8 compatible but some dependencies are stuck in php 7.4. :(
