### ISSUE TITLE
[Enhancement] Add troubleshooting information to getting started guide

### ISSUE THREAD

**Issue by ChrLau** [LycheeOrg/Lychee#813]
Hi, I just finished setting up Lychee via the Release method. So far, so good. However as it is a relatively new rootserver the PHP SQLite module was missing. Hence I only got an HTTP 500 "Server error" when I tried to access Lychee.
As the error produced just the 1 log entry in the error.log from Apache and nothing in PHP logfile it was a little bit hard to understand where the error is originating.

It would have been very helpful to have a short troubleshooting section in the Installation documentation at https://lycheeorg.github.io/docs/installation.html which at least mentions the "artisan lychee:diagnostics" command, for people not familiar with the PHP Laravel Framework. ;-)
As this command does check for dependencies (and other common errors like wrong file permissions, etc.)

On the other hand I was a little bit baffled that a PHP missing module, which isn't required to display the install dialogue, leads to an HTTP 500 error. Most applications do check for necessary dependencies before the installation.

**Comment by ildyria** [comment]
> On the other hand I was a little bit baffled that a PHP missing module, which isn't required to display the install dialogue, leads to an HTTP 500 error. Most applications do check for necessary dependencies before the installation.

One of the thing we check to know if we need to display the install dialog is whether the `config` table is available or not. :frowning_face: 

But I am surprised that this crashes so fast. O.o

That being said we do have a FAQ:
https://lycheeorg.github.io/docs/faq.html#lychee-is-not-working

But also feel free to propose a PR for our documentation here: https://github.com/LycheeOrg/Lycheeorg.github.io

**Comment by ildyria** [comment]
Could be interesting to have fail safe for this case. :thinking:

**Comment by ChrLau** [comment]
> > On the other hand I was a little bit baffled that a PHP missing module, which isn't required to display the install dialogue, leads to an HTTP 500 error. Most applications do check for necessary dependencies before the installation.
> 
> One of the thing we check to know if we need to display the install dialog is whether the `config` table is available or not. 
> But I am surprised that this crashes so fast. O.o
> 
Yeah, when I found out, I was surprised too. Isn't it possible to move the check into the installation dialogue itself?

> That being said we do have a FAQ:
> https://lycheeorg.github.io/docs/faq.html#lychee-is-not-working

Oh... I... Uhm.. Didn't see that. Sorry :-(

**Comment by ildyria** [comment]
> Yeah, when I found out, I was surprised too. Isn't it possible to move the check into the installation dialogue itself?

The installation dialog has the check.
But it is before the installation dialog that the check should fail but be gracefully catch.
