### ISSUE TITLE
Installation loop

### ISSUE THREAD

**Issue by homer276** [LycheeOrg/Lychee#817]
Hi,

I am trying to install Lychee 4.0.8 via webinstallation on my Debian dedicated server. Debian Vers. 9.13 PHP 7.4.13
The installation steps 1,2,3,4 pass without problem. All required items have been found as you can see on the picture.
When clicking on install I'm ending up on page 1. and again and again
![Lychee 4](https://user-images.githubusercontent.com/48461825/102231940-d4e75100-3eee-11eb-8580-fcbc0dd57f65.png)
![Bildschirmfoto 2020-12-15 um 16 08 26](https://user-images.githubusercontent.com/48461825/102232766-d1a09500-3eef-11eb-82c7-634e84dde4ec.png)
![Bildschirmfoto 2020-12-15 um 16 08 05](https://user-images.githubusercontent.com/48461825/102232784-d5ccb280-3eef-11eb-8eb6-9fc9432defc2.png)

I guess I'm overlooking something here. Any further info required ?

Tks

**Comment by ildyria** [comment]
Try with this in your `.env`:
```
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
```

We are actually missing the last screen where the migration is being applied... Could you provide it too?

**Comment by homer276** [comment]
Hi,
tks , but the last step is ignored . 1,2,3 &  4 and we are back to 1
No migration and no error message, at least not on the screen

Tks

**Comment by homer276** [comment]
Furthermore I just noticed that when I try to run "php artisan lychee:diagnostics"
I get this
Quote
In BusServiceProvider.php line 51:
                                
  syntax error, unexpected ')'  
                                
Unquote

But not sure if this is the reason at all

**Comment by ildyria** [comment]
> Furthermore I just noticed that when I try to run "php artisan lychee:diagnostics"
> I get this
> Quote
> In BusServiceProvider.php line 51:
> 
> syntax error, unexpected ')'
> 
> Unquote
> 
> But not sure if this is the reason at all

That is absolutely NOT normal.

~~Okay... Seems like Diagnostic is broken some way.~~ Is not broken on Master.

**Comment by ildyria** [comment]
> last step is ignored . 1,2,3 & 4

What do you mean by ignored?

**Comment by ildyria** [comment]
You don't get such screen: 
![2020-12-15_5760x2160_18:17:50](https://user-images.githubusercontent.com/627094/102249131-4ed50580-3f02-11eb-9351-9a158409274f.png)

**Comment by homer276** [comment]
Correct, no such screen. It jumps back to page 1

**Comment by homer276** [comment]
Hi,
after some googeling and thinking I removed the last comma in this line : ......config('queue.batching.table', 'job_batches'),
After that it was working 
1st php artisan key:generate and
2nd php artisan migrate

Diagnostics from the server ( via SSH ) shows PHP 7.2, but diagnostics from within Lychee shows PHP 7.4
[Diagnostics via console.txt](https://github.com/LycheeOrg/Lychee/files/5701439/Diagnostics.via.console.txt)

System Information from Lychee webpage
    --------------
    Lychee Version (release):        4.0.8
    DB Version:                      4.0.8
    
    composer install:                --no-dev
    APP_ENV:                         production
    APP_DEBUG:                       false
    
    System:                          Linux
    PHP Version:                     7.4
    Max uploaded file size:          16M
    Max post size:                   8M
    MySQL Version:                   10.1.47-MariaDB-0+deb9u1
    
    Imagick:                         1
    Imagick Active:                  1
    Imagick Version:                 1687
    GD Version:                      bundled (2.1.0 compatible)

All a bit odd, but it's working now

Tks

**Comment by d7415** [comment]
> Diagnostics from the server ( via SSH ) shows PHP 7.2, but diagnostics from within Lychee shows PHP 7.4

That means you have php7.2-cli set as default for the cli, but php7.4 for whichever web server you're using.

> after some googeling and thinking I removed the last comma in this line : ......config('queue.batching.table', 'job_batches'),

That's not our code. I haven't checked our bundled stuff.

Edit: Yup. `Lychee/vendor/laravel/framework/src/Illuminate/Bus/BusServiceProvider.php:50` and it's only a problem with PHP 7.2 https://github.com/laravel/framework/pull/34435 . ~~@ildyria Does the installer end up calling CLI php?~~ It doesn't look like we're ever calling php from the CLI, so I'm unclear what's caused that. Maybe artisan does that by itself?

**Comment by homer276** [comment]
Hi,

I downloaded everything from here (
https://github.com/LycheeOrg/Lychee/releases )



Am Mi., 16. Dez. 2020 um 11:28 Uhr schrieb Martin Stone <
notifications@github.com>:
