### ISSUE TITLE
SQLSTATE[22P02]: Invalid text representation

### ISSUE THREAD

**Issue by tnodev** [LycheeOrg/Lychee#821]
### Detailed description of the problem [REQUIRED]
Trying to upload a photo, then error

    2020-12-17 07:39:56 -- error   -- App\ModelFunctions\PhotoFunctions::save -- 814 -- Something went wrong, error 22P02, SQLSTATE[22P02]: Invalid text representation: 7 ERREUR:  syntaxe en entrée invalide pour le type numeric : « undef » (SQL: insert into "photos" ("id", "checksum", "title", "url", "description", "tags", "width", "height", "type", "size", "iso", "aperture", "make", "model", "lens", "shutter", "focal", "takestamp", "latitude", "longitude", "altitude", "imgDirection", "location", "livePhotoContentID", "public", "star", "album_id", "owner_id", "thumb2x", "thumbUrl", "medium", "medium2x", "small", "small2x", "updated_at", "created_at") values (16081907946012, 4d264cc0afe04a78fceaea60f3de46c05d41047f, DSCN7229, b4166da96dcf0c5090fcc7f2deb73e00.jpg, , , 4608, 3456, image/jpeg, 3.4 MB, 100, f/3.0, NIKON, COOLPIX P510, , 1/800 s, 4 mm, 2019-03-24 13:06:39, 43.29672, 5.360755, -46.6, undef, , ?, 0, 0, 16081515596097, 0, 1, b4166da96dcf0c5090fcc7f2deb73e00.jpeg, 1440x1080, 2880x2160, 480x360, 960x720, 2020-12-17 07:39:56, 2020-12-17 07:39:56) returning "id")

### Output of the diagnostics  [REQUIRED]
Diagnostics
    -------
    Info: Latest version of PHP is 7.4
    Warning: You may experience problems when uploading a photo of large size. Take a look in the FAQ for details.
    Warning: Dropbox import not working. dropbox_key is empty.

    System Information
    --------------
    Lychee Version (git):            No git data found.
    DB Version:                      4.0.8
    
    composer install:                --no-dev
    APP_ENV:                         production
    APP_DEBUG:                       false
    
    System:                          Linux
    PHP Version:                     7.3
    Max uploaded file size:          20M
    Max post size:                   100M
    PostgreSQL Version:              PostgreSQL 11.9 (Debian 11.9-0+deb10u1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
    
    Imagick:                         1
    Imagick Active:                  1
    Imagick Version:                 1690
    GD Version:                      2.2.5

    Config Information
    --------------
    version:                         040008
    check_for_updates:               0
    sorting_Photos_col:              takestamp
    sorting_Photos_order:            ASC
    sorting_Albums_col:              max_takestamp
    sorting_Albums_order:            ASC
    imagick:                         1
    skip_duplicates:                 0
    small_max_width:                 0
    small_max_height:                360
    medium_max_width:                1920
    medium_max_height:               1080
    lang:                            fr
    layout:                          1
    image_overlay:                   1
    image_overlay_type:              desc
    default_license:                 none
    compression_quality:             90
    full_photo:                      1
    delete_imported:                 0
    Mod_Frame:                       1
    Mod_Frame_refresh:               30
    thumb_2x:                        1
    small_2x:                        1
    medium_2x:                       1
    landing_page_enable:             0
    landing_owner:                   John Smith
    landing_title:                   John Smith
    landing_subtitle:                Cats, Dogs & Humans Photography
    landing_facebook:                https://www.facebook.com/JohnSmith
    landing_flickr:                  https://www.flickr.com/JohnSmith
    landing_twitter:                 https://www.twitter.com/JohnSmith
    landing_instagram:               https://instagram.com/JohnSmith
    landing_youtube:                 https://www.youtube.com/JohnSmith
    landing_background:              dist/cat.jpg
    site_title:                      Lychee v4
    site_copyright_enable:           1
    site_copyright_begin:            2019
    site_copyright_end:              2019
    additional_footer_text:          
    display_social_in_gallery:       0
    public_search:                   0
    SL_enable:                       0
    SL_for_admin:                    0
    public_recent:                   0
    recent_age:                      1
    public_starred:                  0
    downloadable:                    0
    photos_wraparound:               1
    map_display:                     1
    zip64:                           1
    map_display_public:              0
    map_provider:                    Wikimedia
    force_32bit_ids:                 0
    map_include_subalbums:           0
    update_check_every_days:         3
    has_exiftool:                    1
    share_button_visible:            0
    import_via_symlink:              0
    has_ffmpeg:                      1
    location_decoding:               0
    location_decoding_timeout:       30
    location_show:                   1
    location_show_public:            1
    rss_enable:                      0
    rss_recent_days:                 7
    rss_max_items:                   100
    prefer_available_xmp_metadata:   0
    editor_enabled:                  1
    lossless_optimization:           0
    swipe_tolerance_x:               150
    swipe_tolerance_y:               250
    local_takestamp_video_formats:   .avi|.mov
    log_max_num_line:                1000
    unlock_password_photos_with_url_param: 0

### Browser and system
Firefox - ubuntu 20.04

**Comment by tnodev** [comment]
With this photo
![DSCN7229](https://user-images.githubusercontent.com/1222321/102458481-99f73180-4044-11eb-8f84-65e3e6f050ba.jpg)

**Comment by tnodev** [comment]
| | 10) GPSImgDirection = undef (0/0)

**Comment by tnodev** [comment]
`$ exiftool -GPSImgDirection= DSCN7229.jpg
    1 image files updated
`
exiftool resolve the problem

**Comment by tmp-hallenser** [comment]
PR of php-exif handles now the case of non-numerical image directions.
