### ISSUE TITLE
[Enhancement] Don't require new PHP Versions too early

### ISSUE THREAD

**Issue by ghost** [LycheeOrg/Lychee#823]
I see the requirement for PHP 7.4. 
Common LTS Versions of server OS (e.g. Ubuntu Server 18.04) don't ship with this version but are still used frequently in productive systems. I request for future releases of this fine software to support at leat LTS Unix OS for a longer time period.

**Comment by ghost** [comment]
I see! PHP 7.2 is dead since 30.11.2020 (d436ed7146714f65ee4e713315bcaf6a2ac9fec3). So sorry for disturbing. I should upgrade my installations anyway.

**Comment by ildyria** [comment]
No as we do not support non-actively maintained versions of PHP.
See here: https://www.php.net/supported-versions.php

You can install PHP 7.4 on older version of e.g. Ubuntu.
```
sudo apt-get update
sudo apt -y install software-properties-common
sudo add-apt-repository ppa:ondrej/php
sudo apt-get update
sudo apt -y install php7.4
```

Additionally, moving forward in PHP allows us to benefits from the new features (e.g. arrow functions) and improve the quality of our code (via type checking).

**Comment by ildyria** [comment]
We do not support PHP 8 yet as the dependency chain (some composer packages) does not support it either. But it will be added at some point.
