### ISSUE TITLE
Secure and HttpOnly cookie causes HTTP 400 on Albums::get

### ISSUE THREAD

**Issue by joszz** [LycheeOrg/Lychee#827]
If I add the following header in my Apache config
`Header always edit Set-Cookie ^(.*)$ "$1;HttpOnly;Secure;SameSite=strict"`

I get a HTTP 400 code when "Albums::get" is called.
The response of that call contains 
`{"error":"Session timed out"}`

**Comment by ildyria** [comment]
I don't know why you want to do that but it is not needed as this is already taken care of by us:
https://github.com/LycheeOrg/Lychee/blob/27e4428786c2cacface06c8986d62db02ee0dfaf/config/session.php#L172-L196

Also by forcing HttpOnly on every cookies, you are shooting yourself in the foot as this prevent Javascript to read the XRSF token which we need to send along to any request to the server.

**Conclusion: don't add the following header in Apache.**

Also we have the secure header plugin enabled with the following configuration: 
https://github.com/LycheeOrg/Lychee/blob/master/config/secure-headers.php
