### ISSUE TITLE
Album name not correct displayed in confirmation popup when moving a newly created album

### ISSUE THREAD

**Issue by bastantoine** [LycheeOrg/Lychee#828]
### Detailed description of the problem

When you want to move a newly created album into another one, the confirmation popup shown doesn't have the name of the albums, but _Untilted_ instead (note the typo as well 😄).

### Steps to reproduce the issue
**Steps to reproduce the behavior:**

1. Create a new album
2. Go back to parent
3. Create another album
4. Go back to parent
5. Try to move one of the newly created into the other

**Screenshots**
Note the two albums in the screenshot below: _test1_ and _test2_. I just created them, and this is the popup shown when I try to move _test2_ into _test1_.
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/8548006/102976567-0caf5380-4502-11eb-8c9b-ae925bf385a2.png">

### Output of the diagnostics

    Diagnostics
    -------
    Info: Latest version of PHP is 7.4
    Warning: You may experience problems when uploading a photo of large size. Take a look in the FAQ for details.
    Warning: Dropbox import not working. dropbox_key is empty.

    System Information
    --------------
    Lychee Version (git):            No git data found.
    DB Version:                      4.0.8
    
    composer install:                --no-dev
    APP_ENV:                         production
    APP_DEBUG:                       false
    
    System:                          Linux
    PHP Version:                     7.3
    Max uploaded file size:          20M
    Max post size:                   100M
    MySQL Version:                   10.5.8-MariaDB-1:10.5.8+maria~focal
    
    Imagick:                         1
    Imagick Active:                  1
    Imagick Version:                 1690
    GD Version:                      2.2.5

    Config Information
    --------------
    version:                         040008
    check_for_updates:               0
    sorting_Photos_col:              takestamp
    sorting_Photos_order:            ASC
    sorting_Albums_col:              title
    sorting_Albums_order:            ASC
    imagick:                         1
    skip_duplicates:                 0
    small_max_width:                 0
    small_max_height:                360
    medium_max_width:                1920
    medium_max_height:               1080
    lang:                            en
    layout:                          1
    image_overlay:                   1
    image_overlay_type:              desc
    default_license:                 none
    compression_quality:             90
    full_photo:                      1
    delete_imported:                 0
    Mod_Frame:                       1
    Mod_Frame_refresh:               30
    thumb_2x:                        1
    small_2x:                        1
    medium_2x:                       1
    landing_page_enable:             0
    landing_owner:                   ***
    landing_title:                   ***
    landing_subtitle:                Cats, Dogs & Humans Photography
    landing_facebook:                https://www.facebook.com/JohnSmith
    landing_flickr:                  https://www.flickr.com/JohnSmith
    landing_twitter:                 https://www.twitter.com/JohnSmith
    landing_instagram:               https://instagram.com/JohnSmith
    landing_youtube:                 https://www.youtube.com/JohnSmith
    landing_background:              dist/cat.jpg
    site_title:                      ***
    site_copyright_enable:           1
    site_copyright_begin:            2017
    site_copyright_end:              2020
    additional_footer_text:          
    display_social_in_gallery:       0
    public_search:                   0
    SL_enable:                       0
    SL_for_admin:                    0
    public_recent:                   0
    recent_age:                      1
    public_starred:                  0
    downloadable:                    0
    photos_wraparound:               1
    map_display:                     0
    zip64:                           1
    map_display_public:              0
    map_provider:                    Wikimedia
    force_32bit_ids:                 0
    map_include_subalbums:           0
    update_check_every_days:         3
    has_exiftool:                    1
    share_button_visible:            0
    import_via_symlink:              0
    has_ffmpeg:                      1
    location_decoding:               0
    location_decoding_timeout:       30
    location_show:                   1
    location_show_public:            0
    rss_enable:                      0
    rss_recent_days:                 7
    rss_max_items:                   100
    prefer_available_xmp_metadata:   0
    editor_enabled:                  1
    lossless_optimization:           0
    swipe_tolerance_x:               150
    swipe_tolerance_y:               250
    local_takestamp_video_formats:   .avi|.mov
    log_max_num_line:                1000
    unlock_password_photos_with_url_param: 0

### Browser and system
macOS Big Sur 11.0.1
Tested on
- Safari 14.0.1
- Chrome 87.0.4280.88

**Comment by kamil4** [comment]
This is actually not limited to newly created albums. Whenever you make any significant edits to your albums, including uploading a new picture or deleting an existing one, this will be triggered for _any_ album moves, and probably some other operations as well.

The underlying reason is that whenever we make any significant changes to the albums, we drop the front end's main album tree data structure (`albums.json` gets set to `null`) since it's no longer current, but we don't immediately fetch a new copy from the server. We postpone that potentially expensive reload until the user navigates back to the top level.

This causes all sorts of little or not-so-little issues, such as the one you found, and I've always hated that aspect of the front end. Fixing this properly will require a major surgery though, I'm afraid, and given @ildyria's appetite for rewriting the front end, I'm not sure if rearchitecting the current one would be worth it...

**Comment by ildyria** [comment]
> I'm afraid, and given @ildyria's appetite for rewriting the front end, I'm not sure if rearchitecting the current one would be worth it...

Lol

**Comment by nagmat84** [comment]
@LycheeOrg/reviewers I just came across this old bug and I had a deja-vu. I don't remember when and how, but I have the feeling as if I had repaired this problem during one of the big refactorings. Probably not all instances of the problem, but most of them.

**Comment by kamil4** [comment]
Yes, you definitely improved it when it comes to source albums. The destinations may still be screwed up, but that's not easily fixable without a larger refactoring.
