### ISSUE TITLE
App\Image\ImagickHandler::crop -- 170 -- UnableToOpenBlob

### ISSUE THREAD

**Issue by sunosv** [LycheeOrg/Lychee#844]
When I upload a video , format mp4  
log give me this error: UnableToOpenBlob
But not every video can't successfully upload。
I want to know where did go wrong?
or just video not supported

Video info：
`Format                         : MPEG-4'
Format profile                 : 3GPP Media Release 4
Codec ID                       : 3gp4 (3gp4/3gp5/3g2a)
File size                      : 4.98 MiB
Duration                       : 7 s 713 ms
Overall bit rate               : 5 412 kb/s`

and logs
`2020-12-31 23:42:47 -- error   -- App\Image\ImagickHandler::crop -- 170 -- UnableToOpenBlob 'C:/Users/ADMINI~1/AppData/Local/Temp/2/magick-7624nxVcuqIf2H04.pam': No such file or directory @ error/blob.c/OpenBlob/3315
    2020-12-31 23:42:47 -- notice  -- App\ModelFunctions\PhotoFunctions::createThumb -- 617 -- Photo URL is d6605df56b0cb0acfedc2a5f29a66039.mp4
    2020-12-31 23:34:48 -- error   -- App\Image\ImagickHandler::crop -- 170 -- UnableToOpenBlob 'C:/Users/ADMINI~1/AppData/Local/Temp/2/magick-8004g0kEjJ9OmTkw.pam': No such file or directory @ error/blob.c/OpenBlob/3315
    2020-12-31 23:34:46 -- notice  -- App\ModelFunctions\PhotoFunctions::createThumb -- 617 -- Photo URL is 27b4def4a503395d07a2b4daccf635f5.mp4`

Powershell:
`In GdHandler.php line 286:`

 ` Argument 2 passed to App\Image\GdHandler::createImage() must be of the type int, null given, called in O:\Web\WWW\l
  ychee\app\Image\GdHandler.php on line 172`

`Diagnostics
    -------
    Warning: Dropbox import not working. dropbox_key is empty.

    System Information
    --------------
    Lychee Version (release):        4.1.0
    DB Version:                      4.1.0
    
    composer install:                --no-dev
    APP_ENV:                         production
    APP_DEBUG:                       true
    
    System:                          WINNT
    PHP Version:                     7.4
    Max uploaded file size:          10000M
    Max post size:                   10000M
    MySQL Version:                   5.7.26
    
    Imagick:                         1
    Imagick Active:                  1
    Imagick Version:                 1799
    GD Version:                      bundled (2.1.0 compatible)

    Config Information
    --------------
    version:                         040100
    check_for_updates:               0
    sorting_Photos_col:              takestamp
    sorting_Photos_order:            ASC
    sorting_Albums_col:              max_takestamp
    sorting_Albums_order:            ASC
    imagick:                         1
    skip_duplicates:                 0
    small_max_width:                 0
    small_max_height:                360
    medium_max_width:                1920
    medium_max_height:               1080
    lang:                            简体中文
    layout:                          1
    image_overlay:                   1
    image_overlay_type:              desc
    default_license:                 none
    compression_quality:             90
    full_photo:                      1
    delete_imported:                 0
    Mod_Frame:                       1
    Mod_Frame_refresh:               30
    thumb_2x:                        1
    small_2x:                        1
    medium_2x:                       1
    landing_page_enable:             0
    landing_owner:                   John Smith
    landing_title:                   John Smith
    landing_subtitle:                Cats, Dogs & Humans Photography
    landing_facebook:                https://www.facebook.com/JohnSmith
    landing_flickr:                  https://www.flickr.com/JohnSmith
    landing_twitter:                 https://www.twitter.com/JohnSmith
    landing_instagram:               https://instagram.com/JohnSmith
    landing_youtube:                 https://www.youtube.com/JohnSmith
    landing_background:              dist/cat.jpg
    site_title:                      Lychee v4
    site_copyright_enable:           1
    site_copyright_begin:            2019
    site_copyright_end:              2019
    additional_footer_text:          
    display_social_in_gallery:       0
    public_search:                   0
    SL_enable:                       0
    SL_for_admin:                    0
    public_recent:                   0
    recent_age:                      1
    public_starred:                  0
    downloadable:                    0
    photos_wraparound:               1
    map_display:                     0
    zip64:                           1
    map_display_public:              0
    map_provider:                    Wikimedia
    force_32bit_ids:                 0
    map_include_subalbums:           0
    update_check_every_days:         3
    has_exiftool:                    0
    share_button_visible:            0
    import_via_symlink:              0
    has_ffmpeg:                      1
    location_decoding:               0
    location_decoding_timeout:       30
    location_show:                   1
    location_show_public:            0
    rss_enable:                      0
    rss_recent_days:                 7
    rss_max_items:                   100
    prefer_available_xmp_metadata:   0
    editor_enabled:                  1
    lossless_optimization:           0
    swipe_tolerance_x:               150
    swipe_tolerance_y:               250
    local_takestamp_video_formats:   .avi|.mov
    log_max_num_line:                1000
    unlock_password_photos_with_url_param: 0
    nsfw_visible:                    1
    nsfw_blur:                       0
    nsfw_warning:                    0
    nsfw_warning_admin:              0`

**Comment by ildyria** [comment]
Video is supported.

But too me it looks more like a configuration problem on your side, especially given the logs. This indicates that you are using Windows and to be very fair, I have never used Lychee in a windows environment... :/

**Comment by sunosv** [comment]
> Video is supported.
> 
> But too me it looks more like a configuration problem on your side, especially given the logs. This indicates that you are using Windows and to be very fair, I have never used Lychee in a windows environment... :/

It has been working on windows for two days, I didn't find too many problems. last issue you helped me to find it. And I Manually add ffprobe path on windows, and it worked.
so now I want to ask you again   helping me to find it and get it right.

**Comment by ildyria** [comment]
Okay, so from what I read, it seems that you are trying to use imagick/GD our IMAGE handlers on a VIDEO file. This is not how it is supposed to work. The expected behavior is if it is a video is :

1. extract a frame from the video
2. use that frame to build the thumbnails.

I don't know what it is going on, but this does not seem to be the case here.

**Comment by sunosv** [comment]
> Okay, so from what I read, it seems that you are trying to use imagick/GD our IMAGE handlers on a VIDEO file. This is not how it is supposed to work. The expected behavior is if it is a video is :
> 
> 1. extract a frame from the video
> 2. use that frame to build the thumbnails.
> 
> I don't know what it is going on, but this does not seem to be the case here.

also, I converted the video to MP4 format and uploaded it again successfully.
Because I compared the successful video format with the failed one, and I  found out that  the two type video  Codec ID  is different. failed video  Codec ID  is "3gp4" .

**Comment by kamil4** [comment]
Could you make available for us a sample video file that triggers the issue? We can't really make progress if we can't reproduce it on our systems. Thanks!

**Comment by sunosv** [comment]
> Could you make available for us a sample video file that triggers the issue? We can't really make progress if we can't reproduce it on our systems. Thanks!

Is it because the video format is not supported?    Maybe mp4 container format dose not support raw pcm audio When ffmpeg deal with the video file?

[https://stackoverflow.com/questions/17651975/unable-to-store-pcm-audio-in-mp4-container-file](url)




video details

**General
Format                                   : XAVC
Codec ID                                 : XAVC (XAVC/mp42/iso2)
File size                                : 44.0 MiB
Duration                                 : 6 s 240 ms
Overall bit rate mode                    : Variable
Overall bit rate                         : 59.2 Mb/s
Encoded date                             : UTC 2020-05-24 23:04:00
Tagged date                              : UTC 2020-05-24 23:04:00

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L5.1
Format settings                          : CABAC / 2 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 2 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 6 s 240 ms
Bit rate mode                            : Variable
Bit rate                                 : 57.3 Mb/s
Maximum bit rate                         : 60.0 Mb/s
Width                                    : 3 840 pixels
Height                                   : 2 160 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 25.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.276
Stream size                              : 42.6 MiB (97%)
Encoded date                             : UTC 2020-05-24 23:04:00
Tagged date                              : UTC 2020-05-24 23:04:00
Color range                              : Full
Codec configuration box                  : avcC

Audio
ID                                       : 2
Format                                   : PCM
Format settings                          : Big / Signed
Codec ID                                 : twos
Duration                                 : 6 s 240 ms
Bit rate mode                            : Constant
Bit rate                                 : 1 536 kb/s
Channel(s)                               : 2 channels
Sampling rate                            : 48.0 kHz
Bit depth                                : 16 bits
Stream size                              : 1.14 MiB (3%)
Encoded date                             : UTC 2020-05-24 23:04:00
Tagged date                              : UTC 2020-05-24 23:04:00**

**Comment by kamil4** [comment]
I don't want to speculate what might be going on without attempting to reproduce the problem in my environment first.

Again, as I had requested in my previous message, please upload the problematic video file to some file sharing service and send us the URL so that we can properly investigate what's going on here.

**Comment by sunosv** [comment]
> I don't want to speculate what might be going on without attempting to reproduce the problem in my environment first.
> 
> Again, as I had requested in my previous message, please upload the problematic video file to some file sharing service and send us the URL so that we can properly investigate what's going on here.
here, video download link
[https://drive.google.com/file/d/19QAL7mXiRkgKVboPnduLUN7bD5Joie3J/view?usp=sharing](url)

**Comment by kamil4** [comment]
Thanks! Unfortunately, that link appears to be locked (instead of seeing the video file, I see a form to manually request access).

**Comment by sunosv** [comment]
> Thanks! Unfortunately, that link appears to be locked (instead of seeing the video file, I see a form to manually request access).

It is google drive, still can't download the video file ?

**Comment by sunosv** [comment]
> Thanks! Unfortunately, that link appears to be locked (instead of seeing the video file, I see a form to manually request access).

could you try again ? I think now it could be downloading.

**Comment by sunosv** [comment]
> I don't want to speculate what might be going on without attempting to reproduce the problem in my environment first.
> 
> Again, as I had requested in my previous message, please upload the problematic video file to some file sharing service and send us the URL so that we can properly investigate what's going on here.

I have more info on the windows environment.
When I use power shell to sync the same video, it shows:

**Start syncing.
Status: o:\2: 0%
Status: o:\2: 100%
Status: o:\2/test/: 0%

In GdHandler.php line 286:

  Argument 2 passed to App\Image\GdHandler::createImage() must be of the type int, null given, called in O:\Web\WWW\l
  ychee\app\Image\GdHandler.php on line 172**

---------------------------------------------------

other photo or video(mov;mp4) are ok,  except the video  file that I gave you.

**Comment by kamil4** [comment]
Thanks, download works now! For me the uploading works, but the extraction of a video frame for the thumbnail does not. I'll investigate in the next few days what's going on here.

**Comment by sunosv** [comment]
> Thanks, download works now! For me the uploading works, but the extraction of a video frame for the thumbnail does not. I'll investigate in the next few days what's going on here.

Thanks.

**Comment by kamil4** [comment]
I had a look and the problem is that the MIME type of this file is reported as generic `application/octet-stream` for some reason. This causes `PHPExif\Adapter\FFprobe::getExifFromFile()` to bail out early without doing anything, even though ffprobe itself handles that file just fine. @tmp-hallenser -- any ideas?

**Comment by tmp-hallenser** [comment]
We already have a mimetype overwrite in the function for mpeg; we could do the same for this one (but additionally check the file extension compared to the mpeg case)

Off topic: we still using Travis for php-exif; If someone has some time, migration to GitHub actions would be helpful.

**Comment by ildyria** [comment]
> migration to GitHub actions would be helpful.

@tmp-hallenser Done on your php8 branch.

**Comment by kamil4** [comment]
@sunosv You can test the fix by replacing the contents of the file `Lychee/vendor/lychee-org/php-exif/lib/PHPExif/Adapter/FFprobe.php` in your installation with https://github.com/LycheeOrg/php-exif/raw/d9afbc04ec0a1170ef5a3b2f95e03edc5dda92f7/lib/PHPExif/Adapter/FFprobe.php

**Comment by sunosv** [comment]
I really don't know what went wrong.It still can't upload in my win environment. 

lychee on Windows logs：
 **2021-01-07 16:13:23 -- error   -- App\Image\ImagickHandler::crop -- 170 -- UnableToOpenBlob 'C:/Users/ADMINI~1/AppData/Local/Temp/magick-32929igvO8DVgoA2.pam': No such file or directory @ error/blob.c/OpenBlob/3315**

And,I want to see the difference between linux and windows. I have tried to upload the video in my linux environment.

the video file size is only 44MB and It took a long time, still failed. 
lychee on linux logs:
 
**2021-01-07 16:23:13 -- error   -- App\Image\ImagickHandler::crop -- 170 -- unable to write pixel cache `/tmp/magick-12328XNdv7pP3CKJP': No space left on device @ error/cache.c/WritePixelCachePixels/5984
    2021-01-07 16:21:02 -- notice  -- App\ModelFunctions\PhotoFunctions::createThumb -- 617 -- Photo URL is f41709fb6b4917773b0cc106a8001330.MP4
    2021-01-07 16:20:50 -- notice  -- App\Metadata\GitHubFunctions::__construct -- 49 -- file_get_contents(/www/wwwroot/lychee/.git/HEAD): failed to open stream: No such file or directory**


And Another interesting thing is that the temp space has run out, When uploading the video, although It has 9.3GB.

This is the change of space ,While Uploading the video.

**[root@localhost ~]# df -h /tmp
Filesystem              Size  Used  Avail Use% Mounted on 
/dev/mapper/cl-root   17G  8.8G  8.3G   52% /

[root@localhost ~]# df -h /tmp
Filesystem                    Size  Used  Avail Use% Mounted on 
/dev/mapper/cl-root   17G  9.8G  7.3G   58% /

/dev/mapper/cl-root   17G   11G  6.4G   63% /

/dev/mapper/cl-root   17G   12G  5.7G   67% /

/dev/mapper/cl-root   17G   16G  1.9G   89% /

/dev/mapper/cl-root   17G   16G  1.6G   92% /

/dev/mapper/cl-root   17G   16G  1.3G   93% /

/dev/mapper/cl-root   17G   16G  1.2G   94% /

/dev/mapper/cl-root   17G  7.8G  9.3G   46% /**
