### ISSUE TITLE
Location Decoding may generate non-valid SQL characters.

### ISSUE THREAD

**Issue by nagmat84** [LycheeOrg/Lychee#848]
### Detailed description of the problem

In general, Lychee works quite well. But for particular photos, Lychee returns a HTTP 500 error to the `Photo::add` request. I can see the incrementing counter while the image is being uploaded, then the status notification "processing" appears, and then "failed".

I already have tried to follow [the FAQ](https://lycheeorg.github.io/docs/faq.html#i-have-an-error-500-what-can-i-do), but the settings `APP_DEBUG=true` and `DEBUGBAR_ENABLED=true` in my `.env`-file did not unveil any additional information. (It seems as if changing the settings did not have any effect, although I tried to clear all caches and even restarted Apache.)

If it helps, I can also share some of the failing photos with you.

### Output of the diagnostics

    Diagnostics
    -----------
    Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.
    Warning: Dropbox import not working. dropbox_key is empty.
    
    System Information
    ------------------
    Lychee Version (git):            master (6fec96a) - Data not in Cache
    DB Version:                      4.1.0
    
    composer install:                --no-dev
    APP_ENV:                         production
    APP_DEBUG:                       true
    
    System:                          Linux
    PHP Version:                     7.4
    Max uploaded file size:          32M
    Max post size:                   128M
    PostgreSQL Version:              PostgreSQL 12.5 (Ubuntu 12.5-0ubuntu0.20.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, 64-bit
    
    Imagick:                         1
    Imagick Active:                  1
    Imagick Version:                 1690
    GD Version:                      2.2.5
    
    Config Information
    ------------------
    version:                         040100
    check_for_updates:               0
    sorting_Photos_col:              takestamp
    sorting_Photos_order:            ASC
    sorting_Albums_col:              max_takestamp
    sorting_Albums_order:            ASC
    imagick:                         1
    skip_duplicates:                 1
    small_max_width:                 0
    small_max_height:                360
    medium_max_width:                1920
    medium_max_height:               1080
    lang:                            de
    layout:                          1
    image_overlay:                   1
    image_overlay_type:              desc
    default_license:                 none
    compression_quality:             90
    full_photo:                      1
    delete_imported:                 0
    Mod_Frame:                       1
    Mod_Frame_refresh:               30
    thumb_2x:                        1
    small_2x:                        1
    medium_2x:                       1
    landing_page_enable:             0
    landing_owner:                   Matthias Nagel
    landing_title:                   MHN Net
    landing_subtitle:                Photogallerie
    landing_facebook:                
    landing_flickr:                  
    landing_twitter:                 
    landing_instagram:               
    landing_youtube:                 
    landing_background:              
    site_title:                      MHN Net – Photogallerie
    site_copyright_enable:           0
    site_copyright_begin:            2019
    site_copyright_end:              2069
    additional_footer_text:          
    display_social_in_gallery:       0
    public_search:                   0
    SL_enable:                       0
    SL_for_admin:                    0
    public_recent:                   0
    recent_age:                      1
    public_starred:                  0
    downloadable:                    0
    photos_wraparound:               1
    map_display:                     1
    zip64:                           1
    map_display_public:              1
    map_provider:                    Wikimedia
    force_32bit_ids:                 0
    map_include_subalbums:           0
    update_check_every_days:         3
    has_exiftool:                    0
    share_button_visible:            0
    import_via_symlink:              0
    has_ffmpeg:                      0
    location_decoding:               1
    location_decoding_timeout:       30
    location_show:                   1
    location_show_public:            1
    rss_enable:                      0
    rss_recent_days:                 7
    rss_max_items:                   100
    prefer_available_xmp_metadata:   0
    editor_enabled:                  1
    lossless_optimization:           0
    swipe_tolerance_x:               150
    swipe_tolerance_y:               250
    local_takestamp_video_formats:   .avi|.mov
    log_max_num_line:                1000
    unlock_password_photos_with_url_param: 0
    nsfw_visible:                    0
    nsfw_blur:                       0
    nsfw_warning:                    0
    nsfw_warning_admin:              0

### Browser and system

Firefox 84.0.1-r1, Linux 5.10.1-gentoo-r1 SMP x86_64 GNU/Linux

**Comment by ildyria** [comment]
> `DEBUGBAR_ENABLED=true`

This is not useful because you are working with a `--no-dev` installation, thus you don't have the development extensions which, let's face it, are useless for 99% of our users. :)

To use the `APP_DEBUG=true` you will also need to open the network tab in your browser (usually F12) and look at the response of the failed request. The debug mode should reveal pieces of information such as the error encountered and the function trace instead of a simple white page.

I would be interested in having a failing image so I can also try it on my dev install and figure out what is going on.

**Comment by nagmat84** [comment]
I enabled `APP_DEBUG=true`. The network tab of my browser reports.

**Request Header:**

    POST /lychee/api/Photo::add HTTP/1.1
    Host: www.mhnnet.de
    User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0
    Accept: */*
    Accept-Language: de-DE,de;q=0.8,en-US;q=0.5,en;q=0.3
    Accept-Encoding: gzip, deflate, br
    X-XSRF-TOKEN: eyJpdiI6Im1DRVRWMjZqYTVoYkhyRlJ0eFhnUmc9PSIsInZhbHVlIjoiUFA4bklOV1NtQXZSSkNUbHFCQUFxaUZhaHRJVEVSMHZCOWxKZkpuQ1FSZE9kUDVsSDFsZHZwM1ZUZHJabTFPVXUxRFg4UVpZMXlCTHJBTTF3ZllXM0JTSjA3NjlPVW5sRkZjWGw4STZxTXczSEgrWGs4VTFFZDZQeHhhSkwrWEUiLCJtYWMiOiJjNTAzNjYwYTkzYzc4YmQ5NGEyYTg3ZDViNGFjOTFkMGM1MjM2M2E4MTliYTlhNDExNzUzNzJhOTg0ZmU0NGI2In0
    Content-Type: multipart/form-data; boundary=---------------------------36218867189719653343016447867
    Content-Length: 4328642
    Origin: https://www.mhnnet.de
    Connection: keep-alive
    Cookie: XSRF-TOKEN=eyJpdiI6Im1DRVRWMjZqYTVoYkhyRlJ0eFhnUmc9PSIsInZhbHVlIjoiUFA4bklOV1NtQXZSSkNUbHFCQUFxaUZhaHRJVEVSMHZCOWxKZkpuQ1FSZE9kUDVsSDFsZHZwM1ZUZHJabTFPVXUxRFg4UVpZMXlCTHJBTTF3ZllXM0JTSjA3NjlPVW5sRkZjWGw4STZxTXczSEgrWGs4VTFFZDZQeHhhSkwrWEUiLCJtYWMiOiJjNTAzNjYwYTkzYzc4YmQ5NGEyYTg3ZDViNGFjOTFkMGM1MjM2M2E4MTliYTlhNDExNzUzNzJhOTg0ZmU0NGI2In0%3D; lychee_session=eyJpdiI6Ii9hZVgyYlJxZjhKdU5Yczg0WVN4TGc9PSIsInZhbHVlIjoicDNldW9XL1VOTVpDaTNXR1A1VlZkT0tmWnZ0NDArcytjcjRtWHVTUUw3WGxKWEtOR3NzYmhxUmZnYmM0TmFzZ1BpNTVuOC96eG51aEkwOWpFQ1k2QTBqSFlvOFNoa09wak90Q01LM24yci9kOUFQWExLR3l3WldvR3Z1WlZxd0ciLCJtYWMiOiJhOGY0MjM5ZWMzMWMzOTJiZDg1M2YzNjdjMmNiYzJmZDEyYTRmMzA3ZTkzM2RlNzQ3MzExNmRiOWRjMjlkNmYwIn0%3D

**Request Body:**

    -----------------------------36218867189719653343016447867
    Content-Disposition: form-data; name="function"
    
    Photo::add
    -----------------------------36218867189719653343016447867
    Content-Disposition: form-data; name="albumID"
    
    16096115744840
    -----------------------------36218867189719653343016447867
    Content-Disposition: form-data; name="0"; filename="IMG_20180923_153606.jpg"
    Content-Type: image/jpeg
    
    -- truncated by network tab of browser / JPEG DATA --

**Response Header:**

    HTTP/1.1 500 Internal Server Error
    Date: Sun, 03 Jan 2021 11:21:44 GMT
    Server: Apache
    X-Content-Type-Options: nosniff
    X-Frame-Options: sameorigin
    X-Permitted-Cross-Domain-Policies: none
    X-Robots-Tag: none
    X-XSS-Protection: 1; mode=block
    Strict-Transport-Security: max-age=31104000; includeSubDomains
    Cache-Control: no-cache, private
    Feature-Policy: autoplay 'self'; encrypted-media 'self'; fullscreen 'self'; picture-in-picture *; sync-xhr *
    X-Content-Type-Options: nosniff
    X-Download-Options: noopen
    X-Frame-Options: deny
    X-Permitted-Cross-Domain-Policies: none
    X-XSS-Protection: 1; mode=block
    Referrer-Policy: no-referrer
    Set-Cookie: XSRF-TOKEN=eyJpdiI6IkJCV0dBOG1rZTlwV3JlVStZWnJJVXc9PSIsInZhbHVlIjoiQnNWZEFhckEzbGhuTVFFbmo1aU1Za054eU1lTW9PeHNzZjlxMFl4SmFTL3o2djNrbVEvRHhFVEN5QUlReElEMEhBcWZGWWgzZW4rRVc1SHlaS2E4OUZqVlAzYzRmcEtDUjA3eWdlZnFsYXVjSTIrUFhCT2FXeVNDejNHbTM2WFgiLCJtYWMiOiJlMGFiYTk5YzNhY2IxMDQyOWY4ZGEwOTUyYzNkZDRlYzU1NTM4YWY2ZDNkYzUyMGNiZGQzNDczOGIwYTcyYTczIn0%3D; expires=Sun, 03-Jan-2021 13:21:51 GMT; Max-Age=7200; path=/; samesite=lax
    Set-Cookie: lychee_session=eyJpdiI6IjNUZGlEOTJpT1M1WXhsaXZuMTc3eEE9PSIsInZhbHVlIjoib0J0dGp0b2UrWDRlU0lYczhkNUZJTlVmcHZJSUdhMzc3Vmh1dVovTGg3Vkc5bFFKYnNQR1RON2VET3RPWVFUbEVndTlaYWFMWm02VElDWG8vRDB3UnJjNHJjUXplZjkvVHQ2ZUdyVklCK3pPRG4xM2tzOCtIYlRxcVBGQmd5UUEiLCJtYWMiOiIwNGI0NjE2NmY0ODc0NWRmYTVlMjM2ODM3ZWQ1MTZhMmFiOGIyYjRmYzI3MDg2ZDFhNzU0MmI2ZTFjMzVjNWVlIn0%3D; expires=Sun, 03-Jan-2021 13:21:51 GMT; Max-    Age=7200; path=/; httponly; samesite=lax
    Connection: close
    Transfer-Encoding: chunked
    Content-Type: text/html; charset=UTF-8

**Response Body**

The response body is a Symfony generated HTML page which I cannot properly paste here. But the essential error message on the HTML page is:

> SQLSTATE[22021]: Character not in repertoire: 7 ERROR: invalid byte sequence for encoding "UTF8": 0xc3 0x2c (SQL: insert into "logs" ("type", "function", "line", "text", "updated_at", "created_at") values (error, App\ModelFunctions\PhotoFunctions::save, 814, Something went wrong, error 22021, SQLSTATE[22021]: Character not in repertoire: 7 ERROR: invalid byte sequence for encoding "UTF8": 0xc3 (SQL: insert into "photos" ("id", "checksum", "title", "url", "description", "tags", "width", "height", "type", "size", "iso", "aperture", "make", "model", "lens", "shutter", "focal", "takestamp", "latitude", "longitude", "altitude", "imgDirection", "location", "livePhotoContentID", "public", "star", "album_id", "owner_id", "thumb2x", "thumbUrl", "medium", "medium2x", "small", "small2x", "updated_at", "created_at") values (16096729083190, 3f5c1e12c225b8084868d47972ca075304515223, IMG_20180923_153606, b173225822b5c76e2b5a7eb20cf93039.jpg, , , 4032, 3024, image/jpeg, 4.1 MB, 60, f/2.0, LGE, Nexus 5X, , 1/263 s, 5 mm, 2018-09-23 15:36:08, 48.902080555556, 9.1978555555556, 291, ?, Wasserspielplatz, Marbacher Straße, Ludwigsburg-Mitte, Ludwigsburg, Landkreis Ludwigsburg, Baden-W�, ?, 0, 0, 16096115744840, 0, 1, b173225822b5c76e2b5a7eb20cf93039.jpeg, 1440x1080, 2880x2160, 480x360, 960x720, 2021-01-03 12:21:51, 2021-01-03 12:21:51) returning "id"), 2021-01-03 12:21:51, 2021-01-03 12:21:51) returning "id")

So it seems to be some problem with the meta data. The location should actually be "Baden-Württemberg" with a German Umlaut "ü". Remarkably, only five photos out of a series of about 50 photos is affected and they all have been taken with the same smartphone. For the majority of photos, the "ü" just works, and for a handful of photos the "ü" fails. I don't know why.

That's one of the failing photos:

![Failing photo](https://user-images.githubusercontent.com/7428426/103477583-998ac480-4dc0-11eb-9d35-7caa15d822c3.jpg)

That's a working photo:

![Working photo](https://user-images.githubusercontent.com/7428426/103477598-b626fc80-4dc0-11eb-941a-ba9afed68d0d.jpg)

**Comment by ildyria** [comment]
True, but... if I do 
`exiftool 103477583-998ac480-4dc0-11eb-9d35-7caa15d822c3.jpg | grep Baden`
I don't see those informations.

 Which means that they are not contained in the Exif data but contained in the reverse look up location that we do.

not working:
```
> exiftool 103477583-998ac480-4dc0-11eb-9d35-7caa15d822c3.jpg | grep 'GPS Position'
GPS Position                    : 48 deg 54' 7.49" N, 9 deg 11' 52.28" E

```
working:
```
> exiftool 103477598-b626fc80-4dc0-11eb-941a-ba9afed68d0d.jpg | grep 'GPS Position'
GPS Position                    : 48 deg 54' 7.75" N, 9 deg 11' 50.40" E
```

In other words, it is a bug on our side which should be fixed (actually surprising this is not).

**Comment by ildyria** [comment]
~~Hummm... just tested on my Own server. Both images works but I am using MySQL instead of PostgreSQL.~~

My bad, forgot to enable location decoding... :facepalm:

**Comment by tmp-hallenser** [comment]
Having a similar issue with some images recently (after change of database). I suspect it to be an encoding issue (using forceUTF8 as we do at php-exif ??), but can‘t confirm.

I further discovered that we insert an empty string into the location field instead instead of null if decoding is disabled.

**Comment by tmp-hallenser** [comment]
I did some minor bug fixes (related, but not helping on this issue). @ildyria As I don't have a dev environment available atm (did the edits on the Github Webinterface), could you run apply the formatting and merge the 'bugfixing-location-decoding' branch?

@nagmat84 What does `php artisan lychee:decode_GPS_locations` say? (run it after you imported the images w/o location decoding and after @ildyria has merged the branch above)?

**Comment by ildyria** [comment]
@tmp-hallenser done. Thanks for being so fast on it!

**Comment by ildyria** [comment]
fixed with latest commit.
