### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by StefanescuCristian** [LycheeOrg/Lychee#849]
### Detailed description of the problem [REQUIRED]
After upgrading to 4.1.0 from 4.0.4 and doing `composer install --no-dev` I have the following error:

```
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In FeedServiceProvider.php line 39:

  Invalid argument supplied for foreach()


Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1
```

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Upgraded via documentation / manually
2. On step 3 of the upgrade I have a blank page, so went to CLI and run `composer install --no-dev`

### Output of the diagnostics  [REQUIRED]
```
php artisan lychee:diagnostics

In FeedServiceProvider.php line 39:

  Invalid argument supplied for foreach()

```

The last version that works for me is 4.0.4. Version 4.0.5 has the same problem.

### Screenshots:
<img width="1094" alt="image" src="https://user-images.githubusercontent.com/1718660/103481445-c0a6bd80-4de3-11eb-8a9d-b852be8d7ddb.png">
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/1718660/103481448-cc927f80-4de3-11eb-8515-764e34b48470.png">
<img width="1089" alt="image" src="https://user-images.githubusercontent.com/1718660/103481453-d3b98d80-4de3-11eb-8928-be48c4cd0282.png">

Server: Ubuntu 20.04, PHP 7.4 from Ondrej PPA.

I've tried doing `rm -rf vendor` and `composer install --no-dev` but it throws the same error.

**Comment by ildyria** [comment]
~~That's clearly a dependency error.~~

**Comment by StefanescuCristian** [comment]
Can you help me fixing it?

**Comment by ildyria** [comment]
I can't even reproduce it here. Weird.

**Comment by ildyria** [comment]
~~hummm wait. That is not a composer error.~~

**Comment by ildyria** [comment]
Check if you do have a file `config/feed.php`.

It is provided by our installation : https://github.com/LycheeOrg/Lychee/blob/master/config/feed.php
So it should exist.

**Comment by ildyria** [comment]
Version 4.0.5 is introducing the RSS feed. So if you are not adding the config files as per stated in the update instruction, then will be broken.

> 1 — Download the newest Version
> 2 — Replace **all existing files**, excluding `uploads/` and `dist/user.css`

**Comment by StefanescuCristian** [comment]
It's there and it's the same as the one from the repo.

```
ll config
total 128K
drwxr-xr-x  2 www-data www-data 4.0K Dec 27 17:18 ./
drwxr-xr-x 14 www-data www-data 4.0K Jan  3 16:51 ../
-rw-r--r--  1 www-data www-data 8.3K Dec 27 17:18 app.php
-rw-r--r--  1 www-data www-data 3.4K Dec 27 17:18 auth.php
-rw-r--r--  1 www-data www-data 1.4K Dec 27 17:18 broadcasting.php
-rw-r--r--  1 www-data www-data 2.6K Dec 27 17:18 cache.php
-rw-r--r--  1 www-data www-data 4.3K Dec 27 17:18 database.php
-rw-r--r--  1 www-data www-data 7.0K Dec 27 17:18 debugbar.php
-rw-r--r--  1 www-data www-data  208 Dec 27 17:18 defines.php
-rw-r--r--  1 www-data www-data  660 Dec 27 17:18 feed.php
-rw-r--r--  1 www-data www-data 2.9K Dec 27 17:18 filesystems.php
-rw-r--r--  1 www-data www-data 1.5K Dec 27 17:18 hashing.php
-rw-r--r--  1 www-data www-data 2.0K Dec 27 17:18 image-optimizer.php
-rw-r--r--  1 www-data www-data 5.2K Dec 27 17:18 larapass.php
-rw-r--r--  1 www-data www-data 2.4K Dec 27 17:18 logging.php
-rw-r--r--  1 www-data www-data 2.9K Dec 27 17:18 mail.php
-rw-r--r--  1 www-data www-data 4.1K Dec 27 17:18 markdown.php
-rw-r--r--  1 www-data www-data 2.4K Dec 27 17:18 queue.php
-rw-r--r--  1 www-data www-data 8.4K Dec 27 17:18 secure-headers.php
-rw-r--r--  1 www-data www-data  855 Dec 27 17:18 services.php
-rw-r--r--  1 www-data www-data 6.9K Dec 27 17:18 session.php
-rw-r--r--  1 www-data www-data  287 Dec 27 17:18 urls.php
-rw-r--r--  1 www-data www-data  961 Dec 27 17:18 view.php
```

**Comment by ildyria** [comment]
hummmm

**Comment by StefanescuCristian** [comment]
> Version 4.0.5 is introducing the RSS feed. So if you are not adding the config files as per stated in the update instruction, then will be broken.
> 
> > 1 — Download the newest Version
> > 2 — Replace **all existing files**, excluding `uploads/` and `dist/user.css`

I've done that already.

1. Downloaded the ZIP.
2. extracted it and removed uploads and dist/user.css.
3. Copied via mc with the option to overwrite all.
4. `composer install --no-dev` throws the error.

**Comment by ildyria** [comment]
very surprising.

**Comment by StefanescuCristian** [comment]
Let's say that it's something wrong with my installation. Can you give me some advice on how to force an upgrade?

**Comment by ildyria** [comment]
If you download the zip file you should not need to do the `composer` part as the vendor folder is provided.

But it seems you would still get the error. :thinking:

**Comment by StefanescuCristian** [comment]
Yeah, I'm still getting the error.

BTW, I'm running PHP-FPM with stock settings, if this helps.

**Comment by ildyria** [comment]
can you try this:
```
composer dump-autoload
php artisan config:clear
php artisan config:cache
```

**Comment by StefanescuCristian** [comment]
It doesn't work unfortunately

```
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In FeedServiceProvider.php line 39:

  Invalid argument supplied for foreach()


Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1
```

**Comment by ildyria** [comment]
Honestly for that one, I am out of ideas. :(
You can give a try to commenting line 26 in the `routes/web.php` file. :(

**Comment by ildyria** [comment]
Could you check if your composer is up to date? :thinking:

**Comment by StefanescuCristian** [comment]
Composer is up to date.

```
   ______
  / ____/___  ____ ___  ____  ____  ________  _____
 / /   / __ \/ __ `__ \/ __ \/ __ \/ ___/ _ \/ ___/
/ /___/ /_/ / / / / / / /_/ / /_/ (__  )  __/ /
\____/\____/_/ /_/ /_/ .___/\____/____/\___/_/
                    /_/
Composer version 2.0.8 2020-12-03 17:20:38
```
Commenting line 26 gives more errors.

I guess I'll stick with 4.0.4 since it works.

**Comment by ildyria** [comment]
I'm really sorry for that. :(

**Comment by StefanescuCristian** [comment]
No problem.
I somehow manged to fix that issue: https://github.com/spatie/laravel-feed/issues/127, but now I have some other errors.
