### ISSUE TITLE
Random string for non-admin users on main page

### ISSUE THREAD

**Issue by nagmat84** [LycheeOrg/Lychee#851]
### Description of the problem

If a non-admin user logs in, a random string appears on top of the main page. This glitch does not appear within albums.

### Steps to reproduce the issue

1. Create some albums with photos
2. Create a non-admin user (the settings for the rights for uploading and restriction are irrelevant)
3. Share some albums with the freshly created user
4. Log-out and re-login as the freshly created user

### Screenshot

~~removed for security purposes~~

### Output of the diagnostics

    Diagnostics
    -----------
    Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.
    Warning: Dropbox import not working. dropbox_key is empty.
    
    System Information
    ------------------
    Lychee Version (git):            master (6fec96a) - Data not in Cache
    DB Version:                      4.1.0
    
    composer install:                --no-dev
    APP_ENV:                         production
    APP_DEBUG:                       true
    
    System:                          Linux
    PHP Version:                     7.4
    Max uploaded file size:          32M
    Max post size:                   128M
    PostgreSQL Version:              PostgreSQL 12.5 (Ubuntu 12.5-0ubuntu0.20.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, 64-bit
    
    Imagick:                         1
    Imagick Active:                  1
    Imagick Version:                 1690
    GD Version:                      2.2.5
    
    Config Information
    ------------------
    version:                         040100
    check_for_updates:               0
    sorting_Photos_col:              takestamp
    sorting_Photos_order:            ASC
    sorting_Albums_col:              max_takestamp
    sorting_Albums_order:            ASC
    imagick:                         1
    skip_duplicates:                 1
    small_max_width:                 0
    small_max_height:                360
    medium_max_width:                1920
    medium_max_height:               1080
    lang:                            de
    layout:                          1
    image_overlay:                   1
    image_overlay_type:              desc
    default_license:                 none
    compression_quality:             90
    full_photo:                      1
    delete_imported:                 0
    Mod_Frame:                       1
    Mod_Frame_refresh:               30
    thumb_2x:                        1
    small_2x:                        1
    medium_2x:                       1
    landing_page_enable:             0
    landing_owner:                   Matthias Nagel
    landing_title:                   MHN Net
    landing_subtitle:                Photogallerie
    landing_facebook:                
    landing_flickr:                  
    landing_twitter:                 
    landing_instagram:               
    landing_youtube:                 
    landing_background:              
    site_title:                      MHN Net – Photogallerie
    site_copyright_enable:           0
    site_copyright_begin:            2019
    site_copyright_end:              2069
    additional_footer_text:          
    display_social_in_gallery:       0
    public_search:                   0
    SL_enable:                       0
    SL_for_admin:                    0
    public_recent:                   0
    recent_age:                      1
    public_starred:                  0
    downloadable:                    0
    photos_wraparound:               1
    map_display:                     1
    zip64:                           1
    map_display_public:              1
    map_provider:                    Wikimedia
    force_32bit_ids:                 0
    map_include_subalbums:           0
    update_check_every_days:         3
    has_exiftool:                    0
    share_button_visible:            0
    import_via_symlink:              0
    has_ffmpeg:                      0
    location_decoding:               1
    location_decoding_timeout:       30
    location_show:                   1
    location_show_public:            1
    rss_enable:                      0
    rss_recent_days:                 7
    rss_max_items:                   100
    prefer_available_xmp_metadata:   0
    editor_enabled:                  1
    lossless_optimization:           0
    swipe_tolerance_x:               150
    swipe_tolerance_y:               250
    local_takestamp_video_formats:   .avi|.mov
    log_max_num_line:                1000
    unlock_password_photos_with_url_param: 0
    nsfw_visible:                    0
    nsfw_blur:                       0
    nsfw_warning:                    0
    nsfw_warning_admin:              0

### Browser and system

Firefox 84.0.1-r1, Linux 5.10.1-gentoo-r1 SMP x86_64 GNU/Linux

**Comment by ildyria** [comment]
Hahahaha :sweat_smile:  Yeah I recognize that string...

Already fixed in #832
