### ISSUE TITLE
Hide Smart Albums not working

### ISSUE THREAD

**Issue by m0yP** [LycheeOrg/Lychee#861]
### Detailed description of the problem [REQUIRED]
*After typing the custom CSS to hide Smart Albums and reloading page, they're not hidden.*

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Go to 'Settings -> Personalize your CSS'
2. Paste the code in 'https://lycheeorg.github.io/docs/faq.html#how-to-hide-smart-albums'
3. Click on 'Change CSS'
4. See error*

**Screenshots**
N/A

### Output of the diagnostics  [REQUIRED]

    System Information
    --------------
    Lychee Version (release):        4.1.0
    DB Version:                      4.1.0
    
    composer install:                --no-dev
    APP_ENV:                         production
    APP_DEBUG:                       false
    
    System:                          Linux
    PHP Version:                     7.4
    Max uploaded file size:          1G
    Max post size:                   1G
    MySQL Version:                   10.2.36-MariaDB
    
    Imagick:                         1
    Imagick Active:                  1
    Imagick Version:                 1690
    GD Version:                      bundled (2.1.0 compatible)

### Browser and system

Firefox 84.0.2 and Fennec 84.1.2

**Comment by kamil4** [comment]
I think the answer in the FAQ may be obsolete. Can you try the following CSS instead?
```
[data-id="unsorted"] { display:none; }
[data-id="public"] { display:none; }
[data-id="starred"] { display:none; }
[data-id="recent"] { display:none; }
```

**Comment by kamil4** [comment]
OK, I played with it a bit and the above works, but to make it look really neat you should also add:
```
div.content > div.divider:first-child { display:none; }
div.content > div.divider:nth-child(6) {
    margin-top: 10px;
    border-top: 0;
    box-shadow: none;
} 
```

**Comment by kamil4** [comment]
Documentation updated...

**Comment by m0yP** [comment]
Awesome! Thanks a lot.
