### ISSUE TITLE
Note: my hoster currently supports MySQL 5.6 | all Lychee crashed

### ISSUE THREAD

**Issue by ko3t3r** [LycheeOrg/Lychee#862]
### Detailed description of the problem [REQUIRED]
*A clear and concise description of what the bug is.*

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
4. See error*
5. Note: my hoster currently supports MySQL 5.6 | all Lychee crashed. No more needs to be said or analyzed.

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

### Output of the diagnostics  [REQUIRED]
*(Settings => Diagnostics or https://example.com/Diagnostics or `php artisan lychee:diagnostics`)*

### Browser and system
Linux, Opera / Firefox

**Comment by ildyria** [comment]
Then I guess you are stuck to v4.0.8 :(

**Comment by ko3t3r** [comment]
I know, I know. I should have read the requirements for the new Lychee version. - Lots of work. - Thank you for your prompt reply!

**Comment by ko3t3r** [comment]
I contacted my host and asked them to say goodbye to Old MySQL 5.6.
