### ISSUE TITLE
FFMPEG and Exiftool Issue for thumbnail

### ISSUE THREAD

**Issue by mgilank** [LycheeOrg/Lychee#866]
### Detailed description of the problem [REQUIRED]
*A clear and concise description of what the bug is.*

i have make sure that ffmpeg and exiftool are installed, working and access in user permission.
exec also enable. fresh install.

already following this guide https://lycheeorg.github.io/docs/faq.html#why-dont-my-videos-have-thumbnails
but seems like it move/rename the file to app/Actions/Photo/Extensions/VideoEditing.php

error log  2021-01-13 03:25:02 -- notice  -- App\Metadata\Extractor::extract -- 109 -- FFmpeg and Exiftool not being available; Extraction of metadata limited to mime type and file size.
    2021-01-13 03:25:02 -- notice  -- App\Metadata\Extractor::extract -- 109 -- FFmpeg and Exiftool not being available; Extraction of metadata limited to mime type and file size.
    2021-01-13 03:24:15 -- notice  -- App\Actions\Photo\Extensions\VideoEditing::extractVideoFrame -- 29 -- Failed to extract snapshot: bad config: 
    2021-01-13 03:24:15 -- notice  -- App\Metadata\Extractor::extract -- 109 -- FFmpeg and Exiftool not being available; Extraction of metadata limited to mime type and file size.
    2021-01-13 03:22:40 -- notice  -- App\Actions\Photo\Extensions\VideoEditing::extractVideoFrame -- 29 -- Failed to extract snapshot: bad config: 

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
uploading video with .mp4 and .mov format

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

### Output of the diagnostics  [REQUIRED]
*(Settings => Diagnostics or https://example.com/Diagnostics or `php artisan lychee:diagnostics`)*

Diagnostics
    -------
    Warning: Dropbox import not working. dropbox_key is empty.
    Warning: You may experience problems when uploading a photo of large size. Take a look in the FAQ for details.
    Warning: You may experience problems when uploading a photos of large size. Take a look in the FAQ for details.
    Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.

    System Information
    --------------
    Lychee Version (git):            master (1ce756e) - Up to date (7 minutes ago).
    DB Version:                      4.2.0
    
    composer install:                --no-dev
    APP_ENV:                         production
    APP_DEBUG:                       false
    
    System:                          Linux
    PHP Version:                     7.4
    Max uploaded file size:          2M
    Max post size:                   8M
    MySQL Version:                   10.5.8-MariaDB-1:10.5.8+maria~focal
    
    Imagick:                         1
    Imagick Active:                  1
    Imagick Version:                 1690
    GD Version:                      2.3.0

    Config Information
    --------------
    version:                         040200
    check_for_updates:               0
    sorting_Photos_col:              takestamp
    sorting_Photos_order:            ASC
    sorting_Albums_col:              max_takestamp
    sorting_Albums_order:            ASC
    imagick:                         1
    skip_duplicates:                 0
    small_max_width:                 0
    small_max_height:                360
    medium_max_width:                1920
    medium_max_height:               1080
    lang:                            en
    layout:                          1
    image_overlay:                   1
    image_overlay_type:              desc
    default_license:                 none
    compression_quality:             90
    full_photo:                      1
    delete_imported:                 0
    Mod_Frame:                       1
    Mod_Frame_refresh:               30
    thumb_2x:                        1
    small_2x:                        1
    medium_2x:                       1
    landing_page_enable:             0
    landing_owner:                   John Smith
    landing_title:                   John Smith
    landing_subtitle:                Cats, Dogs & Humans Photography
    landing_facebook:                https://www.facebook.com/JohnSmith
    landing_flickr:                  https://www.flickr.com/JohnSmith
    landing_twitter:                 https://www.twitter.com/JohnSmith
    landing_instagram:               https://instagram.com/JohnSmith
    landing_youtube:                 https://www.youtube.com/JohnSmith
    landing_background:              dist/cat.jpg
    site_title:                      Lychee v4
    site_copyright_enable:           1
    site_copyright_begin:            2019
    site_copyright_end:              2019
    additional_footer_text:          
    display_social_in_gallery:       0
    public_search:                   0
    SL_enable:                       0
    SL_for_admin:                    0
    public_recent:                   0
    recent_age:                      1
    public_starred:                  0
    downloadable:                    0
    photos_wraparound:               1
    map_display:                     0
    zip64:                           1
    map_display_public:              0
    map_provider:                    Wikimedia
    force_32bit_ids:                 0
    map_include_subalbums:           0
    update_check_every_days:         3
    has_exiftool:                    0
    share_button_visible:            0
    import_via_symlink:              0
    has_ffmpeg:                      0
    location_decoding:               0
    location_decoding_timeout:       30
    location_show:                   1
    location_show_public:            0
    rss_enable:                      0
    rss_recent_days:                 7
    rss_max_items:                   100
    prefer_available_xmp_metadata:   0
    editor_enabled:                  1
    lossless_optimization:           0
    swipe_tolerance_x:               150
    swipe_tolerance_y:               250
    local_takestamp_video_formats:   .avi|.mov
    log_max_num_line:                1000
    unlock_password_photos_with_url_param: 0
    nsfw_visible:                    1
    nsfw_blur:                       0
    nsfw_warning:                    0
    nsfw_warning_admin:              0

**Comment by kamil4** [comment]
> seems like it move/rename the file to app/Actions/Photo/Extensions/VideoEditing.php

Correct. It's a new location for the upcoming 4.2.0 release. The FAQ will need to be updated.

Can you set `has_ffmpeg` to `1` in the advanced config (Settings / More) and report back the messages you see then?

**Comment by mgilank** [comment]
Hi, nice it works!

case closed

**Comment by kamil4** [comment]
The FAQ has been updated/expanded.
