### ISSUE TITLE
Lychee-Installer :  Please fix the errors before going to the next step.  EXIF Error /  PHP.exec() not available Error

### ISSUE THREAD

**Issue by wellfedartist** [LycheeOrg/Lychee#881]
Hello all.  I've been pulling my hair out for 3 weeks now trying to install Lychee on my hosted server, with too many errors to list along the way.   Finally, I have gotten to a stage where the install page is actually loading, but I am getting an error with EXIF and Php.exec(), that won't let me proceed.  

My server is running Centos 7.6 through Alibaba hosting.   I have php 7.4.14 installed, and BT.cn Linux Pagoda panel installed.
I'm am pretty new to anything server related.  But from what I can tell, I have installed EXIF already.    Any help resolving this would be greatly appreciated. 
![WeChat Image_20210124102445](https://user-images.githubusercontent.com/77907171/105619652-da11b700-5e2f-11eb-8e12-11a366ed711c.png)

**Comment by kamil4** [comment]
Did you install that php version yourself? How did you obtain it?

First, exif:

Do you have command-line access to your server? Can you invoke `php -m` and verify that `exif` is in the list of modules that prints out? Even if it is, it could be that you have more than one version of PHP installed on that server and that the HTTP daemon is using a different version for Lychee than what you invoke from the command line.

Now, exec:

This should be optional, but it's really useful if you want to be able to have previews for video files (which require invoking `ffmpeg` at import time) or higher quality exif information via `exiftool`. It sounds like `exec` is disabled in your PHP config. That's not the default, so somebody must've configured it that way. Still, if you have admin-level access to your server, you should be able to fix it. On my machine, the config file to edit is `/etc/php/apache2-php7.4`; look for the `disable_functions` directive. But that depends on the HTTP daemon you use and how it is configured. Perhaps [this page](https://www.cyberciti.biz/faq/linux-unix-apache-lighttpd-phpini-disable-functions/) will be more helpful for you.

**Comment by wellfedartist** [comment]
Yes, I installed php 7.4.14 myself. So, maybe it's possible there are two installations.  Exif is listed when I input php -m in my terminal.   How would I go about removing other php versions?  When I input php -v, I get the 7.4.14 version listed.

**Comment by wellfedartist** [comment]
> Did you install that php version yourself? How did you obtain it?
> 
> First, exif:
> 
> Do you have command-line access to your server? Can you invoke `php -m` and verify that `exif` is in the list of modules that prints out? Even if it is, it could be that you have more than one version of PHP installed on that server and that the HTTP daemon is using a different version for Lychee than what you invoke from the command line.
> 
> Now, exec:
> 
> This should be optional, but it's really useful if you want to be able to have previews for video files (which require invoking `ffmpeg` at import time) or higher quality exif information via `exiftool`. It sounds like `exec` is disabled in your PHP config. That's not the default, so somebody must've configured it that way. Still, if you have admin-level access to your server, you should be able to fix it. On my machine, the config file to edit is `/etc/php/apache2-php7.4`; look for the `disable_functions` directive. But that depends on the HTTP daemon you use and how it is configured. Perhaps [this page](https://www.cyberciti.biz/faq/linux-unix-apache-lighttpd-phpini-disable-functions/) will be more helpful for you.

Yes, I installed php 7.4.14 myself. So, maybe it's possible there are two installations. Exif is listed when I input php -m in my terminal. How would I go about removing other php versions? When I input php -v, I get the 7.4.14 version listed.

**Comment by kamil4** [comment]
On my machine I use the Apache HTTP daemon with `mod_php` module. In `/usr/lib64/apache2/modules/` directory I have a link `mod_php.so` that points to `/usr/lib64/php7.4/apache2/libphp7.so`. This is how Apache finds the PHP to use. If you use the same sort of configuration, this may help you (there are other ways of invoking php, and in fact I believe that what I use may be considered obsolete).

Also make sure that you have restarted the HTTP daemon after installing the new php version.

**Comment by wellfedartist** [comment]
I have managed to fix the php.exec issue. Thanks for that info. Still working on the exif situation though.  I really don't know a whole lot about apache
