### ISSUE TITLE
[Enhancement] Disable direction display (more general: ignore certain EXIF tags)

### ISSUE THREAD

**Issue by sjml** [LycheeOrg/Lychee#886]
I'm setting up a new gallery with a lot of images that are geotagged. What I'm discovering, though, is that while the GPS locations are accurate, the direction info usually is not. On top of that, the apps that I use tend to only expose correction of the latitude/longitude, not of the direction, so it's a difficult problem to fix for large numbers of photos. 

I'd be happy for the photo's map to simply not show the direction, but I don't see any simple way to disable it beyond hacking the JavaScript myself (which would not survive an upgrade). 

Would you accept a PR to expose something like "Ignore GPS direction" as a setting? 

Alternately, and maybe solving a more general problem: is there some way to create an exclusion list of EXIF tags so that the import process could treat the photo as if it does not have those tags?

EDIT: I have a PR ready to go that does the simpler version of this (just adding a config flag to not use the direction data in the embedded map), but not sure how you prefer to handle it since it's properly *two* PRs, one to this repo and another to `Lychee-front`. Let me know!

**Comment by ildyria** [comment]
> Would you accept a PR to expose something like "Ignore GPS direction" as a setting?

I have nothing against such setting. :)

> Alternately, and maybe solving a more general problem: is there some way to create an exclusion list of EXIF tags so that the import process could treat the photo as if it does not have those tags?

This is an interesting alternative, though the implementation of such thing would be interesting.

> I have a PR ready to go that does the simpler version of this (just adding a config flag to not use the direction data in the embedded map), but not sure how you prefer to handle it since it's properly two PRs, one to this repo and another to Lychee-front. Let me know!

Usually the process is as follows: 
- we take the 2 PR (Lychee-front and Lychee),
- review them both,
- merge on Lychee-front
- switch Lychee-front to master, rebuild & commit on the PR.
- merge to Lychee master

**Comment by sjml** [comment]
Great, I'll prep two PRs, then. Thanks! 

> This is an interesting alternative, though the implementation of such thing would be interesting.

(Yeah, I think "interesting" is the right choice of word there. :) While it might be worth doing in the long run, it's definitely beyond the scope of fixing this very simple problem.)
