### ISSUE TITLE
Downloadfile not found on password protected Album

### ISSUE THREAD

**Issue by Flecko** [LycheeOrg/Lychee#891]
If I am logged in as admin I can download different resolutions of the picture in the albums via Download.

If I protect the folder with a password and log in there, I get a 404 error when I go to download after selecting the resolution

Example url: https://mywebsite.com/api/Photo::getArchive?photoIDs=16117763347685&kind=FULL
Config of Album: ![Bildschirmfoto 2021-01-28 um 20 07 48](https://user-images.githubusercontent.com/4092664/106186445-93f88280-61a4-11eb-97f2-e33e108b913c.png)

Lychee 4.2.1 / PHP 7.4.8 FPM

**Comment by kamil4** [comment]
Can you include the config settings obtained through Diagnostics? In particular, what is your value of `downloadable`? I was only able to reproduce this with `downloadable` set to `0`, but in that case it doesn't seem to matter if the album is password-protected or not. And, `downloadable` shouldn't matter in that case anyway, so there's clearly a bug. I just want to make sure that we are looking at _the same_ bug :smiley:.

**Comment by d7415** [comment]
> Can you include the config settings obtained through Diagnostics?

Also because actively deleting the template is rude and disrespectful.

**Comment by Flecko** [comment]
`


    Diagnostics
    -------
    Warning: Dropbox import not working. dropbox_key is empty.
    Warning: You may experience problems when uploading a photos of large size. Take a look in the FAQ for details.




    System Information
    --------------
    Lychee Version (git):            master (d683c13) - Up to date (2 hours ago).
    DB Version:                      4.2.1
    
    composer install:                --no-dev
    APP_ENV:                         production
    APP_DEBUG:                       false
    
    System:                          Linux
    PHP Version:                     7.4
    Max uploaded file size:          32M
    Max post size:                   32M
    SQLite Version:                  3.8.7.1
    
    Imagick:                         1
    Imagick Active:                  1
    Imagick Version:                 1673
    GD Version:                      bundled (2.1.0 compatible)

    
    Lychee total space:              539.95 MB
    Upload folder space:             458.10 MB
    System total space:              295.26 GB
    System free space:               219.38 GB (74%)




    Config Information
    --------------
    version:                         040201
    check_for_updates:               0
    sorting_Photos_col:              takestamp
    sorting_Photos_order:            ASC
    sorting_Albums_col:              max_takestamp
    sorting_Albums_order:            ASC
    imagick:                         1
    skip_duplicates:                 0
    small_max_width:                 0
    small_max_height:                360
    medium_max_width:                1920
    medium_max_height:               1080
    lang:                            en
    layout:                          1
    image_overlay:                   0
    image_overlay_type:              desc
    default_license:                 reserved
    compression_quality:             90
    full_photo:                      1
    delete_imported:                 0
    Mod_Frame:                       1
    Mod_Frame_refresh:               30
    thumb_2x:                        1
    small_2x:                        1
    medium_2x:                       1
    landing_page_enable:             1
    landing_owner:                   my name
    landing_title:                   my name
    landing_subtitle:                Dogs
    landing_facebook:                
    landing_flickr:                  
    landing_twitter:                 
    landing_instagram:               
    landing_youtube:                 
    landing_background:              dist/lion.jpg
    site_title:                      Photography
    site_copyright_enable:           1
    site_copyright_begin:            2021
    site_copyright_end:              2021
    additional_footer_text:          
    display_social_in_gallery:       0
    public_search:                   0
    SL_enable:                       0
    SL_for_admin:                    0
    public_recent:                   0
    recent_age:                      1
    public_starred:                  0
    downloadable:                    0
    photos_wraparound:               1
    map_display:                     0
    zip64:                           1
    map_display_public:              0
    map_provider:                    Wikimedia
    force_32bit_ids:                 0
    map_include_subalbums:           0
    update_check_every_days:         3
    has_exiftool:                    0
    share_button_visible:            0
    import_via_symlink:              0
    has_ffmpeg:                      0
    location_decoding:               0
    location_decoding_timeout:       30
    location_show:                   0
    location_show_public:            0
    rss_enable:                      0
    rss_recent_days:                 7
    rss_max_items:                   100
    prefer_available_xmp_metadata:   0
    editor_enabled:                  1
    lossless_optimization:           0
    swipe_tolerance_x:               150
    swipe_tolerance_y:               250
    local_takestamp_video_formats:   .avi|.mov
    log_max_num_line:                1000
    unlock_password_photos_with_url_param: 0
    nsfw_visible:                    1
    nsfw_blur:                       0
    nsfw_warning:                    0
    nsfw_warning_admin:              0`

**Comment by kamil4** [comment]
Can you try the fix from #893 and report back? Basically, you need to replace the file `Lychee/app/Actions/Photo/Archive.php` with the contents of https://raw.githubusercontent.com/LycheeOrg/Lychee/71efcfe8cf4dd2c965cf9a0e07948e51a4b7dcf3/app/Actions/Photo/Archive.php

**Comment by Flecko** [comment]
Perfect now it works. Thanks for the support, great work.
