### ISSUE TITLE
Help on installation.

### ISSUE THREAD

**Issue by JaseNZC** [LycheeOrg/Lychee#896]
Followed instruction of installation with compose which went off fine.

Changed .env file and added in details for mysql server.

First error showed some dirs were not writable which were easy fix. 

Point browser at Lychee just results in following.

http://192.168.1.203/install.   - This just results in a 404 not found error.

Not sure what I have done wrong mod_rewrite is on and no errors showing up in apache logs.

On latest apache/php/mysql.

Any direction would be most helpful thanks.

**Comment by ildyria** [comment]
Hi, thank you for opening an issue. In order to optimally help you, please fill up the data requested...

> ### Output of the diagnostics  [REQUIRED]
> *(Settings => Diagnostics or https://example.com/Diagnostics or `php artisan lychee:diagnostics`)*

And next question, is your apache pointing to `/var/www/html/lychee` or `/var/www/html/lychee/public` ?

**Comment by JaseNZC** [comment]
Server is pointing at /var/www/html/lychee/public

`Diagnostics
-----------
Warning: Dropbox import not working. dropbox_key is empty.
Warning: You may experience problems when uploading a photo of large size. Take a look in the FAQ for details.
Warning: You may experience problems when uploading a photos of large size. Take a look in the FAQ for details.
Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.

System Information
------------------
Lychee Version (git):            master (cf9bcfb) - Data not in Cache
DB Version:                      4.2.1

composer install:                --no-dev
APP_ENV:                         production
APP_DEBUG:                       false

System:                          Linux
PHP Version:                     7.4
Max uploaded file size:          2M
Max post size:                   8M
MySQL Version:                   8.0.23

Imagick:                         1
Imagick Active:                  1
Imagick Version:                 1690
GD Version:                      2.2.5

Config Information
------------------
version:                         040201
check_for_updates:               0
sorting_Photos_col:              takestamp
sorting_Photos_order:            ASC
sorting_Albums_col:              max_takestamp
sorting_Albums_order:            ASC
imagick:                         1
skip_duplicates:                 0
small_max_width:                 0
small_max_height:                360
medium_max_width:                1920
medium_max_height:               1080
lang:                            en
layout:                          1
image_overlay:                   1
image_overlay_type:              desc
default_license:                 none
compression_quality:             90
full_photo:                      1
delete_imported:                 0
Mod_Frame:                       1
Mod_Frame_refresh:               30
thumb_2x:                        1
small_2x:                        1
medium_2x:                       1
landing_page_enable:             0
landing_owner:                   John Smith
landing_title:                   John Smith
landing_subtitle:                Cats, Dogs & Humans Photography
landing_facebook:                https://www.facebook.com/JohnSmith
landing_flickr:                  https://www.flickr.com/JohnSmith
landing_twitter:                 https://www.twitter.com/JohnSmith
landing_instagram:               https://instagram.com/JohnSmith
landing_youtube:                 https://www.youtube.com/JohnSmith
landing_background:              dist/cat.jpg
site_title:                      Lychee v4
site_copyright_enable:           1
site_copyright_begin:            2019
site_copyright_end:              2019
additional_footer_text:          
display_social_in_gallery:       0
public_search:                   0
SL_enable:                       0
SL_for_admin:                    0
public_recent:                   0
recent_age:                      1
public_starred:                  0
downloadable:                    0
photos_wraparound:               1
map_display:                     0
zip64:                           1
map_display_public:              0
map_provider:                    Wikimedia
force_32bit_ids:                 0
map_include_subalbums:           0
update_check_every_days:         3
has_exiftool:                    1
share_button_visible:            0
import_via_symlink:              0
has_ffmpeg:                      1
location_decoding:               0
location_decoding_timeout:       30
location_show:                   1
location_show_public:            0
rss_enable:                      0
rss_recent_days:                 7
rss_max_items:                   100
prefer_available_xmp_metadata:   0
editor_enabled:                  1
lossless_optimization:           0
swipe_tolerance_x:               150
swipe_tolerance_y:               250
local_takestamp_video_formats:   .avi|.mov
log_max_num_line:                1000
unlock_password_photos_with_url_param: 0
nsfw_visible:                    1
nsfw_blur:                       0
nsfw_warning:                    0
nsfw_warning_admin:              0`

**Comment by JaseNZC** [comment]
Sorry you can delete this now, My fault for not changing non to all in the apache config "doh"

**Comment by ildyria** [comment]
No worries. :)

**Comment by michelle0812** [comment]
Dear all,
In my state, I got 404 not found like this → The requested URL /Lychee/public/install was not found on this server.
Many thanks.

**Comment by ildyria** [comment]
@michelle0812 please check this: https://lycheeorg.github.io/docs/faq.html#i-have-an-error-404-and-im-using-apache-what-can-i-do
