### ISSUE TITLE
Deleting User which owns albums breaks Lychee.

### ISSUE THREAD

**Issue by ildyria** [LycheeOrg/Lychee#902]
### Detailed description of the problem [REQUIRED]

see #900 

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Create user A with upload rights.
2. Log as user A and create an album
3. Log as admin and delete user A.
4. **BOUM**

### Solutions

1. Forbid User deletion if they still own albums
2. If a user is delete, all the pictures and albums they are are deleted.
3. If a user is delete, all the pictures and albums have their ownership transferred to admin.

Pick your poison.

**Comment by haivala** [comment]
3

**Comment by d7415** [comment]
I would also vote 3, with perhaps an option for 2 (i.e. an "also delete all of their photos/albums" checkbox)

**Comment by kamil4** [comment]
While they are all somewhat acceptable, I'll vote for 1 :smiley:. I would be OK with 2 if there was a confirmation dialog in case there are any albums/photos.

**Comment by haivala** [comment]
1.5 forbid the deletion but then admin could disable the user

**Comment by haivala** [comment]
actually I change my vote to: all of them

**Comment by nagmat84** [comment]
The problem will be solved by the linked PR. With this PR the admin cannot delete users who still own an album. The admin must first delete the affected albums or change ownership.
