### ISSUE TITLE
Server error or API not found

### ISSUE THREAD

**Issue by 13017565173** [LycheeOrg/Lychee#906]
![屏幕截图 2021-02-05 005522](https://user-images.githubusercontent.com/56523675/106927314-ffb29080-674c-11eb-91d9-068dc38eda83.png)

### Output of the diagnostics  [REQUIRED]
*(Settings => Diagnostics or https://example.com/Diagnostics or `php artisan lychee:diagnostics`)*
    Diagnostics
    -----------
    Warning: Dropbox import not working. dropbox_key is empty.

    System Information
    ------------------
    Lychee Version (release):        4.2.1
    DB Version:                      4.2.1
    
    composer install:                --no-dev
    APP_ENV:                         local
    APP_DEBUG:                       true
    
    System:                          Linux
    PHP Version:                     7.4
    Max uploaded file size:          64M
    Max post size:                   200M
    MySQL Version:                   5.7.32-log
    
    Imagick:                         1
    Imagick Active:                  1
    Imagick Version:                 1802
    GD Version:                      bundled (2.1.0 compatible)

    Config Information
    ------------------
    version:                         040201
    check_for_updates:               0
    sorting_Photos_col:              takestamp
    sorting_Photos_order:            ASC
    sorting_Albums_col:              max_takestamp
    sorting_Albums_order:            ASC
    imagick:                         1
    skip_duplicates:                 0
    small_max_width:                 0
    small_max_height:                360
    medium_max_width:                1920
    medium_max_height:               1080
    lang:                            en
    layout:                          1
    image_overlay:                   1
    image_overlay_type:              desc
    default_license:                 none
    compression_quality:             90
    full_photo:                      1
    delete_imported:                 0
    Mod_Frame:                       1
    Mod_Frame_refresh:               30
    thumb_2x:                        1
    small_2x:                        1
    medium_2x:                       1
    landing_page_enable:             0
    landing_owner:                   John Smith
    landing_title:                   John Smith
    landing_subtitle:                Cats, Dogs & Humans Photography
    landing_facebook:                https://www.facebook.com/JohnSmith
    landing_flickr:                  https://www.flickr.com/JohnSmith
    landing_twitter:                 https://www.twitter.com/JohnSmith
    landing_instagram:               https://instagram.com/JohnSmith
    landing_youtube:                 https://www.youtube.com/JohnSmith
    landing_background:              dist/cat.jpg
    site_title:                      Lychee v4
    site_copyright_enable:           1
    site_copyright_begin:            2019
    site_copyright_end:              2019
    additional_footer_text:          
    display_social_in_gallery:       0
    public_search:                   0
    SL_enable:                       0
    SL_for_admin:                    0
    public_recent:                   0
    recent_age:                      1
    public_starred:                  0
    downloadable:                    0
    photos_wraparound:               1
    map_display:                     0
    zip64:                           1
    map_display_public:              0
    map_provider:                    Wikimedia
    force_32bit_ids:                 0
    map_include_subalbums:           0
    update_check_every_days:         3
    has_exiftool:                    2
    share_button_visible:            0
    import_via_symlink:              0
    has_ffmpeg:                      0
    location_decoding:               0
    location_decoding_timeout:       30
    location_show:                   1
    location_show_public:            0
    rss_enable:                      0
    rss_recent_days:                 7
    rss_max_items:                   100
    prefer_available_xmp_metadata:   0
    editor_enabled:                  1
    lossless_optimization:           0
    swipe_tolerance_x:               150
    swipe_tolerance_y:               250
    local_takestamp_video_formats:   .avi|.mov
    log_max_num_line:                1000
    unlock_password_photos_with_url_param: 0
    nsfw_visible:                    1
    nsfw_blur:                       0
    nsfw_warning:                    0
    nsfw_warning_admin:              0

**Comment by kamil4** [comment]
Sorry, we need more details if we are to be able to help. _Server error or API not found_ is a generic error message from Lychee and it can be due to just about anything.

Is this a new installation? Do you get the error when you try to load Lychee for the first time, or does it fail only when you try to perform a particular action?

In the debug console (thanks for including it!) it would probably be more useful if you showed us the output of the "Network" tab (fourth one from the left in Chrome).

**Comment by 13017565173** [comment]
This is a new installation，The output of the"Network" tab is as follows
![1612490213(1)](https://user-images.githubusercontent.com/56523675/106979137-a3755e00-6798-11eb-9a75-ff3aced1aea5.png)

**Comment by kamil4** [comment]
This looks like incorrectly configured URL rewriting. Depending on the http server you use, please see https://lycheeorg.github.io/docs/faq.html#i-have-an-error-404-and-im-using-apache-what-can-i-do or https://lycheeorg.github.io/docs/faq.html#i-have-an-error-404-and-im-using-nginx-what-can-i-do.

The following sections of the Lychee manual should be relevant: https://lycheeorg.github.io/docs/upgrade.html#preparing-the-server, https://lycheeorg.github.io/docs/installation.html#web-server-configuration.

I hope this helps!
