### ISSUE TITLE
Error: "Album JSON not found!"

### ISSUE THREAD

**Issue by elvisef** [LycheeOrg/Lychee#912]
### Detailed description of the problem [REQUIRED]
I am having a weird problem. Do these albums need to be indexed or something, after a migration ?
Generally: an error occurred, and says that JSON for an album is not found (?)

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Go to search and fill in with desired name
2. Wait for search to show some results
3. Choose an album and right click on one
4. In the v3 version there was a menu under a right click, here there is no menu
5. What happens after a click, error occurred

**Screenshots**
![2021-02-11_10-20](https://user-images.githubusercontent.com/25976749/107619337-4e7f8f00-6c53-11eb-8624-04f2f2d55b52.png)

### Output of the diagnostics  [REQUIRED]

> Diagnostics
> -----------
> Warning: Dropbox import not working. dropbox_key is empty.
> Warning: You may experience problems when uploading a photo of large size. Take a look in the FAQ for details.
> Warning: You may experience problems when uploading a photos of large size. Take a look in the FAQ for details.
> Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.
> 
> System Information
> ------------------
> Lychee Version (git):            master (7e352be) - Data not in Cache
> DB Version:                      4.2.1
> 
> composer install:                --no-dev
> APP_ENV:                         production
> APP_DEBUG:                       true
> 
> System:                          Linux
> PHP Version:                     7.4
> Max uploaded file size:          20971520
> Max post size:                   20971520
> MySQL Version:                   5.7.33
> 
> Imagick:                         1
> Imagick Active:                  1
> Imagick Version:                 1687
> GD Version:                      2.2.5
> 
> Config Information
> ------------------
> version:                         040201
> check_for_updates:               0
> sorting_Photos_col:              id
> sorting_Photos_order:            DESC
> sorting_Albums_col:              id
> sorting_Albums_order:            DESC
> imagick:                         1
> skip_duplicates:                 0
> small_max_width:                 0
> small_max_height:                360
> medium_max_width:                1920
> medium_max_height:               1080
> lang:                            en
> layout:                          1
> image_overlay:                   0
> image_overlay_type:              exif
> default_license:                 none
> compression_quality:             90
> full_photo:                      1
> delete_imported:                 1
> Mod_Frame:                       1
> Mod_Frame_refresh:               30
> thumb_2x:                        1
> small_2x:                        1
> medium_2x:                       1
> landing_page_enable:             0
> landing_owner:                   John Smith
> landing_title:                   John Smith
> landing_subtitle:                Cats, Dogs & Humans Photography
> landing_facebook:                https://www.facebook.com/JohnSmith
> landing_flickr:                  https://www.flickr.com/JohnSmith
> landing_twitter:                 https://www.twitter.com/JohnSmith
> landing_instagram:               https://instagram.com/JohnSmith
> landing_youtube:                 https://www.youtube.com/JohnSmith
> landing_background:              dist/cat.jpg
> site_title:                      Lychee v4
> site_copyright_enable:           1
> site_copyright_begin:            2019
> site_copyright_end:              2019
> additional_footer_text:          
> display_social_in_gallery:       0
> public_search:                   0
> SL_enable:                       0
> SL_for_admin:                    0
> public_recent:                   0
> recent_age:                      1
> public_starred:                  0
> downloadable:                    0
> photos_wraparound:               1
> map_display:                     0
> zip64:                           1
> map_display_public:              0
> map_provider:                    Wikimedia
> force_32bit_ids:                 0
> map_include_subalbums:           0
> update_check_every_days:         3
> has_exiftool:                    0
> share_button_visible:            0
> import_via_symlink:              0
> has_ffmpeg:                      0
> location_decoding:               0
> location_decoding_timeout:       30
> location_show:                   1
> location_show_public:            0
> rss_enable:                      0
> rss_recent_days:                 7
> rss_max_items:                   100
> prefer_available_xmp_metadata:   0
> editor_enabled:                  1
> lossless_optimization:           0
> swipe_tolerance_x:               150
> swipe_tolerance_y:               250
> local_takestamp_video_formats:   .avi|.mov
> log_max_num_line:                1000
> unlock_password_photos_with_url_param: 0
> nsfw_visible:                    1
> nsfw_blur:                       0
> nsfw_warning:                    0
> nsfw_warning_admin:              0
> map_display_direction:           1
> album_subtitle_type:             oldstyle
> 

### Browser and system
OS: **Debian 10.x**
Browser: **Firefox 78.x**

**Comment by ildyria** [comment]
> Do these albums need to be indexed or something, after a migration ?

No. :)

> Generally: an error occurred, and says that JSON for an album is not found (?)

Most likely a bug on the front-end for that one.

I'm really sorry that you are finding all those bugs, you seem like a magnet to them. :sweat_smile:

**Comment by elvisef** [comment]
> I'm really sorry that you are finding all those bugs, you seem like a magnet to them. sweat_smile

Yeah.. all the github stuff I am using a lot, a good stuff like this Lychee, is making me think I won't survive : ]
But I need it anyway, so... would be nice to have this working :P

Anyway, I just wanted to change one of my album's name, and no menu, error... it just happened...

**Comment by ildyria** [comment]
Well, at least I can guarantee you that this will be fixed with the new front end, SoonTM.

But there should be some fixes for the current front-end for now (sadly I can't work on it as I have more pressing matters at hand).

**Comment by elvisef** [comment]
Will `git pull` be enough sometimes ?

**Comment by ildyria** [comment]
> Will `git pull` be enough sometimes ?

if your git hooks are set (which I think you did with `composer install`), it is indeed the simplest way to update yes. :smiley:

**Comment by kamil4** [comment]
It appears to be due to a bug in the recently added support for selecting a cover thumb. Should be an easy fix.

@elvisef, do you have the front end checked out as well and npm set up to recompile it or did you git clone just the backend?

**Comment by kamil4** [comment]
OK, should be fixed now. Please resync.

**Comment by elvisef** [comment]
> if your git hooks are set (which I think you did with `composer install`), it is indeed the simplest way to update yes. smiley

Alright : )

> @elvisef, do you have the front end checked out as well and npm set up to recompile it or did you git clone just the backend?

Just git cloned.

> OK, should be fixed now. Please resync.

Thanks, it works now : )
