### ISSUE TITLE
[Enhancement] Limit the parallel processing on upload

### ISSUE THREAD

**Issue by miahi** [LycheeOrg/Lychee#913]
I have a memory and CPU limited server (shared hosting) and when I try to upload a large number of photos it seems that each of them creates a process for resizing (so if I drag and drop 100 photos, 100 threads will start). This hits the CPU/memory limit and the processes crash, so I get a lot of fails in the status, or the upload crashes completely because the upload process hit the limit and the whole page crashes. The limit varies with the photo dimensions, probably because the high resolution photos need more CPU time and memory to resize. 

It would be great if only a limited number of processing threads can be set to start in parallel, and all the other uploads wait until there is a processing slot for them.

**Comment by kamil4** [comment]
Agreed. We discussed some of this recently in #903 as well, although the fix for that particular bug will be different.

**Comment by kamil4** [comment]
As a workaround for now, assuming that you have file access to that server, you can upload the files to the server using ftp/ssh/whatever and then use Lychee's _Import from Server_ feature. Importing is then done one-by-one (sequentially).

**Comment by miahi** [comment]
Good to know that _Import from server_ is sequential (and yes, I hit the #903 also). Thank you!

**Comment by ildyria** [comment]
should be fixed now with #919
