### ISSUE TITLE
[question] wrapping album titles

### ISSUE THREAD

**Issue by elvisef** [LycheeOrg/Lychee#914]
Just a question, is there a way to somehow wrap album titles/words on the list ?
Or maybe any of the font sizes.. do I need to use "Personalize your CSS" setting to do that ?

Or maybe there is a quick (not fix but) addon to do this ?
I just want to see the whole sentence, whole title that is being showed on album.

I did not find any suitable option.

![2021-02-11_18-46](https://user-images.githubusercontent.com/25976749/107676494-7d205880-6c99-11eb-9c78-9dcb6699f41d.png)

**Comment by kamil4** [comment]
Yeah, you can easily do it by customizing the CSS. I believe the following will do what you want:
```
.content .album .overlay h1 {
    white-space: normal;
}   
```

**Comment by elvisef** [comment]
I believe I am a very good tester.. I have a bad day again...
![2021-02-12_11-02](https://user-images.githubusercontent.com/25976749/107754553-ed72bc80-6d21-11eb-9e0d-c497b9a970d1.png)

**Comment by ildyria** [comment]
I will be able to have a look at it tomorrow if @kamil4 does not beat me at it.

**Comment by elvisef** [comment]
> I will be able to have a look at it tomorrow if @kamil4 does not beat me at it.

okie dokie : )
By the way, the "API not found" problem existed before I wrote it now.. but it happened in specific situations only.. I did not test it thoroughly.

**Comment by ildyria** [comment]
By the way for faster "support", you may want to drop by our gitter: https://gitter.im/LycheeOrg/Lobby (you can login with your github ID there). :smiley:

**Comment by kamil4** [comment]
You can always simply edit the `user.css` file in `public/dist/`. That's what I do...

Using the UI actually appears to work _if_ the permissions are set correctly (i.e., `public/dist/` writable by the http daemon). It's the proper error handling that's missing.

**Comment by d7415** [comment]
>  _if_ the permissions are set correctly (i.e., `public/dist/` writable by the http daemon).

I thought that was in the Diagnostics page... but it's not listed in @elvisef's diagnostics in #911, so maybe not.

**Comment by kamil4** [comment]
@d7415 I did check this issue for the Diagnostics output but  I was too lazy to check his other reports :smiley:.

I do see the warning in Diagnostics on my devel Lychee instance so you're right that it's there.  Still, on my production one I get no warning and it still fails, with the following error in `laravel.log`:
```
production.ERROR: chmod(): Operation not permitted {"exception":"[object] (ErrorException(code: 0): chmod(): Operation not permitted at /home/kamil/Lychee/vendor/league/flysystem/src/Adapter/Local.php:368)
```
I think it's because my `user.css`, while it is group-writable by the http daemon, is not owned by that daemon. This `chmod` is not just unnecessary, it's clueless and harmful :disappointed:. Still, we are not the ones issuing it, we just do:
https://github.com/LycheeOrg/Lychee/blob/cc6362a475358630dfce7e4fd532acf678ce94cf/app/Http/Controllers/Administration/SettingsController.php#L335
I don't think I've seen this error in the past so it's probably due to an update of a dependency...

**Comment by elvisef** [comment]
> By the way for faster "support", you may want to drop by our gitter: https://gitter.im/LycheeOrg/Lobby (you can login with your github ID there). smiley

Thanks, I'll try this : )



> I think it's because my `user.css`, while it is group-writable by the http daemon, is not owned by that daemon.

Generally I had good permissions, but due to "git pull" updates (I suppose) some new files were created (ex. php, logs_new - what are these files ?) - or maybe after a migration ? Anyway, group for some files were not my http daemon, but just me. Because I have an owner for me, and a group for file is http daemon. Now I've changed a group for all files to daemon and hmm.... nothing changed :P

The crucial point is, the CSS change **kamil4** suggested was fine, and have been saved successfully, despite the error.
Firstly I was shocked because the list looked great - all names were wrapped now. And then I've looked into settings and it's on its place.

![2021-02-12_21-49](https://user-images.githubusercontent.com/25976749/107821654-20966980-6d7d-11eb-88eb-5623aa7e5272.png)


So.. Something need to be fixed I suppose : ))

Laravel... I've never tried it, but maybe it's the right time... ^^ better not : ]

**Comment by ildyria** [comment]
> Laravel... I've never tried it, but maybe it's the right time... ^^ better not : ]

It is not that complex. If you want to dig in our code you may want to have a look at:

- https://lycheeorg.github.io/docs/read-more.html
- https://lycheeorg.github.io/docs/structure.html

:smiley:

**Comment by ildyria** [comment]
@elvisef is this fixed ? :)

**Comment by kamil4** [comment]
The original question is addressed. The server error message if `user.css` is not owned by Apache (but is writable) is not. I just experimented with it and removing `'visibility' => 'public'` from `config/filesystems.php` for `dist` fixes it for me. But I'm not sure if that's a good general solution (what if the umask is set to `077`)?

**Comment by elvisef** [comment]
> 
> 
> @elvisef is this fixed ? :)

Hmm... hard to say.. because I left my Lychee's tab open and... the session is gone.
But I wanted to "go back" (with an arrow on the left), and.... the same error appears.
Is this normal ? Shouldn't the user be redirected to the login page ?

Everywhere where something is wrong, an error with API appears : ]

![firefox_2uoWvCuiPe](https://user-images.githubusercontent.com/25976749/107968682-f4622f00-6fae-11eb-9963-57811c4643ed.png)

**Comment by kamil4** [comment]
Yeah, it's a generic error message whenever the server responds in an unexpected way.

Yes, we do have code in place to redirect the user to the front page when a timeout occurs. It seems to work in simple cases at least...

**Comment by kamil4** [comment]
OK, I played around with it a bit and the timeouts don't seem to be handled correctly anymore. Sigh... I hate when bugs we fixed in the past mysteriously resurface... :cry:

**Comment by kamil4** [comment]
@elvisef The timeout issue will be fixed with https://github.com/LycheeOrg/Lychee-front/pull/248. In general though, I recommend that you try to open a new issue for each bug you find :smiley:.

**Comment by elvisef** [comment]
> I recommend that you try to open a new issue for each bug you find smiley.

Yeah, I thought about it : ]
beware... "git pulls" are coming...

**Comment by qwerty287** [comment]
I think we can close this?
