### ISSUE TITLE
The "BACK" arrow button does not go back to the place I was before

### ISSUE THREAD

**Issue by elvisef** [LycheeOrg/Lychee#920]
### Detailed description of the problem [REQUIRED]
Generally, I was searching for some pictures in my image library.
But when I tried to go back, it did not go back to the place I was before (i.e. search results).

I think I should be able to go back where I was before, not to the parent gallery of the one I entered.
If I wanted to go to the specific gallery, I would find it by name (search result told me how it's named) and enter it manually.

That's my opinion : ) I was just confused how it works, but maybe it's normal.

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. I've searched for "nawi" (it gives me 3 results - two 2nd level galleries and one 1st level gallery with these two 2nd level inside)
2. Now I entered the one of them
3. Next I wanted to go back using the arrow far on the left
4. And... I am not back to the search results, but in the 1st level album of the 2nd level gallery I entered before

**Screenshots**
1) ![firefox_2021-02-14_10-40-42](https://user-images.githubusercontent.com/25976749/107873335-0a3dfa00-6eb2-11eb-92ec-1fd5bb7dbb1d.png)
2) ![firefox_2021-02-14_10-42-06](https://user-images.githubusercontent.com/25976749/107873337-0f9b4480-6eb2-11eb-8003-35a4c1a86692.png)
3) ![firefox_2021-02-14_10-42-29](https://user-images.githubusercontent.com/25976749/107873340-132ecb80-6eb2-11eb-86ba-f96e8d6d9178.png)

### Output of the diagnostics  [REQUIRED]
Not needed.

### Browser and system
**OS:** Windows 7 PRO
**Browser:** 84.0.2 (32 bity)

**Comment by kamil4** [comment]
Yeah, I hate how search support is implemented in the front end; it's a massive hack full of limitations.

I started working on fixing some of this in https://github.com/LycheeOrg/Lychee-front/pull/250. Feel free to give it a try and see if it makes things better. Note that you'll need to switch to a development branch of the front end and recompile it on your own (see https://lycheeorg.github.io/docs/node.html).

**Comment by kamil4** [comment]
OK, can you try the fixes from #931? You simply need to pull the latest updates via git and switch to the `fix-search` branch. No front end recomplication needed :smiley:. I'm interested in feedback both with respect to this issue and to #921.

**Comment by kamil4** [comment]
@elvisef Do you have any feedback on #931?

**Comment by elvisef** [comment]
Sorry for the delay.... ; /
I've just tested it and it still goes wrong. I pulled the newest changes and change branch to "fix-search" as You wrote.
I know that some time has passed but maybe it is still valid.

![putty_4BBCv1ZPxP](https://user-images.githubusercontent.com/25976749/114158848-73c40d00-9925-11eb-9f48-e7b5df7e2324.png)

For example:

1. I search for: "zegarek"
2. Search results show a few elements
3. I click one of them, one "zegarek", and it takes me to the "zegarki" album
4. What is happening next, is if I click "BACK" arrow button, it takes me back to... NOT search results but to the zegarek's parent album

**Comment by kamil4** [comment]
Weird, I'll need to test it again, this should've worked... Did you hit "reload" in your browser after switching the branch?

Just to make sure that I understand: are your search results photos or albums?

**Comment by elvisef** [comment]
Yes, I hit "reload" in my browser after the pull+branch change.
I am searching for an album. An album has "zegarek" in its name, so the results shows albums.
And I go inside chosen album, then I want to go back, using an arrow.

I suppose I do not have to clear my browser cache in order to see a branch change : )
Let me know, maybe it's my fault but I've checked this a few times already.

**Comment by elvisef** [comment]
One more thing, lf I go back to the main screen (by hitting arrow two times, one from the album itself, and second time from the parent album) the search term still persists in the search field. Weird thing because if I click on it, it just updates the screen and searches for the term once more, showing me results. This should happen ? Shouldn't the filed be cleared after going back to the main screen ?
