### ISSUE TITLE
The "BACK" arrow button shows all results instead of found only

### ISSUE THREAD

**Issue by elvisef** [LycheeOrg/Lychee#921]
### Detailed description of the problem [REQUIRED]
If I search for something using the far rgiht textbox, the results are correct.
But If I wanted to go back now, all galleries are shown - but the textbox still shows the name I entered.
Same happens with ESC button, and for 2nd level galleries, when You're back in the 1st level (current functionality) and want to go back to the top level. Confusing..

When I click "back" it should filter again, and not show all results, because I want to search for something and go back to the results to choose any other result to check. It is confusing.

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Got to the 1st level gallery
2. Now click an arrow to go back to... search results (?)
3. You will see all results (not filtered by Your textbox phrase) but the textbox name You've entered is still there

**Screenshots**
1. ![firefox_2021-02-14_10-57-11](https://user-images.githubusercontent.com/25976749/107873646-3c505b80-6eb4-11eb-9733-49085aeb9a70.png)
2. ![firefox_2021-02-14_10-57-36](https://user-images.githubusercontent.com/25976749/107873648-3fe3e280-6eb4-11eb-96c4-f997f2fef6ac.png)
3. ![firefox_2021-02-14_10-58-05](https://user-images.githubusercontent.com/25976749/107873650-42463c80-6eb4-11eb-83e6-be87776377ef.png)

### Output of the diagnostics  [REQUIRED]
Not needed I think.

### Browser and system
**OS:** Win7 PRO
**Browser:** 84.0.2 (32 bity)

**Comment by d7415** [comment]
FWIW screen 3 doesn't claim to be search results - you can see that from the top where it says "albums".

**Comment by elvisef** [comment]
> 
> 
> FWIW screen 3 doesn't claim to be search results - you can see that from the top where it says "albums".

Yes, because on the screen 2 I clicked "back" arrow button. This is the effect.

**Comment by d7415** [comment]
> Yes, because on the screen 2 I clicked "back" arrow button. This is the effect.

Just clarifying as you described it as "all results" as if it was a broken search rather than not-a-search.

**Comment by kamil4** [comment]
Yeah, it is a confusing picture... I feel that either the search box should be cleared or the search results should be shown. The latter behavior should make it easier to implement at least a semi-consistent back button behavior (I started working on it in https://github.com/LycheeOrg/Lychee-front/pull/250 but haven't gotten to fix this issue yet).

**Comment by kamil4** [comment]
Actually, https://github.com/LycheeOrg/Lychee-front/pull/250 should already fix the case shown in the pictures: clicking on an album in search results and clicking the back button in that album does now bring one back to the search results. Same with clicking on photos in search results (I still need to add next/prev support there though).

The case that can't be easily fixed though is if a user clicks on an album in search results and that album contains subalbums. Clicking on those subalbums erases the tweaks I made so clicking the back button twice will not bring one back to the search results.

**Comment by elvisef** [comment]
I don't know how it works exactly, but in fact there is possibility that the search field is being cleared after clicking the "back" arrow button. Maybe that's why search results are "skipped" every time. 

Anyway the ESC button is very functional here, I can simply and quickly go back to every place I was earlier. Just wondering if the ESC works same as the "back arrow".

**Comment by ildyria** [comment]
> Just wondering if the ESC works same as the "back arrow".

It was supposed to yes.
