### ISSUE TITLE
[feature] Would it be possible ? : )

### ISSUE THREAD

**Issue by elvisef** [LycheeOrg/Lychee#922]
I've wrote down some feautres I would like to have, based on my Luchee use experience : )

I'll list it here:

> **1. Option to search 1st level (or current level if we're at a certain level of album hierarchy) albums only**
> ~~2. Official (not advanced as it is now) options to sort albums (each albums leve separately ? + default options, would be nice)~~
> ~~**3. Additional users with permissions (I would like to share my whole albums account with my Mother, Father, siblings, friends etc..), not by sharing, I just want to make they have almost full permissions to read it, use it**~~
> 4. Import albums from Nextcloud ? (I don't know how does Dropbox work, cause I do not have an account, but I am using Nextcloud, and WebDav is there).
> **5. (issue) After changing advanced sorting the main list of albums is not refreshed (only the > 2nd level) - can this be updated just after leaving settings sections ? : )**
> 6. A filter in the (for example) "move to" menu - a small search bar to filter all albums by name, quick search, quick filter or something.
> **7. A possibility to use + or - to collapse/reveal elements by hierarchy in the (for example) "move to" menu. I have a long list of albums.. not so long, but it's log enough to make problems.**
> 8. A way to "highlight" top level albums names, in the (for example) "move to" menu. Would be nice to have option in settings to change behaviour (also applies to previous points).
> ~~**9. Drag & drop for galleries ? Would be nice but not necessary. I was about to move one album inside the other album, which on the main list was just next to. But unfortunately while using "move to" I needed to find it first on a very logn list of albums, where all are uncollapsed, and unhighlighted anyhow. Very difficult task...**~~
> 10. If I am using "move to" menu, and I choose the target place to move images to, a popup question is shown. But.... the menu is gone. And if I choose to "cancel" I need to do all the thing I've done before again. Yep, would be nice to have a cancel and go back to the menu, because sometimes I will do it too fast, unconciously and... everything is gone.
> **11. Cropping images for album album covers. For instance, I have a picture that is too long, I could choose that crop "bottom" or "top", so the "square" would be chosen based on my setting. I know that we have external applications/software, but just for a quick crop, without forcing to use external soft. I thing this could be achieved using for example "imagemagick".**

There is no big description for every point. We can discuss it here of course.
These are feature requests, sugestions, something like this : )

Sorry for my bad english, but I wanted to make it possible to use more functionality here.

Let me know what is not understandable, I will try to explain.
And say what can be done and what not of course.

Some screens:
![firefox_2021-02-14_12-14-50](https://user-images.githubusercontent.com/25976749/107878504-75e48f00-6ed3-11eb-8375-375f55f9dff1.png)
![firefox_2021-02-14_12-23-39](https://user-images.githubusercontent.com/25976749/107878502-75e48f00-6ed3-11eb-8caa-b1dc05a2840b.png)
![firefox_2021-02-14_13-08-32](https://user-images.githubusercontent.com/25976749/107878497-74b36200-6ed3-11eb-81d6-2252d67e6a62.png)

**Comment by d7415** [comment]
> > **1. Option to search 1st level (or current level if we're at a certain level of album hierarchy) albums only**

I'm not sure I see a use case for non-recursive search.

> > 4. Import albums from Nextcloud ? (I don't know how does Dropbox work, cause I do not have an account, but I am using Nextcloud, and WebDav is there).

#580 

> > 10. If I am using "move to" menu, and I choose the target place to move images to, a popup question is shown. But.... the menu is gone. And if I choose to "cancel" I need to do all the thing I've done before again. Yep, would be nice to have a cancel and go back to the menu, because sometimes I will do it too fast, unconciously and... everything is gone.

I wouldn't expect the menu to still be open here. That's not how context menus usually work.

> > **11. Cropping images for album album covers. For instance, I have a picture that is too long, I could choose that crop "bottom" or "top", so the "square" would be chosen based on my setting. I know that we have external applications/software, but just for a quick crop, without forcing to use external soft. I thing this could be achieved using for example "imagemagick".**

This is possible. I'd have to remind myself what we just did to album thumbnails to know how much of a pain (or otherwise) this would be.


This is a long list, so individual issues would have been a pain, but as a rule 11 feature requests in one issue isn't going to go well. Also 6, 7 and 8 seem to be different approaches to the same thing.

Completely aside, the abuse of the quote function and the alternating bold text upsets me on some level :P

> Sorry for my bad english, but I wanted to make it possible to use more functionality here.

The english is fine :)

**Comment by kamil4** [comment]
I think 5 should be fixed now that #894 is merged.

11 is definitely doable using the tools we already have. The major effort would be coding a UI to enable it. I'm definitely _not_ volunteering :wink:.

**Comment by elvisef** [comment]
> I think 5 should be fixed now that #894 is merged.
> 
> 11 is definitely doable using the tools we already have. The major effort would be coding a UI to enable it. I'm definitely _not_ volunteering wink.

Alright, I will try to enter the code.. soon, and see what happens.

**Comment by kamil4** [comment]
> Alright, I will try to enter the code.. soon, and see what happens.

The way I _imagine_ it to work would be a button in the photo view, next to the rotate left / rotate right buttons, that enables a "crop selection" mode where a square outline is drawn over the image. The user can shift the outline (by grabbing in the center) or resize it (by grabbing one of the corners). There would probably need to be Accept and Cancel buttons as well. On Accept, we send the offset/size dimensions to the server, which does the rest (that's the easy part; we would just need to extend the code we already have).

**Comment by ildyria** [comment]
Most of those are now taken care of in the new front-end, the rest are duplicates of existing issues.
