### ISSUE TITLE
Polish translation

### ISSUE THREAD

**Issue by elvisef** [LycheeOrg/Lychee#923]
I am working on it, and it's almost done.
But some words made me think I cannot udnderstand it : ]

![2021-02-14_16-36](https://user-images.githubusercontent.com/25976749/107881158-5a818000-6ee3-11eb-845f-af7ef5c9b5a7.png)

Alright, what is a "sensitive" album ?
Maybe I did not read FAQ thoroughly but just in short, please.

Some words or sentences need to be longer, as for my language.
I tried to make it understandable and not so general in meaning some functions, in settings generally.

And if I'm done (I am working with GIT, but I am new to github pushing), do I need to use the master branch or how this should be properly done ?

**Comment by ildyria** [comment]
>Alright, what is a "sensitive" album ?


See here : https://github.com/LycheeOrg/Lychee/pull/822 :laughing: 

> And if I'm done (I am working with GIT, but I am new to github pushing), do I need to use the master branch or how this should be properly done ?

https://lycheeorg.github.io/docs/contributions.html#how-to-properly-submit-a-pull-request-to-lychee

**Comment by elvisef** [comment]
Alright, thanks, piece of cake ; )

One question, shouldn't "Owner" be in the locale files as well ?
![2021-02-14_19-32](https://user-images.githubusercontent.com/25976749/107885595-8c9edc00-6efb-11eb-8748-5c92da7b1370.png)

I could not find it there.

And one more, I could not find "Tags" in locales:
![2021-02-14_20-32](https://user-images.githubusercontent.com/25976749/107887061-cd9aee80-6f03-11eb-956c-d83a69d7f3aa.png)

It's when I wanted to edit tags for an album.

Ooops, one more : ) "About" is missing as well. While translating I think this should be easily changeable.
![2021-02-14_20-34](https://user-images.githubusercontent.com/25976749/107887125-1c488880-6f04-11eb-949c-0a28b5016e2d.png)

I'll try to find it in the code maybe. I will try to finish translating today or tomorrow max.
Will see how it looks :P

Anyway what exactly means "Take Date" or "Latest Take Date" ?
I suppose it could mean a date picture was taken, right ? Or not ?
It is confusing for me, sorry. If You could write what it means in other words, I will be happy.

**Comment by ildyria** [comment]
There might indeed be missing some parts as you noticed for Owner, Tags, and other.

Now to answer your simpler questions:
- "Take Date" is the date the picture is taken (obviously)
- "Latest Take Date" and "Oldest Take Date" refers respectively to the maximum and minimum value of "Take Date" in an album: your pictures may not be taken all on the same date. As a result, you may want to **order your albums by using the oldest picture in that album or the youngest**. This has no influence on the picture ordering inside the album, this is only of the album ordering.

**Comment by zaisty** [comment]
Hi @elvisef !
Im looking forward for Your Polish translation when it will be ready.
Keep up good work.
Thank You and good luck!

**Comment by elvisef** [comment]
Oh yeah, I had no time lately, but it is translated almost whole.
I will look into it today and let You know. Will try then to make a push with this translation.

I suppose, my translation will be changed somehow according to the most appropriate words or phrases used, by other users, but at least the polish will be usable : )

**Comment by elvisef** [comment]
Alright, I need help. I did what's written here: https://lycheeorg.github.io/docs/contributions.html#how-to-properly-submit-a-pull-request-to-lychee but can't push my changes due to 403 error... What am I doing wrong ?

![2021-07-17_19-07](https://user-images.githubusercontent.com/25976749/126044563-6c5ffcaa-5dc0-464d-8077-f2b3107854c3.png)

**Comment by ildyria** [comment]
Ah, I see the error. And it is our fault, we did not make it explicit that you had to create a fork of the repository.

https://github.com/LycheeOrg/LycheeOrg.github.io/issues/32 < Improve documentation...

You are trying to push it to the main repo, but because you are not part of the organization yo don't have such rights.

So. you need to do a fork of the repository, then you do
```
git remote add elvisef https://github.com/elvisef/Lychee/
git push -u elvisef <your branch name>
```
This will push the branch to your repository.
After which you can make a pull request between the branch on your repo and the master branch of this repository. :+1: 

If you have more questions, don't hesitate.

**Comment by elvisef** [comment]
Thanks for info. I wasn't aware.
Alright, I think the pull request was automatically added.
Let me know if everything is ok.

**Comment by ildyria** [comment]
https://github.com/LycheeOrg/Lychee/pull/1065/checks?check_run_id=3093988877#step:19:55 :)
You are missing some translations.

**Comment by elvisef** [comment]
Alright, so i will need to compare my file to the newest English..
I will do that asap I suppose.

**Comment by ildyria** [comment]
Done.
