### ISSUE TITLE
Is the "reuse" header needed if default is set ?

### ISSUE THREAD

**Issue by elvisef** [LycheeOrg/Lychee#924]
Look at my screenshot first:
![2021-02-14_20-41](https://user-images.githubusercontent.com/25976749/107887250-11dabe80-6f05-11eb-9ca6-ef4a55f25571.png)

I've made the album public visible and did not change any license settings.
It is set to default, so probably "no license".
So, is this alone header needed here ? It's shown while I am viewing a gallery being not logged in, just as a guest.

**Comment by ildyria** [comment]
Fixed.
