### ISSUE TITLE
Meta Description

### ISSUE THREAD

**Issue by danieldotnet** [LycheeOrg/Lychee#930]
Possibility to capture meta description for better web search.

**Comment by ildyria** [comment]
Hi,

Please be more descriptive about what you are talking about. This is hardly understandable in the sense that neither the title of this issue nor the content is clear.

Finally politeness goes a long way.

**Comment by danieldotnet** [comment]
OK, sorry for the short summary.
My idea is to optimize the photo gallery for search engines like Google.
Currently I don't see any possibility to add a meta description that will appear in the search results. Or even the generation of an XML sitemap for search engines.

**Comment by ildyria** [comment]
That will be possible with the new front end which will enable the access of meta data etc. But sadly this _new front end_ is pretty much a long term project on which I am working when I have free time (which is not the case at the moment). This actually is my next focus point for Lychee, but in a not so near future.

**Comment by danieldotnet** [comment]
OK - thank you.
