### ISSUE TITLE
"Move to" menu list scroll covered by a browser scrollbar

### ISSUE THREAD

**Issue by elvisef** [LycheeOrg/Lychee#934]
It happens only for every three far right positioned image boxes - so 3 counting from the right side.
The third one (the latest counting from the right), is almost good, but still half-covered.

![2021-02-20_19-27](https://user-images.githubusercontent.com/25976749/108606249-49d87a80-73b9-11eb-8b1d-4540d1d5ce4d.png)

Browser 1: Chromium Version 88.0.4324.146 (Developer Build) built on Debian 10.7, running on Debian 10.8 (64-bit)
Browser 2: Firefox 78.7.0esr (64 bity)
OS: Debian 10.x

I don't use GoogleChrome so I did not test it.

**Comment by kamil4** [comment]
Yeah, I seem to remember that in the past even the main Lychee content ignored the scrollbars, although thanks to the 30px margins that wasn't that big of a deal. I guess I didn't realize at the time that the dialog windows had the same problem...

**Comment by elvisef** [comment]
Perfect! Thanks. Works well.
