### ISSUE TITLE
Missed thumb in video uploaded in gallery

### ISSUE THREAD

**Issue by FrankiePustorino** [LycheeOrg/Lychee#935]
Hello @developer Team

When you upload any kind of video or media in Lychees gallery, the video is show only play button, Can be possible to enhance that by gathering the first frame of the video as thumb? "as it is in Youtube"

![image](https://user-images.githubusercontent.com/79408426/108627463-07b14680-7456-11eb-9222-7f03918c5e6e.png)

**Comment by ildyria** [comment]
https://lycheeorg.github.io/docs/faq.html#why-dont-my-videos-have-thumbnails :)
