### ISSUE TITLE
[Enhancement] Add one Tag to multiple Photos

### ISSUE THREAD

**Issue by vonmiristdasnicht** [LycheeOrg/Lychee#938]
If I want to add one tag (i. e. "name surname") on to multiple images, I can do so by marking multiple images and right click on them and add them. But when I'm adding a different tag (i. e. because its an other person) on to other photos and only on some already tagged photos, these already tagged photos are getting overwritten by the new tag and are not added to the already existing tag. 

Instead of changing the tags on all marked images, I'd like to add a tag onto already tagged images.
This would be very helpful to mark images, where a lot of different people in different constellations are on the images.

I hope my text is understandable, not written in english for a long time.

**Comment by ildyria** [comment]
I thought we already had an issue about that. :thinking:

**Comment by ildyria** [comment]
Yep, duplicate: https://github.com/LycheeOrg/Lychee/issues/654
