### ISSUE TITLE
Folder structure during move as cached items

### ISSUE THREAD

**Issue by hDoubleU71** [LycheeOrg/Lychee#943]
When browsing pictures and moving them to a different folder, it would be much quicker and easier, if the folder structure is not read every time you make a new move request.
Would be great if the webpage caches the folder structure and display it from cache during the move command. 
Needs only to be refreshed if a new folder is created.

**Comment by ildyria** [comment]
I totally agree with you, we just haven't had time to cover work on such improvements, but indeed caching the JSON responses was in my mind.

**Comment by kamil4** [comment]
It's easier to do now that the album list does not include thumbs.

For the record, the refresh needs to take place not just when a new album is created, but also after album delete, album move, merge, and import from server operations (that's just off the top of my head).

**Comment by ildyria** [comment]
> It's easier to do now that the album list does not include thumbs.

Well.... In theory it should include thumbs, it's just a bug I haven't fixed yet... :sweat_smile: 
Let's just call it a temporary feature. :smiley:

**Comment by kamil4** [comment]
If the list is to include thumbs, then the original suggestion is virtually unworkable. Thumbs can change in unpredictable ways after every move operation.

**Comment by ildyria** [comment]
Given how small the thumbs are, I would not worry too much about it though.

**Comment by kamil4** [comment]
Actually, let me add to that. I think the best way to do it would be to have a separate API call for the thumbs from the one for the album tree. So when photos get moved around, (some) thumb information is invalidated but the album tree stays valid. The same principle could be applied to `albums.json` and `album.json`, which get dropped way more frequently than needed for the same reason (thumb invalidation).

Is any of this going to be relevant with the new front end though?

**Comment by kamil4** [comment]
> Given how small the thumbs are, I would not worry too much about it though.

Well, I think that either we shouldn't display them or, if we do, they should be correctly updated. But maybe that's just my OCD talking :wink:.

**Comment by ildyria** [comment]
> Is any of this going to be relevant with the new front end though?

I don't know yet if there are way to use caching with Livewire, but I would be surprised if there wasn't.

**Comment by ildyria** [comment]
I don't see this being relevant with the new front-end.
