### ISSUE TITLE
php artisan lychee:sync to create symlinks?

### ISSUE THREAD

**Issue by szamanposp** [LycheeOrg/Lychee#947]
Hi there,
I am looking for to use Lychee to manage my photo albums. I have thousends photos organized in multiple directories. I would like to sync them all to Lychee. Initially, I was tinking to use "import from server" option with "symbolic links". But going further, I was looking for a way on how to automatically update the albums with recently added photos to my root photo directory. It seems the solution is "php artisan lychee:sync /path/to/import" described in FAQ (https://lycheeorg.github.io/docs/faq.html), but it does not create symlinks but copy the files in full size. Is there any way to set up Lychee to watch a specfic folder for new images and automatically add them to albums creating only symbolic links? I want to keep my original photo folder structure, presenting the photos via Lychee, avoiding file duplicates to save disk space.
Tank you in advance for your support!

**Comment by ildyria** [comment]
Actually, as long as you set it in your settings, it should import with symlinks. Cf code line 43:

https://github.com/LycheeOrg/Lychee/blob/29637272515e05d2c351ddf93433b88e26bb2943/app/Console/Commands/Sync.php#L32-L53
