### ISSUE TITLE
[Enhancement] Album Slideshow

### ISSUE THREAD

**Issue by jtommi** [LycheeOrg/Lychee#949]
I'd love to see a slideshow feature, so that you can put it up on a TV and watch the newly added photos.
Ideally it would have a direct link with autostart

**Comment by vuongquoc** [comment]
That's a really good idea!

**Comment by tomstgeorge** [comment]
agreed... I was surprised to find this feature missing.

**Comment by ildyria** [comment]
> agreed... I was surprised to find this feature missing.

we are kinda missing contributors. hence why the project does not improve much over the years. :(

**Comment by ildyria** [comment]
Thanks to @mingan666 with #1819 this is now supported in the `/frame` mode.
You can specify which album to display in parameters.
