### ISSUE TITLE
Corrupted link in manual

### ISSUE THREAD

**Issue by janstieler** [LycheeOrg/Lychee#952]
Hi,
There is a not working link in your manual docs:
https://lycheeorg.github.io/docs/update-manually

Cheers

**Comment by ildyria** [comment]
Hi, thank you for bringing that up. Where is that link ?

**Comment by janstieler** [comment]
Hi,
Sorry that I forgot to post the source link.
It links from [here](https://lycheeorg.github.io/docs/update.html) on _Update manually._

**Comment by d7415** [comment]
Fixed. Thanks for letting us know!
