### ISSUE TITLE
Cannot install Lychee

### ISSUE THREAD

**Issue by danieldotnet** [LycheeOrg/Lychee#953]
After editing the config file with DB Username and Password, click on Save --> Install, error 500 occurs.
![grafik](https://user-images.githubusercontent.com/18641962/112966322-68fdc100-914a-11eb-8c26-e0ced4ba7dd8.png)

Firefox Browser, newest version.
DB: MariaDB
PHP: 8.0.2

**Comment by ildyria** [comment]
> PHP: 8.0.2

Well I can already tell you this will not work.
We do not support 8.0 yet (sorry, but it is on my todo list).

(still I'm surprised you managed to get this far in the process).

**Comment by danieldotnet** [comment]
OK, thanks. Yes I was wondering that no message comes during the installation.
