### ISSUE TITLE
"Field 'position' doesn't have a default value" not fixed with existing installations

### ISSUE THREAD

**Issue by GNUtoo** [LycheeOrg/Lychee#957]
### Detailed description of the problem [REQUIRED]

The commit 2a8b1f9ec2ec488b32571a0eb316a75bc90b5683 (Update photos_table.sql) doesn't fix existing installations as the SQL code only creates the table correctly if it doesn't exist (CREATE TABLE IF NOT EXISTS), so the table isn't modified on existing installations.

### Steps to reproduce the issue
1. Try to upload a big picture
2. An error modal appears on the web page
3. "Field 'position' doesn't have a default value" appears in the logs

### Output of the diagnostics  [REQUIRED]
"Field 'position' doesn't have a default value"

### Browser and system
Distribution: Debian GNU/Linux 10 (buster) with php 7.3

### Workaround
1. Login into the table dedicated to lychee (probably lychee by default)
$ sudo mysql lychee
2. Add the default to the position column of the photo table (probably lychee_photos by default):
$ MariaDB [lychee]> ALTER TABLE lychee_photos ALTER COLUMN position SET DEFAULT 0;

**Comment by ildyria** [comment]
> ### Output of the diagnostics [REQUIRED]
> "Field 'position' doesn't have a default value"

1. **This is not the output of the diagnostics page.**
2. There is no position column in the `photos` table.

> ### Browser and system
> Distribution: Debian GNU/Linux 10 (buster) with php 7.3

3. Lychee does not support PHP 7.3 since it is EOL.

As a result, I can only deduce you are using an old version of Lychee (namely the v3).
Please update to version 4.
