### ISSUE TITLE
Registration for new users

### ISSUE THREAD

**Issue by tio-trom** [LycheeOrg/Lychee#958]
Maybe I didn't get it, but does it support user registration? Can users register and use this service? Or is it only for personal use on our personal servers? Cheers!

**Comment by ildyria** [comment]
It is only for personal use / personal server. The admin has to create the other users accounts rather than enabling other people access the server.

**Comment by tio-trom** [comment]
I see thank you!

**Comment by tio-trom** [comment]
Will you consider allowing open registrations if admins select that?
