### ISSUE TITLE
POST /api/Session::init is protected by CSRF

### ISSUE THREAD

**Issue by nagmat84** [LycheeOrg/Lychee#959]
### Detailed description of the problem

I am working on an Android client app for Lychee using Retrofit on Android side. According to the [API documentation of Lychee](https://lycheeorg.github.io/docs/api.html#phpindexphp-apisessioninit) an HTTP POST to `/api/Session::init` should not be protected by `X-XSRF-TOKEN`. But it seems to be so.

Expected result: Receive a HTTP 200 response together with a CSRF cookie/token to be used in subsequent requests.

Actual result: I receive HTTP status `419` with the following response body `{ "message": "CSRF token mismatch.", ... }`.

I thought, I had to POST to `/api/Session::init` as my very first step of my client app to receive a CSRF token. Maybe I am doing something wrong and I misunderstood something. In that case, it might not be bug and I would appreciate any help telling me where I am wrong.

Note: I also tried a `GET` request, because I thought the API documentation might be wrong. But then I get a "method not allowed" response.

**Comment by ildyria** [comment]
It appears you are correct. :)

If you can submit a PR modifying this file, simply adding `api/Session::init` and it will be fixed.: https://github.com/LycheeOrg/Lychee/blob/master/app/Http/Middleware/VerifyCsrfToken.php:

https://github.com/LycheeOrg/Lychee/blob/70b40c678f7dff7c3b417853ab956accd87585b4/app/Http/Middleware/VerifyCsrfToken.php#L17-L20

And it will be fixed.

**Comment by nagmat84** [comment]
Et voilà: [PR #960](https://github.com/LycheeOrg/Lychee/pull/960)
