### ISSUE TITLE
[Enhancement] Images should not be accessible by non-users

### ISSUE THREAD

**Issue by klausmcm** [LycheeOrg/Lychee#961]
Going to any image in an album and right-clicking and selecting **View Image**, will display only the image in the browser without any of the Lychee interface. This also updates the URL in the address bar to something like **https://<domain>/uploads/medium/7cb5b13ff204613c7a9f10a2e691870b.jpg**.

With the URL, the image loads even for anyone without an account.

I'm not sure if that's the intended behavior. The **Public** option for the particular image I tested with is set to false.

Thanks,

**Comment by kamil4** [comment]
Yeah, that's pretty much the intended behavior. We provide an option in the advanced config to enable symbolic linking, which will make the URLs more temporary and unpredictable. In general though, our approach is to make it secure through the use of difficult to guess filenames.

**Comment by klausmcm** [comment]
Ok, I'll check the symbolic linking option. That might be sufficient. Thanks,
