### ISSUE TITLE
No uploaded images are shown in new created album

### ISSUE THREAD

**Issue by r-grewer** [LycheeOrg/Lychee#969]
### Detailed description of the problem [REQUIRED]
After installing and configuring Lychee 4.2.1 10 weeks ago for my webpage (hosted by Strato (with MySQL 5.7 and PHP 8)) I added a lot of albums and photos to them, and everything worked fine. 
When I added a new album and uploaded some photos to it some days ago (in the same way I did before), the photos aren't displayed in the album, they are only shown (and clickable) in the Recent (and the Public) smart albums, and one of them as thumb in the album view. 
But if I add a photo to an old, existing album, it is shown as it should be!

### Steps to reproduce the issue
To reproduce this issue, I created a fresh lychee installation on another webspace, did only the neccessary modifications, created one album and uploaded two photos (a small (20k) and a big (3M) one). The result is the same: they aren't shown in the album, but in the Recent (and the Public) smart albums.

I had a look into the database to see, what the difference is between old and new created objects (albums, photos), and found out, that all new created objects have an id of 14 digits length, while all old objects have 10 digit length ids. Maybe, that could have something to do with this issue... And maybe my hosting provider changed/updated something with PHP...

### Output of the diagnostics  [REQUIRED]
    Diagnostics
    -----------
    Warning: Dropbox import not working. dropbox_key is empty.
    Warning: You may experience problems when uploading a photos of large size. Take a look in the FAQ for details.

    System Information
    ------------------
    Lychee Version (release):        4.2.1
    DB Version:                      4.2.1
    
    composer install:                --no-dev
    APP_ENV:                         production
    APP_DEBUG:                       false
    
    System:                          Linux
    PHP Version:                     8
    Max uploaded file size:          64M
    Max post size:                   76M
    MySQL Version:                   5.7.32-log
    
    Imagick:                         1
    Imagick Active:                  1
    Imagick Version:                 1691
    GD Version:                      bundled (2.1.0 compatible)

    Config Information
    ------------------
    version:                         040201
    check_for_updates:               0
    sorting_Photos_col:              title
    sorting_Photos_order:            ASC
    sorting_Albums_col:              title
    sorting_Albums_order:            ASC
    imagick:                         1
    skip_duplicates:                 0
    small_max_width:                 480
    small_max_height:                360
    medium_max_width:                1920
    medium_max_height:               1080
    lang:                            de
    layout:                          1
    image_overlay:                   0
    image_overlay_type:              desc
    default_license:                 none
    compression_quality:             90
    full_photo:                      1
    delete_imported:                 0
    Mod_Frame:                       1
    Mod_Frame_refresh:               30
    thumb_2x:                        1
    small_2x:                        1
    medium_2x:                       1
    landing_page_enable:             0
    landing_owner:                   VIRADA
    landing_title:                   VIRADA
    landing_subtitle:                interne Fotogalerie
    landing_facebook:                https://www.facebook.com/JohnSmith
    landing_flickr:                  https://www.flickr.com/JohnSmith
    landing_twitter:                 https://www.twitter.com/JohnSmith
    landing_instagram:               https://instagram.com/JohnSmith
    landing_youtube:                 https://www.youtube.com/JohnSmith
    landing_background:              dist/cat.jpg
    site_title:                      VIRADA
    site_copyright_enable:           1
    site_copyright_begin:            1986
    site_copyright_end:              2021
    additional_footer_text:          
    display_social_in_gallery:       0
    public_search:                   1
    SL_enable:                       0
    SL_for_admin:                    0
    public_recent:                   0
    recent_age:                      1
    public_starred:                  0
    downloadable:                    0
    photos_wraparound:               1
    map_display:                     0
    zip64:                           1
    map_display_public:              0
    map_provider:                    Wikimedia
    force_32bit_ids:                 0
    map_include_subalbums:           0
    update_check_every_days:         30
    has_exiftool:                    0
    share_button_visible:            0
    import_via_symlink:              0
    has_ffmpeg:                      0
    location_decoding:               0
    location_decoding_timeout:       30
    location_show:                   0
    location_show_public:            0
    rss_enable:                      0
    rss_recent_days:                 7
    rss_max_items:                   100
    prefer_available_xmp_metadata:   0
    editor_enabled:                  1
    lossless_optimization:           0
    swipe_tolerance_x:               150
    swipe_tolerance_y:               250
    local_takestamp_video_formats:   .avi|.mov
    log_max_num_line:                1000
    unlock_password_photos_with_url_param: 0
    nsfw_visible:                    0
    nsfw_blur:                       0
    nsfw_warning:                    0
    nsfw_warning_admin:              0

### Browser and system
Firefox 87.0 (64-Bit)
Windows 10 Pro  Version 20H2 (Build 19042.928)

**Comment by d7415** [comment]
Unless I missed it, PHP 8 is not yet supported.

Correct #803

**Comment by ildyria** [comment]
> Unless I missed it, PHP 8 is not **yet** supported.

Emphasis on the **YET**.

**Comment by ildyria** [comment]
If you manage to install php-8 with imagick, then Lychee should be usable now if you use #803 (I will need to look at why the CI fails, but it seems to be working fine locally on my VM **with php8**).
