### ISSUE TITLE
Installer resets to the first step after clicking Install in the Environment step if the DB config is invalid

### ISSUE THREAD

**Issue by poisonborz** [LycheeOrg/Lychee#970]
### Detailed description of the problem [REQUIRED]
The installer resets on wrong db settings, instead of showing some meaningful error.
Env: php-7.4.0-Win32-vc15-x64, Windows 10, latest Laragon

### Detailed description of the problem [REQUIRED]

- Start Lychee installation
- Go until Environment step (all checks presumed green)
- Enter a wrong db password in the presented config form
- Click install

The installer resets, instead of showing a proper error message.

**Comment by larsnsonsk** [comment]
I had the same problem and was able to solve it :

- The mysql password must not contain any special characters /#=)%("=...
- Remove the # before #DB_DATABASE

Thats worked for me

**Comment by ildyria** [comment]
Duplicate: https://github.com/LycheeOrg/Lychee/issues/1248
