### ISSUE TITLE
Cannot Open Web Installer - "File not found."

### ISSUE THREAD

**Issue by JacobRock** [LycheeOrg/Lychee#975]
Hello,

I have been attempting to install Lychee on a Vultr VPS running Debian 10 but for some reason I am unable to open the web installer after installing the program on my VPS via SSH. I have tried visiting "http://host.mydomain.com", "http://host.mydomain.com/install", "http://host.mydomain.com/install/env", and lastly "http://my-ip-address" (plus it's variations) and a simple HTML page saying "File not found." is what always appears.

I am not sure if the problem is with my .env file, my Nginx server block, or my DNS records. I have copied my full .env file below along with the output of "php artisan lychee:diagnostics". As for the Nginx server block, I'm using the example configuration in the documentation, with only the server name changed to my domain name. I have a regular A record for my DNS.

I do also have a working Peertube instance on the same VPS; is it possible that this could be causing issues?

**.env:**

APP_NAME=Lychee
APP_ENV=production
APP_KEY=base64:CTMU1COEwjGzCxW5BOlJnLQUHakMMi2DFv8Ljwhb9YA=
APP_DEBUG=false
APP_URL=http://localhost

\# enable or disable debug bar. By default it is disabled.
DEBUGBAR_ENABLED=false

LOG_CHANNEL=stack

\# IMPORTANT: To migrate from Lychee v3 you *MUST* use the same MySQL/MariaDB \#
\#            server as v3.                                                   \#

\# Table prefix (e.g. lychee_) of a Lychee v3 instance for migration
DB_OLD_LYCHEE_PREFIX=

\# DB_CONNECTION can be sqlite, mysql or pgsql. For sqlite the other entries are
\# not required, but an existing sqlite3 database may be specified if desired. In
\# this case, please use an absolute path. DB_DATABASE may be omitted but should
\# *not* be left blank.
DB_CONNECTION=sqlite
DB_HOST=
DB_PORT=
#DB_DATABASE=
DB_USERNAME=
DB_PASSWORD=
DB_LOG_SQL=false

TIMEZONE=UTC

\# folders in which the files will be stored
\# LYCHEE_DIST="/var/www/html/Lychee-Laravel/public/dist/"
\# LYCHEE_UPLOADS="/var/www/html/Lychee-Laravel/public/uploads/"

\# url to access those files
\# LYCHEE_DIST_URL="dist/"
\# LYCHEE_UPLOADS_URL="uploads/"

BROADCAST_DRIVER=log
CACHE_DRIVER=file
SESSION_DRIVER=file
SESSION_LIFETIME=120
QUEUE_DRIVER=sync

SECURITY_HEADER_HSTS_ENABLE=false

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=
MAIL_PORT=
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_ENCRYPTION=

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

-----------

`Diagnostics
-----------
Warning: Dropbox import not working. dropbox_key is empty.
Warning: You may experience problems when uploading a photo of large size. Take a look in the FAQ for details.
Warning: You may experience problems when uploading a photos of large size. Take a look in the FAQ for details.
Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.
Info: Latest version of PHP is 8

System Information
------------------
Lychee Version (git):            master (5b63694) - Data not in Cache
DB Version:                      4.3.0

composer install:                --no-dev
APP_ENV:                         production
APP_DEBUG:                       false

System:                          Linux
PHP Version:                     7.4
Max uploaded file size:          2M
Max post size:                   8M
SQLite Version:                  3.27.2

Imagick:                         1
Imagick Active:                  1
Imagick Version:                 1690
GD Version:                      2.2.5

Config Information
------------------
version:                         040300
check_for_updates:               0
sorting_Photos_col:              takestamp
sorting_Photos_order:            ASC
sorting_Albums_col:              max_takestamp
sorting_Albums_order:            ASC
imagick:                         1
skip_duplicates:                 0
small_max_width:                 0
small_max_height:                360
medium_max_width:                1920
medium_max_height:               1080
lang:                            en
layout:                          1
image_overlay_type:              desc
default_license:                 none
compression_quality:             90
full_photo:                      1
delete_imported:                 0
Mod_Frame:                       1
Mod_Frame_refresh:               30
thumb_2x:                        1
small_2x:                        1
medium_2x:                       1
landing_page_enable:             0
landing_owner:                   John Smith
landing_title:                   John Smith
landing_subtitle:                Cats, Dogs & Humans Photography
landing_facebook:                https://www.facebook.com/JohnSmith
landing_flickr:                  https://www.flickr.com/JohnSmith
landing_twitter:                 https://www.twitter.com/JohnSmith
landing_instagram:               https://instagram.com/JohnSmith
landing_youtube:                 https://www.youtube.com/JohnSmith
landing_background:              dist/cat.jpg
site_title:                      Lychee v4
site_copyright_enable:           1
site_copyright_begin:            2019
site_copyright_end:              2019
additional_footer_text:
display_social_in_gallery:       0
public_search:                   0
SL_enable:                       0
SL_for_admin:                    0
public_recent:                   0
recent_age:                      1
public_starred:                  0
downloadable:                    0
photos_wraparound:               1
map_display:                     0
zip64:                           1
map_display_public:              0
map_provider:                    Wikimedia
force_32bit_ids:                 0
map_include_subalbums:           0
update_check_every_days:         3
has_exiftool:                    0
share_button_visible:            0
import_via_symlink:              0
has_ffmpeg:                      1
location_decoding:               0
location_decoding_timeout:       30
location_show:                   1
location_show_public:            0
rss_enable:                      0
rss_recent_days:                 7
rss_max_items:                   100
prefer_available_xmp_metadata:   0
editor_enabled:                  1
lossless_optimization:           0
swipe_tolerance_x:               150
swipe_tolerance_y:               250
local_takestamp_video_formats:   .avi|.mov
log_max_num_line:                1000
unlock_password_photos_with_url_param: 0
nsfw_visible:                    1
nsfw_blur:                       0
nsfw_warning:                    0
nsfw_warning_admin:              0
map_display_direction:           1
album_subtitle_type:             oldstyle
upload_processing_limit:         4
public_photos_hidden:            1`

Any help would be appreciated!

**Comment by d7415** [comment]
While I can't be certain, I suspect the problem is with your nginx configuration. If you're using the default, is it installed in /var/www/lychee? Can you access static files, like http://host.mydomain.com/dist/cat.jpg? Also check whether there is any redirect to https that may be breaking things.

**Comment by JacobRock** [comment]
It is installed in /var/www/html/Lychee. I am not able to access the static files, the same html page saying "File not found." appears when I try to. There doesn't seem to be any redirect to https either.

Looking over the .env file again, should I enter anything into the "#DB_DATABASE=" field or leave it empty like in my post above?

**Comment by d7415** [comment]
> It is installed in /var/www/html/Lychee

Ok. So you also changed the `root` directive in the nginx configuration? And that configuration is loaded (restarted/reloaded nginx)?

> Looking over the .env file again, should I enter anything into the "#DB_DATABASE=" field or leave it empty like in my post above?

As it says in the .env, that can be left blank.

**Comment by JacobRock** [comment]
> Ok. So you also changed the `root` directive in the nginx configuration? And that configuration is loaded (restarted/reloaded nginx)?

I just checked and the root directive in the nginx configuration was set to /var/www/lychee/public.

I've gone ahead and re-installed Lychee entirely in /var/www/html/Lychee and changed the root directive to /var/www/html/Lychee/public in the nginx configuration; the "File not found." message no longer appears but instead "403 Forbidden" appears. I am able to access the cat.jpg static file now however.

**Comment by ohreally** [comment]
I just had this same problem on Apache. The reason was that the `.htaccess` file was not read (the default value for `AllowOverride` is `no` for Apache 2.4).

I don't know exactly how the Apache directives in the file `public/.htaccess` would translate to Nginx, but you may want to look into that.

**Comment by JacobRock** [comment]
So I looked into reading the .htaccess file with Nginx. I found this plugin: https://github.com/e404/htaccess-for-nginx and tried to use it, however I was still ending up with the same 403 Forbidden error when trying to access the web installer.

I then found this htaccess to Nginx converter: https://www.winginx.com/en/htaccess. Putting the Lychee .htaccess file into the converter output the following:
>\# nginx configuration by winginx.com
>
>autoindex off;
>
>autoindex off;
>
>location / {
  >if (!-e $request_filename){
    >rewrite ^(.*)$ /%1 redirect;
  >}
  >if (!-e $request_filename){
    >rewrite ^(.*)$ /index.php break;
  >}
>}

I then put this into the Nginx server block for Lychee and ran "sudo nginx -t", which output an error saying "autoindex off;" was repeated. Removing one of the "autoindex off:"s, I tested again and there were no errors. However, after I re-linked the server block and restarted Nginx/php, I got the same 403 Forbidden page.

I am not sure if the htaccess to Nginx conversion is correct or if I am missing something else; I apologize but I have only minor experience with Nginx and basically 0 with Apache and thus am quite stumped as to what exactly the problem is along with how to fix it. Otherwise, Lychee seems to be functioning correctly and I can still access the cat.jpg access file from my browser.

**Comment by ohreally** [comment]
No need to apologize.
Since those `.htaccess` directives haven't changed anything, you may want to delete them again, to keep your config clean.

Make sure that the PHP-FPM user has access to files in the document root.
If the `user` directive in the PHP-FPM configuration file says `www-example`, for example, try the following command as root:

`sudo -u www-example cat /var/www/html/Lychee/public/index.php`

Also, check the Nginx and PHP-FPM log files. You may want (or need) to enhance the respective log levels and restart Nginx and PHP-FPM.

If you still can't get it to work, consider using [the Docker image](https://lycheeorg.github.io/docs/docker.html); I think that should run out of the box.

**Comment by JacobRock** [comment]
After troubleshooting and tinkering some more, I was finally able to access the web installer and open Lychee successfully; I believe that the issue was from the Nginx configuration I was using. I also updated the permissions of /var/www/html/Lychee with the `sudo chown -R www-data:www-data .` command just to make sure the permissions were correct.

The Nginx configuration I found to work is as follows:

```
server {
    listen 80;
    listen [::]:80;
    server_name photos.mydomain.com;

##### Path to the Lychee public/ directory.
    root /var/www/html/Lychee/public/;

    index index.html index.htm index.nginx-debian.html index.php

    # If the request is not for a valid file (image, js, css, etc.), send to bootstrap
    if (!-e $request_filename)
    {
        rewrite ^/(.*)$ /index.php?/$1 last;
        break;
    }

    # Serve /index.php through PHP
    location = /index.php {
        fastcgi_split_path_info ^(.+?\.php)(/.*)$;

        # Mitigate https://httpoxy.org/ vulnerabilities
        fastcgi_param HTTP_PROXY "";

######### Make sure this is the correct socket for your system
        fastcgi_pass unix:/run/php/php7.4-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PHP_VALUE "post_max_size=200M
            max_execution_time=200
            upload_max_filesize=200M
            memory_limit=300M";
        fastcgi_param PATH /usr/local/bin:/usr/bin:/bin;
        include fastcgi_params;
    }
    # Deny access to other .php files, rather than exposing their contents
    location ~ [^/]\.php(/|$) {
        return 403;
    }

    # [Optional] Lychee-specific logs
    error_log  /var/log/nginx/lychee.error.log;
    access_log /var/log/nginx/lychee.access.log;

    # [Optional] Remove trailing slashes from requests (prevents SEO duplicate content issues)
    rewrite ^/(.+)/$ /$1 permanent;
}
```

However, I am having issues uploading photos to Lychee now; whenever I attempt to upload a photo larger than ~1MB in size, the upload fails and the error message "Upload failed. The PHP post_max_size limit is too small!" appears. I am not sure why this is happening, because I have the post_max_size set to 200M in the php.ini. This is confirmed in the diagnostics below:

```
Diagnostics
    -------
    Warning: Dropbox import not working. dropbox_key is empty.
    Info: Latest version of PHP is 8



    System Information
    --------------
    Lychee Version (git):            master (10927c6) - Up to date (1 days ago).
    DB Version:                      4.3.0
    
    composer install:                --no-dev
    APP_ENV:                         production
    APP_DEBUG:                       false
    
    System:                          Linux
    PHP Version:                     7.4
    Max uploaded file size:          200M
    Max post size:                   200M
    SQLite Version:                  3.27.2
    
    Imagick:                         1
    Imagick Active:                  1
    Imagick Version:                 1690
    GD Version:                      2.2.5
```

Would anyone have insight into what may be causing this issue and how to fix it? I would greatly appreciate the help.

**Comment by d7415** [comment]
As a start, check your nginx `client_max_body_size` - e.g. `client_max_body_size 200M;` in the `server` block.

**Comment by JacobRock** [comment]
> As a start, check your nginx `client_max_body_size` - e.g. `client_max_body_size 200M;` in the `server` block.

Checked my nginx.conf and discovered that `client_max_body_size` was missing entirely. I added it in and now can properly upload photos. Thank you for all your help!
