### ISSUE TITLE
A popup with password field does not disappear after changing browser URL to non-secured gallery

### ISSUE THREAD

**Issue by elvisef** [LycheeOrg/Lychee#979]
Just in short: 

1. Enter gallery URL, that is password protected.
2. A password popup will be shown.
3. Enter the other gallery URL that is not password protected (so we fully change the URL field in the browser).
4. The new gallery URL will show the other gallery, in the background, while the password field from the previous one did not disappear and the background is still "opaque".

![firefox_2021-04-29_09-06-37](https://user-images.githubusercontent.com/25976749/116513829-71245a00-a8ca-11eb-9c5f-3df91906a641.png)

So the effect is that I see the contents of not password protected gallery, while the password popup is still visible, wishing me to enter something ?! : )

**Comment by kamil4** [comment]
A bizarre behavior indeed... And it's not limited to the album password prompt. I can recreate it, e.g., in the photo view for the download dialog.

**Comment by elvisef** [comment]
Yeah.. I know I'm a genius for finding bugs :P

**Comment by ildyria** [comment]
Done.
