### ISSUE TITLE
[Enhancement] Downloadable albums, command line import with symbolic links

### ISSUE THREAD

**Issue by clix10** [LycheeOrg/Lychee#980]
Hello,

I have been testing different self hosted galleries / photo management solutions, that would fit the bill for me. So far, I like Lychee the best. But there are few things, that I would change. :

1.) For example, I really like the option to easily share different albums with different users. For the other galleries I tested, it was usually impossible. But the problem is, that I would like to make whole album and each image downloadable for users that I shared the albums with.
There is no intuitive way to do it, and I, as an admin, have to make each album public, hidden, password protected and downloadable. Suddenly, even if the users are accessing the albums via private accounts and not via direct links, albums are available as a downloadable. With a lot of albums, this is quite tedious, and doesn't make much sense, because in my opinion it would be better If it would be possible to make whole albums downloadable per user basis, and not per album basis.

2.) The other thing is, that I am currently using it with all pictures imported as a symbolic link. Originals stay where they are, and lychee create its own folder structure with thumbnails. That is OK by me. The problem is, that currently there is no way to make automatic import with symbolic links via command line.  Currently, command line import  copies all the files to lychee folder structure and in my case, this is not desired. I would like to have a command line import with option to select symbolic links.

3.) One small niggle is, that when there are no public albums and user lands on the page, they are effectively greeted with the blank page. They have to click on the small icon on the top left corner for the login box to appear. In my case, older parents and grandparents can easily miss this. Is there a way, that login box would be shown by default?

Thank you and keep up the good work

**Comment by ildyria** [comment]
Hi thank you for your kind words.

> If it would be possible to make whole albums downloadable per user basis, and not per album basis.

That is an interesting option to add and would probably not be that hard to implement.
Please create an issue with this suggestion, that way it will be easier for us to track it and we will be able to directly close it when this done.

**Comment by ildyria** [comment]
> The problem is, that currently there is no way to make automatic import with symbolic links via command line. Currently, command line import copies all the files to lychee folder structure and in my case, this is not desired. I would like to have a command line import with option to select symbolic links.

Are you sure of that? If you set-up import via symbolic link this should directly translate. I think we have a `lychee:sync` command in that regard:
https://github.com/LycheeOrg/Lychee/blob/54586dc9a4071f61dd792ba935ebfb6b95ab3dc0/app/Console/Commands/Sync.php#L32-L45

**Comment by ildyria** [comment]
> One small niggle is, that when there are no public albums and user lands on the page, they are effectively greeted with the blank page. They have to click on the small icon on the top left corner for the login box to appear. In my case, older parents and grandparents can easily miss this. Is there a way, that login box would be shown by default?

That is an interesting proposition and I don't think it would be hard to implement, especially with the new front end I have in mind.
Could you open an additional issue (enhancement) for this ?

Bonus hint: press `L` when not logged in and you will be greeted with the login box.

**Comment by kamil4** [comment]
> 1.) For example, I really like the option to easily share different albums with different users. For the other galleries I tested, it was usually impossible. But the problem is, that I would like to make whole album and each image downloadable for users that I shared the albums with.
> There is no intuitive way to do it, and I, as an admin, have to make each album public, hidden, password protected and downloadable. Suddenly, even if the users are accessing the albums via private accounts and not via direct links, albums are available as a downloadable. With a lot of albums, this is quite tedious, and doesn't make much sense, because in my opinion it would be better If it would be possible to make whole albums downloadable per user basis, and not per album basis.

There is an option in the advanced config, `downloadable`, that may do what you want. It's documented [here](https://lycheeorg.github.io/docs/settings.html#downloadable). Basically, it specifies what the fallback behavior should be for cases when the per-album setting of _Downloadable_ does not apply, such as private albums shared between users (which is what you want to do, correct?). Note that it will apply to _all_ shared private albums and _all_ users. Check it out and let us know if that's good enough for you.

**Comment by clix10** [comment]
Hello ildyria and kamil4,

1. yes, setting downloadable to 1 did the trick. It is good enough for me. 
2. I am just testing it now.  I set the import_via_symlink to 1 and did the import via the command line. It looks OK.

For the first two point it was definitely the RTFM moment for me. I somehow missed the whole "more" section of the settings, so, didn't know these two settings were possible, thx for the support. :)

Regarding the 3rd pint, I will open additional issue,
Thank you!

**Comment by ildyria** [comment]
Fixed by RTFM and now when the album view is empty we display login dialog.
