### ISSUE TITLE
[Enhancement] API to set photo upload date

### ISSUE THREAD

**Issue by endotronic** [LycheeOrg/Lychee#984]
Hello! Thanks for all the awesome work. I love Lychee so far.

I'm working on a script to import photos into Lychee, and right now, all imported photos have the same upload date (now). I would like to be able to set the upload date to a different date, which I happen to have data for. Note that this is still different than the takestamp. I have no issue with that, but that is not what I'm looking for.

Thanks!

**Comment by ildyria** [comment]
Hi thank you for your suggestion. Currently the only way to edit this is by editing directly the database. :(

That being said, it could be interesting to add it as a "service" but as this is a pretty isolated case, I would suggest you to implement it and propose it as a Pull Request.
The main devs of the team (@kamil4 , @tmp-hallenser , & me) are quite is quite busy at the moment: Lychee does not pay the bills. ;) I am working a full refactoring of the front-end as a result, it is very unlikely that any of us has the time to work on such suggestion (sorry for the brutally honest answer).

**Comment by endotronic** [comment]
No worries; I figured this was the case. I'll see if I can add it to the parameters for Photo::add since I always know it at add time. This is a personal project for me, though, so I don't have a lot of time either.

Since you are working on the frontend, I opened another request I have that may be in the space you are working. I imagine it is small: https://github.com/LycheeOrg/Lychee/issues/987

**Comment by kamil4** [comment]
Out of curiosity, what is your use case? I've been meaning to make the takestamp editable for a long time, but I never thought that some might want to do it with the upload date?

**Comment by endotronic** [comment]
I'm scraping photos from a forum for a project, and Lychee is a great way to manage them and search through them. In this scenario, I would prefer to use uploaded date to reflect the date it was posted to the forum. Takestamp also makes sense, but if the forum isn't stripping EXIF data (I haven't checked), then there is potential value in keeping that true to the original.
