### ISSUE TITLE
CSS to disable the 'zoom' animation while browsing pictures not working anymore

### ISSUE THREAD

**Issue by hDoubleU71** [LycheeOrg/Lychee#985]
The CSS snipet mentioned in the FAQ is not working anymore for actual version

**Comment by ildyria** [comment]
@SerenaButler :smiley:

**Comment by kamil4** [comment]
Erm, it works for me?

Note that the CSS snippet from the FAQ only controls the behavior in photo view, after clicking on a photo in an album, or when going next/previous from one photo to another.

@hDoubleU71, what is specifically the behavior you are looking for?

**Comment by hDoubleU71** [comment]
As taken from the FAQ

**How to disable the 'zoom' animation while browsing pictures?**

Add the following custom CSS to your user.css or via the settings menu:

#imageview #image {
  transition: none !important;
  animation-name: none !important;
  animation-duration: 0 !important;
}

I toop this in the configuration but when browsing thru the photos of an album it always "zoom" the photo, so the menu bar etc. at the top is hidden until you move your mouse.

**Comment by kamil4** [comment]
Right. This particular FAQ entry actually addresses another issue than the one you want, so no wonder it doesn't work for you. What it addresses is the fraction-of-second-long "zooming in" of a photo when it's first being displayed. Blink and you'll miss it; it's a little more obvious when you click on next/previous.

For what you want, I'll refer you to the following old issue: #718 (maybe we should turn it into another FAQ entry). I believe you'll want to copy the CSS from https://github.com/LycheeOrg/Lychee/issues/718#issuecomment-689593325 and possibly also https://github.com/LycheeOrg/Lychee/issues/718#issuecomment-689701058.

I hope this helps! Let us know if you have any further questions.

**Comment by hDoubleU71** [comment]
Solved with last comment
