### ISSUE TITLE
[Enhancement] Plugin system

### ISSUE THREAD

**Issue by ohreally** [LycheeOrg/Lychee#986]
Hi,

I just installed Lychee, and I like it.

However, I was wondering if there are any plans for implementing some sort of plugin system for additional functionality? Like with hooks in the core code, and plugins can register to be executed at those hooks?

I'd like to add some functionality, but I really don't feel like learning the ins and outs of Laravel and all the other packages Lychee depends on. I'd just like to write a small chunk of PHP code, and then tell Lychee that I would like to have that executed when an image is imported, or when a gallery is displayed, or whatever.

Also, I think that the core code would become way too heavy at some point, if all functionality is just added to the core. I'd like my installation to only contain code I actually use; this minimizes the risk for abuse of code I don't even use, and it enhances the usability by only showing settings for functionality I chose.

Thanks for considering.

**Comment by ildyria** [comment]
At the moment, I don't think we plan to a plugin system as this would induce a yet another Major overhaul of the code: it is not just "adding some hooks there and there..."
Furthermore, most of the plugins that were provided by the version 3 are already ported to this version.

Laravel is an extremely versatile system which allows you do things like:
https://jhadiary.wordpress.com/2020/03/14/laravel-call-a-routine-or-function-before-each-route-action-is-called/ 
You could also use something like events: https://laravel.com/docs/master/events#introduction

Really, do try to have a look at the code, with the recent refactoring the architecture is simpler than it was, e.g. check the folder `App/Actions/Photo/`, check the file `route/web.php`, and `App/Http/Controllers`.

**Comment by ohreally** [comment]
That's a shame.

With all due respect: I just looked at my installation, and it's 90MB, the `uploads` directory not included. So I'm not even going to try and find my way through it. I'd love to contribute some small bits, but I really don't have time to make this my new hobby.

But not to worry: I already have the functionality I need in a shell script (resizing, addition of watermarks, modification of Exif tags), so I'll just keep using that to pre-process my images. And for the rest I enjoy Lychee, so I'll keep using it.
And I'm pretty sure that at some moment you'll have to implement a plugin system to keep the code manageable, so I'll just wait for that. :)

Thanks.
Have a nice weekend.

**Comment by kamil4** [comment]
> With all due respect: I just looked at my installation, and it's 90MB, the `uploads` directory not included.

Yeah, but most of that is probably the `vendor` directory, i.e., external dependencies. The vast majority of our (server) code is in `app` and, as @ildyria already said, it's pretty well organized.

**Comment by ildyria** [comment]
> With all due respect: I just looked at my installation, and it's 90MB, the `uploads` directory not included. So I'm not even going to try and find my way through it. I'd love to contribute some small bits, but I really don't have time to make this my new hobby.

Actually, if you look only at the `app` folder which contains the code that matters, you will notice that is only 1.8MB (`du -sh app`).

PS : 
```
> du -sh vendor
94M	vendor
```
