### ISSUE TITLE
Old "single" user from v3 stuck after migration to v4

### ISSUE THREAD

**Issue by imThief** [LycheeOrg/Lychee#992]
Hello!
After migrating from v3 to v4 my old single account from v3 looks like stuck to exists forever, i can't delete, change rights or password for this account - whatever i did it still exists unchanged... I couldn't found any mention of this account in database nor in the installation files ('grep -r' was used, maybe i searched not too hard...) what can i do to delete or make this account manageable? Can you help?
Thanks!

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Upgrade your gallery from v3 to v4 following by [this](https://lycheeorg.github.io/docs/installation.html) and [this ](https://lycheeorg.github.io/docs/update.html)docs:
2. If you had custom username/password in your old v3 installation - you will get this issue

### Output of the diagnostics  [REQUIRED]
[diag_output.txt](https://github.com/LycheeOrg/Lychee/files/6414966/diag_output.txt)

```
Diagnostics
    -------
    Warning: Dropbox import not working. dropbox_key is empty.
    Info: Latest version of PHP is 8



    System Information
    --------------
    Lychee Version (git):            master (c551fb1) - Data not in Cache
    DB Version:                      4.3.0
    
    composer install:                --no-dev
    APP_ENV:                         production
    APP_DEBUG:                       false
    
    System:                          Linux
    PHP Version:                     7.4
    Max uploaded file size:          500M
    Max post size:                   500M
    MySQL Version:                   8.0.22
    
    Imagick:                         1
    Imagick Active:                  1
    Imagick Version:                 1802
    GD Version:                      bundled (2.1.0 compatible)



    Config Information
    --------------
    version:                         040300
    check_for_updates:               0
    sorting_Photos_col:              id
    sorting_Photos_order:            DESC
    sorting_Albums_col:              id
    sorting_Albums_order:            DESC
    imagick:                         1
    skip_duplicates:                 0
    small_max_width:                 0
    small_max_height:                360
    medium_max_width:                1920
    medium_max_height:               1080
    lang:                            en
    layout:                          0
    image_overlay_type:              desc
    default_license:                 none
    compression_quality:             90
    full_photo:                      1
    delete_imported:                 0
    Mod_Frame:                       1
    Mod_Frame_refresh:               30
    thumb_2x:                        1
    small_2x:                        1
    medium_2x:                       1
    landing_page_enable:             0
    landing_owner:                   John Smith
    landing_title:                   John Smith
    landing_subtitle:                Cats, Dogs & Humans Photography
    landing_facebook:                https://www.facebook.com/JohnSmith
    landing_flickr:                  https://www.flickr.com/JohnSmith
    landing_twitter:                 https://www.twitter.com/JohnSmith
    landing_instagram:               https://instagram.com/JohnSmith
    landing_youtube:                 https://www.youtube.com/JohnSmith
    landing_background:              dist/cat.jpg
    site_title:                      Photos
    site_copyright_enable:           0
    site_copyright_begin:            2019
    site_copyright_end:              2030
    additional_footer_text:          
    display_social_in_gallery:       0
    public_search:                   0
    SL_enable:                       0
    SL_for_admin:                    0
    public_recent:                   0
    recent_age:                      0
    public_starred:                  0
    downloadable:                    1
    photos_wraparound:               1
    map_display:                     0
    zip64:                           1
    map_display_public:              0
    map_provider:                    Wikimedia
    force_32bit_ids:                 0
    map_include_subalbums:           0
    update_check_every_days:         365
    has_exiftool:                    1
    share_button_visible:            1
    import_via_symlink:              0
    has_ffmpeg:                      1
    location_decoding:               0
    location_decoding_timeout:       30
    location_show:                   1
    location_show_public:            0
    rss_enable:                      0
    rss_recent_days:                 7
    rss_max_items:                   100
    prefer_available_xmp_metadata:   0
    editor_enabled:                  1
    lossless_optimization:           0
    swipe_tolerance_x:               150
    swipe_tolerance_y:               250
    local_takestamp_video_formats:   .avi|.mov
    log_max_num_line:                1000
    unlock_password_photos_with_url_param: 0
    nsfw_visible:                    1
    nsfw_blur:                       0
    nsfw_warning:                    0
    nsfw_warning_admin:              0
    map_display_direction:           1
    album_subtitle_type:             oldstyle
    upload_processing_limit:         4
    public_photos_hidden:            1
 ```
### Browser and system
[system_info.txt](https://github.com/LycheeOrg/Lychee/files/6414967/system_info.txt)

**Comment by ildyria** [comment]
> my old single account from v3 looks like stuck to exists forever, i can't delete, change rights or password for this account.

Your account from v3 (thus admin) had its information transfered to the Config table and subsequently to the User with id 0. We ensure that this user is not deleted for security reasons as this is the admin one. However you can still rename it/change its login/password as you did in the v3 in the basic Settings panel.

I don't understand the problem. :thinking:

**Comment by imThief** [comment]
Thank you for so swift answer! :)

I'm do the following:
1. Logging in with account "from v3"
2. Going to settings (gear icon at top left -> Settings)
3. Entering my current "from v3" username/password and and the new Username and Password/Confirm in the "Your username and password will be changed to the following" fields, and then pressing "Change login" button
4. Now i can enter with new credentials, supplied in the form, but also i still can login with old credentials too - that is the problem

Maybe something i'm doing wrong?

**Comment by ildyria** [comment]
> but also i still can login with old credentials too

Okay, THAT is a problem. :)

**Comment by imThief** [comment]
Thanks for confirmation! ^_^ I will help with anything you need, tests/info/access to site - just ask.

**Comment by ildyria** [comment]
You can disable that connection pretty easily. Go to Settings -> More settings. Replace the two strings for `username` and `password` by something random and you should be fine. :p

**Comment by imThief** [comment]
Many thanks for advice, i noticed these fields in settings but wasn't sure that they belongs exactly to "this" account... Now i got hashes from database (from user with id 0 - supposed that it is the admin), replaced existing values on settings page with those i got from database and it works! Now old credentials are incorrect (as it suppose to be) and i can login with admin rights only with my new credentials, thanks! :)
Issue is resolved for me, but i still will be glad to help if my assistance is still need for you.
