### ISSUE TITLE
Search in Lychee database

### ISSUE THREAD

**Issue by ghost** [LycheeOrg/Lychee#997]
I did some test on search in Lychee. I tried to search on Camera type or date (I want to search on all the photos taken with a iPhone) But this not possible. However you can search on Title or Tag. 
My question is: Is it possible to extend the search to other items in the EXIF data?
Thanks, Peter

**Comment by ildyria** [comment]
Only if you edit the Search module:
https://github.com/LycheeOrg/Lychee/blob/10927c6de9912284179ff88e4e7bba8a9aeeba00/app/Actions/Search/PhotoSearch.php#L54-L57

**Comment by ghost** [comment]
Thanks. i adjusted the file and it works.

**Comment by ildyria** [comment]
If you wish, you can also open a Pull Request and we will merge this into Lychee default behaviour. :)
This will make it easier for you when you want to update your installation with the latest version.

**Comment by ghost** [comment]
Never done this before. But  I can give it a try😊.
